test(react-ui): use package @skbkontur/react-props2attrs
skbkontur/retail-ui pull request #2078
Opened 2020-07-24 13:05 UTC by lossir

Перевёл скриншотные тесты на `@skbkontur/react-props2attrs`.

Пытался сразу втащить и в валидации и в react-ui-testing, но не осилил. Нужен специалист.

2020-08-03 13:19 UTC, lossir commented
@zhzz Забыл поставить WIP. На этой ветке я экспериментировал.
Ещё планирую здесь же и в селениумных тестах пакет заюзать. Чтоб два раза не вставать.

2020-08-03 14:20 UTC, zhzz commented
Я давненько уже хочу предложить, не запрашивать ревью, пока PR не готов, но все время забываю.

2020-10-08 07:56 UTC, zhzz requested changes
Ура, сторибук в тестовом режиме перестанет тормозить! 🎉

2020-10-08 07:56 UTC, zhzz commented on packages/react-ui/.storybook/preview.tsx
> +  return ['data-tid', 'data-testid'];
Остальные компоненты поди сами их прокидывают)

2020-10-08 07:56 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.tsx
> -        data-tid="SidePage__root"
Дата-тиды в сами компоненты были добавлены не только для наших тестов, но и для пользователей. Они могут их использовать и не иметь возможности или желания применять props2attrs. 

Их во всех компонентах стоит оставить.

2020-10-08 07:56 UTC, zhzz commented on packages/react-ui/package.json
> +    "@skbkontur/react-sorge": "0.1.0",
Сам Зорге же не нужен, его props2attrs подтянет.

2020-10-08 08:40 UTC, lossir commented on packages/react-ui/.storybook/preview.tsx
> +  return ['data-tid', 'data-testid'];
Сами?

2020-10-08 08:43 UTC, lossir commented on packages/react-ui/package.json
> +    "@skbkontur/react-sorge": "0.1.0",
В preview.tsx используется хелпер из зорге.

2020-10-09 09:58 UTC, zhzz reviewed
Остальные изменения с компонентах/историях/тестах наверное тоже уже не нужны?

2020-10-09 10:11 UTC, lossir commented
> Остальные изменения с компонентах/историях/тестах наверное тоже уже не нужны?

Не очень понял, о каких изменениях речь?

2020-10-09 10:54 UTC, zhzz commented
> > Остальные изменения с компонентах/историях/тестах наверное тоже уже не нужны?
> 
> Не очень понял, о каких изменениях речь?

Я про изменения в тестах и историях Paging, DropdownMenu, в ToastView.  Нужны ли они еще?

2020-10-12 08:19 UTC, zhzz approved these changes

2020-10-12 10:51 UTC, merged