feat(react-ui): ssr
skbkontur/retail-ui pull request #2103
Opened 2020-08-23 22:50 UTC by lossir

Поддержка SSR

Closes #2068

2020-08-24 11:32 UTC, zhzz commented
Удалось собрать какой-нибудь тестовый стенд?

Я пытаюсь накидать демку в nextjs. Пока нашел еще проблемы с HTMLElement в Popup.

2020-08-24 11:54 UTC, lossir commented
Собирал внутри репы, но не добавил в индекс гита, и благополучно похерил при билдинге контролов.
Скинь, пожалуйста, ошибку что выдаёт `next.js`, и код.

2020-09-01 12:45 UTC, dzekh commented
Просто проверяю связь с тасками в трелло https://trello.com/c/au2FaPZP/1111-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D1%8F%D1%8E-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C-%D1%81-%D0%B3%D0%B8%D1%82%D1%85%D0%B0%D0%B1%D0%BE%D0%BC

2020-09-01 12:47 UTC, dzekh commented
![](https://github.trello.services/images/mini-trello-icon.png) [Просто проверяю связь с гитхабом](https://trello.com/c/au2FaPZP/1111-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D1%8F%D1%8E-%D1%81%D0%B2%D1%8F%D0%B7%D1%8C-%D1%81-%D0%B3%D0%B8%D1%82%D1%85%D0%B0%D0%B1%D0%BE%D0%BC)

2020-09-02 11:58 UTC, rustho commented
Слушай, а зачем плодить еще дополнительный пакет? 
По сути SSR это тот же smoke-test но без запуска в браузере. Может просто добавить в smoke тесты - ssr? 
(предлагаю просто перенести из packages/react-ui-ssr-test в packages/react-ui-smoke-test)

2020-09-02 12:40 UTC, zhzz reviewed
Тест и решение в целом неплохо выглядят. А ты не пробовал еще на сервере вытащить стили из [emotion](https://emotion.sh/docs/ssr#advanced-approach), чтобы они тоже при первом рендере появлялись?

Единственное смущает, что по факту тест не дает 100% гарантии. Может быть такое, что в компоненте небезопасное апи вызывается где-нибудь в конструкторе при определенной комбинации пропов. Это уже тестами не покроешь. Есть одна мысль, что можно еще попробовать. Но это потом. Для начала должно хватить.

2020-09-02 12:40 UTC, zhzz commented on packages/react-ui/lib/client.ts
> +  const vendor = ((navigator && navigator.vendor) || '').toLowerCase();
Кажется, что кода получилось многовато. Почему бы не сделать так, чтобы в ноде переменные `platform`, `userAgent` и `vendor` просто получали пустые строки? Тогда `isMac`, `isWindows` и тд можно будет объявить всего один раз, сразу экспортировать, и даже типы сами выведутся.

2020-09-02 12:40 UTC, zhzz commented on packages/react-ui/lib/client.ts
> +export const isClient = typeof window !== 'undefined';
Я бы предложил назвать флаг `isBrowser`. Так будет более конкретно. Когда встречаешь в коде `isClient`, не сразу понятно о чем речь.

2020-09-02 12:40 UTC, zhzz commented on packages/react-ui/lib/events/tabListener.ts
> +export const tabListener = (): null | TabListener => {
Мне кажется, в этом модуле можно просто сделать проверку внутри конструктора, а остальное оставить как было. Будет значительно проще.

2020-09-02 12:40 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +  return () => {
Тут не совсем понял, почему стала функция возвращаться.

2020-09-17 04:44 UTC, zhzz commented
В качестве еще одного способа тестирования ssr-safe, на обсуждение. Можно обойтись одним только jest'ом:

>\_\_tests\_\_/ssr.test.tsx
```tsx
/**
 * @jest-environment node
 */

import React from 'react';
import ReactServer from 'react-dom/server';
import * as Components from '../index';

const isReactComponent = (o: any) => {...}

describe('SSR Safe', () => {
  Object.keys(Components).forEach(ComponentName => {
    const Component = Components[ComponentName];
    const someProps = {}; 
    if (isReactComponent(Component)) {
      it(ComponentName, () => {
        const element = React.createElement(Component, props);
        expect(() => ReactServer.renderToString(element)).not.toThrow();
      });
    }
  });
});

```

Из особенностей:
- Довольно просто, не требуется лишней инфраструктуры
- Можно автоматом забирать и тестировать все компоненты из индекса
- Сперва нужно отфильтровать из индекса все, что не является компонентом
- У некоторых компонентов есть обязательные пропы. Придется их где-то хранить и передавать в тест

2020-09-17 09:14 UTC, lossir commented
> В качестве еще одного способа тестирования ssr-safe ... только jest'ом ...

Вариант интересный. Но из преимуществ вижу только условную простоту. Т.к. отсутствие инфраструктуры для тестирования, заменится настройками обязательных пропов.
Главное преимущество текущей инфраструктуры в приближённости к реальному проекту с `ssr`. Также это даёт широкие возможности дебага. Можно смотреть сгенерированный код, и проверять его работоспособность в браузере.

2020-09-24 13:29 UTC, zhzz requested changes

2020-09-24 13:29 UTC, zhzz commented on packages/react-ui-smoke-test/react-ui-ssr/package.json
> +    "@emotion/core": "^10.0.35",
Тут в зависимостях не хватает самого "webpack". Без него из папки "react-ui-ssr" ничего не запускается.

2020-09-24 13:29 UTC, zhzz commented on packages/react-ui-smoke-test/smoke.test.ts
> +  it('Render all controls on server side (SSR)', async () => {
Я бы предложил вынести этот тест в отдельный файл, чтобы можно было запускать отдельно от smoke-теста.

2020-09-24 13:29 UTC, zhzz commented on packages/react-ui/lib/SSRSafe.ts
> +export const WindowOrGlobal = _ as {
Вроде не очень хорошо с типизацией получилось. Еще пытаюсь сам понять как правильно.

2020-09-24 13:29 UTC, zhzz commented on packages/react-ui/lib/client.ts
> +const platform = isBrowser ? ((navigator && navigator.platform) || '').toLowerCase() : '';
Можно еще чуть проще.

```suggestion
const platform = ((isBrowser && navigator && navigator.platform) || '').toLowerCase();
```

2020-09-24 13:29 UTC, zhzz commented on packages/react-ui/lib/theming/Emotion.ts
> +import createEmotionServer from 'create-emotion-server';
Почему бы по аналогии с `@emotion/core` не переложить эту зависимость на того, кто пилит у себя ssr?

2020-10-05 05:42 UTC, zhzz commented on packages/react-ui/lib/SSRSafe.ts
> +export const WindowOrGlobal = _ as {
Тип у `WindowOrGlobal` не очень хорош, потому что не включает в себя никаких свойств из реальных Window и global. 
Если вернуться к мысли про [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis), то можно было бы воспользоваться его [поддержкой в ts](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#type-checking-for-globalthis) и сделать свой упрощенный [полифил](https://mathiasbynens.be/notes/globalthis). 

// SSRSafe.ts
```ts
export const globalThat: typeof globalThis =
  (typeof globalThis === 'object' && globalThis) ||
  (typeof global === 'object' && global) ||
  (typeof window === 'object' && window) ||
  Function('return this')();
```
// global.d.ts
```ts
declare var __RetailUiZIndexes: number[];
```

Таким образом, globalThat будет реальным глобальным объектом, с хорошим типом и поддержкой кастомных свойств. Плюс, будет опираться на стандарт globalThis.

![image](https://user-images.githubusercontent.com/4607770/95043758-2ad19880-06f7-11eb-970d-e5416735fa9a.png)

2020-10-05 05:50 UTC, lossir commented on packages/react-ui/lib/SSRSafe.ts
> +export const WindowOrGlobal = _ as {
Крутое решение! Так и сделаю)

2020-10-05 05:54 UTC, lossir commented on packages/react-ui/lib/theming/Emotion.ts
> +import createEmotionServer from 'create-emotion-server';
Сделал

2020-10-05 05:54 UTC, lossir commented on packages/react-ui/lib/client.ts
> +const platform = isBrowser ? ((navigator && navigator.platform) || '').toLowerCase() : '';
Сделал

2020-10-05 06:02 UTC, lossir commented on packages/react-ui-smoke-test/smoke.test.ts
> +  it('Render all controls on server side (SSR)', async () => {
При желание их можно запускать отдельно и так. Но я решил добавить именно сюда, т.к. этот тест подпадает под определение smoke-тестов.

2020-10-05 06:31 UTC, zhzz commented on packages/react-ui-smoke-test/smoke.test.ts
> +  it('Render all controls on server side (SSR)', async () => {
А, ну да, забыл про опцию `jest -t`. 

Но все же, там сейчас сперва неизбежно собирается пакет react-ui, который для ssr не нужен. Плюс отдельные файлы jest запускает параллельно.

2020-10-05 09:50 UTC, lossir commented on packages/react-ui-smoke-test/smoke.test.ts
> +  it('Render all controls on server side (SSR)', async () => {
Вынес в отдельный файл и переименовал старый. Перенёс всё в папку `__tests__`.

![image](https://user-images.githubusercontent.com/2708211/95065015-ec99a080-0719-11eb-82ec-265029a0b38d.png)

2020-10-06 05:52 UTC, zhzz commented on packages/react-ui-smoke-test/react-ui-ssr/src/getPageHTML.ts
> +    <script crossorigin src="https://unpkg.com/react-dom@16.12.0/umd/react-dom.production.min.js"></script>
А зачем понадобилось подключать реакт так, а не в client.js?

2020-10-06 05:52 UTC, zhzz commented on packages/react-ui/SSR.md
> +Контролы поддерживает рендеринг на стороне сервера из коробки. Но для предварительного рендеринга стилей понадобится установить пакеты `@emotion/core` и `create-emotion-server`. И экпортировать `cach
```suggestion
Контролы поддерживают рендеринг на стороне сервера начиная с версии `2.7.0`. Но для предварительного рендеринга стилей понадобится установить пакеты `@emotion/core` и `create-emotion-server`. И импортировать `cache` из библиотеки контролов.
```

Не совсем же получается "из коробки", если нужно самому настраивать извлечение стилей.

2020-10-06 05:52 UTC, zhzz commented on packages/react-ui/SSR.md
> +
Тут как будто не хватает последнего абзаца. Что делать с этими `css`, `ids`? Можеn добавить сюда еще функцию getPageHTML?

2020-10-06 06:43 UTC, lossir commented on packages/react-ui/SSR.md
> +
Этот пример лишь дополняет документацию https://emotion.sh/docs/ssr. А именно показывает где брать `cache` в нашем случае.
Как именно использовать `css` и `ids` уже есть там.

2020-10-06 06:44 UTC, lossir commented on packages/react-ui-smoke-test/react-ui-ssr/src/getPageHTML.ts
> +    <script crossorigin src="https://unpkg.com/react-dom@16.12.0/umd/react-dom.production.min.js"></script>
Забыл перенести в `peerDependencies`.

2020-10-08 07:28 UTC, zhzz commented on packages/react-ui/internal/RenderContainer/RenderContainer.tsx
> +      return this.props && this.props.children;
Еще такой момент нашел. 

`RenderInnerContainer` помимо своих `children`  в портале рендерит рядом проп `anchor`. На сервере сейчас он будет теряться. Например, не будет рендериться все, что завернуто в Tooltip или ValidationWrapper. 

Да и в целом рендерить то, что предназначается для портала просто в месте его вызова может быть не стоит.
Получается разный HTML на сервере и клиенте. Кажется, что этот варнинг в консоли ssr-приложения как-раз из-за этого. 
![image](https://user-images.githubusercontent.com/4607770/95426969-425f8a00-0960-11eb-9089-898f51856cf1.png)

И еще на клиенте у модалки пропадает темный фон.

Есть вариант не рендерить на сервере только сам портал. Тогда все открытые Модалки/Выпадашки будут появляться только на клиенте, что вроде бы не очень страшно. И варнинг это наверное не уберет, но рендеринг на сервере улучшит.

А в остальном больше вопросов нет.

2020-10-08 18:08 UTC, lossir commented on packages/react-ui/internal/RenderContainer/RenderContainer.tsx
> +      return this.props && this.props.children;
Поправил. Там целый ворох проблем вылез. Реакт за раз только один варнинг показывает.

2020-10-09 05:05 UTC, zhzz commented on packages/react-ui/internal/RenderContainer/RenderContainer.tsx
> +      return this.props && this.props.children;
Проп `anchor` в RenderContainer же все еще не рендерится на сервере. Мне кажется, нужно сделать чтобы рендерился.

Про подход `setState({ isBrowser: true })`. Он заставит компонент рендериться на клиенте два раза, вне зависимости от того, был SSR или нет. Это может вызвать просадку в производительности для всех пользователей. 

Думаю, в Spinner его еще можно применить, там внутри только иконка. А вот в RenderContainer, боюсь, оно того не стоит. Учитывая, что в него оборачиваются Modal, SidePage, все выпадашки. У них контент может быть очень большим, и рендерить его лишний раз может быть дорого.

Но, зная, что варнинг должен появляется только при рендере открытых Модалок/Выпадашек, что на сервере не так вероятно в реальном приложении, я бы предложил просто его игнорить, сохранив прежнюю производительность.

2020-10-09 10:28 UTC, lossir commented on packages/react-ui/internal/RenderContainer/RenderContainer.tsx
> +      return this.props && this.props.children;
Да, с использованием `state.isBrowser` просадка в производительности достигала 17% (при 10 компонентах на странице). Изменил реализацию.
Не смог пристроить проп `suppressHydrationWarning`, чтобы варнинг не всплывал. Пока придётся жить с этим.

Однако, сохранив производительность, повышается риск дефектов. React ожидает, что отрендеренное содержимое идентично на сервере, и на клиенте. И прямо говорит, что нет гарантий, что различия будут исправлены автоматически. Рекомендуется считать такие нестыковки ошибками, и исправлять вручную.

[_подробнее_](https://ru.reactjs.org/docs/react-dom.html#hydrate)

2020-10-12 10:40 UTC, zhzz commented
Обнаружил такую ошибку при кликах в тестовом приложении. 

![Screenshot_5](https://user-images.githubusercontent.com/4607770/95737354-fa629f00-0ca0-11eb-83ee-cc001685bea9.png)

Закинул правку. Наконец понял, зачем нужны эти `<noscript data-render-container-id=".." />`

2020-10-12 10:41 UTC, zhzz submitted a review, later dismissed

2020-10-12 10:50 UTC, rustho approved these changes

2020-10-12 10:50 UTC, rustho commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
а точно стоит сюда иконочки импортить из внешнего приватного пакета?

2020-10-14 07:21 UTC, zhzz commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
Почему бы и нет? Пока у иконок нет своих подобных тестов. Можно считать этот таким, супер-интеграционным.

2020-10-14 07:33 UTC, rustho commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
А у нас вообще есть место где иконки используются, кроме как здесь? Кажется что планировали иконки выпилить вообще отовсюду

2020-10-14 07:36 UTC, zhzz commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
В историях только.

2020-10-14 07:37 UTC, rustho commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
так может вообще выпилить к черту (((: В историях можно юзать внутренние реакт-юи иконки

2020-10-14 07:48 UTC, zhzz commented on packages/react-ui-smoke-test/react-ui-ssr/src/App.tsx
> +import EditIcon from '@skbkontur/react-icons/Edit';
![image](https://user-images.githubusercontent.com/4607770/95959170-8ef10c80-0e1b-11eb-9c2b-ae0940f68801.png)

2020-10-14 13:29 UTC, zhzz commented
Выкатил беты
 ```
@skbkontur/react-ui@2.7.0-beta.0 
@skbkontur/react-ui-validations@1.4.0-beta.0 
```

2020-11-26 05:15 UTC, zhzz commented
Обнаружил еще проблему с порталами. В предыдущей версии можно было заметить на тестовой странице для ssr, что SidePage ломал идущий за ним Spinner. Поправил комитом 19a909b.

2020-12-18 07:21 UTC, zhzz approved these changes

2020-12-23 10:05 UTC, zhzz approved these changes
качу

2020-12-23 12:43 UTC, merged