fix(Autocomplete): delete inline-span, add flex, add stories
skbkontur/retail-ui pull request #2104
Opened 2020-08-24 10:33 UTC by dimohqa99

Изменил inline-flex на flex, чтобы можно было задать ширину в процентах. 
https://github.com/skbkontur/retail-ui/issues/1713

2020-08-25 10:05 UTC, lossir requested changes
В текущей реализации возможен такой эффект.
На скриншоте, ширина `50%` прокидывается в `Input`, из-за чего он получает ширину `50%` от `50%`...

![image](https://user-images.githubusercontent.com/2708211/91160995-903b6e00-e6e3-11ea-9fdc-e1406cee8a9f.png)

---
Необходимо, например, в `Input` передавать ширину 100%.
Либо, переверстать без `span`, но тут уже надо будет разбираться.

2020-08-26 04:11 UTC, dimohqa99 commented
@lossir Переделал. Добавил для input ширину 100% и убрал значение ширины для меню.

2020-08-26 09:29 UTC, zhzz requested changes

2020-08-26 09:29 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +      width: '100%',
Теперь сломался сценарий по умолчанию, когда ширина Автокомплиту не задана. Раньше бралась дефолтная ширина Инпута 250px, сейчас какая-то дефолтная браузерная, она меньше.

![image](https://user-images.githubusercontent.com/4607770/91286757-449ec800-e7a8-11ea-8b4e-2bb621e4790a.png)
![image](https://user-images.githubusercontent.com/4607770/91286800-541e1100-e7a8-11ea-9802-caf80dd57515.png)

2020-09-23 09:09 UTC, dimohqa99 commented
@lossir добавил дефолтную ширину, если не задана ширина из props

2020-09-24 05:01 UTC, zhzz requested changes

2020-09-24 05:01 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +        <span style={{ display: 'inline-block', width: this.props.width || defaultWidth }}>
Если в `this.props.width` придет 0, то сработает не так как задумано.

Плюс, дефолтную ширину для инпута по хорошему нужно брать из темы, там есть переменная `inputWidth`. Но, чтобы не подключать Автокомплит к ThemeProvider, проще передать `width: undefined` в `inputProps`, когда Автокомплиту ширина явно не задается. Тогда Инпут внутри себя сам все правильно разрулит.

2020-09-24 07:22 UTC, dimohqa99 commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +        <span style={{ display: 'inline-block', width: this.props.width || defaultWidth }}>
@zhzz Установил для span 100% ширины, чтобы он занимал весь блок, а для инпута теперь передается ширина из props, либо undefined.

2020-09-25 05:53 UTC, zhzz requested changes
Давай соберем все условия в одном месте. Мы хотим, чтобы:
 
 -  автокомплит принимал переданную в пропах ширину (в том числе в процента
 -  автокомплит принимал дефолтную ширину инпута, когда самому автокомплиту ширина не задана
 
Под шириной автокомплита имеется в виду ширина его самого внешнего элемента, а не только видимого инпута внутри. Автокомплит не должен быть по умолчанию "100%". Напротив, он должен сохранять поведение инлайн-блочного элемента и принимать ширину содержимого.

Изначально мы уже имели правильное поведение в отсутствии заданной ширины. Остается обеспечить корректную работу всех значений пропа width. Для этого требовалось перенести установку ширины пропом на самый внешний элемент. И поддержать это новшество во внутреннем инпуте, не сломав дефолтное поведение (т.е. с помощью 100% или undefined на инпуте).

2020-09-25 11:01 UTC, dimohqa99 commented
@zhzz Исправил. Добавил тест для ширины с 0, переименовал тест с шириной в процентах.

2020-09-25 11:50 UTC, zhzz requested changes

2020-09-25 11:50 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> -      width: this.props.menuWidth || this.props.width,
Как-то упустил. Это лучше вернуть для совместимости. Да и нет вроде причин тут что-то менять.

2020-09-28 07:47 UTC, dimohqa99 commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> -      width: this.props.menuWidth || this.props.width,
Если вернуть, то при ширине равной 50%, элементы меню будут шириной 50% от ширины инпута.

![image](https://user-images.githubusercontent.com/36468649/94404525-63262380-0199-11eb-8bbd-ff0564cd5799.png)

2020-09-28 07:52 UTC, dimohqa99 commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> -      width: this.props.menuWidth || this.props.width,
@zhzz Сейчас это условие отрабатывает именно так как мы обсудили выше. При undefined, меню занимает всю ширину инпута. Если задаем ширину меню, то она выставляется.

2020-09-28 11:04 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> -      width: this.props.menuWidth || this.props.width,
Да, точно, просто вернуть нельзя. Но также есть ситуация, когда ширина Автокомплиту задана меньше, чем фактическая длинна какого-то элемента в списке. Тогда результат прежний и нынешний будет разным:

| Раньше | Теперь |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4607770/94424574-e0ef2c80-01a3-11eb-9d2b-eaf90f71b8c5.png) |  ![image](https://user-images.githubusercontent.com/4607770/94424339-7dfd9580-01a3-11eb-8e63-b62ae9260c41.png)  |

2020-09-29 08:52 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> -      width: this.props.menuWidth || this.props.width,
Наверное, можно добавить расчет текущей ширины Автокомплита, подобно тому, как это делает DropdownContainer, например. И подставлять это значение вместо menuWidth, если он не задан.

2020-10-22 11:35 UTC, rustho commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +      width: this.props.width && '100%',
дефолтное поведение в таком случае изменится, по дефолту должно быть 250px

2020-10-22 11:35 UTC, rustho commented on packages/react-ui/components/Autocomplete/__tests__/Autocomplete-test.tsx
> +      width: '100%',
а зачем?

2020-10-22 11:44 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +      width: this.props.width && '100%',
Это когда width не задан? Ширина ведь и останется той, которая у инпута по дефолту.

2020-10-22 11:51 UTC, zhzz commented on packages/react-ui/components/Autocomplete/__tests__/Autocomplete-test.tsx
> +      width: '100%',
🤷‍♂️

2020-10-22 12:09 UTC, rustho commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +      width: this.props.width && '100%',
ну в таком случае width тут вообще не нужен.

2020-10-23 09:28 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +      width: this.props.width && '100%',
нужен, но решили переделать на использование переменной из темы для наглядности

2020-10-27 11:14 UTC, zhzz approved these changes

2020-10-27 12:34 UTC, merged