feat(Tooltip): add manual control
skbkontur/retail-ui pull request #2115
Opened 2020-09-02 12:57 UTC by YakOFF19

Добавлено состояние 'manual' в триггере.
Реализованы методы show и hide для управления открытием/закрытием.
Добавлен пример использования в пункте про триггеры.

Closes #914

2020-09-03 07:30 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +   */
Это лишнее. `Typescript` уже указывает на доступность

2020-09-03 07:30 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    if(this.state.opened) return;
Не хватает пробелов. Надо настроить `prettier` в `IDE`.

2020-09-03 07:30 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.md
> +class UseManualTooltip extends React.Component {
Для изменения в доках тоже есть отдельный скоуп - `docs`

2020-09-03 07:44 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +   */
Этот коммент позволяет методам появляться в доке, под списком пропов. Можно туда дописать про условия и режим, в котором они работают.

![image](https://user-images.githubusercontent.com/4607770/92085849-d0d17080-ede2-11ea-83be-ee3078d35b18.png)

2020-09-03 07:50 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +   */
Точно, дока) Да, в таком случае стоит добавить описание.

2020-09-03 11:17 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +   */
@YakOFF19, поторопился зарезолвить?

2020-09-14 06:29 UTC, rustho approved these changes

2020-09-14 06:52 UTC, zhzz commented
Там в issue пришли к тому, что можно разрешить ручное управление во всех режимах, кроме opened/closed.

2020-09-21 05:46 UTC, zhzz requested changes
Кажется, что для полноценного использования новых методов еще не хватает пропа `onClose`, по аналогии с `onOpen`. Иначе никак не отследить текущее состояние и не реализовать кнопку `toggle`, например.

2020-09-21 05:46 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +      throw new Error('Invalid trigger specified: ' + this.props.trigger);
Кидать ошибку довольно жестко в такой ситуации. Если это случится во время рендера, то все приложение может упасть. Лучше просто вывести сообщение в консоль через функцию `warning` (уже используется в тултипе). И текст сообщения можно уточнить, написав что этот метод не работает в этом режиме.

2020-09-21 05:46 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.md
> +      {state.trigger === 'manual' ? <UseManualTooltip /> : null}
Для того, чтобы сместить акцент на ручной тултип, когда он демонстрируется, можно еще остальные тултипы скрыть на это время.

2020-09-23 05:29 UTC, zhzz requested changes
Крутяк. Но onClose при включении триггера `closed` почему-то не срабатывает.

И еще было бы здорово добавить юнит-тестов на новые методы и пропы.

2020-09-24 04:29 UTC, zhzz approved these changes
👍

2020-09-25 11:55 UTC, zhzz approved these changes

2020-09-28 11:15 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +   * @public Программно открывает тултип (кроме тиггеров 'opened' и 'closed').
Неправильный синтаксис `JSDoc`. Из-за этого на витрине не рендерится описание метода.
[Здесь](https://jsdoc.app/) можно почитать доку о `JSDoc`. 

| ![image](https://user-images.githubusercontent.com/2708211/94423827-b2248680-01a2-11eb-9c58-4d2e74e7f7e9.png) |
| --- |

2020-09-28 11:15 UTC, lossir commented on packages/react-ui/components/Tooltip/Tooltip.md
> +Тултип может располагаться в одной из 12 позиции и триггериться одним из 8 способов
Здесь написано 8 способов, но в селекте ниже всего 7 вариантов (а до этого было 5 и 6 соответственно).
Восьмой триггер есть в последнем примере, но он не назван "триггером". Просто невзначай говорится "_... прицеплять тултип ... с помощью anchorElement..._".

Предлагаю исправить описание здесь, и ниже. Чтобы избавить от путаницы.

2020-10-01 05:09 UTC, lossir reviewed
Пример с триггером `hoverAnchor` всё равно очень громозкий. Предлагаю максимально его упростить. Что-то такое, думаю, будет в самый раз.
```javascript
import { Tooltip, Button } from '@skbkontur/react-ui';

<>
  {state.anchor && (
    <Tooltip anchorElement={state.anchor} render={() => 'Hello React'} trigger="hoverAnchor" />
  )}
  <Button
    onMouseEnter={event => setState({ anchor: event.target })}
    onMouseLeave={() => setState({ anchor: null })}
  >
    trigger = hoverAnchor
  </Button>
</>;
```

2020-10-01 05:23 UTC, zhzz commented
@lossir Упростить можно, но в твоей версии изначальный смысл немного теряется. Он был частично и в том, что anchor'ов может быть много, а Тултип один. Тут либо добавить еще anchor'ов, либо заменить пляски с onMouseEnter/onMouseLeave на ref, чтобы не смущали.

2020-10-01 07:10 UTC, lossir commented
@zhzz Можно что-то такое сделать:
```javascript
import { Tooltip, Button, Gapped } from '@skbkontur/react-ui';

const setAnchor = event => setState({ anchor: event.target });
const removeAnchor = () => setState({ anchor: null });

<>
  {state.anchor && <Tooltip anchorElement={state.anchor} render={() => 'Hello React'} trigger="hoverAnchor" />}
  <Gapped>
    <Button onMouseEnter={setAnchor} onMouseLeave={removeAnchor}>
      1
    </Button>
    <Button onMouseEnter={setAnchor} onMouseLeave={removeAnchor}>
      2
    </Button>
  </Gapped>
</>;
```

Либо что-нибудь придумать с рефами (я придумать не смог).

2020-10-01 09:04 UTC, zhzz commented
Постойте-ка. Триггер `hoverAnchor` не завязан на прямую на проп `anchorElement`. Он может использоваться и без него. Это обычный триггер, который, видимо, просто забыли добавить в первый пример. Давайте может добавим его туда, а второй пример оставим как был, в нем в таком все-таки есть смысл.

2020-10-01 09:39 UTC, lossir commented
@zhzz Извиняюсь. Видимо, я всех запутал с самого начала, касательно 8-го триггера. Его можно тупо добавить в список к остальным.
Если последний пример показывает работу с пропом `anchorElement`, то он всё равно перегружен. Больше похоже на копипасту. Кажется, что упрощённый вариант (https://github.com/skbkontur/retail-ui/pull/2115#issuecomment-701936890) вполне подойдёт. Но в текущем ПРе можно не трогать.

2020-10-01 12:43 UTC, YakOFF19 commented
В общем, `anchorElement` откатил до прежней реализации. Просто добавил `hoverAnchor` в пример с триггерами.

2020-10-01 19:40 UTC, lossir approved these changes

2020-10-02 05:32 UTC, merged