feat(Toggle): add prop 'child' and 'childPosition'
skbkontur/retail-ui pull request #2121
Opened 2020-09-04 10:47 UTC by YakOFF19

Добавлена возможность передать child.
Дочерний элемент может быть расположен справа или слева от тоггла.
Значение переключается в том числе при клике по child.

Closes #1723

2020-09-04 11:56 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +      });
Здесь функция `cn()` уже и не нужна:
```javascript
const captionClass = childLeft ? jsStyles.captionLeft(this.theme) : jsStyles.captionRight(this.theme);
```

Но для наглядности, я бы предложил такой вариант:
```javascript
[jsStyles.captionLeft(this.theme)]: childPosition === 'left',
[jsStyles.captionRight(this.theme)]: childPosition !== 'left',
```

2020-09-04 11:56 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +  child?: React.ReactNode;
Тут надо использовать специальный проп `children`.
Почитать о нём можно здесь [Composition vs Inheritance](https://reactjs.org/docs/composition-vs-inheritance.html).

Для примера посмотри реализацию чекбокса и радиокнопки.

2020-09-04 11:56 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +export type LablePosition = 'left' | 'right';
Очепятка - `Label`

---

Также, у тебя три разных существительных для обозначения чилдренов:
1. Тип называется `Label...`
2. Проп называется `child...`
3. Класс называется `caption...`

2020-09-04 11:56 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      ${styles.caption()}
Здесь необходимо использовать функцию `cssName` из файла `/lib/theming/Emotion.ts`:
```javascript
${cssName(styles.caption())}
```

<details>
<summary>что за cssName?</summary>   
  
За этим небольшим хаком скрывается целая эпопея:
- акт I (начало) - https://github.com/skbkontur/retail-ui/pull/1846
- акт II (накал) - https://github.com/skbkontur/retail-ui/issues/1952
- акт II (кульминация?) - https://github.com/skbkontur/retail-ui/compare/fix-styles-3
- акт III - ...

Увлекательное чтиво))

</details>

2020-09-04 12:22 UTC, YakOFF19 commented on packages/react-ui/components/Toggle/Toggle.tsx
> +      });
Вообще изначально и использовал второй вариант, а убирал чтоб подчистить)

2020-09-08 08:30 UTC, lossir reviewed
Предлагаю добавить пример в `Toggle.md`.

Ещё текст коммита "устарел", касательно названий пропов. К тому же, проп`children` доступен всегда. Просто сейчас ты начал его использовать. Поэтому текст коммита стоит заменить на что подобное:
```feat(Toggle): add caption support by using `children` ```

Скриншотные тесты тоже не помешали бы. Надо бы потестировать базовую линию, и многострочный вариант, ко всему прочему.

2020-09-08 08:30 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +  childrenPosition?: 'left' | 'right';
Давай заменим на `captionPosition`. Чтобы абстрагироваться от реализации.

2020-09-08 08:30 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      ${cssName(styles.childrenCaption())}
Тут я криво посоветовал. Мой косяк.

Дело в том, что функция `cssName()` возвращает строку - имя класса с точкой.
И в итоге этот `css` код будет выглядеть так:
```css
.react-ui-p3wy1a {
    padding-left: 10px;
    .react-ui-118p1ou
}
```
Надо удалить эти строчки(167, 174), и добавить класс `caption` первым аргументом в функцию `cn()`
```javascript
...
const childrenCaptionClass = cn(jsStyles.caption(), {
    [jsStyles.captionLeft(this.theme)]: childrenPosition === 'left',
...
```

2020-09-09 11:47 UTC, YakOFF19 commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        {childrenPosition !== 'left' ? childrenCaption : null}
В этом месте было бы логично, но здесь не только когда указан right но и когда всё что угодно другое.

2020-09-09 12:01 UTC, YakOFF19 commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        {childrenPosition !== 'left' ? childrenCaption : null}
Либо сделать 'right' | undefined

2020-09-09 19:58 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        {childrenPosition !== 'left' ? childrenCaption : null}
Добавить дефолтное значение для `captionPosition` в `defaultProps`. Тогда можно будет убрать `?` в интерфейсе `ToggleProps`.

2020-09-10 09:09 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        <label className={cn(jsStyles.wrapper(this.theme))}>
Элемент `label` внутри `label` не стоит использовать. Такое вложение запрещено [спецификацией](https://www.w3.org/TR/html52/sec-forms.html#the-label-element).
> Content model:
Phrasing content, but with no descendant labelable elements unless it is the element’s labeled control,
**and no descendant label elements.**

 Следовательно браузеры будут пытаться интерпретировать такой код "по-своему".

 Используй `span`.

2020-09-10 09:31 UTC, YakOFF19 commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  caption() {
мне кажется можно оставить caption по аналогии с реализацией checkbox

2020-09-10 12:49 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        <span className={cn(jsStyles.wrapper(this.theme))}>
Здесь `cn()` уже не надо использовать, т.к. класс всего один.

2020-09-10 18:22 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.md
> +  </Toggle>
Давай заменим на что-то более лаконичное и ожидаемое. Например:
```jsx
<Toggle checked={state.checked} onValueChange={toggle} captionPosition="left">
  <span>Показывать уведомления</span>
</Toggle>
```

Лучше использовать `span`, т.к. вариант с `div` немного сбивает с толку:
| ![image](https://user-images.githubusercontent.com/2708211/92777129-5348ca00-f3b9-11ea-9bc3-9bc5113792e3.png) |
| --- |
  
К тому же, спецификации не предполагают использование блочного `div` внутри строчных `label` и `span`.
Хоть в том же тогле есть такой косяк, не стоит учится плохому) Однажды мы это переверстаем.

2020-09-10 18:22 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.md
> +В компонент можно передать `children`, который будет отбражаться рядом с переключателем.
```suggestion
В компонент можно передать `children`, который будет отображаться рядом с переключателем.
```
тут просто очепятка

2020-09-11 05:31 UTC, YakOFF19 commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      display: table-cell;
не копипаст, нужен) вручную там подбирал для правильного позиционирования.
Но прикольно что сошлось.

2020-09-11 09:19 UTC, rustho commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      padding-right: ${t.toggleLabelGap};
тут наверное правильней будет toggleCaptionGap

2020-09-11 12:48 UTC, lossir commented on packages/react-ui/components/Toggle/__stories__/Toggle.stories.tsx
> +          <span style={{ display: 'block' }}>State:</span>
Правильнее будет тестировать длинное название, которое из-за ограничения по ширине пойдёт в несколько строк. Использования `display: block`, ты просто обходишь "запрет" на `div`, и получаешь точно такой же результат. В итоге тестируется разрыв строки, а надо тестировать перенос сроки.

Если сейчас ввести длинный текст - тогл "скукоживается", т.к. его поджимает caption:
| ![image](https://user-images.githubusercontent.com/2708211/92924507-84290d80-f452-11ea-893c-d67d38806530.png) |
| --- |

Тут дело во флексах. В качестве подсказки прилагаю текст из [спецификации](https://drafts.csswg.org/css-flexbox-1/#box-model), блок `main size`:
> The width or height of a flex container or flex item, whichever is in the main dimension, is that box’s main size. Its main size property is thus either its width or height property, whichever is in the main dimension. Similarly, its min and max main size properties are its min-width/max-width or min-height/max-height properties, whichever is in the main dimension, and determine its min/max main size.

2020-09-11 12:48 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        [jsStyles.wrapperDisabled(this.theme)]: !!disabled,
Так делать не стоит. Класс содержит правила, которые не нужны этому элементу. Это может запутать при изучении кода.
Лучше создать отдельный класс `disabled`, и вешать его на рутовый элемент.
Посмотри реализацию в чекбоксе

2020-09-14 10:24 UTC, lossir reviewed
Осталось совсем по-мелочи)

2020-09-14 10:24 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      }
Это можно заменить на одну строчку в классе `disabled`:
```css
cursor: default !important;
```

2020-09-14 10:24 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
>        cursor: pointer;
Стиль курсора теперь можно перенести в рутовый класс.

2020-09-14 10:24 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  },
Если вынести стиль курсора в рутовый класс, то весь этот класс можно удалить.

2020-09-15 07:44 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  caption() {
Блин, у нас действительно идет разделение на caption и label среди компонентов. Это приведет к путанице. Но похоже, что caption побеждает числом.

```
Проп caption: Button, Dropdown(Menu), TooltipMenu, Loader, Paging, Spinner
Проп label: Fias
Переменные c "Label*": Radio, Switcher, Checkbox
```

Нужно, видимо, принять caption за стандарт, и переименовать переменные в 3.0.0.

2020-09-15 07:55 UTC, zhzz requested changes

2020-09-15 07:55 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        {captionPosition === 'right' ? caption : null}
У нас же теперь flex. Можно управлять порядком `toggle <---> caption` через css (flex-direction или order).

2020-09-15 08:22 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        {captionPosition === 'right' ? caption : null}
Почему бы и нет. Код `js` станет проще, за счёт всего одного `css` класса.

2020-09-21 06:27 UTC, zhzz requested changes
По непонятной пока причине падают старые тесты. Позже попробую разобраться.

2020-09-21 06:27 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      min-width: ${t.toggleWidth};
Учитывая, что верстка флексовая, правильнее будет настроить ширину/сжатие/расширение элементов wrapper и caption через css-свойство `flex`.

Получается, что wrapper не должен сжиматься, а caption наоборот, должен занимать все свободное пространство.

2020-09-21 06:27 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static togglePaddingX = '10px';
Похоже, что это лишняя переменная.

2020-09-21 06:27 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.tsx
> +        style={{ flexDirection: captionPosition === 'left' ? 'row-reverse' : 'row' }}
Стилями все-таки лучше управлять через классы.

2020-09-21 09:14 UTC, YakOFF19 commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static togglePaddingX = '10px';
тогда текст с тоглом будут вплотную
![image](https://user-images.githubusercontent.com/67053828/93750332-be459c80-fc14-11ea-8922-2dd5d4c86a50.png)

2020-09-21 12:20 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static togglePaddingX = '10px';
Не, там же есть `toggleCaptionGap`, ее нужно оставить. Просто эти 10px можно сразу присвоить ей, а не вытаскивать их из `togglePaddingX`, которая по сути больше ни для чего не нужна.

2020-09-23 07:49 UTC, zhzz requested changes

2020-09-23 07:49 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.tsx
> +      [jsStyles.rootRow()]: captionPosition === 'right',
Желательно делать так, чтобы дефолтный стиль применялся в любой непонятной ситуации. Например, если пользователь внезапно передаст null (такое бывает). Мы обычно зашиваем его в классе, который всегда на элементе, т.е. `root`. А дополнительный стиль уже отдельно. 

Кстати, "Row/RowReverse" в именах классов не помогают читающему понять, зачем они нужны. Имя лучше выбирать исходя из его общей функции/назначения, абстрактно от внутренней реализации. Просто "root" и "rootRight" подойдут.

И в caption тоже, лучше сделать один дефолтный класс, и один класс-модификатор.

2020-09-28 11:32 UTC, zhzz commented
Подправил скриншоты DropdownMenu в IE. Они были не совсем корректными. Я не выявил прямой зависимости между их падением и изменениями в Тоггле. Но вроде ничего на самом деле не сломалось.

2020-09-28 11:32 UTC, zhzz approved these changes

2020-09-28 11:40 UTC, lossir commented on packages/react-ui/components/Toggle/__stories__/Toggle.stories.tsx
> +  name: 'with long description',
Название обновил, но не удалил скриншоты для старого название `with two children`.

| ![image](https://user-images.githubusercontent.com/2708211/94427120-0aaa5280-01a8-11eb-9332-1568270f33be.png) |
| --- |

2020-09-28 11:40 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      flex-direction: row;
Для `flex-direction` это значение является дефолтным - [MDN web docs](https://developer.mozilla.org/ru/docs/Web/CSS/flex-direction).
Поэтому, его можно не указывать.

2020-10-01 04:31 UTC, lossir approved these changes

2020-10-01 04:49 UTC, zhzz approved these changes

2020-10-01 08:49 UTC, merged

2021-06-01 19:54 UTC, dzekh commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  caption() {
не сделали?  не переименовали? забыли?

2021-06-02 05:16 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  caption() {
забыли

2021-06-03 04:55 UTC, zhzz commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +  caption() {
Есть задача #2196