fix(Input): fixed wrong right mask position
skbkontur/retail-ui pull request #2127
Opened 2020-09-09 10:04 UTC by YakOFF19

Поправил положение текста инпута и маски.

Fixes #1379

2020-09-11 11:31 UTC, lossir reviewed
Реализовано довольно интересно, но немного мудрёно.
Давай попробуем переложить все вычисления с `js` на `css`?
Используя `inline-flex`, о котором говорили в ПРе про тогл. Код может заметно сократиться и упроститься.

2020-09-11 13:06 UTC, YakOFF19 commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +      <span style={{ display: 'inline-flex' }} className={jsStyles.container()} x-ms-format-detection="none">
да, перекину style)

2020-09-11 14:40 UTC, lossir commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +          style={{ ...style }}
Теперь `style` не модифицируется, а значит можно вернуть как было. Т.е. он будет пробрасываться в `...inputProps`.
Если не хочешь писать колбасу `this.props.style?.textAlign`, то оставь. Тогда можно ещё деструктурировать и `state` до кучи.
```javascript
const { emptyValue, value } = this.state;
```

2020-09-11 14:40 UTC, lossir commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +            <span style={{ color: '#a0a0a0', userSelect: 'none' }}>
Инлайново стили мы пишем только для вычисляемых свойств. Либо, если это "технический" элемент.
Надо вынести это дело в класс. К тому же этот `color` может задаваться через переменную темы `placeholderColor`.

2020-09-14 07:14 UTC, lossir reviewed
Всё чётко. Теперь можешь пересобрать коммиты в один.

2020-09-15 05:19 UTC, zhzz requested changes

2020-09-15 05:19 UTC, zhzz commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +          (style?.textAlign === 'right' ? (
Верстка в обоих случаях довольно похожа. Можно перенести условие во внутрь, чтобы избежать дублирования:

```jsx
<span className={cn(jsStyles.inputMask(this.theme), { [ jsStyles.inputMaskLeft()]: isAlignLeft })}>
  {isAlignLeft && <span style={{ color: 'transparent' }}>{emptyValue.slice(0, value.length)}</span>}
  {emptyValue.slice(value.length)}
</span>
```

2020-09-15 07:07 UTC, lossir commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +          (style?.textAlign === 'right' ? (
Текущий вариант не такой "плотный", и его проще читать. Мне кажется, лучше оставить как есть.

2020-09-15 08:07 UTC, zhzz commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +          (style?.textAlign === 'right' ? (
Можно разбавить плотность выносом длинных выражений в отдельные переменные. И прозрачному элементу тоже свой класс дать, если нужно, и управлять его видимостью от туда.

Но все-таки налицо дублирование кода. Плюс еще один [анти-паттерн](https://medium.com/@cowi4030/optimizing-conditional-rendering-in-react-3fee6b197a20), хоть в этом случае он и не сильно вредит.

2020-09-15 08:34 UTC, lossir commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +          (style?.textAlign === 'right' ? (
Сохранение выражений в константы кажется оптимальным вариантом.

2020-09-16 09:12 UTC, lossir approved these changes

2020-09-16 11:06 UTC, zhzz approved these changes

2020-09-16 11:49 UTC, lossir approved these changes

2020-09-16 11:51 UTC, merged