fix(spinner): fix spinner fallback mini
skbkontur/retail-ui pull request #2134
Opened 2020-09-15 09:39 UTC by rustho

пофиксил размер анимации, теперь работает норм

2020-09-15 11:12 UTC, zhzz commented
![image](https://user-images.githubusercontent.com/4607770/93203533-088ad180-f76e-11ea-846c-7a92987c3f76.png)

2020-09-16 07:59 UTC, zhzz requested changes

2020-09-16 07:59 UTC, zhzz commented on packages/react-ui/components/Spinner/SpinnerFallback.tsx
> +    const size = type === 'big' ? 96 : type === 'normal' ? 48 : 18;
Но ты же этим самым подвинул caption вправо, так как размер иконки увеличился. Теперь он отличается от нормального спиннера.

Плюс, dimmed mini теперь сломался, т.к. там спрайт шириной 16px.

Надо перегенерить все-таки.

2020-09-17 11:30 UTC, rustho commented on packages/react-ui/components/Spinner/SpinnerFallback.tsx
> +    const size = type === 'big' ? 96 : type === 'normal' ? 48 : 18;
перегенерил, йех

2020-09-21 08:03 UTC, zhzz requested changes
Картинка здоровая, 134 KB.

И похоже, что она получилась не зацикленная, анимация дергается на месте склейки. 

Еще стартует с другого места, нежели раньше. И кадров в ней сейчас 120, а не 151 и не 302.

2020-09-21 12:06 UTC, dzekh commented
Миша, а напиши потом сколько времени у тебя ушло на генерацию спрайта, может мы другими более оптимальными средствами настроим экспорт этого всего? Сделаем упрощенный шаблон в фотошопе или в фигме с меньшим количеством кадров и цветов чтоб всем было проще и быстрее.

2020-09-21 12:38 UTC, rustho commented
> Миша, а напиши потом сколько времени у тебя ушло на генерацию спрайта, может мы другими более оптимальными средствами настроим экспорт этого всего? Сделаем упрощенный шаблон в фотошопе или в фигме с меньшим количеством кадров и цветов чтоб всем было проще и быстрее.

Да это дичь, день чистого времени точно ушло. Просто надо найти какой-нибудь тул, который свг анимацию в спрайт превращает и всё. Потому что сейчас я сделал видосов 7, сделал гифок штук 30 наверное, и спрайтов штук 50 ): Короч сложно

2020-09-21 12:54 UTC, zhzz requested changes
138KB!!!11 😱

2020-09-23 03:55 UTC, zhzz approved these changes

2020-09-23 07:24 UTC, merged