PR по изменениям в TokenInput
skbkontur/retail-ui pull request #2143
Opened 2020-09-21 08:09 UTC by YakOFF19

Можно редактировать выбранный токен.
При переходе к редактированию или наборе нового значения в инпуте выделение со всех токенов снимается.
Во время набора в инпуте в меню выделяется первый элемент, либо полностью соответствующий введённому значению. При этом теперь по Enter вводится выделенный пункт, а дефолтные разделители запятая и пробел.

Closes #2112 #1879 #1187 #1878

2020-09-23 13:36 UTC, zhzz requested changes
1. Судя по макетам, инпут редактирования с длинным текстом внутри должен уметь подстраиваться по высоте, а не прокручивать текст внутри себя.  Я бы попробовал использовать textarea для этого.

2. Еще заметил такой момент. Бывает что инпут, который для добавления токенов, переносится один на новую строку. В такой ситуации, при начале/конце редактирования существующего токена, высота всего ТокенИнпута скачет. Возможно, стоит подумать об использовании отдельного поле для редактирования токенов.

![4e41d7ac-e1e2-4179-a486-0fcfb0902231](https://user-images.githubusercontent.com/4607770/94018969-a9ab0500-fdca-11ea-88ab-94a6ced43d4b.gif)

3. И похоже все-таки можно разделить отдельные правки по коммитам. Это нужно и для удобства ревью и для того, чтобы все они попали в changelog. Вроде бы четко отделяются "подсветка первого элемента", "сброс активных токенов" и "редактирование токенов". Первые две можно пометить фиксами, последнюю - фичей.

2020-09-23 13:36 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  changeableTokenIndex: number;
Лучше назвать `editingTokenIndex`. "сhangeаble" больше говорит о "возможности редактирования", чем о текущем состоянии "редактирование".

2020-09-23 13:36 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    if (prevState.inputValue !== this.state.inputValue || this.state.changeableTokenIndex >= 0) {
Насколько понял, эта новая проверка не очень нужна, ведь inputValue меняется и в момент начала редактирования.

2020-09-23 13:36 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
Лучше сделать `onDoubleClick` на токене вместо этого всего.

2020-09-23 14:26 UTC, YakOFF19 commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
там уже есть `onClick` на элементе, поэтому `onDoubleClick` не срабатывает как надо

2020-09-23 15:05 UTC, YakOFF19 commented
Тогда и инпут ввода можно на такой случай с textarea делать
> Судя по макетам, инпут редактирования с длинным текстом внутри должен уметь подстраиваться по высоте, а не прокручивать текст внутри себя. Я бы попробовал использовать textarea для этого.

Просто он будет по сути дублировать все функции инпута. Да и как поступать тогда если что-то в инпут введено и пользователю захотелось в этот момент редактировать токен - два инпута не очень будет. В обоих случаях наверно можно подставлять на время редактирования какой-нибудь "недотокен" вместо инпута ввода, а после возвращать обратно.
> Возможно, стоит подумать об использовании отдельного поле для редактирования токенов.

2020-09-23 19:53 UTC, dzekh commented
Потестил редактирование, получилось круто, мне нравится =)

Ну конечно всё о чем писали выше нужно поправить, и еще вот это:

Когда в режиме редактирования стираешь все символы и продолжаешь нажимать бекспейс фокус перескакивает на последний в списке токен. Дальше ⌫ удаляет его — последний токен и курсор возвращается в редактируемый токен и всё повторяется. Это не логично, когда ты редактируешь не последний токен. 

Я бы предложил реализовать один из двух вариантов: 
1) Пока мы находимся в режиме редактирования не последнего токена — фокус не уходит из поля на другие курсоры при нажатии ⌫ (так же как происходит при нажатии делит например). Бекспейс из пустого поля начинает стирать токены только если редактируемый токен — последний. 
2) С удалением последнего символа редактирование прекращается, токен который редактировали удаляется, фокус переходит на токен который стоял перед редактируемым. Этот вариант проще и логичней, но есть опасность что пользователь не ожидает, и случайно сотрёт всё что стоит перед. Например когда он нажал и удерживает бекспейс, хотел стереть только символы редактируемого, а стер всё вместе с токенами. Но возможно этого не стоит бояться. Либо, если мы можем такую ситуацию отловить — поставить ограничение и не удалять токены пока пользователь не сделает паузу, не отпустит кнопку и не начнет её снова осознанно нажимать. 🤔

Так же странное происходит если в режиме редактирования выделить любой токен: если стёрты все символы — стирается выделенный только что мной токен, если поле не пустое — убирается фокус с токена и стирается символ редактируемого токена. Тут стирание выделенных токенов наверно нужно оставить только если редактируемый токен последний и он пустой. 

Еще один момент, если я редактирую какой-то токен, и выделяю мышью другой и нажимаю ентер — редактируемый превращается в нормальный и фокус остается на нём, а с того что я только что выделил — снимается. Логичней было бы завершать редактирование текущего и сразу переключать на редактирование нового, который я выделил. 

Это мы сразу в аналитике не подумали, но пока не потыкаешь живой компонент, не поймешь чего не хватает. 

Еще вот такая ошибка иногда вылазит:

![image](https://user-images.githubusercontent.com/26383080/94058681-c828f480-fdfa-11ea-87fb-c022cc87c558.png)

2020-09-24 04:43 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
Может удастся победить?

2020-09-24 05:37 UTC, YakOFF19 commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
в основном этим и побеждают)

2020-09-24 07:11 UTC, YakOFF19 commented
Первый вариант мне кажется больше подходит, но предлагаю дополнить: если стёрты все символы, выходить из редактирования - по сути это будет эквивалент удаления токена.
> Пока мы находимся в режиме редактирования не последнего токена — фокус не уходит из поля на другие курсоры при нажатии ⌫ (так же как происходит при нажатии делит например). Бекспейс из пустого поля начинает стирать токены только если редактируемый токен — последний.

2020-10-02 12:47 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
А в чем конкретно проблема? Проверил, `onDoubleClick` вроде срабатывает.

2020-10-02 16:30 UTC, YakOFF19 commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
дважды срабатывал `onClick` когда использовались и `onClick` и `onDoubleClick`

2020-10-05 11:48 UTC, zhzz commented
Мне кажется, что лишняя логика с определением последний токен редактируется или не последний, она ни к чему. Я не вижу особой разницы. Может лучше сделать для всех одинаково? Пока редактируется какой-то токен, другие не удаляются.

А ситуация с одновременным выделением и редактированием разных токенов выглядит в принципе странной. Я бы предложил, пока идет редактирование больше ничего не позволять делать и по потере фокуса (в том числе по клину на другой токен) заканчивать текущее редактирование. Иначе и логика запутанная и артефактов куча может вылезти. Чем проще - тем лучше.

2020-10-05 12:27 UTC, YakOFF19 commented
Мне кажется разница есть. Когда редактируется последний токен пользователь не видит что это именно редактирование, а может ждать поведения как для обычного инпута в котором нажатие ⌫ вызывает выделение и удаление расположенных перед ним токенов.

> Мне кажется, что лишняя логика с определением последний токен редактируется или не последний, она ни к чему. Я не вижу особой разницы.

2020-10-05 12:57 UTC, zhzz requested changes

2020-10-05 12:57 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    this.handleRemoveToken(itemNew);
Удаление токена перед непосредственно редактированием выглядит преждевременным. Пользователю придет `onValueChange` еще до того, как он что-то изменит. А в случае когда он вовсе оставит старое значение после редактирования, придет два `onValueChange`, хотя в этом случае не должно быть ни одного.

2020-10-05 12:57 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    const paddingX = parseInt(this.tokenInputPaddingX, 10) || 0;
```suggestion
    const paddingX = parseInt(this.tokenPaddingX, 10) || 0;
```

2020-10-05 12:57 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static get tokenTextareaPaddingXRight() {
Тут и выше скорее правильней было бы назвать переменную `tokenInputTextareaPaddingLeft`.  Важен префикс "tokenInput", он служит для группировки переменных в документации. Да и логичнее вроде.

2020-10-05 12:58 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const timer = setTimeout(() => {
Закономерно, но что в этом плохого?

2020-10-05 14:28 UTC, zhzz commented
@YakOFF19 А мне почему-то видится наоборот. Раз пользователь сам инициирует редактирование, то у него не должно быть других ожиданий в этот момент. А разное поведение для последнего/непоследнего токенов как раз может внести путаницу.

2020-10-28 06:34 UTC, zhzz commented
Разделил ПР на #2183 и #2189

2020-10-28 06:34 UTC, closed without merging