Theme 8px/menu
skbkontur/retail-ui pull request #2164
Opened 2020-10-08 09:08 UTC by rustho

Добавил переменных для 8пиксельной сетки

2020-10-13 06:02 UTC, zhzz requested changes

2020-10-13 06:02 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  //#endregion
А как же депрекейт переменных перед удалением. Мы же в 2.х это катим. Нельзя так просто удалить.

2020-11-24 05:59 UTC, rustho commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      left: ${parseInt(t.menuItemPaddingForIcon) - 16 - parseInt(t.menuItemPaddingIcon)}px;
произойдет дезинформация, потому что будет работать только для этого отступа

2020-11-24 06:00 UTC, rustho commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  //#endregion
перенес поближе к menu

2020-11-26 09:37 UTC, zhzz requested changes
Конвенция по именованию переменных скачет, где-то `HoverColor`, где-то `ColorHover`.

2020-11-26 09:37 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      left: ${parseInt(t.menuItemPaddingForIcon) - 16 - parseInt(t.menuItemPaddingIcon)}px;
Не, все будет норм, потому что мы применим ее в иконке по назначению. 

Вообще, текущая ситуация выглядит очень странно. Отдельная переменная `menuItemPaddingForIcon` точно не нужна, она может быть высчитана из понятных переменных ширины и отступа иконки. Ее можно задепрекейтить и использовать для отступа в MenuItem, только если она определена пользователем. В иных случаях, расчитывать отступ из иконки.

Вроде можно так выкрутиться.

Имена новых переменных по идее должны быть  `menuItemIconWidth` и `menuItemIconGap`.

И тогда все будет по красоте.

2020-11-26 09:37 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static menuItemPaddingY = '6px 18px '; //hack for don't crash screenshots
Это конечно оригинально, но как такое объяснить пользователям? И если они переопределят одним значением, то все уедет.

Плюс в иконке это не сработало.

Если хочется обойтись двумя переменными, но они не равны в старой теме, то можно завести дополнительные  `legacy` переменные, в которых хранить разницу и добавлять в старой теме. В новой, они будут по нулям. Я так делал в токене.

2020-11-26 09:38 UTC, zhzz commented on packages/react-ui/components/MenuSeparator/MenuSeparator.styles.ts
> +      margin: ${t.menuSeparatorPadding} 0;
Не, все будет норм, потому что мы применим ее в иконке по назначению. 

Вообще, текущая ситуация выглядит очень странно. Отдельная переменная `menuItemPaddingForIcon` точно не нужна, она может быть высчитана из понятных переменных ширины и отступа иконки. Ее можно задепрекейтить и использовать для отступа в MenuItem, только если она определена пользователем. В иных случаях, расчитывать отступ из иконки.

Вроде можно так выкрутиться.

Имена новых переменных по идее должны быть  `menuItemIconWidth` и `menuItemIconGap`.

И тогда все будет по красоте.

2020-11-26 09:39 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      left: ${parseInt(t.menuItemPaddingForIcon) - 16 - parseInt(t.menuItemPaddingIcon)}px;
Не, все будет норм, потому что мы применим ее в иконке по назначению. 

Вообще, текущая ситуация выглядит очень странно. Отдельная переменная `menuItemPaddingForIcon` точно не нужна, она может быть высчитана из понятных переменных ширины и отступа иконки. Ее можно задепрекейтить и использовать для отступа в MenuItem, только если она определена пользователем. В иных случаях, расчитывать отступ из иконки.

Вроде можно так выкрутиться.

Имена новых переменных по идее должны быть  `menuItemIconWidth` и `menuItemIconGap`.

И тогда все будет по красоте.

2020-11-26 09:40 UTC, zhzz requested changes

2020-11-26 09:40 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static menuItemPaddingForIcon = '36px';
![image](https://user-images.githubusercontent.com/4607770/100334209-4b321b00-2ff5-11eb-8443-b7f8b7d3e119.png)

2021-03-02 07:01 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      left: ${parseInt(t.menuItemPaddingForIcon) - 16 - parseInt(t.menuItemPaddingIcon)}px;
Я предлагаю все же переделать этот момент. Есть чуть более логичный способ.

Можно сделать переменную `menuItemPaddingForIcon` вычисляемой на основе `menuItemPaddingX` и предложенных `menuItemIconWidth` и `menuItemIconGap`. Видимо еще понадобится `menuItemIconLegacyMargin` для воспроизведения дополнительного отступа слева в старой теме.

Думал совсем отказаться от `menuItemPaddingForIcon`, но она еще используется в MenuHeader, что дает причину ее оставить.

2021-03-02 07:33 UTC, zhzz requested changes
Состояние disabled испортилось. Нужны !important.
![image](https://user-images.githubusercontent.com/4607770/109607847-acb0db00-7b4a-11eb-8fff-7f9b429c0a93.png)![image](https://user-images.githubusercontent.com/4607770/109607731-7ecb9680-7b4a-11eb-9f37-b8621120f03e.png)


Еще стоит переименовать некоторые переменные, о которых я писал ранее.

2021-03-02 07:33 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      top: ${t.menuItemPaddingY};
Раньше в старой теме значение было `5px`, теперь получается `6px`. Из-за этого поменялись скриншоты c Dropdown.

В 8px-теме все вроде выглядит норм, по макетам, но в старой раньше иконка была на 1px выше. Чтобы лишний раз не ломать скриншоты, предлагаю завести еще одну legacy-переменную:
```js
icon(t: Theme) {
   ...
   transform: translateY(${t.menuItemIconLegacyShift});
}
```

Потом, при удалении старой темы мы удалим и все legacy-переменные.

2021-03-02 07:33 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.styles.ts
> +      padding: ${t.menuPaddingY} 0;
```suggestion
      padding: ${is8pxTheme(t) ? t.menuPaddingY : 0} 0;
```

Из-за новых паддингов поменялось много скриншотов. Мы льем это в мастер, поэтому все-таки стоит этого избегать. Есть такой способ. Я делал специальный хелпер `is8pxTheme` в `lib/theming/ThemeHelpers.ts`. Он позволяет отличить старую тему от 8px. Используя его, можно применить этот паддинг для разных тем в разных местах, и, тем самым, сохранить скриншоты.

2021-03-02 07:33 UTC, zhzz commented on packages/react-ui/internal/Menu/__stories__/Menu.stories.tsx
> +  <Menu>
Еще сюда можно добавить `<MenuHeader/>`. Он оказывается тоже завит от наличия иконки.

2021-03-02 07:33 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static menuHeaderPaddingX = '8px';
Вероятно тут стоит сослаться на `menuItemPaddingX`.

2021-03-04 12:48 UTC, zhzz requested changes
Еще парочка моментов осталась 🙂

2021-03-04 12:48 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      left: ${parseInt(t.menuItemPaddingForIcon) - parseInt(t.menuItemIconWidth) - parseInt(t.menuItemIconGap)}px;
Здесь теперь можно сделать попроще и пологичнее:

`menuItemPaddingX + menuItemIconLegacyMargin`

2021-03-04 12:48 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
>        cursor: default;
Там еще курсор при наведении остается `pointer`. И в background тоже думаю на всякий случай стоит добавить important.

2021-03-09 11:13 UTC, zhzz approved these changes

2021-03-18 10:39 UTC, closed without merging

2021-03-18 10:53 UTC, zhzz commented
Закрыл случайно, залил в #2322