Theme 8px/tooltip
skbkontur/retail-ui pull request #2165
Opened 2020-10-08 10:17 UTC by rustho

добавил переменные к тултипу

2020-11-25 15:11 UTC, zhzz requested changes

2020-11-25 15:11 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.styles.ts
> +      right: ${t.tooltipCloseBtnPadding};
![image](https://user-images.githubusercontent.com/4607770/100245559-fc837300-2f59-11eb-856a-b261ed09d578.png)

2020-11-25 15:11 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +    return this.popupMargin;
В 8px заезжает на элемент. Скорей всего так не должно быть.

![image](https://user-images.githubusercontent.com/4607770/100245776-3b192d80-2f5a-11eb-8793-8369c868bf76.png)

2020-12-01 17:41 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +    return this.popupMargin;
Должно быт так: 
![image](https://user-images.githubusercontent.com/26383080/100776409-55557e80-3426-11eb-9e60-3c0ab8a4b02a.png)

Там похоже отступы сложились.

2021-02-18 07:10 UTC, zhzz requested changes

2021-02-18 07:10 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Крестик полечился.

Но стоит обратить внимание еще на пару других моментов. 

| tooltipPinOffset | tooltipMargin |
|---|---|
| ![image](https://user-images.githubusercontent.com/4607770/108316123-41781800-71de-11eb-83cf-1da6110f70da.png) | ![image](https://user-images.githubusercontent.com/4607770/108316153-4fc63400-71de-11eb-9e07-5541c87d1d8d.png) |

Эти две переменные в коде и в макетах интерпретированы по разному:
- `tooltipPinOffset` в макете считается до середины пина, а в коде до ближнего края пина;
- `tooltipMargin` в макете до кончика пина, а в коде до края тултипа;

Плюс, в макете их значения ссылаются на другие переменные (`popupPinOffset` и `popupMargin`), а их значения в свою очередь нигде в макете вроде не прописаны. Боюсь, Вова мог не знать чему именно они сейчас равны (`16px` и `10px` во всех темах).

В общем, я бы перепроверил с Вовой эти переменные. И синхронизировал их интерпретацию между кодом и макетом. Кажется, что тултип в 8px сейчас ближе к элементу, чем нарисовано:

![image](https://user-images.githubusercontent.com/4607770/108318594-e7795180-71e1-11eb-9de1-b69cd2921934.png)


И имена переменных все-таки тоже стоит сразу синхронизировать, а то путаница страшная.

2021-02-18 10:49 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
`tooltipPinOffset` идеально было бы оставить до середины пина, но можно сделать как в коде, всё равно.
`tooltipMargin` исправлю в макете и сделаю как в коде — до края тултипа, отступ проверю.

А мы не делали чтоб можно было управлять размерами пина? Я чот нее понял в коде вообще как он рисуется.

2021-02-20 09:20 UTC, StathamJason commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
@dzekh переименуй в макете переменные: `tooltipArrowPadding`, `popupArrowPadding`, `tooltipPadding`, `popupPadding` (смотри комментарии в макете 17, 18, 25, 26)


> А мы не делали чтоб можно было управлять размерами пина? Я чот нее понял в коде вообще как он рисуется.

 Добавлю переменную `tooltipPinSize`, чтобы можно было менять размер пина.

> `tooltipMargin` исправлю в макете и сделаю как в коде — до края тултипа, отступ проверю.

Договорились. Ожидаю точный размер для 8px

> `tooltipPinOffset` идеально было бы оставить до середины пина, но можно сделать как в коде, всё равно.

Сейчас проверю получится ли сделать так (до середины пина) и жду значение для `popupPinOffset `

2021-02-24 10:00 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Все переменные в макете переименовал, комментарии зарезолвил.

2021-02-24 11:49 UTC, StathamJason commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
`tooltipPinOffset` решили оставить от края, надо исправить в макете

2021-03-01 09:13 UTC, zhzz requested changes

2021-03-01 09:13 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
А на каких значениях для 8px в итоге сошлись? Сейчас в коде и в макете они отличаются, если аккуратно посчитать.

В коде `16px`  и `10px`. В макетах аналогичные расстояния `19px` и `13px`. Осталось несоответствие.

| tooltipPinOffset | tooltipMargin |
|---|---|
|![Screenshot_25](https://user-images.githubusercontent.com/4607770/109475478-9433b880-7a97-11eb-92cb-e0399562e3b0.png)|![Screenshot_24](https://user-images.githubusercontent.com/4607770/109474984-efb17680-7a96-11eb-82d2-be9e93a67405.png)|

2021-03-01 14:15 UTC, StathamJason commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
@dzekh посмотри плиз. Сейчас просто tooltipPinOffset и tooltipMargin ссылаются на popupPinOffset и popupMargin. У них значения 

> В коде 16px и 10px.

А в макете и правда другие немного. Поэтому скажи какие значения делаем или макет исправляем

2021-03-02 06:11 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Исправлял в макетах и заметил, что немного отличаются отступы у уголков которые торчат вверх и вниз от тех которые вправо и влево. Они отличаются как раз на 3 пикселя.
Если быть совсем точным то нужно сделать так: 
tooltipPinOffsetY = 20 px (округлил чтоб было ближе к сетке — 2,5 модуля)
tooltipPinOffsetX = 16 px

tooltipMargin поправил в макете

2021-03-19 12:30 UTC, StathamJason commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
@zhzz @dzekh я так понимаю tooltipMargin теперь 10px

А что с tooltipPinOffsetY и tooltipPinOffsetX, делаем их одинаковой величины? И если да, то какой, надо на макете тогда исправить и определиться

2021-03-22 05:19 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Еще нашел момент, что из-за особенностей позиционирования тултипа вокруг кнопки, новый `tooltipMargin` выглядит по-другому:

| старая тема (15px) | 8px-тема (10px) |
| - | - |
| ![image](https://user-images.githubusercontent.com/4607770/111943208-c795c000-8af6-11eb-90ee-8ddcab688b5b.png) | ![image](https://user-images.githubusercontent.com/4607770/111943295-f90e8b80-8af6-11eb-866b-b75fb6e962df.png) |

По факту, тултип всегда позиционировался вокруг текста. Видимо и с этим нужно что-то поделать.

2021-03-22 07:55 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Давайте все-таки разделим tooltipPinOffset на две отдельные переменные, может название получше придумать им?

2021-03-22 08:53 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
> Еще нашел момент, что из-за особенностей позиционирования тултипа вокруг кнопки, новый `tooltipMargin` выглядит по-другому:

Видимо нужно сделать 16. Это скорее всего потому, что я выбирал значение от пина, а позже мы выяснили что пин не считается в этом отступе.

2021-03-22 11:44 UTC, StathamJason commented
Добавил новые переменные темы `tooltipPinHorizontalEdgesOffset` и `tooltipPinVerticalEdgesOffset`

Они базируются на соответствующих переменных `Popup`: `popupPinHorizontalEdgesOffset` и `popupPinVerticalEdgesOffset`

При этом переменные `popupPinOffset` и `tooltipPinOffset` еще остаются, так что если кто-то использовал и переписывал их, то ничего не сломается, так как в первую очередь смотрятся эти переменные. Фишка в том, что сейчас по дефолту они будут 0.

2021-03-23 06:05 UTC, zhzz requested changes

2021-03-23 06:05 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static popupPinVerticalEdgesOffset = '16px';
Не очень уверен на счет такого варианта названий. Кажется стало не сильно понятней, но зато довольно громоздко.

Вариант с `popupPinOffset(X|Y)` хоть и тоже не самый понятный, но зато компактный и более-менее в рамках соглашения.

2021-03-23 06:09 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
> ![image](https://user-images.githubusercontent.com/4607770/111943208-c795c000-8af6-11eb-90ee-8ddcab688b5b.png)	![image](https://user-images.githubusercontent.com/4607770/111943295-f90e8b80-8af6-11eb-866b-b75fb6e962df.png)

Пока договорились поменять на `16` в 8px-теме. Чуть позже мы отдельно пофиксим позиционирование в тултипе и вероятно снова подкорректируем этот параметр.

2021-03-23 17:29 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
@dzekh, сделали вертикальное смещение `20px`, но по всем расчетам, чтобы наш план  с выравниванием сработал, должно быть `18px`.

Сейчас в 8px, если сделать позиционирование справа сверху:
![image](https://user-images.githubusercontent.com/4607770/112190565-ef844100-8c26-11eb-8cd6-49e77647a6cd.png)

2021-03-24 11:39 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  }
Сошлись на `18px`

2021-03-24 12:45 UTC, zhzz approved these changes

2021-03-24 12:48 UTC, merged