Theme-8px/hint
skbkontur/retail-ui pull request #2166
Opened 2020-10-08 10:56 UTC by rustho

Добавил переменные для 8пиксельной темы для hint

2020-11-20 08:53 UTC, zhzz requested changes

2020-11-20 08:53 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.styles.ts
> +      max-width: ${t.hintMaxWidth};
Не хватает `;` в конце. В css эти две строчки склеились и не работают.

Еще, остался проп `maxWidth`, который перебивает переменную.

2020-11-20 10:00 UTC, rustho commented on packages/react-ui/components/Hint/Hint.styles.ts
> +      max-width: ${t.hintMaxWidth};
починил всё

2020-11-25 14:48 UTC, zhzz requested changes
Еще в 8px-теме отступ от клюва получился меньше, чем нужно.

![image](https://user-images.githubusercontent.com/4607770/100242969-31da9180-2f57-11eb-83d6-cc75f5c7b3a2.png)

2021-03-04 09:42 UTC, StathamJason commented
Делал ребейз и он почему-то размотал мердж коммит на отдельные

2021-03-09 12:14 UTC, zhzz requested changes

2021-03-09 12:14 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static hintMargin = '2px';
В макете `8px`. И стоит проверить, совпадет ли визуально с макетами.

2021-03-19 12:48 UTC, StathamJason commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static hintMargin = '2px';
да, норм сейчас выглядит

2021-03-23 06:19 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static hintMargin = '2px';
![image](https://user-images.githubusercontent.com/4607770/112102079-8a4e3280-8bc9-11eb-8801-906a9597e866.png)

@dzekh в Хинте сейчас аналогичная проблема. Тоже пока 16px сделать?

2021-03-23 09:42 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static hintMargin = '2px';
да, да

2021-03-23 17:35 UTC, merged