Theme 8px/toast
skbkontur/retail-ui pull request #2167
Opened 2020-10-08 12:41 UTC by rustho

добавил переменных в тост, и он чутка изменился

2020-11-20 08:33 UTC, zhzz requested changes
А старый зачем поменялся?

Новый на макеты не похож:

![image](https://user-images.githubusercontent.com/4607770/99777983-e4b08700-2b34-11eb-9391-61b5c77ffee7.png)

2020-11-20 10:16 UTC, rustho commented
> А старый зачем поменялся?

так как необходимых css свойств не было - пришлось дополнять, из-за этого немного поломались скриншоты.

2020-11-20 14:50 UTC, zhzz requested changes

2020-11-20 14:50 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static toastCloseBtnPadding = '10px';
В макетах была неправильная цифра, мы с Вовой уже поправили. `toastCloseBtnPadding` должна быть 16px.

2020-11-20 14:50 UTC, zhzz commented on packages/react-ui/components/Toast/ToastView.styles.ts
> +        ${parseInt(t.toastPaddingY) + parseInt(t.fontFamilyCompensationBaseline)}px;
Горизонтальные отступы у ссылки получились меньше чем в макетах.

![image](https://user-images.githubusercontent.com/4607770/99812708-9cab5780-2b68-11eb-8444-63cc62136c19.png)

2020-11-20 14:50 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static toastPaddingX = '20px'; //hack for bottom padding
`internal` - невалидное значение.

А про какой хак в комменте речь?

2020-11-23 08:09 UTC, rustho commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static toastCloseBtnPadding = '10px';
16пикселей - и оно будет как на твоем скриншоте сверху. поэтому вернул значение из старой темы

2020-11-24 06:02 UTC, rustho commented on packages/react-ui/components/Toast/ToastView.styles.ts
> +        ${parseInt(t.toastPaddingY) + parseInt(t.fontFamilyCompensationBaseline)}px;
Пофиксил

2020-11-24 12:42 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static toastCloseBtnPadding = '10px';
Речь же про отступ крестика от правого края, который должен быть больше, согласно макетам. Можно же наверное переверстать, чтобы и сверху норм все было.

2020-11-24 12:46 UTC, rustho commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static toastCloseBtnPadding = '10px';
![image](https://user-images.githubusercontent.com/26579566/100095728-c3c19c00-2e7c-11eb-93fd-3cfbcf7e4fa2.png)
отступ сверху и справа -> написано 16px, на самом компоненте 14px. Плюс еще нужно понимать, что на скриншоте отступ от самого крестика

2020-11-24 13:15 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +  public static toastCloseBtnPadding = '10px';
В компоненте сейчас в обеих темах отступ справа от самого крестика - 10px. Должно быть: в новой теме 16px, в старой, думаю, как получится. Сверху из-за коррекции базовой линии может быть +-1px. 
Где недопонимание у нас?

2020-11-26 06:09 UTC, zhzz requested changes

2020-11-26 06:09 UTC, zhzz commented on packages/react-ui/components/Toast/ToastView.styles.ts
> +      padding: ${t.toastPaddingY} ${t.toastPaddingX}
Уменьшился отступ между ссылкой и крестиком.

![image](https://user-images.githubusercontent.com/4607770/100313773-1e6f0b00-2fd7-11eb-9aa0-ea1edc705ebe.png)

Здесь лучше сделать как в хедере модалки. Правый паддинг всего тоста, при наличии креста, расчитывать исходя из размеров и отступов креста.

2020-11-26 15:11 UTC, rustho commented on packages/react-ui/components/Toast/ToastView.styles.ts
> +      padding: ${t.toastPaddingY} ${t.toastPaddingX}
Здесь скорее проблема вообще всех переменных отступов. Можно глянуть что отступ справа должен равняться отступу у крестика справа, что логично. Марджин справа у ссылки идет от правого отступа из-за этого наложения. В итоге написал немного странную формулу, которая как раз отражает что кого надо

2021-03-18 08:11 UTC, StathamJason commented
конфликты в скриншотах походу

2021-03-18 11:10 UTC, zhzz commented
@dzekh в старой теме поменялись базовая линия (как в макете) и отступы (так чуть проще и вроде тоже в лучшую сторону), норм?

| было | стало |
| - | - |
| ![toast_was](https://user-images.githubusercontent.com/4607770/111616965-57d8ba00-8804-11eb-886c-2623e1962a49.png) | ![toast_now](https://user-images.githubusercontent.com/4607770/111616978-5c9d6e00-8804-11eb-8de1-25bb1980e68f.png) |

2021-03-19 11:51 UTC, merged