refactor(styleguide): change styles and improve code
skbkontur/retail-ui pull request #2178
Opened 2020-10-24 13:36 UTC by laion220995

2020-10-26 17:59 UTC, zhzz requested changes

2020-10-26 17:59 UTC, zhzz commented on packages/react-ui/.styleguide/components/IssueList/IssueList.tsx
> -    return componentName.toLowerCase();
Похоже что теперь большинство компонентов в гайдах не находятся и ссылки в гайды на них работать не будут. Стоит, видимо, вернуть toLowerCase к именам компонентов там, где они с `GUIDES_LINK` склеиваются.

2020-10-26 17:59 UTC, zhzz commented on packages/react-ui/.styleguide/components/IssueList/IssueList.tsx
> +              this.hasIssues && (
А если ни одного issue у компонента нет, то Spinner после загрузки пропадает, и весь контент немного скачет вверх. Лучше этого избежать и что-нибудь вывести на его месте в любом случае.

2020-10-27 02:35 UTC, laion220995 commented on packages/react-ui/.styleguide/components/IssueList/IssueList.tsx
> -    return componentName.toLowerCase();
Поправлю

2020-10-27 02:36 UTC, laion220995 commented on packages/react-ui/.styleguide/components/IssueList/IssueList.tsx
> +              this.hasIssues && (
Выведу сообщение "Нет связанных задач"

2020-11-02 02:49 UTC, zhzz approved these changes
Спасибо 👍

2020-11-02 02:49 UTC, merged