feat(MaskedInput): remove mask-char-font
skbkontur/retail-ui pull request #2187
Opened 2020-10-27 07:12 UTC by lossir

Closes https://github.com/skbkontur/retail-ui/issues/2181

2020-10-30 08:46 UTC, zhzz requested changes
Крутая идея использовать этот пробел! А также нравится подход с подменой символа внутри отдельного компонента.

А не получилось сделать новую землю один в один со старой? На скриншотах немного отличается.

2020-10-30 08:46 UTC, zhzz commented on packages/react-ui/internal/MaskChar/MaskChar.tsx
> +    maskCharElement = <span className={jsStyles.char()}>{char}</span>;
Получается, что сейчас любой символ в маске стал шириной с цифру, а это не нужно. В маске могут быть разные символы, в том числе узкие буквы, и при в воде они будут скакать. Нас же волнует только ширина земли.

Вообще, думаю, все остальные символы кроме земли стоит возвращать строками как они есть.

![image](https://user-images.githubusercontent.com/4607770/97676543-a0404700-1ab2-11eb-95cb-6d1c5f78d7f0.png)

2020-10-30 08:46 UTC, zhzz commented on packages/react-ui/internal/MaskChar/MaskChar.tsx
> +      <span className={jsStyles.charExemplar()}>{MASK_CHAR_EXEMPLAR}</span>
Символ земли можно сделать одним HTML-элементом, переделав charLowLine и charExemplar на превдо-элементах `:before` и `:after`. Таким образом Реакту будет меньше работы.

2020-10-30 08:46 UTC, zhzz commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +      .map((_char, i) => (_char === maskChar ? <MaskChar key={i} char={_char} /> : _char));
Наверное через \<MaskChar /> стоит пропускать все, что так или иначе попадает в маску. Потому что земля там может оказаться и просто в качестве предустановленного символа.

![image](https://user-images.githubusercontent.com/4607770/97678164-34aba900-1ab5-11eb-8c4e-6c49379e9f3b.png)

2020-10-30 08:53 UTC, zhzz commented
Еще оказывается, что в том шрифте были кастомные символы точки и тире. Посмотрел через https://www.glyphrstudio.com/online/

Разницу между тире я не нашел, а вот точки отличаются:

| Было | Стало |
| --- | --- |
|![image](https://user-images.githubusercontent.com/4607770/97679485-2199d880-1ab7-11eb-9eb9-e1a2b7c968e3.png)|![image](https://user-images.githubusercontent.com/4607770/97679521-2a8aaa00-1ab7-11eb-89c0-985c8ea5e74e.png)|

@dzekh, норм?

2020-10-30 12:24 UTC, dzekh commented on packages/react-ui/internal/MaskChar/MaskChar.tsx
> +    maskCharElement = <span className={jsStyles.char()}>{char}</span>;
+1

2020-10-30 12:26 UTC, dzekh commented
> Еще оказывается, что в том шрифте были кастомные символы точки и тире.
> @dzekh, норм?

Кажется что стало даже лучше. Апрув.

2020-10-30 12:28 UTC, dzekh submitted a review, later dismissed

2020-11-01 22:22 UTC, lossir commented on packages/react-ui/internal/MaskChar/MaskChar.tsx
> +      <span className={jsStyles.charExemplar()}>{MASK_CHAR_EXEMPLAR}</span>
Если `charExemplar` будет отсутствовать в `html`, то надо будет что-то тестами с тестами. Остальное, думаю, можно попробовать переверстать.

2020-11-01 22:22 UTC, lossir commented on packages/react-ui/internal/MaskedInput/MaskedInput.tsx
> +      .map((_char, i) => (_char === maskChar ? <MaskChar key={i} char={_char} /> : _char));
Правильно понимаю, что это предлагается сделать, чтобы "земля" везде была одинаковой?
Если так, то я не соглашусь. Мне кажется, что "земля" как часть маски должна отличаться от обычной "земли".
К тому же, в текущем варианте невозможно повлиять на отображение символа в введённой части, т.к. это инпут. Поэтому отображение будет дёргаться при вводе.

Хотя, в текущем варианте смежные символы сливаются. Можно попробовать сделать "землю" маски чуть пониже.

| Сейчас | Пониже |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/97813427-ff1be100-1ca9-11eb-8f25-64e26b5c4e7c.png) | ![image](https://user-images.githubusercontent.com/2708211/97813417-f1665b80-1ca9-11eb-8107-665ce8c618bf.png) |

@dzekh помоги =)

2020-11-01 22:23 UTC, lossir commented
Опять стали падать тесты с цветом выделения. Надо будет что-то сделать с ними.

2020-11-02 12:07 UTC, zhzz approved these changes
👍

2020-11-05 08:53 UTC, rustho approved these changes

2020-11-06 07:28 UTC, merged