Theme 8px/popup
skbkontur/retail-ui pull request #2200
Opened 2020-11-05 07:07 UTC by rustho

удалил пропы margin pinOffset - перенес их в переменные темизации.

2020-11-09 06:23 UTC, zhzz requested changes
Норм, только пара вопросов:

1. Не лучше ли сохранить в именах переменных оригинальные названия margin и offset? Вроде они наиболее точно отражают их назначение. Padding - это ведь внутренний отступ в границах самого элемента.

2. Что если так же добавить переменных для pinSize и popupOffset?

2020-11-09 06:23 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static popupArrowPadding = '7px';
Раньше `pinOffset` по дефолту был 16px, а стал 7px.

2020-11-09 09:36 UTC, rustho commented
1) да, можно сделать 
2) добавление popupOffset кажется только запутает переменные

2020-11-10 06:19 UTC, zhzz requested changes

2020-11-10 06:19 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +          size={pinSize || parseInt(this.theme.popupPinOffset)}
```suggestion
          size={pinSize || parseInt(this.theme.popupPinSize)}
```

2020-11-11 06:31 UTC, zhzz approved these changes

2020-11-13 05:11 UTC, merged