Theme-8px/modal add variables
skbkontur/retail-ui pull request #2204
Opened 2020-11-06 10:03 UTC by rustho

добавил переменные
modalPaddingTop
modalPaddingBottom
modalPaddingLeft
modalPaddingRight
modalHeaderFontSize
modalHeaderLineHeight
modalHeaderPaddingBottom
modalFixedHeaderPaddingBottom
modalBodyPaddingBottom
modalFooterPaddingTop
modalFooterPaddingBottom
modalBodyPanelPaddingBottom
modalFooterPanelPaddingTop
modalFooterPanelPaddingBottom
modalCloseBtnPadding

2020-11-10 07:08 UTC, zhzz requested changes
А когда новые значения для 8px-темы подъедут?

2020-11-10 07:08 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      ${cssName(styles.body(t))}& {
Этот стиль применяется где-нибудь?

2020-11-10 07:08 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
А почему `0px`? Там же все равно остается расстояние.

2020-11-10 09:00 UTC, rustho commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
ну потому что сейчас это так, если сделать иначе то поедут скриншоты

2020-11-10 12:03 UTC, rustho commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
этот паддинг не для креста. и в целом он странно себя ведет из-за флоатов. где-то считается от начала креста, где-то начинает считаться от правого края

2020-11-10 12:05 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
Наоборот же. Просто переменная `modalBodyPanelPaddingBottom` сейчас не работает. А когда заработает, то со значением `0px` скриншоты попадают. Потому что Body прилипнет к панели футера.

![image](https://user-images.githubusercontent.com/4607770/98671941-d3b68780-2376-11eb-9503-de3062181e1c.png)

2020-11-10 12:09 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
Верно, паддинг для ModalHeader, но вычислить его можно было бы из переменных креста.

2020-11-10 12:18 UTC, rustho commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
я скорее имею в виду что 110 пикселей это магическая константа. Вычислить её с помощью переменных возможно добавив к ней только другую специфичную константу

2020-11-10 12:42 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
А, сначала не так понял фразу "не для креста".

Для креста он конечно. А для чего же еще? То, что странно ведет - скорей всего фиксится, это отдельный вопрос. Но вычисляется примерно так: `ширина креста` + `горизонтальные паддинги креста` + `какой-нибудь собственный паддинг ModalHeader`, и все.

В гайдах даже что-то есть про этот паддинг хедера.

![image](https://user-images.githubusercontent.com/4607770/98675409-06af4a00-237c-11eb-919f-478953a959ae.png)

2020-11-10 14:06 UTC, rustho commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
понял о чем ты, говоришь. Исправил, но вместе с этим сломалось вот это - здесь написано что они должны быть разными.
![image](https://user-images.githubusercontent.com/26579566/98684124-9e666580-2387-11eb-8c60-56ff1961ef8d.png)

2020-11-11 07:33 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
В общем, проблема в том, что в новой теме поменялось два отступа.

Раньше у боди паддинг был обычный и "additional". Additional добавлялся в двух разных случаях: когда у футера есть панель и когда футера совсем нет. Теперь в этих двух случаях нужны разные значения. При том, несмотря на то, что отступ без футера равен теперь обычному отступу, в старой теме это не так. Нужно это как-то разрулить, чтобы и старая тема нигде не сломалась.

Возможно, поменять как-то текущий набор переменных. И логику их использования, вероятно, тоже.
```
modalPaddingBottom
modalBodyPaddingBottom 
modalBodyPanelPaddingBottom 
```

Первая, кстати, сейчас вообще не используется.

2020-11-11 08:52 UTC, dzekh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
Можем с дизайнерами попробовать договориться и сделать эти отступы одинаковыми. Должно быть норм.

2020-11-11 08:55 UTC, rustho commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static modalBodyPanelPaddingBottom = '0px';
Сделать разные отступы не сильно сложно, но если переменных для отступов будет поменьше - будет только лучше

2020-11-13 05:46 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
Думаю, стоит уточнить у @dzekh некоторые моменты, учитывая #2213. 

1. Сейчас, в контролах почему-то паддинги у креста асимметричные: top/right = 35px, bottom/left = 20px. Так и должно быть? Они формируют кликабельную область.
2. Какой должен быть правый паддинг хедера без креста? Наверное равный `modalPaddingRight `.
3. Может быть не стоит вводить отдельную переменную для охранного поля, а можно переиспользовать там `modalPaddingRight`.

2020-11-13 06:15 UTC, rustho commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
кажется это отдельные задачи вообще. 
Убирать отступ через темизацию вообще не правильно
Изменить значение её в пользу охранного - ок (:

2020-11-13 12:30 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      padding: ${t.modalPaddingTop} 110px ${t.modalHeaderPaddingBottom} ${t.modalPaddingLeft};
Мы с Вовой перетерли в оффлайне и сошлись на том, что горизонтальные паддинги у креста можно сделать одинаковыми, размера modalCloseBtnPadding. А специальное охранное поле не нужно. Пусть хедер упирается в край обводки креста. Таким образом, переменная modalHeaderPaddingRight не нужна, а правый паддинг хедера рассчитывается как closeSize + 2 * modalCloseBtnPadding.

2020-11-18 05:56 UTC, zhzz requested changes
Что еще заметил:

1. `modalFixedHeaderPaddingBottom` используется не там, где нужно.  Сейчас паддинг применяется не в зафиксированном состоянии хедера, а в зависимости от наличия/отсутствия  футера и панели.

2. Остались еще захардкоженные числа в `closeWrapper` и `closeOutline`. В результате чего, outline в 8px-теме немного смещен. А `closeWrapper` в отсутствии хедера может позволить тексту заехать на крестик немного дальше, чем дозволено.

3. Некоторые стили в 8px-теме стали перебиваться другими. Например, перестал работать верхний паддинг футера в зафиксированном состоянии без панели. И верхний паддинг боди в отсутствии хедера. 
4. Верхний паддинг боди в отсутствии хедера захардкожен. Может использоваться `modalPaddingTop`.

2020-11-19 07:13 UTC, rustho commented
> 1. `modalFixedHeaderPaddingBottom` используется не там, где нужно.  Сейчас паддинг применяется не в зафиксированном состоянии хедера, а в зависимости от наличия/отсутствия  футера и панели.

остались неясности, что делать в зависимости от наличия отсутсвия панели. Оставил как в прошлом было (хардкод), но кажется что выглядит это не очень всё равно.

> 3. Некоторые стили в 8px-теме стали перебиваться другими. Например, перестал работать верхний паддинг футера в зафиксированном состоянии без панели. И верхний паддинг боди в отсутствии хедера.

Посмотрел, добавил в одном случае импортант, вроде всё остальное норм выглядит

2020-11-19 11:51 UTC, zhzz commented
> 4. Верхний паддинг боди в отсутствии хедера захардкожен. Может использоваться modalPaddingTop.

Кажись я был не прав. В старой теме modalPaddingTop не подходит, значения разные. Тесты попадали.



> остались неясности, что делать в зависимости от наличия отсутсвия панели. Оставил как в прошлом было (хардкод), но кажется что выглядит это не очень всё равно.

Хардкод не подойдет, т.к. разные значения в разных темах. Либо нормальную переменную заводить, либо какую-нибудь -legacy, если в новой теме все везде одинаковое.



> > 1. Некоторые стили в 8px-теме стали перебиваться другими. Например, перестал работать верхний паддинг футера в зафиксированном состоянии без панели. И верхний паддинг боди в отсутствии хедера.
> 
> Посмотрел, добавил в одном случае импортант, вроде всё остальное норм выглядит

В 8px-теме в основном проблемы
 
![image](https://user-images.githubusercontent.com/4607770/99661710-0bfc4b00-2a86-11eb-8cbc-1f4bb80e247a.png)

2021-03-15 14:21 UTC, StathamJason commented
До моих коммитов были заапрувлены ломающие старую верстку скрины
Сейчас вернул как должно быть

2021-03-19 10:16 UTC, zhzz commented
Добавил legacy-переменных, чтобы вернуть скриншоты, и поправил крестик в соответствии с https://github.com/skbkontur/retail-ui/pull/2204#discussion_r522920497.

2021-03-19 12:58 UTC, zhzz approved these changes

2021-03-19 13:38 UTC, merged