Textarea counter 2208
skbkontur/retail-ui pull request #2211
Opened 2020-11-11 07:25 UTC by tsypilov

https://github.com/skbkontur/retail-ui/issues/2208

Добавлены новые пропы: 
- showCharsCounter?: boolean;
- counterCharsLength?: number;
- counterHelp?: TextareaCounterHelpProps;

Для позиционирования счетчика используется:
- MutationObserver - чтобы определять ширину текстарии(при resize: auto) текстария может быть различной ширины, позиционирование с помощью right не подойдет, тк в этом случае контейнер(label) остается заданой изначально ширины
- ResizeDetector - используется когда Textarea задана в процентах относительно окна, а контейнер сжимается при уменьшении окна

Почему не использовать только ResizeDetector: да можно, но тогда надо давать inline детям детектора, а inline, но тогда появляются проблемы с высотой, а их решение будет еще более громоздким. @zhzz про это все уже знает.

2020-11-19 08:52 UTC, zhzz commented
А `0` по умолчанию в maxAllowedCharsLength это валидный сценарий? Когда указываешь только `showCharsCounter`, он при фокусе показывает 0 и при вводе сразу идет на убыль, хотя лимиты фактически не задавались.

Я еще думаю, не назвать ли `counterCharsLength` как-то созвучно с нативным `maxLength`? Например, `maxAllowedLength` или `maxRecommendedLength`?

2020-11-19 10:35 UTC, tsypilov commented
> А `0` по умолчанию в maxAllowedCharsLength это валидный сценарий? Когда указываешь только `showCharsCounter`, он при фокусе показывает 0 и при вводе сразу идет на убыль, хотя лимиты фактически не задавались.

Ну тут ограничения у меня по макетам не было, поэтому решил, что можно так. 
Возможно @dzekh подскажет точнее :) 

> Я еще думаю, не назвать ли `counterCharsLength` как-то созвучно с нативным `maxLength`? Например, `maxAllowedLength` или `maxRecommendedLength`?

Хотелось, чтобы название пропа отражало именно счетчик, а не ограничение, считаешь лучше переделать?

2020-11-19 13:25 UTC, zhzz commented
Вове нужно демо: [https://textarea-counter.vercel.app](https://textarea-counter.vercel.app)

---
> А 0 по умолчанию в maxAllowedCharsLength это валидный сценарий? 

Есть вариант, исходя из текущей интерпретации счетчика, не ставить автоматом 0, а просто не показывать счетчик пока явно не задано какое-то значение. Так, кажется, лучше будет.

---

> хотелось, чтобы название пропа отражало именно счетчик

Мне просто видится логичным связать как-то эти два пропа. Ведь они очень похожи по смыслу и отличаются только жесткостью ограничения. `maxLength` не разрешает выходить за рамки, а второй - разрешает. Или у тебя тут другое видение? 

В любом случае, словосочетание "counter chars length" скорее звучит как "длина символов счетчика". Это может быть не очень говорящим названием.

---

Еще, вроде, тег section имеет некую свою семантику. [Не велят](https://developer.mozilla.org/ru/docs/Web/HTML/Element/section#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D0%B5) использовать просто как контейнер.

2020-11-23 16:59 UTC, rustho requested changes

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      border-radius: 4px;
А оно точно вообще надо?

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      height: 26px;
Зачем делать такую высоту?

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      display: flex;
Кажется что можно не оборачивать иконку в секцию и тогда это не нужно

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      padding-left: 4px;
почему именно 4? откуда появилось это значение?

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/Textarea.tsx
> +    counterCharsLength?: number;
А нельзя отделаться одной переменной?

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/TextareaCounter.tsx
> +    <section
Как выше заметили секция здесь вообще не к месту

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/components/Textarea/TextareaCounterHelp.tsx
> +    <section className={jsStyles.counterHelp()}>
тут можно использовать span

2020-11-23 16:59 UTC, rustho commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static textareaCounterHeight = '20px';
Используется только в хэлперах, больше не на что ни влияет. 
Ну и вообще кажется что нужно отталкиваться в таких случаях от lineheight или fontsize

2020-11-23 17:25 UTC, tsypilov commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      padding-left: 4px;
Договорились с проектировщиком (Женей), чтобы минус был небольшой отступ слева

2020-11-23 17:26 UTC, tsypilov commented on packages/react-ui/components/Textarea/Textarea.styles.ts
> +      border-radius: 4px;
что именно?

2020-11-23 17:55 UTC, tsypilov commented on packages/react-ui/components/Textarea/Textarea.tsx
> +    counterCharsLength?: number;
Одной переменной нельзя отделаться, тк есть maxLength, он может быть не указан, тк не обязательно текстариа будет с ограничением длины.
Может быть и другая ситуация, если указан maxLength, но отсутствует maxRecommendedLengthCounter(новое название) и showMaxRecommendedLengthCounter={true}

2020-11-23 18:46 UTC, dzekh commented
Если смотреть на то, что выложено [по ссылке](https://textarea-counter.vercel.app/#/Components/Textarea) нужно счетчик вместе с иконкой сдвинуть вправо на 4-6 пикселей и поднять вверх на три. 

Почему сдвинуть вправо — хочется чтоб отступ справа был такой же как до текста слева. Ну и в любом случае хочется ближе, [тут](https://guides.kontur.ru/components/textarea/#13) он поближе к правому краю нарисован.

Вверх — чтобы поставить на одну базовую линию с последней строкой, хоть ее и не видно, но ритм всё равно есть, и она появляется когда много строк. 

Вообще параметры текста счетчика и его отступы должны совпадать с параметрами текстэрии и её отступов и меняться вместе с ними, если они меняются в теме или каким-то другим способом. Это нужно, чтобы всегда стоять на базовой линии последней строки и выглядеть гармонично с набранным текстом. Не знаю может сейчас так и сделано, просто хочу обратить внимание.

2020-11-23 19:00 UTC, dzekh commented
По поводу пропов — тоже кажется ,что одного достаточно. Если указан лимит, показывать счетчик, если не указан — не показывать. Либо, если оставлять два, то сделать так: когда не указан лимит символов можно считать их не в минус. Просто указывать количество введенных символов серым.

2020-11-23 19:50 UTC, dzekh commented
Договорились оставить отступ справа как был из-за того чтоб скролл на маке не перекрывало. А паддинги и скругления у белой подложки сделать по 2px.

2020-11-24 16:48 UTC, lossir reviewed
В целом решение выглядит капитально, но немного запутанно. Хочу предложить несколько "упрощений".

### Наименования

Вариант `maxRecommendedLengthCounter` мне кажется черезчур длинным и подробным. Слово `Recommended` мне кажется однозначно избыточным. Не вижу смысла уточнять, что это "рекомендованная" длина значения, тем более таким длинным словом.
Также, предлагаю не использовать префикс `max`, ведь счётчик длины можно использовать без `maxLength`, и уходить в "минус".  
Если так подробно называть пропы, то свойстсво `maxLength`, например, должно называться `maximumAllowedValueLength`. Но мне кажется такие названия сложнее запомнить и использовать.

Поэтому, предлагаю такие название:
- `lengthCounter`
- `showLengthCounter`
- `counterHelp`\* - с этим названием согласен


### `<TextareaCounter />`
Кажется, если немного переверстать компонент `TextareaCounter`, то можно немного будет "разгрузить" компонент `<Textarea />`, и перенести в него все связанные расчёты.

Пример вертки:
```jsx
<div
  id="root"
  style={{ position: 'absolute', width: textareaWidth, height: textareaHeight }}
>
  <div
    id="counter"
    style={{ position: 'absolute', right: 30, bottom: 30, zIndex: 5 }}
  >
    <span>{length}</span>
    {counterHelp && <span>{counterHelp()}</span>}
  </div>
</div>;
```

Где `textareaWidth` и `textareaHeight` можно получить используя метод `getBoundingClientRect()`:
```jsx
private resizeTextArea = () => {
    ...
    const {
        height: textareaHeight,
        width: textareaWidth
    } = this.node.getBoundingClientRect();
    this.setState({ textareaHeight, textareaWidth });
};
```

В этом случае элемент `div#root` будет всегда повторять размеры textarea, а отступы для паддингов, скроллбара и бордюров переедут на элемент `div#counter`.

При этом наблюдателя за мутациями и метод `resizeTextArea()` можно перенести в сам компонент `<TextareaCounter />`. И ограничиться в итоге всего 3-мя пропами:


```jsx
showLengthCounter && <TextareaCounter
    length={maxLength ?? lengthCounter ?? 0}
    textareaNode={this.node}
    counterHelp={counterHelp}
/>
```

А остальные необходимые расчёты проводить внутри `TextareaCounter`.

---

Также, можно будет избавиться от `counterNode`, т.к. достаточно `textareaNode`. И, вероятно, придётся перейти на `ClassComponent`, чтобы отключать обзёрвер при демонтаже компонента: `textareaObserver.disconnect()` (хотя не проверял, сказывается ли это на производительности).

### `<TextareaCounterHelp />`

Мне кажется, что этот компонент в принципе лишний. Предлагаю пойти другим путём и отдать реализацию хелпера на откуп пользователям.
Т.е. проп `counterHelp` может быть такого типа: `() => React.ReactNode | undefined`. А в документации компонента описать рекомендуемый вариант его использования:
```jsx
<Textarea
    ...
    counterHelp={() => (
        <Tooltip render={() => 'Не больше 200 символов'} pos="right top">
            <HelpDotIcon />
        </Tooltip>
    )}
/>
```
@rustho @zhzz @dzekh Что думаете?

### Проверка орфографии
При тестировании редактируемых компонентов с текстом (input, textarea, contenteditable=true) стоит явно отключать проверку орфографии, т.к. поддчёркивание работает нестабильно, что влияет на тесты.
Это можно сделать с помощью пропа `spellCheck` ([MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#spellcheck))
```jsx
<Textarea
    spellCheck={false}
    ...
/>
```
| Textarea/Textarea with chars length counter/Focus/firefox |
| --- |
| ![image](https://user-images.githubusercontent.com/2708211/100125254-62122980-2e9e-11eb-9c7d-25f96ca63207.png) |

2020-11-26 15:34 UTC, lossir commented
> ### Компонент `TextareaCounterHelp`
> Мне кажется, что этот компонент в принципе лишний.
> ...
> @rustho @zhzz @dzekh Что думаете?

Обсудили и решили, что у пользователя должны быть такие возможности:
1. Быстро использовать дефолтный стиль (по Гайду)
1. Легко кастомизировать подсказку при необходимости

Поэтому, предлагаем, чтобы проп `counterHelp` принимал 2 типа:
```typescript
() => ReactNode | string
```

<details>
<summary>*</summary>

Изначально я отказывался от строки и мы договорились на `() => ReactNode | ReactNode`. Но потом решил, что совсем фигня какая-то =)

---
</details>

При передачи строки, будем просто подставлять подобный код:
```typescript
<Tooltip render={() => counterHelp} pos="right bottom" trigger="click">
    <HelpDotIcon />
</Tooltip>
```
Так мы реализуем первую возможность.


В документации к компоненту надо будет привести вариант кастомизации, например:
```typescript
counterHelp={() => (
    <Tooltip render={() => 'Не больше 200 символов'} pos="right top">
        ❓
    </Tooltip>
)}
```
Так мы реализуем вторую возможность, ведь АПИ тултипа уже всем знакомо.

2020-12-03 16:34 UTC, tsypilov commented
Сделано все, кроме переноса логики размеров и отступов в компонент TextareaCounte.tsx
@lossir знает почему :)

2020-12-17 07:07 UTC, zhzz approved these changes

2020-12-17 07:11 UTC, merged

2020-12-17 07:12 UTC, zhzz commented
@tsypilov, спасибо за PR. Выкатим в 2.11.0