Theme 8px/tooltip kebab menus
skbkontur/retail-ui pull request #2214
Opened 2020-11-13 08:07 UTC by rustho

2020-11-18 07:01 UTC, zhzz commented on packages/react-ui/internal/themes/Theme8px.ts
> +    return this.popupMargin;
У Кебаба в 8px-теме отступ стал 10px вместо прежних 5px. Это законно? Не нашел его в макетах.

| Старая тема | 8px|
|--|-|
| ![image](https://user-images.githubusercontent.com/4607770/99496195-aaf54a00-2995-11eb-9145-600922dd5810.png)| ![image](https://user-images.githubusercontent.com/4607770/99496237-b5afdf00-2995-11eb-9e31-f1447c9cdd9d.png) |

2020-11-18 07:48 UTC, rustho commented on packages/react-ui/internal/themes/Theme8px.ts
> +    return this.popupMargin;
Вот сюда надо @dzekh призвать, про 8px ничего не сказано, оставил наследование от попапа

2020-11-18 11:36 UTC, dzekh commented on packages/react-ui/internal/themes/Theme8px.ts
> +    return this.popupMargin;
Ну логично сделать 8, в старой оставить 5.
Это вот этот отступ?
![image](https://user-images.githubusercontent.com/26383080/99525809-2833b580-29bc-11eb-88d8-a71efaddb498.png)

2020-11-25 11:28 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static kebabBackground = 'inherit';
Тут бы больше подошел `transparent`. Если когда-нибудь попадется родитель с полупрозрачным фоном, то эффект будет неожиданный.

2020-11-27 08:59 UTC, zhzz submitted a review, later dismissed

2021-02-25 12:01 UTC, StathamJason commented
Заапрувленные скриншоты это оно - [pull/2225](https://github.com/skbkontur/retail-ui/pull/2225)

2021-03-01 12:23 UTC, zhzz requested changes

2021-03-01 12:23 UTC, zhzz commented on packages/react-ui/components/Kebab/Kebab.styles.ts
> +        margin-top: -5px;
Поменявшиеся скриншоты - это результат недоконца вмерженных изменений из 2225. Там была [правка](https://github.com/skbkontur/retail-ui/pull/2225/commits/c3d5b138ddcf1da45f487616fa940f7ac2d7e921) на `-4px`, но она потерялась.

2225 ведь уже в мастере, и других правок с иконкой не было, поэтому скриншоты не должны были измениться.

В остальном кажется все норм.

2021-03-03 04:12 UTC, zhzz approved these changes

2021-03-18 11:20 UTC, merged