fix(ComboBox): add an explicit call to focus on the Input
skbkontur/retail-ui pull request #2215
Opened 2020-11-17 20:18 UTC by lossir

_Что-то никак не могу завести пример с валидацией комобокса на [codesanbox](https://codesandbox.io/s/dawn-mountain-pmrdd?file=/src/index.js). Фокус не ставится ни мышкой ни табом. Только по нажатию `Submit`._

Самый просто способ воспроизвести баг, это задать проп `searchOnFocus={false}`. Затем ввести любое значение и нажать `Submit`. 

| Фактический результат | Ожидаемый результат |
| --- | --- |
| ![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/2708211/99441487-bf0b5e00-2939-11eb-82d7-3f9d2e1ec621.gif) | ![ezgif com-gif-maker (7)](https://user-images.githubusercontent.com/2708211/99441714-19a4ba00-293a-11eb-9ec7-838277f72b26.gif) |

Проблема была в редьюсере комбобокса, который не обрабатывал явно фокус по инпуту в 3 из 3 сценариях(!). 
Лишь по какой-то причине, в случае когда `props.searchOnFocus && !state.editing`, фокус всё-таки срабатывал. Я так и не смог разобраться, почему-же он срабатывал. Поэтому для всех сценариев явно добавил `Effect.InputFocus`.

Fixes #1862

2020-11-18 10:25 UTC, zhzz commented
> Что-то никак не могу завести пример с валидацией комобокса на codesanbox. Фокус не ставится ни мышкой ни табом. Только по нажатию Submit.

Похоже какие-то проблемы с react@17 😱

2020-11-18 11:07 UTC, lossir commented
> Похоже какие-то проблемы с react@17 😱

Спасибо, поправил пример)

2020-11-19 04:53 UTC, zhzz commented
На самом деле редьюсер "Focus" должен вызываться в ответ на событие реального фокуса, т.е. уже после него, в обработчике handleFocus. Поэтому явного фокусирования там не было. Это вызвало бы зацикливание.

Сам фокус должен инициироваться в ValidationWrapperInner, через публичный метод контрола. Однако, проблема в том, что у комбобокса он не работает как положено. Т.е. команда на фокус не доходит до реального input, который затем должен испустить событие focusin, которое уже ловит тултип.

Однако, инпут иногда-таки реально фокусируется. Это происходит в глубине Effect.SelectInputText.

2020-11-20 07:49 UTC, zhzz requested changes

2020-11-20 07:49 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +    }
Это вроде не обязательно, потому что `this.input!.focus()` вряд ли сработает еще раз, когда фокус уже есть.

2020-11-20 07:49 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +    this.input?.focus();
Тут есть нюанс. В комбобоксе вместо инпута может рендериться InputLikeText. Он тоже умеет фокусироваться. Поэтому нужно предусмотреть такой случай.

А `this.handleFocus()` далее - уже лишний, потому что он вызовется сам в обработчике фокуса.

2020-11-25 10:47 UTC, zhzz requested changes

2020-11-25 10:47 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      this.setState({ editing: true });
В чем тут логика?

Все же просто. Нужно позвать фокус на this.input или this.inputLikeText в зависимости от того, что из этого сейчас есть.

2020-12-07 05:53 UTC, lossir commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      this.setState({ editing: true });
Да сам не знаю) совсем забыл, что событие всплывает, и, чёт, перемудрил...

2020-12-08 16:23 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
>      this.handleFocus();
Фактически, `this.handleFocus()` больше не нужен. Он сработает сам после фокуса. А этот ручной вызов будет уже дублирующим.

Тесты на enzyme попадали после его удаления потому что там, видимо, `.focus()` на нативных элементах не совсем работает. Если поискать, то все советуют делать `find('input').simulate('focus')` или  `find('input').prop('onFocus')()`.

Так что, думаю, нам стоит подправить тесты.

Учитывая, что у нас там бывает и input и inputLikeText, то можно делать:
```
wrapper.find('input').simulate('focus');
```
и
```
wrapper.find('[tabIndex=0]').simulate('focus');
``` 
соответственно.

Или универсально:
```
wrapper.find(ComboBoxView).prop('onFocus')?.();
```

2020-12-14 11:46 UTC, zhzz approved these changes

2020-12-15 03:05 UTC, merged