build: update all deps
skbkontur/retail-ui pull request #2217
Opened 2020-11-19 15:50 UTC by lossir

2021-03-19 13:33 UTC, zhzz requested changes
В целом выглядит хорошо. Еще не все отсмотрел. Есть парочка предложений.

2021-03-19 13:33 UTC, zhzz commented on packages/eslint-config/.eslintrc
> +    "@typescript-eslint/explicit-module-boundary-types": 0
Думаю, нам следует поддержать эти новые рекомендуемые правила. Будет много изменений. Но они в принципе простые и полезные. Иначе этот технический долг будет только копиться.

Не обязательно прям сейчас. Можно завести отдельную задачу и сделать после релиза.

2021-03-19 13:33 UTC, zhzz commented on packages/react-ui/package.json
> +    "react-styleguidist": "^11.1.5",
В стайлгайдисте еще остались места, куда нужно дописать `static`. Например, в `LOCALECONTEXT.md` и `ThemeContext.md`.

Плюс, они [отказались](https://github.com/styleguidist/react-styleguidist/releases/tag/v11.0.0) от `initialState` и `setState` в пользу `React.useState`. Все примерчики в доке сломались.

2021-03-22 17:17 UTC, zhzz reviewed
Похоже, что все изменения в тестах, которые не касаются типов - лишние. Проверил, без них работает.

И да, можно еще раз пройтись. Уже снова накопилось достаточно обновлений. Особенно интересует `emotion@11`.

Пакеты, которые можно удалить: `csstype`, `selenium-webdriver`.

2021-04-08 15:18 UTC, zhzz requested changes

2021-04-08 15:18 UTC, zhzz commented on packages/react-ui/test-setup.js
> +});
Больше получается не нужно
```suggestion
```

2021-04-08 15:20 UTC, zhzz commented on packages/eslint-config/.eslintrc
> +    "@typescript-eslint/explicit-module-boundary-types": 0
Заведешь issue?

2021-04-09 05:43 UTC, lossir commented on packages/eslint-config/.eslintrc
> +    "@typescript-eslint/explicit-module-boundary-types": 0
Да, я записал себе завести 3 задачи.

2021-04-11 08:42 UTC, zhzz commented
Оказалось, что хуки с проверкой `git-lfs` генерируются им самим автоматически. Поэтому снова добавил их в репу. На винде все это работает, проверил.

Добавил еще ссылку на предыдущий пример SSR для 2.x.

2021-04-11 09:07 UTC, zhzz approved these changes

2021-04-11 09:09 UTC, merged