Theme-8px/sidepage
skbkontur/retail-ui pull request #2218
Opened 2020-11-20 10:32 UTC by rustho

add 
  sidePageBackingBg
  sidePageBackingBgOpacity
  sidePagePaddingLeft
  sidePagePaddingRight
  sidePagePaddingTop
  sidePagePaddingBottom
  sidePageFooterPaddingTop
  sidePageBodyPaddingBottom
  sidePageBgDefault
  sidePageBorderColor
  sidePageHeaderFontSize
  sidePageHeaderLineHeight
  sidePageHeaderPaddingBottom
  sidePageHeaderFixedFontSize
  sidePageHeaderFixedLineHeight
  sidePageHeaderFixedPadding
  sidePageCloseBtnPadding
  sidePageFooterPanelPaddingTop
  sidePageFooterPanelPaddingBottom

2021-03-18 08:35 UTC, StathamJason commented
Потом надо будет после объединения подвязаться на переменные модалки

2021-03-23 12:38 UTC, zhzz requested changes
Можно подлить в ветку `theme-8px/all` и попробовать подвязаться на модалку.

2021-03-23 12:56 UTC, zhzz requested changes

2021-03-23 12:56 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePageHeader.tsx
> +      FONT_FAMILY_CORRECTION;
Оказалось, что эта формула была неправильная, и в 8px-теме сейчас крестик при залипании хедера немного дергается. Но работающую формулу вывести у меня не получается. Там и размер шрифта имеет значение. Предлагаю просто завести для этого смещения переменную. В старой темt значение `11px`, в новой `7px`.

2021-03-25 09:41 UTC, zhzz commented
Докинул правок:
1. Обновил некоторые переменные в соответствии с макетами и соглашению по именам
2. Подправил проверку на тип компонента
3. Перенес все отступы в компонент Container потому что это есть его основная функция
4. Подправил отступ от футера по макетам. Он должен появляться только когда футер с панелью.

2021-03-25 11:26 UTC, zhzz approved these changes

2021-03-25 12:46 UTC, StathamJason approved these changes

2021-03-25 12:54 UTC, merged