Golubev/change button loading states
skbkontur/retail-ui pull request #2256
Opened 2020-12-23 08:20 UTC by StathamJason

2020-12-23 09:58 UTC, lossir approved these changes

2020-12-23 11:48 UTC, zhzz requested changes
Из-за особенностей работы emotion и нашего его не совсем корректного использования, в таком примере у спиннера появляется лишний отступ справа 3px.
```jsx
<Button use="link" icon={<OkIcon />} loading>Link</Button>
```

При переключении загрузки наблюдаются скачки ширины. 

Чтобы это побороть, нужно вынести отступ иконки в режиме ссылки в отдельный класс.  Отсюда:
https://github.com/skbkontur/retail-ui/blob/c7f69293c401412650a09ae39d00c1d8839b3aa5/packages/react-ui/components/Button/Button.styles.ts#L239-L241

Например, так:
```js
  iconLink(t: Theme) {
    return css`
      padding-right: ${t.btnLinkIconMarginRight};
    `;
  },
```
```jsx
      icon = (
        <span
          className={cn(..., {
            ...
            [jsStyles.iconLink(this.theme)]: this.props.use === 'link',
          })}
        >
          ...
        </span>
      );
```


---

Плюс, еще можно удалить переменные темы, которые больше не используются.

2020-12-23 11:48 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +          {!icon && loading}
Чтобы это условие  с `!icon` не дублировать лишний раз, можно его зашить в `loading`.

2020-12-23 11:48 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +            {loading && !icon ? this.getHiddenChildren() : this.props.children}
Здесь лучше всегда рендерить span и менять только его className, чтобы избежать лишних изменений в DOM.

2020-12-24 08:52 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +            <span className={cn({ [jsStyles.visibilityHidden()]: loading && !icon })}>{this.props.children}</span>
```suggestion
            <span className={cn({ [jsStyles.visibilityHidden()]: loading })}>{this.props.children}</span>
```

`&& !icon` ведь больше тоже не нужен.

2020-12-25 05:55 UTC, zhzz approved these changes
👍

Можно еще показать [демо](https://button-loading.vercel.app/#/Components/Button) @dzekh

2020-12-25 12:22 UTC, dzekh commented
Всё круто! 👍

2020-12-25 12:24 UTC, merged