Golubev/new arrow buttons
skbkontur/retail-ui pull request #2263
Opened 2020-12-30 08:17 UTC by StathamJason

**С какими проблемами столкнулся:**

- Не получится просто так сделать угол более скругленным, так как теперь селектора два (:before и :after) и, соответственно, два элемента. При попытке изменения border-radius по углам происходит следующее: 
![image](https://user-images.githubusercontent.com/31249664/103336588-7ac3bf80-4a9a-11eb-8df6-a7dd5bf5b223.png)

- Пропала тень на верхней грани и верхнем ребре самой стрелки, так как псевдокомпоненты рисуются поверх блока с кнопкой. Если расположить под блоком, тогда надо добавлять четыре тени в box-shadow родителя, чтобы правая/левая грань была без границы и стили теней для верхнего ребра псевдоэлемента стрелки. CSS код распухнет.
![image](https://user-images.githubusercontent.com/31249664/103338216-81a10100-4a9f-11eb-87ee-594b61b20589.png)

**_Новая верстка решает некоторые артефакты предыдущей, но в целом все равно получается такое себе решение_**

2021-01-11 06:59 UTC, StathamJason commented
Кажется, что визуальных артефактов стало меньше и убрались лишние большие миксины. Но угол энивэй не получится сделать круглее.

2021-01-12 05:39 UTC, zhzz commented
Думаю, в целом решение получается норм и изменения того стоят. Мы избавляемся от переменных стрелок для их фона и позиционирования. Решаем проблемы с торчащими то и дело уголками. Стрелки стали проще и ровнее. 👍

По артефактам:

1. `border-radius` К слову, прошлое решение его изменение вообще не поддерживало. А мы можем общий радус стрелок тоже унаследовать. Тогда до каких-то пределов его можно будет даже адекватно кастомизировать. А конкретно в углу стрелки думаю можно его захардкодить в 0 или 1px. Тогда получится что-то такое:

| 9px | 2px |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4607770/104271638-3209fe80-54bd-11eb-8b9e-0b3106acf7a5.png) | ![image](https://user-images.githubusercontent.com/4607770/104271767-76959a00-54bd-11eb-9328-ddf07b6a9c93.png) |

2. `box-shadow` Жаль, конечно, что его унаследовать никак не получится. Но это не большая беда. Артефакты, которые ты перечислил, думаю, не критичны. Но есть еще другой, по хуже. Дело в том, что стрелка перекрывает тень, которая применяется при нажатии на кнопку в дефолтной теме. 

| Было | Стало |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4607770/104272122-48fd2080-54be-11eb-834b-107a983552a9.png) | ![image](https://user-images.githubusercontent.com/4607770/104272171-65995880-54be-11eb-8c2f-125198ebb568.png) |

Это стоит поправить. Думаю, как вариант обойтись копированием (с корректировкой) ее в тень верхней половинки стрелки. Будет немного заметна нестыковка при масштабировании, но вероятно с этим можно жить.

| Сейчас | Будет с тенью |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4607770/104272171-65995880-54be-11eb-8c2f-125198ebb568.png) | ![image](https://user-images.githubusercontent.com/4607770/104272754-a2b21a80-54bf-11eb-9aa0-0d083f73209d.png) |
```css
::before {
    ...
    box-shadow: 1px 0 0 0 rgba(0,0,0,0.25), inset -1px 1px 2px 0 rgba(0,0,0,0.1) !important;
}
```
---
Из других моментов, которые можно поправить до аппрува скриншотов и ревью:
1. Изменились переменные `btnDefaultHoverBorderColor` и `btnCheckedDisabledShadow` в плоской теме. Вроде незаконно.
2. Добавление состояния `success` в таблицу кнопок хорошая правка. Но сейчас она вызовет лишние изменения скриншотов, из-за которых мы можем упустить что-то важное в изменении стрелок. Лучше это сделать в конце или отдельно. Идеально, если на скриншотах поменяются только стрелки. Тогда мы будем уверены, что ничего другого не сломалось.

Еще остались переменный фона стрелок в темах, которые можно удалить.

2021-01-12 10:55 UTC, dzekh commented
А что если внутренню тень нажатой кнопки сделать не честной тенью а градиентом? У нас же как-то реализован градиент на дефолтном состоянии? Тут он тоже будет выглядеть почище, если его получится подогнать.

2021-01-12 13:54 UTC, StathamJason commented
С градиентом будет видно грани псевдоэлементов. Примерно так
![image](https://user-images.githubusercontent.com/31249664/104323022-791ce180-5507-11eb-9396-274dcd5e4fe8.png)

2021-01-12 14:04 UTC, zhzz commented
> А что если внутреннюю тень нажатой кнопки сделать не честной тенью а градиентом? У нас же как-то реализован градиент на дефолтном состоянии? Тут он тоже будет выглядеть почище, если его получится подогнать.

Интересный вариант) Но получается не очень.

![image](https://user-images.githubusercontent.com/4607770/104322125-5dfda200-5506-11eb-9549-04a3d4ca03a6.png)

![image](https://user-images.githubusercontent.com/4607770/104323409-f3e5fc80-5507-11eb-91be-e90d619a172a.png)

(справа все через градиенты, на второй диапазон градиента пошире)

Тень выглядит более размазанной и плавной. И плюс отбрасывается сразу на четыре стороны. А градиент нужен будет для каждой стороны отдельный.

Это похоже на нашу обводку через тени. Тоже какой-то не совсем правильный путь.

2021-01-13 07:46 UTC, zhzz commented
@dzekh а тебе не нравится мой вариант с тенью?

Вот этот

> ![image](https://user-images.githubusercontent.com/4607770/104420458-b6cb4a00-559b-11eb-9100-b1166c2df035.png)

Он хорош еще тем, что затрагивает только сами стрелки. Сама кнопка никак не страдает.

2021-01-14 15:52 UTC, StathamJason commented
- Были убраны лишние миксины
- Верстка стала попроще
- Стало меньше визуальных артефактов
- Бэкграунд теперь наследуется
- Стало намного меньше переменных стрелок (и теперь они общие для левой  и правой)
- Тень верхней грани внутри стрелки задается с помощью linear-gradient через css-свойсто background-image (переменные arrowActiveShadowGradient и arrowCheckedShadowGradient)

2021-01-18 07:15 UTC, zhzz requested changes

2021-01-18 07:15 UTC, zhzz commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static btnDefaultHoverBorderColor = '#d9d9d9';
А зачем поменялось? Изменился цвет обводки при наведении на активную плоскую кнопку.

2021-01-18 08:28 UTC, StathamJason commented on packages/react-ui/components/Button/Button.styles.ts
> +        transform: skewX(30deg) scaleX(-1) !important;
Без псевдо-селекторов не работает

2021-01-18 08:49 UTC, zhzz commented on packages/react-ui/components/Button/Button.styles.ts
> +        transform: skewX(30deg) scaleX(-1) !important;
Должно же, типо такого:

```js
arrowLeft() {
    return css`
        transform: scaleX(-1);
    `
}
```

2021-01-18 09:02 UTC, StathamJason commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  btnDefaultHoverShadowArrow: '1px 0 0 0 rgba(0, 0, 0, 0.3)',
потому что у основной обводки две тени, которые накладываются друг на друга и выглядят темнее по итогу

2021-01-18 09:13 UTC, StathamJason commented on packages/react-ui/components/Button/Button.styles.ts
> +        transform: skewX(30deg) scaleX(-1) !important;
попробовал, не работает. Видимо псевдо-элементы своей жизнью живут. Если сделать как ты предложил, то они просто не отображаются

2021-01-18 09:28 UTC, StathamJason commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static btnDefaultHoverBorderColor = '#d9d9d9';
это я поменял на rgba и потом вернул '#d9d9d9' - это значение изначально было

2021-01-18 10:44 UTC, zhzz commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static btnDefaultHoverBorderColor = '#d9d9d9';
Да, я перепутал. Это сломалось еще раньше. Поправим в рамках #2209

2021-01-18 11:11 UTC, zhzz commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  btnDefaultHoverShadowArrow: '1px 0 0 0 rgba(0, 0, 0, 0.3)',
А вы обсуждали это с кем-то?  Вроде немного хаотично получилось. Где-то на стрелке осталось два цвета, но они изменились. Где-то стал один и потемнел. Кажется стоит выбрать одно какое-то правило.

@dzekh У некоторых кнопок нижняя обводка отличается. Раньше стрелки это повторяли. Может сейчас для простоты оставить на стрелке один цвет, равный цвету основной обводки у кнопки (т.е. как на левом/верхнем/правом ее краях)?

2021-01-18 11:18 UTC, zhzz commented on packages/react-ui/components/Button/Button.styles.ts
> +        transform: skewX(30deg) scaleX(-1) !important;
Нужно видимо этот контейнер подверстать так, чтобы у него появились свои размеры. Тогда заработает.

2021-01-18 19:12 UTC, lossir reviewed
Из-за изменений, о которых Егор говорит здесь https://github.com/skbkontur/retail-ui/pull/2263#discussion_r559346049, также пришлось обновить скриншоты теста `Button/text styles reset`. Их тоже надо вернуть.

---

У стрелки совсем нет внутренней тени в нажатом состоянии. Мне кажется, её стоит добавить. Я попробовал сделать вариант, правда, только через браузер.

| где | чего |
| --- | --- |
| было | ![image](https://user-images.githubusercontent.com/2708211/104954640-6e23ee80-59ea-11eb-81f9-89dbf61a5906.png) |
| стало | ![image](https://user-images.githubusercontent.com/2708211/104954699-8e53ad80-59ea-11eb-8caa-34f7dd1d53a9.png) |
| как вариант | ![image](https://user-images.githubusercontent.com/2708211/104954713-957abb80-59ea-11eb-9bba-58a9b40fff8e.png) |

2021-01-19 11:58 UTC, dzekh commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  btnDefaultHoverShadowArrow: '1px 0 0 0 rgba(0, 0, 0, 0.3)',
Да, давайте так и сделаем. В [макетах в Фигме](https://www.figma.com/file/4vh3dHXmD8Ae4IGfIIApbC/%E2%9A%A1%EF%B8%8F-Kontur-UI-8px?node-id=1453%3A1927) отличается только нижняя обводка, сам уголок стрелки повторяет основную тень:
![image](https://user-images.githubusercontent.com/26383080/105031661-6f4f2d00-5a77-11eb-8d5f-c7ae5bd76b24.png)

2021-01-19 12:00 UTC, dzekh commented
> У стрелки совсем нет внутренней тени в нажатом состоянии. Мне кажется, её стоит добавить. Я попробовал сделать вариант, правда, только через браузер.

Да, мне нравится такой вариант, который «как вариант».

2021-01-20 05:13 UTC, zhzz commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  btnDefaultHoverShadowArrow: '1px 0 0 0 rgba(0, 0, 0, 0.3)',
Похоже, что в темной теме еще остались непоправленные цвета обводок у стрелок.

2021-01-20 07:16 UTC, lossir submitted a review, later dismissed
По моим замечаниям всё ок. После переапрува скриншотов ещё гляну.

2021-01-25 07:53 UTC, zhzz requested changes
Переаппрувлено и добавлено несколько лишних скриншотов (DateInput, Input, Link, Radio, Textarea, Tooltip). В идеале, должны поменяться только скриншоты с кнопками-стрелками. Новых быть не должно, т.к. тестов не добавляли.

Все это видно на вкладке "Files changed" в ПРе.

2021-01-26 11:23 UTC, zhzz approved these changes
Теперь четко 👍

2021-01-28 07:25 UTC, lossir approved these changes

2021-01-28 07:34 UTC, merged