feat(Link): new loading state
skbkontur/retail-ui pull request #2271
Opened 2021-01-15 09:35 UTC by StathamJason

2021-01-18 04:56 UTC, zhzz requested changes

2021-01-18 04:56 UTC, zhzz commented on packages/react-ui/components/Link/__stories__/Link.stories.tsx
> +Simple.story = { parameters: { creevey: { tests: linkTests } } };
```suggestion
Loading.story = { parameters: { creevey: { tests: linkTests } } };
```

Здесь видимо `Loading.story` имелся в виду. Не хватает скриншотов в IE. А в остальном кажется все круто.

2021-01-18 19:14 UTC, lossir submitted a review, later dismissed

2021-01-19 07:27 UTC, zhzz commented
Первые две картинки теперь лишние получаются. Их можно удалить.

2021-01-20 07:45 UTC, lossir commented on packages/react-ui/components/Link/Link.tsx
> +      iconElement = <span className={jsStyles.icon(this.theme)}>{loading ? this.getLoadingSpinner() : icon}</span>;
Тут можно не создавать отдельный метод.
```jsx
iconElement = (
  <span className={styles.icon}>{loading ? <Spinner caption={null} dimmed type="mini" /> : icon}</span>
);
```

2021-01-20 10:11 UTC, lossir approved these changes

2021-01-20 10:19 UTC, zhzz approved these changes

2021-01-20 10:20 UTC, merged