feat(TokenInput): onUnexpectedInput prop added
skbkontur/retail-ui pull request #2279
Opened 2021-01-26 09:14 UTC by StathamJason

**Функция для обработки ситуации, когда была введена строка в инпут и был потерян фокус с элемента.**

Функция срабатывает с аргументом инпута строки.

Когда произойдет срабатывание функции:
- Если при потере фокуса есть список элементов (автокомплит) и значение в текстовом поле НЕ будет совпадать с результатом `renderValue` какого-нибудь элемента (в противном случае сработает onValueChange со значением данного элемента)
- При редактировании токена (если оно не было завершено)

2021-01-28 03:41 UTC, zhzz commented
Выглядит круто! Стоит уточнить еще моменты:

1. Обработка возвращаемого значения из onUnexpectedInput
2. Авто-выбор совпадающего значения из списка только если оно там осталось одно

Такая логика в комбобоксе.

2021-01-28 08:23 UTC, StathamJason commented
> Выглядит круто! Стоит уточнить еще моменты:
> 
> 1. Обработка возвращаемого значения из onUnexpectedInput
> 2. Авто-выбор совпадающего значения из списка только если оно там осталось одно
> 
> Такая логика в комбобоксе.

 
Насчет возвращаемого значения это ок, добавлю.

А вот насчет автовыбора, там сейчас в `checkAutocompleteForCorrectItem` идет поиск элемента по названию. То есть по сути это всегда будет один айтем с совпадающим value. Или может быть ситуация, что будет два токена с одинаковым value? Тогда это уже косяк разраба и данных, пусть фильтруют. **Но я добавлю доп проверку чтобы в текущем автокомплите был один айтем.**

2021-01-28 09:20 UTC, zhzz commented
> А вот насчет автовыбора, там сейчас в `checkAutocompleteForCorrectItem` идет поиск элемента по названию. То есть по сути это всегда будет один айтем с совпадающим value. Или может быть ситуация, что будет два токена с одинаковым value? Тогда это уже косяк разраба и данных, пусть фильтруют. **Но я добавлю доп проверку чтобы в текущем автокомплите был один айтем.**

На счет уникальности value ты прав. Но тут еще дело, как я понимаю, вот в чем. Могут быть два айтема: `abc` и `abcdef`. Пользователь ввел "abc"  и бросил. В меню оставались оба варианта. Чтобы быть уверенным, что он хотел ввести в итоге именно первый, а не второй, нужна проверка на количество.

Путь Вова меня поправит, если что, ведь он все читает)

2021-01-28 10:46 UTC, dzekh commented
А мы же ищем совпадение не по подстроке а строгое. С первым совпадение строгое со вторым нет. Кажется что среди токенов не может быть двух одинаковых, они уникальные по определению =) Может среди айтемов комбобокса бывает такое, но тут похоже на ошибку.

2021-01-28 10:47 UTC, dzekh commented
Интересно а строчные прописные мы игнорируем?

2021-01-28 10:54 UTC, dzekh commented
В общем в анэкспектед мы предполагаем что пользователь, возможно, закончил ввод, но не сказал об этом явно. Поэтому проверяем совпадения. 
Если пользователь ввел `abc` а токен есть только `abcde` то токен не выберется. 
И в ситуации когда пользователь ввел `abc`, есть токены и `abc` и `abcde` — второй токен не должен мешать выбрать первый, первый же совпадает полностью.

2021-01-28 12:09 UTC, StathamJason commented
> Интересно а строчные/прописные мы игнорируем? если я ввел `abc` а токен `Abc`?

Фильтр строгий, регистрозависимый. По запросу Abc  вариант abc не найдется

2021-01-28 12:15 UTC, StathamJason commented
Функция для обработки ситуации, когда была введена строка в инпут и был потерян фокус с элемента.

Функция срабатывает с аргументом инпута строки.

Сама функция также может вернуть значение, неравное `undefined`, с которым будет вызван `onValueChange`.
Если возвращаемое значение будет равно `null`, то сработает очистка текущего значения инпута.
   
### Когда произойдет срабатывание функции:

- Если при потере фокуса есть список элементов (автокомплит)
    с длиной больше одного
- Если при потере фокуса есть список элементов (автокомплит)
    с одним элементом и значение в текстовом поле НЕ совпадает
    с результатом `renderValue` элемента
    (в противном случае сработает `onValueChange` со значением данного элемента)
- При редактировании токена (если оно не было завершено)

2021-01-28 18:53 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> -      this.finishTokenEdit();
Теперь заметно поменяется поведение при отмене редактирования токена.

Раньше, при `blur`/`esc` редактирование заканчивалось и вызывался `onChange`.
Теперь, вместо него вызывается `onUnexpectedInput` и при этом состояние редактирования токена сохраняется даже при потере фокуса самим `TokenInput`'ом.

Предлагаю, если проп `onUnexpectedInput` не задан, то дёргать `this.finishTokenEdit()` как раньше.

2021-01-28 18:53 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        const item = onUnexpectedInput(inputValue);
Сейчас `onUnexpectedInput` вызывается при любом блюре, даже если пользователь ничего не вводил. Например, если просто "табаться" по форме через `TokenInput`, то будет вызван `onUnexpectedInput` с пустой строкой.

Кажется, это не совсем верное поведение. И если `inputValue` пуст, то при блюре, ничего делать не стоит.

2021-01-28 18:53 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  private checkAutocompleteForCorrectItem = () => {
Метод `checkAutocompleteForCorrectItem` меня немного смущает. Он и проверяет на что-то `item`, возвращая `boolean`. Но также может вернуть и сам `item`.

Предлагаю сделать отдельный метод для обработки случаев `onUnexpectedInput`, перенести в него код отсюда и из `this.handleInputBlur`, а непосредственно в `this.handleInputBlur` только дёргать этот отдельный метод.

2021-01-28 18:53 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
По-моему, здесь можно заметно упростить логику.
```suggestion
    if (autocompleteItems && autocompleteItems.length === 1) {
      return autocompleteItems.find(item => valueToString(item) === inputValue);
    }
```

2021-01-29 06:43 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> -      this.finishTokenEdit();
Мы обговаривали этот момент и пришли к выводу, что на блюр не будет завершаться редактирование токена. Будет ли он завершаться если нет unexpectedInput - это вопрос для обсуждения

2021-01-29 06:44 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        const item = onUnexpectedInput(inputValue);
Ну я подумал, что этот момент оставляем на откуп пользователя. Он в своем хэндлере может проверить пустой ли инпут и ничего не делать.

2021-01-29 08:28 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  private checkAutocompleteForCorrectItem = () => {
зарефакторил

2021-01-29 08:28 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
отрефакторено

2021-01-29 11:45 UTC, dzekh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        const item = onUnexpectedInput(inputValue);
Не, мне кажется это не правильно. Кажется Максим прав, есть смысл дергать `onUnexpectedInput` только если значение менялось. Но тут я не уверен.

2021-01-29 11:47 UTC, dzekh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> -      this.finishTokenEdit();
То, что поведение поменялось, да, это норм, мы обговаривали.

2021-02-01 06:56 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +   * с длиной больше одного
А почему обязательно наличие минимум одного элемента в списке для вызова `onUnexpectedInput`? Кажется, такого условия изначально не было.

2021-02-01 06:56 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +   * с результатом `renderValue` элемента
```suggestion
   * с результатом `valueToString` элемента
```

2021-02-01 06:56 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    if (item && !this.isEditingMode) {
А почему для режима редактирования тут поведение отличается?

2021-02-01 06:56 UTC, zhzz commented on packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
> +      if (foundItems.length === 0) {
Тут всегда `true` из-за асинхронности getItems.

2021-02-01 06:59 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        const item = onUnexpectedInput(inputValue);
Я согласен, что сейчас много лишних вызовов. В комбобоксе есть проверка перед вызовом на то, что значение менялось, через флаг `inputChanged`

2021-02-01 07:54 UTC, zhzz reviewed
Я бы еще подумал об обработке пустой строки при редактировании. 

Когда пользователь все стер и бросил, вместо вызова onUnexpectedInput, вероятно, стоит просто удалить этот токен. Так было раньше внутри `finishTokenEdit()`.

Так же и при возвращении null из onUnexpectedInput, после редактирования на месте токена остается пустое поле ввода. Думаю, в этом случае тоже можно токен удалить.

---

Так и у пользователя останется возможность удалить токен во время редактирования. И разработчик тоже сможет это сделать.

2021-02-01 10:29 UTC, StathamJason commented
- финиш токен едит мы убираем да?
- в режиме редактирования и без него логика работы одинаковая (взаимодействие с поиском)?
- проверка перед вызовом на то, что значение менялось?
- если все стерли, то удаляем токен?

2021-02-01 11:10 UTC, StathamJason commented
- В режиме редактирования и без него логика работы одинаковая (по взаимодействию с поиском)
- проверка перед вызовом на то, что значение менялось
- если все стерли в режиме редактирования, то удаляем токен (проверка на '')
- при возвращении null в режиме редактирования удаляем токен

2021-02-05 06:29 UTC, zhzz requested changes

2021-02-05 06:29 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      item = autocompleteItems.find(item => valueToString(item) === inputValue);
Кажется странным делать поиск по массиву с заведомо одним элементом. Наверняка понятней и дешевле будет взять его сразу по индексу.

2021-02-05 06:29 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      return null;
```suggestion
      return;
```

Этот null же нигде не нужен. В таких ситуациях обычно просто выходят из функции. 
Еще в паре мест ниже такое же есть.

2021-02-05 06:29 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    newActiveTokens.splice(index, 1, ...[]);
`selectedItems` и `activeTokens` это разные массивы. Индексы в них в общем случае не совпадают.

2021-02-05 06:29 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    this.dispatch({ type: 'CLEAR_INPUT' });
Функция, судя по названию, призвана делать вполне конкретную работу, но также делает еще что-то несвязанное (вместо `finishTokenEdit`).

Может там, где она используется, получится сначала очистить инпут, а потом вызвать finishTokenEdit, который и удалит и все остальное сделает?

2021-02-05 06:29 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    this.tryGetItems();
Там, где removeTokenByIndex используется, это похоже не нужно.

2021-02-05 06:43 UTC, zhzz requested changes
Еще есть момент, когда после блюра фокус возвращается в редактирование токена. Там открывается пустой список подсказок. Можно его наполнить, так же как и при запуске редактирования по двойному клику.

2021-02-05 07:28 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      return null;
опять же остатки прошлой работы во мне. там линтер не пропускал пустые return

2021-02-05 08:13 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      return null;
![image](https://user-images.githubusercontent.com/4607770/107007145-f1e42600-67b3-11eb-9256-12ae8a5b082e.png)

2021-02-08 14:47 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +   * - При редактировании токена (если оно не было завершено)
исправил

2021-02-08 14:47 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    this.setLastQuery(this.state.inputValue);
Теперь поведение совпадает

2021-02-08 14:47 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      item = autocompleteItems.find(item => valueToString(item) === inputValue);
Исправлено)

2021-02-11 05:16 UTC, zhzz requested changes

2021-02-11 05:16 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      this.tryGetItems();
```suggestion
      this.tryGetItems(this.isEditingMode ? '' : this.state.inputValue);
```

Чтобы не менять прошлого поведения, кажется, лучше сделать так.

2021-02-11 07:32 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      process.nextTick(() => this.finishTokenEdit(true));
Да, да для явности. Внутри проверку на `isEditingMode` решил оставить во избежание казусов в дальнейшем (вдруг надо будет использовать и проверка на режим редактирования будет пропущена). Ничего страшного в этом не вижу.

Насчет callback в dispatch это понятно, но у меня не работал правильно `finishTokenEdit`, если я передавал его коллбэком. Видимо что-то влезало в цепочку событий или не успевало отработать корректно и поэтому я расположил ниже с нулевым таймаутом (ну с `process.nextTick(...)`) чтобы явно в event loop врезать.
**НО** я видимо внес правки в `finishTokenEdit` и сейчас он отрабатывает коллбэком корректно...

Anyway, запись такая `this.isEditingMode ? this.removeCurrentlyEditedToken() : this.clearInput();` мне нравится больше, чем вот такая 
`this.dispatch({ type: 'CLEAR_INPUT' }, this.isEditingMode ? () => this.finishTokenEdit(true) : undefined)` 
или же такая 
`this.dispatch({ type: 'CLEAR_INPUT' }, () => {
          if (this.isEditingMode) {
            this.finishTokenEdit(true);
          }
        });`

2021-02-11 07:33 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      process.nextTick(() => this.finishTokenEdit(true));
Оставил вариант 
`this.dispatch({ type: 'CLEAR_INPUT' }, () => { if (this.isEditingMode) { this.finishTokenEdit(true); } });`

2021-02-11 07:40 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      this.dispatch({ type: 'SET_ACTIVE_TOKENS', payload: [newItems[editingTokenIndex - 1]] });
это я удалить забыл, когда коммиты объединял...

2021-02-11 08:15 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Логика ниже остается как и была раньше. Этот момент нужен на случай когда случился `onUnexpectedInpit`, вернувший `null`. Фокус уже ушел, нам не нужен активный токен)

2021-02-11 08:17 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  lastInputValue: string;
Это да, правда

2021-02-11 08:20 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      this.tryGetItems();
Поведение не изменилось, но можно и так сделать)

2021-02-11 12:26 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      this.tryGetItems();
Поменялся при фокусе на инпут, если в нем уже был какой-то текст. Раньше поиск стартовал с этим текстом, а до последней правки - по пустой строке.

Сейчас все норм.

2021-02-11 12:43 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Но сейчас же не только при возврате `null`, а еще в двух местах используется `finishTokenEdit(true)`.

Если хочется сбрасывать активные именно при удалении редактируемого, то можно добавить по аналогии в конец `finishTokenEdit` соответсвующее условие и сброс, без отдельного флага. Для единообразия.

2021-02-16 04:38 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Ага. Я в прошлый раз не обратил внимания, что активные токены уже сбрасываются перед редактированием. И что в `finishTokenEdit` уже была своя логика работы с активными при удалении редактируемого. Сейчас она поменялась, и не понятно законно ли.

Не уверен, что старая логика была лучше, не помню почему именно так сделали. Но такие изменения лучше обсуждать. 

В таком случае еще вопрос. В чем была изначальная идея обрабатывать удаление при возврате `null` по другому, нежели чем при полном стирании текста в инпуте? Вроде кажется что это одно и то же, и активные можно проставлять в этих случаях одинаково (по старому, например).

2021-02-16 04:39 UTC, zhzz commented
Пара картинок `withClearedToken` лишние, не используются. В остальном тесты крутые.

2021-02-16 07:30 UTC, StathamJason commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Не понял вопроса. Мы договорились, что при возврате `null` (если пользователь захочет так делать) токен будет удаляться, так ведь. Вот сейчас при `null` и происходит очищение строки сперва, а потом `finishTokenEdit`, если режим редактирования.

То, что было добавлено `if (newItems.length < selectedItems.length) {
      return;
    }`  строки (830 - 832) считаю норм, тк перед редактированием и так все активные токены сбрасываются и это условие сработает **только в этом случае** (`onUnexpectedInput` вернул null и мы были в режиме редактирования токена)

2021-02-16 08:02 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Да, с возвратом null, очищением и удалением вопросов нет. Все верно.

Вопрос теперь в том, что раньше, до onUnexpectedInput, после редактирования была такая логика: 
  - если токен не удалялся, то он становился активным;
  - если удалялся, то активным ставился предшествующий удаленному или первый из оставшихся;
 
Теперь же, при удалении активный токен больше вообще не ставится. А еще раньше, ты хотел не ставить его только при удалении через возврат null.

Вот я и пытаюсь разобраться в твоем подходе к этому и понять, как правильно сделать.

2021-02-16 12:18 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
Согласовали вместе с Вовой новое поведение. Если токен во время редактирования не был удален, то после он остается активным (как и раньше). А если был удален, то никакие токены вместо него активными не становятся (в отличии от старого поведения).

2021-02-16 12:19 UTC, zhzz approved these changes

2021-02-16 12:21 UTC, zhzz commented
Продублирую из обсуждения:

> Согласовали вместе с Вовой новое поведение. Если токен во время редактирования не был удален, то после он остается активным (как и раньше). А если был удален, то никакие токены вместо него активными не становятся (в отличии от старого поведения).

2021-02-25 07:53 UTC, lossir approved these changes

2021-03-02 12:37 UTC, merged