Remove deprecated vars and components
skbkontur/retail-ui pull request #2286
Opened 2021-02-04 11:35 UTC by StathamJason

Решение для https://yt.skbkontur.ru/issue/IF-55

### Было выпилено
**Компоненты:**
-  `TopBar`
-  `Fias`
-  `Logotype`
-  `SpinnerOld`
- `LocaleProvider`
- `ThemeConsumer`
- `ThemeProvider`

**Пропы:**
- _alcoLink_ (`MenuItem`)
- _diadocLinkIcon_  (`DropDown`, `Select`)
- _cloud_ (`Spinner`, `Loader`)

**Остальное:**
- переменные из `DEPRECATED_VARIABLES`
- неиспользуемые истории и скриншоты

2021-02-18 12:27 UTC, zhzz requested changes
Все круто. 

Было бы еще здорово составить список переменных, которые были переименованы, с новыми именами. Поможет при написании кодмода в том числе, ну и для информации, чтобы не искать. Возможно прикрепим ссылку на этот ПР к гайду по миграции.

Еще нужно понять, что делать с переменными темы удаленных компонентов, и как в целом теперь наладить кастомизацию и локализацию компонентов из аддонов. Над этим я еще подумаю.

2021-02-18 12:27 UTC, zhzz commented on packages/react-ui-smoke-test/cra-template-react-ui/template/src/App.tsx
>    DatePicker,
Еще осталось несколько артефактов к удалению: 

1. Дока
https://github.com/skbkontur/retail-ui/blob/626ac07178e4d2139b03e6a6cb3e04a8e69475de/packages/react-ui/.styleguide/helpers.js#L26

2. Смок-тесты
https://github.com/skbkontur/retail-ui/blob/626ac07178e4d2139b03e6a6cb3e04a8e69475de/packages/react-ui-smoke-test/smoke.test.ts#L13

3. `LocaleProvider` в доке многих компонентов
https://github.com/skbkontur/retail-ui/blob/626ac07178e4d2139b03e6a6cb3e04a8e69475de/packages/react-ui/components/ComboBox/ComboBox.md#L412

4. MenuItem
https://github.com/skbkontur/retail-ui/blob/626ac07178e4d2139b03e6a6cb3e04a8e69475de/packages/react-ui/components/MenuItem/MenuItem.tsx#L50
 
5. В доке `LOCALECONTEXT.md` осталось много использований
https://github.com/skbkontur/retail-ui/blob/ad7bb41316378fe37af8cc6ad9efe15537804f7a/packages/react-ui/lib/locale/LOCALECONTEXT.md#L26

2021-02-18 12:27 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> -
Предложенные в коммите как альтернатива пропы `use` и `_icon` не позволяют сделать на 100% то же самое. Это касается внешнего вида и работы с плейсхолдером/локалью. 

Я думаю стоит предложить проп _renderButton. И даже добавить пример для него в доку к Select, куда скопировать эту удаленную функцию рендера ссылки.

2021-02-19 10:15 UTC, zhzz commented
От переменных тем удаленных компонентов тоже можно полностью избавиться.

2021-03-02 15:12 UTC, zhzz requested changes
Заметил еще пару моментов.

И списочек переменных, которые были переименованы, с новыми именами было бы здорово к описанию ПРа добавить. Он будет полезен.

2021-03-02 15:12 UTC, zhzz commented on packages/react-ui-validations/docs/Layout.tsx
> -          <Logotype suffix="ui-validations" href="#/" color="#fff" textColor="#fff" />
Как-то сразу не обратил внимания. Совсем без заголовка будет пустовато.

![image](https://user-images.githubusercontent.com/4607770/109668243-cd048800-7b92-11eb-8033-384c9e8337e8.png)

Может хотя бы простой h3 на место логотипа поставить.

![image](https://user-images.githubusercontent.com/4607770/109668494-0dfc9c80-7b93-11eb-89e2-4eddd2c8a737.png)

2021-03-05 13:02 UTC, StathamJason commented
### Переименованные переменные

| Было  | Стало |
| ------------- | ------------- |
| chbCheckedColor  | checkboxCheckedColor |
| chbBg  | checkboxBg  |
|  |  |
|  |  |
|  |  |
|  |  |

2021-03-05 13:22 UTC, StathamJason commented
### Переименованные переменные

| Было  | Стало |
| ------------- | ------------- |
| chbCheckedColor  | checkboxCheckedColor |
| chbBg  | checkboxBg  |
| chbHoverBg | checkboxHoverBg |
| chbShadowDisabled  | checkboxShadowDisabled |
| chbIndeterminateBg | checkboxIndeterminateBg |
| sltPlaceholderColor  |  selectPlaceholderColor |
| btnSmallBorderRadius | btnBorderRadiusSmall |
| btnBorderRadius | - (удалено)|
| sltPlaceholderColor | selectPlaceholderColor |
| textareaHeight | textareaMinHeight |

2021-03-09 10:18 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    return this.checkboxShadow;
Это еще осталось

2021-03-09 10:43 UTC, zhzz requested changes

2021-03-09 12:12 UTC, StathamJason commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    return this.checkboxShadow;
А я вроде прикрепрял картинку, видимо не отправилась.

Там кароч было вот так 
<img width="490" alt="Снимок экрана 2021-03-09 в 17 11 40" src="https://user-images.githubusercontent.com/31249664/110468748-86ff7500-80fa-11eb-84e3-5ec6e5f209be.png">
 
Так что сейчас все норм

2021-03-09 12:56 UTC, StathamJason commented
Обновил таблицу с именами, ответил на комменты. Почему есть мердж конфликты в github хз, ветка `next` смерджена уже

2021-03-09 13:45 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    return this.checkboxShadow;
Да, это я затупил

2021-03-10 10:31 UTC, zhzz approved these changes

2021-03-10 10:41 UTC, zhzz requested changes
Блин, после мерджа мастера теперь еще `PropsForwarding-test.tsx`  нужно поправить.

https://github.com/skbkontur/retail-ui/blob/9597469a3c55dd83ac2e91b56e255caccc3c49c8/packages/react-ui/components/__tests__/PropsForwarding-test.tsx#L6-L11

https://github.com/skbkontur/retail-ui/blob/9597469a3c55dd83ac2e91b56e255caccc3c49c8/packages/react-ui/components/__tests__/PropsForwarding-test.tsx#L25-L26

2021-03-11 05:53 UTC, zhzz approved these changes
👍

2021-03-15 11:53 UTC, merged