Button if 88
skbkontur/retail-ui pull request #2287
Opened 2021-02-04 13:17 UTC by bae1

test(Button): change screenshots for different combinations

В плейграунд добавлена кнопка success + изменены скриншоты, связанные с этими правками

2021-02-09 08:38 UTC, lossir reviewed
Вроде, всё норм)

Только `prettier` надо запустить, чтобы код поправить немного.

Ещё у некоторых скринов в ie11 появился скролл, и стала скрываться часть страницы. Не знаю на сколько это критично. @zhzz что скажешь? ![image](https://user-images.githubusercontent.com/2708211/107337093-bad78280-6adb-11eb-8447-3892bb3ae2b8.png)

2021-02-10 05:04 UTC, zhzz requested changes
> Ещё у некоторых скринов в ie11 появился скролл, и стала скрываться часть страницы. Не знаю на сколько это критично. @zhzz что скажешь?

Думаю, что не очень критично. Кажется все норм.

2021-02-10 05:04 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +export type ButtonUse = 'default' | 'primary' | 'success' | 'danger' | 'pay' |'success'| 'link';
```suggestion
export type ButtonUse = 'default' | 'primary' | 'success' | 'danger' | 'pay' | 'link';
```

Тут `success` не нужно добавлять, он уже есть.

2021-02-10 08:05 UTC, zhzz approved these changes

2021-02-10 08:55 UTC, merged