feat(Loader): add component prop
skbkontur/retail-ui pull request #2295
Opened 2021-02-10 08:31 UTC by StathamJason

Добавлен новый проп `component`, позволяющий заменить стандартный спиннер чем-нибудь кастомным

2021-02-11 06:08 UTC, zhzz requested changes

2021-02-11 06:08 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    component: undefined,
Это лишнее, по умолчанию и так будет `undefined`.

2021-02-11 06:08 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +      const element = this.spinnerNode.children[0] || this.spinnerNode;
Сам `this.spinnerNode` тут не сгодится, потому что его размеры отличаются от размеров его содержимого. Видно проблему, если на истории "Vertical scroll" в качестве компонента передать строку.

Наверное здесь стоит придумать еще одну обертку, которая будет точно присутствовать и соответствовать размерам своего содержимого.

А также, стоит предусмотреть, что содержимое и его размеры теперь могут меняться со временем.

2021-02-16 08:13 UTC, zhzz requested changes

2021-02-16 08:13 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    return <div style={{ display: 'inline-block', textAlign: 'center' }}>{component}</div>;
Предлагаю эту обертку использовать всегда, даже с дефолтным спинером. Тогда мы сможем перевесить на нее this.spinnerNode, и смело использовать его для подсчета высоты, не копаясь в `this.spinnerNode.children[0]`.

Стили уже лучше вынести в css, думаю. 

На счет `textAlign: 'center'` не уверен, что он нужен. Пусть может сами своей версткой рулят?

2021-02-16 08:13 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    console.count('checkSpinnerPosition');
Забыл удалить

2021-02-16 08:13 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    return prevProps.children && prevProps.children !== children;
Тут точно `children` имелся в виду? Или `component`.

Если проп сначала был undefined, потом в него что-то передали, то проверка не сработает.

2021-02-17 06:03 UTC, zhzz requested changes
Снова картиночки лишние остались, а в остальном кажись норм 👍

2021-02-17 07:46 UTC, zhzz approved these changes

2021-02-25 08:24 UTC, StathamJason commented
Если все ок, то потом надо будет на парковке использовать новый проп

2021-03-02 12:21 UTC, zhzz commented
Я выкатил тестовую версию с этой фичей ` @skbkontur/react-ui@0.0.0-e39f3359cc` чтобы можно было на парковке начинать делать. Но скорей всего этот ПР быстрее зарелизится, чем до парковки руки дойдут. Ничего страшного, если в аддонах фича чуть позже появится.

2021-03-04 06:33 UTC, zhzz commented
После последних правок сразу катнем релиз.

2021-03-04 11:49 UTC, zhzz approved these changes

2021-03-04 13:48 UTC, merged