feat(Kebab): focus and blur methods added, onBlur, onFocus props added
skbkontur/retail-ui pull request #2303
Opened 2021-03-04 08:12 UTC by draugi

Добавлены методы focus() и blur() для Kebab, добавлены пропы onFocus, onBlur
fix #2140

2021-03-04 15:41 UTC, lossir commented on packages/react-ui/components/Kebab/Kebab.tsx
> +  onBlur?: () => void;
По факту, пропы `onFocus` и `onBlur` никак не обрабатываются.
На спане, на котором дёргаются методы `this.span?.focus()`, навешаны обработчики `this.handleFocus` и `this.handleBlur`. И на них эти события и "потухают", не выходя наружу.

К тому же, `Kebab` не простой элемент формы. Надо учесть, что при открытии всплывашки, не стоит дёргать `onBlur`, т.к. для пользователя он как-бы в "фокусе".
А вот при закрытии всплывашки, `onBlur` надо дёрнуть.

2021-03-04 15:41 UTC, lossir commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> +
Тут тоже приттер? Слишком много воздуха)

2021-03-04 15:41 UTC, lossir commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> +ProgrammaticFocus.story = { name: ' Kebab with programmatic focus', parameters: { creevey: { skip: [true] } } };
```suggestion
ProgrammaticFocus.story = { name: 'Kebab with programmatic focus', parameters: { creevey: { skip: [true] } } };
```
---
Почему заскипал? Хороший тест получится.

Ещё можно сделать тест на `jest` для пропов `onFocus` и `onBlur`.

2021-03-11 05:33 UTC, lossir reviewed
Почти все `suggestion` я добавлял лишь для удобства. Так лучше читается, что именно я предлагаю заменить.
Я к тому, что не стоит их "коммитить".

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> + } } };
`Prettier` так и не настроил?

Перед коммитом, набери в терминале в корне:
```shell
yarn prettier --write ./**/Kebab/**/*.tsx
```

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> +      async focusedByFocusMethod() {
Давай здесь заюзаем "серию" скриншотов. Вот [здесь](https://github.com/wKich/creevey/blob/master/docs/tests.md), внизу, написано как это делать.
В данном случае это кажется в самый раз.

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__tests__/Kebab.test.tsx
> +    const kebab = mount(<Kebab onFocus={onFocus} />);
Метод `mount` возвращает обёртку, поэтому будет корректнее назвать так:
```suggestion
    const wrapper = mount(<Kebab onFocus={onFocus} />);
```

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__tests__/Kebab.test.tsx
> +    kebab.find('[tabIndex=0]')
Здесь можно использовать иконку в качестве селектора:
```suggestion
    kebab.find(MenuKebabIcon)
```

Это более однозначный и "устойчивый" поиск.

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__tests__/Kebab.test.tsx
> +    const onFocus = jest.fn();
Здесь незачем создавать шпиона за `onFocus`, т.к. его вызов не отслеживается.

2021-03-11 05:33 UTC, lossir commented on packages/react-ui/components/Kebab/__tests__/Kebab.test.tsx
> +describe('Kebab', () => {
Не хватает теста, который проверят потерю фокуса при открытом меню и клике снаружи.
Тебе поможет функция `clickOutside()`. Она реализована в нескольких тестах, например в `Tooltip-test.tsx`

2021-03-16 15:30 UTC, lossir commented on packages/react-ui/components/Kebab/Kebab.tsx
> +        this.props.onFocus?.();
Опять `prettier`
```suggestion
      this.props.onFocus?.();
```

2021-03-16 15:30 UTC, lossir commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> +          await this.expect({ afterFocus, afterBlur }).to.matchImages();
Давай немного переименуем, а то префикс `after` лишь мешает.
```suggestion
          await this.expect({ focus, blur }).to.matchImages();
```

2021-03-22 07:51 UTC, lossir commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          this.props.onBlur?.();
При работе с клавиатуры может прийти аргумент `restoreFocus = true`. В таких случаях не надо вызывать `onBlur()`, т.к. по факту фокус сразу восстанавливается после закрытия всплывашки.
```suggestion
          !restoreFocus && this.props.onBlur?.();
```

2021-03-22 07:51 UTC, lossir commented on packages/react-ui/components/Kebab/Kebab.tsx
> +      this.props.onFocus?.();
Когда фокус "восстанавливается", то коллбек срабатывает лишний раз. Поэтому надо добавить проверку, что кебаб "закрыт":
```suggestion
      !this.state.opened && this.props.onFocus?.();
```

2021-03-22 07:51 UTC, lossir commented on packages/react-ui/components/Kebab/Kebab.tsx
> +  private spanRef = (ref: HTMLSpanElement | null) => {
Давай избавимся от этого метода, и воспользуемся `useRef`, как в сторисах.

2021-03-28 20:17 UTC, lossir approved these changes

2021-03-30 10:45 UTC, StathamJason approved these changes

2021-03-31 06:54 UTC, zhzz reviewed
Получилось вроде прикольно. 

Но не совсем однозначный вопрос, когда считать что Кебаб в фокусе, а когда нет. 
1. С одной стороны, можно учитывать его открытое состояние, как сейчас. Тогда нет множественных вызовов onFocus/onBlur, что для пользователя иногда может быть понятней.
2. Но с другой стороны, Кебаб можно рассматривать в сущности только как кнопку с иконкой. Тогда именно ее события onFocus/onBlur логично транслировать наружу.

Аргумент за первый вариант, это более очевидное в некоторых случаях поведение.
Аргумент против, это отрыв от реального состояния фокуса в DOM. Например, если посмотреть на другие компоненты с выпадахами (ComboBox, Select), то там после вызова события onFocus основной элемент внутри (инпут или кнопка) всегда однозначно в настоящем фокусе. А вызов метода `blur` в таком состоянии всегда приведет к вызову onBlur. Сейчас в Кебабе это не так. 
Плюс, синяя обводка от фокуса по Tab в Кебабе сейчас при открытии пропадает, но onBlur при этом не вызывается.

Если взять наверное ближайший аналог - Select, то там фокус привязан напрямую к кнопке. Бывают лишние вызовы событий при клике на элементы меню. Но их там меньше, потому что меню на себя фокус не забирает при открытии, как в Кебабе.

Я не знаю, насколько это критично и как правильно. Сам скорее склоняюсь ко второму варианту, но готов и на текущий согласиться. Можно спросить совета у автора issue, как он собирался эти штуки использовать.

2021-03-31 06:54 UTC, zhzz commented on packages/react-ui/components/Kebab/__stories__/Kebab.stories.tsx
> +            .click(blurButton)
Здесь получается, что тест на метод `blur` не работает, потому что blur происходит от самого нажатия на кнопку, а не вызова метода. Можно попробовать использовать событие наведения мыши вместо клика.

2022-03-24 10:19 UTC, Lelchik commented
Выбрала второй вариант, передаем в методы onFocus и onBlur состояние кнопки с иконкой. Но мне кажется немного странным поведение: открылось меню и у кнопки вызвался onBlur.

2022-04-01 08:17 UTC, zhzz requested changes
Да, похоже второй вариант правильнее, а переход фокуса на выпадашку странен. 

Можно будет отдельно поразбираться с причинами такого поведения фокуса. Возможно, получится переделать. Наверное, это было сделано для передачи управления выделением элементов стрелками вверх/вниз в InternalMenu. Но, кажется, есть и другие способы это организовать.

2022-04-01 08:17 UTC, zhzz commented on packages/react-ui/components/Kebab/__tests__/Kebab.test.tsx
> +    clickOutside();
В этом случае `clickOutside` бесполезен, т.е. его можно удалить и тест продолжит проходить, т.к. blur срабатывает при открытии выпадашки от клика.  Похоже, в нашем втором варианте этот тест не очень нужен.

2022-04-04 06:59 UTC, Lelchik commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          restoreFocus && this.props.onFocus?.();
Потому что фактически фокус уходит с кнопки

2022-04-04 07:04 UTC, Lelchik commented
Пока видится такое поведение: 
метод focus: ставит фокус на кнопку. Если фокус уже есть или открыта выпадашка, то ничего не делает 
метод blur: снимает фокус с кнопки. Если открыта выпадашка, то закрывает её.
onFocus вызывается при фокусе на кнопку. При открытии и закрытии выпадашки НЕ вызывается.
onBlur - при снятии фокуса с кнопки. При открытии выпадашки метод НЕ вызывается так как фокус остался все равно на контроле.

2023-05-22 13:15 UTC, closed without merging