feat(react-ui): new arrow icons
skbkontur/retail-ui pull request #2331
Opened 2021-03-26 12:31 UTC by dzekh

Заменил иконки-стрелки треугольники у инпутов комбобокса и кнопок селекта на стрелки галки.

2021-04-02 05:08 UTC, zhzz commented
>  пропадает стрелка в IE на этом скриншоте, надо понять почему

Понять сложно, возможно связано с `position: absolute` у стрелки. Т.к. это идет в next, то предлагаю переверстать там все на флексах, без всяких легаси-отступов, которые сейчас есть. В 8px по макетам, а в старой теме как получится (более/менее похоже чтобы было). Эту проблему в IE должно починить.

2021-04-07 05:35 UTC, zhzz requested changes

2021-04-07 05:35 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +              style={{ marginBottom: '-3px' }}
Этот margin кажется ни на что не влияет.

2021-04-07 05:35 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> -    const useIsCustom = this.props.use !== 'default';
В селект можно передавать разные `use`, и тогда цвет стрелки должен меняться, как раньше было.

2021-04-07 05:35 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> -          return this.theme.selectPaddingArrowSmall;
Можно поудалять эти старые переменные `selectPaddingArrow*`

2021-04-07 05:35 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +          {this.props._icon && <div style={{ paddingRight: this.getLeftIconGap() }}>{this.props._icon}</div>}
У иконки в 8px-кнопке также меняется и ширина в зависимости от размера. Ее тоже сюда нужно применить.

Я бы предложил вообще по максимуму утащить все стили в css.

2021-04-07 05:35 UTC, zhzz commented on packages/react-ui/internal/icons/16px/index.tsx
> +    <svg viewBox="0 0 16 16" style={{ marginBottom: '-3px' }}>
```suggestion
    <svg viewBox="0 0 16 16" style={{ marginBottom: '-0.1875em' }}>
```

Вероятно это то же смещение, что и в новых react-icons. Значение в em лучше, потому что масштабируется со шрифтом. В `ArrowChevronUpIcon` тоже.

2021-04-08 03:17 UTC, zhzz requested changes

2021-04-08 03:17 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +            <ArrowChevronDownIcon color={this.getArrowColor(this.props.use)} />
Почему бы не использовать прежний `jsStyles.customUseArrow` для цвета? Он так же даст правильную прозрачность, в ссылке в том числе. Только сейчас он нужен на элементе `arrowWrap`, и можно убрать из него `border-top-color`.

2021-04-08 06:51 UTC, StathamJason commented on packages/react-ui/components/Select/Select.tsx
> +            <ArrowChevronDownIcon color={this.getArrowColor(this.props.use)} />
Потому что раньше было реализовано через css и цвет подхватывался. А сейчас через компонент иконки, который явно ожидает в себя цвет. Поэтому так с не сработает уже.

Но прозрачность сейчас добавлю

2021-04-08 06:59 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +            <ArrowChevronDownIcon color={this.getArrowColor(this.props.use)} />
Но компонент иконки тоже подхватывает текущий цвет ☝️

2021-04-08 09:36 UTC, zhzz approved these changes
🔥

2021-04-09 04:30 UTC, merged