docs(react-ui): add migration guide for 3.0
skbkontur/retail-ui pull request #2343
Opened 2021-04-09 08:44 UTC by zhzz

Добавил гайд по миграции на 3.0.

Демо в [репе](https://github.com/skbkontur/retail-ui/blob/migration-3.0/packages/react-ui/MIGRATION.md).

2021-04-09 09:36 UTC, lossir commented on packages/react-ui/MIGRATION.md
> +Помимо этого, были переименованы некотрые переменные темы. Подробнее в [#2286](https://github.com/skbkontur/retail-ui/pull/2286).
```suggestion
Помимо этого, были переименованы некоторые переменные темы. Подробнее в [#2286](https://github.com/skbkontur/retail-ui/pull/2286).
```

2021-04-09 10:27 UTC, StathamJason requested changes

2021-04-09 10:27 UTC, StathamJason commented on packages/react-ui/MIGRATION.md
> +  - [Зависимости](#зависимости)
`- [Ломающие изменения](#ломающие-изменения)`

2021-04-09 12:24 UTC, StathamJason submitted a review, later dismissed

2021-04-09 12:45 UTC, lossir commented on packages/react-ui/MIGRATION.md
> +### Ломающие изменения
Вроде, тут почти все изменения ломающие. Может написать:
```suggestion
### Обёртка в Tooltip и Hint
```

2021-04-09 12:58 UTC, lossir approved these changes

2021-04-12 03:00 UTC, merged

2021-05-03 18:32 UTC, dzekh commented on packages/react-ui/MIGRATION.md
> +| `DEFAULT_THEME_8PX` | По умолчанию     |
Егор предлагал переименовать темы так, чтоб новые добавить со старыми названиями, а старым добавить _OLD

2021-05-05 05:17 UTC, zhzz commented on packages/react-ui/MIGRATION.md
> +| `DEFAULT_THEME_8PX` | По умолчанию     |
И не забыть отразить это в гайде по миграции