[WIP] [Switcher] проблемы с валидацией
skbkontur/retail-ui pull request #2353
Opened 2021-04-14 11:43 UTC by StathamJason

Фикс для https://github.com/skbkontur/retail-ui/issues/2191

2021-04-22 09:26 UTC, lossir requested changes

2021-04-22 09:26 UTC, lossir commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> +    return this.props.errorMessage(clonedChild, !!validation, validation);
Опасно так делать, даже если кажется что вроде ничего не поехало. Ведь если что-то слетит, то слетит у всех и везде.

---

Это, походу, та же проблема, что была у `TokenInput` [в своё время](https://github.com/skbkontur/retail-ui/issues/1918).
Вот здесь надо добавить фильтр и для свитчера.

https://github.com/skbkontur/retail-ui/blob/03cca914d3a2a97659647f919cd83e33e9ff354a/packages/react-ui-validations/src/ValidationTooltip.tsx#L30

2021-04-22 09:26 UTC, lossir commented on packages/react-ui-validations/stories/Switcher.stories.tsx
> +import { ValidationContainer, ValidationInfo, ValidationWrapper, text } from '../src';
Хелпер `text` не используется.
```suggestion
import { ValidationContainer, ValidationInfo, ValidationWrapper } from '../src';
```

2021-04-22 09:26 UTC, lossir commented on packages/react-ui-validations/stories/Switcher.stories.tsx
> +            <Switcher items={['string1', 'string2']} onValueChange={value => this.setState({ value })} />
В свитчер стоит прокинуть `value`, а то при работе в сторибуке нифига не понятно)

2021-04-23 08:41 UTC, StathamJason commented
А то что по хаверу после валидации продолжает появляться tooltip это баг или фича?

2021-04-23 15:31 UTC, lossir commented
> А то что по хаверу после валидации продолжает появляться tooltip это баг или фича?

Так и должно быть, если я тебя правильно понял.
Вот строчка в гайдах - https://guides.kontur.ru/principles/validation/#11

2021-04-23 15:32 UTC, lossir submitted a review, later dismissed

2021-04-25 17:47 UTC, zhzz submitted a review, later dismissed
Нужно оставить один fix-коммит или засквошить.

2021-04-26 13:02 UTC, zhzz approved these changes

2021-04-26 16:59 UTC, merged

2021-06-15 09:28 UTC, dzekh commented
А этот пиар влит? Если да, то таску связанную нужно закрыть. Закрываю?

2021-06-15 09:44 UTC, StathamJason commented
@dzekh был залит

2021-06-16 05:07 UTC, zhzz commented
Закрыл