[DropdownMenu] Невозможно позиционировать caption относительно родителя
skbkontur/retail-ui pull request #2354
Opened 2021-04-15 08:05 UTC by StathamJason

Фикс для https://github.com/skbkontur/retail-ui/issues/944

2021-04-22 07:58 UTC, lossir approved these changes

2021-04-25 11:02 UTC, zhzz requested changes

2021-04-25 11:02 UTC, zhzz commented on packages/react-ui/internal/PopupMenu/PopupMenu.tsx
> +        style={{ width: this.props.width }}
При передаче ширины в %, неравной `100%`, будет неожиданный результат. Что если в `caption` захардкодить `100%`?

2021-05-10 17:08 UTC, zhzz approved these changes

2021-05-11 17:50 UTC, merged