fix(Hint): clear opening timer
skbkontur/retail-ui pull request #2364
Opened 2021-04-22 09:04 UTC by chervyakovru

Сценарий такой:

Hint закрыт
Наводим мышкой - создается таймер открытия на 400мс
нажимаем на компонент раньше, чем прошло 400 мс
По клику устанавливаем пропы `manual=true` и `opened=false`

Ожидание:
Hint не откроется потому что выставлены пропсы `manual=true` и `opened=false`
Реальность:
Hint все равно открывается

2021-04-22 09:07 UTC, chervyakovru commented
Решил очищением timer при изменении пропса `manual` в UNSAFE_componentWillReceiveProps.

Можно сделать по другому - проверять проп `manual` внутри колбека, который передается в `setTimeout`

Как лучше не знаю. Сделал по первому варианту

2021-04-22 12:08 UTC, lossir commented on packages/react-ui/components/Hint/Hint.tsx
> +    }
Думаю, второй вариант лучше. Через проверку флага в колбэке.
Так мы немного локализуем решение проблемы в её источнике.
К тому же, рано или поздно методы `UNSAFE_componentWillReceiveProps` надо будет выпилить.

2021-04-22 16:03 UTC, lossir reviewed
Надо оставить только один коммит в типом `fix...`. Этот тип автоматически попадает `changelog` при релизе.

2021-04-25 17:44 UTC, zhzz requested changes

2021-04-25 17:44 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +      return;
Думаю, очистка таймера правильнее. Источник проблемы же в нем, а не в методе open. Таймер устанавливается только при условии `!manual`, и соответственно при его изменении должен удаляться. 
Можно представить дополненный сценарий, когда, например, при повторном клике втечение тех же 400мс `manual` снова становиться `false`. В текущем решении Хинт в итоге откроется, но я думаю, что уже не должен.

Но, в методе open эта правка тоже кажется логичной. Хотя по факту она ломающая. Я бы перенес ее в ветку next с соответствующей пометкой BREAKING CHANGE.

2021-04-29 07:23 UTC, chervyakovru commented on packages/react-ui/components/Hint/Hint.tsx
> +      return;
Предлагаешь оставить ифчик в 2х местах?

2021-04-29 07:47 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +      return;
Из метода open предлагаю убрать. Тут он сейчас потенциально ломающий. Вероятно, мы перенесем его в следующую мажорную версию.

2021-04-29 09:30 UTC, zhzz submitted a review, later dismissed

2021-04-29 14:00 UTC, zhzz approved these changes

2021-04-29 14:47 UTC, lossir approved these changes

2021-04-29 16:43 UTC, merged