fix: Теперь выделение по двойному клику, а также снятия выделения в C…
skbkontur/retail-ui pull request #2366
Opened 2021-04-22 16:39 UTC by hukopo

…urrencyInput работает

2021-04-22 16:43 UTC, hukopo commented
Мы у себя потестили руками у нас вроде все отлично стало. Правда есть еще другие вопросы к каренси инпуту, но именно баги в ие https://github.com/skbkontur/retail-ui/issues/2362 и https://github.com/skbkontur/retail-ui/issues/2361 в этом пр должны полечится

2021-04-25 17:14 UTC, zhzz requested changes

2021-04-25 17:14 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    { trailing: false },
Использовать debounce хорошая идея, но при таких опциях функция никогда не вызывается.
 
Кажется, часть проблемы с ИЕ кроется в том, что при клике внутри выделенного фрагмента, в событии координаты выделения почему-то приходят старые. Поэтому, внутри debonced-функции их нужно брать не из объекта события, а непосредственно из инпута, актуальные на момент вызова. Таймаут можно поменьше, 200 хватает вроде.

И я бы ограничил всю эту правку только для ИЕ. У нас есть для этого проверки в `packages/react-ui/lib/client.ts`.

2021-06-21 06:23 UTC, zhzz requested changes

2021-06-21 06:23 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +function getInputSelectionFromInput(input: HTMLInputElement): Selection {
А не получится методы `getInputSelectionFromInput`/`getInputSelectionFromEvent` и `setSelectionFromInput`/`setSelectionFromEvent`  все-таки объединить? Они вроде практически одинаковые.

2021-06-21 06:23 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  public nativeInput: HTMLInputElement | null = null;
Зачем пришлось переименовать? Хоть это и законно, я боюсь, что у многих могут быть написаны костыли вокруг инпута, которые трогают это свойство. Тогда они все сломаются. Без нужды я бы не трогал.

2021-06-21 06:23 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      if (selectionStart !== selectionEnd) {
А зачем проверка? Так поведение в IE и остальных браузерах немного отличается.

2021-06-21 07:56 UTC, StathamJason commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      if (selectionStart !== selectionEnd) {
При двойном клике вызывается два события подряд: с точкой клика, допустим 8 и 8, и потом уже с рэнжом выбора на второй клик (8 и 12 например). Так вот если ИЕ позволить обрабатывать их оба, то со вторым событием он справиться не успевает) Просто игнорирует его. Поэтому видимо либо так, либо никак

2021-06-21 08:09 UTC, StathamJason commented on packages/react-ui/components/Input/Input.tsx
> +  public nativeInput: HTMLInputElement | null = null;
ну просто `this.input.input`...

2021-06-21 08:19 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  public nativeInput: HTMLInputElement | null = null;
Да и ладно. 

И, кстати, публичным его не стоит делать. Это внутренности, которые намеренно от пользователя скрываются, чтобы они на него не завязывались.

2021-06-21 08:40 UTC, StathamJason commented on packages/react-ui/components/Input/Input.tsx
> +  public nativeInput: HTMLInputElement | null = null;
А как я тогда селекшн из него получу в CurrencyInput

2021-06-21 09:54 UTC, StathamJason commented
У меня походу дополнительно лагал IE в виртуалке. Проверил на виндовском - все работает...  &#128557;

2021-06-21 09:56 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  public nativeInput: HTMLInputElement | null = null;
Хорошим решением было сделать в Input отдельную `ref` на нативный инпут, и использовать его. Либо добавить публичный метод к Input, для считывания текущего выделения.

Но т.к. это нужно только в костыле для IE, то можно просто добавить [ts-ignore](https://github.com/skbkontur/retail-ui/blob/fix-selection-in-currency-input-for-ie/packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx#L163) с комментарием.

2021-06-21 11:35 UTC, zhzz requested changes

2021-06-21 11:35 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
Прямо так не работает. Нужно добавить `event.persist()`. 

И, согласно моим экспериментам, увеличить задержку до 300. Иначе, при сбросе выделения всего значения, новая позиция курсора не всегда ставится под кликом.

2021-06-21 12:58 UTC, StathamJason commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
Блин, это в 17 реакте избавились от пулла событий. [https://ru.reactjs.org/docs/legacy-event-pooling.html](url)

Он и с 300 так же не устанавливает, бывает проскакивает

2021-06-21 13:26 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
По моим тестам вроде норм. 

Итого, баги пофикшены, основные сценарии работают. Можно катить, думаю.

2021-06-21 13:59 UTC, zhzz approved these changes

2021-06-21 15:44 UTC, merged