fix(locale): add check that 'name' field is configurable
skbkontur/retail-ui pull request #2371
Opened 2021-04-28 13:01 UTC by lossir

Тестировал на Cromium Portable v35.0.1916.27 (262261).

Fix #2370

2021-04-28 13:27 UTC, zhzz approved these changes

2021-04-29 03:04 UTC, zhzz requested changes

2021-04-29 03:04 UTC, zhzz commented on packages/react-ui/lib/locale/decorators.tsx
> +    const isChrome35 = isBrowser && navigator?.appVersion?.includes('Chrome/35');
Предыдущая версия была лучше. Проблема же не в одной конкретной версии. Она может быть также и в других старых версиях и браузерах.

2021-04-29 05:42 UTC, lossir commented on packages/react-ui/lib/locale/decorators.tsx
> +    const isChrome35 = isBrowser && navigator?.appVersion?.includes('Chrome/35');
Посчитал, что не стоит делать общее исправление, т.к. баг возник в одном конкретном древнем браузере. В ie11, например, посыпались некоторые тесты, т.к. `getOwnPropertyDescriptor` возвращает `undefined`, хотя вроде [поддерживается](https://caniuse.com/?search=Object.getOwnPropertyDescriptor).

Но ок, верну.

2021-04-29 06:26 UTC, sergeyshmakov commented on packages/react-ui/lib/locale/decorators.tsx
> +    const isChrome35 = isBrowser && navigator?.appVersion?.includes('Chrome/35');
Мне тоже кажется общее будет лучше )

2021-04-29 06:28 UTC, zhzz commented on packages/react-ui/lib/locale/decorators.tsx
> +    const isChrome35 = isBrowser && navigator?.appVersion?.includes('Chrome/35');
``` javascript
    const nameDescriptor = Object.getOwnPropertyDescriptor(LocaleDecorator, 'name');
    if (!nameDescriptor || nameDescriptor.configurable) {
      Object.defineProperty(LocaleDecorator, 'name', { value: constructor.name });
    }
```

Общее решение же всегда лучше, если не сильно сложнее. Баг нашелся в одном браузере, но присутствует же во многих. А в ie11 свойства `name` просто совсем нет и тоже можно сделать общую проверку.

2021-04-29 07:49 UTC, lossir commented on packages/react-ui/lib/locale/decorators.tsx
> +    const isChrome35 = isBrowser && navigator?.appVersion?.includes('Chrome/35');
Уговорили

2021-04-29 08:29 UTC, zhzz approved these changes

2021-04-29 10:15 UTC, merged