Перевести доку реакт-селениум тестинга на styleguidist
skbkontur/retail-ui pull request #2399
Opened 2021-05-17 13:10 UTC by StathamJason

[IF-117](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-117)

2021-05-18 18:22 UTC, zhzz requested changes
Можно кое-что лишнее выкинуть, например babel, webpack, их конфиги. Они нужны для компонентов, но тут их у нас нет. По сути хватит одной зависимости, это сам стайлгайдист.

И я бы еще перенес стайлгайдист и команды его запуска в package.json родительского проекта, react-ui-testing, чтобы не плодить их. А папку с конфигами и md назвал бы docs или как-то так, для ясности.

Еще стили можно перенести из конфига стайлгайдиста, который в react-ui, чтобы все доки выглядели у нас единообразно.

2021-05-20 16:51 UTC, zhzz reviewed
Все, и `package.json` в docs больше не нужен. `MockReadme` тоже.

2021-05-20 16:51 UTC, zhzz commented on packages/react-ui-testing/package.json
> +    "selenium-styleguide:build": "styleguidist build --config ./docs/.styleguide/config/base.config.js"
```suggestion
    "styleguide": "styleguidist server --config ./docs/.styleguide/config/base.config.js",
    "styleguide:build": "styleguidist build --config ./docs/.styleguide/config/base.config.js"
```

2021-05-21 11:08 UTC, zhzz approved these changes

2021-05-27 13:15 UTC, lossir approved these changes

2021-05-27 13:15 UTC, lossir commented on packages/react-ui-testing/PromoSite/package.json
> -        "publish-docs": "npm run clean && git clone git@github.com:skbkontur/react-ui-validations.git dist && cd dist && git checkout gh-pages && cd .. && npm run build && cd dist && git add . && git
Я так понимаю, эта тока давно не диплоилась)

2021-05-31 11:34 UTC, zhzz approved these changes

2021-05-31 11:37 UTC, merged