[Tabs] Фикс неправильного позиционирования индикатора
skbkontur/retail-ui pull request #2408
Opened 2021-05-21 11:08 UTC by StathamJason

При изменении размеров компонента индикатор активного таба мог позиционироваться неправильно

Например, при использовании `img` с `src` компонент уже смонтировался, индикатор спозиционировался, а картинки подгрузились чуть позже и табы изменили свой размер. В итоге мы имеем неправильно спозиционированный индикатор.

Фикс для https://github.com/skbkontur/retail-ui/issues/2357

2021-05-27 12:50 UTC, lossir commented on packages/react-ui/components/Tabs/Tabs.tsx
> +                  <ResizeDetector
Мне кажется, что подобный баг можно "полечить" напоминанием, что картинкам надо задавать ширину/высоту. Тем более когда это иконки.

Есть ли другие ожидаемые сценарии ресайза вкладки, которые идут в обход реакта, чтобы их так отслеживать?
@zhzz Что думаешь?

2021-06-01 06:36 UTC, zhzz commented on packages/react-ui/components/Tabs/Tabs.tsx
> +                  <ResizeDetector
Другие сценарии могут быть. Например, какие-нибудь счетчики, которые растут/уменьшаются время от времени. Или какой-то другой динамический контент. Всего не предугадать и напоминанием про размер картинки вряд ли получится отделаться. 

![tech skbkontur ru_react-ui_ (1)](https://user-images.githubusercontent.com/4607770/120277438-7ca1e100-c2cd-11eb-873e-a4a97aadb075.png)

2021-06-01 07:04 UTC, zhzz commented on packages/react-ui/components/Tabs/Tabs.tsx
> +                  <ResizeDetector
Сценарий из issue лечится, но могут быть и другие, когда решение не сработает. Например, при горизонтальном расположении табов, растянутых на всю ширину контейнера. В этом случае, ResizeDetector тоже будет растянут и может не реагировать на изменения контента внутри отдельных табов.

Думаю, стоит перенести ResizeDetector внутрь каждого таба.

Также, можно подправить тротлинг функции reflow внутри Indicator, чтобы он работал всегда, а не только для LayoutEvents.

Еще, отдельным комитом стоит выключить tabIndex у iframe внутри ResizeDetector.

И, было бы круто сделать скриншот. История добавлена хорошая, но чтобы не зависеть от чужих картинок, можно заиспользовать что-то такое:
```tsx
const Img: React.FC<{ size: string }> = ({ size }) => (
  <img
    src={`data:image/svg+xml;base64,${btoa(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}"><rect fill="grey" width="100%" height="100%" /></svg>`,
    )}`}
  />
);
```

2021-06-01 08:12 UTC, StathamJason commented on packages/react-ui/components/Tabs/Tabs.tsx
> +                  <ResizeDetector
> Еще, отдельным комитом стоит выключить tabIndex у iframe внутри ResizeDetector.

Пофиксится подливанием мастера в эту ветку

2021-06-01 09:33 UTC, zhzz commented on packages/react-ui/components/Tabs/Tabs.tsx
> +                  <ResizeDetector
тчн

2021-06-02 05:29 UTC, zhzz requested changes

2021-06-02 05:29 UTC, zhzz commented on packages/react-ui/components/Tabs/Tab.tsx
> +            }}
Стрелочная функция в пропе - не очень хорошо.

```suggestion
            onResize={this.context.notifyUpdate}
```

2021-06-02 05:29 UTC, zhzz commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +      },
В creevey есть специальный параметр - задержка перед выполнением всего теста. Примерно для таких ситуаций.

```suggestion
      delay: 500
```

2021-06-02 10:09 UTC, zhzz approved these changes

2021-06-02 10:09 UTC, merged