[react-ui-validations]  Фикс срабатывания lostfocus валидации после первого рендера
skbkontur/retail-ui pull request #2410
Opened 2021-05-24 12:38 UTC by StathamJason

Фикс для https://github.com/skbkontur/retail-ui/issues/2355

2021-05-24 12:39 UTC, StathamJason commented
По идее раз нет скриншотных в валидации, то написать на этот момент селениум тест

2021-06-07 10:53 UTC, zhzz requested changes
Кажется что норм. Учитывая, что у `ValidationContainer` в итоге все равно нужно звать `validate` или `submit` перед отправкой формы. Т.е. корректное состояние валидации перед отправкой всегда отобразится. Значит по `lostfocus`, по аналогии с `submit`, изначально невалидное значение до реальной потери фокуса/сабмита можно не подсвечивать.

2021-06-07 10:53 UTC, zhzz commented on packages/react-ui-validations/selenium-tests/ValidationTests/Storybook/Sync/PreinvalidLostfocusValidation.cs
> +            page.InputValidation.Label.WaitAbsent();
Этот тест перестал соответствовать своему названию. Сейчас он скорее уже `ValidToInvalid`.

2021-06-08 09:24 UTC, zhzz approved these changes

2021-06-08 13:32 UTC, merged