[Checkbox] Fix not triggered onFocus handler
skbkontur/retail-ui pull request #2417
Opened 2021-05-28 10:00 UTC by StathamJason

Фикс для https://github.com/skbkontur/retail-ui/issues/2309

2021-05-28 12:37 UTC, lossir approved these changes

2021-05-31 12:23 UTC, zhzz requested changes

2021-05-31 12:23 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.tsx
> +
Зачем решил добавить эту проверку? 

С фокусами у нас ситуация такая. Контролы, такие как кнопки, чекбоксы и др, получают фокус по табу и по клику. Но мы хотим визуально отображать только фокусы по табу. Для этого используется tabListener и флаг focusedByTab. Но тот фокус, который приходит с кликом, тоже абсолютно законный и настоящий.

Поэтому onFocus должен срабатывать на любой фокус. Так же как сейчас onBlur срабатывает на любой blur.

2021-05-31 13:10 UTC, zhzz approved these changes

2021-05-31 13:56 UTC, merged