feat(Kebab): add custom icon
skbkontur/retail-ui pull request #2430
Opened 2021-06-09 04:59 UTC by khlutkova

2021-06-11 09:37 UTC, zhzz requested changes
👍

2021-06-11 09:37 UTC, zhzz commented on packages/react-ui/components/Kebab/Kebab.tsx
> +    }
Можно весь этот блок еще упростить, заиспользовав функцию `cn`:
```js
    const className = cn({
      [jsStyles.icon()]: true,
      [jsStyles.iconsmall(this.theme)]: size === 'small',
      [jsStyles.iconmedium(this.theme)]: size === 'medium',
      [jsStyles.iconlarge(this.theme)]: size === nlarge',
    })
```

Также, добавить общий для все размеров класс `icon`, куда добавить `display: inline-block`, чтобы у всех иконок он одинаковый был, и `color: #757575`, чтобы передавался в кастомную иконку.

2021-06-11 09:37 UTC, zhzz commented on packages/react-ui/components/Kebab/Kebab.tsx
> +    icon: <MenuKebabIcon color="#757575"/>,
Если вынесем цвет в общий css-класс `icon`, то здесь он уже будет не нужен.

2021-06-15 11:22 UTC, zhzz approved these changes

2021-06-16 09:50 UTC, StathamJason approved these changes

2021-06-16 10:23 UTC, merged