feat(Modal): fix shadows and footer color
skbkontur/retail-ui pull request #2442
Opened 2021-06-15 10:31 UTC by khlutkova

2021-06-16 11:58 UTC, zhzz requested changes

2021-06-16 11:58 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> -      }
Я провел исследование и выяснил, что эта верстка служила для того, чтобы тень отбрасывалась только от одной грани хедера/футера, а не со всех его сторон, как стало сейчас.

Можно посоветоваться с @dzekh, насколько это критично. И, если что, вернуть прежнюю верстку и подобрать другие параметры тени под нее.

2021-06-16 11:58 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> -        box-shadow: ${t.modalFixedFooterShadow};
И еще сейчас пара переменных перестала использоваться, `modalFixedHeaderShadow` и `modalFixedFooterShadow`. Лучше присвоить им новые значения и снова заиспользовать, чтобы пользователи могли кастомизировать.

2021-06-17 11:35 UTC, khlutkova commented on packages/react-ui/components/Modal/Modal.styles.ts
> -      }
После обсуждения с @dzekh, остановились на варианте `box-shadow: 0px 0px 16px 1px rgba(0, 0, 0, 0.3);`, остальное без изменений

2021-06-18 06:16 UTC, zhzz approved these changes
👍

2021-06-18 06:28 UTC, zhzz commented
Здесь бы лучше подошел коммит типа `fix`. Правка маленькая, больше походит на фикс бага, чем на новую фичу. Фича, как правило - это существенное изменение функциональности.

К тому же, мы следуем [semver](https://semver.org/), и коммиты типа `feat` при релизе поднимают минорную версию библиотеки, т.е. `3.0.1` -> `3.1.0`. А фиксы добавляют патч: `3.0.1` -> `3.0.2`. Это тоже стоит иметь в виду.

Но ничего страшного, я засквошу, подправлю на `fix`.

2021-06-18 06:29 UTC, merged