[DatePicker]: Нативные дэйтпикеры на мобилках
skbkontur/retail-ui pull request #2447
Opened 2021-06-18 08:39 UTC by StathamJason

2021-07-01 14:23 UTC, zhzz requested changes

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +        {this.state.isMobile && (
Это лучше глубже внутрь перенести, на месте календаря, например, рисовать.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            }}
Стили в css.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +    if (this.props.autoFocus && !useMobile) {
А в чем проблема с автофокусом? Можно сделать так же, как нативный datepicker его обрабатывает.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      }
Здесь тогда либо wheel, либо touch.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +    stopBodyScroll();
Лучше через event.preventDefault() попробовать.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +    }
Почему не сделать через анимацию, так же как для wheel?

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +  private handleTouchEnd = (event: Event) => {
Если делать на touchEnd, то пока не отпустишь палец - ничего не происходит. Эффект, как будто скролл тормозит. Я попробовал с touchMove.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +  document.getElementsByTagName('body')[0].style.height = '100vh';
Высоту менять опасно. Если у body будут отступы, то все может поехать.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +  document.getElementsByTagName('body')[0].style.overflow = 'auto';
Я знаю проекты, где на body намеренно стоит `overflow-y: scroll`, чтобы не скакала ширина. `auto` им все испортит.

2021-07-01 14:23 UTC, zhzz commented on packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx
> +      </Gapped>
Я бы сделал отдельную историю, чтобы не менять существующие скриншоты.

2021-07-13 06:42 UTC, zhzz requested changes
На iOS'e сейчас нет возможности потестить, так что там не проверял.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx
> +};
Скриншоты этой истории вроде как бесполезны. Можно историю заскипать.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +      const date: CalendarDateShape = { year: 2020, month: 2, date: 1 };
Год тогда тоже стоит проверить на корректное дополнение нулями.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/components/DatePicker/utils.ts
> +    });
Подобная задача уже решалась [здесь](https://github.com/skbkontur/retail-ui/blob/8a1f7c478f3707e7e9f8e29f7ab146c0a8d92208/packages/react-ui/components/DatePicker/DatePickerHelpers.tsx#L5). Тут год форматируется некорректно.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/components/DatePicker/utils.ts
> +export const nativeDateInputUtils = {
А зачем утилиты объединять в один объект? Так всяким статическим анализаторам сложнее работать, и штуки типа рефакторинга в IDE наверное работать не будут.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +    const deltaY = (this.touchStartY || 0) - event.targetTouches[0].clientY;
Из-за того, что `this.touchStartY` обновляется только на `onTouchStart`, при длинных свайпах скрол постепенно ускоряется. Дельта с каждым событием движения все больше и больше. Вероятно, тут стоит сделать более линейную пропорцию.

2021-07-13 06:42 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +    }
Это все выглядит странно. Проблема с кликами возникает после `preventDefault()` на `onTouchStart`. После него клики больше не эмулируются. Это плохо. Кажись есть другое нормальное решение вместо preventDefault:  [`touch-action: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action). Вроде работает, нужно потестить.

2021-07-30 06:09 UTC, zhzz requested changes

2021-07-30 06:09 UTC, zhzz commented on packages/react-ui/components/DateInput/DateInput.tsx
> +          )}
Не пробовал вынести в DatePicker? Тут ему не очень место. Он нужен только в DatePicker и рисовать бы его вместо нашего Picker'а.

2021-07-30 06:09 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    }
Это производит довольно странные ощущения, когда на любого размера свайп он прокручивает всегда на одно и тоже расстояние. Я бы предложил считать дельту пропорционально прокрученному расстоянию.

2021-07-30 06:09 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    }
Что если также как в календаре заменить event.preventDefault() на touch-action: none. Должны будут заработать клики.

2021-07-30 09:39 UTC, StathamJason commented on packages/react-ui/components/DateInput/DateInput.tsx
> +          )}
А почему ему не место не место `DateInput`? Можем также по пропу включать на мобилках открытие нативных календарей, это ведь инпут, связанный с датой. Я наоборот специально это сделал

2021-07-30 09:47 UTC, zhzz commented on packages/react-ui/components/DateInput/DateInput.tsx
> +          )}
Ну, получается что это инпут для ручного ввода. Для выбора из календаря есть как раз DatePicker.

2021-08-11 11:25 UTC, zhzz requested changes
Мы очень близки

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/components/DateInput/DateInput.tsx
> +
Это уже не нужное изменение

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/components/DateInput/DateInput.tsx
> +  useNativeDatePicker?: boolean;
```suggestion
```

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +          useNativeDatePicker={this.props.useMobileNativeDatePicker}
```suggestion
```

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +    }
Эти изменения типов еще актуальны?

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> +  onPick: (date: CalendarDateShape | undefined) => void;
Еще нужно? Кажется в этом файле теперь вообще не должно быть изменений.

2021-08-11 11:25 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    deltaY = Math.round(deltaY / 3 / pixelRatio);
Здесь тоже, если обновлять `this.touchStartY` на move и не делить на 3, то вполне адекватный скролл получается. А сейчас не очень.

2021-08-11 11:27 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +   * При использовании не работает проп `autoFocus`
Я думаю, что сейчас автофокус работает норм. Календарь не открывается, но фокус есть. Можно удалить примечание.

2021-08-11 13:47 UTC, StathamJason commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +   * При использовании не работает проп `autoFocus`
@zhzz добавил на это место заметку, что ios не умеет в minDate и maxDate

2021-08-12 06:29 UTC, zhzz approved these changes
Ну вот, считай с мобильными багами в DatePicker разобрались.

2021-08-17 03:44 UTC, merged