2219 context for modal children
skbkontur/retail-ui pull request #2449
Opened 2021-06-21 08:49 UTC by khlutkova

2021-06-23 07:07 UTC, zhzz requested changes

2021-06-23 07:07 UTC, zhzz commented on packages/react-ui/components/Modal/__stories__/Modal.stories.tsx
> +  const footer = <Modal.Footer sticky={sticky}>Footer</Modal.Footer>;
Здесь Header, Body и Footer не завернуты в другие компоненты. Фактически, получилось то же самое, что и положить их в Modal напрямую.

2021-06-23 07:07 UTC, zhzz commented on packages/react-ui/components/Modal/__stories__/Modal.stories.tsx
> +)
Кажется, что логика со Sticky не очень связана со вложенностью компонентов. Думаю, этот тест можно опустить. Похожий, на работу без sticky, уже есть.

2021-06-23 07:32 UTC, zhzz commented
Бонусом к этой задаче идет сделать то же самое в `SidePage` 😅

2021-06-24 08:05 UTC, zhzz requested changes

2021-06-24 08:05 UTC, zhzz commented on packages/react-ui/components/Modal/ModalFooter.tsx
> +    }
Только что заметил, что эти флаги нигде не сетятся в `false`. Хотя должны, на unmount компонентов и изменении пропа `panel`. Иначе содежимое модалки может измениться, а стили останутся прежними.

2021-06-25 09:30 UTC, zhzz requested changes

2021-06-25 09:30 UTC, zhzz commented on packages/react-ui/components/Modal/ModalFooter.tsx
> +      modal.setHasPanel?.();
Если `panel` поменяется на `false`, то флаг в контексте не обновится.

2021-06-25 09:30 UTC, zhzz commented on packages/react-ui/components/Modal/ModalFooter.tsx
>      setScrollBarWidth(getScrollWidth());
`setScrollBarWidth`  стал вызываться чаще чем было раньше. Но это место можно совсем отрефакторить. На самом деле, ширину скроллбара незачем хранить в стейте. Она вычисляется один раз внутри `getScrollWidth`, потом кэшируется и уже никогда не меняется. Значит можно эту функцию просто каждый раз вызывать на месте, где она нужна, не сохраняя значение в стейт.

2021-06-28 04:18 UTC, zhzz submitted a review, later dismissed

2021-06-28 10:38 UTC, lossir reviewed
С притером проблемы в нескольких файлах. Можно настроить IDE на авто-запуск притера, например, при сохранении файла. И до кучи задать авто-сохранение файла.

2021-06-28 10:38 UTC, lossir commented on packages/react-ui/components/Modal/__stories__/Modal.stories.tsx
> +};
Тут можно убрать лишнюю обёртку и сократить название т.к. `sticky` по умолчанию `true`.

```suggestion
export const ModalWithChildrenFromOtherComponent = () => (
  <Modal>
    <Header />
    <Body />
    <Footer />
  </Modal>
);

ModalWithChildrenFromOtherComponent.story = {
  parameters: { creevey: { tests: TopMiddleBottomModalTests } },
};
```

2021-06-28 10:38 UTC, lossir commented on packages/react-ui/components/Modal/Modal.tsx
> +    const { hasHeader, hasFooter, hasPanel }= this.state;
Беда с притером.

2021-06-28 10:38 UTC, lossir commented on packages/react-ui/components/Modal/__stories__/Modal.stories.tsx
> +const Footer = () => <Modal.Footer>Footer</Modal.Footer>;
Для `<Modal.Footer>` можно добавить проп `panel`. Так мы будем тестировать сразу все нужные состояния.

```suggestion
const Footer = () => <Modal.Footer panel>Footer</Modal.Footer>;
```

2021-06-30 10:07 UTC, zhzz approved these changes

2021-06-30 11:59 UTC, lossir approved these changes

2021-07-13 15:54 UTC, merged