2453 context for sidepage children
skbkontur/retail-ui pull request #2455
Opened 2021-06-24 12:14 UTC by khlutkova

2021-06-28 07:41 UTC, zhzz requested changes
В целом все круто. Предлагаю чуть доработать тест.

2021-06-28 07:41 UTC, zhzz commented on packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx
> +}
Думаю, лучше будет сделать отдельную историю и тест. Чтобы основной сценарий, когда вложенности нет, тоже тестировался. К тому же, все эти флаги влияют только на отступы в компоненте `SidePage.Container`, который в `Sample` не используется.

А в отдельном тесте можно будет проверить, что вложенность работает, все отступы применяются. Также, можно добавить переключение panel/header/footer, чтобы убедиться, что отступы меняются.

2021-06-30 11:29 UTC, zhzz requested changes

2021-06-30 11:29 UTC, zhzz commented on packages/react-ui/components/SidePage/__stories__/SidePage.stories.tsx
> +SidePageWithChildrenFromOtherComponentWithPanel.story = { parameters: { creevey: { tests: tests } } };
Все-таки тест еще не совсем полный. 

Мы тут по сути должны протестировать работу флагов hasHeader/hasFooter/hasPanel, механизм которых переделали. А они влияют только на отступы в SidePage.Container. Т.е. нужно его заиспользовать в истории и протестировать, что все отсутупы работают как нужно.

И еще, на самом деле, можно обойтись одной историей, чтобы не плодить их слишком много. Для это нужно добавить кнопки, которыми будем включать/выключать header/footer/panel в определенный момент и фоткать отступы SidePage.Container. Примеры с кнопками есть в соседних историях.

Получается, нужно 5 скриншотов (с хедером, с футером, без хедера, без футера, с футером-панелью), на которых будут видны соответствующие отступы у SidePage.Container.

2021-07-13 09:53 UTC, zhzz approved these changes

2021-07-13 13:23 UTC, lossir approved these changes
Круто) 🔥

2021-07-13 18:32 UTC, merged