fix(InputLikeText): a hack for IE11 when opened in Popup
skbkontur/retail-ui pull request #2458
Opened 2021-06-30 11:16 UTC by lossir

2021-07-01 13:24 UTC, zhzz requested changes

2021-07-01 13:24 UTC, zhzz commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      )
Здесь тогда больше подойдет другая функция из `listenFocusOutside`, чтобы на детали реализации рендер-контейнеров не завязываться.

```suggestion
      findRenderContainer(node, document.body)
```

2021-07-01 13:24 UTC, zhzz commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Если быть точнее, то причина не в blur, а в focus. Лучше поправить комментарий, чтобы не вводил в заблуждение.

2021-07-02 04:49 UTC, lossir commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      )
Ну, мы всё равно завязываемся на эти детали, просто опосредованно)
Но я согласен, что лучше использовать уже готовую функцию.

2021-07-02 04:49 UTC, lossir commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Почему причина в `focus`?
Вызов `selectNodeContents()` ниже приводит к всплытию `blur`. Из-за чего ещё ниже приходится дёргать `focus`.
Соглашусь, из комментария этого не понятно, т.к. метод `focus()` вызывается непосредственно, а про `blur` ничего не понятно, не прочитав описания этого ПРа.

Можно уточнить в комментарии именно этот момент:
```
Code below (directly due to selectNodeContents) causes Popup to close after triggering the blur event on the body in IE11
```
---

Если причина всё-таки в `focus`, то поясни, пожалуйста.

2021-07-02 05:19 UTC, zhzz commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Согласно моим раскопкам, в результате `selectNodeContents` происходит фокус на `body`, который регистрируется в `listenFocusOutside` и именно он закрывает выпадаху. А `blur` там конечно тоже есть, но он в принципе не всплывает.

А почему ты считаешь, что виноват `blur`?

2021-07-02 07:20 UTC, lossir commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Да, начинается всё с фокуса на `body`. Но именно `blur` на `window` в `RenderLayer` дёргает `onFocusOutside()` и `Popup` закрывается. Поэтому мне кажется, что виновник всё-таки блюр.

В комментарии можно добавить ссылку на метод `attachListeners` в файле `RenderLayer`.

2021-07-02 08:22 UTC, zhzz commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Но `blur` на `window` там не срабатывает и ничего не дергает. Срабатывает фокус и его обработчик. Это видно, если подебажить все навешиваемые хэндлеры в `RenderLayer`.

2021-07-02 08:42 UTC, lossir commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Хм... я вижу другое.

<details>
<summary>Если добавить логирование здесь</summary>

![image](https://user-images.githubusercontent.com/2708211/124246945-d569d100-db3a-11eb-9c87-b19ec0f7ad39.png)

</details>

<details>
<summary>То в IE я вижу это</summary>

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/2708211/124247119-01855200-db3b-11eb-80c9-2742aec492b3.gif)

</details>

2021-07-02 08:48 UTC, zhzz commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Тот же самый `this.handleFocusOutside` навешивается и на фокус. Если залогируешь именно блюр, то его не увидишь.

2021-07-02 08:54 UTC, lossir commented on packages/react-ui/internal/InputLikeText/InputLikeText.tsx
> +      // Code below causes Popup to close after triggering the blur event on the body in IE11
Да, ты прав.. Я совсем не заметил `listenFocusOutside` 🤕

2021-07-23 09:49 UTC, zhzz approved these changes

2021-07-23 09:49 UTC, merged