fix(Combobox): counting the number of items found
skbkontur/retail-ui pull request #2465
Opened 2021-07-02 11:46 UTC by BalabuevIlya

#2066  Валидация при подсчете количества найденных элементов.

2021-07-06 10:30 UTC, lossir commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +   * В found не учитываются ReactNode полученные из getItems
Вроде, не совсем это происходит.
Учитывается только компонент `MenuItem` (подпадает под `ReactNode`), которым по умолчанию оборачиваются объекты, возвращаемые функцией `getItems()`.

2021-07-06 10:30 UTC, lossir commented on packages/react-ui/internal/CustomComboBox/__stories__/ComboBoxView.stories.tsx
> +  },
Тест хороший. Но попробуй сделать как в других тестах. Расширь зону скрина с помощью паддингов или ширины/высоты. Чтобы выпадашка вписывалась в эту зону и ничего лишнего не было

2021-07-06 13:39 UTC, BalabuevIlya commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +   * В found не учитываются ReactNode полученные из getItems
Если из `getItems` возвращаются `ReactNode`, то они не обворачиваются.

2021-07-07 07:15 UTC, lossir commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +   * Учитывается только компонент MenuItem, которым по умолчанию оборачиваются объекты, возвращаемые функцией getItems().
```suggestion
   * `found` учитывает только компонент `MenuItem`. Им "оборачиваются" элементы, возвращаемые `getItems()`.
```

2021-07-08 13:19 UTC, lossir approved these changes

2021-07-09 05:07 UTC, zhzz requested changes

2021-07-09 05:07 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +    if (renderedItems && renderTotalCount && totalCount && renderedItems.length < totalCount) {
По идее, сообщение должно выводится, когда реальных элементов меньше чем totalCount. 

```suggestion
    if (renderedItems && renderTotalCount && totalCount && countItems.length < totalCount) {
```

В остальном - все круто.

2021-07-13 07:53 UTC, zhzz approved these changes

2021-07-13 10:29 UTC, merged