feat(Tabs): add generic type for value instead of string
skbkontur/retail-ui pull request #2471
Opened 2021-07-07 07:24 UTC by HelenaIsh

2021-07-12 09:50 UTC, lossir reviewed
Можно переписать одну из историй в `Tabs.stories.tsx`, с использованием дженерика.

2021-07-12 09:50 UTC, lossir commented on packages/react-ui/components/Tabs/TabsContext.ts
> +export const TabsContextDefaultValue: TabsContextType<any> = {
Мне кажется использование здесь `any` приемлемо, но я не уверен) @zhzz

2021-07-12 09:50 UTC, lossir commented on packages/react-ui/components/Tabs/Tabs.tsx
> -    onValueChange: PropTypes.func,
С этой строкой Typescript не видит значение по умолчанию в дженерике. Не смог порешать обновлением зависимостей, и нигде не нашёл упоминаний этой проблемы. @zhzz

2021-07-12 13:55 UTC, zhzz commented on packages/react-ui/components/Tabs/TabsContext.ts
> +export const TabsContextDefaultValue: TabsContextType<any> = {
Используя `any` мы по сути перечеркиваем все усилия по типизации `id` внутри `TabsContextType`. Ведь в результате, мы можем передать в `TabsContext.Provider` значения любых типов. Однако, кажется, что нормального варианта использовать generic в контексте не существует. Так что, выбора особо нет. Я бы только сделал `any` типом по умолчанию, чтобы не нужно было его явно больше нигде указывать.

2021-07-12 13:56 UTC, zhzz commented on packages/react-ui/components/Tabs/Tabs.tsx
> -    onValueChange: PropTypes.func,
Можно ее удалить, если что. Не очень критично.

2021-07-26 16:33 UTC, lossir reviewed
Добавь ещё для какой-нибудь существующей стори типизацию `value`, как в ишью.
Своеобразный тест будет.

2021-07-27 06:26 UTC, lossir approved these changes

2021-07-27 06:54 UTC, zhzz requested changes

2021-07-27 06:54 UTC, zhzz commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +type Mountain = "fuji" | "tahat" | "alps";
В `<Tab />` id еще остался типа `string`. Там тоже нужен generic, иначе смысла в изменениях не много.

Попробуйте сделать тип Mountain в истории enum-ом.

2021-07-27 07:12 UTC, zhzz requested changes

2021-07-27 07:12 UTC, zhzz commented on packages/react-ui/components/Tabs/Tabs.tsx
>      value: PropTypes.string.isRequired,
В propTypes еще стоит проверка на string. После изменений по сути там тип может быть любой.

2021-08-02 22:52 UTC, lossir requested changes

2021-08-02 22:52 UTC, lossir commented on packages/react-ui/components/Tabs/Tabs.tsx
> +  private getTab = (id: T): Tab<T> | null => {
Здесь давай применим интерфейс контекста, раз метод реализует именно его. Меньше дублирования:
```suggestion
  private getTab: TabsContextType<T>['getTab'] = (id: T)=> {
```

В других методах надо сделать так же.

2021-08-02 22:52 UTC, lossir commented on packages/react-ui/components/Tabs/Tab.tsx
> +export class Tab<T = string> extends React.Component<TabProps<T>, TabState> {
Хоть номинально `id`(`value`) стало любого типа, компонент `Tab` содержит несколько ограничений по типу  `typeof id === 'string'`. Получается, если `id` не является строкой, то компонент перестаёт функционировать.

<details>
<summary>Поиск 'string' по файлу</summary>

![image](https://user-images.githubusercontent.com/2708211/127932380-7340e5eb-309a-4efa-b795-1b2022536516.png)

</details>

Также, в качестве `id` может выступать проп `href`, который точно может быть только строкой:
https://github.com/skbkontur/retail-ui/blob/7513ab9f2f1adbd127d63d933b6ecc8192e31ccf/packages/react-ui/components/Tabs/Tab.tsx#L237

---

Поэтому стоит немного ограничить тип дженерика:
```suggestion
export class Tab<T extends string = string> extends React.Component<TabProps<T>, TabState> {
```

Это надо будет добавить дженерикам в компонентах, пропах и в дженерику контекста.

2021-08-02 22:52 UTC, lossir commented on packages/react-ui/components/Tabs/Tabs.tsx
> -    value: PropTypes.string.isRequired,
Это можно будет вернуть.

2021-08-02 22:52 UTC, lossir commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +      <Tabs value={this.state.active} onValueChange={(v: string) => this.setState({ active: v })}>
Это всё тоже надо будет удалить. Старый код должен работать без приведения к типу.

2021-08-03 03:36 UTC, zhzz commented on packages/react-ui/components/Tabs/Tab.tsx
> +export class Tab<T = string> extends React.Component<TabProps<T>, TabState> {
Есть и другой путь. Понять, актуально ли еще это ограничение, и, если нет, то расширить его.

2021-08-03 07:09 UTC, lossir commented on packages/react-ui/components/Tabs/Tab.tsx
> +export class Tab<T = string> extends React.Component<TabProps<T>, TabState> {
Это уже немного сложнее, чем просто добавить дженерик. Можно завести отдельную задачу, и как-нибудь заняться этим. Пока, вроде, не было ни одного запроса на снятие этого ограничение.

2021-08-03 07:30 UTC, zhzz commented on packages/react-ui/components/Tabs/Tab.tsx
> +export class Tab<T = string> extends React.Component<TabProps<T>, TabState> {
Я считал, что это входит в задачу добавления дженерика. Но можно и правда ограничиться строковыми типами,

2021-08-09 18:26 UTC, zhzz approved these changes
🤘

2021-08-09 18:32 UTC, lossir approved these changes

2021-08-09 21:39 UTC, merged