feat(ScrollContainer): horizontal scroll
skbkontur/retail-ui pull request #2473
Opened 2021-07-08 10:26 UTC by BalabuevIlya

#1931 Добавление горизонтального скролла

2021-07-21 20:26 UTC, lossir reviewed
Еще надо обновить текст документации компонента. Сейчас там говорится, что горизонтальный скролл останется нативным.

Остаётся много повторяющегося кода. Однако, не уверен, что более "глубокая" оптимизации стоит того. 

> Добавить состояния left, scroll, right ?  

Да, думаю стоит добавить. Надо будет разделить `scroll` на горизонтальный и вертикальный

> Реализовывать логику scrollTo, scrollRight, scrollLeft ?

Тоже стоит. Опять же, `scrollTo()` надо будет как-то разделить

> Если надо включать горизонтального скролла через проп?

Думаю не стоит. комбинированный вариант выглядит будто что-то сломалось. Вряд ли кто-то сознательно выберет такой вариант

2021-07-27 03:37 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.styles.ts
>        /* IE sometimes enabled scroll: http://codepen.io/anon/pen/RRrLNX */
Но все равно тот код при желании можно воспроизвести и он проиллюстрирует проблему. Не нужно удалять.

2021-07-27 04:23 UTC, zhzz requested changes
Круто, работает!

Есть еще несколько предложений как улучшить:

1. Получилось много дублированного кода между вертикальным и горизонтальным скроллбарами. Думаю, в пору завести отдельный компонент, например `<ScrollBar ... />`, куда вынести все, что непосредственно связано только со скролбарами. 
```
<ScrollBar asix="y" ... />
<ScrollBar asix="x" ... />
```
Это должно сильно упростить сам ScrollContainer и избавить нас от лишнего дублирования.

2. В закоммиченных файлах есть 30 неиспользуемых скриншотов. Они лишние, нужно удалить.
<details>
with only custom horizontal scroll/addContent/chrome/scroll0.png

with only custom horizontal scroll/addContent/chrome/addContent.png

with only custom horizontal scroll/addContent/chrome/scroll100.png

with only custom horizontal scroll/addContent/chrome/scroll50.png

with only custom horizontal scroll/addContent/chrome8px/addContent.png

with only custom horizontal scroll/addContent/chrome8px/scroll0.png

with only custom horizontal scroll/addContent/chrome8px/scroll100.png

with only custom horizontal scroll/addContent/chrome8px/scroll50.png

with only custom horizontal scroll/addContent/firefox/addContent.png

with only custom horizontal scroll/addContent/firefox/scroll0.png

with only custom horizontal scroll/addContent/firefox/scroll100.png

with only custom horizontal scroll/addContent/firefox/scroll50.png

with only custom horizontal scroll/addContent/firefox8px/addContent.png

with only custom horizontal scroll/addContent/firefox8px/scroll0.png

with only custom horizontal scroll/addContent/firefox8px/scroll100.png

with only custom horizontal scroll/addContent/firefox8px/scroll50.png

with only custom horizontal scroll/addContent/ie11/addContent.png

with only custom horizontal scroll/addContent/ie11/scroll0.png

with only custom horizontal scroll/addContent/ie11/scroll100.png

with only custom horizontal scroll/addContent/ie11/scroll50.png

with only custom horizontal scroll/addContent/ie118px/addContent.png

with only custom horizontal scroll/addContent/ie118px/scroll0.png

with only custom horizontal scroll/addContent/ie118px/scroll100.png

with only custom horizontal scroll/addContent/ie118px/scroll50.png

with only custom horizontal scroll/chrome.png

with only custom horizontal scroll/chrome8px.png

with only custom horizontal scroll/firefox.png

with only custom horizontal scroll/firefox8px.png

with only custom horizontal scroll/ie11.png

with only custom horizontal scroll/ie118px.png
</details>

3. В документации все еще остается устаревший комментарий. Можно обновить. 
![image](https://user-images.githubusercontent.com/4607770/127093466-0d228f55-a5ca-4d21-ab61-364c194bdda6.png)

2021-07-29 03:27 UTC, zhzz requested changes

2021-07-29 03:27 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    });
Это тоже можно делать в самом скроллбаре.

2021-07-29 03:27 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +            [styles.innerBottomIndent(this.theme)]: this.state.x.active && this.state.y.active,
Тут условие на наличие обоих скролбаров. Разве не горизонтальный только нужен?

2021-07-29 03:27 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +      this.props.onScrollStateChange?.(scrollYState, scrollXState);
Если избавиться от стейта в контейнере, то здесь можно было бы придумать какие-то публичные геттеры у скроллбаров для получения текущей фазы скролла.

Но еще возник такой вопрос. Если в какой-то момент один из скроллбаров пропадет, то в onScrollStateChange продолжит приходить его старое значение? У меня все это время крутится мысль, а не стоит ли лучше сделать два отдельных пропа (`onScrollYStateChange/onScrollXStateChange`)? Так и вызовов лишних не будет, когда меняется только один.

2021-07-29 06:40 UTC, BalabuevIlya commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +      this.props.onScrollStateChange?.(scrollYState, scrollXState);
Не хотелось бы сломать кому-то что-то. если только сделать такое с сохранением старого , а потом удалить.

2021-07-29 06:44 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +      this.props.onScrollStateChange?.(scrollYState, scrollXState);
Да, с временным сохранением старого я имел в виду.

2021-07-29 10:14 UTC, BalabuevIlya commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    this.handleInnerScrollAxisWheel(event, 'x');
не работало, т.к. не было проверки на `shiftKey`. Поправил

2021-07-29 10:26 UTC, BalabuevIlya commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +      this.props.onScrollStateChange?.(scrollYState, scrollXState);
> Если в какой-то момент один из скроллбаров пропадет, то в onScrollStateChange продолжит приходить его старое значение?

Будет приходить дефолтное значение `top` или `left`

2021-08-03 03:14 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    this.handleInnerScrollAxisWheel(event, 'x');
Еще остались лишние вызовы. Когда скролишь по X, обработчик для Y тоже отрабатывает, и может сделать `preventDefault` когда не нужно.

2021-08-03 03:21 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/__tests__/ScrollContainer-test.tsx
> +  });
Довольно странный получается тест. Он будет проходить, даже если в ScrollContainer ничего не отрендерено. 

И до этого тест получается совсем не работал.

Думаю, эти сценарии надежно проверяются скриншотами. Может удалить их отсюда?

2021-08-03 04:05 UTC, BalabuevIlya commented on packages/react-ui/components/ScrollContainer/__tests__/ScrollContainer-test.tsx
> +  });
> Думаю, эти сценарии надежно проверяются скриншотами. Может удалить их отсюда?

ну тут я не преследовал цели проверить, что все работает правильно. Хотелось проверить, что контейнер и скроллбары рендерятся.

2021-08-03 04:08 UTC, BalabuevIlya commented on packages/react-ui/components/ScrollContainer/__tests__/ScrollContainer-test.tsx
> +  });
Предыдущий тест просто смотрел, что в стейте `scrollState === 'top'`, хотя это дефолтное значение.

2021-08-06 03:21 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/__tests__/ScrollContainer-test.tsx
> +  });
Рендер скроллбаров хорошо проверяется скриншотами. А эти тесты, на мой взгляд, оставляют больше вопросов, чем дают ответов. Я бы убрал их все-таки.

2021-08-11 04:06 UTC, zhzz requested changes

2021-08-11 04:06 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    this.handleInnerScrollAxisWheel(event, 'x');
Эта проблема еще присутствует. На истории с горизонтальным скроллом, если включить проп  `preventWindowScroll` и проскроллить вправо, влево с нажатым `shift` уже скроллить не будет.

![image](https://user-images.githubusercontent.com/4607770/128967956-41827ebe-726d-4132-beb4-ea49aea86f31.png)

2021-08-11 04:25 UTC, zhzz commented
Заменил data-tid'ы глобальными классами для единообразия, раз они уже не очень нужны.

2021-08-11 21:03 UTC, lossir reviewed
У нас тут завалялся такой хэлпер - [MouseDrag](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/lib/events/MouseDrag.ts).
Если он окажется полезен, то будет круто)

2021-08-12 14:43 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    const refSctollBar = axis === 'x' ? this.refScrollBarX : this.refScrollBarY;
```suggestion
    const refScrollBar = axis === 'x' ? this.refScrollBarX : this.refScrollBarY;
```

2021-08-13 06:08 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  onScrollYStateChange?: (scrollState: ScrollContainerScrollYState) => void;
Думаю второй вариант норм

2021-09-10 05:08 UTC, zhzz approved these changes
Нужно будет засквошить при влитии.

2021-09-14 19:54 UTC, lossir approved these changes

2021-09-15 22:30 UTC, merged