[Select]: Адаптивная версия
skbkontur/retail-ui pull request #2475
Opened 2021-07-09 08:39 UTC by StathamJason

МВП адаптивной версии селекта

- Меню меняет свою высоту в зависимости от контента
- Сверху всегда остается отступ 40px
- Добавлен проп `mobileMenuHeaderText` - текст заголовка выпадающего меню в мобильной версии
- При передачи пропа `search` меню раскрывается на всю высоту, под заголовком появляется инпут для поиска
- Появился внутренний компонент `MobileMenuHeader`
  - Меняет высоту в зависимости от заголовка
  - Текст обтекает крестик
  - Можно передать ребенка для закрепления снизу заголовка

Необходимо будет после влития пр-а с новой версией сторибука настроить дефолтный лэйаут для мобильной истории

2021-07-28 10:01 UTC, StathamJason commented on packages/react-ui/components/Select/Select.tsx
> +      });
Так, здесь надо добавить `else` если медиа-запрос не выполняется и флаг равен `true`, то сетить его в `false`

2021-07-30 06:46 UTC, zhzz reviewed
Еще не все посмотрел. Пока заметил, что под коротким списком вся страница продолжает скролиться. Наверное так не должно быть. 

И на моем телефоне у большого списка почему-то нет отступа сверху.

![image](https://user-images.githubusercontent.com/4607770/127612256-676868ab-5d5a-42e4-8472-1eff197644cb.png)

2021-07-30 06:46 UTC, zhzz commented on packages/react-ui/components/Select/__tests__/Select-test.tsx
> +
Можно замокать один раз в  `test-setup.js`

2021-07-30 06:46 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +  }
Есть [MediaQueryList events change](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#events) и аналог для IE.

2021-08-16 08:01 UTC, zhzz commented
@dzekh @StathamJason 

#### Адаптивность. Выпадашки. Предложения по реализации и макетам. 

Вероятно, какие-то предложения по дизайну будут наивными и нерабочими. Наверное их уже обсуждали. Думаю, стоит еще раз к ним вернуться.

Все выпадашки (тултипы, меню, комбобоксы и тд) могут выглядеть и работать одинаково. Как правило, это какой-то контент, который открывается снизу экрана (в двух режимах высоты), имеет на фоне вуаль и дополнительный элемент для закрытия (крестик или холдер). В случае select/autocomplete/combobox еще может быть инпут для поиска (тоже одинаковый). Мы можем сильно упростить реализацию (и, возможно, даже улучшить UX) если все эти компоненты универсализируем:

1. Один и тот же механизм открытия. Пусть все они открываются одинаково (не на весь экран (как комбобокс и автокомплит), в двух режимах высоты). 
2. Один и тот же элемент закрытия. Везде либо холдер, либо крестик. Может вообще ничего, только клик на фон.
3. Отказ от заголовка. Он привносит разницу между API контрола в десктопной и мобильной версиях. Такого быть не должно, по идее. Если по умолчанию использовать placeholder, то стоит ожидать, что в большинстве случаев он будет пустым. Да и если делать отдельным пропом, то тоже будет пустым. В нативных селектах заголовка нет.
4. В любом случае, все выпадшки построены на основе Popup либо DropdownContainer (когда-нибудь останется только Popup). Большую часть изменений для реализации адаптивности вышеперечисленных компонентов стоит перенести в эти общие компоненты, чтобы переиспользовать их.

Таким образом, мы сможем минимальными усилиями, в два счета реализовать адаптивность по всех выпадашках (Select/Autocomplete/ComboBox/DropdownMenu/Kebab/Tooltip/Hint). Без дублирования. И работать они будут одинаково, что вроде важно для UX.

2021-09-28 06:58 UTC, zhzz requested changes
С MobilePopup нравится как все выглядит. Нужно только мелочи поправить и, думаю, можно переходить к Autocomplete и ComboBox.

С MobileLayout я еще поэкспериментирую.

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/internal/MobileMenu/MobilePopup.tsx
> +   */
Заголовок разве не должен быть сверху? А еще жирным.

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/internal/MobileMenu/MobilePopupHeader/MobilePopupHeader.tsx
> +  getHeightOnMount?: (height: number) => void;
```suggestion
```

Вроде тоже больше не нужен.

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/internal/MobileMenu/MobilePopupHeader/MobilePopupHeader.tsx
> +        onClick={(e) => e.stopPropagation()}
Хорошо бы все вынести в методы

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static mobileMenuItemPadding = '12px 16px';
Не стоит ли в таких переменных `modile` добавлять в конце, как модификатор? Вначале идет имя компонента, будет путаница с `mobilePopup...`. 
```suggestion
  public static menuItemPaddingMobile = '12px 16px';
```

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  //#endregion
Переменные нужно переименовать на `mobilePopup...`.

2021-09-28 06:58 UTC, zhzz commented on packages/react-ui/components/Select/Select.styles.ts
> +      width: 100%;
Вот это потенциально ломающее изменение. Может быть завести переменную и оставить пока прежнее значение до ближайшей мажорной версии?

2021-09-28 07:24 UTC, lossir requested changes

2021-09-28 07:24 UTC, lossir commented on packages/react-ui/components/MobileLayout/MobileLayout.tsx
> +        this.prepareMediaQueries();
Сейчас листенеры создаются для каждого экземпляра контрола с декоратором. Нехорошо.
Стоит реализовать так, чтобы слушатели были для всех одни, а разные только обработчики. Примерно как в компоненте `LayoutEvents`.
Думаю, вряд ли кто-то будет на лету менять `mobileMediaQuery`... вероятно, такой сценарий можно не учитывать.

2021-09-28 07:24 UTC, lossir commented on packages/react-ui/components/MobileLayout/MobileLayout.tsx
> +    }
Метод `render()` возвращает тип [`ReactNode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L490)
Проще просто избавиться от типа, и от фрагмента.
```suggestion
    public render() {
      return super.render();
    }
```

2021-09-28 08:24 UTC, StathamJason commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  maxHeightFor?: 'all' | 'items';
А точно не нужны? Я просто оставил его понятнее

2021-09-28 08:38 UTC, StathamJason commented on packages/react-ui/internal/Menu/Menu.tsx
> +  disableScrollContainer?: boolean;
Оставлю только метод `getChildList`, так красивее

2021-09-28 08:49 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  maxHeightFor?: 'all' | 'items';
Новый код немного усложняет реализацию компонента, но нигде не используется. Я думаю, стоит оставить комментарий для понятности, но неиспользуемый код убрать, пока он действительно где-то не понадобится.

2021-09-28 08:51 UTC, StathamJason commented on packages/react-ui/internal/MobileMenu/MobilePopup.tsx
> +   */
C толщиной все в порядке, на макетах просто лаб гротеск, у него видимо между 400 и 500 разница видна

2021-09-30 07:59 UTC, zhzz commented on packages/react-ui/components/MobileLayout/MobileLayout.tsx
> +export function mobileLayout<T extends new (...args: any[]) => React.Component<any, MobileLayoutState>>(
Можно `responsiveLayout`

2021-09-30 08:06 UTC, zhzz commented on packages/react-ui/components/MobileLayout/MobileLayout.tsx
> +        this.prepareMediaQueries();
`mobileMediaQuery` может меняться, например, для разных компонентов, или для отключения адаптивности в отдельных местах. Думаю, стоит учесть это.

Согласен насчет аналога `LayoutEvents`. Может быть не в первой итерации, возможно в будущем, но стоит это оптимизировать.

2021-09-30 08:39 UTC, zhzz commented on packages/react-ui/components/MobileLayout/MobileLayout.tsx
> +      this.state = { ...this.state, layout: LayoutMode.Desktop };
Мои финальные мысли по поводу текущей реализации декоратора.

1. Менять стейт компонента где-то за кулисами (в декораторе), считаю, нехорошо. Когда знаешь как работает стейт и видишь там поле, которое в самом компоненте нигде не проставляется, возникают вопросы.
2. Нужно дать использовать наш механизм определения текущего лэйаута наружу. Декоратор для этого плохо подходит. Нужен отдельный компонент или контекст.

В качестве решения предлагаю вынести всю логику работы с media queries и определения лэйаута в отдельный публичный компонент, например, `ResponsiveLayout`, с такими пропами:

```ts
{
  onLayoutChange?: (layout: LayoutMode) => void;
  children?: React.ReactNode | (layout: LayoutMode) => React.React.Node;
} 
```

Его можно будет использовать внутри и снаружи библиотеки.

Далее, в декораторе лишь останется обернуть все в этот компонент и проставить нужные геттеры. Так будет проще и прозрачнее.

```tsx
export function responsiveLayout<T extends new (...args: any[]) => React.Component>(WrappedComp: T) {
  const ComponentWithLayout = class extends WrappedComp {
    public layout: LayoutMode = LayoutMode.Desktop;

    public get responsiveLayout(): LayoutMode {
      return this.layout;
    }

    public get isMobileLayout(): boolean {
      return this.layout === LayoutMode.Mobile;
    }

    public set isMobileLayout(value: boolean) {
      //
    }

    public render(): JSX.Element {
      return (
        <ResponsiveLayout>
          {(layout: LayoutMode) => {
            this.layout = layout;
            return super.render();
          }}
        </ResponsiveLayout>
      );
    }
  };
```

2021-11-29 09:39 UTC, zhzz approved these changes

2021-11-29 09:45 UTC, merged