feat(SidePage): change close on cross icon from link to button
skbkontur/retail-ui pull request #2478
Opened 2021-07-12 08:19 UTC by HelenaIsh

Изменила закрытие по крестику с ссылки на кнопку, фокус добавился автоматом

2021-08-02 10:37 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +        height: ${t.sidePageCloseIconSize};
Будет лучше парсить число(`parseInt`) из этой переменной, и прокидывать пропом `size` в саму иконку `<CrossIcon />`.

2021-08-06 07:00 UTC, lossir commented
При попытке задать `size` для `<CrossIcon />` выяснилась небольшая проблема. У нас есть специальная обёртка `SvgIcon` для внутренних иконок, которая добавляет проп `size` и апскелинг иконку по высоте и ширине на `1.14285714`. Для иконок из пакета иконок мы избавились от этого апскейлинга, т.к. он уже не нужен. Но здесь мы забыли его удалить =)

Мы можем:
- Либо использовать эту обёртку как сейчас, и удалить апскейлинг потом.
- Либо наморозить этот ПР, пока не избавимся от апскейлинга везде.

2021-08-09 05:28 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.tsx
> +              <FocusLock disabled={disableFocusLock} autoFocus={false}>
Добавила || вместо && потому, что если blockBackground === true, фокус лок все равно должен быть изначально заблокирован

2021-08-23 05:30 UTC, lossir reviewed
Иконка стала прыгать по высоте при прилипании. Думаю, изначально на кнопку добавили отдельный `<Sticky />`, чтобы этого не было.
| Было | Стало |
| --- | --- |
| ![ezgif com-gif-maker (17)](https://user-images.githubusercontent.com/2708211/130394154-65eb4f66-a200-42bd-84ec-ebb82fe3cdf3.gif) | ![ezgif com-gif-maker (18)](https://user-images.githubusercontent.com/2708211/130394177-0153afc2-072a-45e5-b401-60c18f5376d1.gif) |

Стоит уточнить у проектировщиков, на сколько этот момент важен. Поскольку текст заголовка тоже заметно дёргается и вроде норм.
И если они скажут, что это не принципиально, то можно избавиться от этого отдельного `<Sticky />` и для фиксации крестика смотреть только на `isReadyToFix`.

2021-08-23 07:01 UTC, dzekh commented
Ну прикольно, конечно, когда не дергается, лучше сделать как раньше, если это не займет много ресурсов на разработку

2021-08-25 10:11 UTC, HelenaIsh commented
Пробовала убрать <Sticky /> у кнопки:

2021-09-08 04:38 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      margin: -${t.sidePageCloseButtonClickAreaX} 0 0;
Для этого шрифта просто повезло, что подошел такой margin. Но, если изменить шрифт или высоту строки, то крестик уедет: 
![image](https://user-images.githubusercontent.com/32093844/132447265-46ad65c7-5da1-41bb-82ec-db932d972886.png)
![image](https://user-images.githubusercontent.com/32093844/132447270-ffe896c0-cdef-415e-ae85-0f4ca4ac1065.png)
Не лучше ли было оставить формулу, которая, хоть и не красивая, но высчитывает положение крестика относительно текста?

2021-09-08 06:19 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      margin: -${t.sidePageCloseButtonClickAreaX} 0 0;
А это ты на какой элемент стили такие применила? И не через переменные темы, а напрямую в девтулзе?

На самом деле этот `margin` вовсе не отвечает на шрифт и не зависит от него. Он для центровки кнопки - нивелирует её же `padding`. Если менять шрифт или line-height через переменные, то кнопка всегда будет ориентироваться по базовой линии первой строки заголовка. Это благодаря вёрстке обёртки над кнопкой, которая просто повторяет стили заголовка. 
Так же удалось обойтись без обновления скриншотов (кроме одного сломанного ещё до этого и в другом месте `ZIndex/Loader and SidePage/SidePage shadow cover Loader/ie118px`).

Когда я [предлагал](https://github.com/skbkontur/retail-ui/pull/2478#discussion_r685138153) добавить отдельный `div`, то имел ввиду что-то подобное. Но получилось, что и кнопка и див отвечали за позиционирование кнопки, при этом довольно мудрёнными формулами с магическими коэффициентами.

---

Я просто не хочу мучить тебя правками и замечаниями по этому фиксу, который по-моему ушёл ни туда. И просто добью его сам. Если проложишь ревьить его - будет круто!

2021-09-08 07:21 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      margin: -${t.sidePageCloseButtonClickAreaX} 0 0;
Правда, через переменные темы такого не происходит. Значит, я ошиблась

2021-09-21 12:08 UTC, zhzz requested changes

2021-09-21 12:08 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      padding: ${t.sidePageCloseButtonClickAreaX};
Может переименовать тогда переменную? Будет как в модалке. Я думаю вероятность мала, что кто-то ее использует.

```suggestion
      padding: ${t.sidePageCloseButtonClickArea};
```

2021-09-21 12:08 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    disableFocusLock: true,
А зачем включили в IE11? Он там работает?

2021-09-21 12:30 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      }
Главная работа была сделана ещё до исправлений в [этом ПРе](https://github.com/skbkontur/retail-ui/pull/2526).
Думал потом заменить на класс `.focus-visible`.

2021-09-21 13:49 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    disableFocusLock: true,
Вроде же наоборот - отключили везде, а не только в IE11.

2021-09-21 16:08 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      width: 0;
Можно перейти на `right`, но немного иначе. Здесь такой `line-height` и нулевой  `font-size` в `.close` не просто так. Без них кнопка не будет следовать за базовой линией, а её высота будет зависеть от высоты строки.

<details><summary>Причина:</summary>

![image](https://user-images.githubusercontent.com/2708211/134206734-6769c865-44ad-4316-8a4d-d686d6d1717b.png)

</details>

2021-09-21 16:09 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      padding: ${t.sidePageCloseButtonClickAreaX};
Ну, думаю, можно.

2021-09-22 04:22 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      width: 0;
Не уверен, что кнопке нужно следовать за базовой линией. Кажется, ей место всегда в углу. А высота кнопки зависеть от высоты строки не должна, если поставить ей `line-height: 0`. Но это не критично, пусть так остается.

2021-09-22 04:23 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    disableFocusLock: true,
Да, верно, затупил.

2021-09-22 04:26 UTC, zhzz approved these changes
Кажется, правка крестика не тянет на фичу и поднятие минорной версии. Я бы пометил ее как фикс.

2021-09-22 07:08 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      width: 0;
Равнение по базовой линии заголовка - требование дизайна, на сколько помню. И так ведёт себя текущее решение с ссылкой. Для этого и указана такая `line-height`.

А говоря «..._высота будет зависеть от высоты строки_...» я подразумевал кегль шрифта заголовка... Сори, хз как так напечатал)
Дело в миксине `resetButton()`, который тянет за собой стиль `font: inherit`, из-за чего `font-size` кнопки будет наследоваться от заголовка. И мы получим это:
![image](https://user-images.githubusercontent.com/2708211/134296998-aa5c23ea-6441-4a05-897e-959827376ec0.png)

2021-09-22 10:20 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.styles.ts
> +      width: 0;
Равнение по базовой возможно актуально только для размеров заголовка по умолчанию. Не факт, что при увеличении размеров оно должно сохраняться. Остальное вроде справедливо.

2021-10-04 05:02 UTC, zhzz approved these changes

2021-10-05 08:24 UTC, lossir approved these changes

2021-10-05 10:42 UTC, merged