feat(TokenInput): add dropdown menu #1834
skbkontur/retail-ui pull request #2479
Opened 2021-07-13 05:01 UTC by HelenaIsh

Добавила необязательный boolean пропс - showDropdownMenu, который по умолчанию - false и в этом случае для TokenInput всплывающее окно будет в виде Popup как и раньше. Если установить данный пропс в true, то будет выведено dropdown menu по ширине инпута

2021-07-27 01:45 UTC, lossir commented on packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
> +    </Gapped>
Здесь `Gapped` не нужен, т.к. элемент один.
```suggestion
    <Wrapper menuWidthMode='stretch' getItems={getItems} />
```

---

Ещё можно добавить пустую строку перед объявлением этой стори, а то как-то плотничком)

2021-07-27 06:27 UTC, lossir approved these changes

2021-07-27 12:06 UTC, zhzz requested changes
Думаю, было бы лучше добавить проп width в Popup и научить его работать со значением '100%'. Это можно сделать по аналогии с тем, как работает minWidth в DropdownContainer. 

Для выравнивания добавить отдельный проп `menuAlign: 'left' | 'cursor'` на TokenInput, для ширины - проп menuWidth.
В итоге, проблему бы решала комбинация пропов: 
```
<TokenInput menuWidth="100%" menuAlign="left" />
```

Чем лучше:
1. DropdownContainer на самом деле устаревший компонент. Popup идет ему на смену.
2. Довольно необычно менять движок выпадашек на лету. У них где-то могут отличаться поведение, стили, переменные.
3. Наверняка width у Popup пригодится еще где-нибудь. Полезный был бы проп. Особенно с поддржкой "100%".
4. menuWidth и menuAlign уже распространенные пропы среди наших компонентов.

2021-08-02 14:04 UTC, zhzz requested changes
Практически то что нужно! Кажется, первая половина закоммиченых скриншотов уже не нужна. И есть еще пара предложений.

2021-08-02 14:04 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInputMenu.tsx
> +        menuWidth={menuWidth}
Сейчас в режиме `menuAlign === 'left'` выпадаха слишком низко. Регулируется пропом `margin`.

![image](https://user-images.githubusercontent.com/4607770/127873064-e162d41e-1823-4cc8-9a1f-66aef0f41d85.png)

2021-08-06 03:01 UTC, zhzz requested changes

2021-08-06 03:01 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +      return `${menuWidth}px`;
Это необязательно, потому что любые абсолютные значения с единицами и без должны корректно отработать. В том числе и строки типа `"100"`, которые воспримутся как пиксели.

2021-08-06 04:40 UTC, HelenaIsh commented on packages/react-ui/internal/Popup/Popup.tsx
> +      return `${menuWidth}px`;
Не совсем так. Если передавать строку с конкретными единицами (например, `menuWidth={'300px'}`), все отлично работает: 
![image](https://user-images.githubusercontent.com/32093844/128456413-ef117b2b-186b-4d6f-896d-cd152bbcc0e2.png)


Если передать строку без параметров `menuWidth={'300'}`, то он не переводит их в пиксели, и, кажется, вообще считает это не валидным:
![image](https://user-images.githubusercontent.com/32093844/128456520-005e530b-0b70-4a3c-a79c-36ae1e24a6e5.png)

Если передать число `menuWidth={300}`, то он сам подставляет `px` и все нормально, как в первом случае. 

Именно поэтому у меня это условие, которое проверяет есть ли конкретные единицы, тогда он просто передает строку без изменений. И если пришла строка без параметров, то я добавляю px, чтобы все корректно работало

2021-08-06 04:57 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +      return `${menuWidth}px`;
Действительно. Видимо я невнимательно протестил. 

Но в любом случае, не думаю что стоит этим заниматься. Это то, как реакт работает с атрибутом `style` везде. Если передаешь просто `"100"`, то ты сам себе злобный буратино. Нам важно корректно обработать проценты, в остальном можно положиться на реакт.

2021-08-06 06:54 UTC, zhzz submitted a review, later dismissed

2021-08-06 09:50 UTC, lossir reviewed
Круто получилось! У меня только мелкие замечания по типам и наименованию.

2021-08-06 09:50 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  menuWidth: string | number;
Здесь больше подойдёт тип `React.CSSProperties['width']`

2021-08-06 09:50 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInputMenu.tsx
> +  menuWidth: string | number;
Тут можно использовать интерфейс `TokenInputProps`, ведь проп напрямую приходит от туда:
```suggestion
  menuWidth: TokenInputProps<string>['menuWidth'];
```

<details><summary>☝️ </summary>

Мы как раз обсуждали дефолтное значение для дженерика в пропах тоже. Тут его нет, поэтому приходится обязательно указывать `<string>`.

</details>

2021-08-06 09:50 UTC, lossir commented on packages/react-ui/internal/Popup/Popup.tsx
> +  menuWidth: string | number;
Для попапа это просто ширина - `width`. Сущность menu - это абстракция конкретного использования.
И здесь так же можно использовать `CSSProperties`:
```suggestion
  width: React.CSSProperties['width'];
```

2021-08-06 09:50 UTC, lossir commented on packages/react-ui/internal/Popup/Popup.tsx
> +  };
Здесь аргумент тоже может использовать тип из интерфейса `PopupProps`.
При этом методу не обязательно указывать возвращающийся тип, т.к. метод используется в одном месте, и там допустимые типы уже заданы.

---

Также, можно объединить условия в один блок `if`
```javascript
if (typeof width === 'string' && width.includes('%'))
```

2021-08-07 09:05 UTC, lossir commented on packages/react-ui/internal/Popup/Popup.tsx
> +  private calculateMenuWidth = (menuWidth: PopupProps['width']) => {
Название метода и аргумента тоже можно поменять =)
```suggestion
  private calculateWidth = (width: PopupProps['width']) => {
```

2021-08-09 18:22 UTC, zhzz approved these changes
👍

2021-08-09 18:34 UTC, lossir approved these changes

2021-08-09 18:41 UTC, merged