fix(Tooltip): fix bug on closing tooltip
skbkontur/retail-ui pull request #2485
Opened 2021-07-15 04:25 UTC by HelenaIsh

#2269 Исправила баг, когда в firefox tooltip не закрывается если у него триггер - фокус

2021-07-16 07:58 UTC, lossir approved these changes

2021-07-19 11:12 UTC, zhzz requested changes

2021-07-19 11:12 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +          },
Если дело в этом, то почему проблема проявляется только в Firefox?

На самом деле тултип с триггером "focus" не закрывается, по другой причине. Он ждет события "focusout" на переданном в него элементе. Но в случае комбобокса, когда из него уходит фокус, внутри, реальный <Input /> [заменяется](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx#L212) <InputLikeText />. И, оказывается, в Firefox есть [баг](https://bugzilla.mozilla.org/show_bug.cgi?id=1363964), из-за которого событие "focusout" из удаленного input не возникает. В этом все дело. 
Можно починить, если для Firefox отложить момент удаления input, чтобы все события успели произойти.

Еще пригодился бы какой-нибудь тест, чтобы снова не напороться на это в будущем.

2021-07-27 05:04 UTC, zhzz commented on packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
> +      }
Я бы объединил эти два теста в один, т.е. открыли тутлип - сфоткали, и тут же закрыли тултип - сфоткали. Иначе в тесте на закрытие мы не контролируем что тултип действительно был открыт и такой тест может не работать.

2021-07-28 08:55 UTC, HelenaIsh commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      });
Потому что при клике вне инпута, иногда оставалось выделение текста. После добавления `removeAllSelections()` проблема пропала

2021-07-29 05:48 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      });
Странно, а как воспроизвести?

2021-07-29 06:31 UTC, HelenaIsh commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      });
1. закомментировать removeAllSelections()
2. запустить styleguide
3. зайти в комбобокс
4. У тултипа изменить тригер на фокус
5. Кликать поочередно на комбобокс и вне него. Иногда выделение с текста не снимается:
![doc_2021-07-29_11-18-12](https://user-images.githubusercontent.com/32093844/127442169-5f97fe22-b656-4215-9a93-627501f26602.gif)

Хотя, на самом деле, я не уверена, что это баг какой-то, тк без removeAllSelections() все тесты проходит, но на всякий случай решила оставить

2021-07-29 12:41 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +      });
Кажется и без правки такой эффект присутствовал

2021-07-29 12:42 UTC, zhzz approved these changes

2021-08-02 20:26 UTC, lossir reviewed
Пара моментов:
- Тест `select_1` попробуй заскипать для IE11. Можно просто добавить его к остальным `Combobox.stories.tsx:31`.
- Новый тест неправильно проходит в IE11 - тултип остаётся.
Этот тест надо завести. Попробуй `await delay(1000);` перед взятием скриншота.
![image](https://user-images.githubusercontent.com/2708211/127918424-1c85bfbd-26e3-402a-8da2-484cb3e337ac.png)

2021-08-03 08:31 UTC, HelenaIsh commented
> 
> 
> Пара моментов:
> 
>     * Тест `select_1` попробуй заскипать для IE11. Можно просто добавить его к остальным `Combobox.stories.tsx:31`.
> 
>     * Новый тест неправильно проходит в IE11 - тултип остаётся.
>       Этот тест надо завести. Попробуй `await delay(1000);` перед взятием скриншота.
>       ![image](https://user-images.githubusercontent.com/2708211/127918424-1c85bfbd-26e3-402a-8da2-484cb3e337ac.png)

В IE новый тест проходит правильно, тултип убирается. Это было исправлено в коммите 0f69555: 
![image](https://user-images.githubusercontent.com/32093844/127983586-4b7e82ba-0181-4008-a0ba-b6869b63f615.png)
Оказалось, что в IE такой же баг как и в Firefox. Исправила https://github.com/skbkontur/retail-ui/blob/fb9e52171e03eb6fe3797fd33f4dc8a7f44281d9/packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx#L364

2021-08-03 15:15 UTC, lossir reviewed
> В IE новый тест проходит правильно, тултип убирается. Это было исправлено в коммите [0f69555](https://github.com/skbkontur/retail-ui/commit/0f695550cd6773f3fe8276760149a146945b4fe0):

Я немного ошибся. Эти [скриншоты остались от старых тестов](https://github.com/skbkontur/retail-ui/pull/2485/commits/10fbc393af1e59862f3f99232bdb7207351b58ee), которые не были удалены после объединения тестов и добавления новых скриншотов. Осталось только их удалить.

2021-08-04 07:26 UTC, lossir approved these changes

2021-08-05 05:22 UTC, zhzz commented on packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
> +    skip: [{ in: ['ie11', 'ie11Flat', 'ie118px', 'ie11Flat8px'], tests: ['hovered', 'selected_2', 'select_1'] }],
Скипнутый тест выглядит подозрительно. Слишком стабильно падал. Позже на винде перепроверю. А так все норм.

2021-08-06 02:45 UTC, zhzz commented on packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
> +    skip: [{ in: ['ie11', 'ie11Flat', 'ie118px', 'ie11Flat8px'], tests: ['hovered', 'selected_2', 'select_1'] }],
Все так же стабильно падает, но причин не нашел. Локально работает.

2021-08-06 02:45 UTC, zhzz approved these changes

2021-08-06 06:26 UTC, merged