Fix(radio, checkbox, toggle): fix transparent background for flat theme
skbkontur/retail-ui pull request #2486
Opened 2021-07-16 06:29 UTC by HelenaIsh

#2201  Исправила просвечивающий фон для radio, checkobox, toggle в плоской теме

2021-07-19 12:24 UTC, HelenaIsh commented
уточнение по поводу тоггла от Вовы: Vladimir Dzekh, [16.07.21 11:46]
О, я забыл написать про тогл. прости. Там с ним всё сложно. Он конечно не правильно реализован, заливка должна быть белая, а заблокированность должна быть реализована без прозрачности. Единственное что должно сохранять прозрачность это обводка. Это касается кстати всех контролов. Сейчас проверю как тогл сделан в библиотеках и дам ссылку. оттуда можно будет параметры брать.

Vladimir Dzekh, [16.07.21 11:55]
Вот тут (https://www.figma.com/file/4vh3dHXmD8Ae4IGfIIApbC/%E2%9A%A1%EF%B8%8F-Kontur-UI-8px?node-id=4795%3A284) правильные стили у тогла для дефолтной темы.

Vladimir Dzekh, [16.07.21 11:57]
А тут (https://www.figma.com/file/On4a4hXijhkMe3ym368LIR/%E2%9A%A1%EF%B8%8F-Kontur-UI-8px-Flat?node-id=4633%3A0) для плоской. В плоской от дефолтной тогл должен отличаться только отсутствием градиента.

2021-07-27 02:59 UTC, lossir commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static radioBgImage = '#fff';
Это не валидное значение для `background-image`. Из-за чего тебе и пришлось добавить новое правило в `Radio.style.ts`.

Вот валидное значение:
```suggestion
  public static radioBgImage = 'linear-gradient(#fff,#fff)';
```

2021-07-27 02:59 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static toggleBaseBg = '#fff';
Т.к. это новая переменная, то её стоит добавить коммитом с типом `feat` ([contributing.md](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D1%8B)).

2021-08-03 17:40 UTC, lossir requested changes
Коммит с добавлением переменной темы стоит называть как-то так:
```
feat(Toggle): add `toggleBaseBg` theme variable 
```
Чтобы присутствовало имя переменной.

---

@dzekh Уверены, что такой стиль для тёмной темы пойдёт?
| Было | Стало |
| --- | --- | 
| ![image](https://user-images.githubusercontent.com/2708211/128058335-1017f10a-19e3-4195-a055-bf36e23e693c.png) | ![image](https://user-images.githubusercontent.com/2708211/128058194-4c11418c-ea60-4126-855e-8d6c18f9e171.png) |

2021-08-03 17:40 UTC, lossir commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static checkboxIndeterminateBg = '#fff';
Эта переменная неправильно объявлена нигде не используется. Нужно удалить.

---

При добавлении переменной темы, её сначала надо добавить в файл `internal/themes/DefaultTheme.ts`. Т.к. все остальные темы базируются на нём.
Тип `Theme` тоже основывается на нём, из-за чего ts будет ругаться на отсутствие переменной, хотя по факту она может присутствовать, например, в плоской теме как здесь.

2021-08-03 17:40 UTC, lossir commented on packages/react-ui/components/Toggle/Toggle.styles.ts
> +      background-color: ${t.toggleBaseBg};
Расширим влияние переменной и согласуем название с содержимым:
```suggestion
      background: ${t.toggleBaseBg};
```

2021-08-04 11:10 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static radioBg = 'transparent';
Я не смогла решить данную проблему без введения новой переменной, хотя согласна с тем, что ты написал. Проблема в том, что если добавить классу checked сброс фона` background-image: none` , то в дефолтной теме, там где нет синей обвидки, появится прозрачный фон. Для того, чтобы в дефолтной и плоской теме не было этих конфликтов, пришлось ввести новую переменную

2021-08-10 06:19 UTC, dzekh commented
Сейчас темная тема официально не поддерживается и в принципе можно оставить и так. Если посмотреть [примеры тут](https://tech.skbkontur.ru/react-ui/#/Customization/ThemePlayground) в темной теме много косяков и этот с тоглом не самое странное. 

Но если делать по хорошему, то в темах фон подобных контролов должен задаваться в одном месте и смотреть на переменную типа bgDefault. А bgDefault должна быть равна цвету бекграунда боди, или того контейнера где всё лежит. Так же как например с textColorDefault — для светлой темы тут должен стоять какой-то темный, для светлой — белый.

На bgDefault должны смотреть фоны инпутов, кнопок, радиокнопок, чекбоксов, и тоглов в том числе. Как-то так. 

Если есть еще силы — залинкуйте фон тогла с bgDefault. Если нет, забейте. Но вообще в скором времени мы начнем поддерживать темную тему и всё это всё равно нужно будет сделать.

2021-08-12 18:02 UTC, lossir requested changes
Раз уж залезли в тёмную тему, то давайте дотянем то, что в глаза бросается =)

@dzekh 
![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/2708211/129245655-d57dfce2-393d-40da-9856-9617ea22e53d.gif)

2021-08-12 18:02 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static radioBgColor = 'transparent';
Извиняюсь... Мне самому не удалось сделать иначе 
С новой пременной проще всего 🙃

2021-08-13 05:04 UTC, HelenaIsh commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  checkboxBg: '#333333',
@dzekh Точно, я спрашивала как должны себя вести элементы при ховере, а при нажатии не спросила. Правильно я понимаю, что у них тоже нужно убрать все эффекты?

2021-08-13 05:15 UTC, dzekh commented on packages/react-ui/internal/ThemePlayground/darkTheme.ts
> +  checkboxBg: '#333333',
да, убрать

2021-08-13 09:07 UTC, HelenaIsh commented
добавила изменения для заблокированного тогла согласно [задачке](https://yt.skbkontur.ru/issue/IF-149)

2021-08-18 05:29 UTC, lossir reviewed
| Было \| Стало |
| --- |
| ![image](https://user-images.githubusercontent.com/2708211/129840554-03815cac-1e4d-4a92-906f-3f9bbc2a93fd.png) |

Теперь цвет из пропа `color` не "просвечивает" когда Тоггл выключен. Если так и должно быть (@dzekh), то стоит об этом упомянуть в описании ПРа.

2021-08-18 05:29 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static toggleBgDisabled = '#E5E5E5';
У нас есть общая переменная `bgDisabled`, которая чуть светлее - `#f2f2f2` (`#E5E5E5`).
Другие контролы её наследуют: радио, чекбокс, кнопка, инпут.
Тоггл, вероятно, тоже должен её наследовать. Надо уточнить у @dzekh.

2021-08-18 05:39 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static toggleBgDisabled = '#E5E5E5';
Согласно макетам из фигмы:
у радио `#f2f2f2`:
![image](https://user-images.githubusercontent.com/32093844/129843168-f5091066-82d3-4787-ada6-548232ae70c0.png)
у тогла `#e5e5e5`:
![image](https://user-images.githubusercontent.com/32093844/129843311-cc52232f-764a-447f-9a80-8e53b5d3a4f3.png)

2021-08-18 10:39 UTC, dzekh commented
> Теперь цвет из пропа `color` не "просвечивает" когда Тоггл выключен. 
выключен — задизаблен? если в этом смысле то да, сейчас всё правильно. 

> Тоггл, вероятно, тоже должен её наследовать. 
да, вполне логично, давайте поправим на `bgDisabled` которая `#f2f2f2`

@lamergood измени пожалуйста фон тогла в библиотеках всех и [проверь переменные тут](https://www.figma.com/file/newCbSUe899sicnY2Kvd1m/React-UI-Theming?node-id=2357%3A3789)

2021-08-23 11:40 UTC, dzekh approved these changes
Меня смущает только один момент — при наведении мышью на чекбокс в фокусе стили фокуса перебиваются, исчезает синяя обводка. Но это поведение повторяется и в других темах и в мастере. По этому поводу нужно завести отдельную задачку. Заведи плиз. А с тоглом и остальными состояниями всё хорошо!

2021-08-25 09:59 UTC, lossir approved these changes

2021-08-25 10:52 UTC, merged