fix(Loader): disable focus children events while page is loading
skbkontur/retail-ui pull request #2494
Opened 2021-07-28 02:49 UTC by ErmolaevID

Closest #1732

2021-07-28 05:36 UTC, zhzz requested changes

2021-07-28 05:36 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
Спасибо за ПР!

Тут есть пара нюансов:
1. В задаче подразумевается блокировка только в активном состоянии лоадера. Чтобы пользователь не мог редактировать форму, пока данные отправляются, например. А до тех пор пока лоадер не активирован, он не должен никак влиять на контент внутри.
2. Предложенный способ, насколько я понимаю, блокирует реактовые события, но реальные фокусы продолжают работать и с элементами по прежнему можно взаимодействовать. Возможный способ исправить, это ловить фокусы внутри лоадера и принудительно делать `blur()`.

![image](https://user-images.githubusercontent.com/4607770/127268991-3567b2e5-c253-4874-a693-c563a33cd1cd.png)

2021-07-28 11:43 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
Также, новому `<div />` нужно указать `height: 100%`, иначе в некоторых случаях ломается верстка.

2021-07-28 13:28 UTC, lossir commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
@zhzz @ErmolaevID 
Подобным способом работает компонент `FocusLock` (нюанс 2). Если элемент, получивший фокус, находится за пределами обёртки, то он просто вызывает `document.activeElement.blur()`. Что в свою очередь вызовет событие `onBlur`, на которое пользователь мог завязаться.
Мы используем `FocusLock` в компонентах [`Modal`](https://guides.kontur.ru/components/lightbox/#01) и [`SidePage`](https://guides.kontur.ru/components/sidepage/#01), которые являются [модальными окнами](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%BE%D0%BA%D0%BD%D0%BE), и предполагают некоторую изоляцию пользователя от основного контента страницы. В этих компонентах, чтобы сфокусироваться на элементе "вовне" надо заморочиться (не считая `blockBackground` в `SidePage`, там только недавно добавили `FocusLock`). Поэтому, такой радикальный метод ловли фокуса кажется приемлемым. 

Но в случае с `Loader`, это может вызывать проблемы. Т.к. ничто не мешает пользователю оборачивать только часть формы в `Loader`. В гайдах никак это поведение не описано. 
Получается, что сейчас при табуляции __визуально__ стало всё норм, но по факту фокус всё также проходит по всем элементам и дёргает `onFocus` и `onBlur`. 

---

Я бы предложил чуть более замороченный, но надёжный способ.
Мы можем просто исключать фокусируемые элементы из навигации табом. Достаточно найти их, используя `getFocusableElements`, и задать `tabIndex = -1`, пока Лоадер активен. А при отключении возвращать прежнее значение.
В этом случае, при табуляции фокус будет сразу пропускать эти элементы, переходя к ближайшему после них. И не будут вызываться события `onFocus` и `onBlur`.

2021-07-29 04:38 UTC, ErmolaevID commented
## Что сделал
Если лоадер активен, то для всех фокусируемых элементов (находятся с помощью getFocusableElements) tabIndex ставится в значение -1. Также сохраняются предыдущие значения tabIndex для всех элементов. Если лоадер не активен, то фокусируемым элементам возвращаются их первоначальные значения tabIndex

2021-07-29 07:13 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
Да, с `tabIndex = -1` способ получше. Но нужно учитывать возможное изменение содержимого Лоадера. Т.е. эти поля могут поменяться в любой момент, добавиться новые в середину и тд. Можно попробовать хранить оригинальный tabIndex где-то в атрибутах самого элемента и следить за обновлением children.

Но кажется есть еще один способ. Это `<fieldset disabled />` . [Делает](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#attr-disabled) практически то, что нам нужно, только больше. Возможно он сгодится, если дать возможность пользователям отключить такое поведение по умолчанию.

2021-07-29 08:36 UTC, lossir commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
@zhzz @ErmolaevID 
Да, это был бы лучший вариант, если бы не наши кастомые элементы: `DateInput`, `DatePicker`, `Paging`, `Tabs`, `Link`, `Kebab` и, вероятно, какие-то ещё. Т.к. они не базируются на нативных элементах формы, то на них не работает `disabled`.

В хроме это проявляется заметнее всего. В лисе это визуально не заметно, и события не дёргаются, но `document.activeElement` меняется. При этом в IE11 всё работает как надо =)

<details>
<summary>Пример для витрины</summary>

```javascript
import { Gapped, Input, Checkbox, Radio, DateInput, Paging, Textarea, DatePicker, Toggle, Tabs, Link, Kebab } from '@skbkontur/react-ui';

<fieldset disabled>
  <Gapped vertical>
    <Link>Link 1</Link>
    <Input />
    <Kebab />
    <input />
    <DateInput />
    <Checkbox />
    <Toggle />
    <Radio />
    <Paging />
    <Textarea />
    <DatePicker />
    <Button use="default">Default</Button>
    <Button use="link">Link 2</Button>
    <Tabs >
      <Tabs.Tab id="1">11</Tabs.Tab>
      <Tabs.Tab id="2">22</Tabs.Tab>
      <Tabs.Tab id="3">33</Tabs.Tab>
    </Tabs>
  </Gapped>
</fieldset>;
```

</details>

2021-07-29 11:52 UTC, ErmolaevID commented
Осталось только учитывать изменения children внутри Loader

2021-07-29 12:34 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
Да, похоже `fieldset` не вариант. Нужно будет проверить, что вариант с getFocusableElements не будет тормозить на больших страницах. Операция довольно затратная.

2021-07-30 13:12 UTC, ErmolaevID commented
## Что сделал
Теперь для контроля состояния DOM в children используется MutationObserver. При любом изменении DOM, будет вызываться либо disableChildrenFocus, либо enableChildrenFocus (зависит от состояния лоадера)

## Улучшение кода
Сейчас используется focusable() напрямую из библиотеки, если добавим правильную реализацию getFocusableElements(), то можно будет избавиться от некоторого кода (276-279). Также, id обёртки дочерних элементов можно вынести в стейт, чтобы не хардкодить его во всех методах.

2021-07-30 13:31 UTC, ErmolaevID commented
Придумал небольшую оптимизацию, сейчас внесу изменения

2021-08-06 04:34 UTC, zhzz requested changes

2021-08-06 04:34 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    this.setState({ childrenObserver: observer });
Хорошее решение с MutationObserver. Думаю, нам подходит.

Однако, не стоит его держать всегда включенным. Лучше включать/выключать вместе с пропом `active`, чтобы избежать лишних вычислений.

Также, нет смысла его хранить в стейте. Обычно такие штуки ложат в приватные поля класса. Так не будет лишних перерисовок из-за изменения стейта. Можно глянуть другие примеры использования MutationObserver в коде.

2021-08-06 04:34 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    this.setState({ childrenFocusableElements: [] });
То же, вроде нет смысла хранить эти элементы в стейте. Будут лишние перерисовки или там могут оказаться уже удаленные элементы.

Лучше просто каждый искать актуальные элементы по нашему атрибуту `origin-tabindex`.

2021-08-06 04:34 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +            </div>
Здесь можно не делать новую обертку, а использовать компонент `ZIndex`, в который уже все оборачивается. Можно получить его ref через проп `wrapperRef` и использовать везде вместо `#children-loader-wrapper`.

2021-08-06 04:34 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +      active ? this.disableChildrenFocus() : this.enableChildrenFocus();
Эта логика повторяется и в `makeObservable`. Можно вынести в отдельный метод.

2021-08-09 19:39 UTC, zhzz requested changes
👍, есть еще парочка предложений

2021-08-09 19:39 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    const observer = new MutationObserver(() => this.toggleChildrenFocus());
```suggestion
    const observer = new MutationObserver(this.disableChildrenFocus);
```

На самом деле выходит что тут только disable уже актуален.

2021-08-09 19:39 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +    const tabbableElements = tabbable(this.childrenContainerNode);
Можно уже заехать на новый `getTabbableElements`.

2021-08-09 23:58 UTC, ErmolaevID commented
В ревью было `const observer = new MutationObserver(this.disableChildrenFocus);`, но из за этого `this` теряется и в будущем ссылается на `MutationObserver`, а не на `Loader`. Можно использовать bind, но я думаю лучше сделать `new MutationObserver(() => this.disableChildrenFocus());`. В коммите так и сделал

2021-08-10 03:53 UTC, ErmolaevID commented
Либо можно функцию disableChildrenFocus сделать стрелочной 🧐

2021-08-10 08:16 UTC, zhzz approved these changes

2021-08-11 17:16 UTC, lossir reviewed
Получилось очень круто 🔥 
У меня буквально пара ремарок ;-)

2021-08-11 17:16 UTC, lossir commented on packages/react-ui/components/Loader/Loader.tsx
> +      this.toggleChildrenFocus();
Давай избавимся от этого метода. Выглядит как оптимизация ради оптимизации =)
Логику лучше здесь явно написать, тем более такую короткую:
```suggestion
      if (active) {
        this.disableChildrenFocus();
      } else {
        this.enableChildrenFocus();
      }
```

2021-08-12 08:01 UTC, lossir submitted a review, later dismissed

2021-08-19 05:59 UTC, zhzz approved these changes
Хотел еще добавить скриншотный тест, но не хватает прав. @ErmolaevID можешь добавить меня в коллабораторы своего форка?

2021-08-19 06:01 UTC, ErmolaevID commented
@zhzz добавил

2021-08-23 10:11 UTC, lossir approved these changes

2021-08-23 11:24 UTC, merged