delete findDomNode
skbkontur/retail-ui pull request #2518
Opened 2021-08-24 06:18 UTC by khlutkova

2021-09-29 13:55 UTC, lossir requested changes
Думаю, стоит сразу перейти на `React.createRef()`, где возможно.

2021-12-01 08:20 UTC, zhzz requested changes
В финале еще хорошо бы дооформить ПР - добавить описание идеи и изменений (для других ревьюеров и на будущее). А также, где-то в доке добавить раздельчик про StrictMode, нюансы с findDOMNode, forwardRef и как их избежать.

2021-12-01 08:20 UTC, zhzz commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +export const getRootNode = (instance: Nullable<React.ReactInstance>) => {
Возвращаемый тип у `getRootNode` сейчас выводится `any`, но лучше что-то вроде `HTMLElement | null`.

2021-12-01 08:20 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> -
А этот warning зачем ушел?

2021-12-09 10:00 UTC, zhzz commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +  const domNode = (instance as any)?.getRootNode?.() || findDOMNode(instance);
Это еще осталось

2021-12-20 09:08 UTC, zhzz commented on packages/react-ui/README.md
> +Начиная с версии 3.10.0 (?) библиотека поддерживает работу в StrictMode.
```suggestion
Начиная с версии 3.10.0 библиотека поддерживает работу в StrictMode.
```

Не забыть убрать вопрос и еще дописать, что в валидациях с `1.7.0`.

2021-12-29 07:34 UTC, zhzz approved these changes

2021-12-29 07:35 UTC, merged