feat(react-ui-testing): Switcher control with tests
skbkontur/retail-ui pull request #2519
Opened 2021-08-24 07:44 UTC by callmekoo

New Switcher control and tests for it

Closes #2238

2021-08-24 10:44 UTC, slawwan requested changes

2021-08-24 10:44 UTC, slawwan commented on packages/react-ui-testing/SeleniumTesting/Controls/Switcher.cs
> +        public new IProp<bool> HasError => ReactProperty<bool>("error");
вот такое переопредление так-то опасно
может быть haserror в базовом классе сделать виртуальным?
и нам точно нужен тот базовый класс? ControlList ?
может быть кнопки селекта вытаскивать через коллекцию которая в Selone?

2021-08-24 10:44 UTC, slawwan commented on packages/react-ui-testing/SeleniumTesting/Controls/Switcher.cs
> +            this.AsEnumerable().Wait().Single(x => x.Text.AssertEqualTo(name), timings.GetConfiguration()).Click();
хорошо бы в первую очередь давать доступ к списку всех элементов. у нас элементом является кнопка и вероятно сама кнопка может быть заблокированной, только одна. а еще может захотеться выбирать элемент не по названию а по может быть чему-нибудь другогму, может быть value но вообще не понятно, надо ли давать такое. ох, сложнаа

вот эти списочные шняги что тут что в выпадахах комбобокса и селекта я так и не придумал как нормально это оформлять, но прям основательно не садился думать еще ни разу

не хочется здесь Wait употреблять

2021-09-20 11:34 UTC, zhzz commented
Если больше нет предложений, можем влить.

2021-09-20 15:19 UTC, slawwan approved these changes

2021-09-20 15:19 UTC, slawwan commented on packages/react-ui-testing/SeleniumTesting/Controls/Switcher.cs
> +        public new IProp<bool> HasError => ReactProperty<bool>("error");
мы не можем потому что там это метод, просто названия совпадают. надо будет в будущем переделать базовый на IProp

2021-09-20 15:27 UTC, zhzz commented
@callmekoo, спасибо за ПР! @slawwan, спасибо за ревью! На днях вольем и выкатим.

2021-09-21 17:52 UTC, merged