Update link to Slack
skbkontur/retail-ui pull request #2520
Opened 2021-08-24 14:50 UTC by dzekh

2021-08-24 15:59 UTC, lossir requested changes

2021-08-24 15:59 UTC, lossir commented on contributing.md
> +По любым возникающим вопросам можно обращаться в канал поддержки [#infra_front](https://kontur.slack.com/archives/C013HTCE18Q) в Слаке или напрямую пользователям:
Всё-таки либа открытая и я думаю здесь стоит оставить ссылку на телегу.

2021-08-25 05:58 UTC, dzekh commented on contributing.md
> +По любым возникающим вопросам можно обращаться в канал поддержки [#infra_front](https://kontur.slack.com/archives/C013HTCE18Q) в Слаке или напрямую пользователям:
Не, думаю что это не проблема. Не попадут в чат в слаке, есть другие способы написать. Кому-то лично, или таску завести тут. Основная масса всё равно из Контура. А вот то, что контуровские новички будут не в тот чат попадать это уже немного проблема, и таких будет больше. 

Но согласен что можно добавить что-то типа «если вы из Контура, пишите в Слак. Если нет — в личку.» Надо бы в профилях контакты оставить еще всякие.

2021-08-25 06:14 UTC, lossir commented on contributing.md
> +По любым возникающим вопросам можно обращаться в канал поддержки [#infra_front](https://kontur.slack.com/archives/C013HTCE18Q) в Слаке или напрямую пользователям:
Может тогда вместе со слаком оставить и телегу? Кажется, это лучше, чем в личку писать, т.к. может покрыть больше сценариев. Например, состав команды меняется быстрее, чем мы обновляем тут данные) Также, кто-то может быть в отпуске или на стажировке.

А в чате всегда кто-нибудь да ответит, либо позовёт "актуального" майнтейнера репы =)

2021-08-25 06:20 UTC, dzekh commented on contributing.md
> +По любым возникающим вопросам можно обращаться в канал поддержки [#infra_front](https://kontur.slack.com/archives/C013HTCE18Q) в Слаке или напрямую пользователям:
Добавил

2021-08-25 06:59 UTC, lossir commented on contributing.md
> +- [Владимир Дзех](https://github.com/dzekh) — дизайн, гайдлайны. Телеграм: [@dzekh](tg://resolve?domain=dzekh);
Вроде гитхаб не поддерживает ещё такой протокол. Поэтому вместо ссылки будет просто текст. Но можно указать обычную ссылку:
```suggestion
- [Владимир Дзех](https://github.com/dzekh) — дизайн, гайдлайны. Телеграм: [@dzekh](https://t.me/dzekh);
```

2021-08-25 08:34 UTC, lossir approved these changes

2021-08-25 08:35 UTC, merged