(Input, Combobox): fix border and background for disabled state in flat theme
skbkontur/retail-ui pull request #2521
Opened 2021-08-26 09:46 UTC by HelenaIsh

fix #2148 
Исправила фон и обводку у заблокированного инпута в плоской теме. Комбобокс использует инпут, поэтому его стили тоже поменялись.
Для заблокированного инпута добавила свойство `background-clip: padding-box;`, чтобы полупрозрачный бордер не накладывался на фон инпута. Из-за этого сломались тесты для инпута в дефолтной теме, что визуально не заметно.

2021-09-03 09:45 UTC, lossir commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static inputDisabledBg = '#f2f2f2';
Кажется, это строку можно просто удалить.

У нас уже есть общая переменная с таким цветом - `bgDisabled`:
https://github.com/skbkontur/retail-ui/blob/27b9e48029a397e40b822e3d1a8088f7b96570b4/packages/react-ui/internal/themes/DefaultTheme.ts#L34

И в дефолтной теме она как раз наследуется в `inputDisabledBg`:
https://github.com/skbkontur/retail-ui/blob/27b9e48029a397e40b822e3d1a8088f7b96570b4/packages/react-ui/internal/themes/DefaultTheme.ts#L981-L983

2021-09-03 09:45 UTC, lossir commented on packages/react-ui/internal/themes/FlatTheme.ts
> +  public static inputDisabledBorderColor = 'rgba(0, 0, 0, 0.05)';
Давай ещё создадим общую переменную `borderColorDisabled`, и также залинкуем её здесь.

2021-09-06 10:14 UTC, lossir submitted a review, later dismissed

2021-09-07 05:23 UTC, zhzz requested changes

2021-09-07 05:23 UTC, zhzz commented on packages/react-ui/components/Input/Input.styles.ts
> +      background-clip: padding-box;
На самом деле `background-clip: padding-box` уже применяется в `.root`, и я бы сказал, что там ему более подходящее место. Но он перетирается в `.disabled` общим свойством `background: ...`.  Думаю, лучше будет поменять background на background-color. Тогда новый background-clip не понадобится.

```suggestion
      background-color: ${t.inputDisabledBg};
      border-color: ${t.inputDisabledBorderColor};
      box-shadow: none;
```

2021-09-07 06:44 UTC, zhzz approved these changes

2021-09-09 16:39 UTC, merged