[Radio] убрать отображение фокуса при работе с мышью
skbkontur/retail-ui pull request #2526
Opened 2021-08-31 11:26 UTC by HelenaIsh

fix #1729 
Убрала появление фокуса при клике мышью

2021-09-03 08:40 UTC, lossir reviewed
Изящный фикс) 👍

2021-09-03 08:40 UTC, lossir commented on packages/react-ui/components/Radio/Radio.styles.ts
> +import 'focus-visible';
Давай перенесём этот импорт в `Emotion.ts`.И добавим какой-нибудь комментарий, например:
``` javascript
// Use '.focus-visible' class instead ':focus-visible' pseudo-class
import 'focus-visible';
```

2021-09-06 10:15 UTC, lossir submitted a review, later dismissed

2021-09-07 05:58 UTC, zhzz requested changes
Да, решение было бы идеальным, если бы не одно но. Полифил будет модифицировать DOM на всей странице приложения пользователя, а не только внутри наших контролов. Такое поведение крайне не желательно для библиотек, как и использование подобных полифилов в принципе (они должны подключаться в проекте пользователя, чтобы избежать дублирования). Это решение уже озвучивалось в #2091. 

Вижу два варианта:
1. Помочь реализовать в этом полифиле фичу со scope (https://github.com/WICG/focus-visible/issues/126), заслав PR. И тогда можно будет его заиспользовать.
2. Реализовать правку через tabListener, как в остальных контролах.

2021-09-07 11:32 UTC, HelenaIsh commented
> 
> 
> Да, решение было бы идеальным, если бы не одно но. Полифил будет модифицировать DOM на всей странице приложения пользователя, а не только внутри наших контролов. Такое поведение крайне не желательно для библиотек, как и использование подобных полифилов в принципе (они должны подключаться в проекте пользователя, чтобы избежать дублирования). Это решение уже озвучивалось в #2091.
> 
> Вижу два варианта:
> 
>     1. Помочь реализовать в этом полифиле фичу со scope ([Bundling in a widget, scope WICG/focus-visible#126](https://github.com/WICG/focus-visible/issues/126)), заслав PR. И тогда можно будет его заиспользовать.
> 
>     2. Реализовать правку через tabListener, как в остальных контролах.

Я выбрала второй вариант :)
Проблема только в том, что для радиокнопок согласно [гайдам](https://guides.kontur.ru/components/radio/#Rabota_s_klaviaturoi) фокус может приходить не только от таба, но и от стрелочек. Поэтому я написала keydownListener аналогично tabListener. И поправила [тест](https://github.com/skbkontur/retail-ui/pull/2526/commits/13577afd4fb279be7811b18d3823066908b260c6): добавила паузу между нажатием таба и стрелочки, так как фокус не успевал переключаться

2021-09-08 12:24 UTC, zhzz requested changes

2021-09-08 12:24 UTC, zhzz commented on packages/react-ui/components/Radio/Radio.tsx
> +        if (keydownListener.isKeyPressed) {
Думаю, лучше все-таки смотреть на нажатие определенных клавиш. Т.е. нас тут интересуют уже и Tab и стрелки. Может тогда объединить tabListener и keydownListener в одну общую штуку, где будут все нужные флаги, типа isTab/isArrow?

2021-09-09 04:59 UTC, HelenaIsh commented on packages/react-ui/components/Radio/Radio.tsx
> +        if (keydownListener.isKeyPressed) {
> Может тогда объединить tabListener и keydownListener в одну общую штуку

Абсолютно согласна. В моем случае было дублирование кода и я это видела, просто не хватало увереннности вносить изменения в реализованные внутренние функции

2021-09-09 07:30 UTC, zhzz requested changes

2021-09-09 07:30 UTC, zhzz commented on packages/react-ui/lib/events/tabListener.ts
> -export const tabListener = new TabListener();
Получилось отлично! Только я не обратил внимания, что  `tabListener` лежит в `lib`, а не в `internal`, и его [используют](https://sg.testkontur.ru/search?q=tabListener&patternType=literal) другие команды. Поэтому нужно временно оставить старый модуль, чтобы у людей ничего не сломалось. А в следующей мажорной версии удалим.

Его можно переделать на использование нового. И пометить комментарием "deprecated", чтобы мы его потом нашли.

tabListener.ts
```js
// deprecated, use keyListener
export { keyListener as tabListener } from './keyListener';
```

2021-09-09 07:30 UTC, zhzz commented on packages/react-ui/components/Radio/Radio.tsx
> +    keyListener.isArrowPressed = true;
Хватит и одного таба.
```suggestion

```

2021-09-09 07:30 UTC, zhzz commented on packages/react-ui/components/Tabs/Tab.tsx
> +      if (keyListener.isTabPressed || this.isArrowKeyPressed) {
Получается, в табе тоже можно перейти на новый флаг и удалить его собственный listener! 

```suggestion
      if (keyListener.isTabPressed || keyListener.isArrowPressed) {
```

2021-09-09 07:35 UTC, zhzz requested changes

2021-09-09 07:35 UTC, zhzz commented on packages/react-ui/lib/events/keyListener.ts
> +      );
Оба флага можно сетить в одном обработчике.
Также, в `keyboard/identifiers.ts` есть общий хелпер для всех стрелок `isKeyArrow`.

2021-09-09 09:39 UTC, HelenaIsh commented on packages/react-ui/components/Tabs/Tab.tsx
> +      if (keyListener.isTabPressed || this.isArrowKeyPressed) {
да, здорово получилось! Спасибо, что заметил!

2021-09-09 10:08 UTC, zhzz submitted a review, later dismissed
👍  Осталось подправить коммиты либо засквошить при влитии.

2021-09-15 03:01 UTC, zhzz approved these changes

2021-09-15 08:24 UTC, lossir approved these changes

2021-09-15 21:56 UTC, merged