[TokenInput] Запятая ведет себя не как разделитель
skbkontur/retail-ui pull request #2539
Opened 2021-09-15 08:29 UTC by HelenaIsh

fix #1860

2021-09-24 03:45 UTC, zhzz submitted a review, later dismissed

2021-09-27 05:28 UTC, lossir requested changes

2021-09-27 05:28 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    }
У события `KeyboardEvent` есть свойство `char`, которое поддерживается только в IE 9+ [MDN Web Docs](https://developer.mozilla.org/ru/docs/Web/API/KeyboardEvent#%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0).
Это свойство как раз содержит `,` в тех же случаях, что и свойство `key` в других браузерах.

Ещё у нас есть [специальные хелперы](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/lib/events/keyboard/identifiers.ts) для работы с клавиатурой. Там спрятана браузерная специфика, чтобы в контролах можно было об этом не думать.

В `identifiers.ts` можно добавить, например, такой экстрактор:
```typescript
// IE 9+ supports char attribute
// https://developer.mozilla.org/ru/docs/Web/API/KeyboardEvent
const getChar = (e: E) => {
  if (e instanceof KeyboardEvent) {
    return e.char;
  } else return e.nativeEvent.char;
};
```
И новый идентификатор для запятой:
```typescript
export const isKeyComma: IS = (e) => e.key === ',' || getChar(e) === ',';
```

И тогда в `TokenInput` можно будет заменить `includes` на `some`:
```typescript
this.props.delimiters.some((key) => key === e.key || (key === ',' && isKeyComma(e)))
```

2021-09-27 10:14 UTC, lossir approved these changes

2021-09-27 13:33 UTC, zhzz approved these changes

2021-09-27 18:51 UTC, merged