[Modal-HBVS] Неправильное определение контейнера
skbkontur/retail-ui pull request #2540
Opened 2021-09-16 14:20 UTC by HelenaIsh

fix #1305

2021-09-21 16:29 UTC, lossir submitted a review, later dismissed

2021-09-23 09:34 UTC, zhzz requested changes

2021-09-23 09:34 UTC, zhzz commented on packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
> +    const shouldHide = !disposeDocumentStyle && clientHeight <= scrollHeight;
Получается, что скролл теперь скрывается всегда, ведь `clientHeight` никогда не больше `scrollHeight`. Такое условие бесполезно. 

В данный момент, когда скрывается скролл, к \<html /> добавляется margin, чтобы сконпенсировать ширину скролл-бара. И получается, если скролла в момент скрытия не было, то этот margin все равно добавляется и смещает контент страницы.

Можно рассмотреть вариант с безусловным скрытием скролла, как сейчас стало, но с выборочным добавлением margin, только если он нужен.

2021-09-28 04:48 UTC, zhzz approved these changes
👍 Можно обновить описание ПРа.

2021-10-01 07:42 UTC, merged