[FileUploader, FileAttacher] Добавление двух компонентов загрузки файлов.
skbkontur/retail-ui pull request #2542
Opened 2021-09-17 06:10 UTC by MozalovPavel

FileUploader позволяет загружать файлы асинхронно.
FileAttacher позволяет прикреплять файлы к форме.

2021-09-17 07:26 UTC, zhzz commented
Круто, поглядим! Похоже лишние коммиты попали, можешь отребэйзиться на мастер?

2021-09-17 07:32 UTC, MozalovPavel commented
> Круто, поглядим! Похоже лишние коммиты попали, можешь отребэйзиться на мастер?

Да, сейчас отребейзимся. 
Там еще линты упали. Сейчас подолью правки.

2021-09-20 14:13 UTC, MozalovPavel commented on packages/react-ui/internal/UploadFileControl/locale/index.ts
> +// TODO @mozalov: мб стоит разделить переводы для всех компонентов
Да, кажется все же стоит. Сейчас все контролы зависимы.

2021-09-23 05:55 UTC, zhzz commented on packages/react-ui/components/FileAttacher/FileAttacher.tsx
> +import React from 'react';
Выглядит круто! Есть пара глобальных мыслей, после первого подхода.

1. Как я понял, `FileUploader` и `FileAttacher` отличаются только наличием у первого пропов для асинхронной загрузки (request, onRequestSuccess, onRequestError), и еще механизмом валидации файлов. Может быть лучше будет объединить это все в одном контроле и универсализировать валидацию? Отличий не много и они вроде не конфликтуют. Тогда пользователю не придется вникать в их разницу.
2. Валидация всего контрола целиком (проп `controlError`). Уверен, что для этого лучше будет использовать react-ui-validations, по аналогии с остальными контролами. Т.е. нужно наладить их совместимость (пропы error, warning, onChange и тд, можно заглянуть [сюда](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui-validations/src/ValidationWrapperInternal.tsx#L106-L145)).

2021-10-06 18:16 UTC, dzekh commented on packages/react-ui/components/FileAttacher/FileAttacher.tsx
> +import React from 'react';
Посмотрел компонент в сторибуке, выглядит круто, особенно понравилась анимация при перетаскивании =) Потестил немного разные стори, и кажется что заблокированный контрол не должен реагировать на перетаскиваемые файлы.  Сейчас реагирует — появляется анимация, но потом конечно ничего не происходит. Нужно убрать анимацию у заблокированного.

2021-11-11 06:20 UTC, zhzz requested changes
В целом выглядит здорово! Есть немного предложений. Мне кажется, почти готово для выпуска первой версии.

Я чуть позже могу докинуть скриншотов, т.к. у тебя с ними проблемы. 

Еще нужно прогнать `yarn workspace @skbkontur/react-ui fix:prettier` чтобы линтеры прошли.

2021-11-11 06:20 UTC, zhzz commented on packages/react-ui/components/FileUploader/__tests__/FileUploader-test.tsx
> +import { mount, ReactWrapper } from 'enzyme';
При запуске тестов выводятся предупреждения о нехватке `act(() => { ... })`.

2021-11-11 06:20 UTC, zhzz commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +export interface IFileUploaderProps extends _IFileUploaderProps, IFileUploaderControlProviderProps {}
Мы не используем префикс `I` для интерфейсов в проекте. Думаю будет лучше сохранять единообразие.

2021-11-16 09:34 UTC, MozalovPavel commented
> Еще нужно прогнать `yarn workspace @skbkontur/react-ui fix:prettier` чтобы линтеры прошли.

Да, тут упустил, прогоню.

2021-11-16 13:40 UTC, MozalovPavel commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +import { _FileUploader, _IFileUploaderProps, IFileUploaderRef } from './_FileUploader';
Кажется так сделал по причине циклической зависимости. Но да, согласен. Попробую причесать по-другому.

2021-11-16 13:43 UTC, MozalovPavel commented on packages/react-ui/components/FileUploader/_FileUploader.tsx
> +import UploadIcon from '@skbkontur/react-icons/Upload';
Хм, а почему их нельзя использовать?
И почему можно в intarnal?

2021-11-16 13:45 UTC, MozalovPavel commented on packages/react-ui/components/FileUploader/_FileUploader.tsx
> +import UploadIcon from '@skbkontur/react-icons/Upload';
Увидел. Есть в dev зависимостях, поэтому можно юзать в дев компонентах.

2021-11-17 09:30 UTC, dzekh commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      &:focus {
Да, тут лучше так же, единообразно сделать: показывать рамку фокуса только когда табом фокус получен. При фокусе курсором фокус остается на контроле но рамка не отображается. 

Еще я понял что нет примера фокуса на крестике — он тоже долже появляться при работе с клавиатурой. можно сделать рамку вокруг крестика как в лайтбоксе или сайдпедже сейчас.

2021-11-18 09:40 UTC, zhzz commented on packages/react-ui/components/FileUploader/_FileUploader.tsx
> +import UploadIcon from '@skbkontur/react-icons/Upload';
Нельзя, потому что они часть фирменного стиля, и все их в открытое использование отдавать не хотят. А библиотека открытая. 

Но отдельные иконки мы использовать в библиотеке можем, скопировав их из пакета.

В dev-зависимостях пакет есть, да. Можно использовать в доке или историях.

2021-11-22 14:07 UTC, zhzz commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +import { _FileUploader, _IFileUploaderProps, IFileUploaderRef } from './_FileUploader';
Отдельные сущности `_FileUploader` и `_FileUploaderProps` все еще кажутся немного лишними. Почему бы их тоже не объединить с `FileUploader` и `FileUploaderProps`?

2021-11-22 14:09 UTC, zhzz commented on packages/react-ui/components/FileUploader/_FileUploader.tsx
> +              </Link>
В новой ссылке пропало подчеркивание при наведении. Скорей всего его нужно сохранить. Для этого тоже уже должны быть все переменные.

2021-11-22 14:30 UTC, zhzz requested changes

2021-11-22 14:30 UTC, zhzz commented on packages/react-ui/lib/fileUtils.ts
> +}
Так как эти типы тоже получаются частью публичного API, то я бы и их переименовал по имени компонента, для консистентности. Например, в  `FileUploaderFileInBase64` , `FileUploaderFileStatus` и `FileUploaderAttachedFile`.

И в целом, кажется эти утилиты довольно специфичны для FileUploader'a. Может их перенести к нему в директорию?

2021-11-24 11:57 UTC, zhzz commented
Я еще в предыдущем ревью пару дискуссий раскрыл и комментариев добавил.

2021-11-26 10:01 UTC, MozalovPavel commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +import { _FileUploader, _IFileUploaderProps, IFileUploaderRef } from './_FileUploader';
Обсудили голосом и решили, что это править не будем.

2021-12-02 11:39 UTC, bymse commented on packages/react-ui/internal/FileUploaderControl/FileUploaderControlProvider.tsx
> +        onValueChange?.(newFiles);
вот эта строчка (и выше, 70я строчка) дает варнинг `Cannot update a component (...) while rendering a different component` , если внутри onValueChange есть setState 
а такой сценарий с `onValueChange` кажется вполне адекватным, т.к. нужно куда то положить выбранные пользователем файлы

2021-12-06 06:45 UTC, zhzz submitted a review, later dismissed

2021-12-06 06:45 UTC, zhzz commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'onSelect'> {
Кстати, нативный `onChange` не обязательно убирать, его тоже можно поддержать, во многих компонентах он работает.

А `onSelect` может переименовать в `onAttach`? Чтобы не путать с нативным `onSelect`, который про другое.

2021-12-06 19:39 UTC, bymse commented on packages/react-ui/lib/guidUtils.ts
> +export const getGuid = (): string => {
nit: [guid](https://en.wikipedia.org/wiki/Universally_unique_identifier) не совсем корректный термин для этой функции, лучше `getUid`

2021-12-15 10:38 UTC, dzekh commented
Потестил локально ветку, появилось несколько предложений-замечаний. Собрал [картинку в фигме ](https://www.figma.com/file/HNDVXgv304Mvuq2h3n9uToNN/Guides-Drafts?node-id=1469%3A1848)про это, дублирую здесь: 

![image](https://user-images.githubusercontent.com/26383080/146171037-baf4206f-9877-4400-8e5b-342d1e9bc8bf.png)

Видео:

https://user-images.githubusercontent.com/26383080/146171330-471f1515-df35-4e86-98a3-d4b0c84d001a.mov

https://user-images.githubusercontent.com/26383080/146171246-220ef4c6-7de2-48eb-a191-03c0d2f2b968.mov

2021-12-17 09:26 UTC, MozalovPavel commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'onSelect'> {
Про onSelect согласен, поправлю. Про onChange - кажется, что не очень хорошо, что onChange и onValueChange срабатывают не синхронно, это может приводить (теоретически) к багам с валидациями. Я проверил и пока все нормально. Но рассинхрон меня настораживает.

2021-12-23 06:50 UTC, zhzz commented
Это нормально, что высота компонента в старой теме была на 2px больше. В актуальной теме все норм. Видимо, Вова смотрел на старую.

Еще заметил, что при появлении окна выбора файлов на input происходит blur (хотя, в document.activeElement по прежнему он). После закрытия - снова фокус. Это приводит к тому, что валидация всего контрола на lostfocus срабатывает еще до выбора файлов (в первой истории в валидациях видно). Вероятно, стоит отфильтровать эти лишние события.

2021-12-29 04:14 UTC, zhzz commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'onSelect'> {
По опыту других контролов пока таких проблем не было. Предлагаю оставить, будем иметь это в виду.

2022-02-03 12:22 UTC, merged