Static global loader
skbkontur/retail-ui pull request #2554
Opened 2021-10-05 04:41 UTC by HelenaIsh

2021-11-11 13:00 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +            }}
Думаю, можно прокидывать пропы в класс. На то он и `css-in-js` - пусть отрабатывает =)

Ну и `keyframes` остались в файле `AnimationKeyframes.ts`. Их ничего не мешает перетащить.

2021-12-07 18:08 UTC, lossir requested changes
Изначально думал сам всё поправить, но всё-таки передумал =)

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +            [animations.standardAnimation(this.theme, this.props.expectedResponseTime)]: !this.props.status,
Стоит добавить статус для анимации `standardAnimation`. По-сути им является `undefined`, но это неудобно и непрозрачно. С первого взгляда кажется, будто `standardAnimation` может применяться с другими анимациями.

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +Глобальным лоадером можно управлять путем передачи необходимых переменных в качестве пропсов, а также с помощью статических методов:
Говоря о статический методах, упустили, что стоит добавить коллбэки. "Слушателям" может понадобиться закрыть обычным Лоадером контент при старте. Либо дёрнуть Тост при ошибки, как описано в Гайдах.

Думаю, может понадобиться 4 коллбэка:
```ts
onStart?(): void;
onDone?(): void;
onReject?(): void;
onAccept?(): void;
```

Ещё стоит попробовать добавить проп `disableAnimations`, как в других контролах с анимациями.

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +const myTheme = ThemeFactory.create({ globalLoaderPosition: 'fixed' });
Учитывая, что по Гайдам ГЛ должен быть вверху шапки, то многим командам придётся это делать. Лучше сразу задать это значением по-умолчанию.

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +    <Button onClick={cancelErrorProp}>Cancel Error</Button>
Пример не очень информативен. Предлагаю сделать 2 отдельных примера. В первом примере будут статические методы. А во втором будет управление через пропы тогглами для `active` и `rejected`. Таймауты можно будет в коде править.

В обоих примерах можно добавить разную кастомизацию. Это наглядно покажет, что будет работать именно второй инстанс ГЛ.

Можно добавить ещё пример из Стори, когда ГЛ запускается из Модалки. И добавить к нему СайдПейдж.

И совсем круто будет добавить [пример из Гайдов](https://guides.kontur.ru/components/global-loader/#18).

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +      <GlobalLoader expectedResponseTime={2000} delayBeforeShow={0} active={active} rejected={error} />
Если передать сразу `active = true` и `rejected = true`, то анимация ошибки не включиться

2021-12-07 18:08 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoaderView.styles.ts
> +          infinite alternate;
Здесь начинайте анимация ошибки, но это никак не отражается в состоянии контрола. Это не получится протестировать. И получается, что стили берут на себя часть логики.
Лучше вынести эту логику в `GlobalLoader.tsx`. Чтобы по истечении таймаутов сеттился статус `rejected`.

2021-12-09 06:26 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +export class GlobalLoaderView extends React.Component<GlobalLoaderViewProps> {
Хорошее замечание. Обязательно сделаю, если время останется

2021-12-09 06:30 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +    <Button onClick={cancelErrorProp}>Cancel Error</Button>
Сделала 2 отдельных примера. Для управления пропами добавила тоггл, добавила кастомизацию.  Если добавить модалку третим примером, то первые два ГЛ не будут работать. Пример из гайдов было бы здорово добавить. Сделаю, если время останется

2021-12-09 09:11 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +    <Button onClick={cancelErrorProp}>Cancel Error</Button>
В примере с Модалкой можно ведь статические методы дёргать, и первые 2 примера будут работать.

2021-12-09 12:53 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +    <Button onClick={cancelErrorProp}>Cancel Error</Button>
Неточно выразился. Я имел в виду именно одновременное отображение Модалки/СайдПейджа и ГЛ.

2021-12-09 17:53 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
> +            delayBeforeTaskStart: this.props.expectedResponseTime * (1 + parseInt(theme.globalLoaderWaitingFactor)),
Давай вынесем `globalLoaderWaitingFactor` в пропы, но посмотрим на неё с другой стороны.
По сути эта переменная нужна для вычисления третьей переменной, на основе `expectedResponseTime`.
Назовём третью переменную `overtime`. И если сейчас передать в пропы `expectedResponseTime = 5000`, то  `overtime` будет 25 секунд. Довольно странная зависимость получается.

Думаю, лучше дать возможность задавать `overtime` напрямую, и не привязывать к `expectedResponseTime`. Т.е. её дефолтное значение будет сразу `5000`. Так будет проще для использования и мы вытащим лишнюю логику из стилей.

---

Вместо `TaskWithDelayAndMinimalDuration` для этих целей больше подойдёт [`lodash.debounce`](https://lodash.com/docs/4.17.15#debounce). Можно посмотреть как он используется в других контролах.

2021-12-09 17:53 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
> +      this.startTask.start();
Здесь не хватает `errorTask.stop()`. Или отмены дебаунсера `.cancel()`, если использовать `lodash.debounce`.

2021-12-09 17:53 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
> +  };
Здесь надо глушить и все таски/таймеры.

2021-12-09 17:55 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +      <GlobalLoader expectedResponseTime={2000} delayBeforeShow={0} active={active} rejected={error} />
Это поведение не исправлено. Если задано `rejected = true`, то при активации ГЛ сразу должна стартовать анимация ошибки.

2021-12-09 17:56 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.md
> +    <Button onClick={cancelErrorProp}>Cancel Error</Button>
Пока оставим как есть.

2021-12-10 06:10 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
> +            delayBeforeTaskStart: this.props.expectedResponseTime * (1 + parseInt(theme.globalLoaderWaitingFactor)),
> Думаю, лучше дать возможность задавать overtime напрямую, и не привязывать к expectedResponseTime

`overtime` должна зависеть от `expectedResponseTime`. Сначала ГЛ за время `expectedResponseTime` плавно едет до 80%. Потом, если ответ от сервера не пришел, ГЛ должен замедляться. В данный момент он замедляется на величину `globalLoaderWaitingFactor`, то есть в 5 раз.  

Если мы оставим `expectedResponseTime` по дефолту равной 1000ms и введем переменную `overtime` равной по дефолту 5000ms, может произойти ситуация, когда человек установит `expectedResponseTime`, скажем равной 5000ms, `overtime` он забудет обновить. Тогда у нас не будет замедления после 80%. И нехорошо, когда разработчику придется следить, что если он поменял  `expectedResponseTime`, то нужно не забыть изменить `overtime` 

> Вместо TaskWithDelayAndMinimalDuration для этих целей больше подойдёт lodash.debounce

Мне переписывать TaskWithDelayAndMinimalDuration  на lodash.debounce?

2021-12-10 07:02 UTC, lossir commented on packages/react-ui/components/GlobalLoader/GlobalLoader.tsx
> +            delayBeforeTaskStart: this.props.expectedResponseTime * (1 + parseInt(theme.globalLoaderWaitingFactor)),
> И нехорошо, когда разработчику придется следить

Наоборот, это вполне нормально. Для `expectedResponseTime` от 1 до 3 секунд, `overtime` размером 5 секунд вполне приемлем. Если разработчику надо ещё больше, то он сможет легко задать новый `overtime`.
Сейчас, если разработчик захочет это поменять, то ему придётся лезть в Темизацию и колдовать с `globalLoaderWaitingFactor`, чтобы получить конкретное значение.

> Мне переписывать TaskWithDelayAndMinimalDuration на lodash.debounce?

Да, стоит переписать на `lodash.debounce`.

2021-12-15 13:38 UTC, dzekh commented
### Анимация

- Хочется отсыпать немного изингов, чтоб он был более плавный в те моменты когда скорость меняется. В Фигме в настройках анимации есть Ease in / Ease out. Кажется в ЦСС тоже такие штуки есть, нет? Если конкретно говорить то: в самом начале, как только полоса появляется можно сделать чтоб она начинала движение быстрее — Ease out, постепенно замедляясь при подходе к той точке когда она совсем медленно поползет. Потом, если она от этой точки заполняется к концу — наоборот Ease in. 
![image](https://user-images.githubusercontent.com/26383080/146185638-e321df0b-6f2e-4a26-895c-430ff34abae2.png)
- Не очень нравится анимация в состоянии ошибки, хочется чтоб было максимально ближе к тому, как сделано на [стаффе](https://staff.skbkontur.ru/). Можно посмотреть как это если троттлинг включить, у них такой типа спиннер как у нас глобальный лоадер в состоянии ошибки. Можно даже прямо скопировать параметры анимации.
- Хочется немного поправить завершение загрузки и изчезновение лоадера. Если нажать саксесс он моментально добегает до конца, какое-то время висит и потом резко изчезает. Хочется чтоб тут тоже была анимация растягивания и потом исчезновение через прозрачность. Сейчас в примерах-прототипах 200ms на исчезновение в прозрачность и 400ms он висит. 
- Переход из состояния ошибки в саксесс тоже хочется сделать более плавным. 

### Примеры в сторибуке

- А можем добавить в стори несколько примеров с разными вариантами времени, чтоб посмотреть как в них будет это работать. То есть сделать несколько кнопок: «ответ пришел через X секунд» при нажатии на которую запускается лоадер и какой-то таймер, через который приходит типа ответ что всё загруженно и лоадер завершается. Чтобы были отрезки показательные, например: 0,5 сек, 1, 2, 4, 8. 16.  

### Параметры/настройки

- Не уверен что задержку показа лоадера стоит зашивать прямо в логику лоадера. В рекомендации в гайде [много другой логики](https://guides.kontur.ru/components/global-loader/#03) — поджигание пункта меню, отправка запроса, переключение на новую страницу если есть кэш. Но я и не настаиваю что зашивать не нужно. Нужно подумать как будет лучше, проще и правильней в контексте того, как будут использовать его, чтоб удобней было настраивать.
- Немного смущает то, что ошибку можно включить только включив сам лоадер, кажется что это должны быть отдельные параметры. 
- Мы рассчитывали что глобальный лоадер всегда один и всегда в одном месте, даже когда открыт лайтбокс. В гайде чот не нащел про это но момню что обсуждали и [есть такой пример](https://www.figma.com/proto/igS9KiYFsoQ7zF0S0wzB4H/%D0%9B%D0%BE%D0%B0%D0%B4%D0%B5%D1%80-%D0%B8-%D1%81%D0%BA%D0%B5%D0%BB%D0%B5%D1%82%D0%BE%D0%BD?page-id=776%3A528&node-id=776%3A791&viewport=324%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=776%3A791).

2022-01-18 18:27 UTC, lossir requested changes

2022-01-18 18:27 UTC, lossir commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    // });
Мне тоже не удалось победить эту проблему. Везде говорят, что должен помочь `.update()`, но в нашем случае это не помогает.
По логам видно, что стейт меняется как надо, но последним изменением всё сбрасывается.

В идеале, конечно, было бы вынести логику расчёта стейта по пропам в отдельные хелперы, и отделить их от таймаутов. Что-то на подобии `CurrencyInputHelper`. Но это довольно заморочено сейчас, да и проблема в тестовом окружении.

Обратимся к @zhzz за советом. Может он сможет помочь.
Если не получится, и в ближайшем будущем мы планируем избавиться от `enzyme`, то можно просто заскипать пока эти тесты.

2022-01-19 05:59 UTC, lossir commented
@dzekh 
> Не уверен что задержку показа лоадера стоит зашивать прямо в логику лоадера...

Такая же логика в `Loader`, и её можно просто отключить. Если её не зашивать, то каждая команда, которая решит следовать Гайдам, будет вынуждена что-то придумывать.

> Мы рассчитывали что глобальный лоадер всегда один и всегда в одном месте, даже когда открыт лайтбокс. В гайде чот не нащел про это но момню что обсуждали и есть такой пример.

Тут не очень понятно, о чём вопрос... "Мы" это проектировщики? =)
Сейчас ГЛ может быть только один. При монтировании он "убивает" предыдущий ГЛ, и начинает принимать на себя все вызовы статических методов.

2022-01-19 09:09 UTC, dzekh commented
> Тут не очень понятно, о чём вопрос... "Мы" это проектировщики? =) Сейчас ГЛ может быть только один. При монтировании он "убивает" предыдущий ГЛ, и начинает принимать на себя все вызовы статических методов.

ага, проектировщики. Я имею ввиду что не нужно делать его внутри лайтбокса. только в самом верху страницы, над вуалью, если она есть. Хотя... если будет такая возможность наверное пусть будет. Но в примерах и по умолчанию всегда в одном месте.

2022-01-19 09:10 UTC, dzekh commented on packages/react-ui/components/GlobalLoader/__stories__/GlobalLoader.stories.tsx
> +  const items = [0.5, 1, 2, 4, 8, 16];
А вроде она сама и не должна включаться, только если приложение скажет что точно ошибка есть.

2022-01-19 13:25 UTC, lossir commented on packages/react-ui/components/GlobalLoader/__stories__/GlobalLoader.stories.tsx
> +  const items = [0.5, 1, 2, 4, 8, 16];
А я думал почему-то что должна =)
Но всё равно текущая анимация кажется странной. По истечению овертайма полоска схлопывается вправо, а потом разворачивается справа-налево.

2022-01-19 15:54 UTC, dzekh commented on packages/react-ui/components/GlobalLoader/__stories__/GlobalLoader.stories.tsx
> +  const items = [0.5, 1, 2, 4, 8, 16];
да, то что она схлопывается и потом разворачивается выгладит странно

2022-01-21 06:28 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/__stories__/GlobalLoader.stories.tsx
> +  const items = [0.5, 1, 2, 4, 8, 16];
Хотя я не смогла повторить в этом примере такое ошибочное поведение, я нашла небольшую уязвимость в коде, которая могла это вызвать и исправила ее. 

@dzekh, когда Максим говорил, что анимация ошибки не включается, я думаю он имел ввиду, что не запускается спиннер после того, как вышло время ожидания ответа от сервера

2022-01-21 07:58 UTC, dzekh commented on packages/react-ui/components/GlobalLoader/__stories__/GlobalLoader.stories.tsx
> +  const items = [0.5, 1, 2, 4, 8, 16];
Да, я тоже так понял.

2022-01-27 04:53 UTC, lossir approved these changes
Думаю, для первой итерации достаточно. Посмотрим, на сколько удобным окажется АПИ.
Уже сейчас хочется заменить простые коллбэки на подписку на события, например:
```typescript
type Stage = 'start' | 'reject' | 'accept' | 'done';
GlobalLoader.on(stage: Stage, handler(stage: Stage) => void): void
```
Но, можно оставить это на потом.

2022-02-03 09:47 UTC, zhzz commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    // });
Вероятно, из-за того, что `lodash.debounce` [замокан](https://github.com/skbkontur/retail-ui/blob/aa8319f6bb3f5ce6652cbc737b466770667ede91/packages/react-ui/test-setup.js#L10-L15).

2022-02-03 10:10 UTC, merged