docs(Button): enhance documentation
skbkontur/retail-ui pull request #2613
Opened 2021-11-02 22:41 UTC by JackUait

Улучшил документацию контрола `Button`: добавил новые примеры, дополнил описание старых, добавил описание для пропов.

Проп `focused` передаётся в этот контрол только номинально. Нужно понять нужен ли он и затем восстановить поведение, либо удалить его.

У пропа `arrow` неконсистентное `API`. Сейчас у пропа `arrow` такой тип: `arrow?: boolean | "left"`. Правильно было бы временно изменить тип пропа на `arrow?: boolean | "left" | "right"` и в  одном из мажорных релизов избавиться от `boolean` поменяв тип на `arrow?: "left" | "right"`.

С пропами  `focused`, `warning` и `error` та же проблема, что и в [#2606](https://github.com/skbkontur/retail-ui/pull/2606#discussion_r740847532).

2021-11-07 10:06 UTC, zhzz requested changes
Похоже, что проп `focused` тоже не нужен.

На счет `arrow` в принципе согласен. Однако, в текущем типе смысл тоже есть. Вероятно, что правая стрелка более популярна. Поэтому, в целях удобства и экономии было выбрано такое API. Если поменяем, то потеряем в этом. Не уверен, что стоит того.

2021-11-08 00:34 UTC, JackUait commented
Удалил проп `focused`.

2021-11-08 00:50 UTC, JackUait commented on packages/react-ui/components/Button/Button.md
> +Пример кнопки-чекбокса.
На самом деле такой компонент и по семантике не проходит. Если действительно нужен такой контрол как кнопка-чекбокс, то нужно расширять `API` контрола `Checkbox`, чтобы была возможность рендерить кастомный компонент.

Так что пока удаляю пример и добавляю `@ignore` для пропа.
Но предлагаю всё же дождаться ответа @dzekh, чтобы понять должен ли чекбокс иметь возможность рендерить кастомные компоненты, потому что я довольно часто встречаю потребность в чекбоксах необычной формы.

2021-11-08 00:52 UTC, JackUait commented on packages/react-ui/components/Button/Button.md
> +<Button autoFocus>Создать отчёт</Button>;
Хах, действительно)

2021-11-08 01:34 UTC, JackUait commented
Что насчёт того, чтобы добавить `"right"` в проп `arrow` (не удаляя `boolean`) и затем (ближе к мажорному релизу) провести исследование на тему того, используют ли разработчики новое `API` и на основании этого сделать выводы о том, стоит ли удалять `boolean`.

Чтобы провести исследование достаточно будет в организации выполнить поиск трёх строк и посчитать вхождения: 
1. `arrow="right"`
2. `arrow='right'`
3. `arrow`

Первые две строки помогут понять используют ли пользователи новый синтаксис. 
Третья строка поможет понять сколько пользователей использовали синтаксис `arrow` после обновления. Для третьей строки нужно будет использовать сортировку `Recently indexed`.

Если в ближайшем мажорном релизе исследование не даст положительных результатов, нужно будет провести исследование повторно при следующем мажорном релизе, если исследование также не даст положительных результатов - значит стоит оставить оба варианта т.е. `"right" | boolean`. 

Отрицательные результаты породят ещё большую неконсистентность, мало того, что в библиотеке, но и в самих проектах. Но мне кажется, что риск стоит того, потому что одно из главных правил при написании кода это _"Явное решение всегда лучше неявного"_. Сейчас библиотека поступает очень странно, предоставляя пользователю явный способ создания стрелки указывающей влево и неявный способ создания стрелки указывающей вправо.

P.S.
Для проведения такого исследования понадобится человек, у которого есть доступ ко всем репам в организации, по идее такой доступ должен быть у DevOps'а.

2021-11-11 16:23 UTC, zhzz commented
Да, ты описал рабочую методику. Но легко провернуть это прямо сейчас мы не можем. А те усилия, которые понадобятся, не стоят того.

Принцип ты упомянул хороший, но лучше всего его использовать на этапе проектирования.

В любом случае, проблем сейчас это особо не приносит. Без повода ломать не будем. Подвернется случай - переделаем.

PS. Эта штука работает. А есть у нас куча других, которые не работают, но должны. Лучше сконцентрировать усилия на них.

2021-11-11 16:29 UTC, zhzz requested changes

2021-11-11 16:29 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +   * Цветовая схема обводки кнопки для ошибки.
Здесь тоже про цветовую схему и ниже про тему.

2021-11-15 12:36 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +   * Тема кнопки.
Здесь еще "тема".

2021-11-16 04:02 UTC, merged