docs(Hint): enhance documentation
skbkontur/retail-ui pull request #2622
Opened 2021-11-05 00:02 UTC by JackUait

Улучшил документацию контрола `Hint`: добавил описание контрола,  добавил описание для пропов, добавил новые примеры.

2021-11-05 00:51 UTC, JackUait commented
Не понял какой сценарий использования у пропа `useWrapper`.

2021-11-07 10:39 UTC, zhzz approved these changes

2021-11-07 10:52 UTC, zhzz requested changes

2021-11-07 10:52 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +   * **Допустимые значения**: `"top left"`, `"top center"`, `"top right"`, `"right top"`, `"right middle"`, `"right bottom"`, `"bottom left"`, `"bottom center"`, `"bottom right"`, `"left top"`, `"lef
Допустимые значения сейчас неплохо достаются из типа. К тому же, список в комментарии получился неполным. 

![image](https://user-images.githubusercontent.com/4607770/140641990-ed949cb4-ab4c-493e-a4e9-88e5d7f75441.png)

2021-11-08 02:11 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.tsx
> +   * **Допустимые значения**: `"top left"`, `"top center"`, `"top right"`, `"right top"`, `"right middle"`, `"right bottom"`, `"bottom left"`, `"bottom center"`, `"bottom right"`, `"left top"`, `"lef
Забыл упомянуть, что этот PR сопряжён с #2623. Там явное указание типа заменяется на `'top' | 'right' | 'bottom' | 'left' | PopupPosition`.

2021-11-08 02:13 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.tsx
> +   * **Допустимые значения**: `"top left"`, `"top center"`, `"top right"`, `"right top"`, `"right middle"`, `"right bottom"`, `"bottom left"`, `"bottom center"`, `"bottom right"`, `"left top"`, `"lef
Недостающие значения добавил.

2021-11-11 16:35 UTC, zhzz approved these changes

2021-11-11 17:34 UTC, merged