refactor(Hint, Tooltip, Popup, PopupMenu): reuse variables
skbkontur/retail-ui pull request #2623
Opened 2021-11-05 13:52 UTC by JackUait

Переиспользовал `PopupPositions` из контрола `Popup` в других компонентах.
Уменьшил репетативность кода, определив массив `PopupPositions` как константный тип.
Добавил константу `DefaultPosition`.
Добавил тип `BasePosition`.

2021-11-07 11:31 UTC, zhzz requested changes
Неплохая идея!

2021-11-07 11:31 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> -    | 'left'
Похоже, что ` 'top' | 'right' | 'bottom'  | 'left'` это локальное расширение `PopupPosition` внутри Hint. И что BasePosition больше нигде не нужен. Почему бы тогда просто не добавить нужных типов к PopupPosition в  внутри самого Hint. Так будет проще, и лучше для доки.

2021-11-07 11:31 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +export type PopupPosition = typeof PopupPositions[number];
Popup это внутренний компонент. Такие компоненты мы не рекомендуем использовать во вне и не экспортируем, скажем, из корня библиотеки. Однако, если мы начинаем активно использовать его типы в публичных компонентах, то пользователям тоже стоит дать это делать. Для этого можно собрать все его типы в отдельный файл, и добавить реэкспорт из него в `index.ts`. Таким образом, компонент останется внутренним, а типы можно будет импортировать из корня пакета.

2021-11-08 02:10 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.tsx
> -    | 'left'
Да, это действительно локальное расширение. Изменил решение.

> Так будет проще, и лучше для доки.

Так в доке же всё равно будет `'top' | 'right' | 'bottom' | 'left' | PopupPosition` и придётся описывать допустимые значения ручками.

2021-11-11 16:39 UTC, zhzz approved these changes

2021-11-11 18:29 UTC, zhzz requested changes
Там ts ругается в PopupMenu.

![image](https://user-images.githubusercontent.com/4607770/141350295-c79d289a-d293-4b09-aad7-f1862a12076a.png)

2021-11-16 07:51 UTC, zhzz commented
Тут еще проблемка осталась, в комменте выше.

2021-11-18 11:29 UTC, zhzz submitted a review, later dismissed

2021-11-18 20:25 UTC, zhzz requested changes
Есть еще одна проблема. Все прошлые массивы позиций в Hint/Tooltip/Popup/PopupMenu отличались между собой порядком, в котором эти позиции были перечислены. Соответственно, поменялся порядок, в котором эти позиции применяются. Только сейчас это заметил на упавших скриншотах.

2021-11-22 03:44 UTC, zhzz requested changes
Проблемка из предыдущего коммента осталась.

2021-11-24 07:25 UTC, JackUait commented
Это не проблема, а мёд для моих ушей! 
Я изначально хотел решить эту задачу использовав композицию, но отказался от неё в пользу простоты.

2021-11-24 09:17 UTC, JackUait commented
Я имел ввиду, что можно использовать изначальную, более правильную (с моей точки зрения) реализацию с композицией, что также поможет решить проблему:)

2021-11-24 09:32 UTC, JackUait commented
Заменил монолит `PopupPositions` композицией. Теперь массив `PopupPositions` состоит из массивов `PopupPositionsTop`, `PopupPositionsRight`, `PopupPositionsBottom` и `PopupPositionsLeft`, при этом каждый из составных массивов можно использовать независимо от  `PopupPositions`. Значения в массиве `PopupPositions` хранятся по часовой стрелке.
Заменил деструктуризацию массива в `PopupMenu` на `Readonly` тип.
Изменил название типа `PopupPosition` на `PopupPositionsType`, чтобы не путать его со значением `PopupPositions`.

При этом скриншотные тесты скорее всего всё равно упадут, так как направления в файлах были перемешаны.
```tsx
ControlX.tsx
const Positions = [
	  ...
	  'left right',
	  'left top',
	  'left bottom',
	  ...
]
```

```tsx
ControlY.tsx
const Positions = [
	   ...
	  'left top',
	  'left right',
	  'left bottom',
	  ...
]
```
Я хочу понять насколько это критично.

2021-11-30 19:14 UTC, zhzz commented
Думаю, критично. В гайдах Тултипа и Хинта указаны приоритеты позиций, и они отличаются. Сломаны скриншоты Хинта.

2021-11-30 22:57 UTC, JackUait commented
Я имел ввиду, что в позициях внутри одного направления в разных контролах могут быть перемешаны вторичные направления.

В одном контроле может быть `'left right', 'left top', 'left bottom'`, а в другом `'left top', 'left right', 'left bottom'`, то есть первое и второе вторичные направления поменяны местами. При этом, оба примера следуют гайдам, так как там идёт речь только об основном направлении.

Очевидно, что это было сделано ненамеренно и нет смысла завязываться на этом поведении, вводя новые костыли на замену старым. Правильнее было бы изменить скриншотные тесты.

2021-12-01 12:47 UTC, zhzz commented
Они не перемешаны, а намеренно в определенном порядке выставлены. В тултипе против часовой. В хинте с приоритетом к центру. 

Скриншоты переаппрувить нельзя, потому что дефолтная позиция поменялась.

![image](https://user-images.githubusercontent.com/4607770/144237058-c117793e-39bc-4649-9dd9-1208e7c65dd3.png)

2021-12-01 19:01 UTC, JackUait commented
Круто! Не думал, что у задачи такой уровень проработки.

Восстановил изначальный порядок позиций.

**P.S.**
Думал над тем, как можно решить эту задачу через функцию, которая принимала бы два аргумента и на основании этих аргументов генерировала бы массив позиций.
Но понял, что решение "в лоб" лучше, потому что:
1. Основное направление может находиться на одной из 4-ёх позиций (т.е. 4-е значения для первого аргумента).
2. Существует 9 возможных комбинаций основной и вторичной позиций (т.е. 9 значений для второго аргумента, которым нужно придумать описательное название).
3. В массиве всего 12 значений и он используется всего в четырёх компонентах.

Так что функция не стоит свеч.

2021-12-01 19:12 UTC, JackUait commented
Заметил ещё одну интересную особенность: 
1. У основных направлений `left` и `right` центральное вторичное направление называется `middle`.
2. У основных направлений `top` и `bottom` центральное вторичное направление называется `center`.

Есть ли у этого нейминга какие-то основания?
И почему бы нам не привести всё к единой форме?

С этими вопросами нужно разобраться сейчас, так как если мы решим изменить нейминг в будущем, это будет ломающее изменение (из-за того, что мы даём доступ к типам пользователям).

2022-01-31 11:50 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    pos: DefaultPosition,
В доке теперь дефолтное значение отображается как `PopupPositions[0]`, что мало о чем говорит.  Зато тип PopupPositionsType стал нормально раскрываться и необязательно его вручную расписывать в описании пропа `allowedPositions`. Можно снова пройтись по этим местам в доке и обновить.

2022-01-31 13:59 UTC, JackUait commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    pos: DefaultPosition,
Убрал тип из `allowedPositions` и добавил упоминание о значении по умолчанию в `pos`.
Не стал добавлять полное описание для `pos`, думаю что Максим всё равно будет его менять и в этом сейчас нет смысла.

2022-01-31 14:00 UTC, JackUait commented
Смёржил актуальный мастер.

2022-01-31 21:58 UTC, JackUait commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    pos: DefaultPosition,
Задать значение по умолчанию через `@default` не получилось, так как `styleguidist` перебивает пользовательское значение своим.

2022-02-02 05:54 UTC, zhzz approved these changes

2022-02-02 05:56 UTC, merged