docs(Checkbox): enhance documentation
skbkontur/retail-ui pull request #2624
Opened 2021-11-05 23:03 UTC by JackUait

Улучшил документацию контрола `Checkbox`: удалил описание контрола, добавил описание для пропов и методов, добавил новые примеры и отрефакторил старые.

2021-11-07 11:02 UTC, zhzz requested changes

2021-11-08 01:42 UTC, JackUait commented on packages/react-ui/components/Checkbox/Checkbox.md
> -Чекбокс может быть в состоянии "частично выбран". Как и в браузерном чекбоксе, это состояние влияет только на внешний вид и не влияет на состояние `checked`. `indeterminate` устанавливается в констру
Да, не заметил, что в статье на `MDN` эта информация отсутствует.

2021-11-09 19:06 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.md
> +Чекбокс имеет несколько тем. <br/> _Примечание_: у состояний ошибки и предупреждения при фокусе цвет не меняется на синий.
Упоминание тем осталось.

2021-11-09 20:03 UTC, JackUait commented on packages/react-ui/components/Checkbox/Checkbox.md
> +Чекбокс имеет несколько тем. <br/> _Примечание_: у состояний ошибки и предупреждения при фокусе цвет не меняется на синий.
Заменил на _"У чекбокса есть несколько состояний"_.

2021-11-10 04:32 UTC, zhzz approved these changes

2021-11-10 04:55 UTC, merged