[SidePage] Добавить проп offset
skbkontur/retail-ui pull request #2626
Opened 2021-11-09 06:44 UTC by HelenaIsh

fix #2352 
Проп offset задает отступ от края экрана в пикселях

2021-11-09 11:40 UTC, lossir requested changes

2021-11-09 11:40 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +  offset?: number;
Давай добавим возможность передавать строку и строку, как для `width`. На случай, если разработчику понадобятся другие единицы измерения.

2021-11-10 05:35 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +  offset?: number;
> строку и строку

ахах 😅, сори)

2021-11-10 11:21 UTC, lossir approved these changes

2021-11-18 19:06 UTC, zhzz approved these changes

2021-11-19 04:17 UTC, merged