[Customization] - переименовать label в caption
skbkontur/retail-ui pull request #2629
Opened 2021-11-09 09:25 UTC by HelenaIsh

fix #2196 

Переименовано в компонентах Radio, Checkbox, Switcher

2021-11-10 09:49 UTC, lossir requested changes

2021-11-10 09:49 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +  caption?: string;
Это ломающее изменение. Поэтому надо применить "мягкое удаление", т.е. сначала задеприкетить, а удалить в мажорном релизе.
Вот здесь неплохой текст на эту тему - [What is the meaning of deprecated code?](https://www.programmerinterview.com/technical-vocabulary/what-is-deprecated-code/)

Пример реализации можешь подглядеть в Toggle:
https://github.com/skbkontur/retail-ui/blob/513240fd43a03f4b8334dded086212199fc89a99/packages/react-ui/components/Toggle/Toggle.tsx#L69-L72

https://github.com/skbkontur/retail-ui/blob/513240fd43a03f4b8334dded086212199fc89a99/packages/react-ui/components/Toggle/Toggle.tsx#L98-L102

2021-11-10 09:49 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static radioCaptionDisplay = 'inline-table';
Это тоже ломающее изменение. Переменные темы можно оставить как есть. А переименовать потоп, вместе с удалением пропа `label`.
Заодно можно будет добавить кодмод, как Егор делал [для Аддонов 3.0](https://github.com/skbkontur/retail-ui/pull/2574).

2021-11-18 06:45 UTC, lossir approved these changes

2021-11-18 12:00 UTC, zhzz approved these changes

2021-11-19 09:41 UTC, zhzz approved these changes

2021-11-19 09:42 UTC, merged