feat(react-ui-validations): add independent validation
skbkontur/retail-ui pull request #2632
Opened 2021-11-10 18:33 UTC by lossir

## Независимые валидации
> Логично и ожидаемо если по потере фокуса будет валидироваться и подсвечиваться только то поле, которое потеряло фокус.

*Цитата отсюда https://github.com/skbkontur/retail-ui/issues/2412#issuecomment-926109432*

Изначально хотел добавить новый тип вилидации (`selflostfocus`), но в итоге решил добавить отдельный атрибут `independent`. 
Зависимость валидаций [в документации](http://tech.skbkontur.ru/react-ui-validations/#/dependent-validation) описана как фича. Поэтому подумал, что так будет немного понятнее и добавил отдельную страницу «Незивиcимые валидации».

2021-11-19 12:08 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +Чтобы исключить независимые поля надо вторым аргументом `withoutIndependent` передать `true`.
А зачем может быть нужно исключить независимые поля при валидации всей формы?

2021-11-24 11:53 UTC, zhzz requested changes

2021-11-24 11:53 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Displaying/ValidationType/ValidationType.md
> +
Не стоит ли этот абзац в самое начало файла перенести? После ссылки на гайды. Т.к. это вроде общая информация.

2021-11-24 11:53 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +Например, несколько полей проверяются на пустое значение, и тип валидации - `lostfocus`:
Здесь стоит упомянуть, что такое использование [осуждается гайдами](https://guides.kontur.ru/principles/validation/#09). В этом источник всей проблемы вообще. Если придерживаться гайдов, то проблемы нет. Видимо на этом и основана текущая реализация зависимости.

2021-11-24 11:53 UTC, zhzz commented on packages/react-ui-validations/src/ValidationContext.tsx
> +      (x) => !withoutIndependent || !x.isIndependent() || getType(x.props.validation) === 'submit',
В целом, мне кажется, что флаги `withoutIndependent` не нужны. Но тут еще и странное исключение в случае `submit`. В чем логика? `validate` раньше запускал валидацию вне зависимости от типа.

2021-11-24 11:53 UTC, zhzz commented on packages/react-ui-validations/src/Validations/ValidationBuilder.ts
> +    typeOrValidationInfo?: ValidationBehaviour | InvalidValidationInfo,
Думаю, для этого лучше будет использовать [перегрузку](https://www.typescriptlang.org/docs/handbook/functions.html#overloads) метода. Тогда ts не даст передать лишних аргументов. 

И можно дать передавать _вторым_ аргументом привычный полноценный `ValidationInfo`, в котором тоже есть `message`.

2021-12-10 06:00 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +ru/principles/validation/#09)).
Не рекомендуется для 'lostfocus'.

2021-12-10 06:00 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +По умолчанию, потеря фокуса на одном поле вызовет валидацию и на другом.
Предыдущий пример с валидацией пустого значения был проще и популярнее. Именно с ним пользователи приходили. Думаю, лучше оставить его.

К тому же, если исключить из этого проверку пустого значения, то проблема пропадает.

И одинаковый паттерн ведь не требуется. Ничего не изменится, например, если будут телефон и email, или что-то еще.

2021-12-10 06:00 UTC, zhzz commented on packages/react-ui-validations/src/Validations/ValidationBuilder.ts
> +  ): unknown {
Почему `unknown`?

2021-12-10 07:34 UTC, lossir commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +По умолчанию, потеря фокуса на одном поле вызовет валидацию и на другом.
> И одинаковый паттерн ведь не требуется

Тут не очень понял

2021-12-10 07:48 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +По умолчанию, потеря фокуса на одном поле вызовет валидацию и на другом.
> когда несколько полей имеют одинаковый шаблон проверки

> Или, у полей одинаковый паттерн валидации

Я про то, что одинаковость тут не является обязательным условием, но из текста может сложиться обратное впечатление.

2021-12-11 07:41 UTC, lossir commented on packages/react-ui-validations/docs/Pages/Validator/Independent/Independent.md
> +По умолчанию, потеря фокуса на одном поле вызовет валидацию и на другом.
Постарался всё переписать, чтобы воспринималось однозначно.

2021-12-13 10:18 UTC, zhzz approved these changes

2021-12-13 11:30 UTC, merged