chore(forwardRefAndName): decorator for forwarding name and ref to component
skbkontur/retail-ui pull request #2637
Opened 2021-11-12 09:11 UTC by JackUait

2021-11-15 10:32 UTC, zhzz requested changes
Выглядит как то, что нужно.

2021-11-15 10:32 UTC, zhzz commented on packages/react-ui/lib/forwardRefAndName.ts
> +export interface CompoundedComponent<T> extends React.ForwardRefExoticComponent<T> {
А почему именно такое имя? Может лучше будет что-то вроде `ReactUIComponent`? Потому что эта метка как раз служит для идентификации наших компонентов среди прочих.

2021-11-15 10:32 UTC, zhzz commented on packages/react-ui/lib/forwardRefAndName.ts
> +  const renderWithRef = React.forwardRef(render) as CompoundedComponent<Props>;
Оригинальный `forwardRef` не совсем такой тип возвращает. Если сейчас попробовать взять ref у компонента с этим декоратором, то TS заругается на отсутствие пропа ref.

![image](https://user-images.githubusercontent.com/4607770/141766325-51267658-2c63-4800-a216-5af1992696dc.png)

2021-11-15 17:46 UTC, JackUait commented on packages/react-ui/lib/forwardRefAndName.ts
> +  const renderWithRef = React.forwardRef(render) as CompoundedComponent<Props>;
Починил. Также убрал возможность передавать `defaultProps` в компонент. И заменил импорт `React`'а на деструктурирование `forwardRef`, в целях оптимизации потребления памяти.

2021-11-15 21:02 UTC, JackUait commented on packages/react-ui/lib/forwardRefAndName.ts
> +export interface CompoundedComponent<T> extends React.ForwardRefExoticComponent<T> {
Думаю, стоит пойти дальше и назвать тип `ReactUIComponentWithRef` так как мы передаём в него ещё и `ref`.

2021-11-16 06:53 UTC, zhzz approved these changes

2021-11-16 06:53 UTC, merged