[Button]  фокус после состояния loading
skbkontur/retail-ui pull request #2661
Opened 2021-11-17 08:03 UTC by HelenaIsh

fix #2533 

Состояние loading блокировало кнопку (переводила ее в состояние disabled), а в этом состоянии не работают евенты onBlur и пр.  
Удалила состояние disabled, тк все равно заблокированность задается классом disabled

2021-11-19 07:15 UTC, lossir requested changes

2021-11-19 07:15 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> -      disabled: disabled || loading,
В состояние `loading` кнопка должна быть заблокированной. Т.е. не должны работать события, и при табуляции она не должна попадать в фокус.
Поэтому эту строчку надо вернуть.

Здесь лучше использовать метод [`getDerivedStateFromProps()`](https://ru.reactjs.org/docs/react-component.html#static-getderivedstatefromprops). 

```tsx
public static getDerivedStateFromProps(props: ButtonProps, state: ButtonState) {
  if (props.loading) {
    return { focusedByTab: false };
  }
  return state;
}
```

2021-11-19 07:45 UTC, HelenaIsh commented on packages/react-ui/components/Button/Button.tsx
> -      disabled: disabled || loading,
а второй return разве не должен null  возвращать?
Из документации:
>  Он должен вернуть объект для обновления состояния или null, чтобы ничего не обновлять.

2021-11-19 09:13 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> -      disabled: disabled || loading,
Да, ты права. Я ошибся. Второй `return` должен возвращать `null`.
Правильно сделала, что проверила. Всегда так делай)

2021-11-21 07:26 UTC, dzekh commented
А как эти изменения повлияют на фокус, после того как кнопка будет разблокирована, фокус на неё вернется? 
Что я имею ввиду: я как пользователь нажал на кнопку не важно чем мышью или прийдя табом, ожидаю что фокус будет на ней. Даже после нажатия и после того как действие совершится и кнопка вернется из состояния загрузки в обычное состояние, я ожиданию что фокус вернется на неё и нажав таб, фокус перейдет на следующий после кнопки контрол. Или ожидаю что при нажатии пробела или ентера нажмется эта кнопка еще раз. 
Будет странно если фокус сбросится и мне придется табом снова идти по всем контролам. Хотя я не проверял, как это работает в нативных контролах.

2021-11-22 04:16 UTC, HelenaIsh commented
> А как эти изменения повлияют на фокус, после того как кнопка будет разблокирована, фокус на неё вернется?
В данный момент фокус не вернется. Хорошее замечание, подумаю как это реализовать

2021-11-22 06:51 UTC, HelenaIsh commented
В таком случае предлагаю блокировать все действия с кнопкой в состоянии loading кроме onblur и onfocus. Таким образом, в данном состоянии сохранится фокус, если он был до этого, а также у нас будет возможность перейти табом к другим элементам

2021-11-22 06:55 UTC, HelenaIsh commented
@dzekh 

Вова, а на кнопку в состоянии loading можно прийти табом? То есть на ней должен появится фокус в таком случае?

2021-11-22 08:11 UTC, lossir commented
@dzekh При состоянии `disabled={true}` фокус пропадёт с кнопки и не вернётся после установки `disabled={false}`. Но при нажатии на `Tab` фокус переключится на следующий табулируемый элемент. Как будто бы он остался на выключенной кнопки.

Получается, при возвращении `loading={false}`, должна вернуться синяя обводка и фокус?
А до этого кнопка должна полностью вести себя и выглядеть как `disabled={true}`? 
Но если за время `loading={true}` пользователь кликнул где-то ещё, то мы уже не должны этого делать.

2021-11-22 09:18 UTC, dzekh commented
> Вова, а на кнопку в состоянии loading можно прийти табом? То есть на ней должен появится фокус в таком случае?

нет, контрол в состоянии лоадинг так же заблокированный пропускается. Максим хорошо описал про дизаблед:

> При состоянии `disabled={true}` фокус пропадёт с кнопки и не вернётся после установки `disabled={false}`. Но при нажатии на `Tab` фокус переключится на следующий табулируемый элемент. Как будто бы он остался на выключенной кнопки.

Да, это ожидаемо, так же должно быть с сотоянием лоадинга.

> Получается, при возвращении `loading={false}`, должна вернуться синяя обводка и фокус? А до этого кнопка должна полностью вести себя и выглядеть как `disabled={true}`? 

Если до этого пришли табом и обводка была — по хорошему обводка должна вернуться вместе с фокусом. Если контрол получил фокус мышью и обводки на нем не было — визуально обводки не должно появиться. Но Таб должен переводить фокус на следующий контрол. 

> Но если за время `loading={true}` пользователь кликнул где-то ещё, то мы уже не должны этого делать.

Да, так.

2021-11-22 10:04 UTC, lossir commented
> «По хорошему» — я имею ввиду в идеальном мире, но это не критично, если это сложно реализовать или появляются какие-то противоречия.

Кажется, это можно порешать добавив ещё один флаг в стайте, и накрутив логики. 

@HelenaIsh Лена, если хочешь, то можешь попробовать. Если считаешь слишком запарно, то просто откати последние коммиты.

Текущая реализация с обнулением нативных событий напрямую очень не очень.

2021-11-22 10:20 UTC, HelenaIsh commented on packages/react-ui/components/Button/Button.tsx
> -      disabled: disabled || loading,
проблема с этим вариантом в том, что после завершения загрузки, если я не ухожу никуда с этой кнопки, то она не включается с клавиатуры: 
комментарий от Вовы чуть ниже:

>  Или ожидаю что при нажатии пробела или ентера нажмется эта кнопка еще раз.

2021-11-22 10:35 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> -      disabled: disabled || loading,
Да, этот сценарий Вова назвал "по-хорошему". Если хочешь его реализовать, то ок.

2021-11-24 09:56 UTC, lossir commented
⚠️ Надо будет засквошить

2021-11-24 10:05 UTC, lossir approved these changes

2021-11-30 04:43 UTC, zhzz approved these changes
👍 

Получилось поведение идентичное нативной кнопке.

Похожая проблема наблюдается и в других компонентах с фокусом и пропом disabled.

2021-12-02 11:08 UTC, merged