chore(withClassWrapper): HOC for converting class components  to functional components
skbkontur/retail-ui pull request #2662
Opened 2021-11-17 09:59 UTC by JackUait

`HOC` для переезда на функциональные компоненты.

Оборачивает функциональные компоненты в классовую обёртку, позволяя сохранить текущее поведение `ref`'ов и перевести компоненты на функциональные рельсы.

Также обёртка предоставляет доступ к функциональному компоненту через `ComponentName.FC`.

2021-11-17 14:38 UTC, JackUait commented
Проблема с тем, что TypeScript не понимает, что мы пытаемся использовать класс как тип, а не как значение решается определением нового типа, с таким же именем как у класса.

Тип должен выглядеть следующим образом: `type ComponentName = InstanceType<typeof ComponentName>`.

```tsx
interface FCProps {
  ...
}

const FC = (props: FCProps) => {
  return <div {...props} />;
};

export const WrappedFC = withClassWrapper('WrappedComponent', FC);
export type WrappedFC = InstanceType<typeof WrappedFC>;

const UserComponent = () => {
  const ref = React.useRef<WrappedFC>(null);

  return <WrappedFC ref={ref} />;
};
```

_Примечание:_ и тип, и класс должны быть экспортированы.
_Ещё одно примечание:_ TypeScript всегда будет предлагать импортировать только одну сущность и в зависимости от контекста будет решать использовать сущность как тип или как значение.

2021-11-17 14:54 UTC, JackUait commented
Проблему с затиранием `ref`'а при использовании `useImperativeHandle` можно решить создав новый `ref` внутри компонента, который будет ссылаться на DOM элемент.

```tsx
const Input = React.forwardRef<HTMLInputElement>((_, ref) => {
  const inputRef = React.useRef();

  React.useImperativeHandle(ref, () => ({
    node: inputRef.current,
    focus: () => {
      inputRef.current.focus();
    },
  }));

  return <input ref={inputRef} />;
});

const UserComponent = () => {
  const ref = React.useRef(null);

  const clickHandler = () => {
    ref.current.focus();
  };

  return (
    <>
      <button onClick={clickHandler}>Вызвать фокус</button>
      <Input ref={ref} />
    </>
  );
};
``` 

Так пользователю и нам будут одновременно доступны императивные методы и ссылка на элемент DOM, через `ref.current.methodName` и `ref.current.node` соответственно.

2021-11-21 01:38 UTC, JackUait commented
Добавил возможность оборачивать функциональные компоненты, которые содержат методы, а также расширил документацию.

2021-11-21 01:45 UTC, JackUait commented
Пример использования `HOC`'а с функциональным компонентом содержащим методы.

```tsx
interface InputProps {
  type: 'a' | 'b' | 'c';
  other: number;
}

// Первый аргумент forwardRefAndName должен быть пустым.
const InputFC = forwardRefAndName<{ }, InputProps>('LinkFC', (props, ref) => {
  const inputRef = React.useRef<HTMLInputElement>(null);

  // Определяем методы, которые будут доступны классу.
  React.useImperativeHandle(ref, () => ({
    focus: () => {
      inputRef.current?.focus();
    },
    test: () => {
      console.log('test is passed');
    },
  }));

  return <input ref={inputRef} {...props} />;
});

// Названия должны совпадать с названиями из useImperativeHandle.
const methodsNames = ['focus', 'test'] as const;
type NamesType = typeof methodsNames[number];
type MethodsType = { [K in NamesType]: () => void };

const Wrapped = withClassWrapper(InputFC, methodsNames);
interface Wrapped extends InstanceType<typeof Wrapped>, MethodsType {}

const UserComponent = () => {
  const ref = React.useRef<Wrapped>(null);

  return (
    <>
      {/*
       *
       * Обращаемся к методам определённым в классе.
       * Методы в классе имеют те же имена, что и методы в оборачиваемой функции.
       * Методы из класса просто вызывают методы из функции.
       *
       * */}
      <button onClick={() => ref.current?.focus()}>call focus on input</button>
      <Wrapped ref={ref} type="c" other="wrong value" />
    </>
  );
};
```

2021-11-21 01:58 UTC, JackUait commented
При экспорте компонента содержащего методы меняется типизация. 
Необходимо вручную расширить тип обёртки методами.

Так как методы определённые в `useImperativeHandle` не могут возвращать значений, их тип всегда будет `() => void`.
Следовательно, код ниже достаточно копи-пастить в компоненты с методами, заменяя `ComponentName` и содержимое массива `methodsNames`. 
```tsx
const methodsNames = ['name1', 'name2', 'name3'] as const;
type NamesType = typeof methodsNames[number];
type MethodsType = { [K in NamesType]: () => void };

const ComponentName = withClassWrapper(ComponentNameFC, methodsNames);
type ComponentName = InstanceType<typeof ComponentName> & MethodsType;
```

2021-11-23 09:22 UTC, JackUait commented
Изменил способ определения методов в классовом компоненте. Теперь они не передаются отдельным массивом, а забираются напрямую из ref-ки функционального компонента.

2021-11-23 14:31 UTC, JackUait commented
Финальный способ определения типа компонента с публичными методами и свойствами.
```tsx
// Объявляем тип методов и свойств определённых в useImperativeHandle.
type InstanceMethods = { focus: () => void; blur: () => void; id: string };

// Передаём этот тип в instanceRef .
const InputFC = forwardRefAndName<HTMLInputElement, { instanceRef?: React.MutableRefObject<InstanceMethods | null> }>(
  'InputFC',
  (props, ref) => {
    const inputRef = React.useRef<HTMLInputElement>(null);
    ref = inputRef;

    React.useImperativeHandle(props.instanceRef, () => ({
      focus: () => {
        inputRef.current?.focus();
      },
      blur: () => {
        inputRef.current?.blur();
      },
	  id: 10fecg5,
    }));

    return <input ref={inputRef} {...props} />;
  },
);

export const Wrapped = withClassWrapper(InputFC);
// Добавляем этот тип к экспортируему типу.
export type Wrapped = InstanceType<typeof Wrapped> & InstanceMethods;
```

2021-11-24 04:30 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Почему бы просто не использовать `Object.getOwnPropertyDescriptors` и `Object.defineProperties`?

2021-11-24 05:17 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
`Object.getOwnPropertyDescriptors` возвращает `configurable: true, enumerable: true, writable: true` для свойств полученных из `instanceRef`. Нам нужно чтобы свойство было `configurable: false, enumerable: true, writable: false`, чтобы пользователи могли забирать значения, но не могли изменять их.

Нам всё равно придётся пройтись по дескрипторам циклом и поменять `configurable` и `writable` на `false`.

Или у тебя есть план?

2021-11-24 09:26 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Он ведь возвращает дескрипторы объекта как они есть, не меняет их. Если хочется их настроить, получается, что нужно делать это внутри FC (т.к. в будущем все будет браться напрямую из него), а задача ClassWrapper просто скопировать.

2021-11-24 09:55 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Как по мне, это выглядит как недоработка со стороны `React`'а и это поведение наоборот нужно будет выносить в отдельный хук, чтобы не позволять пользователям менять реализацию свойств объекта получаемого из `instanceRef`.

Пример ниже отрабатывает и ни `TypeScript`, ни `React` на него не ругаются.
```tsx
React.useEffect(() => {
    // меняем реализацию
    ref.current.focus = () => console.log('очень, очень не хорошо');
  }, []);
```

Чувствую, что дефолтное поведение `useImperativeHandle` вызовет больше проблем, чем решит. Пользователь вместо того, чтобы написать в чатик и попросить исправить баг потенциально может переписать реализацию.

2021-11-24 10:06 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Но в любом случае же этот вопрос должен быть решен для instanceRef вне зависимости от того, используется ClassWrapper или нет.

2021-11-24 10:12 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Да, теперь понял твою мысль. Сейчас изменю реализацию.

2021-11-24 11:02 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Что думаешь насчёт утилиты `objectToArray`? Вроде полезная штука. Может стоит её оставить?

2021-11-24 11:06 UTC, JackUait commented
Изменил механизм определения дескрипторов свойств. Теперь дескрипторы наследуются из функционального компонента, а не определяются внутри класса-обёртки.

2021-11-29 04:53 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +      definePublicProperties<ClassWrapper>(this, instanceProperties);
Не большой фанат добавлять функциональность про запас, которая в данный момент не нужна. С большой вероятностью она и потом не понадобится. Останется мертвым кодом, будет вызывать вопросы о том, зачем она есть, если явно не используется. Еще принцип такой есть, [yagni](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

А в чем принципиальное отличие `objectToArray` от `Object.entries`?

2021-11-29 05:59 UTC, zhzz requested changes

2021-11-29 05:59 UTC, zhzz commented on packages/react-ui/lib/testUtils.ts
> +}
В Jest 27 [подвезли](https://jestjs.io/docs/api#describeeachtablename-fn-timeout) возможность достичь этого из коробки используя поля объекта в заголовке через `$`.  Можно обновиться и нужда в утилите отпадет.

2021-11-29 05:59 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +        />
Здесь TS нашей версии  `4.1.3` ругается и не дает билдить `yarn workspace @skbkontur/react-ui build`.
В `lib/utils.ts` тоже есть проблема.

2021-11-29 06:12 UTC, zhzz commented
Финальный вариант типизации с полями инстанса получается так выглядит, да?

```ts
interface InstanceFields { ... }
export type Wrapped = InstanceType<typeof Wrapped> & InstanceFields;
```

Вроде норм, учитывая, что отдельный интерфейс с полями у нас всегда будет в наличии в тех компонентах, где эти поля есть. И еще есть надежда, что можно этот интерфейс прокинуть внутрь `withClassWrapper` и подмешать к инстансу автоматически, но это не обязательно.

2021-11-29 16:40 UTC, JackUait commented on packages/react-ui/lib/testUtils.ts
> +}
Тогда удаляю файл с утилитами, тем более, что утилита из файла сейчас не понадобится, так как я также удалил `objectToArray`.

2021-11-29 18:18 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +        />
Если я правильно понял ошибку, то `TypeScript` не понимает, что оба типа содержат `ref`. При этом `TypeScript` не понимает это только на стадии билда. `TypeScript` встроенный в `IDE` понимает что оба типа содержат `ref`, поэтому не выдаёт ошибку. Вероятно, это можно пофиксить только использовав `@ts-ignore`.
```ts
Type '{ instanceRef: RefObject<T>; } & Readonly<P> & Readonly<{ children?: ReactNode; }>' is not assignable to type 'IntrinsicAttributes & PropsWithoutRef<P> & RefAttributes<T>'
Type '{ instanceRef: RefObject<T>; } & Readonly<P> & Readonly<{ children?: ReactNode; }>' is not assignable to type 'PropsWithoutRef<P>'.
```

2021-11-29 18:21 UTC, JackUait commented on packages/react-ui/lib/withClassWrapper.tsx
> +        />
Вообще странно, что эти ошибки сыпятся только на стадии билда.

2021-11-30 13:01 UTC, zhzz commented on packages/react-ui/lib/withClassWrapper.tsx
> +        />
При билде просто используется именно версия ts из ропозитория. А IDE может свою иметь.

2021-11-30 13:01 UTC, zhzz approved these changes
Можно пробовать)

2021-11-30 16:33 UTC, zhzz approved these changes

2021-11-30 16:37 UTC, merged