refactor(isNonNullable): replace explicit undefined checks with isNonNullable util
skbkontur/retail-ui pull request #2676
Opened 2021-11-30 00:37 UTC by JackUait

Заменил явные проверки на `undefined` на утилиту `isNonNullable`, там где это было возможно.

А также:
1. Переписал тесты для утилиты `isNonNullable`.
2. Заменил тернарные операторы на `if-else`.
3. Избавился от "магических чисел" при определении високосного года.

2022-06-14 10:32 UTC, khlutkova requested changes
Подлей свежий мастер, пожалуйста

2022-06-16 08:05 UTC, JackUait commented on packages/react-ui/components/Gapped/Gapped.tsx
>      } else {
Ветка `else` исчезла со свежим мастером)

2022-06-16 08:14 UTC, JackUait commented on packages/react-ui/lib/date/InternalDateValidator.ts
> +    if (isNonNullable(type)) {
Вынес эту логику в отдельную функцию за пределами класса

2022-06-17 10:42 UTC, zhzz requested changes

2022-06-17 10:42 UTC, zhzz commented on packages/react-ui/components/Loader/Loader.tsx
> +          {isNonNullable(component) ? component : <Spinner type={type} caption={caption} />}
`x !== undefined` и `isNonNullable(x)` это же разные вещи

2022-06-20 21:24 UTC, JackUait commented on packages/react-ui/components/Loader/Loader.tsx
> +          {isNonNullable(component) ? component : <Spinner type={type} caption={caption} />}
Не уверен как бы я аргументировал большинство кейсов в тех местах, где я произвёл замену, но учитывая что это один из первых моих коммитов в библиотеку, то полагаю, что тогда я не задумывался об обратной совместимости и просто хотел унифицировать эту историю, даже если бы это привело к некоторому кол-ву багов

<hr />

Провёл селф-ревью пулл-реквеста и оставил вызовы `isNonNullable` только там, где они действительно нужны

2022-06-23 06:36 UTC, zhzz approved these changes

2022-06-23 07:58 UTC, zhzz requested changes

2022-06-23 07:58 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> -    return !children || !childrenToArray(children).filter(isExist).length;
Тут и в Menu `isExist` остался неиспользуемым.

2022-06-24 09:01 UTC, khlutkova commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> -    return !children || !childrenToArray(children).filter(isExist).length;
Вроде `isExist` удалена из Menu/InternalMenu

2022-06-24 09:02 UTC, khlutkova approved these changes

2022-06-24 09:13 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> -    return !children || !childrenToArray(children).filter(isExist).length;
Как-то я просмотрел

2022-06-24 10:16 UTC, zhzz approved these changes

2022-06-24 10:18 UTC, merged