feat(Modal): add adaptive version of modal component
skbkontur/retail-ui pull request #2682
Opened 2021-11-30 12:50 UTC by StathamJason

2021-12-10 04:06 UTC, zhzz commented on packages/react-ui/components/Modal/ModalBody.tsx
> +            </div>
Я бы попробовал рисовать этот крестик где-то в одном месте для мобилки и десктопа, чтобы не дублировать.

2021-12-21 06:31 UTC, zhzz requested changes

2021-12-21 06:31 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.tsx
> +                                  [styles.mobileCloseWrapper(this.theme)]: isMobile,
Этот класс никогда не применится, потому что `isMobile` внутри `!isMobile`.

2021-12-21 06:31 UTC, zhzz commented on packages/react-ui/components/Sticky/Sticky.tsx
> +
А зачем это понадобилось?

2021-12-21 06:41 UTC, zhzz commented on packages/react-ui/components/Modal/ModalBody.tsx
> +            </div>
Рисовать крестик внутри Body ненадежный вариант, потому что Body в общем случае необязательный элемент. Он создает отступы по гайдам, но люди могут использовать свои обертки вместо него. В этом случае крестик пропадет.

Если в мобильной версии без хедера нельзя воспроизвести десктопную верстку с обтеканием контента вокруг крестика, тогда я бы предложил рисовать его прежним способом, но без обтекания, на отдельной строке, например. Чтобы он рисовался в любом случае, пока явным образом не отключен.

![image](https://user-images.githubusercontent.com/4607770/146883717-8ddaaf3e-265d-41d2-9b00-1de7ef22a1f4.png)

2021-12-21 08:07 UTC, StathamJason commented on packages/react-ui/components/Sticky/Sticky.tsx
> +
Если изменять рывками ширину окна (например переключать в сторибуке с телефона на планшет) то стики заголовок и футер могли не высчитать свою ширину правильно. Но по идее на устройствах изменение ширины происходит разово и это норм, поэтому уберу

2021-12-22 06:20 UTC, zhzz requested changes

2021-12-22 06:20 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.styles.ts
> +  mobileCloseWithoutHeaderWrapper(t: Theme) {
Больше не используется

2021-12-22 10:33 UTC, zhzz requested changes
Без хэдера крест наезжает.

![image](https://user-images.githubusercontent.com/4607770/147079072-37d11f02-64a0-445e-9785-355ab79dc84d.png)

2021-12-22 11:29 UTC, dzekh commented
> Без хэдера крест наезжает.
А давайте может непрозрачную подложку крестику сделаем просто? Так то редкий случай, когда текст или что-то в лайтбоксе будет вот так до края, как в примере. Даже если будет всегда будет возможность его поскроллить и увидеть.

2021-12-23 20:50 UTC, dzekh commented
Договорились сделать подложку под крестиком — круг с радиальным градиентом, чтоб не сливался с фоновым текстом: 
background: radial-gradient(50% 50% at 50% 50%, #FFFFFF 60%, rgba(255, 255, 255, 0) 100%);

Нужно предусмотреть чтоб #FFFFFF и rgba(255, 255, 255, 0) был не захардкожен и зависел от темы — при переключении на темную тему становился синхронным с цветом фона — bgDefault в переменных. Но не терял прозрачность при этом ;)

Выглядит как-то так:
![image](https://user-images.githubusercontent.com/26383080/147290251-2abfd16b-8625-4492-b787-f7f27f01ded6.png)

2021-12-24 05:46 UTC, zhzz requested changes

2021-12-24 05:46 UTC, zhzz commented on packages/react-ui/components/Modal/ModalClose.tsx
> +            [styles.mobileCloseWithoutHeader(theme)]: !modal.hasHeader && isMobile,
Кресту внутри себя вредно знать, где он находится. Это увеличивает связность кода. Лучше передавать ему класс снаружи.

2021-12-24 12:37 UTC, zhzz requested changes

2021-12-24 12:37 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.tsx
> +                                      : undefined
Два раза проверка isMobile

2021-12-27 10:03 UTC, zhzz commented on packages/react-ui/components/Modal/Modal.tsx
> +                                  }
Без веток было бы получше.

```suggestion
                                  className={cx({
                                    [styles.mobileCloseWithoutHeader()]: isMobile && !this.state.hasHeader,
                                  })}
```

2021-12-29 04:18 UTC, merged