Adaptive tooltip
skbkontur/retail-ui pull request #2688
Opened 2021-12-07 12:07 UTC by StathamJason

2021-12-22 07:03 UTC, zhzz requested changes

2021-12-22 07:03 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
>      }
Если нет слушателя, не нужно закрывать?

2021-12-22 07:03 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static mobileMediaQuery = '(max-width: 576px)';
Наверное, после отладки осталось.

2021-12-24 07:49 UTC, zhzz reviewed
Меню ТокенИнпута не закрывается по клику на темный фон.

2021-12-24 07:49 UTC, zhzz commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    }
Я потестил на андроиде и там ховеры вроде везде корректно эмулируются кликами, так что они будут работать и на мобилках. Не нужно их тотально менять.

Единственную вероятно связанную с этим проблему обнаружил в сторибуке валидаций, история switcher--required, обернутый в валидацию свитчер не переключается.

Тултипы валидаций в целом тоже работают. Разве что не очень дружелюбно автоматом открываются при мнгновенной валидации и валидации по сабмиту.

2021-12-24 09:51 UTC, StathamJason commented on packages/react-ui/components/Hint/Hint.tsx
> +  private getMobileClickHandler = () => (this.isMobileLayout && !this.props.manual ? this.open : undefined);
потому что если будет передан close handler,  то до `MobilePopup` дойдет onClose и по нажатию на тень ВСЕГДА будет закрываться выпадающее меню. Поэтому здесь проверка на мануальное управление, я сейчас просто переделаю ее немного

2021-12-24 09:53 UTC, StathamJason commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
>      }
Да, если не был передан onClose, то это значит ручной режим управления открытием/закрытием

2021-12-27 07:38 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
>      }
Получается скрытая логика, совсем не очевидно. Нужно, чтобы работало более явным образом.

Мы же в итоге все равно управляем показом попапа из того компонента, который его рендерит. И в нем же задается режим (ручной/неручной). Попап может всегда обрабатывать запросы на закрытие одинаково и передавать их наружу, где родительский компонент уже будет их игнорить или нет в зависимости от режима.

А `isOpened` в MobilePopup не нужен, об этом ниже отдельно.

2021-12-27 07:41 UTC, zhzz requested changes

2021-12-27 07:41 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
> +      });
`isOpened` в целом не нужен. Можно считать, что MobilePopup всегда открыт, когда отренедерен. А для анимации использовать `<Transition />` как в десктопном попапе.

2021-12-28 08:23 UTC, StathamJason commented
Для ТокенИнпута считаю, что надо дизайн мобильный обсудить. Сейчас там на телефонах не удаляются токены и меню не закрывается просто так. Отключил мобильную версию пока что

2021-12-29 05:20 UTC, zhzz requested changes
В тултипе сломалось закрытие мобильного попапа (триггер click). 

И в мобильном попапе пока еще не совсем налажена логика с закрытием. В десктопном попапе onClose вызывается только когда попап реально закрывается. В мобильном получается есть еще отдельный "запрос на закрытие" (нажатие на фон или крестик), который не обязательно приведет к закрытию, потому что этим в итоге рулит родительский компонент (может быть ручной режим и тд). Дергать onClose в мобильном нужно по той же логике, что и в десктопном. Плюс, похоже нужен отдельный проп на запрос закрытия, например `onCloseRequest`, как в тултипе.

2021-12-29 05:20 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
> +        <Transition mountOnEnter in={true} appear={true} timeout={0}>
Анимация на закрытие пропала. И еще всю анимацию нужно отключать в тестовом окружении.

2021-12-30 09:14 UTC, zhzz requested changes

2021-12-30 09:14 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
> +                  [jsStyles.visibilityHidden()]: state === 'exited',
Нужен unmountOnExit, тогда это не понадобится. И HideBodyVerticalScroll тоже всегда можно будет рисовать.

2021-12-30 09:14 UTC, zhzz commented on packages/react-ui/internal/MobilePopup/MobilePopup.tsx
> +      console.count('CLOSE ДЕРНУТ');
```suggestion
```

2021-12-30 09:14 UTC, zhzz commented on packages/react-ui/internal/PopupMenu/PopupMenu.tsx
> +                mobileOnCloseRequest={this.isMobileLayout ? this.hideMenu : undefined}
Здесь нет смысла isMobileLayout проверять.

2021-12-30 13:13 UTC, zhzz approved these changes

2022-01-10 05:51 UTC, merged