Adaptive sidepage
skbkontur/retail-ui pull request #2695
Opened 2021-12-14 10:09 UTC by StathamJason

2021-12-22 06:38 UTC, zhzz requested changes

2021-12-22 06:38 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.tsx
> +      </RenderContainer>
Здесь потерялся CommonWrapper. Показательный пример, почему дублирование - зло. Что-нибудь да забудешь.

Можно попробовать избавиться от дублирования. Объединить в один рендер, повыключав лишнее, либо вынести общие пропы/компоненты куда-то.

2021-12-22 06:38 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePageFooter.tsx
> +
Зачем хранить в поле? А если проп поменяется?

2021-12-22 06:38 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePageHeader.tsx
> +    }
Тоже случай с изменением пропа не предусмотрен.

2021-12-22 10:51 UTC, zhzz requested changes
В истории "SidePage with variable content" после нескольких кликов по "Add sidePageText" начинает ехать верстка при скролле:

![image](https://user-images.githubusercontent.com/4607770/147081172-285f0f79-7773-42b3-8205-460c307097da.png)

2021-12-23 09:49 UTC, StathamJason commented
> В истории "SidePage with variable content" после нескольких кликов по "Add sidePageText" начинает ехать верстка при скролле:

Да, потому что там у блока высота задана фиксированная 600px и его флекс облегает. А все, что ниже - это оверфлоу этого блока

2021-12-24 06:51 UTC, zhzz requested changes

2021-12-24 06:51 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePageFooter.tsx
> +  public checkSticky() {
Лучше сделать геттер `isSticky` или назвать метод `getSticky`. От `checkSticky` не ожидаешь что он что-то возвращает.

2021-12-24 12:39 UTC, zhzz approved these changes

2021-12-29 13:50 UTC, merged