fix(ScrollContainer): consider scaling cases in browsers
skbkontur/retail-ui pull request #2705
Opened 2021-12-20 05:22 UTC by lossir

В Хроме при масштабировании позиция скролла может стать дробной.
`floor()` - для обычного (1:1) и уменьшенного масштаба
`round()` - для увеличенного масштаба

Fix #2704

2021-12-21 08:38 UTC, zhzz requested changes

2021-12-21 08:38 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Из экспериментов похоже, что позиция может отличаться в пределах единицы включительно в любую сторону.

Решение не сработает, если позиция будет меньше `latestScrollPos` более чем на `0.5`. Либо будет отличаться ровно на `1`.

2021-12-21 08:43 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Нужны подробности для воспроизведения. При каких условиях ты добился таких значений?

2021-12-21 08:52 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Думаю, будет достаточно заменить `round` на `ceil`

2021-12-21 10:11 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Прошелся по всем предустановленным в хроме значениям зума на истории `scrollcontainer--with-large-content-height`. Логировал значения в нижней позиции, видел там -1 и +0.6 (67% и 300%) от границы контейнера. Предположил возможность всех остальных из диапазона `[-1, +1]`.

 `ceil` и `floor` не помогут при отличии ровно на 1px.

2021-12-21 11:56 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Понял в чём дело. Ты проверяешь в Хроме на Маке. Там действительно значение другие.
На Винде проблема с `round` всплыла только на 150%. При переходе на `ceil` везде стало норм.

2021-12-23 04:23 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
Текущее решение также срабатывает на значениях от +1 до +2.

2021-12-24 04:21 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
При горизонтальном скроле и масштабе 67% в хроме я встретил значение ровно +1. Так что нужно его включить.

`latestScrollPos` скорее должен называться `maxScrollPos`. latest больше указывает на время либо очередь. 

А масштаб в браузерах чаще зовется zoom чем scaling. Так будет понятнее о чем речь.

2021-12-24 06:02 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
На маке или на винде?

2021-12-24 06:04 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (floorPos === latestScrollPos || roundPos === latestScrollPos) {
На винде

2022-02-03 11:49 UTC, zhzz approved these changes

2022-02-03 11:49 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    if (maxScrollPos === floorPos || maxScrollPos === floorPos + 1 || maxScrollPos + 1 === floorPos) {
В таком виде было бы чуть выразительнее `Math.abs(maxScrollPos - this.inner[pos]) <= 1`.

2022-02-04 11:22 UTC, merged