refactor: reduce code duplication for component detection
skbkontur/retail-ui pull request #2712
Opened 2022-01-13 05:08 UTC by JackUait

Отрефакторил определение компонентов:
1. Создал утилиту `isComponent` (используется в контролах `Button` и `MenuItem`).
2. Отрефакторил функцию `isReactUIInstance` из класса `ModalStack`, теперь она принимает на вход имя компонента и возвращает функцию.

2022-02-02 06:27 UTC, zhzz requested changes

2022-02-02 06:27 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +  isComponentName(name);
А зачем эта проверка? Кажется лишней. Функция проверяет наличие нашей метки, но ограничений на формат метки нигде не накладывалось по идее. Вводит в заблуждение.

2022-02-02 06:39 UTC, JackUait commented on packages/react-ui/lib/utils.ts
> +  isComponentName(name);
Я вижу эту функцию просто как дополнительную проверку, чтобы удостовериться что с переданным названием компонента всё ок.

Насчёт формата метки: мы же в `forwardRefAndName` делаем `displayName` и `__KONTUR_REACT_UI__` равным названию компонента, а названия компонентов должны начинаться с заглавной буквы. Отсюда и проверка.

В принципе можно обойтись и без неё, много не потеряем. Удаляем?

2022-02-02 08:52 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +  isComponentName(name);
Удаляем. Если еще назвать функцию `isReactUIComponent`, например, то будет совсем хорошо.

2022-02-02 08:58 UTC, JackUait commented on packages/react-ui/lib/utils.ts
> +  isComponentName(name);
Готово. Удалил функцию-хелпер и переименовал основную функцию.

2022-02-02 09:00 UTC, JackUait commented
Смёржил актуальный мастер.

2022-02-02 10:58 UTC, zhzz submitted a review, later dismissed

2022-02-02 11:18 UTC, zhzz commented
`yarn workspace @skbkontur/react-ui lint:tsc` не проходит

2022-02-02 14:31 UTC, JackUait commented
Пришлось частично отказаться от типизации (только для `MenuItem`).
Компилятор по какой-то причине сравнивает типы пропов из `MenuHeader` и `MenuItem` и обнаруживает, что они не совпадают. Из-за чего и появляется ошибка. Выглядит как баг на уровне `TypeScript`'а.

Напомни, мы можем как-то обновить версию `TypeScript` для компилятора? Или это происходит не по причине разнящихся версий? Не могу вспомнить в своей практике такого, чтобы `IDE` и компилятор по-разному воспринимали `TypeScript`-типы.

2022-02-03 07:32 UTC, zhzz approved these changes

2022-02-03 07:33 UTC, merged

2022-02-03 07:40 UTC, zhzz commented
Обновить можно. В next уже обновили. Лучше еще настроить IDE на использование версии из репозитория (если еще не настроено).