chore(packages): add testing libraries and storybook addon
skbkontur/retail-ui pull request #2721
Opened 2022-01-17 09:00 UTC by JackUait

Добавил библиотеки для тестирования: [react-testing-library](https://github.com/testing-library/react-testing-library) и [user-event](https://github.com/testing-library/user-event)
И аддон для тестирования `accessibility` для `Storybook`: [@storybook/addon-a11y](https://storybook.js.org/addons/@storybook/addon-a11y)

2022-01-18 05:16 UTC, zhzz requested changes

2022-01-18 05:16 UTC, zhzz commented on packages/react-ui/package.json
> +    "@testing-library/user-event": "14.0.0-beta",
Версия некорректная, не устанавливается, просит указать конкретную.

2022-01-18 05:16 UTC, zhzz commented on packages/react-ui/.storybook/main.ts
> +    '@storybook/addon-a11y',
Похоже, что с нашей версией сторибука [не работает](https://github.com/storybookjs/storybook/issues/16455), можно попробовать обновить.

2022-01-18 08:34 UTC, JackUait commented on packages/react-ui/package.json
> +    "@testing-library/user-event": "14.0.0-beta",
Поменял на 14.0.0-beta.8.

2022-01-18 08:45 UTC, JackUait commented on packages/react-ui/.storybook/main.ts
> +    '@storybook/addon-a11y',
Обновил `storybook` и связанные зависимости, проблема ушла.

2022-01-18 09:10 UTC, zhzz commented on packages/react-ui/.storybook/main.ts
> +    '@storybook/addon-a11y',
Но, похоже что [криви не работает с 6.4](https://github.com/wKich/creevey/issues/195). Выходит, пока не обновиться и a11y не затащить.

2022-01-18 10:00 UTC, JackUait commented on packages/react-ui/.storybook/main.ts
> +    '@storybook/addon-a11y',
Даунгрейднул `storybook`, связанные зависимости и `a11y`. Последний заработал)

2022-01-18 13:16 UTC, JackUait commented
Добавил вспомогательную библиотеку: [jest-dom](https://github.com/testing-library/jest-dom).

Пытался настроить плагины для `eslint`: [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom) и [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library), но не похоже, что проект понимает их. Есть предположения почему это может проихсодить?

2022-01-19 04:36 UTC, zhzz commented
> Пытался настроить плагины для `eslint`: [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom) и [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library), но не похоже, что проект понимает их. Есть предположения почему это может проихсодить?

Добавлял их в `.eslintrc`?

2022-01-19 04:37 UTC, zhzz approved these changes

2022-01-19 04:37 UTC, merged

2022-01-19 06:28 UTC, JackUait commented
Да, в тот который относится к `react-ui`, не в общий. Причём судя по правилу `import/no-default-export` этот файл всё же работает. Странно. Есть предположение, что в локальном конфиге нельзя добавлять новые зависимости, а только управлять зависимостями из общего конфига, но ещё не проверял его.