MenuItem in any level
skbkontur/retail-ui pull request #2749
Opened 2022-01-28 07:00 UTC by khlutkova

2022-03-02 00:10 UTC, JackUait requested changes

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +      index = items.findIndex((x: any) => itemToValue(x) === itemToValue(value));
Давай вынесем эту логику в отдельную функцию, чтобы не мутировать `index`.

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  };
Если нам нужен доступ к `menuItems` в других компонентах, почему не вынести `menuItems` в контекст?

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  public highlightItem(key: string) {
Нужно переиспользовать тип из `MenuItemType`.

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  private select(key: string, shouldHandleHref: boolean, event: React.SyntheticEvent<HTMLElement>): boolean {
Нужно переиспользовать тип из `MenuItemType`.

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  private addMenuItem = (key: string, item: MenuItem) => {
Нужно переиспользовать тип из `MenuItemType`.

2022-03-02 00:10 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  private deleteMenuItem = (key: string) => {
Нужно переиспользовать тип из `MenuItemType`.

2022-03-02 09:07 UTC, JackUait commented
Нужно удалить лишние комментарии.

2022-03-14 11:57 UTC, khlutkova commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  };
Про идентичность согласна.
Но на будущее есть задача про унификацию меню-подобных компонентов, в рамках которой и хотела избавиться от копипасты.
Подумаю, что и как можно сделать на текущем этапе.

2022-03-23 10:38 UTC, khlutkova commented on packages/react-ui/internal/InternalMenu/__tests__/InternalMenu-test.tsx
> +  // });
Выпилила тест совсем)
Раньше через реф определялся активный элемент меню, чтобы до него можно было скроллить. Теперь же DomNode активного элемента определяется непосредственно перед скроллом в scrollToSelected

2022-06-23 06:15 UTC, closed without merging