Типы в defaultProps
skbkontur/retail-ui pull request #2760
Opened 2022-02-07 04:58 UTC by HelenaIsh

fix [IF-284](https://yt.skbkontur.ru/issue/IF-284)

2022-02-09 09:39 UTC, JackUait requested changes

2022-02-09 09:39 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
>      menuMaxHeight: 300,
Не похоже, что это полностью решает проблему, так как  например `menuMaxHeight` может быть как `string`, так и `number`. А в `defaultProps` проп `menuMaxHeight` может быть только `number`. Нужно решение, которое оттипизирует все пропы в `defaultProps`.

Также `InputSize` это не тип пропа `small`. Тип пропа `small` это `AutocompleteProps["size"]`, если тип пропа `size` поменяется в `AutocompleteProps`, его придётся менять также и в `defaultProps`.

2022-02-09 09:39 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
>      menuMaxHeight: 300,
Предлагаю такое решение:
```tsx
// Снаружи компонента
const defaultPropsInstance = {
  renderItem,
  size: 'small',
  disablePortal: false,
  hasShadow: true,
  menuMaxHeight: 300,
  menuAlign: 'left',
  preventWindowScroll: true,
};
type DefaultProps = Pick<AutocompleteProps, keyof typeof defaultPropsInstance>;
const defaultProps: DefaultProps = defaultPropsInstance as DefaultProps;

// Внутри компонента
public static defaultProps = defaultProps;
```

Так как мы будем переиспользовать эту логику, стоит вынести её в отдельную функцию:
```tsx
// utils/getDefaultProps.ts
export const getDefaultProps = <T>(props: T) => {
  return props as Pick<T, keyof typeof props>;
};

// Снаружи компонента
const defaultPropsInstance = {
  renderItem,
  size: 'small',
  disablePortal: false,
  hasShadow: true,
  menuMaxHeight: 300,
  menuAlign: 'left',
  preventWindowScroll: true,
};
const defaultProps = getDefaultProps<AutocompleteProps>(defaultPropsInstance as AutocompleteProps);

// Внутри компонента
public static defaultProps = defaultProps;
```

2022-02-09 09:39 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
>      menuMaxHeight: 300,
С таким решением нам не придётся беспокоиться о том, что могут вылезти подобные ошибки с типизацией, с другой стороны мы явно приводим тип пропов, что тоже не есть гуд, но как временное решение сгодится, так как в функциональных компонентах деструктурируемые пропы типизируются автоматически.

2022-02-09 09:47 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
>      menuMaxHeight: 300,
Эти изменения нужно будет внести везде, где используются `defaultProps`.

2022-02-11 14:36 UTC, JackUait commented
В компонентах `Tab` и `ZIndex` нет `getDefaultProps`.

Давай ещё переименуем `getDefaultProps` в `getDefaultPropsTypes` и добавим описание этой функции, чтобы было понятно, что это костыль чисто для классовых компонентов.

2022-02-12 21:10 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
Здесь закралась потенциальная проблема. Дело в том, что конструкция `as` конвертирует типы, приводя к более или менее конкретным, но всё ещё сопоставимым.

[Type Assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions)
> TypeScript only allows type assertions which convert to a more specific or less specific version of a type. This rule prevents “impossible” coercions.

Т.е. здесь, в `defaultPropsInstance`, можно всем свойствам задать любые строковые значения, и Тайпскрипт не будет ругаться.

Собрал пример с такими проблемами - [typescriptlang.org/play](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAYwgOwM7wObBgEWAMwEMBXAGxgAUoIxU4BeOfY5BGASxQB4AVAPgAUYarQBccHgEo4AbwBQcOFGzEoyOMJp1CdCuwQBrXgBo4B4AE8I+ODAthg1jSNR8A3HIC+cuaEiw4dmQYYCgiBGA4ACFiGBgUKi1ZBVt7YAB+cQByAHcgkKgsuAAfOCzUYgBbStCsj0VCKChxZCqAI1CAbQBdYxSINvEZHQATFvbQzz7FVsrxyo6oLx8AehW4QCIQADpALhAtuAADHQO4HcA+EEBeEEAmEEBWEEABEEAhEEAOEDvAYRAbh7hnwH4QQGkQU0AsiDPOCAdhALoAGEEA4iA3C5PQDyIHBvnczoBREDOgBYQOEPORINDwEYEEjkRK0ACSeMIrEijHkijsDmy7GoGCy0zgjWacE6AEZTFkAExZXr9QayKYpNZwQCoIIBBEEA3CBPOB3cEg86AHhAYc9kVdwQ9ADIgcBlD2RO1ecFhgDYQG6mB5nL5nQDMIOjwYdjnBAIwgr3RHyVrwdur1MrhEvWs2y6CgQRZXg8uPQcAJRDIlBcDDgWFwhOTJNQXBicQSLkEiaJKa05PQlIi7Lo+fiyBzkg8cklgFwQO1XC6vY2K9XfS6al0-X5wK7ms53DW+cDQeBx+D04DiRdOEvZlxbRdprLsDDQOrT-xzlDxjnLtKrrPEjcctM8vmC7oePyzxAn+ADc8OS9J69aLYDGmMieB4QA).

2022-02-12 21:13 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +  public static defaultProps = defaultProps;
Думаю, что эту проблему надо решать по другому.

По типам Реакта для [`ComponentClass`](https://github.com/DefinitelyTyped/DefinitelyTyped/blame/master/types/react/v16/index.d.ts#L589) и [`FunctionComponent`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v16/index.d.ts#L546) видно, что в `defaultProps` предполагается тип `Partial<Props>`. Но в Классовом компоненте, в поле `defaultProps`, по сути можно написать что угодно.
Предлагаю просто добавить `Partial<...Props>` для `defaultProps`. И больше ничего не делать.


Сделал небольшой пример для наглядности - [typescriptlang.org/play](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirkFwQQBhBAJEEA4QOQfhBABEED4QdwaRBywAHYwkUTOiRwACjjABnOAG9ycOEJQgkALgIQhSfHAA+BGAHcIZcgF9KaffPgAxAK5CMwfQGFckAyK6yOgwAHRuHjBeQr7g+kgiADyyEAoAfHAAvHAAFACUWRlCrgA2JRQRnj5+8SKhACZIEqUwKQpZyqpwNHCAJCCAwiCAvCCAXCCAYiAs3IMMgNwggDIgg3yAnCBww9yAPCDsk4CsIIOAQiBwgIIgnAyA7CD9HNyALCC7gPIggMwgLIBMIAxb+7ss-HAAtDIosMAoErJOTyNJdDRaXQARgATABmAA0tgo5DQJRQ8kUsX8CXgSAAHqIhPVFMEMKFsbUYMDUqDOmowK4AEYlYBoOBOFBRdmNZolVogjoqNRqHqAPBBAIwgfEA4iALZarDbbPZwQYsYYMYYqrZwd7sFgnFicfqvUJwQBIIHBALIgu3WcEeBxuHB4EumWzWDC6aghOjgsMRXRsFDs1FogFIQbi3C6HfrvOCAAhAthq3hrAGwg2q4W0um2mDDuL320ptOoYazgEv6l1ev3+gJp6XIMAAnmApAARJooFpteQAFWbUmyZLClICMG86MxiSHFJqo+7iSbLYgmDgI9xaTSAG18LzO-zu-gALoUAmQWBwBxCJxwdt8gW03S3vf3hR9ltC8GaH1+pGByg9L5APjQBUEEAChBgLoQAMEGA75AMoU9oHgNEMSxWdcWcYB8TgAkiRJRBiGHNCkm7DJhW6WhAHwQHgDiLXV9UNY1SwOR5uEWGiWLtI1ZX6QA5EC6RkWTZDkYC5ITdy7EFdGkP4olrEiPxFdQv2heEkTUP87CAA).

2022-02-13 11:41 UTC, lossir commented
## По поводу smoke тестов (`Lint/Test`)

### Кратко
Вот "фикс" https://github.com/skbkontur/retail-ui/pull/2799. Надо будет просто подлить мастер потом.

### Подробно
Там возникает ошибка в типах `Select`'а.
```red
ERROR in src/App.tsx:125:7
TS2589: Type instantiation is excessively deep and possibly infinite.
    123 |       </RadioGroup>
    124 |       <ScrollContainer>scroll container</ScrollContainer>
  > 125 |       <Select onValueChange={() => ({})} />
        |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ERROR in src/App.tsx:125:30
TS2589: Type instantiation is excessively deep and possibly infinite.
    123 |       </RadioGroup>
    124 |       <ScrollContainer>scroll container</ScrollContainer>
  > 125 |       <Select onValueChange={() => ({})} />
        |                              ^^^^^^^^^^
```

Она также появляется при использовании `Partial<Props>`, о котором я говорил выше https://github.com/skbkontur/retail-ui/pull/2760#discussion_r805205086.
А возникает она, когда TypeScript решает, что типы становятся слишком сложными для вычисления.

> https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
> > It happens when TS decides that types become too complex to compute (ie).

Способ решения - исследовать каждый случай самостоятельно... **Но нам повезло =)**

У нас в смок тестах устарел TS - `~3.7.4`. А в версии `3.9` заметно повысили производительность.
Например, скорость компиляции `material-ui` сократилась на **40%**

> [TypeScript 3.9 > Speed Improvements](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#speed-improvements)
> > In total, we believe we’ve achieved around a 40% reduction in material-ui’s compile time!

Я проверил, и, действительно, после обновления до `3.9` и выше ошибка пропадает. Пока можно не вникать что же там такого сложно было в вычислениях =)

2022-02-14 02:11 UTC, JackUait commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
> Здесь закралась потенциальная проблема. Дело в том, что конструкция `as` конвертирует типы, приводя к более или менее конкретным, но всё ещё сопоставимым.

Ты неправильно интерпретировал написанное в доке. В доке написано, что конструкция `as` можно выполнить приведение только к более или же менее точному типу. То есть мы можем привести тип `string | number` к `string`, но при этом не можем привести тип `number` к `string`.

В примере ниже то, о чём говорится в доке:
```ts
const foo: string | number = 4 // Знаем, что переменная никогда не поменяет своё значение.

const takesOnlyNumber = (value: number) => {
...
}

/*
* Так как мы знаем, что значение переменной никогда не изменится 
* мы сокращаем её тип и TypeScript позволяет нам это сделать.
*/
takesOnlyNumber(foo as number)
```
  

> Т.е. здесь, в `defaultPropsInstance`, можно всем свойствам задать любые строковые значения, и Тайпскрипт не будет ругаться.

`TypeScript` не будет ругаться, так как мы не типизируем `defaultPropsInstance`. Для `defaultPropsInstance` `TypeScript` наследует типы, также, как он это делает и для `defaultProps` внутри компонента. То есть мы полностью мимикрируем поведение `TypeScript`'а в этом случае.

Для нас главное что пользователи и мы (внутри компонента) получаем типизированные пропы.

2022-02-14 02:27 UTC, JackUait commented on packages/react-ui/components/Button/Button.tsx
> +  public static defaultProps = defaultProps;
В своём примере ты используешь `.defaultProps` для задания значений по умолчанию для функционального компонента, но такой способ задания значений по умолчанию [deprecated](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components). Значения по умолчанию для функциональных компонентов задаются через механизм аргументов по умолчанию, так как он работать быстрее, чем `.defaultProps` и удобнее. В [треде](https://github.com/reactjs/rfcs/pull/107) можно почитать о дальнейшей судьбе различных задиприкейчиных механизмов, в том числе о `.defaultProps` в функциональных компонентах.

И тут мы подбираемся к тому, почему я не предложил идти путём `Partial<Props>`: механизм задания значений по умолчанию в функциональных компонентах работает значительно лучше и внутри компонента мы получаем конкретный тип `Props`, а не `Partial<Props>`.

Вот пример из компонента `MenuHeader`:
<img width="382" alt="Снимок экрана 2022-02-14 в 05 26 01" src="https://user-images.githubusercontent.com/48599460/153789606-0ebcc4ec-d91a-4de6-ad27-95777093363e.png">
При `MenuHeaderProps` тип `children` это `children: ReactNode`.


Если мы поменяем `MenuHeaderProps` на `Partial<MenuHeaderProps>`:
<img width="376" alt="Снимок экрана 2022-02-14 в 05 24 41" src="https://user-images.githubusercontent.com/48599460/153789417-a3edea2d-b7bc-490d-8b42-dae634511bc7.png">
Тип `children` соответственно изменится на `children?: ReactNode`.

2022-02-14 02:50 UTC, JackUait commented
Хмм, странно, `TypeScript` благодаря своей статической натуре может "поглощать" очень глубокие типы. В отличие от например `Swift`, у которого типизация не статическая. Скорее всего где-то в типах `Select` закралась рекурсия, которую `TypeScript` не воспринимает как ошибку.

2022-02-14 10:44 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
Хм.. всё-таки думаю, что я правильно интерпретировал доку. Просто ты проводишь пример когда это будет полезно/допустимо, а я привёл пример потенциальной проблемы.

Для нас `defaultPropsInstance` это тоже "внутри компонент", и не стоит самим себе мину подкладывать.

2022-02-14 10:44 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +  public static defaultProps = defaultProps;
Я не предлагал делать так =)
Тип пропов в FC должен быть "как есть". Как это сделано в `MenuHeaderProps`.

Но дефолтное значение аргумента, сейчас не может полностью заменить дефолтное значение из `.defaultProps`. Например, в `CurrencyLabel` так сделать будет не просто, т.к. возникнет проблема с кастомным `propTypes` для `fractionDigits`. 

> [default-prop-values](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values).
> > The propTypes typechecking happens after defaultProps are resolved, so typechecking will also apply to the defaultProps.

При отказе от `.defaultProps`, `propTypes` не будет содержать значение по умолчанию из аргументов.
И в этом случае можно пока оставить `.defaultProps`. И также использовать `Partial<Props>`.

```tsx
const defaultProps: Partial<CurrencyLabelProps> = {
  fractionDigits: 2,
};
```

2022-02-14 20:47 UTC, JackUait commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
Я всё ещё не до конца пойму причём тут приведение типов, если в `defaultPropsInstance` мы не приводим типы, а наследуем их. Мы приводим типы только в `defaultProps`.

2022-02-14 20:47 UTC, JackUait commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
Насчёт приведённых тобой строк из доки:
> TypeScript only allows type assertions which convert to a _more specific_ or _less specific_ version of a type. This rule prevents “impossible” coercions.

Можно перевести как:
> TypeScript позволяет совершать приведение типов только к более или же менее специфичной версии типа. Это позволяет предотвращать "невозможные" приведения типов.

То есть этот механизм защищает от выстрела в ногу и никак не влияет на тип, который мы получим на выходе.

2022-02-15 09:27 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +  public static defaultProps = defaultProps;
Согласен, вариант с `FRACTION_DIGITS_DEFAULT` выглядит красиво =)
Давай так и сделаем.

2022-02-15 09:27 UTC, lossir commented on packages/react-ui/components/Button/Button.tsx
> +const defaultProps = getDefaultProps<ButtonProps>(defaultPropsInstance as ButtonProps);
Да, непосредственно в `defaultPropsInstance` нет никакого приведения у типу. Здесь мы и стреляем себе в ногу.
Дефолтные значения меняются крайне редко, но меняются. Поэтому лучше бы их типизировать. Плюсом будет автокомплит при редактировании.

Конструкция `defaultPropsInstance as ButtonProps` не пропустит только "невозможные" приведения типов, но пропустит "возможные". И в примере выше я привёл такие типы, которые будут считаться допустимыми, но в коде могут всё запросто развалить.

2022-02-15 10:31 UTC, JackUait commented
@HelenaIsh Обсудили эту проблему с Максимом @lossir голосом, решили остановиться на `Partial<Props>` внутри компонента.
```tsx
class SomeComponent {
	public static defaultProps: Partial<Props> = {
		...
	}
}
```

Недопонимание произошло по причине того, что я думал, что `React` мутирует типы пропов, чтобы они совпадали с `defaultProps`.

Как я это понимал:
1. В компонент передаются `Props`;
2. Мы задаём `defaultProps` тип `Partial<Props>`;
3. `React` работает с `Partial<Props>`, вместо `Props` (то как это работает в функциональных компонентах).

Как это работает на самом деле:
1. В компонент передаются `Props`;
2. Мы задаём `defaultProps` тип `Partial<Props`;
3. Тип `defaultProps` распространяется только на `defaultProps` и `React` не подхватывает его для типизации `Props` переданных в компонент;
4. `React` работает с `Props`.

2022-02-16 11:37 UTC, JackUait commented
Столкнулись с проблемой, что `Partial<Props>` не работает с `createPropsGetter`. 
Решили так:
```tsx
// Снаружи компонента.

// Разделяем пропы на пропы у которых есть значение по умолчанию и все остальные.
type DefaultProps = {
  width: number | string;
  maxHeight: number | string;
  hasShadow: boolean;
  ...
};

// Пользователи будут получать Partial пропы.
type MenuProps = {
  children?: React.ReactNode;
  ...
} & Partial<DefaultProps>;

// Мы будем пользоваться полноценными пропами.
type MenuComponentProps = MenuProps & DefaultProps;

// Внутри компонента.
class Menu extends React.Component<MenuComponentProps> {
  ...
  public static defaultProps: DefaultProps = {
    ...
  }
  ...
}
```

Пока что не нашёл изъянов у этого решения.
Это решение покрывает все проблемы, о которых мы говорили выше, а также:
1. Позволяет избавиться от `createPropsGetter` (что предлагаю сделать прямо в этом `PR`);
2. Мы получаем более строгую типизацию в том плане, что мы наверняка знаем какие типы будет иметь `defaultProps`

2022-02-17 20:49 UTC, JackUait commented
Вот такие вот конструкции выглядят очень устращающе:
```tsx
// ComponentTable.tsx

interface DefaultProps<C, P, S> {
  presetProps: DefaultizeProps<C, P>;
  presetState: Partial<S>;
}

public static defaultProps: DefaultProps<any, any, any> = {
  presetProps: {},
  presetState: {},
};
```

Давай там, где используются дженерики добавим значений по умолчанию для `DefaultProps`:
```tsx
// ComponentTable.tsx

interface DefaultProps<C = any, P = any, S = any> {
  presetProps: DefaultizeProps<C, P>;
  presetState: Partial<S>;
}

public static defaultProps: DefaultProps = {
  presetProps: {},
  presetState: {},
};
```

Таким образом мы во всех компонентах приведём поглощение типа `DefaultProps` к общему виду.

2022-02-17 20:52 UTC, JackUait commented
В `InputLikeText` нет типа `DefaultProps`.

2022-02-17 21:06 UTC, JackUait commented
У нас получилась какое-то месиво из ключевых слов `type` и `interface`. Давай в тех местах, где ты внесла правки приведём всё к единому стилю. Так как `type` это по сути продвинутый `interface`, то давай использовать его.

2022-02-17 21:32 UTC, JackUait commented
Нам не нужно дублировать типы из `ComponentNameProps` в `DefaultProps`.

План такой:
1. Удаляем пропы с дефолтными значениями из `ComponentNameProps`;
2. Закидываем их в `DefaultProps` и удаляем у этих пропов вопросики;
3. Создаём два типа: пользовательский и внутренний, в пользовательском должны быть `Partial<Props>`, во внутреннем `Props`.

То о чём я говорю на примере компонента `Button`:
```tsx
// Изначальное состояние
export type ButtonProps = {
  corners?: number;
  disabled?: boolean;
  ...
  size?: ButtonSize;
  type?: ButtonType;
  use?: ButtonUse;
} & CommonProps;
```

```tsx
// С типом DefaultProps
// Пользовательский тип ButtonProps
export type ButtonProps = {
  corners?: number;
  disabled?: boolean;
  ...
} & CommonProps & Partial<DefaultProps>;

type DefaultProps = {
  use: ButtonUse;
  size: ButtonSize;
  type: ButtonType;
}

// Внутренний тип ButtonComponentProps
type ButtonComponentProps = ButtonProps & DefaultProps;

```

2022-02-21 22:30 UTC, JackUait approved these changes

2022-02-22 07:38 UTC, JackUait commented
Создал [пулл-реквест](https://git.skbkontur.ru/ui/ui-parking/-/merge_requests/180) в парковку удаляющий `createPropsGetter` оттуда.

2022-05-19 13:05 UTC, zhzz requested changes
Я вижу, что это решение одновременно двух проблем, `IF-284` и #2553.

Оно работает, но слишком радикально. Разделение интерфейса пропов на много частей уменьшает читаемость в данном случае. Придется в голове собирать все по кусочкам. Плюс, поддерживать код и писать новый по этим правилам будет непросто. Уже сейчас в `ValidationContainer` объявление пропа `disableSmoothScroll` дублируется в двух местах. Нет шансов что в этом всегда будет порядок.

Решаемые проблемы того не стоят. Они все исходят из особенностей `defaultProps`, от использования которых мы сможем вовсе [отказаться](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/default_props/#you-may-not-need-defaultprops) с переходом на функциональные компоненты. Предлагаемые изменения тогда станут не нужны.

Я бы обе проблемы решил просто в лоб, локально. Для #2553 cделал бы все пропы опциональными, порешав проблемы с линтом дополнительными проверками в нашем коде. А для `IF-284` указал бы везде корректный тип для `defaultProps` руками. 

От `createPropsGetter` можно отказаться.

2022-05-19 22:15 UTC, JackUait commented
> Для #2553 cделал бы все пропы опциональными

С этим не соглашусь по нескольким причинам (которые мы даже кажется уже обсуждали):
1. _Сделать пропы опциональными - просто. Вернуть их в прежнее состояние, когда будет готов полноценный фикс - не просто_
	1. **С точки зрения разработки:** нужно будет сверять все места из пулл-реквеста, где поменялась обязательность пропов и добавились лишние проверки и ручками всё это возвращать в адекватное состояние. Плюс, из этого вытекает ещё одна проблема - придётся выполнить тройную работу: сначала сделать временное решение, удалить временное решение, запилить полноценное решение
	2. **С точки зрения пользователей:** чтобы вернуть обязательные пропы придётся выпускать мажорную версию библиотеки, так как для пользователей, которые будут использовать компоненты с дефолтными значениями вместо дефолтов придётся вводить настоящие данные, что будет для них ломающим изменением
2. _Пользователям полезно видеть обязательные пропы. Нам полезно видеть, что пользователи видят обязательные пропы (пункт 2, подпункт 2)._ Не думаю, что много пользователей наизусть помнят `API` компонентов и какие пропы нужно передавать "чтобы работало", поэтому предполагаю, что многие завязываются именно на обязательных пропах, чтобы заставить компоненты работать 
	Если мы сделаем все пропы необязательными мы столкнёмся с:
		i. **Ухудшением `DX`** - пользователям придётся лезть в доку или смотреть на типы, чтобы понять что им ещё нужно передать "чтобы заработало" 
		ii. **"`HTML`-ностью"**. В `HTML` все "пропы" - необязательные. Я это вижу как образец плохого проектирования. Рассмотрим, что я имею ввиду на примере тега `<img />`: у этого тега на самом деле есть два обязательных атрибута - `src` и `alt`. Атрибут `src` необходим для отображения изображения для зрячих пользователей, атрибут `alt` необходим для отображения изображения при чтении документа скрин-ридерами, поисковыми работами и т.д. (с какой-то точки зрения атрибут `alt` даже более необходимый чем атрибут `src`). Что мы имеем на самом деле: на большинстве сайтов не прописаны `alt`-атрибуты картинкам (статистики у меня нет, но достаточно зайти даже на какой-нибудь Озон (кажется, что интернет-магазин идеальное место, чтобы прописывать `alt`-атрибуты картинкам, так как у тебя всегда есть необходимый текст), чтобы увидеть, что там в большинстве разделов сайта отсутствуют `alt`-атрибуты у изображений), такая же история будет и у нас: пользователи будут неправильно пользоваться компонентами, потому что им никто не запрещает это делать
3. _Грязный код._ Это изменение затруднит внесение других изменений: например, нам нужно добавить условие, что, если какой-то проп передан сделать то-то, теперь нам придётся выполнять эту логику внутри проверки на `undefined`, что в зависимости от типа данных либо почти не повлияет на читаемость кода, либо значительно затруднит его чтение

Я вижу два вероятных решения этой проблемы:
1. Решить задачу от начала и до конца, сев и просмотрев все компоненты на обязательность пропов (по опыту функциональных компонентов могу сказать, что это не всегда очевидно и порой приходится покопаться в коде, чтобы понять что проп на самом деле необязательный) - оперативно закроем задачу, потратим много человеко-часов на её закрытие
2. Решить эту задачу в рамках "функциональных компонентов" - крайне не оперативно закроем проблему, почти не потратим человеческих ресурсов, так как опять же по опыту могу сказать, что проблема решается "сама собой", по ходу рефактора

Я голосую за второй вариант, так как оперативно закрыть задачу у нас уже не получилось

2022-05-20 07:04 UTC, zhzz commented
> 1. Сделать пропы опциональными - просто. Вернуть их в прежнее состояние (...) - не просто.

Зачем их возвращать? У нас проблема с типом пропов, у которых есть дефолтные значения (#2553). Их нужно перманентно порешать, сделав по-настоящему опциональными.

> 2. Пользователям полезно видеть обязательные пропы.

Согласен. Со "всеми" пропами я погорячился. Нужно сделать опциональными только те, которые сейчас в типах указаны обязательными, но имеют дефолтные значения (по сути - необязательные). Это корень проблемы #2553.

P.S: на счет обязательности `alt` не согласен. Это выбор каждого делать `a11y` или нет. Нельзя к такому форсить, можно лишь рекомендовать (через линтеры, например). 

> 3. Грязный код

Это цена решения проблемы на нашей стороне. Не такая уж и большая. До этого мы решили предоставить пользователям мириться с ней, что и привело к #2553.

---
С тем, что можно оставить как есть до перехода на функциональные - согласен.

2022-05-20 08:59 UTC, JackUait commented
> Со "всеми" пропами я погорячился. Нужно сделать опциональными только те, которые сейчас в типах указаны обязательными, но имеют дефолтные значения (по сути - необязательные)...

В таком случае, мы кстати можем убить двух зайцев сразу: сейчас сделать все пропы, которые есть в `defaultProps` опциональными, это не должно занять много времени и мы быстро закроем задачу, а в функциональных компонентах углубиться в задачу и решить, какие пропы на самом деле необязательны

> ...на счет обязательности alt не согласен. Это выбор каждого делать a11y или нет. Нельзя к такому форсить...

В документации `W3C` к `HTML` атрибут `alt` обозначен как обязательный, это можно проверить в [валидаторе](https://validator.w3.org/nu/#textarea). А причины можно узнать в [туториале об изображениях](https://www.w3.org/WAI/tutorials/images/), если коротко, то любое, даже декоративное изображение должно иметь атрибут `alt`, но для декоративных изображений он должен быть пустым, также `alt` используется не только для обеспечения `a11y`, но в том числе и для скраппинга веб-страниц (распространённый пример - поисковые роботы)

<img width="686" alt="Снимок экрана 2022-05-20 в 12 54 05" src="https://user-images.githubusercontent.com/48599460/169492412-f4136eb5-4ece-4af8-bba6-685d6353704f.png">

2022-05-23 11:10 UTC, zhzz commented
Тогда, сходимся на том, что, что сейчас делаем все пропы, которые есть в `defaultProps` опциональными, прописывая для `defaultProps` корректный тип, например, через `<Partial<P>>`. Но проще, думаю, уже в отдельном ПРе. Этот закроем.

> углубиться в задачу и решить, какие пропы на самом деле необязательны

Это какая-то отдельная задача, раньше она не звучала. Можно сделать в функциональных, если она действительно стоит.

> В документации W3C к HTML атрибут alt обозначен как обязательный

Да, по факту так. Но с моей точки зрения, поддержка a11y, скраппинга и др. - это все дополнительный функционал, который мне может быть сознательно не нужен. В этом случае, меня насильно будут заставлять передавать пустую строку. И даже в остальных случаях, думаю, многие будут это делать. Тоже не очень хорошее API, плохой  DX. Я бы сделал такой проп опциональным, снабдив соответствующим правилом для eslint.

2022-06-27 10:52 UTC, closed without merging