fix(Paging): change border-radius styles
skbkontur/retail-ui pull request #2765
Opened 2022-02-07 21:59 UTC by JackUait

fixes #2762

Проблема была в том, что форму "колбаски" или "капсулы" нельзя создать с помощью процентного скругления (т.е. задав значение `border-radius` в `50%` и более процентов), для этого нужно использовать скругление в пикселях.

Обычно, для создания формы "капсулы" используют значение `9999px`, что на языке `CSS` значит: этот элемент будет кругом, когда контента мало и капсулой, когда контента будет много.

За примером использования значения `9999px` далеко ходить не нужно, `Tailwind CSS` [использует](https://tailwindcss.com/docs/border-radius) это значение в своём классе `rounded-full`.

2022-02-08 06:04 UTC, lossir reviewed
Круто бы скриншотик добавить на это дело =)

2022-02-08 11:02 UTC, JackUait commented
Добавил скриншотные тесты, но в `ie11` (8px)  и `firefox` (8px) скриншоты не совпадают с тем, что отображается в браузере (как минимум в `firefox`) на самом деле. Судя, по предыдущим скриншотам, эта проблема была и до этого изменения.

Также обновил скриншоты для тестов `Move focus right` в `ie11` и `Move to page by Enter` в `ie11` (8px). По всей видимости, в `ie11` более плохой алгоритм скругления при `border-radius: 50%` и он начинает превращать круг в яйцо на более ранней стадии.

И последнее, что заметил: в тесте `Move focus right` в `ie11` (8px) стало происходить какое-то мракобесие. Вместо того, чтобы просто смещать фокус вправо, в тесте:
1. Выбирается третий элемент меню;
2. Смещается фокус на четвёртый элемент меню;
3. А курсор (как и ожидается) остаётся на первом элементе меню.
<img width="396" alt="Снимок экрана 2022-02-08 в 13 55 45" src="https://user-images.githubusercontent.com/48599460/152973486-543e7ca3-8c50-4fa7-a66f-f92222337701.png">
При этом тест я никак не трогал.

2022-02-10 18:01 UTC, lossir reviewed
Тесты `Move focus right` и `Move to page by Enter`  походу не очень стабильные. Локально они то падают, то нет.
Можешь попробовать заменить `pause()` на `delay()`. Если не поможет, то просто заскипай.

---

> скриншоты не совпадают с тем, что отображается в браузере

Это у меня не воспроизводится. Записал видос, где я накладываю скриншоты которые сделал сам, поверх скриншотов Криви.

https://user-images.githubusercontent.com/2708211/153467717-d4cad987-2df2-4148-aeae-4c33c25f8c2e.mp4

2022-02-10 20:06 UTC, JackUait commented on packages/react-ui/components/Paging/__stories__/Paging.stories.tsx
> +};
Эта история с заданием пропсов через `.args` нужна чтобы создавать интерактивные истории.

https://user-images.githubusercontent.com/48599460/153487219-17d98c3d-47e1-4718-a912-bdee084fc744.mov

Вообще была идея создать историю, значения которой можно менять как через `controls`, так и в самом интерфейсе, но она провалилась, так как значения передаваемые в `activePage` не учитывались из-за стейта.

В общем, теперь в истории все пропсы просто деструктурируются в `Paging` и задаются через `.args`.

2022-02-10 20:31 UTC, JackUait commented
> Локально они то падают, то нет

Да, в этот раз не упали. Интересно. А есть понимание, это какой-то баг в Криви или это на стороне эмуляции браузера проблема?

2022-02-10 20:42 UTC, JackUait commented
> Это у меня не воспроизводится. Записал видос, где я накладываю скриншоты которые сделал сам, поверх скриншотов Криви.

Оказалось, что всё дело в том, как `Firefox` рендерит шрифт. В моей, последней версии  `Firefox` шрифты рендерятся чуть выше, чем в версии `Firefox` из Криви. Поэтому в текущей версии `Firefox` нет ощущения, того, что шрифт не отценрирован вертикально, а вот в старой версии  `Firefox`, которая используется в Криви такое ощущение возникает.

На видео: сравнение высоты отрендеренных шрифтов в эмуляции `Firefox` из Криви и последней версии настоящего `Chrome`. Если приглядеться, то можно увидеть, что `Chrome` рендерит шрифт выше, чем это делает эмуляция `Firefox`.

P.S.
Не стал делать сравнение непосредственно `Firefox`'ов, так как там различия ещё более минорные.

https://user-images.githubusercontent.com/48599460/153491684-2ab29891-cc1a-4c2f-bed8-c5e663955d34.mov

2022-02-11 07:29 UTC, lossir commented
> А есть понимание, это какой-то баг в Криви или это на стороне эмуляции браузера проблема?

Думаю, проблем в `selenium-webdriver`. Точнее в поддержке Web Driver самим IE11.
Мелкомягкие релизят только фиксы безопасности для осла. Вероятно, после добавления поддержки Web Driver (в ~2014) они толком ничего не правили... 

Сейчас выгоднее такие тесты просто скипать.

2022-02-11 09:26 UTC, JackUait commented
Понял) Спасибо за объяснение)

2022-03-29 07:31 UTC, lossir submitted a review, later dismissed

2022-03-29 23:28 UTC, JackUait commented
Спулил актуальный мастер.

2022-04-01 07:47 UTC, lossir commented
Надо тесты скриншотные обновить для IE11. И проверить тест `With Long Items` - там будто шрифт съехал.

2022-04-01 07:47 UTC, lossir commented
Надо тесты скриншотные обновить для IE11. И проверить тест `With Long Items` - там будто шрифт съехал.

2022-04-02 22:06 UTC, JackUait commented
Новые скриншоты заапрувил.
Скриншот `Paging` -> `GoToAbsensePage` -> `Move to page by Ender` -> `ie118px` падает с ошибкой `unrecognised content at end of stream`. Пытался перезапускать его, но это не принесло результатов. Возможно это моя, локальная ошибка из-за криво спуленных скриншотов.

Насчёт шрифта в `With Long Items` - не заметил, чтобы он съехал, может я не туда смотрел?

2022-04-04 05:34 UTC, lossir commented
> Насчёт шрифта в `With Long Items` - не заметил, чтобы он съехал...

В [том билде](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_ScreenshotTests/25543314?showRootCauses=false&expandBuildChangesSection=true&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) скриншоты выглядили так:

![image](https://user-images.githubusercontent.com/2708211/161479536-e01ad8c4-6117-4068-b737-a97027390c1f.png)

Видимо, какой-то разовый глич. Такое бывает.
Либо исправилось при мерже мастера.

2022-04-15 08:05 UTC, zhzz requested changes
Скриншоты еще не проходят.

2022-04-20 03:14 UTC, JackUait commented
Забыл обновить скриншоты для `IE11`. Там всё в порядке, просто скругление более правильное стало.

@zhzz Можешь пожалуйста обновить скриншоты? Из Армении не хочет подниматься криви-сервер. Пока разбираюсь что с этим можно сделать.

2022-04-27 06:52 UTC, zhzz commented
С криви все еще проблема? Переменная `GET_IP_URL` в .env есть?

2022-04-27 08:46 UTC, JackUait commented
Вероятно проблема была в отельном вай-фае, сейчас всё запускается нормально

Обновил скриншоты

2022-04-27 12:50 UTC, zhzz approved these changes

2022-04-28 01:20 UTC, merged