fix(PasswordInput): disable eye button when input is disabled
skbkontur/retail-ui pull request #2766
Opened 2022-02-07 22:17 UTC by JackUait

fixes #2764

Добавил стили, запрещающие клики по иконке-кнопке глаза, когда инпут отключен.

2022-04-26 08:50 UTC, JackUait commented
Обновил реализацию согласно [комментарию](https://github.com/skbkontur/retail-ui/issues/2764#issuecomment-1039246980) Вовы.

2022-04-27 09:57 UTC, zhzz requested changes

2022-04-27 09:57 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> +    }
Чтобы избежать ререндера лучше заиспользовать `getDerivedStateFromProps`.

2022-04-27 09:57 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> +          }}
В целях того же перформанса не стоит использовать стрелочную функцию в jsx. Также, можно добавить проверку на `state.visible`, прежде чем ставить в него `false`.

И я бы оставил `onBlur` в `inputProps` для красоты.

2022-04-28 08:42 UTC, zhzz requested changes

2022-04-28 08:42 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> +          onBlur={this.onBlur}
Если в компонент придет пользовательский onBlur, то он перетрет этот.

2022-04-29 06:34 UTC, zhzz approved these changes

2022-04-29 06:40 UTC, merged