Global loader correction
skbkontur/retail-ui pull request #2767
Opened 2022-02-08 05:58 UTC by HelenaIsh

fix [IF-367](https://yt.skbkontur.ru/issue/IF-367)

2022-02-09 12:14 UTC, JackUait requested changes

2022-02-09 12:14 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +}
Стоит вынести хук в отдельный файл внутри директории `/GlobalLoader`, а также добавить ему описание и покрыть тестами.

2022-02-10 10:55 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +}
```tsx
// /GlobalLoader/usePrevious.ts

/**
* Общее описание хука
* 
* @param value - описание аргумента value
* @returns Описание того, что возвращает хук
*/
function usePrevious(value: any) {
  const ref = React.useRef();
  React.useEffect(() => {
    ref.current = value;
  });
  return ref.current;
}
```

2022-02-10 10:59 UTC, JackUait commented
Заметил ещё одну деталь: `Glabal` в `GlabalLoaderView` написано через две "a".

2022-02-10 11:22 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +    <CommonWrapper {...props}>
Я был не совсем прав на счёт `data-*` атрибутов, они всё-таки могут быть переданы в компонент.

Так как помимо `data-*` атрибутов больше никакие не типизированные атрибуты не могут попасть в компонент достаточно сделать следующее:
```tsx
export const GlobalLoaderView = ({
  expectedResponseTime,
  delayBeforeHide,
  status,
  disableAnimations,
  ...rest <-- деструктурируем rest
}: GlobalLoaderViewProps) => {
   ...
   ...
   ...
  return (
    <ZIndex priority="GlobalLoader" className={styles.outer(theme)} {...rest} <-- передаём в ZIndex>
	  ...
	  ...
	  ...
    </ZIndex>
  );
};
```

2022-02-10 11:37 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +  }, [status]);
Вот эту логику тоже стоит вынести в отдельный хук, в который мы будем передавать `status` и `ref` и обратно получать `width`, `left` и `startWidth`.

Что-то вроде этого:
```tsx
// /GlobalLoader/useSomething.ts
export const useSomething = (status, ref) => {
	const { width = 0, left = 0 } = ref.current?.getBoundingClientRect() || {};

  const [startWidth, setStartWidth] = useState(0);

  const prevStatus = usePrevious(status);

  useEffect(() => {
    if (prevStatus === 'standard' && status === 'error') {
      setStartWidth(width);
    } else if (prevStatus === 'error' && status === 'accept') {
      setStartWidth(startWidth);
    } else {
      setStartWidth(0);
    }
  }, [status]);
	
	return { width, left, startWidth }
}

// GlobalLoaderView.tsx
const ref = useRef<HTMLDivElement>(null);
const theme = useContext(ThemeContext);

const { width, startWidth, left } = useSomething(status, ref)
```

2022-02-11 13:14 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useGlobalLoaderViewParams.ts
> +    const statusChangedToAccept = prevStatus === 'error' && status === 'accept';
Давай заменим на:
1. `statusChangedToError` => `hasStatusChangedToError`
2. `statusChangedToAccept` => `hasStatusChangedToAccept`

Кстати, а почему в `statusChangedToError` расширилось условие?

2022-02-11 13:17 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/usePrevious.ts
> + * Возвраащет предыдущее значение переданной переменной
```suggestion
 * Возвращает предыдущее значение переданной переменной
```

2022-02-11 13:32 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useGlobalLoaderViewParams.ts
> + */
Лучше использовать названия компонентов на английском и писать их слитно в обратных кавычках (так они будут приятно подсвечиваться `IDE`):
```suggestion
/**
 * Вычисляет необходимые параметры `GlobalLoader`
 *
 * @param status - статус `GlobalLoader`
 * @param ref - ref `GlobalLoaderView`
 * @returns - возвращает ширину, левое положение и ширину полоски `GlobalLoader` при переходе в состояние ошибки
 */
```

Также _"Вычисляет необходимые параметры"_ звучит слишком глобально (_намеренный каламбур_), хук всё-таки вычисляет размер полоски в зависимости от статуса. Нужно это как-то обыграть.

2022-02-11 13:36 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useGlobalLoaderViewParams.ts
> + */
Следовательно и название самого хука стоит изменить

2022-02-11 13:38 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useGlobalLoaderViewParams.ts
> +  ref: React.RefObject<HTMLDivElement>,
Давай в `GlobalLoaderView` вынесем тип `ref`-ки в отдельный тип и переиспользуем в хуке:
```ts
// GlobalLoaderView.tsx: снаружи компонента
export type GlobalLoaderViewRef = {
  element: HTMLDivElement;
  refObject: React.RefObject<GlobalLoaderViewRef['element']>;
};

// GlobalLoaderView.tsx: внутри компонента
const ref = useRef<GlobalLoaderViewRef['element']>(null);

// useGlobalLoaderViewParams.ts
ref: GlobalLoaderViewRef['refObject']
```

2022-02-11 13:52 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/GlabalLoaderView.tsx
> +    <CommonWrapper {...props}>
Хмм, да, странное поведение. Окей, пускай пока остаётся так, я во время перевода на функциональные компоненты посмотрю в чём была проблема.

2022-02-14 03:06 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/usePrevious.ts
> +export function usePrevious(value: any) {
Не думаю, что этот хук стоит выносить в `/lib` сейчас.
Это больше запасной вариант, когда `useEffect` с необходимой зависимостью не позволяет решить задачу. Есть большая вероятность, что он никогда больше не понадобится (это буквально второй раз, когда я вижу необходимость в этом хуке за всю практику, вероятно и эту задачу можно решить без "путешествий во времени"). Нужно по возможности избегать "путешествий во времени", так как они всегда добавляют много неопределённости.

> Ещё стоит добавить в зависимость эффекта саму переменную. Так не будет лишнего запуска, если методы дёрнуться несколько раз подряд.

А вот насчёт этого согласен.

2022-02-14 04:49 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/useGlobalLoaderViewParams.ts
> +    const statusChangedToAccept = prevStatus === 'error' && status === 'accept';
> Кстати, а почему в statusChangedToError расширилось условие?

Когда рефакторила, поняла, что мы должны "запоминать" где остановилась загрузка не только когда ошибка пришла после "стандартной" загрузки, но также если ошибка пришла после состояния "accept"

2022-02-14 08:04 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/usePrevious.ts
> +export function usePrevious(value: any) {
Попробовала избавиться от `usePrevious` - вроде бы получилось

2022-02-14 09:51 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useWidthAndPosition.ts
> +export const useWidthAndPosition = (status: GlobalLoaderViewProps['status'], ref: GlobalLoaderViewRef['refObject']) => {
Зачастую, появление `and` в названии сигнализирует о том, что логику стоит разделить на две отдельных сущности.

Давай разделим этот хук на два: `useGlobalLoaderWidth` и `useGlobalLoaderPosition`. Можно в принципе даже оставить их в одном файле, так как они логически связаны, но тогда нужно что-то сделать с названием самого файла.

2022-02-14 10:06 UTC, JackUait commented on packages/react-ui/components/GlobalLoader/useWidthAndPosition.ts
> +  const { width = 0, left = 0 } = ref.current?.getBoundingClientRect() || {};
Слишком много логики для одной строки. Давай вынесем в отдельную функцию и сразу в `/lib` её запихнём, так как эта логика много где нужна (главное не забыть её переиспользовать в последствии).
```ts
// lib/dom/getDOMRect.ts

const getDOMRect = <T extends HTMLElement>(ref: React.RefObject<T>): Omit<DOMRect, 'toJSON'> => {
  if (!ref.current) {
    const defaultValues = {
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      bottom: 0,
      left: 0,
      right: 0,
      top: 0,
    };

    return defaultValues;
  }

  return ref.current.getBoundingClientRect();
};
```

2022-02-14 10:18 UTC, JackUait approved these changes

2022-02-14 10:18 UTC, JackUait requested changes
Промазал по кнопке😪

2022-02-15 09:36 UTC, JackUait approved these changes

2022-02-15 12:49 UTC, JackUait commented
Ещё нашёл случаи использования `non-null assertion` в `GlobalLoader`.

```tsx
// GlobalLoader.tsx: 71-84
private readonly startTask = debounce(() => {
  this.setState({ visible: true });
  this.props.onStart?.();
  this.errorTask();
}, this.props.delayBeforeShow!); <---

private readonly errorTask = debounce(() => {
  this.setState({ rejected: true });
}, this.props.expectedResponseTime + this.props.overtime!); <---

private readonly stopTask = debounce(() => {
  this.setState({ visible: false, successAnimationInProgress: false });
  this.props.onDone?.();
}, this.props.delayBeforeHide!); <---
```
```tsx
// GlobalLoader.tsx: 146-153
<GlobalLoaderView
  expectedResponseTime={this.state.expectedResponseTime}
  delayBeforeHide={this.props.delayBeforeHide!} <---
  status={status}
  data-tid="GlobalLoader"
  disableAnimations={this.props.disableAnimations}
  overtime={this.props.overtime!} <---
/>
```

Нужно заменить `non-null assertion` на проверки.

2022-02-15 19:23 UTC, JackUait commented
В #2803 пофиксил все места, где используется `non-null assertion`, кроме `GlobalLoader`'а. Так как в этом `PR` произошли изменения относительно мест, где используется `non-null assertion`, которых нет в `next`.

2022-02-15 19:24 UTC, JackUait requested changes
В https://github.com/skbkontur/retail-ui/pull/2803 пофиксил все места, где используется non-null assertion, кроме GlobalLoader'а. Так как в этом PR произошли изменения относительно мест, где используется non-null assertion, которых нет в next.

2022-02-16 05:20 UTC, lossir commented
@JackUait Правки по GL приоритетней. Потом просто обновишь ветку в https://github.com/skbkontur/retail-ui/pull/2803 и добавишь изменения для GL

2022-02-16 12:34 UTC, dzekh approved these changes

2022-02-16 12:36 UTC, JackUait commented
Да, теперь топ!

2022-02-16 12:36 UTC, JackUait approved these changes

2022-02-16 12:57 UTC, merged