[Input] - проблема с placeholder в IE11
skbkontur/retail-ui pull request #2777
Opened 2022-02-09 10:02 UTC by HelenaIsh

2022-02-10 11:45 UTC, JackUait commented
Может скриншотиков добавим?)

2022-02-11 12:05 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +      }
Давай упростим ветвление до одного `if`, а также вынесем условие проверки изменённого значения в переменную.

```suggestion
  public componentDidUpdate(prevProps: Readonly<InputProps>) {
    const isValueChanged = this.props.value !== prevProps.value
  
    if (isValueChanged && polyfillPlaceholder && !this.props.value) {
        this.setState({ polyfillPlaceholder: true });
     }
```

2022-02-11 12:46 UTC, JackUait commented
Давай здесь же обновим `polyfillPlaceholder`.

Изменения:
1. `polyfillPlaceholder.ts` => `needsPolyfilledPlaceholder.ts`.
2. Полностью удаляем `polyfillPlaceholder`.
3. Заменяем `polyfillPlaceholder` на `needsPolyfilledPlaceholder` в `Input` и `Textarea`.
```ts
// lib/needsPolyfilledPlaceholder.ts

import { canUseDOM, isIE11 } from './client';

export const needsPolyfilledPlaceholder = () => {
  if (canUseDOM) {
    const supportsPlaceholder = 'placeholder' in document.createElement('input');

    if (!supportsPlaceholder || isIE11) {
      return true;
    }
  }

  return false;
};

```

Достаточно в местах где сейчас используется переменная `polyfillPlaceholder` вызывать функцию `needsPolyfilledPlaceholder`.

Я прогнал скриншотные и unit/интеграционные тесты ничего не упало.

2022-02-11 12:50 UTC, JackUait commented
Давай ещё задокументируем и покроем тестами `needsPolyfilledPlaceholder`, чтобы не плодить техдолг)

2022-02-14 12:22 UTC, JackUait commented on packages/react-ui/lib/__tests__/needsPolyfillPlaceholder-test.ts
> +  }
В текущем варианте всегда будет запускаться только один тест.
То есть мы не узнаем падает ли тест со вторым условием, если первое правдиво.
```suggestion
  it('returns true if the browser is IE11', () => {
    if (isIE11) {
      expect(needsPolyfillPlaceholder()).toEqual(true);
    }
  });

  it('returns true if browser does not support placeholder attribute', () => {
    if (!supportsPlaceholder) {
      expect(needsPolyfillPlaceholder()).toEqual(true);
    }
  });

  it('returns false if browser supports placeholder attribute', () => {
    if (isIE11 && !supportsPlaceholder) {
      expect(needsPolyfillPlaceholder()).toEqual(true);
    }
  });
```

Для изменений выше придётся ещё вытащить из функции и экспортировать наружу `supportsPlaceholder`.

```ts
// lib/needsPolyfillPlaceholder.ts

export const supportsPlaceholder = 'placeholder' in document.createElement('input');
```

2022-02-16 12:06 UTC, JackUait submitted a review, later dismissed

2022-02-28 11:02 UTC, zhzz requested changes

2022-02-28 11:02 UTC, zhzz commented on packages/react-ui/lib/needsPolyfillPlaceholder.ts
> +};
@JackUait зачем было менять константу на функцию? Значение ведь не может поменяться с течением времени, достаточно его вычислить один раз.

2022-02-28 22:52 UTC, JackUait commented on packages/react-ui/lib/needsPolyfillPlaceholder.ts
> +};
Я вижу несколько причин по которым не стоит использовать константу:
1. Функцию можно покрыть тестами;
2. Код функции выглядит чище и понятнее;
3. Мы не мутируем данные.

Если вопрос больше про то, почему мы несколько раз вычисляем значение, когда этого можно не делать, то можно сделать функцию внутренней и экспортировать результат вычисления в качестве переменной (то есть частично вернуть старый вариант):
```ts
export const needsPolyfillPlaceholder = needsPolyfillPlaceholderInternal()
```

2022-03-01 06:12 UTC, zhzz commented on packages/react-ui/lib/needsPolyfillPlaceholder.ts
> +};
Согласен, что функция лучше, но вызывать ее каждый раз действительно нет смысла. Сохранить результат и экспортировать - норм.

2022-03-01 17:12 UTC, JackUait commented
Падают смок-тесты.

2022-04-15 14:14 UTC, zhzz requested changes
Глядя на Textarea, там тот же функционал реализуется без махинаций в componentDidUpdate и, вроде, работает. Наверное стоит сделать одинаково.

В обоих компонентах сейчас не учитывается сценарий uncontrolled-режима с переданным `defaultValue`, напрмер:

```jsx
<Input placeholder="placeholder" defaultValue="value" />;
```

2022-04-25 13:05 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +      }
В Textarea та же проблема решается только в `handleChange`, без этой логики вообще. Она точно нужна?

2022-04-25 14:31 UTC, HelenaIsh commented on packages/react-ui/components/Input/Input.tsx
> +      }
Конечно не нужна. Была уверена, что удалила этот кусок кода 🤦‍♀️. Извини

2022-04-26 06:06 UTC, zhzz approved these changes

2022-04-26 06:09 UTC, merged