fix(Paging): hide Paging when only one page presented
skbkontur/retail-ui pull request #2778
Opened 2022-02-09 21:49 UTC by JackUait

fixes #2761

Добавил условие, скрывающее `Paging` при менее чем двух страницах.

2022-02-10 18:13 UTC, lossir requested changes

2022-02-10 18:13 UTC, lossir commented on packages/react-ui/components/Paging/Paging.tsx
> +    }
Давай всё-таки спрячем это под флаг. Пусть по-умолчанию будет старое поведение.
У нас у самих несколько тестов развалилось. Изменения однозначно ломающее.

2022-02-10 20:51 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.tsx
> +    }
Думаю, что стоит обсудить это с Вовой @dzekh сначала. Если это новое дефолтное поведение, то его нет смысла прятать под флаг, даже если оно ломающее.

Смысл прятать это изменение под флаг есть в том случае, если есть сценарий, в котором такое поведение может понадобиться. Но я не уверен, что такой сценарий на самом деле существует для этого кейса)

2022-02-11 06:51 UTC, lossir commented on packages/react-ui/components/Paging/Paging.tsx
> +    }
Новое новое дефолтное поведение надо в некст тащить. А мастер совсем скоро станет `LTS`.
Не надо людей пугать ломающими изменениями.

2022-02-11 09:49 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.tsx
> +    }
Да, так и собирался сделать, не от той ветки бренчанулся. Есть какой-то способ залить этот PR в next без создания новой ветки?

2022-02-11 13:47 UTC, dzekh commented on packages/react-ui/components/Paging/Paging.tsx
> +    }
Вроде разобрались тут, да? Перенаправим в некст и не будем ничего прятать под флагами. 

Хотя есть конечно вероятность что кому-то все-таки приспичит и понадобится задизебленый одностраничный пейджинг, но предлагаю начать это обсуждать после того как такой человек или проект появится, и добавлять только если мы мы поймем что там точно по другому не обойтись.

2022-04-01 04:25 UTC, lossir commented
Поменял тест dotnet.. Но похоже мы опоздали с релизом =)

Предлагаю добавить новый проп, который будет реализовывать этот сценарий. Но по умолчанию будет старое поведение. И для следующего мажорного релиза мы изменим поведение по умолчанию (и удалим проп...)

Так мы не потеряем этот код, и сможем предупредить пользователей.

2022-04-15 07:53 UTC, zhzz commented
Ждем новый проп.

2022-04-20 03:45 UTC, JackUait commented
Спрятал изменения под проп, написал новые интеграционные тесты, вернул старый тест в селениуме (не уверен, можно ли в селениум-тесты пробрасывать пропы).

2022-04-27 06:55 UTC, zhzz commented on packages/react-ui/components/Paging/Paging.tsx
> +    if (this.props.pagesCount < 2 && this.props.shouldBeVisibleWithOnePage) {
Тут немного не соответствует условие и название флага. Флаг не отражает ситуацию с `pagesCount === 0`.

2022-04-27 07:20 UTC, zhzz requested changes

2022-04-27 07:20 UTC, zhzz commented on packages/react-ui/components/Paging/Paging.tsx
> +    if (this.props.pagesCount < 2 && this.props.shouldBeVisibleWithOnePage) {
Перепутано условие и значение флага по умолчанию. В формулировке `shouldBeVisibleWithOnePage` он по умолчанию должен быть `true` и в этом условии возвращать не `null`.

2022-04-27 09:08 UTC, JackUait commented
Пофиксил оба коммента

2022-04-27 10:12 UTC, zhzz commented
Юнит-тестики сломались. Стоит тогда селениум тест переименовать обратно тоже.

2022-04-28 11:27 UTC, zhzz approved these changes

2022-04-28 11:30 UTC, merged