chore(eslint): expand eslint config with new rules
skbkontur/retail-ui pull request #2791
Opened 2022-02-11 02:09 UTC by JackUait

Добавил новые правила в глобальный `.eslintrc`.
Эти правила не нашли ошибок в проекте.

2022-02-11 19:45 UTC, JackUait commented
Заапрувил скриншоты:
1. СomboBox > always reject > opened > chromeDark
2. Group > Simple Group with Input and Button > focused input > chromeDark
3. TokenInput > [combined] filled > editToken > chromeDark
4. TokenInput > custom add button > addButton > chromeDark
5. TokenInput > empty combined > selectFirst > chromeDark
6. TokenInput > empty with reference > clicked > chromeDark
7. TokenInput > empty with reference > withMenu > chromeDark
8. TokenInput > full width menu > selectFirst > chromeDark
9. Tooltip > Tooltip with Input and switchable content > clear input > chromeDark

На этих скриншотах была мигающая палочка ввода, которая отсутствует на этих же скриншотах из других браузеров.

2022-02-13 12:46 UTC, JackUait commented
Часть новых функций названа общими именами (вроде `getGeneric`, `calculateGeneric`), потому что у меня недостаточно контекста, чтобы дать им более конкретные названия.

Было бы круто, если бы вы помогли обозвать такие функции)

2022-02-13 20:16 UTC, JackUait commented
Для того, чтобы затащить правило `no-bitwise` пришлось произвести серьёзный рефактор и избавиться от константы `CORNERS`. Эта константа и вся связанная с ней логика были нужны только для определения скругления кнопок в компоненте `Group`, больше константа нигде не использовалась.

Логику касающуюся скругления кнопок в `Group` пришлось полностью перелопатить, так как для определения скругления использовались очень неочевидные действия с побитовыми операциями.

2022-03-16 23:30 UTC, JackUait commented
Смёржил актуальный мастер и пофиксил конфликты.

2022-03-24 16:20 UTC, zhzz requested changes

2022-03-25 05:46 UTC, JackUait commented on .eslintrc
> +    "eqeqeq": 2,
> А также не стоит ли добавить isNullable на замену !isNonNullable, чтобы было проще читать и понимать.

Изначально не хотели добавлять вторую функцию)) [Комментарий](https://github.com/skbkontur/retail-ui/pull/2573#issuecomment-950398540) из #2573

Добавил функцию `isNullable` в `react-ui` и `react-ui-validations` и покрыл её тестами.

2022-03-25 05:54 UTC, JackUait commented on packages/react-ui/components/DateInput/helpers/InternalDateMediator.ts
> +    const calculatedType = getType();
Можно переписать так:
```ts
const calculatedType = type ?? this.getLeftmostType()
```

2022-03-25 06:01 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +  // TODO: Find out what's going on in this `if` statement`.
> В случае функции, она вызывается, результат реассайнится и тоже проверяется ReactElement.

Есть идеи как это можно пофиксить?

2022-03-25 06:01 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +  // TODO: Find out what's going on in this `if` statement`.
Удалил все свои комментарии в стиле _"find out what's wrong here..."._

2022-03-25 06:07 UTC, JackUait commented on packages/react-ui/components/Modal/__tests__/Modal-test.tsx
> +    isClickTarget.dispatchEvent(clickEvent);
Заменил на `mouseElementTarget` и `clickElementTarget`.

2022-03-25 06:13 UTC, JackUait commented on .eslintrc
> +    "prefer-arrow-callback": 2,
Да, пожалуй с селениумом его особо не поиспользуешь. Пока отключил его.

Жаль, что нет возможности настраивать проверяемые файлы для каждого отдельного правила, кажется, что такая фича очень пригодилась бы для большого количества правил.

2022-03-25 06:22 UTC, JackUait commented on .eslintrc
> +    "no-multi-assign": 2,
Ты имеешь ввиду сделать что-то вроде кода ниже?
```ts
let expectingId = this.requestId;
expectingId += 1;
```

Если да, то мне не особо нравится такой вариант, из-за мутации значения `expectingId`.

Можно создать какую-нибудь функцию, которая бы увеличивала на единицу, но без мутации переменной.

2022-03-25 06:24 UTC, JackUait commented on .eslintrc
> +    "no-multi-assign": 2,
```ts
// components/Tooltip/__tests__/Tooltip-test.tsx

const timer = (instance.hoverTimeout = setTimeout(() => {}));
```

А в этом случае, честно говоря у меня даже нет предположений как это переписать.

2022-03-28 11:01 UTC, zhzz requested changes

2022-03-29 08:11 UTC, zhzz commented on .eslintrc
> +    "no-multi-assign": 2,
> ```ts
> // components/Tooltip/__tests__/Tooltip-test.tsx
> 
> const timer = (instance.hoverTimeout = setTimeout(() => {}));
> ```
> 
> А в этом случае, честно говоря у меня даже нет предположений как это переписать.


```ts
const timer = setTimeout(() => {});
instance.hoverTimeout = timer;
```
?

2022-03-29 08:23 UTC, zhzz commented on .eslintrc
> +    "no-multi-assign": 2,
> Ты имеешь ввиду сделать что-то вроде кода ниже?
> 
> ```ts
> let expectingId = this.requestId;
> expectingId += 1;
> ```
> 
> Если да, то мне не особо нравится такой вариант, из-за мутации значения `expectingId`.
> 
> Можно создать какую-нибудь функцию, которая бы увеличивала на единицу, но без мутации переменной.

А просто вот так?
```ts
this.requestId += 1;
const expectingId = this.requestId;
```

2022-03-29 09:56 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +  // TODO: Find out what's going on in this `if` statement`.
> > В случае функции, она вызывается, результат реассайнится и тоже проверяется ReactElement.
> 
> Есть идеи как это можно пофиксить?

Например, через функцию `getTextFromItem`:
```ts
const getTextFromItem = (item: any): string => {
  switch (true) {
    case isFunction(item): {
      return getTextFromItem(item());
    }
    case React.isValidElement(item): {
      return reactGetTextContent(item);
    }
    case typeof item === 'number': {
      return item.toString(10);
    }
    default: {
      return '';
    }
  }
};

function filterItem(value: any, item: any, pattern: string) {
  if (item === Select.SEP) {
    return false;
  }

  const itemText = getTextFromItem(item);

  if (!itemText) {
    return false;
  }

  return itemText.toLowerCase().indexOf(pattern) !== -1;
}
```

2022-03-29 23:58 UTC, JackUait commented on .eslintrc
> +    "object-shorthand": [2, "consistent"],
Как по мне такую запись сложнее воспринимать:
```ts
const foo = () => {
  ...
  return {
    label,
    value: id,
    description 
  }
}
```

Чем такую запись:
```ts
const foo = () => {
  ...
  return {
    label: label,
    value: id,
    description: description 
  }
}
```

При этом правило позволяет не прописывать `value`, когда у всех полей в объекте `key` и `value` совпадают:
```ts
const foo = () => {
  ...
  return { label, value, description }
}
```

> Зачем писать лишнее?

Так более очевидно какое значение у поля) Если идти по аналогии, то тернарники с более чем двумя вариантами короче чем несколько `if`, также как и стрелочные функции без тела, но сложнее воспринимать чем более длинные варианты.

Можем вынести этот вопрос на обсуждение и на основании голосования принять решение оставлять это правило или нет.

2022-03-30 09:57 UTC, zhzz commented on .eslintrc
> +    "object-shorthand": [2, "consistent"],
Вот мы и столкнулись со вкусовщиной! Я поэтому и предпочитаю дефолтные/рекомендуемые/общепринятые настройки, о которых уже кто-то подумал и обоснованно выбрал, чтобы нам не спорить и от проекта к проекту потом не переучиваться.

В случае тернарников там заметно страдает читаемость. А тут, если честно, не понимаю, чем так:
```
{ label: label, value: id, description: description }
```
очевиднее чем так:
```
{ label, value: id, description }
```
но при этом такое считается норм:
```
{ label, value, description }
```

2022-04-02 21:31 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +  // TODO: Find out what's going on in this `if` statement`.
Круто! Только немного поменял реализацию условной логики, так как вариант со свитчём походит на ненужный хак.
```ts
const getTextFromItem = (item: any): string => {
  if (isFunction(item)) {
    return getTextFromItem(item());
  }

  if (React.isValidElement(item)) {
    return reactGetTextContent(item);
  }

  if (typeof item === 'number') {
    return item.toString(10);
  }

  return '';
};

```

2022-04-04 14:35 UTC, zhzz reviewed
Линтеры еще не до конца проходят

2022-04-08 15:35 UTC, JackUait commented
С исправленной функцией `filterItem` не работал поиск. Пока разбирался в чём причина того, что не работает поиск переписал тест, тестирующий поиск. Тест остался по сути остался прежним, но я избавился от тестирования деталей реализации, имитируя действия пользователя, при работе с `Select`-ом; также немного дополнил тест, проверкой того, что пользователь может ввести не только один символ.

2022-04-13 11:30 UTC, zhzz requested changes
Скриншоты не должны были поменяться. Они видимо когда-то пару раз мигнули, ты 10 штук переаппрувил, а теперь они же снова не проходят. Скриншоты мигают, такое бывает.

2022-04-13 11:30 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +            const hasOnlyOneChild = firstChild === null;
Тут что-то странное. Условие `firstChild === null` не говорит о том, что child только один.

2022-04-13 11:30 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
Не очень понятно, зачем нужен `hasOnlyOneChild`, ведь `isFirstChild` должен по идее отработать и в том случае, когда ребенок только один.

2022-04-13 11:30 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +};
Функции некорректно отрабатывают в случае, когда child только один, возвращая `undefined`.

2022-04-13 11:39 UTC, zhzz reviewed
> С исправленной функцией `filterItem` не работал поиск. Пока разбирался в чём причина того, что не работает поиск переписал тест, тестирующий поиск.

А что в итоге с этим? Поиск будет работать, просто я в своей версии `getTextFromItem` не учел случай, когда item уже строка.

2022-04-27 03:39 UTC, JackUait commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +  return newPos;
Да, ты прав, тут можно спокойно обойтись без мутации, всего лишь нужно было поменять местами условия:
```tsx
const calculatePos = (pos: number, minPos: number, maxPos: number) => {
  if (maxPos <= pos) {
    return maxPos;
  }

  if (minPos >= pos) {
    return minPos;
  }

  return pos;
};
```

2022-04-27 04:33 UTC, JackUait commented
> А что в итоге с этим? Поиск будет работать, просто я в своей версии getTextFromItem не учел случай, когда item уже строка.

Добавил обработку строк

2022-04-27 20:15 UTC, JackUait commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
Логика с `hasOnlyOneChild` нужна для кейса `CurrencyInput`, можно увидеть как он падает в истории `ThemeProvider`

2022-04-28 11:23 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
А почему таки `isFirstChild` не хватает и он падает?  И почему условие `firstChild === null` означает `hasOnlyOneChild`?

2022-04-28 11:23 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
А почему таки `isFirstChild` не хватает и он падает?  И почему условие `firstChild === null` означает `hasOnlyOneChild`?

2022-04-28 13:30 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
Но логика не появилась. Почему условие `firstChild === null` называется `isFirstChild `?
И отдельный вопрос, что будет, если перед инпутом появится еще один `child`, который тоже будет `null`?

2022-04-28 14:24 UTC, JackUait commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
Потому что `firstChild` у нас может быть как компонентом так и `null`

> И еще вопрос, что будет, если перед инпутом появится еще один child, который тоже будет null?

Мы же рассматриваем только `child`ов внутри `Group` и если у нас `children` внутри `Group` будут иметь такой вид:
```tsx
[null, null, { component }]
```
То первый `child` всё равно будет `null` и логика отработает правильно
Или я неправильно понял что ты имеешь ввиду?

2022-04-29 06:30 UTC, zhzz commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
> Почему условие `firstChild === null` называется `isFirstChild`?

> Потому что `firstChild` у нас может быть как компонентом так и `null`.

Но ведь `isFirstChild` применится ко всем чилдам. И непонятно, почему третий по порядку `child` (и все последующие тоже) должен считаться первым, если первый по порядку равен `null` (а второй по порядку, например, не равен).

Пример выше я не тот привел. На самом деле хотел привести такой:
```jsx
<Group>
  {null}
  <Input />
  <Button />
  // ...
</Group>
```
Можно посмотреть [в доке](https://tech.skbkontur.ru/react-ui/#/Components/Group).

2022-04-29 07:42 UTC, JackUait commented on packages/react-ui/components/Group/Group.tsx
> +                    [styles.itemFirst()]: isFirstChild || hasOnlyOneChild,
Теперь понял о чём речь)

Получилось пофиксить этот момент, убрав из массива "пустых" детей с помощью `React.Children.toArray`, теперь, если какой-то из `child`ов равняется `null` он просто не будет отображаться в массиве
```ts
// Раньше
[null, { component }, { component }]
```

```ts
// Теперь
[{ component }, { component }]
```

2022-05-06 06:04 UTC, zhzz approved these changes

2022-05-23 11:28 UTC, zhzz commented
Подождем, пока починятся скриншоты, подольем мастер, перепрогоним и вольем.

2022-06-03 17:34 UTC, zhzz approved these changes

2022-06-03 17:35 UTC, merged