chore(eslint): expand TypeScript linting rules
skbkontur/retail-ui pull request #2803
Opened 2022-02-15 19:17 UTC by JackUait

Добавил новые и включил старые правила относящиеся к React'у в глобальном .eslintrc.

Каждый коммит покрывает одно правило.

2022-02-15 22:37 UTC, JackUait commented
Удалил `spinnerCloudOffset` и `spinnerCloudLength` из `lib/theming/AnimationKeyframes.ts`, так как эти стили нигде не использовались.

2022-02-16 12:34 UTC, JackUait commented
Исправил настоящие проблемы, которые нашло правило `@typescript-eslint/ban-types` и отключил его, так как оно много где ругается на вполне легальное использования типов. Можно время от времени его прогонять для профилактики, но постоянно держать его включённым не стоит.

2022-02-16 18:45 UTC, JackUait commented
Линтинг перестанет падать после слива #2768 в `next`.

2022-03-16 23:35 UTC, JackUait commented
Смёржил актуальный мастер и пофиксил конфликты.

2022-03-24 08:12 UTC, zhzz requested changes
А на какие легальные случаи ругается `@typescript-eslint/ban-types`?
Есть ли шанс полностью перейти на все рекомендуемые правила, без исключений?

2022-03-24 08:12 UTC, zhzz commented on .eslintrc
> +    "@typescript-eslint/no-unused-vars": 1,
Это дубль настройки из `@typescript-eslint/recommended`.

2022-03-24 10:53 UTC, JackUait commented on packages/react-ui/lib/styles/DimensionFunctions.ts
> +export const shift = (value: string, shift?: string): string => {
В `/lib/styles/__tests__/DimensionFunctions-test.ts` есть тест:
```ts
test('does not shift if no shift passed', () => {
  const actual = shift('50px');
  expect(actual).toBe('50px');
});
```

Из-за него подумал, что есть cценарий, в котором функция используется без второго аргумента.
Тогда удалю тест, так как не вижу в нём смысла, если функция внутренняя и мы её будем использовать только в связке с тайпскриптом.

2022-03-24 10:57 UTC, JackUait commented on .eslintrc
> +    "@typescript-eslint/no-unused-vars": 1,
Оставил объявление правила, чтобы настроить [ignorerestsiblings](https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings).

2022-03-24 11:29 UTC, JackUait commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
Вообще у меня была такая логика: как возвращаемый тип указан `InternalDateComponentsNumber`:
```ts
interface InternalDateComponentsNumber {
  year: number;
  month: number;
  date: number;
}
```

Следовательно, мы не ожидаем, что функция вернёт `null`. А так как у переменной `components` тип `InternalDateComponentsNumber`, решил, что правильным будет возвращать его.

Внутри `if` мы просто возвращаем объект `components` с месяцем уменьшенным на единицу.

Также одно из двух мест (проп `onSelect` из `Picker`), в которое передаётся `toNativeFormat` ожидает `CalendarDateShape` без `null`. Если проп `onSelect` всё-таки может обрабатывать `null`, то это ошибка в типе возвращаемого значения в функции `toNativeFormat` и в типе принимаемого аргумента в `onSelect`.

P.S.
Также не пойму зачем нам два различных типа: `CalendarDateShape` и `InternalDateComponentsNumber`, если они идентичны.

2022-03-24 11:32 UTC, JackUait commented
> А на какие легальные случаи ругается @typescript-eslint/ban-types?
Есть ли шанс полностью перейти на все рекомендуемые правила, без исключений?

В основном на `{}` и на `object`. Эти типы не особо пригождаются в продуктовой разработке, но в библиотеке есть места, где они действительно нужны. Есть вариант отключить проверку именно этих типов.

2022-03-24 11:44 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.tsx
> +// TODO: Stop passing `active` prop to `component`.
Сейчас уже не вспомню какая причина у этого `TODO`... В следующий раз буду писать более развёрнутый комментарий.

2022-03-24 11:44 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.tsx
> +// TODO: Stop passing `active` prop to `component`.
Пока удаляю `TODO`.

2022-03-24 11:45 UTC, JackUait commented on packages/react-ui/components/Paging/__stories__/Paging.stories.tsx
> +      <a href={'#' + (getPageFromHash() + 1)} {...rest}>
Решилось добавлением правила `ignoreRestSiblings`.

2022-03-25 12:22 UTC, JackUait commented
Функция `fetch` из файла `/lib/net/fetch` нигде не использовалась, удалил её до выяснения обстоятельств.

2022-03-28 08:32 UTC, lossir commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
`InternalDate` был создан позднее и как самостоятельный хелпер. Использовать тип `CalendarDateShape` было не очень правильно, хоть они и идентичны. Неочевидная внешняя зависимость.
И наоборот, замена  `CalendarDateShape` на `InternalDateComponentsNumber` также бы усложнило устройство Календаря, который и так реализован довольно запутанно. Его давно следовало бы переписать.

Хелпер `InternalDate` появился только для поддержки локализации в `DateInput`. И тогда хватило сил только на необходимый рефакторинг самого `DateInput` =)

2022-03-28 12:14 UTC, zhzz commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
Возвращаемый тип раньше был же `InternalDateComponentsNumber | null`.
И на этот возможный null был расчет в DatePicker при форматировании minDate/maxDate. Сейчас в них может упасть какая-то невалидная дата вместо undefined.
А в Picker видимо не нужно дергать onSelect если получился null.

2022-03-29 07:24 UTC, zhzz commented
> Функция `fetch` из файла `/lib/net/fetch` нигде не использовалась, удалил её до выяснения обстоятельств.

Пока вижу функцию на месте. 🤔  И она используется в доке и в аддонах. Можно будет вынести потом в [отдельный пакет](https://yt.skbkontur.ru/issue/IF-215).

2022-03-29 11:32 UTC, zhzz commented
> > А на какие легальные случаи ругается @typescript-eslint/ban-types?
> > Есть ли шанс полностью перейти на все рекомендуемые правила, без исключений?
> 
> В основном на `{}`, `object` и `Function`. Эти типы не особо пригождаются в продуктовой разработке, но в библиотеке есть места, где они действительно нужны. Есть вариант отключить проверку именно этих типов.
> 
> Вернул правило `@typescript-eslint/ban-types` с отключенными типами `{}`, `object` и `Function`.

Я нашёл только пару безопасных использований `Function`, и там правило можно локально заигнорить. 

В остальных же случаях, мне кажется, мы как раз попадаем в ловушку неочевидных особенностей `{}` и `object`, от которых пытаются оградить нас дефолтные настройки этого правила. Т.е. мы используем `{}` и `object` там, где подразумеваем любой объект со строковыми ключами, но эти типы [намного шире](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492). Стоит переписать на рекомендуемый `Record<string, unknown>`.

А у `Function` возвращаемый тип всегда `any`, и он также принимает классы, поэтому тоже резонно не рекомендуется к  использованию.

2022-04-11 07:42 UTC, JackUait commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
Расширил тип пропа `onSelect` в `Picker`. Теперь тип выглядит так: `CalendarDateShape | null`.

Для этого пришлось расширить функцию `handleSelect` в `DatePicker`, чтобы она обрабатывала `null`, что наводит на мысль, что изменение может быть ломающим для пользователей.

Изменения можно посмотреть в коммите [fix: typing of toNativeFormat](https://github.com/skbkontur/retail-ui/pull/2803/commits/3a6805f16348307fd3d9135792b4d0fbccbccd7a).

2022-04-20 04:51 UTC, JackUait commented
Полностью включил правило `@typescript-eslint/ban-types`. В некоторых местах для замены `object` пришлось использовать `Record<string, any>`, вместо `Record<string, unknown>`, не нашёл простого/универсального способа пофиксить это здесь и сейчас, вернусь к этому вопросу в #2856, когда буду выпиливать `any`.

2022-04-26 10:57 UTC, zhzz commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
Проще не звать `onSelect` в `handleSelectToday`,  если из `toNativeFormat` пришел `null`, как я уже предложил.

Вряд ли это что-то сломает. Скорее наоборот предотвратит ошибки с дальнейшей деструктуризацией `null`.

2022-04-27 02:47 UTC, JackUait commented on packages/react-ui/lib/date/InternalDate.ts
> +    return components;
Поменял реализацию

2022-04-29 08:22 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +export class Select<TValue = unknown, TItem = unknown> extends React.Component<
Это не эквивалентная замена. У типа `{}` есть все свойства `Object` (например, `toString`),  и его можно присвоить к чему то другому с типом `{}` или `Record`. А с `unknown` так не получится. Если бы в Select не было проблем с  авто-выведением типа item (из-за propTypes), то такой пример бы сломался:
```jsx
<Select items={['one', 'two', 'three']} onValueChange={(e) => console.log(e.toString())} />
```
 Он и сейчас ломается, по другому. Непонятно что тут должно по хорошему быть, возможно `string`. Но это правка в любом случае ломающая. Пока все места, касающиеся публичного API стоит просто заигнорить.

2022-04-29 08:31 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
В таких местах можно не указывать типы для `React.Component`, потому что props не используется, а  для state хватает указания в `public state: ...`.

2022-04-29 09:56 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +export class Select<TValue = unknown, TItem = unknown> extends React.Component<
Насколько увидел, `Select` это единственное место где замена `{}` на `unknown` действительно сломает публичное поведение

Можно конечно ещё поспорить насчёт `isInstanceWithAnchorElement`, `isNode`, `isInternalDateValidateCheck`, `isInstanceWithRootNode` и других `is*`ов, но в данном случае `unknown` с точки зрения пользователя работает как `any`, как и в случае с `extends`

Для `Select` отключил правило и добавил поясняющий комментарий

2022-05-04 05:46 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
С `this.state` как раз все нормально. Это для аргументов `this.setState` почему-то тип не выводится. Но его там можно руками указать. Таких мест не много.

В любом случае, `unknown` на место пустых пропов не подходит. Там скорее должен быть какой-нибудь `EmptyObject`. Но лучше, мне кажется, было бы вообще в таких местах типы опустить, для краткости.

2022-05-04 11:18 UTC, JackUait commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
> Это для аргументов this.setState почему-то тип не выводится. Но его там можно руками указать.

Правильнее сказать, что второй аргумент используется как для `this.state` так и для `this.setState`.
Так, например, не отходя от примера выше можно привести ещё один: когда мы типизируем `public state` мы типизируем только содержимое объекта, но не сам стейт. В примере ниже я создаю новый тип `Test` с помощью которого типизирую стейт и в этом типе хранится правильный тип для `label` - `number`, при этом в типе `ComboBoxWithErrorTogglerState`, который используется во втором аргументе `React.Component` у `label` неправильный тип - `boolean`, и `TS` смотрим именно на тип во втором аргументе, из-за чего находит две ошибки, из чего можно сделать вывод, что стейт типизируется именно вторым аргументом: 

<img width="620" alt="Снимок экрана 2022-05-04 в 15 14 07" src="https://user-images.githubusercontent.com/48599460/166671038-4b20ae3d-7f06-4120-b7ce-b105c7d4b165.png">


Также не совсем пойму почему `unknown` не подходит на место пустого объекта, если мы используем этот тип просто как типизированную заглушку, то есть если мы попробуем обратиться к какому-нибудь пропу `TS` не разрешит нам это сделать:
<img width="193" alt="Снимок экрана 2022-05-04 в 15 10 12" src="https://user-images.githubusercontent.com/48599460/166670552-469b34db-ea86-4bb4-9b57-a7acba490c39.png">

2022-05-04 19:39 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
Ожидаемо, что явно переданный в аргумент тип побеждает тип, указанный свойству state. Но это не значит, что только тип через аргумент для this.state работает. Если опустить аргумент и указать только тип для свойства state, то this.state будет так же полноценно типизирован.

---

Потому что unknown это не пустой объект, а эквивалент any. А пропы - это всегда объект. Только благодаря [пересечению](https://npmfs.com/package/@types/react/17.0.44/react%20v17.0/index.d.ts#L497) `Readonly<P> & Readonly<{ children?: ... }>` внутри React.Component в твоем варианте у this.props будут законные свойства Object (toString, hasOwnProperty и тд). Но в типах react@18 этого пересечения [уже нет](https://npmfs.com/package/@types/react/18.0.8/react/index.d.ts#L490).

2022-05-04 20:49 UTC, JackUait commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
> ...у this.props будут законные свойства Object (toString, hasOwnProperty и тд)...

Да, но зачем они нам нужны, в пустом объекте?) Тип `Readonly<P>` ничего глобально не ломает, а приводить пустой объект к строке или проверять у него наличие какого-то свойства не вижу особого смысла

<hr/>

Вообще это не какой-то принципиальный момент связанный с "красотой кода" или чем-то подобным, так что удалил `unknown` во всех подобных местах и заменил его на объявление типов стейта прямо на объекте стейта

2022-05-06 05:50 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
Нам нужен корректный пустой объект, а не просто заглушка, которая работает. Мы же тут типы в порядок приводим.

2022-05-06 06:03 UTC, zhzz commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
> удалил unknown во всех подобных местах

Еще кое-где осталось.

2022-05-08 10:32 UTC, JackUait commented on packages/react-ui-validations/docs/Pages/Concepts/InlineValidations/InlineValidations.demo.tsx
> +export default class InlineValidationsDemo extends React.Component<unknown, State> {
> Мы же тут типы в порядок приводим.

В общем, меня эта фраза вдохновила и я поправил типы в принципе везде, где используется `React.Component`.

Что конкретно сделал:
1. Привёл объявление типов к единому виду: из `Component` в `React.Component`;
2. Помимо мест где использовался тип `unknown` задел также и места где использовался тип `any`, а также места где был тип `<any, any>`;
3. Вместо дублирования/пропуска типов у некоторых компонентов сделал наследование типов от базового компонента;
4. Вынес инлайн типы в собственные, полноценные типы;
5. Продублировал типы из второго аргумента `React.Component` в `public state` там где это нужно было;
6. Удалил весь стейт или часть стейта в тех компонентах, где он не использовался (например, в `TogglePlayground`); 
7. Удалил конструктор там, где можно было обойтись без него.

Я наверняка пропустил достаточно много мест, где эти правила можно было бы применить, но я пытался покрыть изменениями как можно бОльшую часть кодовой базы, через несколько итераций селф-ревью, надеюсь у меня это получилось)

Понятно, что сильно долго это не продержится, но по крайней мере бОльшая часть кодовой базы уже всегда будет с правильными типами

P.S. Изменения выше почти не затронули публичные компоненты, а в тех местах, где изменения всё-таки затронули публичные компонентов тщательно проверил, что обратная совместимость случайно не сломалась

P.P.S. Изменения описанные выше не затрагивали пакет `react-ui-testing`

2022-05-16 12:34 UTC, zhzz commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
Почему так лучше ( через `& Pick<...>`)? Стало сложнее читать и понимать, что в итоге за тип получается в `TokenInputStoryState`.

```ts
type TokenInputStoryState = {
  checked: boolean;
  selectedItems: TokenInputProps<string>['selectedItems'];
};
```

Так не лучше? А то и просто, через `string[]`.

2022-05-16 12:34 UTC, zhzz commented on packages/react-ui/.styleguide/components/Argument/ArgumentRenderer.tsx
> +  state: ErrorBoundaryState = { hasError: false };
Простые типы можно и вовсе не указывать, зачем? Они выведутся из присваиваемого значения точно такие же.

2022-05-16 12:34 UTC, zhzz commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  public state: UncontrolledAutocompleteState = {
Предлагаю выработать некоторый критерий для принятия решения о том, как в итоге должны выглядеть типы (инлайн/вынесены/указан/опущен), например:

`корректность > читаемость > лаконичность`

Корректность, естественно, на первом месте (тип должен быть правильным). Далее - читаемость, которая определяется количеством усилий, требуемом на понимание кода сторонним читателем. И последнее по значимости - лаконичность, т.е. краткость, компактность кода.

В итоге, такое соглашение поможет меньше думать и спорить при написании кода и рефакторинге.

Так, следуя моему критерию, в этом участке кода можно опустить тип стейта (лаконичность), а пропы передать в инлайн-форме (читаемость + лаконичность).

2022-05-16 14:56 UTC, JackUait commented on packages/react-ui-validations/docs/Common/Demo.tsx
> +};
Механизм `type` более гибкий чем `interface`. По сути `type` позволяет делать всё то же самое, что и `interface`, но `type` также позволяет делать `alias`'ы типов. Хочется, чтобы все объявления типов были написаны в едином синтаксисе, а так как `type` более гибкий, кажется что логичнее использовать именно его

Вот для сравнения `type` vs `interface` для создания типа с помощью `Pick` (на самом деле конструкцию с `interface` не пропустит линтер, но для примера сойдёт):
```ts
interface SomeInterface extends Pick<InputProps, 'leftIcon'> {}

type SomeType = Pick<InputProps, 'leftIcon'>
```

2022-05-16 15:11 UTC, JackUait commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
Да, вариант из сниппета с переименованием выглядит читабельнее)

Насчёт `string[]` -  мы не будем придерживаться `DRY` в таком случае и потенциально это приведёт к ложно-позитивным тестам

2022-05-16 19:32 UTC, JackUait commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  public state: UncontrolledAutocompleteState = {
> `корректность > читаемость > лаконичность`

Звучит разумно, нужно вынести эту информацию под какую-то ссылку в "гайде для контрибуторов", чтобы на неё можно было оттуда ссылаться

> можно опустить тип стейта (лаконичность)

Тут согласен, в историях он ни к чему

> пропы передать в инлайн-форме (читаемость + лаконичность)

Тут согласен, с тем, что это будет лаконичнее, но не согласен с тем, что от этого повысится читаемость
```tsx
class Component extends React.Component<Partial<ComponentProps>, Pick<ComponentProps, 'value'>>
```
```tsx
type ComponentProps = Partial<AutocompleteProps>;
type ComponentState = Pick<AutocompleteProps, 'value'>;
class Component extends React.Component<ComponentProps, ComponentState>
```
В инлайн-записи слишком много ёлочек, из-за чего такую запись становится очень сложно читать, особенно, если в оба аргумента `React.Component` передаются вложенные параметры (как в `Pick<AutocompleteProps, 'value'>`), а если туда ещё и много вложенных параметров передаётся, из-за местного форматирования такая запись превращается в небольшой адок для восприятия (поэтому я и начал выносить стейт/пропы в отдельные типы), так как текст просто съезжает на новую строчку, а не разбивается на четыре строчки

2022-05-16 22:00 UTC, JackUait commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
Если речь о всей историей с использованием `Pick` (а не только о случаях где нужны дженерики), то она оправдывается правильностью типа и `DRY`. Если писать переименования во всех местах, где можно просто заиспользовать `Pick` мы после двух-трёх переименований полей одного типа начнём тонуть в пучине объявлений, что с моей точки зрения гораздо сильнее испортит читаемость кода, чем `Pick`

2022-05-16 22:07 UTC, JackUait commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
В варианте с `Pick` мы именно забираем тип из объекта, в случае с переименованием мы этот тип пересоздаём, так, например, если тип будет опциональным мы пересоздадим его как обязательный. То есть для полноценного воспроизведения типа через переименование нам нужно будет нарушать `DRY`

Насчёт `string[]` - тут мы также не будем придерживаться `DRY`, что потенциально это приведёт к ложно-позитивным тестам

2022-05-18 13:14 UTC, zhzz commented on packages/react-ui-validations/docs/Common/Demo.tsx
> +};
Под "гибкий" ты подразумеваешь "удобный" для создания алиасов объектов. Это довольно частный случай, и `type` там выглядит лучше. Интерфейсы не предназначены для алиасов вообще. Зато в общем случае они лучше справляются с описанием объектов, в силу нескольких отличий:

1. у них описательнее сообщения об ошибках (пример [тут](https://www.typescriptlang.org/play?#code/PTAEBUAsFMCdtAQ3qALgdwPagLaIJYB2ammANgM4mgAm0AxmcgqjKBZIgA4KYBmSQgFgAUCFCYARgCsGqAFygiqOH0T1oVRIRpoAnjyRl8iCpoB0okFbBRoepCgBucBxXw58TWABpBuvkxYNDYcTApUUHpMHDDielNNGyR6SNYECkQcaEsRUVQDBAAhfFgacELQAF5QAG9RUFB0IgBzCkUAJgBuUQBfHryRZVV1YtKaAElCFVg1DTqGptb20G6+0VFowgjQSXGARkUSsorDGtqlwjbO0H7NzG3IvbKOo-GpmbmEc8vr1duBskigxEABXMwQQoAZXosHwXEi+C07FQsFBqVBsEQZH0hgoegi0BwPmS+FQAHIqFxwu5JGQWNhhrBPAAPELQUqgcEMzC5e6PXbjADMbzKHxG8xqzxo+0BYlsMAckkwrHYoK41NgkWgLJUOlaEnSwSZXy0OlxFmSpwQ2JMZioNGwrCRoCcJiU0zgZlS+AeFoofnQkC80FJntmoyonBcSFAAGt7FgynyRAVDAB5dA4n6ETAY2CEbGKVGghC9UAAMlAx3KhQGaYQACUpERqnVQLn84WyIo1JQy5Xq+9w185SbRqAAArQdR5uOgHV6mhUGvWhYiRrRMiYTF8UE9tBo6ADRp8YyaXvYswDXqicfzADCwfoCeIi+gOhXw8+E-qG6i5A7rM+6Xv2J6gGe+AXhBV7Husgz0pEmBZoombZu2zRXCsHR+J2qCYt2xZHgCoiIVEz6vooT74C+H5thcmF-DhAHbruIEwf2fiQdBfYQncgziFAiCRJk+A0IGCDwNEsQfroeg7lyEL3poEguMEDbJLaiQUOYoBQjw9D4HwNHYmQeh+JIILcqA8mgksZA4i00BPM5MwLrAsBBMk2QUJkTk6aAEwCLZoCQJgamqXA7IQeQ26Me5nmwAGNkKQkwjyuw0AIGF6CQjwMJwgiUTaKAXCeW6dBoF6UXaLoYQoIE9DcjQ3maH5KlBnRSZxgazSqspVDGAmoDUbRhApsh6H0BRH4DNNNGvm2k1yuI6aEAgeDSEEtBGXwcAfvMlkYFlxANkYdoqU4VADZpKCsMJHo-hoWgoJgPDELVFrndpjgIIw4TQDQuSCcGVDZNoVAhWlC66rJgiPRKCCSA4dCMMgBpkppmVbLoqAeDkGxDCOE4ANJknq66NFwmJJYoyrkDOhA3oTymgGTqAU3+m6AZiigRHCVzMwJYBTNFKowMECQQogX1pbmLnkdoTm6DuqDuJV-CkmrtAMN4wm+uNhNnZO6pcA45yLFuQR86irQ3nKxum+blMkASiiEKCOCWbA9uE+IAAi0DvTQBp+rZwQtJgV5+M6Dq7fthDzNE+66JZSDJNS7h4zG20y+tLT6y4ukABLIdAEWBME1N0jRZkw5ngPJA2yVkpSsZHW5CQOdQeDDekODw8pKaretEgCOkuyaJE8AUEBz0xcEZgclcRg4vw0WA05yRSypyA7uazeutdxPPTHoMouo87haocVN5A8CILoLoy5HmC6FwTDzKg2ARMgCh+2ASAHMuDtBAL-F819ZhxXMNJYAABHUsEQDYUGAEKAA7B0IU6ChQAFZgDN1hPCVAABaAaxCrrEObsAHBHQABsAAODoTCAAMABiGhDCmEdGYaIIAA), строки 48-49)
2. синтаксис расширения других объектов через `extends` подсказывает о конфликтующих полях с несовместимыми типами, в отличии от синтаксиса пересечения через `&`, который молча поставит такому полю тип `never`, и ты об этом можешь не узнать (пример [тут](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKgjFAvFA3gKCpqBDAXFAZ2ACcBLAOwHMBuNAXzTVElgCYlUMs8pyBXALYAjCMVoMm4aDADMHeFABkbJaigB6dbwD2UUcW3EumIfiHbtAGwjZy42mgrBRAM2wBjaAEk5EAB7O5AAmBLBwADQqKBpa+obGUKaJFta24oz+YIbAUMzQAIIIyLIA2gDk2GUAutQxvBAAbqKRbqTEuVKJfDkEpNbkOSIAFtgNpPGZ2R0s+ezIPuWVNXVEZFSRAI58EETj5NhC1tPQQt1QAO7QANbk2uc45mfAQ9BgBocQAkA)) 
3. не очень существенно для нас, но, возможно нужно для внешних пользователей: `type` не поддерживает [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) 

Так что `type` не совсем поддерживает все то же самое, что `interface`. Вероятно, поэтому именно `interface` часто используют и рекомендуют по умолчанию для объектов, а `type` для более сложных типов ([handbook](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces), [react types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts)).

Думаю, чтобы все объявления типов были написаны в едином синтаксисе, не так существенно. Разумно придерживаться рекомендации из официальной документации: использовать `interface` пока не понадобились фичи `type`. Применять оба синтаксиса не так эстетично, конечно, но и не очень вредно, покуда есть объективные причины. Тем более, что у нас уже в основном используется `interface`.

И все таки, без eslint-правил единый синтаксис долго не живет.

2022-05-18 13:38 UTC, JackUait commented on packages/react-ui-validations/docs/Common/Demo.tsx
> +};
Окей, получается что для объектов лучше использовать `interface`. В линте есть [правило](https://typescript-eslint.io/rules/consistent-type-definitions/) на такой случай, оно позволяет принуждать пользователей писать интерфейсы везде, где они нужны и `type` во всех остальных случаях

За такое подробное описание почему `type` не полностью "перебивает" `interface` - спасибо, пойду глубже вникать)

2022-05-19 06:29 UTC, zhzz commented on packages/react-ui-validations/docs/Common/Demo.tsx
> +};
Хорошее правило

2022-05-19 07:43 UTC, zhzz commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
Про опциональный тип справедливо. Про переименование не понял, почему ты так это называешь.

Но в любом случае, это не существенно здесь. История - это отдельный, внешний по отношению к нашему, компонент (как, например, пользовательский компонент или тест). Тут нет нужды следовать принципам DRY, потому что ее стейт это отдельная сущность, связанная с пропами нашего компонента лишь тем, что они должны быть совместимы. Если ты меняешь тип в нашем компоненте, то во внешнем коде его неизбежно приходится также обновлять, это нормально.

Тут важнее то, что при твоем подходе без заглядывания в несвязанный, по сути, компонет, сложно понять, что за тип у стейта истории. С этой точки зрения, `string[]` лучше.

Про ложно-позитивные тесты не понял. Можно пример?

2022-05-19 07:52 UTC, zhzz commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  public state: UncontrolledAutocompleteState = {
Согласен про нечитаемость больших инлайн-типов и скобочек. 

Тут я имел в виду то, что если не передавать вторым аргументом фактически ненужный ComponentState, то там останется лишь `React.Component<Partial<ComponentProps>>`, который уже довольно прост.

2022-05-19 22:32 UTC, JackUait commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
> Если ты меняешь тип в нашем компоненте, то во внешнем коде его неизбежно приходится также обновлять, это нормально

Не совсем понимаю почему это "неизбежно", если `Pick` позволяет забирать необходимый тип и менять только входные данные, если есть такая необходимость. При этом, с забором типа у нас не будет происходить рассинхрона типов в отличие от переопределения типа. Оперируя твоей "шкалой приоритета типизации" (`корректность > читаемость > лаконичность`) можно прийти к выводу о том, что в данном случае, нам стоит пожертвовать читаемостью кода в угоду корректности типа. Считаю, что правильные типы в тестах не менее важны, чем правильные типы в публичных компонентах, так как неправильные типы могут порождать "ложно-позитивные" тесты, а "ложно-позитивные" тесты могут в свою очередь порождать баги

> Про ложно-позитивные тесты не понял. Можно пример?

Если сводить ложно-позитивные тесты к термину, то получится что-то вроде: _Ложно-позитивные тесты - это тесты, которые возвращают правильный результат с неправильным (или не ожидаемым программой) типом входных данных_

Под ложно-позитивными тестами в нашем случае я понимаю скриншотные тесты, которые правильно отрабатывают, но только из-за допущения в типах

То есть, предположим, что у нас есть история с полем в типах `something: any`, но на самом деле, в компоненте у этого поля тип `something: string`. В самом компоненте, мы берём длину строки `something`, проходимся по всем её буквам и производим какие-то преобразования с ними, затем каждую букву помещаем в новую строку. Теперь, представим, что в истории вместо строки в компонент передаётся массив строк, мы сможем произвести с ним все те же самые преобразования что и со строкой. В итоге, у нас получится, что тест полностью проходит и в тесте даже может выводиться необходимый результат (то есть, в данном случае есть сценарий, в котором визуально этот недочёт можно будет не заметить)

Теперь представим, что внутри компонента поменялась реализация этой логики и вместо того, чтобы сразу проходиться по строке она сначала тримится, чтобы убрать лишние пробелы - все тесты завязанные на допущение в типах упали и разработчику пришлось дебажить код, а ревьюеру разбираться почему были переписаны тесты и всё такое. В общем из-за такого маленького допущения в типах сломалось какое-то количество тестов и пришлось потратить какое-то количество человеко-часов на то, чтобы разобраться в проблеме, которые потенциально могли бы уйти на решение более важных задач

Поэтому, я считаю вариант с переписыванием типа, без взятия его из родительского компонента несостоятельным в том числе и для историй

2022-05-19 22:53 UTC, JackUait commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  public state: UncontrolledAutocompleteState = {
Но мы же в основном передаем поля из стейта ниже в компонент, следовательно у стейта должен быть определённый тип (основываясь на размышлениях из комментариев выше)

2022-05-20 09:50 UTC, zhzz commented on packages/react-ui-validations/stories/TokenInput.stories.tsx
> +} & Pick<TokenInputProps<string>, 'selectedItems'>;
> почему это "неизбежно", (...) менять только входные данные

Потому и неизбежно, что данные все равно менять. От того, что ты заберешь тип и его менять не придется, ты сэкономишь немножко при рефакторинге, но будешь значительно терять в читаемости все остальное время. 

Это справедливо именно для "внешнего" кода, про который я писал, и к которому отношу истории. История - она как продуктовый код, использует внутри наш компонент, но реализует какой-то свой бизнес-функционал. 

Например, взять форму где-нибудь на странице Экстерна. Там поле для ввода массива активных пользователей. Используется TokenInput. Данные хранятся в стейте. Как лучше типизировать стейт? В каком варианте понятнее тип `FormState` для того, кто читает код впервые?

```tsx
import { TokenInputProps } from '@skbkontur/react-ui';

type User = string;

type FormState = Pick<TokenInputProps<User>, 'selectedItems'>;

class Form extends React.Component {
  state: FormState = {
    selectedItems: [],
  };

  render() {
    <TokenInput selectedItems={this.state.selectedItems} />;
  }
}
```
vs
```tsx
type User = string;

type FormState = {
  activeUsers: User[];
};

class Form extends React.Component {
  state: FormState = {
    selectedItems: [],
  };

  render() {
    <TokenInput selectedItems={this.state.activeUsers} />;
  }
}
```

А если таких полей в форме будет несколько? 

А что, если `TokenInput` решат заменить на `<select multiple />`? Менять `FormState`? Но ведь тип данных не поменялся. Поэтому и говорю, что стейт внешнего компонента это отдельная, не связанная с пропом контрола сущность. И DRY тут не уместен.

Все это к тому, что я считаю, что это же относится к историям и к тестам. Это внешний код. DRY там не нужен.

---
Про правильность типов.

Про правильность типов я не спорю. Они должны быть правильными везде. 

Я говорю не про 

```
TokenInputProps<string>['selectedItems'] vs any[]
```

я говорю про

```
TokenInputProps<string>['selectedItems'] vs string[]
```
---

Про ложно-позитивные тесты.

Ты привел пример про `any`. Это безусловное зло. Но речь шла про конкретный пример с `string[]`.

2022-05-20 10:01 UTC, zhzz commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  public state: UncontrolledAutocompleteState = {
Тип выведется сам в месте определения поля state из переданного значения. В более сложных случаях можно указывать его руками там же. В еще более сложных - передавать аргументом в `React.Component`. Это в порядке уменьшения лаконичности.

2022-06-23 19:54 UTC, zhzz requested changes

2022-06-23 19:54 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/ResponsiveLayoutEvents.ts
> +  return eventListener?.mql.matches;
Поменялся тип возвращаемого из `checkMathes` значения. Больше вопросов нет.

2022-06-29 06:47 UTC, zhzz requested changes

2022-06-29 06:47 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/ResponsiveLayoutEvents.ts
> +  return eventListener?.mql.matches;
Поменялся тип возвращаемого значения. Больше вопросов нет.

---

Уже писал этот коммент, но видимо потом случайно удалил.

2022-06-29 11:06 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/ResponsiveLayoutEvents.ts
> +  return eventListener?.mql.matches;
Нет, она не могла вернуть `undefined`, т.к. выше проверка на существование этого значения в Map. Это несовершенство типизации Map вынуждало там делать `!`.

2022-07-10 19:47 UTC, zhzz approved these changes

2022-08-12 09:49 UTC, zhzz approved these changes

2022-08-15 06:46 UTC, zhzz approved these changes

2022-08-15 06:47 UTC, merged