Replace getBoundingClientRect with getDOMRect
skbkontur/retail-ui pull request #2815
Opened 2022-02-24 04:26 UTC by HelenaIsh

2022-02-25 09:14 UTC, JackUait requested changes
Ошибку в `Sticky` не удалось воспроизвести, скорее всего ты просто импортировала `getDOMRect` из `react-ui/lib/dom/getDOMRect`, а не из `../../../lib/dom/getDOMRect`

2022-02-28 23:14 UTC, JackUait commented
@zhzz Почему-то в скриншотных тестах при импорте `getDOMRect` падает ошибка `Error from JavaScript: '_getDOMRect' is undefined`.

Это баг в `Creevey`?

2022-03-01 07:55 UTC, zhzz commented
> @zhzz Почему-то в скриншотных тестах при импорте `getDOMRect` падает ошибка `Error from JavaScript: '_getDOMRect' is undefined`.
> 
> Это баг в `Creevey`?

Нет, функции внутри `this.browser.executeScript` выполняются изолированно селениумом внутри браузеров. У них там уже другая лексическая область видимости и нет доступа к сущностям, объявленным вне ее.

2022-03-01 08:00 UTC, zhzz commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> +import { getDOMRect } from '@skbkontur/react-ui/lib/dom/getDOMRect';
Нельзя использовать в валидациях новые штуки из react-ui, иначе сломается совместимость со старыми версиями контролов. Мы пока держим текущие валидации совместимыми с контролами >=0.53.7

2022-03-01 16:42 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
>    };
Здесь больше не нужна функция. Можно просто вызывать `getDOMRect` в нужном месте.

2022-03-01 16:42 UTC, JackUait commented
Появился конфликт с базовой веткой.

2022-03-02 09:17 UTC, JackUait approved these changes

2022-04-01 09:47 UTC, zhzz requested changes

2022-04-01 09:47 UTC, zhzz commented on packages/react-ui/internal/DropdownContainer/DropdownContainer.tsx
> +    };
А тут не поменялась логика при невыполнении старого условия `target && this.isElement(target)`?

И до второго `return` дело никогда не дойдет.

2022-04-04 07:05 UTC, HelenaIsh commented on packages/react-ui/internal/DropdownContainer/DropdownContainer.tsx
> +    };
да, ты прав. Вернула прежнюю логику

2022-04-18 06:08 UTC, zhzz approved these changes

2022-04-18 07:15 UTC, merged