chore(SidePage): add enableScroll prop
skbkontur/retail-ui pull request #2821
Opened 2022-03-01 08:26 UTC by HelenaIsh

2022-03-02 10:46 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +  enableScroll?: boolean;
Так делать не стоит. Получается что мы прячем фикс бага под флаг. По сути предлагаем пользователю выбрать какой баг оставить, а с каким можно жить =)

Надо научить `SidePage` понимать, что внутри него находится `ScrollContainer`. И не блокировать скролл, когда мышка над ним.

Например, можно добавить дата-атрибут HTML-элементу `ScrollContainer`'а. А в `SidePage` добавить слушателей на этот элемент (если он есть внутри `SidePage`'а).
Т.е. при событии `mouseenter` выключать "блокировку" скролла, и при `mouseleave`, опять блокировать.

---

Можно ещё научить `ScrollContainer` поджигать кастомные js события ([CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent)), со своим именем, типа `react-ui-scroll`. Внутри события можно будет передавать `scrollState`.
Что-то такое - [Talk to your React components with custom events](https://www.falldowngoboone.com/blog/talk-to-your-react-components-with-custom-events/).
Но это сложнее, и сейчас можно не заморачивать.

2022-03-03 05:07 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.tsx
> +  enableScroll?: boolean;
Такое решение подходит только для `ScrollContainer`, но если внутри `SidePage` будет другой компонент со скроллом - он также сломается. 

> Т.е. при событии `mouseenter` выключать "блокировку" скролла, и при `mouseleave`, опять блокировать.

Тогда сама страничка тоже будет прокручиваться, а мы как раз от этого избавлялись. Предлагаю также как со SidePage - проверять есть ли возможность скроллить `ScrollContainer`, если нет - блокировать скролл.

2022-03-03 22:54 UTC, JackUait requested changes

2022-03-03 22:54 UTC, JackUait commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    }
Вынеси пожалуйста эту логику в функцию.

Сейчас логика получения `scrollContainerScrollAvailable` мешается с остальной логикой из-за чего код превращается в вермишель, а также в текущей реализации мутируется переменная `scrollContainerScrollAvailable`, что добавляет неопределённости коду.

В функции достаточно возвращать результат вычисления с 235-ой строки и `false` в случае невыполнения условия:
```ts
const foo = () => {
	if (...) {
		return 235
	}

	return false
}
```

2022-03-03 22:54 UTC, JackUait commented on packages/react-ui/components/SidePage/SidePage.tsx
> +        scrollContainer.scrollTop >= scrollContainer.scrollHeight - scrollContainer.clientHeight && e.deltaY > 0;
Эти два вычисления также стоит вынести в отдельные функции, а внутри функций дать описательные названия левой и правой частям операндов:
```ts
const getScrollContainerReachedTop = (scrollContainer, e) => {
	const leftOperandDescriptiveName = ...
	const rightOperandDescriptiveName = ...

	return leftOperandDescriptiveName && rightOperandDescriptiveName
}
```

2022-04-01 11:05 UTC, JackUait submitted a review, later dismissed

2022-04-01 11:35 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    if (!this.props.blockBackground && !scrollAvailable && !scrollContainerScrollAvailable) {
Здесь код полностью дублируется из метода `checkScrollContainerScrollAvailability()`.

```suggestion
    const scrollAvailable = this.checkScrollContainerScrollAvailability(layout, scrollingUp);
    if (!this.props.blockBackground && !scrollAvailable) {
```

2022-04-01 11:58 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    if (!this.props.blockBackground && !scrollAvailable && !scrollContainerScrollAvailable) {
Нет, это разное. Функция scrollContainerScrollAvailable проверяет возможность скролла для скрол контейнера. Строчки 231-233 проверяют возможность скролла для самой sidePage. Например, проверь с таким кодом:

import { Button } from '@skbkontur/react-ui';

const [opened, setOpened] = React.useState(false);

function renderSidePage() {
  return (
    <SidePage onClose={close} blockBackground>
      <SidePage.Header>Title</SidePage.Header>
      <SidePage.Body>
        <div
          style={{
            background: `repeating-linear-gradient(
                          60deg,
                          #fafafa,
                          #fafafa 20px,
                          #dfdede 20px,
                          #dfdede 40px
                        )`,
            height: 6000,
            padding: '20px 0',
          }}
        >
          <SidePage.Container>
            <p>Use rxjs operators with react hooks</p>
          </SidePage.Container>
        </div>
      </SidePage.Body>
      <SidePage.Footer panel>
        <Button onClick={close}>Close</Button>
      </SidePage.Footer>
    </SidePage>
  );
}

function open() {
  setOpened(true);
}

function close() {
  setOpened(false);
}

<div>
  {opened && renderSidePage()}
  <Button onClick={open}>Open</Button>
</div>;

2022-04-01 12:07 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    if (!this.props.blockBackground && !scrollAvailable && !scrollContainerScrollAvailable) {
Угу. Код всё равно дублируется. Стоит вынести выборку `querySelector` выше.

2022-04-04 05:56 UTC, lossir approved these changes

2022-04-22 09:44 UTC, zhzz requested changes

2022-04-22 09:44 UTC, zhzz commented on packages/react-ui/components/SidePage/SidePage.tsx
> +    const scrollContainer = layout.querySelector("[data-tid='ScrollContainer__inner']");
Лена верно писала, что это решение не сработает для других элементов со скролом, которые могут быть внутри SidePage (например, `<textarea />` с большим текстом, или любая другая прокручиваемая область с нативным скролбаром). Мы не контролируем содержимое `SidePage` и таким образом не сможем всего предусмотреть.

К тому же, `ScrollContainer` может не только оборачивать все содержимое, как в примере, но и быть внутри дропдаунов, селектов, меню. Их может быть несколько с разным состоянием прокрутки. Все это может работать не как ожидается.

Лучше сейчас откатить #2756, как не очень критичную правку, и поискать другое решение.

2022-04-25 06:01 UTC, zhzz commented
Откатываем 2756, этот закрываем.

2022-04-25 06:01 UTC, closed without merging