New theme 2022
skbkontur/retail-ui pull request #2853
Opened 2022-04-02 11:46 UTC by khlutkova

2022-04-11 19:13 UTC, JackUait commented
Скриншоты для `Switcher`'а и `Toggle`'а поехали куда-то не туда. А из-за них упала ещё куча скриншотов)

2022-04-12 11:38 UTC, JackUait commented
Теперь линтинг падает из-за `Prettier`'а (`theme2022.ts`):

<img width="707" alt="Снимок экрана 2022-04-12 в 14 37 09" src="https://user-images.githubusercontent.com/48599460/162951709-2ba4dd0a-310e-4375-a049-486ee7a54420.png">

2022-04-12 20:25 UTC, JackUait commented
Аня, добавляй пожалуйста описание к пулл-реквесту, пожалуйста) 🙏

2022-04-12 22:14 UTC, JackUait requested changes

2022-04-12 22:14 UTC, JackUait commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static btnPaddingXSmall = '11px';
Это отступ слева для [кнопок с иконками](https://www.figma.com/file/87ScqxPzJpF9DcVBNYWOjM/%F0%9F%9A%A7-Kontur-UI-Modern-Layout?node-id=200%3A4075). У [маленьких кнопок без иконок](https://www.figma.com/file/87ScqxPzJpF9DcVBNYWOjM/%F0%9F%9A%A7-Kontur-UI-Modern-Layout?node-id=200%3A3650) горизонтальный отступ `12px`.

Кстати, у кнопок с иконками отступы сейчас подтягиваются из дефолтной темы.

2022-04-12 22:14 UTC, JackUait commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static btnIconGapLarge = '8px';
Нет гэпа для маленьких кнопок. Гэпы для средних и больших кнопок не совпадают с фигмой.

2022-04-22 09:21 UTC, khlutkova commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static btnBorderRadiusSmall = '8px';
в фигме закралась ошибочка, у всех маленьких иконок скругление по 8px

2022-04-25 23:06 UTC, JackUait requested changes

2022-04-25 23:06 UTC, JackUait commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static fileUploaderLinkHoverTextDecoration = 'none';
Кажется, что `linkHoverTextDecoration` сразу стоит вынести в отдельную переменную, так как по идее у любых ссылок больше не будет подчёркивания, если я всё правильно понял

2022-04-25 23:06 UTC, JackUait commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static radioBulletSize = '6px';
А здесь нам не нужно учитывать различные размеры радио-кнопок?

2022-04-25 23:06 UTC, JackUait commented on packages/react-ui/internal/themes/Theme2022.ts
> +  }
По идее если сделать такую запись:
```suggestion
/**
* @deprecated
*/
public static get dropdownMenuHoverBg() {
  return this.bgDisabled;
}
```
У пользователей это свойство будет отображаться зачёркнутым. Если дипрекейтед именно `bgDisabled`, то можно ему добавить такой комментарий)

2022-04-26 06:17 UTC, closed without merging

2022-04-26 13:29 UTC, dzekh commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static radioBulletSize = '6px';
нет, у нас нет размеров у радиокнопок, нет пропа сайз

2022-04-26 13:29 UTC, dzekh commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static fileUploaderLinkHoverTextDecoration = 'none';
да, у ссылок не будет подчеркивания

2022-04-26 13:30 UTC, dzekh commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static menuItemCommentColor = '#858585';
Предлагаю попозже с этим поразбираться

2022-04-26 13:34 UTC, dzekh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static tokenInputBorderRadius = '0px';
По хорошему да, все инпуты должны иметь один радиус скругления и смотреть на одну переменную. Но можно это позже сделать. Сейчас у токенинпута скругление норм, как должно быть.

2022-04-26 13:37 UTC, dzekh commented on packages/react-ui/components/Modal/Modal.styles.ts
> +      border-radius: 0 0 ${t.modalBorderRadius} ${t.modalBorderRadius};
Там сейчас всё хорошо в светлой теме. Можно разобраться позже со скруглениями этими, если они будут мешать.