feat(Select): theme token for Select menu border-radius
skbkontur/retail-ui pull request #2864
Opened 2022-04-14 10:10 UTC by JackUait

Добавил в стили `Select`'а токен для задания `border-radius`.
Также добавил возможность прокидывать `CommonProps` в `Menu`, так как это нужно было для решения задачи.

2022-04-21 11:23 UTC, khlutkova approved these changes

2022-04-25 09:00 UTC, zhzz requested changes

2022-04-25 09:00 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.styles.ts
> +      border-radius: ${t.menuBorderRadius};
У нас есть еще компоненты на основе `InternalMenu` (это DropdownMenu, Kebab, TooltipMenu). Думаю, в нем тоже стоит эту переменную заиспользовать.

2022-04-26 09:09 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.styles.ts
> +      border-radius: ${t.menuBorderRadius};
Для `DropdownMenu`, `Kebab` и `TooltipMenu` есть отдельная переменная `popupBorderRadius`

2022-04-26 10:19 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.styles.ts
> +      border-radius: ${t.menuBorderRadius};
Да, но Popup внутренний, его переменные по идее тоже. Мы для многих публичных компонентов создаем аналоги переменных попапа.

![image](https://user-images.githubusercontent.com/4607770/165277516-50f947f2-696f-4fe8-9c9b-d1f4c08871a4.png)

Т.к. пользователю нет дела до того, какое меню используется внутри, обычное Menu или InternalMenu, логично было бы предоставить одну переменную для них. Или отдельную для каждого из публичных компонентов. 

Но оказывается, что у Menu и PopupMenu сейчас разные значения радиуса. Поэтому одну переменную использовать не получится без изменения скриншотов. Тогда можно оставить так, до объединения всех меню и выпадашек.

2022-04-26 10:19 UTC, zhzz approved these changes

2022-04-27 03:46 UTC, merged