fix: allow CurrencyInput work with string value
skbkontur/retail-ui pull request #2885
Opened 2022-04-29 10:25 UTC by khlutkova

2022-05-08 11:04 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      CurrencyHelper.parse(`${value}`) !== CurrencyHelper.parse(prevState.formatted) ||
```suggestion
      CurrencyHelper.parse(value?.toString() ?? '') !== CurrencyHelper.parse(prevState.formatted) ||
```

Кажется, что с такой реализацией могут возникнуть проблемы, так как она преобразует `null` и `undefined` в строки:
<img width="152" alt="Снимок экрана 2022-05-08 в 15 01 33" src="https://user-images.githubusercontent.com/48599460/167293164-945970b0-1acc-4947-b097-12c61f3d0adb.png">

Думаю, что тут лучше использовать `value?.toString() ?? ''`, так как `toString()` будет преобразовывать `null` и `undefined` в `null`:
<img width="183" alt="Снимок экрана 2022-05-08 в 15 02 39" src="https://user-images.githubusercontent.com/48599460/167293215-9896132e-bb47-4a80-8439-058c10bfb43b.png">

2022-05-08 11:09 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +WithStringValue.storyName = 'With String Value';
Линтер ругается на эту строчку

2022-05-08 11:13 UTC, JackUait requested changes

2022-05-08 11:13 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
Я бы ещё подумал над тем, можно ли здесь как-нибудь обойтись без `any`, чтобы в будущем (#2856) пришлось меньше мест с `any` глушить

2022-05-31 14:17 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
Лена (@HelenaIsh), а с этим ты что-то пробовала делать?

2022-05-31 14:23 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> -WithStringValue.storyName = 'With String Value';
Насколько вижу, в библиотеке принято две записи названия историй:
```ts
WithStringValue.storyName = 'with string value';  // Все буквы маленькие
WithStringValue.storyName = 'With string value'; // Только первая буква в названии заглавная
```

Не знаю, есть ли в этом какой-то сакральный смысл или это просто исторически так сложилось, но предлагаю придерживаться конвенции

2022-05-31 14:37 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +export const WithStringValue: Story = () => {
Думаю, что дополнительно к скриншотным тестам ещё стоит написать и интеграционные

2022-05-31 15:23 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
Думаю, что тут можно просто отключить это правило и написать, что всё нормально, так и было запланировано в рамках теста:
```ts
// Intended behavior. CurrencyInput technically can't accept strings
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const [value, changeValue] = React.useState<any>('');
```

Либо, так как мы теперь умеем обрабатывать строки можно расширить тип `value` в пропах до:
```ts
value: Nullable<number | string>;
```
По идее, это ничего не должно сломать для пользователей + мы официально говорим, что `CurrencyInput` теперь поддерживает строки, так что я за этот вариант, но нужно смотреть не сломает ли это что-то внутри самого `CurrencyInput` и какой кейс мы пытаемся покрыть этим фиксом

Судя по сообщению из [чата](https://kontur.slack.com/archives/C013HTCE18Q/p1651206042773839):
> У нас в некоторых местах в `CurrencyInput` может прийти строка вместо числа, знаю что это очень не очень, но так получилось.

У пользователей есть кейс, когда они передают/вынуждены передавать строки  в `CurrencyInput` и если сейчас это ограничение на уровне: "мы ожидаем там цифры, а не строки", то предлагаю добавить официальную поддержку строк в этот проп. Егор (@zhzz), Максим (@lossir), что думаете по этому поводу?

2022-06-07 09:30 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      CurrencyHelper.parse(value?.toString() ?? '') !== CurrencyHelper.parse(prevState.formatted) ||
Выглядит действительно продвинуто 🚀

Варнинг да, стоит кидать в консоль.

В целом, не вижу проблемы с пустой строкой. Пример с разным их кол-вом кажется синтетическим - в жизни я с таким не сталкивался. Но почему бы не перестраховаться =)

2022-06-07 09:38 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      CurrencyHelper.parse(value?.toString() ?? '') !== CurrencyHelper.parse(prevState.formatted) ||
@lossir Максим, а по поводу вопроса нужно ли расширять тип пропа `value` до `number | string`? Или это ломающее изменение?

2022-06-07 10:21 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      CurrencyHelper.parse(value?.toString() ?? '') !== CurrencyHelper.parse(prevState.formatted) ||
Да, тип `value` нужно расширить до `number | string`.
Нет, это не ломающее изменение. Те, кто передавал только `number` ничего не заметят. Ну, вернее отрефакторить надо так, чтобы они ничего не заметили.

2022-06-07 12:15 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      CurrencyHelper.parse(value?.toString() ?? '') !== CurrencyHelper.parse(prevState.formatted) ||
Думаю, в доке в проп `value` надо будет добавить, что под типом `string` мы-таки ожидаем валидное число.

2022-06-15 08:31 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
`CurrencyInput` - это компонент для ввода денежных сумм с красивым форматированием. Как по мне, у него сейчас строгое и чистое api. Он оперирует только числами (что логично), принимает, форматирует и возвращает. Строками ему оперировать незачем, кроме как немного сгладить DX.  

Расширение типа `value` на строку лишь избавляет пользователя от необходимости делать `<CurrencyInput value={parseFloat(stringValue)} />`, если у него валидная строка. Если строка потенциально может быть невалидной, то пользователю все равно нужно самому приводить ее к `number`.

Насколько расширение типа улучшит DX - непонятно. Учитывая, что таких запросов от пользователей не было. Автор сообщения в чате выразил понимание, что он использует компонент неправильно, и просил лишь восстановить прежнюю работоспособность.

Зато, это расширение смазывает строгость и определенность api: 
  - компонент принимает строку, но в `onValueChange` возвращает `number`?
  - добавляется скрытая логика обработки невалидных строк 
  - компонент начинает делать несвойственную ему работу по переводу строки в число

К тому же, не так просто определить, что означает валидная строка. "Валидное число в виде строки" - это не стандартизированное понятие. Примеры ниже, по идее, могут считаться валидными:
```js
(1000000).toLocaleString()
'1,000,000'
(1000000).toLocaleString('pl-PL')
'1 000 000'
(1000000).toLocaleString('ar-EG')
'١٬٠٠٠٬٠٠٠'
(1000000).toExponential()
'1e+6'
```
Последний, с экспонентой, работает с `parseFloat`, но не заработает в `CurrencyInput`.

Как по мне, неопределенности от расширения типа больше, чем пользы.

2022-06-15 12:27 UTC, lossir commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
Если `Number(str)` возвращает `number`, то это "Валидное число в виде строки".
Получить такую строку из числа можно только методом `Number.toString()`.

Примеры, что ты приводишь можно отнести ко второму варианту [отсюда](https://github.com/skbkontur/retail-ui/pull/2885#discussion_r890151638). Их я предлагаю не считать валидными. (кроме `toExponential()`, он возвращает вполне валидное число)

Но касательно чистого API компонента - замечание резонное. Надо принять решение =)

2022-06-16 05:01 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +  const [value, changeValue] = React.useState<any>('');
Окей, согласен, мы действительно потратим в десятки раз больше времени на поддержку этого `API`, чем все вместе взятые пользователи потратят на приведение их строк к числу

Я соглашусь с первыми двумя кейсами, которые привёл Егор, так как оба кейса - достаточно распространённые записи чисел и нам придётся объяснять пользователю, что мы не считаем их числами. В последствии мы дойдём до того, что нам придётся добавлять проп вроде `localeString`, чтобы дать пользователю возможность прокидывать такие строки...

В общем, проблем с этим `API` будет гораздо больше как для нас, так и для пользователей (так как пользователи будут путаться)

2022-06-16 06:12 UTC, JackUait requested changes

2022-06-16 11:29 UTC, JackUait requested changes

2022-06-20 11:19 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
Эта строчка не работает, так как нужно.
```ts
isNaN(Number(value)) && Number(value) !== CurrencyHelper.parse(prevState.formatted))
```
например, `value = 1`
`isNaN(Number(value))` выдаст `false`

2022-06-27 14:13 UTC, JackUait requested changes

2022-06-27 14:13 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
> Эта строчка не работает так как нужно.

Почему? Все твои тесты и тесты написанные до этого проходят со строчкой, которую я предложил

Твоё текущее решение падает, если начать ввод в инпут с `value='123'` и текущие тесты этого почему-то не показывают, нужно допилить их

> Но тогда с `value = 'str'`
Вернет `NaN`, что не равно `CurrencyHelper.parse(prevState.formatted))` и произойдет бесконечный перерендер.

Я намеренно не учитывал этот кейс, так как он не легален на все 100%, но я не знал что он выбрасывает ошибку и с учётом этого его тоже следует обрабатывать

В связи с новыми входными, нужно:
1. Сделать обработку `value='str'`
2. Написать тесты на проверку того, что `value='str'` не выбрасывает ошибку

Примерно так я вижу финальный код:
```ts
const isInvalidNumber = isNaN(Number(value));
const isLegalString = !!Number(value);

warning(!isInvalidNumber, `[CurrencyInput]: Prop value is not a valid number`);

if (isInvalidNumber && isLegalString && Number(value) !== CurrencyHelper.parse(prevState.formatted)) {
	...
}
```

2022-06-27 14:13 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      isValidNumber &&
Ещё, так как мы теперь умеем обрабатывать строки, стоит расширить `propTypes` для `value` до `PropTypes.oneOfType([PropTypes.number, PropTypes.string])`, так как пользователи не могут глушить ошибки от `propTypes`

2022-06-27 14:14 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
> Эта строчка не работает так как нужно.

Почему? Все твои тесты и тесты написанные до этого проходят со строчкой, которую я предложил

Твоё текущее решение падает, если начать ввод в инпут с `value='123'` и текущие тесты этого почему-то не показывают, нужно допилить их

> Но тогда с `value = 'str'`
Вернет `NaN`, что не равно `CurrencyHelper.parse(prevState.formatted))` и произойдет бесконечный перерендер.

Я намеренно не учитывал этот кейс, так как он не легален на все 100%, но я не знал что он выбрасывает ошибку и с учётом этого его тоже следует обрабатывать

В связи с новыми входными, нужно:
1. Сделать обработку `value='str'`
2. Написать тесты на проверку того, что `value='str'` не выбрасывает ошибку

Примерно так я вижу финальный код:
```ts
const isInvalidNumber = isNaN(Number(value));
const isLegalString = !!Number(value);

warning(!isInvalidNumber, `[CurrencyInput]: Prop value is not a valid number`);

if (isInvalidNumber && isLegalString && Number(value) !== CurrencyHelper.parse(prevState.formatted)) {
	...
}
```

2022-06-28 05:47 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
https://user-images.githubusercontent.com/32093844/176102169-fb8ac264-d581-4a46-8675-d5a505979dc5.mov

Твое решение не работает из-за условия` if (isInvalidNumber...)` По сути, ты говоришь, что вызывать перерендер, только если число некорректное. Нужно написать:` if (!isInvalidNumber...)`

2022-06-28 07:17 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +      async ['Input value']() {
Линтинг всё ещё ругается на эту строчку. У тебя установлен плагин [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)?

2022-06-28 07:49 UTC, JackUait requested changes

2022-06-28 07:49 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +const inputValueTest = {
```suggestion
const inputValueTest: CreeveyTests = {
```

2022-06-28 07:49 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +      .move(0, 0)
Координаты задаются в неправильном формате

2022-06-28 08:07 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +const inputValueTest = {
неактуально

2022-06-28 08:24 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +    }
> Нужно написать: `if (!isInvalidNumber...)`

Сейчас мы дважды отрицаем `isInvalidNumber` в `warning` и в условии, давай заменим `isInvalidNumber` на `isValidNumber`

2022-06-29 09:18 UTC, JackUait reviewed
В остальном - у меня всё. Осталось только тестики немного подправить

2022-06-29 09:18 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +      </Button>
У нас же есть и другие значения, те же `null`, `undefined`, `NaN` и `'str'`, они не меняют отображение в инпуте, но потенциально могут что-то сломать

Для наглядности стоит добавить в этот тест `value: state.value`, как в истории `Demo` из сторибука

2022-06-29 09:18 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__tests__/CurrencyInput-test.tsx
> +      <Button onClick={() => setValue('123')}>Set valid string value</Button>
Мы используем эти кнопки только для последних двух тестов, а рендерим их для каждого теста, так делать не стоит. Тому, кто в будущем будет читать эти тесты, будет сложно понять зачем нам тут эти две кнопки, особенно, если количество тестов значительно разрастётся. Лучше создать два отдельных компонента, каждый из которых будет рендерить нужную ему кнопку внутри каждого из тестов

2022-06-29 10:30 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +      </Button>
решила объединить мои тесты с Demo, чтобы не было дублирования

2022-06-30 10:43 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +          .click(this.browser.findElement({ css: '[data-tid="button_string"]' }))
Я так задумывала эти тесты: мы задаем какое-то число, проверяем, что оно установилось, а при изменении на nan, null и тд проверяем что ничего не меняется и не разваливается.

Я не поняла насчет key={Math.random()} - если тесты будут в разном порядке, то мы не сможем протестировать их правильно. Или я тебя не поняла

2022-06-30 12:48 UTC, lossir commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +          .click(this.browser.findElement({ css: '[data-tid="button_string"]' }))
> задаем какое-то число, проверяем, что оно установилось, а при изменении на nan, null и тд проверяем что ничего не меняется и не разваливается.

Хм.. Но в юнит тестах уже проверяется отсутствие ошибки при обновлении `value` с числа на строку. Туда можно добавить и другие типы.
К слову, почему `warning` только в `componentDidUpdate`? Может запихать эту проверку в `propTypes`?
Если маунтить объект сразу с `nan`/`null`, то контрол так же не должен разваливаться, и кидать варнинг. Предлагаю добавить ещё юнит тест на маунтинг, скриншотные тесты `Demo/Set value` убрать.

---

Ещё отмечу, что в `@testing-library/react` есть удобный инструмент для сеттинга пропов - [change](https://testing-library.com/docs/angular-testing-library/api/#change).
Думаю, лучше использовать его, вместо рендера кнопки и клика по ней. Т.к. это это ненужная связь с компонентом, проблемы в котором могут развалит этот тест.

2022-06-30 19:42 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__stories__/CurrencyInput.stories.tsx
> +          .click(this.browser.findElement({ css: '[data-tid="button_string"]' }))
> ...есть удобный инструмент для сеттинга пропов - [change](https://testing-library.com/docs/angular-testing-library/api/#change)...

Лучше не использовать такое `API`, было много прецедентов, когда подобное `API` удалялось из `RTL` + они неохотно фиксят баги связанные с этим `API`, так как оно считается запасным, более того - если мы используем `change` то проверяем что `API` из `RTL` может засеттить правильное значение, если мы меняем значение через клик по кнопке - то мы проверяем пользовательский сценарий. Проще говоря, используя `change` - мы [тестируем детали реализации](https://kentcdodds.com/blog/testing-implementation-details), так что бест практис это как раз рендерить кнопку

2022-07-01 10:49 UTC, lossir submitted a review, later dismissed

2022-07-01 11:25 UTC, JackUait requested changes

2022-07-01 11:25 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> +      warning(!isNaN(Number(props.value)), `[CurrencyInput]: Prop value is not a valid number`);
Чтобы избежать дублирования логики, лучше создать функцию `isValidNumber` и использовать её здесь и в `componentDidUpdate`

2022-07-01 11:25 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__tests__/CurrencyInput-test.tsx
> +  });
Эти тесты не эквиваленты удалённым: мы запускаем проверку только после `componentDidUpdate`, следовательно, нам нужна ещё пачка похожих тестов, которые будут проверять, что при изменении значения в инпуте оно действительно поменялось и компонент не выкинул ошибку

Я вижу эти тесты так:
1. Задать какое-то числовое значение инпуту по умолчанию (не важно какое), чтобы мы могли проверить его впоследствии, иначе `RTL` будет считать что в инпуте `,00`, а в `DOM` будет отображаться `value` без значения
2. Изменить значение в инпуте, через кнопку
3. Проверить, что код не выкинул ошибку
4. Проверить, что значение в инпуте для некорректных значений осталось прежним

2022-07-01 11:25 UTC, JackUait commented on packages/react-ui/components/CurrencyInput/__tests__/CurrencyInput-test.tsx
> +    render(<CurrencyInputWithValueProp value={parseInt('str')} />);
Здесь `'str'`, вместо `NaN`

2022-07-06 07:01 UTC, lossir approved these changes

2022-07-08 01:00 UTC, JackUait approved these changes

2022-07-11 14:57 UTC, merged