feat(tokeninput): add renderTotalCount and totalCount props
skbkontur/retail-ui pull request #2887
Opened 2022-05-05 06:50 UTC by Lelchik

https://guides.kontur.ru/components/tokens/#13.

fix #2314

2022-05-12 21:32 UTC, JackUait requested changes
Круто! Давно уже было пока закрыть эту задачку)

2022-05-12 21:32 UTC, JackUait commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  renderTotalCount?: (found: number, total: number) => React.ReactNode;
Так как функция `renderTotalCount` происходит из пропов `ComboBoxMenu` её тип стоит наследовать из пропов, чтобы придерживаться `DRY`

2022-05-12 21:32 UTC, JackUait commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  totalCount?: number;
Думаю, что этот проп лишний, пользователям придётся писать логику для расчёта количества отображаемых сущностей для каждого своего компонента самостоятельно, что не есть гуд, учитывая, что мы можем сделать это за пользователей

Как вариант (вероятно единственный) получить все айтемы можно вызвав функцию `getItems` с пустой строкой `''`. Конечно, походит на хак, но с текущей реализацией компонента других вариантов я не вижу. Вероятно Егор сможет предложить более элегантный способ реализации этой логики

2022-05-13 12:59 UTC, dzekh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  renderTotalCount?: (found: number, total: number) => React.ReactNode;
Про умолчанию — не знаю, не уверен. В основном потому что «записей», может быть тут и «строк» и «значений». Эта формулировка точно будет меняться и зависеть от типа данных. И мне не понятно куда она добавится и как и когда начнет отображаться. Еще нужно чтоб понятно было как её поменять, и она не сломала старое поведение. Как-то это же уже работало раньше?

2022-05-16 22:24 UTC, JackUait commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  renderTotalCount?: (found: number, total: number) => React.ReactNode;
Это сейчас работает в `ComboBox`'е (на котором и основывается `TokenInput`)
Пример можно посмотреть во [втором примере](https://tech.skbkontur.ru/react-ui/4.1.0/#/Components/ComboBox) актуальной документации

2022-05-17 07:31 UTC, Lelchik commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  totalCount?: number;
Сделала также как и у комбобокса чтобы не путать пользователей. И правильно ли делать запрос на получение всех айтемов с пустой строкой? Можно реализовать код так чтобы всегда возвращалось 20 айтемов, а общее количество было значительно больше

2022-05-17 07:58 UTC, Lelchik commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  totalCount?: number;
Либо еще вариант: переделать метод getItems: результат может быть массивом айтемов или объектом с полями items - тот же самый массив и полем totalCount - количество всех элементов. Но тогда по хорошему поменять логику и у комбобокса на такую же (или уже сделано?)

2022-05-20 13:19 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  renderTotalCount?: (found: number, total: number) => React.ReactNode;
В комбобоксе по-умолчанию нет сообщения, нужно передавать свое. Пример в доке вообще не через этот проп сделан, почему-то.

2022-05-20 13:40 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  totalCount?: number;
Без `totalCount` не получится. Нет пока другого способа понять, что отображены не все элементы, и нужно показать сообщение, кроме как сравнить `totalCount` с текущим количеством отображенных элементов. 

Просто комбобокс не знает, все ли в него передали, что есть, или это только часть, лимитированная пользователем ради перформанса. И единственный пока способ это передать их общее количество и сравнить.

Можно было бы сделать дефолтное значение для `renderTotalCount`. Но @dzekh на летучке сказал, что не стоит. Там лучше делать кастомное.

2022-05-20 13:41 UTC, zhzz approved these changes

2022-06-20 00:01 UTC, JackUait submitted a review, later dismissed
Можем мёржить

2022-06-20 10:05 UTC, zhzz commented
Похоже нужно обновить скриншоты после обновления версии firefox на гриде. И еще бы добавить задержку перед снятием скриншота для большей стабильности.

2022-06-22 08:51 UTC, zhzz requested changes
Похоже нужно обновить скриншоты после обновления версии firefox на гриде. И еще бы добавить задержку перед снятием скриншота для большей стабильности.

2022-06-22 10:33 UTC, JackUait commented
@zhzz переапрувил скриншоты и добавил задержку

2022-06-22 10:33 UTC, JackUait approved these changes

2022-06-24 08:36 UTC, zhzz approved these changes

2022-06-24 08:37 UTC, merged