feat(Calendar): add new public component Calendar
skbkontur/retail-ui pull request #2888
Opened 2022-05-12 08:07 UTC by Lelchik

https://yt.skbkontur.ru/agiles/101-1467/102-17779?issue=IF-446

2022-05-12 08:12 UTC, Lelchik commented
Вынесла компонент календаря в публичные. Не стала Picker делать полностью публичным, так как там есть небольшая верстка (тень), которая не нужна (?) в календаре.
Вопросы:
- кажется лишним пропс onSelect. Он вызывается только при клике на кнопку "сегодня". Скорее всего его можно заменить на onPick.
- локализация осталась такая же как и у Datepicker. Стоит ли для календаря копировать ее?

2022-05-25 10:35 UTC, JackUait commented
Вова (@dzekh), сейчас компоненты `Calendar` vs `DatePicker` выглядят так:
<table>
<tr>
	<th>Calendar</th>
	<th>DatePicker</th>
<tr>
	<td><img width="393" alt="Снимок экрана 2022-05-25 в 14 29 01" src="https://user-images.githubusercontent.com/48599460/170242041-541ed544-aa83-41b1-9e6a-663d0f478092.png">
</td>
	<td><img width="306" alt="Снимок экрана 2022-05-25 в 14 21 03" src="https://user-images.githubusercontent.com/48599460/170240574-a7262003-b5ba-4e96-b48c-cc15dfb554bd.png"></td>
</table>

У `DatePicker` есть тень, а у `Calendar` тени нет. Мне кажется правильным, что у `Calendar` как у не-выпадашки нет тени (если я хоть что-то понимаю в дизайне), но в связи с этим возникает проблема: эту тень нужно на что-то заменить. Есть ли возможность отрисовать в дизайне или хотя бы отписать текстом на что мы меняем тень и меняем ли её вообще?

2022-05-25 15:14 UTC, dzekh commented
> проблема: эту тень нужно на что-то заменить

На мой вкус тут проблема только с кнопкой «Сегодня» и тем, что отделяющая линия выглядит странно и шире всех остальных линий, а текст выровнен по центру. Всё остальное оформление и обрамление кажется можно оставить на откуп продуктов. Можно было бы заменить тень на однопиксельную обводку, но чаще всего она будет лишней, потому что там скорее всего будут свои контейнеры обрамляющие календарь и контролы рядом. 

Я бы предложил линию кнопки «Сегодня» убрать в этой версии (тем более она по умолчанию выключена и включается отдельным пропом), но хорошо бы добавить  такую-же линию чтоб она обозначала границу календаря снизу. Она обрезала бы цифры дат. После этого календарь уже будет выглядеть норм, для того чтобы встраивать его куда угодно.

Хорошо еще тут подумать про пару вещей: 
1) фон — идеально, чтоб он был прозрачный,
2) было бы круто если бы этот календарь можно было бы растягивать и сжимать по высоте. Пропом или просто внешним контейнером. Чтобы можно было спрятать торчащий снизу месяц или наоборот дать больше вариантов.

2022-05-25 22:17 UTC, JackUait requested changes

2022-05-25 22:17 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.styles.ts
>        touch-action: none;
А зачем нам тут "дополнительные" стили помимо `box-shadow`?
Эти стили ведь уже есть в `components/Сalendar.styles.ts`

P.S.
Егор (@zhzz), а насколько окей, что у нас тут `z-index` задаётся прямо в стилях, а не сеттится через `ZIndex`?

2022-05-25 22:17 UTC, JackUait commented on packages/react-ui/internal/Calendar/__stories__/Calendar.stories.tsx
> -export const Simple = () => (
А почему этот скриншот был удалён без полноценной замены?

2022-05-25 22:17 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  public static __KONTUR_REACT_UI__ = 'Calendar';
Сейчас у `internal/Calendar` и `components/Calendar` одинаковые поля `__KONTUR_REACT_UI__`

Кстати, Егор (@zhzz) мы хотим публичным делать только то, что раньше было `Picker`'ом или `internal/Calendar` в том числе?

2022-05-25 22:17 UTC, JackUait commented on packages/react-ui/components/Calendar/__stories__/Calendar.stories.tsx
> +      async ['DateSelect months']() {
В этих тестах остались имена из оригинальной истории

2022-05-25 22:20 UTC, JackUait commented
> кажется лишним пропс onSelect. Он вызывается только при клике на кнопку "сегодня". Скорее всего его можно заменить на onPick.

> локализация осталась такая же как и у Datepicker. Стоит ли для календаря копировать ее?

Это вопросы к Егору (@zhzz), я на это ответить не смогу)

2022-06-28 11:23 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  public static __KONTUR_REACT_UI__ = 'Calendar';
Я вообще думал, что в паблик пойдет только сам `internal/Calendar`. Мотивацию напишу ниже.

2022-06-28 11:31 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.styles.ts
>        touch-action: none;
Смотря зачем он тут. Если просто для того, чтобы поднять на фоне соседей, то норм.

2022-12-30 10:54 UTC, JackUait commented
> Я бы предложил линию кнопки «Сегодня» убрать в этой версии, но хорошо бы добавить такую-же линию чтоб она обозначала границу календаря снизу.

Готово:

<table>
<tr>
	<th> С датой
	<th> Без даты
<tr>
	<td> <img width="250" alt="Снимок экрана 2022-12-30 в 13 10 47" src="https://user-images.githubusercontent.com/48599460/210059117-0bfe0170-6f2f-4828-a3a7-2da3a3f14726.png"> </td>
	<td> <img width="245" alt="Снимок экрана 2022-12-30 в 13 10 59" src="https://user-images.githubusercontent.com/48599460/210059112-d1199feb-37ae-4b84-9aa2-09a4b98107c5.png"> </td>

</table>

> фон — идеально, чтоб он был прозрачный...

А зачем календарю прозрачный фон? Мне кажется, что будет достаточно отдельной переменной, позволяющей задать фон только для `Calendar`, а не для `Calendar` + `DatePicker`

> было бы круто если бы этот календарь можно было бы растягивать и сжимать по высоте. Пропом или просто внешним контейнером. Чтобы можно было спрятать торчащий снизу месяц или наоборот дать больше вариантов.

Это не так просто реализовать, в силу того, что календарь отображает только несколько месяцев в момент времени. Нужно раскурить логику, по которой календарь реализует подгрузку. Завёл для этого задачу `IF-928`

https://user-images.githubusercontent.com/48599460/210061798-11025e79-19ec-4d32-b798-a4577b87cfe2.mov

<hr />

Ещё меня смущают эти отступы по бокам. Их можно убрать через переменную, но кажется, что стоит из коробки поставлять компонент без них (чёрная обводка вокруг календаря для наглядности). Что думаешь по этому поводу, @dzekh? 

<img width="279" alt="Снимок экрана 2022-12-30 в 13 29 14" src="https://user-images.githubusercontent.com/48599460/210060609-55c69af2-51f6-4ca6-b703-b77823412120.png">

2023-01-11 08:31 UTC, dzekh commented
> Мне кажется, что будет достаточно отдельной переменной
Если можно менять переменной — ок. 

> Ещё меня смущают эти отступы по бокам. 
Тоже если будет переменная думаю этого достаточно. Лучше отступы оставить.

2023-03-06 08:01 UTC, nulladdict commented
Глянул на структуру компонентов, вот схема (поправьте если я где-то ошибся):

![image](https://user-images.githubusercontent.com/26379644/223049739-850a66a2-03e4-41d5-8fe4-d56c0414dcad.png)

Судя по схеме в зависимости от сценария могут пригодиться разные части:

- `Picker` / `Calendar` — дать скролящийся выбор даты без `DateInput` например по своей кнопке, в модалке или инлайн
- `Month` — сделать выбор даты без скролла, где отображается только один месяц и можно переключаться между ними
- `MonthDayGrid` — сверстать календарь, который показывает справочную информацию в пределах месяца, либо чтобы сверстать несколько месяцев подряд. Здесь цель не выбрать конкретную дату, а показать что-то и возможно перейти в какие-то детали по дню
- `DayCellView` — сюда удобно встраивать кастомный контент, но скорее всего сценарии решаются существованием `renderItem` и компонентом выше

В рамках этой задачи, пока мы не знаем сценариев, я бы не делал публичными компоненты ниже по дереву, если понадобятся можно будет сделать это отдельно

2023-03-17 05:50 UTC, nulladdict approved these changes

2023-03-17 06:50 UTC, nulladdict commented
подлил к себе, в `NativeDateInput-test.tsx` надо поправить импорт `CalendarDateShape`

2023-03-17 07:46 UTC, JackUait commented
> подлил к себе, в NativeDateInput-test.tsx надо поправить импорт CalendarDateShape

Хмм, интересно, не знал, что `jest`'у пофиг на неправильный импорт типов, исправил

P.S. Заодно подлил мастер

2023-03-17 11:25 UTC, nulladdict commented on packages/react-ui/components/Calendar/Calendar.tsx
> +        {...rest}
здесь слишком много пропов спредится, и попадают всякие minDate, onValueChange и тд

2023-03-21 01:21 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +        {...rest}
Обернул корневой тег в `CommonWrapper`

2023-03-21 10:07 UTC, zhzz requested changes

2023-03-21 10:07 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> +          {...rest}
Прокидываются лишние пропы.

2023-03-21 10:19 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  value: Nullable<CalendarDateShape>;
Еще подумал, а может названия `date` и `onDateChange` для пропов лучше подойдут? Будет согласованность с `minDate` и `maxDate`. А `value` это вроде больше к инпутам относится.

2023-03-21 10:19 UTC, zhzz commented
Хорошо бы также актуализировать описание ПРа.

2023-04-19 06:22 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +import * as CalendarUtils from './calendarUtils';
Поправил

2023-04-19 06:22 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    const initialYear = setInititalDate(this.props._initialYear, today.month, date.year, shouldSetInitialDate);
Удалил проп и логику, которая шла с ним

2023-04-19 06:22 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  _initialYear?: number;
- Сделал пропы публичными
- Добавил примеры использования в доку
- Сделал проп `initialMonth` более юзер-френдли, чтобы пользователи могли задавать месяц не с `0` до `11`,  а с `1` до `12`
- Ограничил тип для `initialMonth` числами в диапазоне от `1` до `12`
- Накинул тестов для этих пропов

2023-04-19 06:22 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  hasBottomSeparator?: boolean;
Ты предлагаешь добавить в тему токен `calendarBottomSeparatorDisplay` или какой-то другой токен?

2023-04-19 06:22 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    const { className, hasBottomSeparator, ...rest } = this.getProps();
Поправил

2023-04-19 06:23 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> +          {...rest}
Поправил

2023-04-19 06:23 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  value: Nullable<CalendarDateShape>;
Я поменял названия, но кажется, что всё-таки лучше использовать `value`/`onValueChange`, так как они привычнее для пользователей и не заставляют задумываться над тем, в какой проп нужно передавать значение. Сейчас, вроде как, ни в одном другом компоненте не используется контекстный нейминг подобных пропов, при этом в `SideMenu` есть пропы `value`/`onValueChange`, которые отвечают за ручное управление меню

2023-04-19 06:23 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
>      const { date } = this.state;
Удалил логику из `Picker`'а

2023-04-19 06:23 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            _isDatePicker
> Похоже, что это больше не нужно.

Удалил


> И вообще выходит что API Picker можно не менять, т.к. он остается внутренним. Так не будет ломающих изменений для тех, кто уже использует Picker.

`API` `Picker`'а завязано на `API` `Calendar`, поэтому с переходом к строкам в `Calendar` поломалось и `API` `Picker`'а. Но наверное оно к лучшему, так как это стимулирует пользователей переходить на публичные компоненты

P.S.
Пока адаптировал `Calendar` под работу со строками неоднократно возникало чувство, что `Picker` - это в целом лишняя прослойка, которая только создаёт проблемы. Кажется, что мы ничего не потеряем, если полностью избавимся от него

2023-04-19 06:23 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  value: Nullable<CalendarDateShape>;
Научил пропы `date`, `onDateChange`, `minDate`, `maxDate` и `isHoliday` работать со строками

2023-04-19 06:26 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +      <LocaleContext.Provider value={{ locale: { DatePicker: { months: this.locale.months } } }}>
Не до конца понимаю о чём речь, предлагаю обсудить этот комментарий голосом

2023-04-19 10:39 UTC, JackUait commented
> Хорошо бы также актуализировать описание ПРа.

Обновил описание

2023-04-21 06:01 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    const { className, hasBottomSeparator, ...rest } = this.getProps();
Ничего не поменялось. Все еще прокидывается руками.

![image](https://user-images.githubusercontent.com/4607770/233552579-6572b8b9-f83f-4f12-9cc3-ac09748babb7.png)

2023-04-21 07:35 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  hasBottomSeparator?: boolean;
Какой-то такой:
```ts
  public static get calendarBottomSeparatorBorder() {
    return `1px solid ${this.calendarMonthTitleBorderBottomColor}`;
  }
```

2023-04-26 10:55 UTC, zhzz requested changes

2023-04-26 10:55 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.md
> +<Calendar isHoliday={isHoliday} date={date} onDateChange={setDate} />;
Пример не показывает ни одного кастомного выходного дня, пока не доскролишь до сегодняшней даты.

![image](https://user-images.githubusercontent.com/4607770/234546095-0160b63c-11a0-43d6-91c5-8e9d87a9b489.png)

2023-04-26 10:55 UTC, zhzz commented on packages/react-ui/components/Calendar/index.ts
> +export * from './Calendar';
Теперь рядом два отдельных индексных файла

2023-04-26 10:55 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> -    isHoliday: (_day: string, isWeekend: boolean) => isWeekend,
В консоли появился ворнинг:

![image](https://user-images.githubusercontent.com/4607770/234551690-f1e7111f-ee42-4407-8672-af13c010d243.png)

2023-04-26 10:56 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +      <LocaleContext.Provider value={{ locale: { DatePicker: { months: this.locale.months } } }}>
ок

2023-04-27 04:52 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            _isDatePicker
Договорились отказаться от использования Picker, но пока оставить его в библиотеке с прежним API для обратной совместимости. Нужно будет его задепрекейтить, выводя сообщение в консоль как [тут](https://github.com/skbkontur/retail-ui/blob/5821cc6ef68217030603049937821378fd8d8d83/packages/react-ui/components/TopBar/TopBar.tsx#L149).

2023-04-27 05:27 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  value: Nullable<CalendarDateShape>;
Посмотрел календари в других библиотеках - везде используют `value`. При этом, где-то в комбинации с `minDate`/`maxDate`, а где-то с `minValue`/`maxValue`. Так что, вероятно, ты прав.

2023-05-16 12:05 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.md
> +Вне зависимости от того, какая дата выбрана в календаре в данный момент - можно изменить отображение текущего года и месяца с помощью пропов `initialMonth` и `initialYear`
Поправил

2023-05-16 13:34 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    const { className, hasBottomSeparator, ...rest } = this.getProps();
Поправил

2023-05-16 13:34 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +  value: Nullable<CalendarDateShape>;
Вернул `value` и `onValueChange`

2023-05-16 13:34 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.styles.ts
> +  },
Да, линия с того времени действительно стала шире и так не было задумано. Исправил

----

У кнопок задано относительное позиционирование, из-за чего они могут перекрывать статически позиционированную линию

https://github.com/skbkontur/retail-ui/assets/48599460/799edc48-c446-4ae7-ba60-3e08cf453b54

2023-05-16 13:34 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    });
Отрефакторил и удалил функцию `setInitialDate`

2023-05-16 13:34 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +      months: CalendarUtils.getMonths(this.props.initialMonth ? initialMonth - 1 : initialMonth, initialYear),
Вынес логику в `CalendarUtils.getMonthInNativeFormat()`

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    const maxDate = new InternalDate().parseValue(this.getProps().maxDate).toNativeFormat();
Поправил

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> -    const wrapperStyle = { height: themeConfig(this.theme).WRAPPER_HEIGHT };
Вернул `wrapperStyle`

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.md
> +      }}
Удалил дополнительные стили и вёрстку

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.md
> +<Calendar isHoliday={isHoliday} date={date} onDateChange={setDate} />;
Исправил начальную дату на сегодняшнюю

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/Calendar/index.ts
> +export * from './Calendar';
Удалил лишний файл

2023-05-16 13:35 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> -    isHoliday: (_day: string, isWeekend: boolean) => isWeekend,
Сделал проп необязательным в `PropTypes`

2023-05-17 11:04 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            _isDatePicker
- Разделил `Picker` и `DatePicker`
- Вернул "старое" `API` в `Picker`
- Завёл сообщение об ошибке в `Picker`

2023-05-17 11:13 UTC, JackUait commented
Пока не могу обновить скриншоты, так как не запускается `Creevey`

2023-05-23 05:57 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.styles.ts
> +  },
Но самой линии относительное позиционирование не нужно. Если разобраться в том, почему дни ее перекрывают, несмотря на то, что у них разные контейнеры, то окажется, что дело `overflow: hidden`. Он задан не на `wrapper`, который непосредственно оборачивает дни, а на общем `root`. Если поменять, то лишние стили для линии больше не понадобятся.

2023-05-23 09:48 UTC, zhzz requested changes

2023-05-23 09:48 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> +    return { date, month, year };
Уже ведь есть хелперы для этих задач. Используются в том же `Calendar`.

2023-05-23 09:48 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> +          }}
Стрелочные функции в jsx, уже обсуждали

2023-05-23 09:48 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> -    }
Куда пропал `scrollToMonth`? `Picker` ведь напрямую использовался в проектах. Возможно его место вообще в Calendar на самом деле.

2023-05-23 09:48 UTC, zhzz commented on packages/react-ui/.creevey/images/DatePicker/DatePicker In Relative Body/opened/chrome2022/opened.png
`border-radius` законно поменялся?

2023-05-23 09:50 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.tsx
> +      <LocaleContext.Provider value={{ locale: { DatePicker: { months: this.locale.months } } }}>
А что с этим?

2023-05-30 11:01 UTC, JackUait commented on packages/react-ui/.creevey/images/DatePicker/DatePicker In Relative Body/opened/chrome2022/opened.png
Нет, не законно. Это произошло из-за того, что фон у `DatePicker` и `Calendar` задается через разные переменные: `pickerBg` и `calendarBg` соответственно. Прокинул `border-radius` в `Calendar`, так как изменение переменной в `DatePicker` на `calendarBg` приведёт к ломающим изменениям, а в `Calendar` на `pickerBg` к плохому дизайну и необходимости вносить ломающие изменения в будущем

---

Заведу задачу про отказ от `Picker` в мажорном релизе и добавлю в неё описание этой проблемы

2023-05-30 11:01 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> -    }
> Куда пропал scrollToMonth? Picker ведь напрямую использовался в проектах.

Вернул метод

> Возможно его место вообще в Calendar на самом деле.

`<Picker />`  уже забирает этот метод из `<Calendar />` через `ref`

2023-05-30 11:01 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> +          }}
Отрефакторил

2023-05-30 11:01 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.styles.ts
> +      margin: 0 ${marginX}px;
Отрефакторил

2023-05-30 11:11 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.styles.ts
> +  },
Поправил

2023-05-31 13:02 UTC, zhzz requested changes
Еще остался открытым [этот комментарий](https://github.com/skbkontur/retail-ui/pull/2888#discussion_r1143114100)

2023-06-01 11:04 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> -    }
- Удалил логику из `<Picker />` и `<DatePicker />` и добавил в `<Calendar />`
- Добавил скриншотные тесты на новую логику в `<Calendar />`

2023-06-01 11:04 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> +    return { date, month, year };
- `InternalDateTransformer.dateToInternalString` не обрабатывает случаи когда передаваемое значение `null`|`undefined`. Изначально я использовал этот хелпер, но по итогу решил что целесообразнее будет написать свой
- Заменил `getShapeFromStringDate` на `new InternalDate().parseValue(stringDate).getComponentsLikeNumber()`

2023-06-02 11:07 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.tsx
> +      <LocaleContext.Provider value={{ locale: { DatePicker: { months: this.locale.months } } }}>
- Научил `<Calendar />` использовать локали `<DatePicker />`
- Написал тест на использование локалей `<DatePicker />` в `<Calendar />`

2023-06-02 15:09 UTC, JackUait commented
На `TC` падает не относящийся к задаче скриншот

2023-06-05 22:47 UTC, JackUait commented
На `TC` не билдится `.NET`. Прогнал все скрипты в `react-ui-validations` - все прошли успешно

2023-06-06 12:37 UTC, zhzz commented on packages/react-ui/lib/locale/decorators.tsx
> +export function locale<C>(controlNames: ControlNamesType, localeHelpers: LocaleHelper<C>) {
Не уверен что это усложнение того стоит. Нам нужно всего лишь временно поддержать локализацию Calendar через локаль DatePicker-а. После мажорного релиза это уже будет не нужно. 

Проще обернуть Calendar в LocaleContext.Provider внутри DatePicker, а потом убрать его. Механизм локализации останется простым.

DateSelect тогда должен будет смотреть только на локаль Calendar.

2023-06-06 12:37 UTC, zhzz commented on packages/react-ui/components/DatePicker/Picker.tsx
> +    return { date, month, year };
> InternalDateTransformer.dateToInternalString не обрабатывает случаи когда передаваемое значение null|undefined. Изначально я использовал этот хелпер, но по итогу решил что целесообразнее будет написать свой

Можно проверить на null|undefined прежде чем использовать готовый хэлпер. Лучше же, чем его логику дублировать.

2023-06-07 10:46 UTC, JackUait commented on packages/react-ui/components/DatePicker/Picker.tsx
> +    return { date, month, year };
Переиспользовал хелпер `InternalDateTransformer.dateToInternalString()` и добавил проверку на `undefined`

2023-06-07 10:48 UTC, JackUait commented on packages/react-ui/lib/locale/decorators.tsx
> +export function locale<C>(controlNames: ControlNamesType, localeHelpers: LocaleHelper<C>) {
- Прокинул `LocaleContext.Provider` в `<DatePicker />`
- Удалил логику из `locale/decorators`
- Удалил тест на изменение локали `<Calendar />` через локаль `<DatePicker />`
- Добавил тест на изменение локали `<Calendar />` через локаль `<DatePicker />` внутри `<DatePicker />`

2023-06-08 04:51 UTC, zhzz approved these changes

2023-06-08 10:53 UTC, merged