fix(PasswordInput): get focus back after clicking on the eye icon
skbkontur/retail-ui pull request #2892
Opened 2022-05-18 23:35 UTC by JackUait

fixes [IF-472](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-472)

При повторном клике на иконку глаза в `PasswordInput` перестал возвращаться фокуc (см. видео)

https://user-images.githubusercontent.com/48599460/169170707-995738ae-127a-4c49-bb8b-5ade27f7e022.mov

Это было вызвано двумя причинами:
1. После смены иконки не вызывался `onClick`. Это полечилось добавлением `pointer-events: none` на обе иконки (на самом деле достаточно добавить эти стили на одну иконку, но для уверенности добавил на обе)
2. При потере фокуса инпут мгновенно переходит в режим скрытых символов из-за чего при ручном переходе из открытых символов в скрытые пользователь попадал в бесконечный цикл (см. видео)

	https://user-images.githubusercontent.com/48599460/169172055-4eea64d5-e5cd-4a62-a7e7-9774a22a47d2.mov

	Это удалось полечить проверкой того, что пользователь в данный момент сфокусирован на инпуте перед переходом в режим скрытых символов при блюре

<hr />

Не уверен, насколько легальны обращения к `document.activeElement` (в том плане не упадут ли они в `SSR` окружении) без дополнительных проверок, но увидел несколько мест в публичных компонентах где также используется объект `document` без проверок, так что не стал добавлять и к себе. Но хотелось бы понять благодаря чему такой код не упадёт в `SSR`

2022-05-24 07:36 UTC, zhzz commented
Как воспроизвести бесконечный цикл? У меня не получается. Есть какое-то особое условие?

2022-05-25 09:11 UTC, JackUait commented
Чтобы воспроизвести бесконечный цикл нужно убрать `setTimeout` со 163-ей строки в `PasswordInput`:
```tsx
setTimeout(() => {
  // @ts-expect-error: private property
  if (document.activeElement !== this.input?.input) {
    this.setState({ visible: false });
  }
}, 200);
```

2022-06-02 22:19 UTC, JackUait commented
> Можно было бы завернуть ее в кнопку и улучшить a11y заодно.

Мне второй вариант нравится больше, но оборачивание иконки в кнопку вызовет ряд других проблем. Реализацию этого можно завести как задачу в бэклог, но не думаю, что сейчас есть смысл тратить время на проработку этого поведения

> Детектить только тот blur, который происходит за пределы компонента. Это основная специализация компонента RenderLayer.

Крутая штука! Не понимал что конкретно она делает до этого момента (звучит как тема для тех. ревью `internal` компонентов, на тех. ревью также можно затронуть тему публичности некоторых `internal` компонентов/утилит, а также поговорить об эквивалентах этих компонентов/утилит на хуках, в общем с моей точки зрения эту тему можно растянуть на три тех. ревью)

2022-06-03 14:02 UTC, zhzz requested changes

2022-06-03 14:02 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> +      <RenderLayer onClickOutside={() => this.setState({ visible: false })}>
Стрелочная функция в пропе компонента - плохая примета. Также, помимо `onClickOutside` нужно заюзать еще и  `onFocusOutside`, потому что фокус может уйти не кликом, а табом.

2022-06-03 14:02 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInputIcon.tsx
> +  );
Эти изменения уже скорей всего тоже не нужны.

2022-06-03 14:28 UTC, JackUait commented on packages/react-ui/components/PasswordInput/PasswordInputIcon.tsx
> +  );
Мне кажется, что эти стили лучше оставить, так как они фиксят баг повторного клика на иконку глаза, да, в текущей реализации они уже не нужны, но в будущих пользовательских или наших сценариях могут понадобиться. Я бы добавил комментарий, про то, что эти стили существуют затем, чтобы пофиксить баг, но не стал бы от них полностью избавляться

2022-06-14 06:56 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInputIcon.tsx
> +  );
Не понял тебя. Они либо фиксят баг, либо не нужны.

Но баг уже фиксится по-другому, его больше нет. Следовательно, стили уже не нужны.

2022-06-17 11:06 UTC, zhzz commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> -    this.setState({ visible: false });
Остальной `onBlur` уже тоже не нужен.

2022-06-23 11:36 UTC, JackUait commented on packages/react-ui/components/PasswordInput/PasswordInput.tsx
> -    this.setState({ visible: false });
Удалил

2022-06-23 19:20 UTC, zhzz approved these changes

2022-06-24 08:44 UTC, khlutkova approved these changes

2022-06-24 10:17 UTC, merged