fix(Checkbox): select of multiple checkboxes
skbkontur/retail-ui pull request #2894
Opened 2022-05-20 14:26 UTC by JackUait

fixes [IF-499](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-499)

При зажатии `Shift`'а и попытке одновременно выделить несколько чекбоксов происходило выделение текста, которое мешало отметить сразу несколько чекбоксов. Этот баг появился в #2586 пулл-реквесте, когда мы разрешили пользователям выделять текст чекбоксов

https://user-images.githubusercontent.com/48599460/169548755-2252a31d-5b73-4e66-ab87-5dba4b27c1dc.mov

<hr />

**Решил** проблему добавлением стиля `user-select: none;` при зажатом `Shift`'е

Также добавил интеграционные и скриншотные тесты для тестирования этого поведения

P.S.
Тестировал изменения в `IE11`, там так же всё корректно отрабатывает, но на скриншотах в лучшем случае отмечается только первый чекбокс

2022-06-02 10:32 UTC, zhzz requested changes
Сбивает с толку, что задача и решение формулируются как починка "выбора нескольких чекбоксов с зажатым shift ", хотя такого функционала в библиотеке нет. Это чисто внешний пользовательский сценарий, который они сами реализуют, но его ломает наш баг. А баг заключается конкретно в том, что в хроме не работает клик по чекбоксу с зажатым шифтом. Именно на этом стоит делать акцент, а остальное второстепенно.

2022-06-02 10:32 UTC, zhzz commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +MultipleSelection.storyName = 'multiple selection';
Тут тоже по большей части тестируется чужой код из  `MultipleSelectionComponent`. Было бы проще и достаточно потестить только один наш чекбокс с зажатым шифтом.

2022-06-02 21:25 UTC, JackUait commented on packages/react-ui/components/Checkbox/Checkbox.tsx
> +  };
Не совсем понял: речь про нейминг или про логику
1. Если про нейминг, то можно переименовать переменную в `isOnlyShiftPressed`, но я предлагаю пойти чуть дальше;
2. Изначально у меня было понимание, что `Shift` + `любая другая клавиша` это комбинация отличная от просто зажатого `Shift`. Теперь я думаю, что `Shift` независимо от того, используется он как "самостоятельная комбинация" или в комбинации с другими клавишами должен отключать выделение текста:
    ```ts
    private handleShiftRelease = (e: KeyboardEvent) => {
        if (e.key === 'Shift') {
          this.setState({
            isShiftPressed: false,
          });
        }
      };
    ```

    Аргументирую я это тем, что если пользователь реализует комбинацию завязанную на `Shift` + `какой-либо клавише` и при этом, ему понадобится выделять сразу несколько чекбоксов, то пользователь не сможет реализовать такой сценарий из-за текущей реализации

    Дабы не говорить о сферическом коне в вакууме приведу пример.
    Пользователь хочет реализовать два сценария:
    1. При зажатом `Shift` пользователь хочет позволить выбирать сразу несколько чекбоксов
    2. При зажатом `Shift` + `f` (от "fractional", так как до клавиши "p" (от "partial") слишком далеко тянуться) пользователь хочет реализовать частичное выделение и с текущей реализацией у него это сделать не получится

    Хочу понять, есть ли какие-то сценарии противоположенные приведённому выше или может у тебя есть какие-то другие замечания по поводу ?

2022-06-02 21:33 UTC, JackUait commented on packages/react-ui/components/Checkbox/__tests__/Checkbox.test.tsx
> +    render(<MultipleSelection numberOfItems={5} />);
Удалил тест

2022-06-02 21:57 UTC, JackUait commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +MultipleSelection.storyName = 'multiple selection';
Обновил тест, но пока не получилось посмотреть/заапрувить скриншоты. `Creevey` по какой-то причине отказывается запускаться

2022-06-03 05:09 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.tsx
> +  };
Я говорил про логику, имея в виду, что важен только `shift`. А в текущем варианте, флаг может сброситься любой другой клавишей, отжатой в то время, пока `shift` зажат. С кодом из пункта 2 согласен.

2022-06-14 06:45 UTC, zhzz commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).click(checkbox).perform();
Зачем два клика? 
Что именно сейчас этот тест проверяет? В каком случае он упадет?

2022-06-16 09:58 UTC, JackUait commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).click(checkbox).perform();
Два клика вызывают выделение. Тест проверяет вызовется ли выделение после двойного клика

https://user-images.githubusercontent.com/48599460/174045398-8963208f-0a68-40d5-a58e-eacb3aba4df1.mov

2022-06-17 10:51 UTC, zhzz commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).click(checkbox).perform();
Нам не это важно, а то, чтобы чекбокс работал (чекался) с зажатым шифтом.

2022-06-23 11:03 UTC, JackUait commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).click(checkbox).perform();
Обновил скриншотные тесты, удалил тест `selected`

2022-06-24 07:37 UTC, zhzz requested changes

2022-06-24 07:37 UTC, zhzz commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).perform();
Скриншоты падают из-за того, что `shift` остается зажатым после теста.

2022-06-24 11:07 UTC, JackUait commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +        await this.browser.actions({ bridge: true }).keyDown(this.keys.SHIFT).click(checkbox).perform();
Поправил. Теперь после снятия скриншота клавиша отжимается через `keyUp`

2022-06-24 13:26 UTC, merged