fix(Select): button border-radius with custom select theme
skbkontur/retail-ui pull request #2896
Opened 2022-05-22 11:35 UTC by JackUait

fixes [IF-498](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-498)

Исправил скругление `Button` внутри `Dropdown`, когда задано кастомное скругление `Select`'а

**На видео:** заданы кастомные значения для токенов скругления кнопок (`btnBorderRadius*`), в связи с чем, снаружи `Dropdown` кнопки отображаются со скруглением. Кнопки внутри `Dropdown` наследуют стили скругления для селекта (`selectBorderRadius*`), в связи с чем выглядят квадратными

https://user-images.githubusercontent.com/48599460/169692757-25856905-7ad3-4c32-9157-34a58f620cec.mp4

<hr />

Изменил место задания скругления кнопки, открывающей `Select`, чтобы токены `Select`'а влияли только на открывающую кнопку, а не на все кнопки внутри `Select`/`Dropdown`

Покрыл этот кейс скриншотными тестами

2022-06-03 08:47 UTC, zhzz requested changes

2022-06-03 08:47 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +                  btnBorderRadiusLarge: theme.selectBorderRadiusLarge,
Тут починился только `border-radius`. А как же остальные общие переменные кнопки и селекта, с которыми может произойти то же самое?

2022-06-05 12:39 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +                  btnBorderRadiusLarge: theme.selectBorderRadiusLarge,
Переместил получение всех токенов из `getSelectTheme` до уровня кнопки, также немного дополнил скриншотный тест, но пока не могу заапрувить новые скриншоты, так как `Creevey` до сих пор не запускается

2022-06-05 18:42 UTC, zhzz requested changes

2022-06-05 18:42 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +          this.theme = theme;
Здесь `ThemeContext.Consumer` не нужен, `this.theme` уже записана в `render` и ее дальше можно просто использовать.

2022-06-05 18:42 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +            <ThemeContext.Provider value={ThemeFactory.create(getSelectTheme(theme, this.props))}>
Зачем снова `ThemeFactory.create`? Она уже есть в `getSelectTheme`.

2022-06-06 12:47 UTC, zhzz commented
Скриншоты обновить осталось

2022-06-06 19:55 UTC, JackUait commented
Заапрувил скриншоты 🥳

2022-06-23 06:46 UTC, khlutkova approved these changes

2022-06-23 07:55 UTC, merged