Добавить data-tid
skbkontur/retail-ui pull request #2900
Opened 2022-05-26 08:35 UTC by HelenaIsh

Данный ПР добавляет компонентам атрибут data-tid. Также добавлен экспорт data-tid по просьбе из слака

2022-05-31 12:40 UTC, JackUait requested changes

2022-05-31 12:57 UTC, HelenaIsh commented on packages/react-ui/components/DatePicker/Picker.tsx
> +};
Дата-тид `data-tid="Picker__todayWrapper"` уже был, я его не добавляла. Изменять его я не могу, тк это потенциально ломающее изменение (вдруг кто-то уже использует этот дата-тид).
Но на страничке в доках с дата-тидами для компонента DataPicker я указала, что есть такие data-tid:
```
{
    ['DataPicker']: [
      { ['dataPickerDataTid']: JSON.stringify(dataPickerDataTid) },
      { ['pickerDataTid']: JSON.stringify(pickerDataTid) },
    ],
  },
```
<img width="999" alt="image" src="https://user-images.githubusercontent.com/32093844/171178625-4467e2b9-0ff9-4231-947d-f93e995623c3.png">

2022-05-31 14:15 UTC, JackUait commented on packages/react-ui/lib/data-tid/DataTid.tsx
> +    const list = componentsDataTid.map((element: { [key: string]: any }, index) => {
Эта строчка упадёт после мёржа #2856, нужно заменить `any` на полноценный тип

2022-06-01 10:16 UTC, zhzz commented on packages/react-ui/lib/data-tid/componentsDataTid.ts
> +  { ['Center']: [{ ['centerDataTid']: JSON.stringify(centerDataTid) }] },
Похоже на то, что поле `origin` - лишнее. Заполняется в ручную, значит будем постоянно забывать это делать. А пользователям оно не нужно и будет смущать, находясь в списке рядом с настоящим дата-тидами.

Имя компонента можно же получить отрезав суффикс у имени объекта с тидами.

2022-06-01 10:56 UTC, zhzz commented on packages/react-ui/lib/data-tid/DATATID.md
> +Аттрибут data-tid экспортируется для компонентов в виде объекта.
Атрибут же не один, их там много.

Можно добавить в эту MD информацию о том, что у всех компонентов есть также проп `data-tid`, которым можно переопределять корневые дата-тиды. И переложить в корень react-ui рядом с другой такой же докой.

2022-06-01 10:56 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +};
Я бы предложил называть эти объекты с большой буквы, как и все, что экспортируется из библиотеки, для большей эстетичности. И добавить `s` в конце - это же набор тидов, их там много. Также, указать им `as const`, чтобы сузить тип полей со `string` до конкретных значений, которые пользователь сможет увидеть уже в типах. Плюс, это сделает их `readonly`.

```suggestion
export const ButtonDataTids = {
  origin: 'Button',
  root: 'Button__root',
} as const;
```

2022-06-01 10:56 UTC, zhzz commented on packages/react-ui/lib/data-tid/DataTid.tsx
> +            </div>
Пока табличка выглядит перегруженной. Отдельные колонки для имени компонента и имени объекта с тидами кажутся дублированными, наверное можно их объединить или оставить одну. А вот имена полей и их значений - наоборот, слабо различимы, хотя важны, вероятно стоит их разделить. 

Главное чтобы пользователю было сходу понятно, какие дата-тиды у каких компонентов есть, и как ими воспользоваться.

2022-06-02 22:39 UTC, JackUait commented
В копилку улучшения `UX` для доки: `Select`'у с компонентами стоит добавить поиск

2022-06-03 00:22 UTC, JackUait requested changes

2022-06-03 00:22 UTC, JackUait commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +import * as PopupMenu from '../../internal/PopupMenu';
На митинге я имел ввиду, что все `internal` компоненты, которые экспортируют `data-tid`'ы лучше поместить в какой-то файл в корне `internal` и экспортировать этот файл в `packages/react-ui/index`, тем самым, мы скажем что `internal` `data-tid`'ы на ровне с `data-tid`'ами из публичных компонентов также публичные и пользователям не придётся лезть в какие-то дебри библиотеки и задаваться вопросами future proofing'а, чтобы получить нужный им `data-tid`

Но при этом нужно учитывать нюанс из первого пункта [комментария](https://github.com/skbkontur/retail-ui/issues/2716#issuecomment-1013087333) Егора и экспортировать только `data-tid`'ы из `internal` компонентов. Ну и плюс, так как это `internal` компоненты, все их "кишки" будет неуместно публиковать

Чтобы не забывать экспортить новые `data-tid`'ы, которые попадают в `internal` компоненты предлагаюа написать скриптик на ноде, который будет парсить папку `internal` и создавать файл с экспортами `data-tid`'ов за нас, прогонять скрипт можно либо перед каждым коммитом, либо через `yarn` скрипт

2022-06-03 00:22 UTC, JackUait commented on packages/react-ui/components/Loader/Loader.tsx
> +  vail: 'Loader__Veil',
Разница в названии и содержимом: `vail`/`Veil`

2022-06-03 00:22 UTC, JackUait commented on packages/react-ui/components/Modal/Modal.tsx
> +} as const;
Думаю, что стоит пометить эти `data-tid`'ы как `deprecated` и переписать их на корректные в 5-ой версии как ломающее изменение

P.S.
То же самое относится и ко всем остальным подобным кейсам

2022-06-03 08:22 UTC, zhzz commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +import * as PopupMenu from '../../internal/PopupMenu';
Можно не усложнять на первых порах и не публиковать нигде дата-тиды internal-компонентов. Пусть они будут доступны для импорта из них самих, если понадобятся и люди их найдут в коде. А когда поймем, что это точно нужно - придумаем что-нибудь для их более удобного использования.

2022-06-03 11:30 UTC, JackUait commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +import * as PopupMenu from '../../internal/PopupMenu';
Это кажется очень странным решением с точки зрения `DX`. У нас есть `internal` `data-tid`'ы, которые мы нигде внутри библиотеки не используем, например `ComboBoxMenu__loading`, то есть такие `data-tid`ы скорее всего были добавлены для внешнего пользования, но мы говорим пользователям что им нужно лезть в "кишки" библиотеки, чтобы их достать + нигде в доке не указываем что эти `data-tid`'ы так просто не импортируешь к себе в проект

В общем, мы заставляем пользователя думать, чтобы пользоваться нашей библиотекой, что с моей точки зрения - это всегда плохо

2022-06-05 19:42 UTC, zhzz commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +import * as PopupMenu from '../../internal/PopupMenu';
Согласен, что так будет не очень удобно. Но, в твоем варианте часть api internal-компонентов станет публичным, что внесет противоречие. И это api придется поддерживать совместимым.

В идеале, нам бы нужно вообще как-то перенести такие полезные дата-тиды internal-компонентов в публичные. Пользователь вообще ничего не должен знать про internal, в том числе, работая с тидами. Но как это правильно сделать пока непонятно.

Думаю, не стоит пока сильно углубляться в эту задачу. Можно сделать минимум, собрать ОС, и вернуться к ней позже, если будет необходимость. Главное пока, чтобы дата-тиды были, и была какая-то возможность их получить.

2022-06-06 00:22 UTC, JackUait commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +import * as PopupMenu from '../../internal/PopupMenu';
Окей, давай тогда так и поступим

2022-06-06 15:09 UTC, JackUait reviewed
Максим (@lossir), пробегись плиз по `PR`'у, все предыдущие правки от меня и Егора Лена уже внесла

2022-06-07 10:50 UTC, JackUait commented on packages/react-ui/lib/data-tid/componentsDataTids.ts
> +      // @ts-ignore
Директивы `@ts-ignore` и `@ts-expect-error` предназначены для одного и того же: глушить типизацию. Но если типизация по какой-то причине исправится `@ts-ignore` не сообщит нам об этом, а `@ts-expect-error` - сообщит. Поэтому нет смысла использовать их вместе

Плюс причина по которой `TS` ругается - это возможность передать в `Components` любое строковое значение, даже то, которое вернёт `null`/`undefined`. Но мы знаем, что такого значения там быть не может, поэтому нам нужно явно сообщить `TS`, что мы уверены что всегда будем передавать "законное" значение. Сообщить это можно с помощью оператора `as`:
```ts
[currTid]: Object.entries(Components[currTid as keyof typeof Components])
```

2022-06-07 11:33 UTC, JackUait approved these changes
👍

2022-06-07 15:09 UTC, lossir commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
Думаю, это немного перебор. Страница со всеми компонентами не такая уж длинная. Даже если со временем она увеличится в 2-3 раза, всё равно будет не так много.
Пользователь может использовать встроенный поиск по странице.

Ещё стоит добавить компоненты из папки `internal`. Некоторые контролы можно протестировать, только с ними. У `ComboBox`а так вообще все дата-тиды в `internal/CustomComboBox` лежат.

Накидал тут макет:
| ![image](https://user-images.githubusercontent.com/2708211/172412885-5795d2d4-5387-462e-881d-bc124ec1f769.png) |
| --- |

2022-06-08 05:20 UTC, HelenaIsh commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
По поводу внутренних компонентов обсуждали [вот здесь](https://github.com/skbkontur/retail-ui/pull/2900#discussion_r889729210). Решили, что не будем api внутренних компонентов делать публичным

2022-06-08 08:17 UTC, lossir commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
К слову, по макету. Может слева стоит писать полностью имя?

### `FileUploader`
| `FileUploaderDataTids.root` | `FileUploader__root` |
| :-- | :-- |
| `FileUploaderDataTids.content` | `FileUploader__content` |

2022-06-08 08:30 UTC, HelenaIsh commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
> Может слева стоит писать полностью имя?

Мне кажется, получится дублирование

Мне понравился твой первый вариант, только я бы написала название переменной (по ней будет понятно название компонента)

### `FileUploaderDataTids`
| `root` | `'FileUploader__root'` |
| :-- | :-- |
| `content` | `'FileUploader__content'` |

2022-06-08 09:12 UTC, lossir commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
Хм... а мне кажется наоборот, название компонента надо оставить. Визуально так проще найти нужный компонент, т.к. в названии нет непривычных префиксов/постфиксов.
А полный путь переменной `FileUploaderDataTids.root` проще скопировать, чтобы сразу в код вставить. Автоимпорт уже сам её подтянет.

Но это не принципиально, я ориентируюсь только на свой разработческий UX.

2022-06-08 09:25 UTC, HelenaIsh commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
Звучит логично! Внесла правки =)

2022-06-08 14:23 UTC, JackUait commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
> Думаю, это немного перебор. Страница со всеми компонентами не такая уж длинная. Даже если со временем она увеличится в 2-3 раза, всё равно будет не так много.
Пользователь может использовать встроенный поиск по странице.

Это же не связанные кейсы. То, что мы можем найти нужный компонент/дата-тид с помощью поиска по странице не отменяет того, что мы можем добавить инструмент, который будет помогать пользователю совершать этот поиск

Если проводить аналогию с иконками: зачем нам нужны инструменты для модифицирования внешнего вида иконок в доке, если мы можем то же самое сделать через девтулзы? Потому что через девтулзы это делать не так удобно

2022-06-08 15:15 UTC, lossir commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
В текущем виде не представляю, как бы мне помог этот фильтр. В большинстве компонентов по одному дата-тиду. Когда я фильтровал по компоненту, и появилась всего одна строка, моя первая мысль была: «_Это всё..? Всего один? Может что-то не подгрузилось..._». Я выключил его, начал скролить и искать браузерным поиском. 

Т.е. лично меня он сбил с толку. А браузерный поиск и просто скроллинг покрыли все мои требования по поиску. Ещё вот нейминг был неудобен, и я предложил макет.
Не понимаю, какой сценарий закрывает этот фильтр, поэтому и предлагаю от него избавиться.

Когда мы придумаем, как показывать дата-тиды внутренних компонентов через публичные ручки, то в сумме их станет в полтора-два раза больше. Тогда, думаю, будет смысл подумать над кастомными инструментами поиска. 

Аналогия с иконками мне кажется не корректная. В доке у нас песочница, которая позволяет не только пропы поменять, но и вёрстку накидать или скрипт протестировать - девтулз такое не умеет.

2022-06-08 16:17 UTC, JackUait commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
> А браузерный поиск и просто скроллинг покрыли все мои требования по поиску.

Но это же личные предпочтения) Мне например, удобнее было искать через интерфейс, который реализовала Лена, вероятно есть и другие пользователи, которым будет удобнее пользоваться подобным интерфейсом

Если отойти от личных предпочтений - этот интерфейс в худшем случае не мешает пользователям, а в лучшем помогает выполнять поиск по дата-тидам

> Когда мы придумаем, как показывать дата-тиды внутренних компонентов через публичные ручки

Мы уже сейчас умеем показывать `data-tid`'ы внутренних компонентов через публичные ручки, но так как доступ к ним получается именно из главного компонента, то и ищутся они по имени главного компонента. Так, например, в `DatePicker` есть поле, которое называется `pickerRoot` и предоставляет доступ к корневому 
 `data-tid`'у `Picker`'а

> В доке у нас песочница, которая позволяет не только пропы поменять, но и вёрстку накидать или скрипт протестировать - девтулз такое не умеет

Конкретно в доке с иконками такая же история, как и в доке с дата-тидами. Там нет возможности протестировать пропы или скрипт, так как иконки поставляются в виде монолитного компонента с одним пропом

А все рычажки, которые я настроил контролируются через стили иконки, так что их можно самостоятельно накидать в девтулзах, так же как и дополнительную вёрстку

2022-06-08 16:17 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +export const DataPickerDataTids = {
```suggestion
export const DatePickerDataTids = {
```

2022-06-08 19:03 UTC, lossir commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
> Но это же личные предпочтения)

Ну да. Без опросов и статистики, в плане UX я могу только на свой опыт ориентироваться.

> Мы уже сейчас умеем показывать data-tid'ы внутренних компонентов

А что на счёт `CustomComboBox` внутри `ComboBox` или `FileUploaderFile` внутри `FileUploader`?

> Конкретно в доке с иконками такая же история...

Сори, я сразу не заметил =)

> ... можно самостоятельно накидать в девтулзах, так же как и дополнительную вёрстку

Вёрстку в девтулзах - это как? Не знаю такой фичи... Надеюсь, речь не про вкладку `Elements`? =)

Пропы у меня, кстати, через девтулз не редактируются. Нашёл только [такое пояснение](https://github.com/facebook/react-devtools/issues/1179#issuecomment-444652589) в старой репе самого девтулза. И вроде там же чел что-то [законтребьютил](https://github.com/facebook/react-devtools/pull/1249), но может это не попало в новую репу, хз.

---

Подобная панель инструментов, с одной стороны, даёт интересный функционал, но с другой - им же меня и ограничивает.

Думаю, было бы удобнее, если такие "панели" были в виде простых обёрток и настраивались пропами в самой песочнице. Без необходимости лезть в девтулз за банальным изменением шрифта. А то тексом написано `если задать иконке размер '35', то иконка размера '32' будет растянута до размера '35'` а проверить по быстро не понятно как.
А рядом, в другой песочнице, эти иконки должны быть без всяких обёрток. В идеале с парой примеров использования с контролами и аддонами.

---

В итоге, по-моему, панель в иконках слишком выбивается из общего стиля документации, даёт некоторые фичи, но ограничивает привычные возможности, которые доступны пользователям на страницах старых иконок, логотипов, аддонов и контролов.

---

Вернёмся к фильтру дата-тидов. Предлагаю, отдать на откуп лене Лене. Она почитает наши аргументы и решит сама. Мне это не принципиально, поэтому я выбрал у ревью тип `Comment` ))

2022-06-09 05:27 UTC, lossir commented on packages/react-ui/internal/Calendar/Calendar.tsx
> + * root: 'Calendar__root',
Именно. И такие тесты развалятся, если кто-то уже подвязался. Но при этом мы не закроем никаких проблем.
Ни пользователям ни разработчикам это ничего не даст, ни в моменте ни в будущем, но тесты править придётся... Считаю, что простое единообразие строковых значений дата-тидов этого не стоят.

2022-06-09 08:01 UTC, HelenaIsh commented on packages/react-ui/lib/data-tid/DataTids.tsx
> +        <Select<string> items={this.items} value={this.state.selectedValue} onValueChange={this.setValue} search />
Спасибо за ваши мнения =) Я решила вернуть Select с фильтрацией по компонентам

2022-06-09 21:21 UTC, JackUait commented on packages/react-ui/internal/Calendar/Calendar.tsx
> + * root: 'Calendar__root',
Преимущество в том, что мы создаём предсказуемую систему поиска по `data-tid`'ам кровью нескольких сотен упавших тестов в рамках всего Контура. То есть разработчик или тестировщик (такой сценарий скорее необходим тестировщику) зная только название компонента, сможет найти нужный ему компонент на странице или в тесте

Я вижу этот сценарий как основной для E2E тестов, так как в них тестировщик будет искать корневую ноду компонента, которую дальше уже будет раскручивать удобным для него способом. В сценарии, когда все названия `data-tid`'ов написаны по конвенции - для того, чтобы найти ноду тестировщику всего лишь нужно будет дописать к названию компонента `__root`. В текущем сценарии, для 6 компонентов, которые не следуют конвенции, тестировщику придётся постоянно заглядывать в доку, чтобы найти нужную ему ноду, так как у нас есть четыре дополнительных стиля написания названий `data-tid`'ов, помимо основного с двойным подчёркиванием

Как небольшой плюс ещё можно выделить то, что унифицирование названий `data-tid`'ов - это `future proof` решение. Плюс небольшой, так как я пока не вижу дополнительных сценариев, в которых понадобится унификация, но это не отменяет того, что эти сценарии могут появиться в будущем

2022-06-10 10:23 UTC, lossir commented on packages/react-ui/internal/Calendar/Calendar.tsx
> + * root: 'Calendar__root',
Сценарий, когда тестировщик "вслепую" указывает дата-тид, не проверяя на какой именно дом-элемент он навешан, и пытается как-то его протестировать, мне сложно представить.
Мне представляется, что тестировщик обязательно пойдёт во вкладку `Elements`, чтобы понять как удобнее выхватить нужный дом-элемент, и что конкретно с ним можно сделать.

Из всех обращений по дата-тидам, на моей памяти, ни одно не каcалось их разномастных названий. Поэтому предлагаю решать проблемы по мере поступления.
Всё-таки это ломающее изменение здесь и сейчас. Если бы на них можно было код-мод написать, то другое дело.

2022-06-10 15:16 UTC, JackUait submitted a review, later dismissed

2022-06-10 15:21 UTC, JackUait commented on packages/react-ui/internal/Calendar/Calendar.tsx
> + * root: 'Calendar__root',
Как вариант, мы можем написать `ESLint` плагин, который будет это фиксить

2022-06-15 09:48 UTC, lossir commented on packages/react-ui/internal/DataTids/componentsDataTids.ts
> +        .join(', \n'),
Здесь дата-тиды из массива массивов конвертируются в строку такого вида:
```json
"Loader__Veil', \nspinner: 'Loader__Spinner"
```

А потом обратно конвертируются в массив массивом 🙃
https://github.com/skbkontur/retail-ui/blob/599f8f4fda6aa78a67c7ef9db9a74ab0b8d74ce7/packages/react-ui/internal/DataTids/DataTids.tsx#L28-L31

---

К тому же обратная конвертация оставляет артефакты:
| ![image](https://user-images.githubusercontent.com/2708211/173795899-8b676214-c7ae-41d0-9990-ec497088310d.png) | ![image](https://user-images.githubusercontent.com/2708211/173797475-dc06f30d-4c6c-4ab2-bae2-1dfc791a57ab.png) |
| --- | --- |

---

Т.е. эти конвертации можно просто удалить и ничего не сломается. Даже лучше станет =)

2022-06-20 21:31 UTC, JackUait approved these changes
По моим комментам - всё. Максим (@lossir), глянь пожалуйста, можем ли мы вливать изменения

2022-06-28 07:03 UTC, JackUait approved these changes

2022-06-28 11:48 UTC, lossir approved these changes

2022-06-28 11:52 UTC, merged