fix(MaskedInput): accept null as value
skbkontur/retail-ui pull request #2902
Opened 2022-05-31 17:34 UTC by JackUait

fixes #2901

Смотри только [последний](https://github.com/skbkontur/retail-ui/commit/2c263b4ef1e1280e97589594cac046b7d4f7aebe) (2c263b) коммит, все предыдущие коммиты относятся к #2791

Инпут с маской крашится, если передавать в него `null`, в качестве `value`. Код для воспроизведения:
```tsx
<Input mask="9" value={null} />;
```

Проблема заключалась в том, что в функции `getValue` была строгая проверка на `undefined`, так как что библиотечный `Input`, что реактовский `HTML`-инпут официально могут обрабатывать только `undefined` (на самом деле ограничение надуманное, чуть ниже объясняю почему). Не вижу ничего плохо, в том чтобы добавить проверку на `null` + `undefined` для этого случая

Но не думаю, что официальное добавление поддержки `null` в `Input` - это хорошая идея, так как `React`'у не нравится, когда в качестве `value` в инпут передаётся `null` и он выкидывает ворнинг в консоль, при этом `React` считает, что как `null`, так и `undefined` делают инпут неконтролируемым. В репе `React`'а есть [тред](https://github.com/facebook/react/issues/11417), в котором автор треда предлагает относиться к `null` как к пустой строке, но Дэн Абрамов [справедливо](https://github.com/facebook/react/issues/11417#issuecomment-413240002) замечает, что между `null` и `undefined` нет очевидной разницы и предлагает не менять поведение (но при этом не объясняет почему `null` выкидывает ворнинг)

Также менеджер `React`'а в этом же треде [пишет](https://github.com/facebook/react/issues/11417#issuecomment-340950725) следующее:
> Also, all of our host/DOM components treat null and undefined identically right now, I believe.

Но при этом `null` всё равно выкидывает ворнинг, а  `undefined` - нет

Если я упустил объяснение того, почему `null` выкидывает ворнинг - буду рад, если поделитесь со мной:)

2022-06-03 09:09 UTC, zhzz requested changes
> Смотри только [последний](https://github.com/skbkontur/retail-ui/commit/2c263b4ef1e1280e97589594cac046b7d4f7aebe) (2c263b) коммит, все предыдущие коммиты относятся к https://github.com/skbkontur/retail-ui/pull/2791

Что? Зачем ты пытаешься влить часть #2791 здесь?

2022-06-03 11:11 UTC, JackUait commented
> Что? Зачем ты пытаешься влить часть https://github.com/skbkontur/retail-ui/pull/2791 здесь?

Там произошли изменения, которые затрагивают код из пулл-реквеста
В принципе можно сделать ветку из #2791 базовой и `GitHub` сам перестроит историю, когда #2791 будет смёржена в мастер (что и сделал)

2022-06-03 11:15 UTC, JackUait commented on packages/react-ui/internal/MaskedInput/__tests__/MaskedInput-test.tsx
> +    mount(<MaskedInput value={null} mask="99:99" />);
Или может есть более элегантный способ реализовать эту же/подобную логику (в смысле без создания дополнительной функции)

2022-06-03 14:42 UTC, zhzz commented on packages/react-ui/internal/MaskedInput/__tests__/MaskedInput-test.tsx
> +    mount(<MaskedInput value={null} mask="99:99" />);
Мы уже обсуждали, что явный expect всегда должен быть. Я бы даже [eslint-правило](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/expect-expect.md) такое втащил.

Твой пример из коммента будет работать не как ожидается: `mount` нужно вызывать внутри  `expect`.   Корректный пример есть выше в файле. Мне он не кажется монструозным.

2022-06-04 20:35 UTC, JackUait commented on packages/react-ui/internal/MaskedInput/__tests__/MaskedInput-test.tsx
> +    mount(<MaskedInput value={null} mask="99:99" />);
Я предлагаю придерживаться только тех стилистических правил, которые находят линтеры, иначе мы можем очень долго обсуждать и спотыкаться об различные стилистические моменты обговоренные только на словах, что будет сильно тормозить разработку

Об этих правилах линта не знал, добавил правила из этого пакета в #2906

2022-06-05 18:09 UTC, zhzz commented on packages/react-ui/internal/MaskedInput/__tests__/MaskedInput-test.tsx
> +    mount(<MaskedInput value={null} mask="99:99" />);
Справедливо

2022-06-05 18:09 UTC, zhzz approved these changes

2022-06-09 07:19 UTC, lossir approved these changes

2022-06-09 11:26 UTC, merged