chore(eslint): jest rules
skbkontur/retail-ui pull request #2906
Opened 2022-06-04 01:36 UTC by JackUait

Добавил в линтинг правила из [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest)

Каждый коммит начинающийся с `chore(eslint)` покрывает одно правило или ряд рекомендованных правил

В первом коммите содержатся правила, которые автоматически пофиксились после запуска команды `yarn fix:eslint`, его можно не проверять

2022-06-04 20:10 UTC, JackUait commented
Удалил все закоментированные тесты в `no-commented-out-tests`, так как они тестировали не поведение, а `UI`, то есть должны быть протестированы через скриншоты, но так как в них тестируется анимация даже не стал пробовать воспроизводить их в скриншотах, думаю, лучшее решение - полностью отказаться от этих тестов в силу сложностей с тестированием анимации и отсутствием большого профита от подобных тестов

2022-06-04 20:40 UTC, JackUait commented
В `no-conditional-expect` удалил тест `passes props to input`, так как в тестировании этого поведения в рамках интеграционного теста нет смысла

2022-06-14 11:51 UTC, khlutkova commented
Линт в валидациях проверь, пожалуйста

2022-06-16 09:47 UTC, JackUait commented
Хмм, глобальный `.eslintrc` очень странно работает: некоторые правила он спокойно прогоняет и в других пакетах, а вот правила из пакетов `eslint-plugin-jest` и `@emotion/eslint-plugin` почему-то прогонять не хочет. Вообще это для большинства пакетов с линтингом работает, потому что у наших пакетов общий `yarn.lock`, но нужно углубиться в эту тему и понять почему это не работает для всех пакетов

<hr />

Перенёс правило из глобального `.eslintrc` в `.eslintrc` пакета `react-ui`, после чего прогнал оба линтинга

2022-06-23 15:32 UTC, zhzz requested changes
Там еще остались варнинги.

![image](https://user-images.githubusercontent.com/4607770/175337557-ca66ccd9-1bde-4479-a484-2de0a5818b3c.png)

2022-06-23 15:32 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/__tests__/CustomComboBoxReducer-test.tsx
> +    it(`ValueChange after UnexpectedInput with expectedDispatch = true (test ${index + 1})`, () => {
Про какой `expectedDispatch` теперь речь? Он же удален.

2022-06-23 15:32 UTC, zhzz commented on packages/react-ui/.eslintrc
> +        "jest/max-nested-describe": 2
Это исключение из `recommended` точно нужно?

2022-06-24 18:55 UTC, JackUait commented on packages/react-ui/.eslintrc
> +        "jest/max-nested-describe": 2
По дефолту в этом правиле стоит пятый уровень вложенности. Думаю, что второй уровень вложенности оптимальный. Так мы сможем при необходимости структурировать код и не создадим локальный коллбэк-хелл в тестах

2022-06-24 20:07 UTC, JackUait commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> -
1. Мы просто проверяем, что можем передать какой-то набор пропов на инпут (причём не полный). Для этого у нас уже есть тест `PropsForwarding` и в нём есть смысл, так как мы проверяем, что передаём в компоненты обязательные пропы. В этом тесте конечно немного другой посыл - проверить, что какие-то пропы были переданы на инпут, но с точки зрения пользователей это не имеет значения, а тогда когда это имеет значение - нам другие тесты покажут что что-то пошло не так, например для пропов `placeholder` или `type`. Нам же этот тест в большинстве случаев будет только вставлять палки в колёса, так как если нам понадобится куда-то переместить определённый проп, то нам придётся переписывать это тест, если же мы где-то напортачим при перенесении пропа - нам это должны будут показать другие тесты, этот тест не защитит нас от того, что мы перенесли проп как-то неправильно. То есть этот тест ничто большее как тестирование деталей реализации без выгоды ни для нас, ни для пользователей
2. Этот тест гораздо сложнее воспроизвести в `RTL`, так как она не предоставляет прямой доступ к пропам в отличие от `Enzyme`, в целях стимулирования написания тестов, которые проверяют то, как пользователь взаимодействует с компонентом, а не детали реализации

2022-06-24 20:22 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/__tests__/CustomComboBoxReducer-test.tsx
> +    it(`ValueChange after UnexpectedInput with expectedDispatch = true (test ${index + 1})`, () => {
Поправил

2022-07-11 06:52 UTC, zhzz commented on packages/react-ui/.eslintrc
> +        "jest/max-nested-describe": 2
1. Тут ты не меняешь дефолтное значение на 2, а включаешь правило в режиме ошибки. Оно не входит в список рекомендуемых.
2. Лично я не вижу проблем со вложенностью describe. Наоборот, если использовать не бездумно, то они хорошо структурируют и позволяют гибко делать beforeEach/afterEach там, где нужно. Например, [тут](https://github.com/skbkontur/retail-ui/blob/7b63c63db36ab0d574ae612cdb6e6c66817f12b5/packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx#L61).

2022-07-11 06:56 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/__tests__/CustomComboBoxReducer-test.tsx
> +    it(`ValueChange after UnexpectedInput with expectedDispatch = true (test ${index + 1})`, () => {
Всегда выводит `items[0]` теперь.

2022-07-11 06:57 UTC, zhzz requested changes
Линт все еще не проходит.

2022-07-11 12:05 UTC, zhzz commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> -
1. Здесь проверяется передача конкретных пропов, потому что все они важны. Согласен, что это может быть не лучшая форма и место для этого теста. Вообще-то эта функциональность нужна всем Input-подобным компонентам. И может быть общий тест где-то в отдельной секции `PropsForwarding` был бы лучше. И проверять возможно лучше подругому, так как это позволяет RTL. Но смысл в тесте есть, т.к. функциональность нужна пользователю. А других тестов на большинство из этого прямо сейчас нет, и ты их не предлагаешь. Выходит, просто так удалить тест нельзя.

2022-08-11 21:49 UTC, JackUait commented on packages/react-ui/.eslintrc
> +        "jest/max-nested-describe": 2
Удалил переопределение правила

2022-08-11 22:22 UTC, JackUait commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> -
В общем, пока оставил этот тест на `Enzyme`, а проблему вынес в новую задачу - IF-687

Из подобных тестов можно выжать пользу для нас, но для этого нам понадобится написать кастомное (или поискать готовое) решение, которое позволит нам автоматизировать процесс тестирования этой логики, это должно быть что-то вроде скриншотных/снэпшот тестов, но для пропов. Так мы не перестанем вставлять палки себе в колёса, но научимся эффективно их доставать

Но вообще, в моих глазах эти тесты - при любом раскладе костыль. Но пока у нас нет достаточного покрытия тестами, он нам поможет найти проблемные места в нашем тестировании, а также поможет с переездом на функциональные компоненты и мог помочь с дефолтными пропами и задачами подобного рода

(но если учитывать, что в нашей кодовой базе будут так или иначе появляться новые фичи и компоненты - от этого типа тестирования мы не сможем отказаться никогда)

2022-08-12 00:37 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/__tests__/CustomComboBoxReducer-test.tsx
> +    it(`ValueChange after UnexpectedInput with expectedDispatch = true (test ${index + 1})`, () => {
В `Effect.unexpectedInput` при длине массива `items` равной единице, функция `dispatch` всегда вызывается с `items[0]`:
```ts
// CustomComboBoxReducer.tsx -> Effect.unexpectedInput
...
if (Array.isArray(items) && items.length === 1) {
  const singleItem = items[0];
  const valueContent = getValueString(singleItem, valueToString);

  if (valueContent === textValue) {
    dispatch({ type: 'ValueChange', value: singleItem, keepFocus: false });
    return;
  }
}
...
```

У нас как раз эта ситуация

Но так как у нас одинаковые объекты что в первом, что во втором кейсе, добавил в тайтл переменную `inputValue`

2022-08-12 09:44 UTC, zhzz requested changes

2022-08-12 09:44 UTC, zhzz commented on packages/react-ui/.eslintrc
> +        "import/no-default-export": 0
Удалил плагин и правило для `@emotion`?

2022-08-12 11:03 UTC, JackUait commented on packages/react-ui/.eslintrc
> +        "import/no-default-export": 0
Да, похоже, что `emotion`-новский плагин несовместим с этим плагином. Он во всех совместимых с `glob`'ом файлах выкидывает ошибку:
```diff
- Definition for rule '@emotion/no-vanilla' was not found
```

Эта несовместимость может проявляться как на уровне всего пакета, так и на уровне одного правила. Пока добавлял линтинг я довольно часто встречался с этой ошибкой, но ни разу её не удалось пофиксить. Единственный рабочий способ фикса бага который я видел - написать создателям плагина, чтобы они починили)

Создал [коммит](https://github.com/skbkontur/retail-ui/pull/2906/commits/43230c3b74937bf5a596f40c44beb974641b536c), чтобы это продемонстрировать. Упавший [пайплайн](https://tc.skbkontur.ru/viewLog.html?buildId=27236764&buildTypeId=FrontendInfrastructure_Packages_ReactUI_LintTest&tab=buildLog&_focus=1887#_state=168) из коммита

2022-08-12 11:34 UTC, zhzz commented on packages/react-ui/.eslintrc
> +        "import/no-default-export": 0
Значит нужно удалить плагин целиком из зависимостей

2022-08-12 11:46 UTC, JackUait commented on packages/react-ui/.eslintrc
> +        "import/no-default-export": 0
Уже удалил в [2e60fe685](https://github.com/skbkontur/retail-ui/pull/2906/commits/2e60fe68501cd3b5b1df60e6479ba36b15bc46d4)

2022-08-12 12:06 UTC, zhzz approved these changes

2022-08-15 05:07 UTC, merged