Типы в defaultProps - 2
skbkontur/retail-ui pull request #2915
Opened 2022-06-17 07:48 UTC by HelenaIsh

Была неудачная попытка исправить default props в #2760 

Было решено сделать все пропы, которые есть в `defaultProps` опциональными, прописыв для `defaultProps` корректный тип через `<Partial<P>>`

2022-06-26 23:06 UTC, JackUait requested changes

2022-06-28 02:09 UTC, JackUait commented on packages/react-ui/components/Radio/Radio.tsx
> +  public static defaultProps: Partial<RadioProps<any>> = {
В компонентах `Select`, `TokenInput`, `ComponentCombinator`, `ComponentTable`, `ComboBoxMenu` и `ComboBoxView` ещё остались `any`

2022-06-29 07:30 UTC, HelenaIsh commented on packages/react-ui/components/Radio/Radio.tsx
> +  public static defaultProps: Partial<RadioProps<any>> = {
в TokenInput не получилось заменить `any` на `unknown` из-за конфликта с типами дефолтных методов

2022-06-29 09:44 UTC, JackUait commented on packages/react-ui/components/Radio/Radio.tsx
> +  public static defaultProps: Partial<RadioProps<any>> = {
Для `TokenInput` нужно расширять дженерик с помощью других типов:
```ts
const defaultToKey = <T extends Record<string, unknown>>(item: T): string => item.toString();
const identity = <T extends unknown>(item: T): T => item;
```

2022-06-29 09:46 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> +interface FocusableReactElement extends React.ReactElement<unknown> {
Не в том месте добавила `unknown` в `Select`'е

2022-06-29 11:24 UTC, JackUait commented on packages/react-ui/components/Radio/Radio.tsx
> +  public static defaultProps: Partial<RadioProps<any>> = {
Похоже, что всё-таки в `TokenInput` не получится избавиться от `any`. Когда в мастере будет #2803, `string` и любой другой тип кроме `any` - упадёт. Давай тогда не будем заморачиваться и оставим там `any`

2022-06-29 12:31 UTC, JackUait approved these changes

2022-06-29 13:06 UTC, zhzz requested changes

2022-06-29 13:06 UTC, zhzz commented on packages/react-ui-validations/src/ValidationContainer.tsx
>  }
Почему выбрали `non null assertion`? Мы же так боролись за чистоту и культуру кода в задаче с `eslint`. На то, что это временно и мы скоро все отрефакторим при переходе на функциональные компоненты лучше не надеяться - эта задача может растянуться на годы, а нам тем временем с этим жить.

Обсуждались другие варианты?

2022-06-29 20:40 UTC, JackUait commented on packages/react-ui-validations/src/ValidationContainer.tsx
>  }
Да, другие варианты обсуждались, но этот показался самым оптимальным, так как мы в #2803 избавились от всех `non-null assertion` - теперь мы можем быть уверены, что все имеющиеся `non-null assertion` относятся к `defaultProps`, а новые `non-null assertion`'ы если и появятся в коде - не должны пройти ревью

От других вариантов будет сложнее избавляться впоследствии и они сильнее засоряют код здесь и сейчас

2022-06-30 08:31 UTC, zhzz commented on packages/react-ui-validations/src/ValidationContainer.tsx
>  }
То есть, теперь на ревью нужно будет дополнительно глазами смотреть, а не использовал ли кто `!`? Объяснять всем, что вообще-то у нас `non-null-assertion`  запрещен, и на этих файлах тоже, хоть линт и не работает. Зачем нам тогда eslint-правило, если на него нельзя положиться? 

Ревью ненадежный и дорогой способ контроля стиля кода. Линт создан для этого.

Можно снова вернуться к уже существующему как раз для этого `createPropsGetter`. Его будет просто использовать, и так же просто избавиться от него. Только в типах для `defaultProps` придется отказаться от `Partial`, и перейти, вероятно, на описание всего типа вручную. Но так типы будут даже корректнее. И спать по ночам спокойнее.

2022-07-10 15:04 UTC, JackUait commented on packages/react-ui-validations/src/ValidationContainer.tsx
> +};
С таким подходом нам придётся контролировать типы пропов сразу в двух местах. Предлагаю сделать так:
```ts
type DefaultProps = Required<Pick<ValidationContainerProps, 'disableSmoothScroll'>>;
```

2022-07-11 15:04 UTC, JackUait commented
Появился конфликт с мастером

2022-07-11 15:52 UTC, JackUait requested changes

2022-07-11 15:52 UTC, JackUait commented on packages/react-ui/components/Button/Button.tsx
> +    type: 'button',
Обращение ко всем пропам из `defaultProps` происходит через прямое обращение к `this.props`, а не через метод `getProps`. Если где-то ниже в иерархии компонентов поменяется тип пропов, то это может привести к тому, что в этом компоненте будет возникать ошибка типов. Следовательно, вне зависимости от того выдает код в данный момент ошибку или нет - нужно использовать `getProps`

<hr />

Это встречается не только в компоненте `Button`, так что нужно найти и поправить все места, где для получения значения из `defaultProps` не используется `getProps`

2022-07-11 15:52 UTC, JackUait commented on packages/react-ui/components/Center/Center.tsx
> +  public static defaultProps: Partial<CenterProps> = {
А почему здесь остался старый подход?

Комментарий из `Button` также применим и здесь

2022-07-11 15:52 UTC, JackUait commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +  public static defaultProps: DefaultProps<any> = {
Напоминаю, что обговаривали, что для таких случаев будет использоваться `unknown` вместо `any`

2022-07-18 09:44 UTC, HelenaIsh commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +  public static defaultProps: DefaultProps<any> = {
В `ComboBox` и `TokenInput` не получилось избавиться от `any`

2022-07-21 12:27 UTC, dzekh commented
А этот ПР закроет #2553 ?

2022-07-21 12:33 UTC, HelenaIsh commented
> А этот ПР закроет https://github.com/skbkontur/retail-ui/issues/2553 ?

да

2022-07-24 23:00 UTC, JackUait approved these changes

2022-07-25 09:54 UTC, zhzz requested changes

2022-07-25 09:54 UTC, zhzz commented on packages/react-ui/components/ComboBox/ComboBox.tsx
> +        renderItem={this.getProps().renderItem}
Здесь не вышло сделать просто `{...this.getProps()}`? Это плохой знак. По идее `this.getProps()` должно быть возможно использовать во всех тех же местах, что и `this.props`. Он ведь так же возвращает все пропы, но с более точными типами. Если так не получается, то где-то есть проблема.

Если посмотреть внимательно на реальный тип, возвращаемый из `this.getProps` то видно, что сейчас там есть только дефолтные пропы. Видимо, в этом и проблема - должны быть все. Наверное, сломалось когда-то давно при обновлении `typescript` и `P` внутри `createPropsGetter` перестал корректно выводится.

Я чуток подправил в [отдельной ветке](https://github.com/skbkontur/retail-ui/compare/default-props-2...default-props-2.1), и проблема ушла. Ограничения на использование `this.getProps()` пропали.

2022-07-26 09:06 UTC, zhzz requested changes

2022-07-26 11:28 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> -    inputMode: 'decimal',
потому что: 
1. Он нигде не используется 2. Раньше у дефолт пропсов не было типа и поэтому не было заметно, что этого пропа нет и в `InputProps` от которого наследуются `CurrencyInputProps`

2022-07-26 14:08 UTC, zhzz commented on packages/react-ui/components/CurrencyInput/CurrencyInput.tsx
> -    inputMode: 'decimal',
Он в итоге прокидывается в нативный `input`, чтобы настроить клавиатуру на мобильных устройствах. В `InputProps` он есть, наследуется из `React.InputHTMLAttributes<HTMLInputElement>`.

2022-07-27 09:09 UTC, zhzz commented on packages/react-ui/components/FxInput/FxInput.tsx
> +    const { type: typeWithDefaultValue, value } = this.getProps();
Не заметил, что в некоторых из тех случаев были задействованы `CommonWrapperRestProps`. Они по прежнему нужны, поэтому вернул их и поправил типы с учетом дефолтных.

2022-07-27 09:12 UTC, zhzz approved these changes

2022-07-27 12:59 UTC, JackUait approved these changes

2022-07-27 13:15 UTC, merged