docs(Checkbox): indeterminate common use case
skbkontur/retail-ui pull request #2919
Opened 2022-06-22 13:11 UTC by JackUait

fixes [IF-547](https://yt.skbkontur.ru/agiles/101-1467/current?issue=IF-547)

Добавил скриншотных тестов для проверки самого распространенного (и вероятно единственного) сценария использования `indeterminate` состояния чекбокса. Для этого сценария это состояние изначально в библиотеку и добавлялось (#812), но в #820 оно почему-то не было протестировано

2022-07-01 18:07 UTC, lossir requested changes

2022-07-01 18:07 UTC, lossir commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +    }
Состояние `indeterminate` уже неплохо покрыто тестами в стори `IndeterminatePlayground`.
А здесь тестируется только логика самой стори.

Я могу предположить, что как готовый пример имплементации сценария из гайдов это может быть полезно.
Но зачем это тестировать?

Думаю, в качестве примера на витрине это будет намного уместнее и полезно пользователям. А стори и тесты предлагаю удалить.

2022-07-07 11:56 UTC, JackUait commented on packages/react-ui/components/Checkbox/__stories__/Checkbox.stories.tsx
> +    }
Согласен, в качестве примера в доке от этого кода будет гораздо больше пользы, поправил

2022-07-22 16:49 UTC, JackUait commented
POV: Вова (@dzekh) и Максим (@lossir) перетаскивают тасочки, чтобы биг-дата была рада))
<img width="863" alt="Снимок экрана 2022-07-22 в 19 44 31" src="https://user-images.githubusercontent.com/48599460/180486634-a6a80717-992a-480a-914e-3ee657d0b28d.png">

2022-07-25 07:42 UTC, merged