fix(getRootNode): defaultRootNode & content container instead of anchorElement
skbkontur/retail-ui pull request #2923
Opened 2022-06-23 14:04 UTC by JackUait

2022-06-24 07:57 UTC, khlutkova commented on packages/react-ui/components/Hint/Hint.tsx
> +import { InstanceWithAnchorElement } from '../../lib/InstanceWithAnchorElement';
Ты пытаешься импортить из `../../lib/InstanceWithAnchorElement`, тогда как файл называется `instanceWithAnchorElement`

2022-06-24 10:17 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.tsx
> +import { InstanceWithAnchorElement } from '../../lib/InstanceWithAnchorElement';
Поправил

2022-06-24 10:43 UTC, khlutkova commented on packages/react-ui/components/Hint/Hint.tsx
> +import { InstanceWithAnchorElement } from '../../lib/InstanceWithAnchorElement';
Нет файла `../../lib/InstanceWithAnchorElement`, но есть `../../lib/instanceWithAnchorElement`
И при попытке запустить storybook локально консоль прямо про это говорит

2022-06-24 10:54 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.tsx
> +import { InstanceWithAnchorElement } from '../../lib/InstanceWithAnchorElement';
Это уже какие-то причуды гита, у меня в изменениях на гитхабе отображается файл `instanceWithAnchorElement`, но при этом при мёрже вместо него есть файл `InstanceWithAnchorElement` (который и должен быть). Сейчас залил ещё один коммит, в котором поменял импорты на первую строчную, должно пофиксить проблему

2022-07-04 11:09 UTC, zhzz requested changes

2022-07-04 11:09 UTC, zhzz commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +const TabsWithCustomComponent = ({ component }: { component: React.ComponentType }) => {
Не хватает картинок для этой истории.

2022-07-08 00:53 UTC, JackUait commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +const TabsWithCustomComponent = ({ component }: { component: React.ComponentType }) => {
Докинул скриншоты

<hr />

В `CI/CD` тесты упали, перезапустил их. Прогонял тесты для `Tabs` локально - все прошли

2022-09-15 11:55 UTC, JackUait commented
Внёс правки из #2941, #2960, #2939

2022-10-04 10:55 UTC, zhzz requested changes
Тесты не проходят из-за старого jsdom (зависимость jest), который [некорректно](https://github.com/jsdom/jsdom/pull/2996) отрабатывает событие `focusin`. 

Как вариант, обновить jest во всех пакетах до одной и той же самой высокой версии 26.6.3.

Не стоит тут делать правки в валидации, потому что они уже посути сдаланы в последней версии, которая совместима с LTS.

2022-10-19 10:45 UTC, zhzz approved these changes

2022-10-19 10:50 UTC, merged