IF-540: fix validation for tokenInput
skbkontur/retail-ui pull request #2930
Opened 2022-06-28 09:35 UTC by khlutkova

2022-06-29 08:42 UTC, lossir requested changes

2022-06-29 08:42 UTC, lossir commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> +    this.setRootNode(instance);
Компонент `FileUploader` начал валиться с такой ошибкой:
```diff
Error: Argument appears to not be a ReactComponent. Keys: focus,blur,reset
    at findHostInstanceWithWarning
-   at findDOMNode
    ...
```

Она возникает здесь:
https://github.com/skbkontur/retail-ui/blob/60bb19c881b43cdccb9274b3e7f33222c6213b87/packages/react-ui/lib/rootNode/getRootNode.ts#L55

А причина тут:
https://github.com/skbkontur/retail-ui/blob/60bb19c881b43cdccb9274b3e7f33222c6213b87/packages/react-ui/components/FileUploader/FileUploader.tsx#L179

Т.е. `findDOMNode` пытается вытащить ноду из простого объекта и разваливается.

Как вариант, к этому объекту можно добавить свойство `getRootNode: () => <элемент>`. И тогда хелпер `getRootNode()` достанет ноду не доходя до `findDOMNode`.

2022-06-30 16:50 UTC, lossir commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> -    return this.props.errorMessage(<span ref={this.setRootNode}>{clonedChild}</span>, !!validation, validation);
Надо вернуть здесь рефку.

Сейчас валидация не разваливается, но `this.getRootNode()` не проходит проверку `instanceof HTMLElement` ,т.к. возвращает функцию, из которой невозможно вытащить элемент. Из-за этого на `FileUploader` не работают 2 фичи валидации:
1. Промотка страницы до контрола (`Input -> #3 Промотка сообщении`)
2. Выбор контрола, который выше всех на странице (`Input -> #6 Выбор первого контра для валидации`)

Реализация `rootNode` довольно сложная, и я так до конца не понял всей логики. Но нашёл один баг, который опишу в отдельно.

2022-07-01 09:17 UTC, khlutkova commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> -    return this.props.errorMessage(<span ref={this.setRootNode}>{clonedChild}</span>, !!validation, validation);
Здесь возвращать рефку не надо, она проставляется внутри clonedChild, потому что в некоторых компонентах этот спан отбрасывается (подробнее в описании к пр)

С последней правкой фичи 3 и 6 с FileUploader работают

2022-07-01 13:55 UTC, lossir approved these changes

2022-07-01 13:55 UTC, lossir commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> -    return this.props.errorMessage(<span ref={this.setRootNode}>{clonedChild}</span>, !!validation, validation);
Ок. Получается, что у тех кто использует нашу валидацию с собственными контролами могут отвалиться эти фичи, если они используют хук `useImperativeHandle` и не возвращают `getRootNode: () => ref`.

В перспективе эти [обёртки хочется убрать](https://github.com/skbkontur/retail-ui/pull/2908#discussion_r892205440), поэтому решение кажется приемлемым.

2022-07-11 09:23 UTC, JackUait requested changes
Нужно покрыть тестами этот код

2022-07-11 09:31 UTC, zhzz requested changes

2022-08-12 11:54 UTC, zhzz commented on packages/react-ui-validations/src/ValidationWrapperInternal.tsx
> +import { getRootNode } from '@skbkontur/react-ui/lib/rootNode';
Скопировал

2022-08-15 08:59 UTC, lossir commented on packages/react-ui-validations/src/utils/getRootNode/getRootNode.ts
> +  rootNode = findDOMNode(instance);
Почему решил не оставлять try/catch?
Валидации ведь могут использоваться с кастомными компонентами. И при использовании `useImperativeHandle` приложение также рискует крашнуться.

2022-08-16 06:46 UTC, zhzz commented on packages/react-ui-validations/src/utils/getRootNode/getRootNode.ts
> +  rootNode = findDOMNode(instance);
Да, этот фикс будет нужен. Но он делается в отдельной задаче и, фактически, еще в работе. Подумал, что логичнее будет в той задаче попросить продублировать правку сюда, когда она будет готова. Этот код, скорей всего, вольется раньше.

2022-08-16 07:58 UTC, lossir approved these changes

2022-08-17 15:00 UTC, JackUait approved these changes

2022-08-18 12:25 UTC, merged