chore: fix case where findDOMNode crashes app
skbkontur/retail-ui pull request #2939
Opened 2022-07-01 10:54 UTC by lossir

## Проблема

Использование хука `useImperativeHandle` может развалить приложение.
Обнаружил во время ревью фикса другой проблемы связанной с `getRootNode` https://github.com/skbkontur/retail-ui/pull/2930#discussion_r909350929

Там компонент `FileUploader` начал валиться с такой ошибкой:
```diff
Error: Argument appears to not be a ReactComponent. Keys: focus,blur,reset
    at findHostInstanceWithWarning
-   at findDOMNode
    ...
```

Она возникает здесь:
https://github.com/skbkontur/retail-ui/blob/60bb19c881b43cdccb9274b3e7f33222c6213b87/packages/react-ui/lib/rootNode/getRootNode.ts#L55

А причина тут:
https://github.com/skbkontur/retail-ui/blob/60bb19c881b43cdccb9274b3e7f33222c6213b87/packages/react-ui/components/FileUploader/FileUploader.tsx#L179

`findDOMNode` пытается вытащить ноду из простого объекта и разваливается.

Т.е. если пользователь также будет использовать в своём компоненте хук `useImperativeHandle` и обернёт его, например, в Тултип, то его приложение развалится.

## Решение

### `try/catch`
В качестве фикса я использовал `try/catch` которые позволяет приложению просто не крашиться.
Текст ошибки в консоле содержит ссылку на workaround

```diff
-Warning: Argument appears to not be a ReactComponent. Keys: foo
-See workaround https://codesandbox.io/s/getrootnode-useimperativehandle-workaround-qrklrd
```

Тултип и ему подобные контролы всё равно не будут работать, т.к. не смогут достать дом-ноду.

### workaround
Но можно немного доработать объект возвращаемый в `useImperativeHandle`, и всё заведётся.

```jsx
const coolRef = useRef<any>();
useImperativeHandle(ref, () => ({
  ...
  getRootNode: () => coolRef.current
}));
return <span ref={coolRef} />;
```

### workaround 2
Можно ещё просто обернуть пользовательский контрол в `useImperativeHandle` в `span/div` и тогда `findDOMNode` нормально отработает.

## Ссылки

Воспроизведение бага можно посмотреть в песочнице. Там же реализован workaround:
https://codesandbox.io/s/getrootnode-useimperativehandle-workaround-qrklrd?file=/src/App.tsx

По тестам Реакта видно, что `findDOMNode` так и должен себя вести:
https://github.com/facebook/react/blob/main/packages/react-dom/src/__tests__/findDOMNode-test.js#L66-L70

2022-07-11 00:26 UTC, JackUait reviewed
Да, похоже, что с классовыми компонентами (на нашей стороне) можно предложить только обходное решение. С функциональными компонентами в теории можно было бы попробовать использовать [способ](https://github.com/skbkontur/retail-ui/pull/2662#issuecomment-976624883), который мы использовали в `withClassWrapper`

2022-07-11 00:26 UTC, JackUait commented on packages/react-ui/lib/rootNode/__tests__/getRootNode-test.tsx
> +      );
Давай создадим два отдельных компонента в каждом из тестов. Как показывает практика, тесты с условным ветвлением довольно сложно поддерживать

2022-07-11 00:26 UTC, JackUait commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +      e.message + '\nSee workaround https://codesandbox.io/s/getrootnode-useimperativehandle-workaround-qrklrd',
Ссылка на обходное решение плохо считывается в стек трейсе ошибки

<img width="672" alt="Снимок экрана 2022-07-11 в 04 17 43" src="https://user-images.githubusercontent.com/48599460/178167946-b100d96d-9d55-412a-ae0b-5f6a3ec234f6.png">

2022-07-12 08:07 UTC, zhzz commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +      e.message + '\nSee workaround https://codesandbox.io/s/getrootnode-useimperativehandle-workaround-qrklrd',
Да, случай с `useImperativeHandle` мы не учли. Это получается единственный сценарий, fallback для которого нельзя сделать из коробки. И получается, что правки в `3.10.0` с избавлением от `findDOMNode` по факту были ломающими. Но сценарий должен быть довольно редким. И есть способ починить его руками. Поэтому сильно переживать не будем.

Но, всю информацию про этот сценарий и пример исправления лучше вынести в специальную секцию [readme](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/README.md#strictmode). 

А текст ошибки можно сделать кастомный и поточнее, что-то типа 
 `[getRootNode]: сan't fall back to findDOMNode, see http://.../README.md#strictmode`

2022-07-14 10:06 UTC, zhzz commented on packages/react-ui/lib/rootNode/__tests__/getRootNode-test.tsx
> +      expect(rootNode).toBeNull();
Отдельные факты лучше тестировать раздельно. То, что нет исключения - это одно, а что возвращает `getRootNode` - это другое. Тесты на значение из `getRootNode` лучше вынести в секцию выше, рядом с другими такими же.

Еще можно также добавить новых кейсов в секцию с `findDOMNode`.

2022-08-18 12:28 UTC, zhzz requested changes

2022-08-18 12:28 UTC, zhzz commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +  }
Поскольку #2930 влился раньше и там появилась копия `getRootNode.ts` в валидациях, то эти правки нужно будет продублировать и туда.

2022-09-01 11:23 UTC, zhzz commented on packages/react-ui/lib/rootNode/__tests__/getRootNode-test.tsx
> +    });
Какая идея стоит за этими тестами, если `getInstance(..., { noRender: true })` всегда вернет `null`, вне зависимости от первого аргумента?

2022-09-05 07:33 UTC, zhzz commented on packages/react-ui/lib/rootNode/__tests__/getRootNode-test.tsx
> +    });
Похоже, эти сценарии были призваны воспроизвести [этот](https://github.com/facebook/react/blob/cae63505/packages/react-dom/src/__tests__/findDOMNode-test.js#L88-L99), но делали это не совсем корректно. Есть разница между отсутствием рефки и рефки компонента, который уже создан, но еще не смонтирован. Поэтому заменил эти тесты на один корректный.

2022-09-05 09:40 UTC, zhzz commented on packages/react-ui/lib/rootNode/__tests__/getRootNode-test.tsx
> +      );
Больше не актуально

2022-09-05 09:40 UTC, zhzz commented on packages/react-ui/lib/rootNode/getRootNode.ts
> +      e.message + '\nSee workaround https://codesandbox.io/s/getrootnode-useimperativehandle-workaround-qrklrd',
Поправлено

2022-09-05 09:46 UTC, zhzz commented
@lossir @JackUait не могу перезапросить вашего ревью. ПР готов, прошу глянуть.

2022-09-06 02:10 UTC, JackUait approved these changes

2022-09-06 06:17 UTC, lossir commented
👍

2022-09-06 06:35 UTC, merged