fix: add full compatibility with `fbemitter` from older versions
skbkontur/retail-ui pull request #2940
Opened 2022-07-04 19:19 UTC by lossir

## Проблема

Использование контролов `Modal` и/или `SidePage` из разных версий `react-ui` может развалить приложение. 
Я частично решал эту проблему в своё время (#2198, #2199, #2212, #2776), но реализация оказалась не удачной.
Если хоть одна из версий `react-ui` в приложении будет без фикса, то риск критической ошибки остаётся.

## Причина
Контролы `Modal` и `SidePage` могут перекрывать друг друга. Чтобы всё работало, "верхним" надо диактивировать фон и горячие клавиши у "нижних". Для этого `Modal` и `SidePage` используют внутренний компонент `ModalStack`, который при первом монтировании `Modal` или `SidePage` сохраняет в глобальную область `EventEmitter`. Этот эмиттер уведомляет контролы об открытие/закрытии нового `Modal` или `SidePage`.

Проблема возникла после смены эмиттера с `fbemitter` на `eventemitter3` без учета обратной совместимости.
У `fbemitter` нет метода `removeListener()`, а у `eventemitter3` нет метода `remove()`.

Предыдущие фиксы проверяют наличие метода у эмиттера перед вызовом. Но `ModalStack` всё также сохраняет в глобальную область свой эмиттер. Т.е. если у другой версии `react-ui` нет фикса, то приложение развалиться.

Ниже можно увидеть полную картину по всем версиям и их совместимости между собой:

| Ветка релизов | Таблица совместимости |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2708211/177149536-727848dc-5c92-4b85-9acb-e125af58549a.png) | ![image](https://user-images.githubusercontent.com/2708211/177207878-290404a1-d237-4912-9028-edaa6db32482.png) <br>1 - сохранил глобальный emitter <br>2 - использовал глобальный emitter |

## Решение

Предлагаемые правки на ветке релизов отмечены зелёным - мега фикс =)
Теперь не только проверяется наличие нужного метода в эмиттере перед вызовом. Но и добавляется недостающий метод в сам эмиттер. Т.е. другой версии `react-ui` в приложении ничего не надо проверять перед вызовом.

## Ресурсы

Самостоятельные исправления для разных версий описаны здесь:
https://github.com/skbkontur/retail-ui/issues/2197#issuecomment-1173912943

Проверить совместимость версий и workaround'ов можно в этой дэмке:
https://doeurp.csb.app/playgound

2022-07-08 10:21 UTC, zhzz requested changes

2022-07-08 10:21 UTC, zhzz commented on packages/react-ui/lib/ModalStack.ts
> +};
Здесь `remove` добавляется в инстанс `EventEmitter` и перезаписывается каждый раз при добавлении очередной модалки. В итоге он всегда  будет пытаться удалить один и тот же слушатель, добавленный последним. Другие слушатели, если модалок было открыто много, никогда не удалятся. 

Тесты помогли бы это выявить.

В целом, подобный monkey patching модуля мутирует его на уровне всего приложения. В том числе и для пользователей. Если они в своем коде используют ту же версию `eventemitter3` - они получат наши изменения. Это не очень хорошо. Плюс, вторжение во внутреннее устройство модуля может его когда-нибудь сломать.

Гораздо лучше было бы написать свою обертку над EventEmitter, добавив нужное нам api.

2022-08-24 08:22 UTC, lossir commented on packages/react-ui/lib/ModalStack.ts
> +};
Исправил

2022-08-26 11:39 UTC, zhzz requested changes

2022-08-26 11:39 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +// we didn't take this into account when we replaced `eventemitter3` with `fbemitter`.
Все же наоборот, мы заменили `fbemitter` на `eventemitter3`. И в последних версиях используется `eventemitter3`.

2022-08-26 11:39 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Зачем возвращать объект, наследующий Emitter со всеми его методами, если старый `fbemitter.addListener` возвращал [объект подписки](https://github.com/facebookarchive/emitter/blob/master/src/EventSubscription.js), у которого только один метод `remove`?

2022-08-26 11:39 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return this;
Зачем из `removeListener` возвращать `this`?

2022-08-26 11:39 UTC, zhzz commented on packages/react-ui/lib/SSRSafe.ts
> +export const globalThat: typeof globalThis & Window =
Думаю, чтобы и в Window и в globalThat появились наши поля, лучше нам переписать `global.d.ts` по этому [примеру](https://stackoverflow.com/a/68452689).

2022-08-29 16:28 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +// we didn't take this into account when we replaced `eventemitter3` with `fbemitter`.
Просто перепутал пока набирал

2022-08-29 16:28 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Для совместимости.

Метод `addListener()` [возвращает](https://github.com/primus/eventemitter3/blob/master/index.js#L70) `this`, поэтому я тоже его возвращаю. И лишь добавляю метод `remove()` для обратной совместимости.

Это же [касается](https://github.com/primus/eventemitter3/blob/master/index.js#L291)  метода `removeListener()`.

---

Идея была в обёртке, которая одновременно будет вести себя как `eventemitter3` и как `fbemitter`.
Поэтому все методы возвращают `this`, а методы `remove()` и `removeListener()` необязательные.

Изначально я хотел наследоваться от `eventemitter3`. но из-за типов пришлось бы делать игноры, чего мне уже не хотелось... Но пока переписывал обёртку - забыл об этой идее.
Сейчас понимаю, что лучше добавить эти игноры, чтобы полностью сохранить совместимость.

2022-08-29 16:28 UTC, lossir commented on packages/react-ui/lib/SSRSafe.ts
> +export const globalThat: typeof globalThis & Window =
Переписал, но по этому [примеру](https://javascript.plainenglish.io/typescript-and-global-variables-in-node-js-59c4bf40cb31).

2022-08-31 10:00 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +// we didn't take this into account when we replaced `eventemitter3` with `fbemitter`.
Еще осталась неточность в том, что последние версии используют `fbemitter`. 

Если быть совсем точным, то метод `remove()` был не у какого-то из эмиттеров, а у подписки, которую старый эмиттер возвращал.

Эти детали важны для тех, кто в последствии будет с этим разбираться, не имея контекста как мы.

2022-08-31 10:06 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Для совместимости? А разве что-то сломается, если мы не станем возвращать `this` из `addListener` и `removeListener`? Мы его где-то использовали?

2022-08-31 10:24 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Идея с оберткой крутая. Но нам ведь не обязательно иметь все api `eventemitter3` и `fbemitter`. Должно хватить только того, что мы сами используем или использовали раньше. Так будет проще понять, что происходит, если не будет лишнего.

2022-08-31 10:35 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
В реализации класса делать методы опциональными не очень логично. Можно создать желаемый интерфейс с опциональными полями. Его уже имплементировать в обертке и использовать для типизации `StackInfo.emitter`.

```ts

export interface ModalStackEmitter {
  addListener: (event: string, listener: () => void) => { remove?: () => void };
  removeListener?: (event: string, listener: () => void) => void;
  emit: (event: 'change') => void;
}

```

2022-09-02 05:35 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Если мы урежем api, то прямо сейчас ничего не сломается. Но тогда появится сущность с уникальным поведением, помимо старого `fbemitter` и нового `eventemitter3`. Это может создать проблемы в будущем.

Раз есть простая возможность сохранить api, то я предлагаю так и сделать.

---

> В реализации класса делать методы опциональными не очень удобно. Можно создать желаемый интерфейс с опциональными полями. Его уже имплементировать в обертке и использовать для типизации `StackInfo.emitter`.

Поскольку я вернулся к варианту с наследованием, то решил не переопределять методы только ради добавления им необязательности. Всё-таки,  это неоправданно усложняет типизацию.

2022-09-02 06:16 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +// we didn't take this into account when we replaced `eventemitter3` with `fbemitter`.
Поправил комментарии

2022-09-02 09:23 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Хотя надо признать, что в текущей реализации метод `addListener()` возвращает новый экземпляр эмиттера.
Поэтому поля `_events` и `_eventsCount` этих экземпляров будут пусты.

2022-09-02 10:03 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Не вижу в новой сущности ничего плохого. Наоборот. Она будет содержать только то, что действительно важно для проблемы и ничего лишнего. Это абстрагирует нас от конкретных пакетов. И, скорее, убережёт от проблем в будущем. Если бы это было сделано сразу, то мы бы не попали в просак при обновлении на eventemitter3.

---

> Раз есть простая возможность сохранить api, то я предлагаю так и сделать.

Я как раз не считаю это решение простым. 
  1. Ты добавляешь метод remove в инстанс эмиттера. Этим эмулируется возврат токена подписки из fbemitter и возврат инстанса эмиттера из eventemitter3. Но вопрос: почему бы просто не вернуть токен подписки, если инстанс эмиттера нам не нужен? Не понятно.
  2. Ты меняешь тип метода addListener, глуша ошибки TS. Результирующий класс уже не является подклассом EventEmitter. Таким образом ломается концепция наследования. Чуть подробнее описано [тут](https://www.typescriptlang.org/docs/handbook/2/classes.html#overriding-methods).

---


> решил не переопределять методы только ради добавления им необязательности. Всё-таки, это неоправданно усложняет типизацию.

В необходимости переопределения и состоит не удобство, о котором я говорил. А типизацию `StackInfo.emitter` можно уточнить вполне оправданно. Вынос интерфейса как раз решает обе проблемы. И переопределять не нужно, и типизация улучшается.

2022-09-02 10:43 UTC, lossir commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Попрошу тогда тебя добить эту задачу. Для меня большинство замечаний выглядят странными и мелкими придирками не стоящими обсуждений. У меня сложилось ощущение, будто я не пишу своё решение проблемы, а пытаюсь угадать твоё решение. Проще тебе сразу написать своё решение, а я займусь чем-то попроще.

2022-09-05 06:28 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
Я предлагаю обсудить все вопросы подробнее и все-таки найти взаимопонимание, чтобы избежать подобных ситуаций в будущем.

2022-09-05 06:37 UTC, zhzz commented on packages/react-ui/lib/ModalStack/Emitter.ts
> +    return new FallbackFBEmitter(() => this.removeListener?.(event, fn));
> Хотя надо признать, что в текущей реализации метод addListener() возвращает новый экземпляр эмиттера. Поэтому поля _events и _eventsCount этих экземпляров будут пусты.

Это критичная проблема, т.к. часть api не работает. Тест ниже не проходит.

```js
  test('should emit event by fallback instance', () => {
    const emitter = new Emitter();
    const fn = jest.fn();
    const instance = emitter.addListener('change', fn);
    instance.emit('change');
    expect(fn).toHaveBeenCalledTimes(1);
  });
```

2022-09-08 13:46 UTC, zhzz commented
Хочу заморозить этот ПР в таком виде для истории. Работу можно продолжить в новом, код и описание просто скопировать.

2022-09-08 13:46 UTC, closed without merging