fix(ZIndex): update zIndex style if priority/delta props are updated
skbkontur/retail-ui pull request #2942
Opened 2022-07-05 09:26 UTC by lossir

## Предпосылки

Некоторые приложения могут использовать собственные модалки, но при этом внутри использовать наши контролы с хинтами, тултипами, валидациями и другим всплывашками. 
В таких случаях наши выпадашки могут рендериться под их модалкой.

Здесь поможет `ZIndex`. Обернув им содержимое своей модалки и задав пропы `priority`/`delta` проблема будет решена. 

## Проблема

Обновление пропов `priority`/`delta` не учитывается. Из-за чего всё дерево контекста не отражает изменений.
Это можно частично обойти фиксировав `priority`/`delta` большими значениями.

Также компонент `ZIndex` добавляет `div` с нужным стилями `z-index` и `isolation`. Но эта обёртка может мешать вёрстке приложения. В крайних случаях думаю можно переверстать и на стороне приложения.

## Решение

### `componentDidUpdate`

~Результат вычислений пропов `priority` и `delta` сохраняется в поле `this.zIndex`. И раз это влияет на отображение компонента, то хотелось перенести его в `state`. Но это вызывало бесконечный цикл обновлений и я решил, что поле было использовано изначально не просто так =) Поэтому пришлось воспользоваться `forceUpdate()`.~

Егор помог правильно заюзать `setState()` - [`zindex-state`](https://github.com/skbkontur/retail-ui/compare/zindex-state).

Однако, такое простое обновление нормально работает только с одним `ZIndex`. И с его потомками, если они перемонтируются после обновление родительского `ZIndex`.
Дело в логике функции `incrementZIndex(priority: Priority, delta: number)`, которая использует значения из `__RetailUiZIndexes`. Если обновляется несколько компонентов `ZIndex`, то новый z-index для второго и далее компонента успевает вычислиться до удаления старых z-index'ов.

На вскидку, исправить это можно, но без серьёзного рефакторинга не обойтись. Не хочу затягивать эту и без того затянутую задачу.

### `useWrapper`

Также добавил проп `useWrapper`, которым можно убрать обёртку, оставляя только контекст для вложенных компонентов.

2022-07-07 15:53 UTC, zhzz requested changes

2022-07-07 15:53 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        this.forceUpdate();
У меня через state бесконечный цикл не воспроизвелся. И причин для него вроде как и нет.

2022-07-07 15:53 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        removeZIndex(this.zIndex);
Новый zIndex в `__RetailUiZIndexes` добавляется каждый раз при вызове `incrementZIndex`. А старый удаляется только при условии. Возможно засорение `__RetailUiZIndexes`.

2022-08-13 17:53 UTC, lossir commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        this.forceUpdate();
У меня никак не получается сделать рабочий вариант с использованием стейта. Видимо что-то упускаю.
При использовании нескольких `ZIndex`, вложенных друг в друга, в некоторых случаях возникает бесконечных рендер. Например в Модалках.
Можешь запушить свой код в отдельную ветку?

При рефакторинге и реализации альтернативного `ZIndex` встречаю довольно много костылей, от которых так просто не избавиться. Если и добью эту реализацию, то в отдельном ПРе, и влить его можно будет только в мажорную версию.
А этот баг надо полечить малой кровью и выпустить пораньше.

2022-08-17 08:33 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        this.forceUpdate();
Ветка [zindex-state](https://github.com/skbkontur/retail-ui/compare/zindex-state). Проверил все истории `Modal` и `ZIndex`, проблем не обнаружил. Скриншоты тоже прошли.

2022-09-01 08:55 UTC, lossir commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +  contextOnly?: boolean;
Переименовал

2022-09-02 10:31 UTC, zhzz approved these changes

2022-09-02 11:42 UTC, merged