Disabled token and backspace
skbkontur/retail-ui pull request #2943
Opened 2022-07-07 07:27 UTC by HelenaIsh

## Проблема

Заблокированный `Token` сейчас можно удалить из `TokenInput` с помощью `Backspace`, но это незаконное поведение.

## Решение

Мое решение спорное и обусловлено тем, что в `TokenInput` мы можем узнать о состоянии токена только через метод `renderToken`. В методе `handleWrapperKeyDown` при нажатии `Backspace` мы работаем только с `this.props.selectedItems` и мы не знаем какие из них будут иметь рендериться как заблокированные, а какие нет.  Поэтому я создала массив `arrayOfDisabledTokens` в котором из метода renderToken собираю данные о состоянии Токенов, и при удалении проверяю статус в этом массиве

## Ссылки

fix IF-532

## Чек-лист перед запросом ревью

- [x] Добавлены тесты на все изменения
  - [x] unit-тесты для логики ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#unit-тесты))
  - [x] скриншоты для верстки и кросс-браузерности ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#скриншотные-тесты)) Скриншотные тесты добавила для удобства ревьюера. По сути, они дублируют юнит тесты и их можно удалить
  - [ ] тесты не требуются
- [ ] Добавлена (обновлена) документация
  - [ ] styleguidist для пропов и примеров использования компонентов ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#styleguidist))
  - [ ] jsdoc для утилит и хелперов ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#jsdoc))
  - [ ] комментарии для неочевидных мест в коде ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#комментарии-в-коде))
  - [ ] гайд для контрибьютеров ([contributing.md](https://github.com/skbkontur/retail-ui/blob/master/contributing.md))
  - [x] документация не требуется
- [ ] Все тесты и линтеры на CI проходят
- [ ] В коде нет лишних изменений
- [ ] Заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-07-10 22:07 UTC, JackUait requested changes

2022-07-11 08:41 UTC, JackUait approved these changes
Сейчас ещё подумал о том, что в `isCurrentItemDisabled` мы проверяем не отключен ли крайний токен справа, так что логичнее, чтобы функция называлась `isRightmostTokenDisabled`, но это вроде не особо критично

2022-07-13 09:18 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const renderedToken = this.props.renderToken(this.props.selectedItems[currentItem], {}) as React.ReactElement<
Использование `renderToken` кажется единственным способом получить `disabled`. Но лучше использовать метод `this.renderToken(item)`, т.к. он прокидывает дополнительные пропы в токен. Пользователь может их использовать для вычисления `disabled`, и тогда `renderedToken` будет отличаться от пользовательского.

Ещё стоит подумать над мемоизацией. Чтобы не рендерить один и тот же токен каждый раз.

2022-07-13 14:57 UTC, dzekh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      const renderedToken = this.props.renderToken(this.props.selectedItems[currentItem], {}) as React.ReactElement<
Там кажется Аня делала какую-то функцию по мемоизации в соседних пиарах.

2022-07-25 11:55 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      newIndex = newIndex - 1;
Здесь учитывается только движение налево `⟵`. Если пытаться выбрать через `shift` вправо, и там будет выключенный токен, то `newIndex` всегда будет возвращаться в исходное значение и выделение просто замрёт.
При этом если наживать просто вправо `⟶`, то токены следующие за выключенным будут выбраны.

Если исключать выключенные токены из `state.activeTokens`, то их надо исключить и из навигации.

2022-07-25 11:55 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return (itemIndex: number) => {
Мемоизация немного переусложнена. Можно было сразу завязаться на логику рендера токена, не вынося это в отдельный аргумент.
В методе `isItemByIndexDisabled(itemIndex)` "экземпляр" мемоизации каждый раз создаётся заново. Даже если `itemIndex` приходит одинаковый.

У меня возникла другая идея, вместо мемоизации. Обсудит устно. Отпишусь по результатам.

2022-07-25 11:55 UTC, lossir commented on packages/react-ui/components/TokenInput/__tests__/TokenInput.test.tsx
> +    const crossIcon = screen.getByTestId('Token__crossIcon');
А здесь не надо использовать `TokenDataTids`?

2022-07-25 12:55 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      if (!this.isEditingMode && !disabled) {
Это пример из задачи "TokenInput: при отключенном инпуте можно удалять неотключенные токены":
```diff
 <TokenInput
+  disabled
   ...
   renderToken={(item, tokenProps) => (
     <Token
       key={item.toString()}
-      {...tokenProps}
+      disabled={item === 'bbb'}
    >
       {item}
     </Token>
   )}
/>
```

По факту в примере просто игнорируется `disabled`, установленный для `TokenInput`. Он доступен во втором аргументе - `tokenProps.disabled`. Т.е. это не баг.

Думаю, допустимо оставить эту проверку. Но может стоит добавить сообщение в консоль, мол "вы пытаетесь удалить токен в выключенном токенИнпуте". И в сообщении оставить ссылку на пример в документации, как надо делать.
Ведь визуально токен будет включенным, что вроде неправильно.

2022-07-27 10:46 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return (itemIndex: number) => {
Решили сохранять результат рендера токенов сразу в методе `this.renderToken()`.

2022-08-02 10:05 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      if (!this.isEditingMode && !disabled) {
После обсуждения в таске решили, что не стоит вводить людей в заблуждение и не стоит блокировать действия с незаблокированным Токеном. Поэтому в документацию добавила пример  `<Token key={item.toString()} {...tokenProps} disabled={item === 'bbb' || tokenProps.disabled} >` А также создала задачу IF-658 чтобы научить `TokenInput` блокировать состояние переданного в него `Token`

2022-08-02 10:05 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/__tests__/TokenInput.test.tsx
> +    const crossIcon = screen.getByTestId('Token__crossIcon');
удалила этот тест, так как больше не блокируем действия с незаблокированным Токеном

2022-08-02 10:08 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return (itemIndex: number) => {
[Попробовала](https://github.com/skbkontur/retail-ui/pull/2943/commits/87ac7c17054f07672461bbabaa87ad8f49312b01) мемоизировать renderToken, но сломались тесты. Так как состояние токенов меняется, мы не можем их мемоизировать - иначе используются мемоизированные значения вместо новых

2022-08-02 10:08 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      newIndex = newIndex - 1;
исключила

2022-08-03 08:13 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return (itemIndex: number) => {
Тесты и падали  из-за того, что токены мемоизировались только по `item`, но их рендер зависит ещё и от полей `isActive` и `disabled`:
https://github.com/skbkontur/retail-ui/blob/dc990dd1214a88d990a71303d84b3340015f62e0/packages/react-ui/components/TokenInput/TokenInput.tsx#L1022-L1028

Но дело немного в другом. Мемоизация нужна, чтобы для получения актуального `disabled` отрендеренного токена не приходилось каждый раз рендерить этот токен.

Поэтому в методе `this.renderToken()` достаточно сохранять отрендеренный токен. А читать из "кэша" будет только метод `this.isTokenDisabled()`.
И сохранять отрендеренные токены можно по индексу, а не по `item`. Метод `this.renderToken()` вызывается в 2-х местах, и в обоих это маппинг массива - `map(this.renderToken)`. Т.е. вторым аргументом метод уже принимает индекс.

Используя индекс в качестве ключа, нормально очищать кэш не получится. А при использовании `item` сравнивать каждый раз объект тоже затратно.
Но я предполагаю, что актуальный `disabled` нужен для действий пользователя, которые производятся уже над отрендеренными токенами. Тогда если под старым индексом пришёл новый `item`, то в методе `this.renderToken()` кэш просто обновиться.
В этом случае, кэш достаточно очищать в методе `componentDidUpdate()`, когда меняется длина массива `selectedItems`. Так не будут оставаться устарелые данные.

2022-08-03 10:28 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.md
> +  return ['aaa', 'bbb'].filter((s) => s.includes(query));
`isTestEnv` удалила. Задачку завела

2022-08-03 10:28 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  private isItemByIndexDisabled = (itemIndex: number) => {
переименовала

2022-08-03 11:43 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      if (!this.isEditingMode && !disabled) {
Этот метод выполняется на Токене, но состояние `disabled` касается только ТокенИнпута.
И при определённых манипуляциях Токен всё равно можно редактировать.

На видео я дважды кликаю на Токен.

https://user-images.githubusercontent.com/2708211/182595359-b1119916-52bb-4ef2-9bde-d8b9d518c601.mp4


Токен это див и состояние `disabled` в нём выражается только стилями.
Самый простой способ "отключить" див, это добавлять в стилях правило:
```css
pointer-events: none;
```

2022-08-03 11:43 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return index;
Эта логика кажется слишком сложной, и она пропускает некоторые случаи.
Например, если выключенный Токен будет крайним слева или справа, то он попадёт в фокус, и его можно будет отредактировать по `Enter`

![ezgif com-gif-maker (30)](https://user-images.githubusercontent.com/2708211/182599223-e9b1cf4b-0a4b-4adb-aa54-f5e529a1821b.gif)

2022-08-04 06:57 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      if (!this.isEditingMode && !disabled) {
Исправила. Изначально нужно было исправить, что Токены могут переходить в режим редактирования при отключенном инпуте. Про переход самих заблокированных токенов в режим редактирования не говорилось. Хорошо, что ты заметил 👍

2022-08-04 06:59 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return index;
Да, я действительно забыла про крайние токены. Исправила.

2022-08-08 16:10 UTC, lossir commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +    return index;
Но логика стала ещё сложнее 😭
Новые строчки как будто исправляют предыдущие. В цикле мы проверяем на `isTokenDisabled`, а потом проверяем ещё раз.

В качестве примера простой логики, я попробовал немного переименовать переменные и разделить условия из `while`: 
```ts
private getAvailableTokenIndex = (startIndex: number, isDirectionLeft = true) => {
  const { selectedItems } = this.getProps();
  const step = isDirectionLeft ? -1 : +1;
  let availableIndex = startIndex + step;

  while (this.isTokenDisabled(availableIndex)) {
    availableIndex += step;

    if (typeof selectedItems[availableIndex] === 'undefined') {
      return startIndex;
    }
  }

  return availableIndex;
}
```

2022-08-08 16:23 UTC, lossir reviewed
Нашёл ещё один не учтённый случай. Если выбрать один токен и затем нажать `ctrl + A`, чтобы выбрать остальные, то в активные токены попадут все токены без разбора. Из-за чего выделенные токены нельзя будет удалить.
https://github.com/skbkontur/retail-ui/blob/17e3153febb71f92f0126b65a93148d3b2a6340f/packages/react-ui/components/TokenInput/TokenInput.tsx#L799-L804

2022-08-11 11:34 UTC, lossir approved these changes

2022-08-15 11:08 UTC, lossir submitted a review, later dismissed

2022-08-17 12:45 UTC, JackUait requested changes

2022-08-17 12:45 UTC, JackUait commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +  private getAvailableTokenIndex = (isDirectionLeft: boolean, startIndex: number) => {
Я бы предложил поменять аргументы местами и задать переменной `isDirectionLeft` по умолчанию `true`. Так нам в `isKeyArrowLeft` не придётся передавать `true` в первом аргументе, а у читающего код возникнет меньше вопросов к методу

2022-08-18 08:44 UTC, dzekh commented on packages/react-ui/components/Token/Token.styles.ts
> +      pointer-events: none;
кажется что тут можно забить, но если менять, то должно остаться возможность выделить и скопировать текст

2022-08-18 09:44 UTC, JackUait requested changes

2022-08-18 09:44 UTC, JackUait commented on packages/react-ui/components/TokenInput/__tests__/TokenInput.test.tsx
> +  });
Нам нужно тестировать то, можем ли мы после прохода по всем токенам добавить ещё один токен. Если токен добавился - это поведение отрабатывает корректно, если токен не добавился - в логике есть какая-то проблема

https://user-images.githubusercontent.com/48599460/185358271-4f9e99f9-e84a-403a-bc15-7c1ad9c49d8a.mov


 Эта логика может неправильно отрабатывать и без выкидывания ошибки и в таком случае текущая версия теста нам не поможет

2022-08-18 09:44 UTC, JackUait commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        if (!this.isEditingMode && !this.isTokenDisabled(this.getProps().selectedItems.length - 1)) {
Можно ещё вторую часть условия вынести в переменную `isRightmostTokenNotDisabled`, строка очень длинная, её сложно читать

2022-08-19 09:02 UTC, HelenaIsh commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +        if (!this.isEditingMode && !this.isTokenDisabled(this.getProps().selectedItems.length - 1)) {
так как по правилам линта нельзя объявлять переменную внутри case, вынесла ее наверх

2022-08-19 10:24 UTC, JackUait commented on packages/react-ui/components/Token/Token.styles.ts
> +      pointer-events: none;
Возможность скопировать текст из токенов осталась

2022-08-22 15:11 UTC, merged