fix(Popup): displaying SVG icons
skbkontur/retail-ui pull request #2946
Opened 2022-07-13 10:30 UTC by JackUait

## Проблема

Если передать `SVG` иконку напрямую в `Hint` - подсказка на иконке отображаться не будет

**Код для воспроизведения:**
```tsx
<Hint text="Редактирование">
  <svg width="16" height="16" viewBox="0 0 16 16">
    <path
      fillRule="evenodd"
      d="M13 12V12.998H8V12H13ZM3 13V11L9 4.99999L11 6.99999L5 13H3ZM13 5L11.5 6.5L9.5 4.5L11 3L13 5Z"
      clipRule="evenodd"
    />
  </svg>
</Hint>
```

При этом если обернуть тег `<svg />` в любой другой тег (кроме `<svg />`) - проблема уйдёт

## Решение

Решение оказалось достаточно тривиальным (оно занимает всего одну строчку), а вот его поиск был не так тривиален

**Окончательное решение:**

Проблема была в том, что утилита `isHTMLElement`, которая у нас используется в `Popup` и `getRootNode` (на парковке она не используется) проверяла только инстансы от `HTMLElement`. Но `SVG` иконки живут в другой спецификации, и имеют собственный инстанс - `SVGElement`, в связи с чем, вся логика, основывающаяся на проверке `isHTMLElement` - проходила мимо `SVG`, либо неправильно отрабатывала:
1. В `getRootNode` на 58-ой строчке есть проверка: 
	```ts
	return isHTMLElement(rootNode) ? rootNode : null;
	```
	которая для `SVG` возвращала `null`, хотя должна - `rootNode`
2. В `Popup` на 338-ой и 348-ой строчках задаются и очищаются слушатели событий, которые завязаны на проверке `isHTMLElement`
3. Всё ещё в `Popup` на 573-ей строчке, возвращается расположение попапа, которое также завязано на проверке `isHTMLElement`

Есть и другие кейсы, в которых старое определение `HTML`-элемента ломает приложение (вплоть до его краша), но они не относятся к этой задаче

Из-за того, что различные инстансы для `HTMLElement` и `SVGElement` обусловлены различными спецификациями, а также из-за того что `HTML`-элементы и `SVG`-иконки неразрывно связаны - было решено расширить проверку в изначальной функции `isHTMLElement` до:
```ts
return el instanceof HTMLElement || el instanceof SVGElement
```

**Поиски решения:**

Как было сказано выше - если обернуть тег `<svg />` в любой другой тег, то проблема уйдёт, но на месте старой проблемы появится новая, в виде мёртвой зоны, в которой не будет отрабатывать хинт, либо в виде увеличившейся зоны хинта (вероятно зависит от иконки, я сильно не погружался, так как расцениваю этот вариант как хак)

**На скриншоте:** тег `<svg />` был обёрнут в `<span />`, из-за чего его нижняя граница увеличилась на 0.5 пикселей, возможен также случай, когда нижняя граница увеличивается и съезжает вниз, образуя мёртвую зону
<img width="136" alt="Снимок экрана 2022-07-13 в 13 48 21" src="https://user-images.githubusercontent.com/48599460/178704829-3d193c40-724d-42f4-a010-17ed905db207.png">

Также были и другие варианты, но для истории, пожалуй, важен только этот

P.S. Изначально для задачи были написаны интеграционные тесты (и отрефакторены старые), но по итогу оказалось, что `RTL` при клике с фиксом и без - рендерит текст хинта, из-за чего переключился на скриншотные тесты

## Ссылки

IF-608

## Чек-лист перед запросом ревью

- [x] Добавлены тесты на все изменения
  - [ ] unit-тесты для логики ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#unit-тесты))
  - [x] скриншоты для верстки и кросс-браузерности ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#скриншотные-тесты))
  - [ ] нерелевантно
- [x] Добавлена (обновлена) документация
  - [x] пропы, публичные методы и примеры использования в styleguidist ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#styleguidist))
  - [ ] jsdoc для утилит и хелперов ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#jsdoc))
  - [x] комментарии для неочевидных мест в коде ([гайд](https://github.com/skbkontur/retail-ui/blob/master/contributing.md#комментарии-в-коде))
  - [ ] прочие инструкции ([README.md](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/README.md)), ([contributing.md](https://github.com/skbkontur/retail-ui/blob/master/contributing.md))
  - [ ] нерелевантно
- [x] Изменения корректно типизированы
  - [x] без использования `any` ([#2856](https://github.com/skbkontur/retail-ui/pull/2856))
  - [ ] нерелевантно
- [ ] Все тесты и линтеры на CI проходят
- [x] В коде нет лишних изменений
- [x] Заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-07-14 15:21 UTC, lossir requested changes

2022-07-14 15:21 UTC, lossir commented on packages/react-ui/components/Hint/__stories__/Hint.stories.tsx
> +      {/* Manual opening used here as a safer way of performing logic. Opening hint manually does not alter the results of behavior that being tested */}
Ручное управление уже тестируется в юнит тесте. Ещё есть такая стори `SetManualAndOpenedPropOnClick` со скриншотами.

Думаю, здесь достаточно сразу рендерить открытый Хинт, для проверки работы с свг-шкой.

2022-07-15 03:25 UTC, JackUait commented on packages/react-ui/lib/SSRSafe.ts
> +    return el instanceof HTMLElement || el instanceof SVGElement;
> Так делать не стоит. Название функции и возвращаемый тип не отражает действительность. Это тоже нам может аукнуться.

Почему название оставил прежним, я описал в секции "решение", но думаю, чтобы полностью исключить путаницу - можно назвать функцию `isHTMLOrSVGElement`

А вот про возвращаемый тип я как-то я упустил объяснение.. В общем, суть такая, что сейчас мы не можем заменить возвращаемый тип, так как это уже "аукнулось" нам. Сейчас для изменения возвращаемого типа нужно вносить в код ломающие изменения. Плюс, с типом `Element` это будет сделать гораздо сложнее, чем с типом `HTMLElement | SVGElement`, так как `Element` это общий тип и в нём отсутствуют многие специфичные  для `HTMLElement` и `SVGElement` сущности

> Для этих узлов есть общая спецификация - Element ([HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement), [SVGElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGElement))

И так как в идеальном мире возвращаемый тип у нас `HTMLElement | SVGElement`, то и проверка на `instanceof Element` нам не совсем подходит из-за того, что мы вроде как проверяем является ли переданный элемент `SVG` или `HTML` элементом, а по факту смотрим на того является ли элемент инстансом `Element`. То есть с точки зрения работы обе версии выдадут одинаковый результат, но версия с проверкой на `HTMLElement` + `SVGElement` логичнее выглядит и проще для понимания

<hr />

Изменил название функции и добавил пояснение про возвращаемый тип

2022-07-15 04:12 UTC, JackUait commented on packages/react-ui/components/Hint/__stories__/Hint.stories.tsx
> +      {/* Manual opening used here as a safer way of performing logic. Opening hint manually does not alter the results of behavior that being tested */}
Тогда мы не будем проверять пользовательский сценарий, а также не покроем все кейсы, из-за которых хинт может не отрендериться на свг-шке. В задаче хинт рендерился не только из-за того, что мы не могли найти его ноду, а также из-за того, что на него не передавались слушатели событий

Хотя, исходя из этой же логики текущая реализация не является корректной. Следовательно, единственный правильный вариант реализации этого теста - проверять отображается ли хинт при ховере

<hr />

Обновил тест, а также заскипал скриншоты везде кроме хрома, чтобы сократить нагрузку. Думаю, что одного хрома хватит для тестирования логики

2022-07-15 07:53 UTC, lossir commented on packages/react-ui/lib/SSRSafe.ts
> +    return el instanceof HTMLElement || el instanceof SVGElement;
Если в возвращаемый тип не добавить `SVGElement`, то это потенциально ломающая штука.
Например, в компоненте `Menu` есть такой код:

https://github.com/skbkontur/retail-ui/blob/772e647b47ac969242b4379c29c18eb1f35bd8a5/packages/react-ui/internal/Menu/Menu.tsx#L196

Который дёргает свойство `offsetLeft`, и ниже ещё и `offsetTop`
https://github.com/skbkontur/retail-ui/blob/772e647b47ac969242b4379c29c18eb1f35bd8a5/packages/react-ui/components/ScrollContainer/ScrollContainer.tsx#L142-L149

Но для `SVGElement` эти свойства задикрикечены: [offsetLeft](https://caniuse.com/mdn-api_svgelement_offsetleft), [offsetTop](https://caniuse.com/mdn-api_svgelement_offsettop)

---

Интерфейс `Element` наследуют только `HTMLElement`, `SVGElement` и [`MathMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/MathMLElement) (по крайней мере других я не нашёл).

Все 3 типа элементов можно получить через законные [рефки Реакта](https://codesandbox.io/s/div-svg-math-react-ref-ikhwcx). Хоть у `MathML` сейчас ограниченная поддержка, но она только увеличивается.

<details><summary>Поддержка MathML</summary>

https://caniuse.com/?search=MathML

![image](https://user-images.githubusercontent.com/2708211/179161246-97249bc8-7be8-47a0-941a-e45e5d948009.png)

</details>

---

Поэтому, добавить отдельную функцию `isElement` мне кажется уместным решением. В описании можно указать про `HTMLElement`, `SVGElement` и `MathMLElement`. Надо будет везде явно указать типы и разрулить проблемы.

Я бы занялся этим в своем ПРе https://github.com/skbkontur/retail-ui/pull/2939, т.к. уже напоролся на все эти проблемы с типами.

Можем созвониться и обсудить.

2022-07-25 14:12 UTC, JackUait commented on packages/react-ui/lib/SSRSafe.ts
> +    return el instanceof HTMLElement || el instanceof SVGElement;
Что по итогу было сделано:
1. Заменил функцию `isHTMLOrSVGElement` на `isElement`
2. Везде, где надо было, заменил тип `HTMLElement` на `Element`
3. Чтобы задача не разрасталась и не задерживалась, пофиксил тип только в тех местах, которые мешали работе функции `isElement`. Для исправления остальных случаев завёл задачу IF-643
4. Привёл тип к `HTMLElement || SVGElement` там, где нужен был вызов нативных методов (таких как `focus`) из `getRootNode`
5. Поправил тип в `FocusEventType`, поправил и расширил тип в `MouseEventType`
6. Заменил обращение к `offsetLeft`, `offsetTop`, `offsetWidth` и остальных `offset*` на получение значения из `getBoundingClientRect`. Эти сущности в большинстве случаев [возвращают одинаковые значения](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements#how_much_room_does_it_use_up), за исключением случая, когда к элементу применяется стиль `transform`. Например, если к элементу с `width: 100px` будет применён стиль `transform: scale(0.5);`, то `offsetWidth` вернёт `100`, а `getBoundingClientRect` вернёт `50`. Это может поломать интерфейсы, которые уже завязались на этом баге, но кажется, что это крайне маловероятно + лучшая альтернатива `getBoudingClientRect` которую я нашёл это вот [этот сниппет](https://github.com/jsdom/jsdom/issues/135#issuecomment-68191941), но при его тестировании оказалось, что работает он крайне так себе и часто возвращает неправильные значения

	Также, `getBoundingClientRect` возвращает дробное значение, а `offset*` - целое, поэтому, чтобы избежать неожиданных багов, округлил к нижней границе значения получаемые из `getBoundingClientRect`

2022-07-26 08:30 UTC, JackUait commented on packages/react-ui/lib/SSRSafe.ts
> +    return el instanceof HTMLElement || el instanceof SVGElement;
Дополнение к пункту 6:
После написания прошлого комментария обнаружилась ещё одна проблема с `getBoundingClientRect` vs `offset*`: если использовать `getBoundingClientRect` в контейнерах со скроллом, то чтобы получить значение равное `offsetLeft` нужно произвести вычисление `getDOMRect(element).right - getDOMRect(element).left`

Ещё не углублялся в причины этого поведения, но думаю, что это лучше решать в рамках отдельной задачи, так как проблема может оказаться гораздо глубже и замедлить выкатку этого пулл-реквеста. Пока оставил в местах, где обнаружился баг - `offset*`, и завёл задачу IF-647, в рамках которой буду разбираться с этой проблемой

2022-07-27 13:36 UTC, zhzz requested changes

2022-07-27 13:36 UTC, zhzz commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
Не думаю, что тут правильно расширять тип до `Event`. Если проблема была только в `Popup` с событиями `mouse*` на `Element`, то лучше ее там и порешать.

Кажется, что корень в том, что [ElementEventMap](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L4841-L4844) почему-то перестал наследовать события из `GlobalEventHandlersEventMap`, как это [было раньше](https://github.com/microsoft/TypeScript/blame/2d495b7f251511ba00bc0e3311de2090f92e79dd/lib/lib.dom.d.ts#L5016-L5044). Хотя у `Element` [есть ](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event) все `mouse*` события. В таком случае, думаю лучше поставить `@ts-expect-error` в `Popup` где нужно.

2022-07-27 18:53 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Поправил

<hr />

> Зачем здесь || SVGElement?

Сюда может прилететь как `HTMLElement`, так и `SVGElement` и чтобы не произошла такая же история как с `offset*` (поддержку этого `API` для `SVG` обещают удалить из `Chrome` только с 2016-го года, так что есть вероятность, что это может произойти и с другим `API`) - нам нужно поддерживать обе сущности. По-хорошему нам нужно поддерживать и `MathMLElement`, но из-за [плохой поддержки](https://caniuse.com/mdn-api_mathmlelement) этой сущности браузерами и неясностью с тем, будут ли этим `API` вообще пользоваться - решил отложить эту задачу до более ясных времён

2022-08-07 15:15 UTC, JackUait commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
В своём рисёрче я пришёл к тому же выводу относительно `GlobalEventHandlersEventMap`. Но хочу также добавить, что ивентам, которые отсутствуют в `ElementEventMap` и попадают в `addEventListener`/`removeEventListener` `TypeScript` назначает тип `Event`

Следовательно, с моей точки зрения расширить тип `MouseEventType` типом `Event` выглядит вполне нормальным решением, если разработчики `TypeScript` уже достаточно давно решили, что `Element` должен иметь именно такие ивенты

Я понимаю твою позицию насчёт `@ts-expect-error`, но если разработчики `TypeScript` не собираются менять это поведение, то нам нет смысла помечать его `@ts-expect-error`. Мне на самом деле тоже непонятна позиция разработчиков `TypeScript` на этот счёт, если они для `Element` хотели оставить только ивенты, у которых тип `Event`, тогда почему они удалили [такие события как](https://github.com/microsoft/TypeScript/blob/c34f64e407b030d5a48c75159a6a1c6567d8f0e4/lib/lib.dom.d.ts#L5550-L5645) `canplay`, `close`, `ended` и т.д.

Я согласен добавить здесь `@ts-expect-error`, если мы пойдём к ним в репу и будем уже с ними разбираться в причинах этого поведения, иначе, думаю, что лучше расширить тип

2022-08-08 08:04 UTC, zhzz commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
А какой смысл останется в `MouseEventType` если наряду с `MouseEvent` и `React.MouseEvent` в него добавить их родительский `Event`? [Union-тип](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types) дочернего и родительского интерфейсов - это все равно что просто родительский интерфейс, поскольку в типе остаются только их общие свойства. 

Это значит, что вся специфика `MouseEventType` (с его полями `clickX`, `movementX` и др) теряется. И это на самом деле ломающие изменения. Ведь `MouseEventType` типизирует аргументы некоторых пропов-колбэков (`Hint.onMouseEnter` и др) и пользователи могут использовать специфичные поля.

----

Если есть желание обсудить проблему с ребятами из TS - здорово, это правильный путь.

2022-08-08 08:31 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Все равно непонятно что ты хотел сделать в этой строчке конструктором `SVGElement`.

2022-08-08 22:53 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Окей, я понял о чём речь. Сюда может попасть только само меню или его айтемы, которые всегда являются `HTML`-элементами

Поправил

2022-08-08 23:09 UTC, JackUait commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
> [Union-тип](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types) дочернего и родительского интерфейсов - это все равно что просто родительский интерфейс, поскольку в типе остаются только их общие свойства.

Это не совсем так, если бы это было правдой, тогда мы смогли бы заменить `MousEventType` просто на `Event`

<hr />

По поводу ломающих изменений - справедливо, добавил `@ts-expect-error`. Постараюсь оформить вопрос в репу `TS` в ближайшее время, но вряд ли стоит ждать скорого ответа (если мы его вообще получим)

2022-08-09 06:54 UTC, zhzz commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
> > [Union-тип](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types) дочернего и родительского интерфейсов - это все равно что просто родительский интерфейс, поскольку в типе остаются только их общие свойства.
> 
> Это не совсем так, если бы это было правдой, тогда мы смогли бы заменить `MousEventType` просто на `Event`

Это так, но я обобщил лишнего. От `Event` наследуется только `MouseEvent`, поэтому его в `MouseEventType ` можно заменить. В итоге останутся только общие поля `React.MouseEvent` и `Event`. Последствия те же, что описал выше.

2022-08-09 08:34 UTC, JackUait commented on packages/react-ui/typings/event-types.d.ts
> +export type MouseEventType<T extends Element = Element> = React.MouseEvent<T> | MouseEvent | Event;
В общем, я не весь кусок выделил:)
> А какой смысл останется в `MouseEventType` если наряду с `MouseEvent` и `React.MouseEvent` в него добавить их родительский `Event`? [Union-тип](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#working-with-union-types) дочернего и родительского интерфейсов - это все равно что просто родительский интерфейс, поскольку в типе остаются только их общие свойства. 

Хотел подсветить то, что в `React.MouseEvent` тип `Event` используется для задания поля `nativeEvent`, но сам тип полностью не наследуется от `Event`

2022-08-10 06:55 UTC, zhzz requested changes

2022-08-10 06:55 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Тут и в `getScrollYOffset` меняется тип аргумента на то, с чем функция работать не умеет, а ошибка просто глушится. Это чревато ошибками в рантайме, если в функцию попадет не `HTMLElement`, у которого вместо `offsetLeft/offsetTop` будет `undefined`. Не самый лучший способ решить проблему.

2022-08-10 07:04 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Нет, речь о том, как именно работает конструкция

```tsx
((getRootNode(this) as HTMLElement) || SVGElement)?.focus()
```

2022-08-10 08:10 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Изначально в коде была конструкция:
```ts
(getRootNode(this) as HTMLElement || SVGElement)?.focus();
```

Линтер автоматически преобразует её в:
```ts
((getRootNode(this) as HTMLElement) || SVGElement)?.focus()
```

2022-08-10 08:39 UTC, JackUait commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Заменил `Element` на `HTMLElement` и заглушил ошибку в другом месте на время, пока не будет закрыта `IF-647`

2022-08-10 09:28 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Глушилка переехала, но вероятность ошибки ведь осталась.

2022-08-10 09:39 UTC, zhzz commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +    ((getRootNode(this) as HTMLElement) || SVGElement)?.focus();
Полагаю, потому что это одно и то же.

2022-08-10 09:58 UTC, JackUait commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Мы минимизировали вероятность ошибки. Да, пользователи могут передать в проп `component` `MenuItem`'а `SVG`-шку, но вероятность этого крайне мала, так как я даже не могу представить себе кейс, в котором `MenuItem` это просто `SVG`-шка и судя по тому, что к нам не обращались с такой проблемой у пользователей пока не было такой проблемы + её можно обойти обернув `SVG` в что-то `HTMLElement`-ное

Когда речь шла о публичном методе `ScrollContainer` - я согласен, что там вероятность того, что пользователи передадут туда `SVG` высока, так как подобное может быть реализовано в дизайне

В [комментарии](https://github.com/skbkontur/retail-ui/pull/2946#discussion_r929677796) выше я писал, что лучше исправлять это поведение в рамках другого пулл-реквеста, так как проблема требует дополнительного рассмотрения, так как нужно разобраться в причинах того, почему `getBoundingClientRect` себя так ведёт, а это может затянуться

2022-08-10 11:06 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Думаю, большинство багов в разработке ПО так или иначе вызвано тем, что разработчики не могут представить всех возможных кейсов. Зачем гадать и считать вероятности. Почему бы просто не исключить проблему, добавив проверку? И ошибку глушить не придется.

2022-08-10 11:42 UTC, JackUait commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    // @ts-expect-error: needs to be replaced with getDOMRect. See IF-647
Поменял глушилку на проверку, поправил поясняющий комментарий

2022-08-10 11:54 UTC, zhzz approved these changes

2022-08-11 05:06 UTC, merged