build(validations): add react testing library
skbkontur/retail-ui pull request #2952
Opened 2022-07-19 11:20 UTC by zhzz

2022-07-26 10:46 UTC, JackUait requested changes
Также появились конфликты с мастером

2022-07-26 10:46 UTC, JackUait commented on packages/react-ui-validations/package.json
> +      "^.+\\.(j|t)sx?$": "babel-jest"
Если верить [документации](https://jestjs.io/blog/2020/05/05/jest-26#:~:text=Jest%20will%20continue%20to%20ship%20with%20babel%2Djest), то c 26-ой версии `Jest` по умолчанию работает с `babel-jest`, так что от этой строчки можно избавиться

<hr />

Проверил это только на пакете `react-ui` в мастере - там всё работает

В этой ветке проверить это не смог, из-за проблем с запуском тестов, описанных в другом комментарии

2022-07-27 09:41 UTC, zhzz commented on packages/react-ui-validations/babel.config.js
> +  presets: [['@babel/preset-env', { modules: 'auto' }], '@babel/typescript', '@babel/preset-react'],
Убрал

2022-07-27 09:41 UTC, zhzz commented on packages/react-ui-validations/tests/test-setup.js
> +import '@testing-library/jest-dom';
Ошибка из-за конфликта зависимостей. В `packages/react-ui-validations/node_modules` осталась старая версия, нужно и ее удалить.

2022-07-27 09:41 UTC, zhzz commented on packages/react-ui-validations/tests/test-setup.js
> +import React from 'react';
Убрал

2022-07-27 09:41 UTC, zhzz commented on packages/react-ui-validations/package.json
> +      "^.+\\.(j|t)sx?$": "babel-jest"
Круто, убрал

2022-08-01 05:43 UTC, merged