feat(useResponsiveLayout): add isTabletV, isTabletH, isDesktop
skbkontur/retail-ui pull request #2957
Opened 2022-07-20 10:02 UTC by Racconkek

Добавила 3 новых флага в ResponsiveLayoutFlag, логику для них в useResponsiveLayout и дефолтные значения в тему

2022-07-21 07:55 UTC, JackUait requested changes
Нам сейчас не совсем подходит такое решение

Есть три потенциальные проблемы:
1. Когда мы начнём заниматься поддержкой планшетов, нам могут не подойти новые брейкпоинты, из-за чего придётся вносить ломающие изменения, чтобы их изменить. Это чревато проблемами для пользователей и задержками в релизах
2. Нам по какой-то причине могут не подойти новые названия (например, они могут конфликтовать с какими-то механизмами `React`'а, или нам может потребоваться больше/меньше бреикпоинтов и новые названия вызовут проблемы), из-за чего также придётся вносить ломающие изменения
3. Мы не будем поддерживать планшеты и этот код будет лежать в библиотеке мёртвым грузом, но при этом его нужно будет поддерживать: на него будут прилетать баги и фичи

Предлагаю такой вариант: сделать возможность локально расширять `ResponsiveLayout`, так мы не столкнёмся с проблемами описанными выше, а вы сможете закрыть свою потребность и также добавлять новые/менять старые бреикпоинты, не беря в расчёт нашу потребность поддерживать обратную совместимость

P.S. Пока не буду предлагать свои варианты решения задачи, чтобы не наставить на ложную дорожку, так как мои варианты пока кажутся мне достаточно сырыми

2022-07-21 08:41 UTC, Racconkek commented
Пока что первое что приходит в голову это:
1.  завести в теме вместо четырех новых полей одно -  customMediaQueries с типом 
    export interface ICustomMediaQuery {
      name: string;
      query: string;
    }
2. Валидировать всё это в хуке с созданием массива листнеров
3. Наружу выплевывать customFlags: Map<string, boolean>; где ключ будет совпадать с name из ICustomMediaQuery 

Из этого не мне очень понятно можно ли в теме создавать поля с кастомными типами(не увидела таких примеров), ну и вообще прошу провалидировать такой вариант

2022-07-26 15:02 UTC, JackUait commented
> мне очень понятно можно ли в теме создавать поля с кастомными типами

В теме могут храниться только строки и функции, которые возвращают строки, так что через тему эту логику реализовать не получится

Обсудили, как это лучше реализовать с Егором и пришли к выводу о том, лучший вариант - это передавать в хук объект, в котором можно будет задавать различные параметры хука (пока только `customMediaQueries`) и затем, на его основе создавать свою, специфичную версию хука

Пользовательский код будет выглядеть примерно так:
```ts
import { useResponsiveLayout as useResponsiveLayoutOrigin } from '@skbkontur/react-ui';

const useResponsiveLayout = () => {
	return useResponsiveLayoutOrigin({ customMediaQueries: { isTablet: '1024px' } })
};
```

Нужно учитывать, что поля передаваемые пользователями, должны дополнять поля из библиотеки, а конфликтующие поля должны перезаписываться в пользу пользователя. Так, например, если пользователь задаёт поле `isMobile`, то оно должно перезаписать поле `isMobile` которое предоставляет библиотека, но при этом, если пользователь задаёт только поле `isTablet`, то у него должен быть доступ к обоим полям: `isMobile` и `isTablet`

Это поведение также должно поддерживаться компонентом `ResponsiveLayout` через проп

Новую функциональность нужно будет задокументировать и покрыть тестами:
1. Добавить описание для пропа
2. Добавить пример использования пропа
3. Добавить пояснение про создание специфичных версий хука/компонента
4. Добавить тесты на добавление новых и конфликтующих брейкпоинтов в хук/компонент

2022-08-03 23:43 UTC, JackUait requested changes

2022-08-03 23:43 UTC, JackUait commented on packages/react-ui/components/ResponsiveLayout/useResponsiveLayout.ts
> +      }
Эта логика при срабатывании выдаёт ошибку:
```diff
- Cannot convert undefined or null to object
```

Воспроизведение ошибки:

https://user-images.githubusercontent.com/48599460/182721509-9427a758-792d-4c68-9321-e44368561517.mov

Из видео это не понятно, но эта ошибка валит всю страницу

<hr />

На самом деле в этом куске кода переусложнённая и запутанная логика. Почему бы нам просто не объединить кастомные медиа-запросы и внутренние и не прогонять ту же логику, что и для `mobileMediaQuery` в цикле?

2022-08-03 23:43 UTC, JackUait commented on packages/react-ui/components/ResponsiveLayout/useResponsiveLayout.ts
> +    const hasChangedCustomQuery = Object.entries(globalLayout).reduce(
Тут не совпадает название переменной и её суть: мы проверяем не произошли ли изменения во внутренних и внешних медиа-запросах, а в название переменной вынесены только внешние запросы

<hr />

Также тут лучше использовать метод `find`, вместо `reduce`
Это значительно упростит чтение кода

2022-08-05 08:12 UTC, Racconkek commented
Объединила все запросы в один список, из-за чего поменялись способы обработки и стало лучше выглядеть

2022-08-05 10:27 UTC, Racconkek commented on packages/react-ui/components/ResponsiveLayout/ResponsiveLayout.tsx
> +}
всё есть, ваша команда претифая сама убирает так

2022-08-11 11:29 UTC, JackUait requested changes

2022-08-11 11:29 UTC, JackUait commented on packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
> +  });
Здесь мы проверяем только то, что хук может возвращать кастомные медиа-запросы. Этот тест не исключает варианта, когда при прохождении брейкпоинта, значение в переменной может не поменяться

2022-08-12 08:51 UTC, JackUait commented on packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
> +  });
Ладненько, с тестированием адаптивной вёрстки в `Jest`'е действительно всё очень не очень. Давай оставим как есть

2022-08-12 09:07 UTC, JackUait submitted a review, later dismissed

2022-08-15 08:32 UTC, lossir commented on packages/react-ui/components/ResponsiveLayout/types.ts
> +export type MediaQueriesType = Record<string, string>;
Этот тип почти не используется. Вместе с докой и тестами конструкция `Record<string, string>` используется 8 раз

2022-08-15 08:32 UTC, lossir commented on packages/react-ui/components/ResponsiveLayout/useResponsiveLayout.ts
> +export function useResponsiveLayout<T extends Record<string, string>>(options?: ResponsiveLayoutOptions) {
Аргумент можно деструктуризировать, и код ниже станет выглядеть чище.

2022-08-15 08:32 UTC, lossir commented on packages/react-ui/components/ResponsiveLayout/types.ts
> +  [K in keyof T]: boolean;
Здесь поля надо сделать необязательными. И тогда в `useResponsiveLayout` не придётся ассертить тип лишний раз.

2022-08-15 08:32 UTC, lossir commented on packages/react-ui/components/ResponsiveLayout/useResponsiveLayout.ts
> +    const defaultResult = { isMobile: !!isMobile };
По-моему этот хук изначально немного перемудрён, но исправлять это стоит как-то отдельно.
Но сейчас мы можем подтюнить новую логику, сократив и упростив код.

Если объединить встроенные и кастомные флаги в начале хука, то в коде ниже не придётся разделять логику для них:
```ts
const allMediaQueries = {
  isMobile: theme.mobileMediaQuery,
  ...customMediaQueries,
};
```

Если так сделать, то станет заметно, что одни и те же манипуляции над объектом повторяется 4 раза.
Дважды используется `Object.entries` и дважды `Object.values`.
Можно заранее промапиться по этому объекту, и даже сразу добавить туда рефку.

Может получиться уже что-то такое:
```ts
const allMediaQueries = Object.entries({
  isMobile: theme.mobileMediaQuery,
  ...customMediaQueries,
}).map(([key, value]) => ({
  flag: key,
  query: value,
  ref: createRef() as React.MutableRefObject<{ remove: () => void } | null>,
}));
```

С таким массивом объектом новая логика станет проще и чуть последовательнее.

2022-08-16 06:13 UTC, Racconkek commented on packages/react-ui/components/ResponsiveLayout/types.ts
> +export type MediaQueriesType = Record<string, string>;
Ты к тому чтобы заменить её на что-то?

2022-08-16 06:36 UTC, lossir commented on packages/react-ui/components/ResponsiveLayout/types.ts
> +export type MediaQueriesType = Record<string, string>;
Я о том, что осталось много мест, где стоит использовать этот тип.

2022-08-17 07:53 UTC, zhzz requested changes

2022-08-17 07:53 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
> +  });
Этот тест не работает, т.к. не падает, даже когда поля на самом деле не были добавлены.

Например, так - ничего не меняется: 
```ts
const result = getUseResponsiveLayoutResult({});
```

2022-08-17 07:53 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
> +  });
Замоканное таким образом значение нужно размокивать обратно, иначе оно останется в глобальном window после завершения этого теста и сможет влиять на другие тесты.

На мой взгляд, тут было бы лучше мокать `matchMedia` и проверять, что она вызывается с переданными нами MediaQueries. Совместно с проверкой того, что хук возвращает ожидаемый набор полей, этого должно быть достаточно.

2022-08-19 04:57 UTC, zhzz requested changes

2022-08-19 04:57 UTC, zhzz commented on packages/react-ui/MOBILES.md
> +На его основе можно создать свой специфичный хук:
Для доки лучше вернуть на первое место самый простой базовый пример использования `useResponsiveLayout` без опций. А с опциями добавить отдельный пример, в конце. Чтобы усложнять постепенно.

И можно убрать уже ненужный generic тип у `useResponsiveLayoutOrigin<typeof customMediaQueries>`.

2022-08-19 04:57 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/ResponsiveLayout.md
> +В компонент можно передать проп `customMediaQueries: MediaQueriesType`, который позволяет кастомизировать возвращаемые флаги:
Этот пример тоже лучше переместить в конец, после базовых. Также, стоит дополнить его использованием добавленных флагов

2022-08-19 04:57 UTC, zhzz commented on packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx
> +    expect(result.isTablet).toBeTruthy();
В предыдущем варианте теста проблема была не в наборе полей или текущем активном query. `toBeFalsy` допускает как `false` так и  `undefined`. Соответственно, для него нет разницы, между значением поля - `false` и отсутствием поля как такового. В текущем варианте, это проблема осталась у поля `isMobile`.

Тут лучше подойдут проверки на конкретные значения `true` и `false`.

2022-08-23 05:46 UTC, zhzz submitted a review, later dismissed
Пофиксил выведение типов, удалив `propTypes` из `ResponsiveLayout`. Похожая проблема уже была в #2607. Она лежит где-то на стороне тайпингов реакта.

Убрал ненужный больше тип из примера в доке.

2022-08-23 07:17 UTC, merged