[FileUploader] Добавить размеры в FileUploader
skbkontur/retail-ui pull request #2961
Opened 2022-07-21 10:42 UTC by ant-d-skb

- [x] добавить стандартные размеры в компонент;
- [x] убрать минимальную ширину компонента, сделать обрезку текста, который не помещается в компонент;
- [x] добавить border-radius из стайлгайда;
- [x] привести цвет текста в контроле в соответствие с гайдами;
- [x] изменить отступ между размером файла и именем;
- [ ] поменять старую иконку Upload на новую;

2022-07-26 21:42 UTC, JackUait commented
> - [x] добавить border-radius из стайлгайда;
> - [x] привести цвет текста в контроле в соответствие с гайдами;
> - [ ] поменять старую иконку Upload на новую;

Вот эти пункты будут закрыты в рамках #2889, там разработка пошла дальше и Максим, который занимается задачей - на короткой ноге с дизайнерами, так что там могло быть всё перелопачено 10 раз и изменения касательно этих пунктов из этого пулл-реквеста только создадут конфликты в коде. В общем, их нужно будет откатить

Также ты внёс изменения сразу в дефолтную тему. Сейчас дефолтная тема - это 8-ми пиксельная тема, эти изменения относятся к так называемой теме 2022, в коде она хранится в файле `Theme2022`. Тема 2022 станет дефолтной вместе со следующим мажорным релизом. Сейчас мы не можем вносить подобные изменения в дефолтную тему, так как они являются потенциально ломающими

<hr />

Вова (@dzekh), можешь провалидировать все изменения, которые описаны ниже:

> - [x] добавить стандартные размеры в компонент;

Сравнение новых размеров контрола `FileUploader`:

<table>
    <tr>
        <th scope="col">Размер контрола</th>
        <th scope="col">Размер шрифта</th>
        <th scope="col">Высота строки</th>
        <th scope="col">Горизонтальный паддинг (ось x)</th>
        <th scope="col">Вертикальный паддинг (ось y)</th>
        <th scope="col">Внешний вид</th>
    </tr>
    <tr align="center">
        <th scope="row">small (по умолчанию)</th>
        <td>14px</td>
        <td>20px</td>
        <td>8px</td>
        <td>5px</td>
        <td><img width="689" alt="Снимок экрана 2022-07-27 в 01 59 26" src="https://user-images.githubusercontent.com/48599460/181110948-55269dcc-2dd5-4a37-80a1-c70b0752a7c9.png"></td>
    </tr>
    <tr align="center">
        <th scope="row">medium</th>
        <td>16px</td>
        <td>22px</td>
        <td>12px</td>
        <td>8px</td>
        <td><img width="688" alt="Снимок экрана 2022-07-27 в 01 59 38" src="https://user-images.githubusercontent.com/48599460/181111070-125c580c-b393-49dc-b60a-1ff22dd1ece0.png"></td>
    </tr>
    <tr align="center">
        <th scope="row">large</th>
        <td>18px</td>
        <td>24px</td>
        <td>16px</td>
        <td>11px</td>
        <td><img width="693" alt="Снимок экрана 2022-07-27 в 01 59 50" src="https://user-images.githubusercontent.com/48599460/181111137-81786de0-8cc8-4517-b983-0a7e84188642.png"></td>
    </tr>
</table>

<hr />

> - [x] убрать минимальную ширину компонента...

Денис (@ant-d-skb), а можешь привести сценарий, в котором это поведение вам мешает?
Мы не можем просто так полностью избавиться от минимальной ширины, так как это будет ломающим изменением. Но мы можем вынести это поведение под проп - для этого нам нужно знать сценарий, в котором это поведение мешает

Также, зная сценарий, мы сможем при необходимости задокументировать его и покрыть тестами

<hr />

> - [x] ...сделать обрезку текста, который не помещается в компонент;

Как выглядит обрезка текста с различными размерами контрола:
<table>
    <tr>
        <th>small</th>
        <th>medium</th>
        <th>large</th>
    </tr>
    <tr>
    <td><img width="263" alt="Снимок экрана 2022-07-27 в 02 11 43" src="https://user-images.githubusercontent.com/48599460/181114062-701712ce-2eaf-4425-ba36-266f224feb3d.png"></td>
    <td><img width="316" alt="Снимок экрана 2022-07-27 в 02 19 18" src="https://user-images.githubusercontent.com/48599460/181114160-d5b02ec1-fc9e-49e4-a8ce-c3e87883036c.png"></td>
    <td><img width="375" alt="Снимок экрана 2022-07-27 в 02 19 26" src="https://user-images.githubusercontent.com/48599460/181114194-9350bdb5-343b-400c-9f61-26520b6cf30b.png"></td>
    </tr>
</table>

Вне зависимости от размера контрола, отступ между иконкой и текстом остаются одинаковыми

> - [x] изменить отступ между размером файла и именем;

Денис (@ant-d-skb), можешь уточнить про какой отступ идёт речь? В пулл-реквесте поменялось несколько отступов

P.S. На самом деле в пулл-реквесте есть и другие изменения (не отражённые в чек-листе), в том числе и ломающие. Комментарии и вопросы к ним я оформлю в виде комментариев к коду

2022-07-27 11:09 UTC, JackUait requested changes

2022-07-27 11:09 UTC, JackUait commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      color: ${t.fileUploaderLinkColor};
Нужна ссылка на макеты для этого изменения

2022-07-27 12:35 UTC, dzekh commented
> Вова (@dzekh), можешь провалидировать все изменения

Посмотрел, вроде всё ок, с одной оговоркой и одним условием: 

По логике этот контрол это частный случай инпута (если заглядывать в нативные). Поэтому он должен копировать размеры и отступы инпута. И если смотреть на переменные вертикального паддинга (ось y): они совпадают с соответствующими у инпутов: `inputPaddingYLarge`, `inputPaddingYMedium`, `inputPaddingYSmall`. Но вертикальные на пиксель не совпадают с `inputPaddingXLarge`, `inputPaddingXMedium`, `inputPaddingXSmall`, там 15, 11 и 7px. 
Но тут нужно смотреть, входит ли бордер или обводка в эти паддинги. В идееале логика и размеры должны совпадать с инпутом, а результируящая высота контролов должна быть 32, 40 и 48px включая обводку. 

Отступы между иконками и размеры иконок так же должны дублировать и смотреть на общие или на значения инпута: `inputIconGapLarge`, `inputIconGapMedium`, `inputIconGapSmall`, `inputIconSizeLarge`, `inputIconSizeMedium`, `inputIconSizeSmall`.

Все эти новые переменные и их значения (или ссылки) должны появиться одинаковые во всех темах. А в теме 2022 переопределятся цвета, радиус скругления и прочие стили, не связанные с размерами и подъедут с другим PR.

2022-07-27 12:38 UTC, dzekh requested changes
> Вова (@dzekh), можешь провалидировать все изменения

Посмотрел, вроде всё ок, с одной оговоркой и одним условием: 

По логике этот контрол это частный случай инпута (если заглядывать в нативные). Поэтому он должен копировать размеры и отступы инпута. И если смотреть на переменные вертикального паддинга (ось y): они совпадают с соответствующими у инпутов: `inputPaddingYLarge`, `inputPaddingYMedium`, `inputPaddingYSmall`. Но вертикальные на пиксель не совпадают с `inputPaddingXLarge`, `inputPaddingXMedium`, `inputPaddingXSmall`, там 15, 11 и 7px. 
Но тут нужно смотреть, входит ли бордер или обводка в эти паддинги. В идееале логика и размеры должны совпадать с инпутом, а результируящая высота контролов должна быть 32, 40 и 48px включая обводку. 

Отступы между иконками и размеры иконок так же должны дублировать и смотреть на общие или на значения инпута: `inputIconGapLarge`, `inputIconGapMedium`, `inputIconGapSmall`, `inputIconSizeLarge`, `inputIconSizeMedium`, `inputIconSizeSmall`.

Все эти новые переменные и их значения (или ссылки) должны появиться одинаковые во всех темах. А в теме 2022 переопределятся цвета, радиус скругления и прочие стили, не связанные с размерами и подъедут с другим PR.

2022-07-28 06:26 UTC, ant-d-skb commented
пример, где нужен контрол с меньшей шириной
![image](https://user-images.githubusercontent.com/80962206/181435588-4b5f6987-437e-4737-8834-ad79fab1b3ec.png)
![image](https://user-images.githubusercontent.com/80962206/181435639-6a57e34d-bebb-4f51-b77a-2b597a56b06a.png)

2022-07-28 06:29 UTC, ant-d-skb commented
"Вот эти пункты будут закрыты в рамках 2889", а когда будет влит ПР с этой задачей? может мне лучше офрмить свой ПР на ее основании? Но откатить свои изменения тоже могу

2022-07-28 06:37 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
https://www.figma.com/file/afTxkfhYKci0UTFr8Fnp57/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-XCOM'22?node-id=220%3A10058

2022-07-28 06:39 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      color: ${t.fileUploaderLinkColor};
https://www.figma.com/file/afTxkfhYKci0UTFr8Fnp57/%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-XCOM'22?node-id=220%3A10058

2022-07-28 06:46 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      font-size: ${t.fileUploaderFontSizeSmall};
поправлю

2022-07-28 06:50 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
display: flex нужен, чтобы текст обрезался, насколько я помню, dispaly: flex, inline-flex не позволяют пользоваться обрезкой текста с точками. Остальные стили просто остались

2022-08-03 06:11 UTC, dzekh commented
> "Вот эти пункты будут закрыты в рамках 2889", а когда будет влит ПР с этой задачей? может мне лучше офрмить свой ПР на ее основании? Но откатить свои изменения тоже могу

Лучше откатить тут изменения, сейчас тот в работе.

2022-08-03 12:09 UTC, ant-d-skb commented
> результируящая высота контролов должна быть 32, 40 и 48px включая обводку
проверил, все так и есть: 32, 40 и 48

2022-08-04 05:39 UTC, ant-d-skb commented
> Но горзонтальные на пиксель не совпадают
Поправл, теперь визуально с инпутами совпадает
![image](https://user-images.githubusercontent.com/80962206/182771001-fcc55028-8b10-4adc-a422-5c28bf06e96d.png)

2022-08-04 05:41 UTC, ant-d-skb commented
> Полагаю, что в этом пункте речь всё-таки идёт об отступе между крестиком и размером файла
Ну да, смотря с какой стороны посмотреть)

2022-08-04 13:40 UTC, ant-d-skb commented
> Вне зависимости от размера контрола, отступ между иконкой и текстом остаются одинаковыми
Поправил

2022-08-04 21:07 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
1. В фигме написано: _"По ховеру браузерный хинт показывает текст полностью"_. Сейчас это поведение не работает, если файл не выбран: 

<table>
<tr>
	<th>Без файла</th>
	<th>С файлом</th>
<tr>
	<td><img width="417" alt="Снимок экрана 2022-08-04 в 13 34 11" src="https://user-images.githubusercontent.com/48599460/182826705-8881cc30-8d63-4d5d-9f09-41e597bf77ac.png"></td>
	<td><img width="442" alt="Снимок экрана 2022-08-04 в 13 35 52" src="https://user-images.githubusercontent.com/48599460/182827036-dc6c7650-b0c6-495e-9d77-b956d565eb2d.png"></td>
</table>

Плюс в фигме идёт речь о браузерном хинте, а у нас уже используется библиотечный хинт для этих целей, нужно уточнить у дизайнеров какой хинт здесь должен быть (имхо, лучше использовать наш хинт)


2. Также в фигме в зависимости от размера контрола меняется отступ от текста до иконки:

<table>
<tr>
	<th>small</th>
	<th>medium</th>
	<th>large</th>
<tr>
	<td><img width="207" alt="Снимок экрана 2022-08-04 в 15 00 55" src="https://user-images.githubusercontent.com/48599460/182842488-73d954ff-5d64-447b-969d-19b5bfe0c741.png"></td>
	<td><img width="222" alt="Снимок экрана 2022-08-04 в 15 01 06" src="https://user-images.githubusercontent.com/48599460/182842386-951f1f4c-0c01-4fd5-a902-32505edca3f1.png"></td>
	<td><img width="279" alt="Снимок экрана 2022-08-04 в 15 01 16" src="https://user-images.githubusercontent.com/48599460/182842557-733d36cc-b7e8-453c-afb4-36ae32e2c1ac.png"></td>
</table>

В реализации  это поведение не сохраняется:

<table>
<tr>
	<th>small</th>
	<th>medium</th>
	<th>large</th>
<tr>
	<td><img width="613" alt="Снимок экрана 2022-08-04 в 15 50 54" src="https://user-images.githubusercontent.com/48599460/182952483-7336c161-13d0-496f-aadd-44073e356c1b.png"></td>
	<td><img width="635" alt="Снимок экрана 2022-08-04 в 15 51 02" src="https://user-images.githubusercontent.com/48599460/182952509-c23b07e6-7792-4116-8d29-9220ef7d3851.png"></td>
	<td><img width="617" alt="Снимок экрана 2022-08-04 в 15 51 09" src="https://user-images.githubusercontent.com/48599460/182952521-4476bc80-aad9-469c-9884-bc99223f60e4.png"></td>
</table>

3. Это пункт не относится к текущим изменениям, но теперь, когда крест прижат к правому краю инпута, проблема стала гораздо более заметной: обрезание текста выбранного файла происходит так, что зачастую, вместо имени файла остаются только три точки, как видно на скриншотах ниже:

<table>
<tr>
	<th>Старая версия</th>
	<th>Текущая версия</th>
<tr>
	<td><img width="422" alt="Снимок экрана 2022-08-04 в 15 33 59" src="https://user-images.githubusercontent.com/48599460/182848078-0ce32b83-b893-409f-bcc7-f7025c90bc6b.png"></td>
	<td><img width="589" alt="Снимок экрана 2022-08-04 в 15 33 26" src="https://user-images.githubusercontent.com/48599460/182847974-22532bf8-59cc-49c5-8e25-9206cdefffd0.png"></td>
</table> 

Это приводит к двум проблемам:
1. Визуально пользователь интерфейса ожидает, что будет отображена большая часть заголовка файла (в соответствии с тем, как обрезается "приветственный" текст)
2. Отображение полного названия файла происходит только при наведении на троеточие, если навестись в другую часть инпута - имя файла отражено не будет:

https://user-images.githubusercontent.com/48599460/182850100-8d427870-daad-4d0f-a64b-a2332242836d.mov

2022-08-04 21:10 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      position: absolute;
Потенциально ломающее изменение - это изменение, которое потенциально может сломать что-то в пользовательских интерфейсах, такие изменения мы можем выпускать только в мажорных версиях

Думаю, что здесь лучше попробовать использовать флексы, это также должно помочь решить проблему с отступами из треда выше

2022-08-04 21:18 UTC, JackUait commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      color: ${t.fileUploaderLinkColor};
Не увидел в фигме каких-либо изменений связанных с обработкой ошибок, которые включаются если контрол находится в `multiple` режиме

2022-08-04 21:57 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
Проверил отступы из второго пункта в последнем коммите, сейчас получаются такие значения:
1. `small`: 6px
2. `medium`: 8px
3. `large`: 10px

С визуальной же точки зрения, к этим значениям может прибавиться ещё пару пикселей "воздуха":

<table>
<tr>
	<th>Нормальная ситуация</th>
	<th>Что-то пошло не так</th>
<tr>
	<td><img width="440" alt="Снимок экрана 2022-08-05 в 00 38 55" src="https://user-images.githubusercontent.com/48599460/182957598-3dff8b82-59d4-47a7-b1fd-32e5f6e8a60a.png"></td>
	<td><img width="408" alt="Снимок экрана 2022-08-05 в 00 39 45" src="https://user-images.githubusercontent.com/48599460/182957579-55423f48-5cfd-49a9-9bb4-f5445f4d1404.png"></td>
</table>

Нужно понять почему это происходит

Я получил значения выше по формуле:
`левый паддинг` + `правый паддинг` + `ширина контента` + `ширина иконки` - `ширина контрола` = `отступ иконки от текста`

Вычисления по приведённой формуле совпадают со значениями, получаемыми при вычислении ширины по формулам из классов `contentInner*`, так что проблема в логике, а не в браузерах

Также в коде используются переменные `btnIconSize*`, вместо `inputIconSize*`. Как отметил Вова: _"этот контрол - это частный случай инпута"_, так что переменные он должен забирать из переменных инпута

2022-08-05 05:11 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
> Также в фигме в зависимости от размера контрола меняется отступ от текста до иконки. В реализации это поведение не сохраняется.

Вроде у меня все четко, даже на очень маленькой ширине контрола:
![image](https://user-images.githubusercontent.com/80962206/183005915-70cad826-5d41-488e-a6c7-a24fe66471cf.png)
![image](https://user-images.githubusercontent.com/80962206/183005925-b586a3d0-d700-4463-b9ba-85bf29565536.png)
![image](https://user-images.githubusercontent.com/80962206/183005936-6fd469ee-fc44-44ad-ad2e-f9f267d741d7.png)

2022-08-05 05:24 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
> Визуально пользователь интерфейса ожидает, что будет отображена большая часть заголовка файла

Подскажи, как это воспроизвести. У меня такон воспроизводится, только если ни одна буква названия файла физически не влезает вместе с многоточием в контейнер
![image](https://user-images.githubusercontent.com/80962206/183007313-b41d3b70-0372-47aa-b398-d59cb0924213.png)

2022-08-05 07:14 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      position: absolute;
Если классу content задать display: flex/inline-flex, то многоточие исчезает, но текст обрезается. Это не соответствует макету, поэтому выбрал значение block. Также я пробовал для обрезки текста использовать TextWidthHelper, но у него на корневом узле также абсолютное позиционирование, поэтому с ним будет еще больше "ломающих" изменений

2022-08-05 08:34 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
> Проверил отступы из второго пункта в последнем коммите, сейчас получаются такие...

Не очень понял, как посчитано по формуле, на маленьком контроле вроде отступ корректный (я поменял переменные темы с кнопки, на инпут, но они вроде одинаковые по значениям)
![image](https://user-images.githubusercontent.com/80962206/183037418-b5496e5c-e727-47c5-9fc4-72e6122ab635.png)

2022-08-05 09:55 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      color: ${t.fileUploaderLinkColor};
Это было нужно, для приведения контрола к новому виду. Выпилил, т.к. такие правки будут в другом ПР

2022-08-17 20:00 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
> Не очень понял, как посчитано по формуле, на маленьком контроле вроде отступ корректный...

`левый паддинг` + `правый паддинг` = `14px`

<table>
<tr>
	<td><img width="620" alt="Снимок экрана 2022-08-17 в 22 44 21" src="https://user-images.githubusercontent.com/48599460/185229024-dc87c4f6-e860-4cf4-a86b-751a36d94958.png"></td>
	<td><img width="195" alt="Снимок экрана 2022-08-17 в 22 44 34" src="https://user-images.githubusercontent.com/48599460/185229076-fd808644-1c54-49bc-a6be-c0da75d521ac.png"></td>
</table>

`ширина контента` = `164px`


<table>
<tr>
	<td><img width="630" alt="Снимок экрана 2022-08-17 в 22 47 28" src="https://user-images.githubusercontent.com/48599460/185229354-0b5888f8-64cd-4294-82b4-5c8e84f50bea.png"></td>
	<td><img width="202" alt="Снимок экрана 2022-08-17 в 22 47 35" src="https://user-images.githubusercontent.com/48599460/185229378-8df35130-3397-4d5c-a30e-1102d77361bf.png"></td>
</table>

`ширина иконки` = `16px`

<table>
<tr>
	<td><img width="620" alt="Снимок экрана 2022-08-17 в 22 49 42" src="https://user-images.githubusercontent.com/48599460/185229749-c7a8b90f-fa2c-4edb-a728-2d53b2d9d60c.png"></td>
	<td><img width="231" alt="Снимок экрана 2022-08-17 в 22 49 52" src="https://user-images.githubusercontent.com/48599460/185229775-c6f6be21-6d4d-4285-b4e6-b4cbfc818176.png"></td>
</table>

`ширина контрола` = `200px`

<table>
<tr>
	<td><img width="625" alt="Снимок экрана 2022-08-17 в 22 50 55" src="https://user-images.githubusercontent.com/48599460/185229952-89b68851-6f80-49d8-bcd6-116e9d5a7a07.png"></td>
	<td><img width="217" alt="Снимок экрана 2022-08-17 в 22 51 01" src="https://user-images.githubusercontent.com/48599460/185229974-3cc495c9-f9e5-4556-9c9a-e56e37d9e4b3.png"></td>
</table>

Подставляем значения в формулу:
200 - 16 - 164 - 14 = 6 пикселей отступ от контента до иконки у маленького контрола

В Фигме у контрола этого размера отступ 4 пикселя:
<img width="86" alt="Снимок экрана 2022-08-17 в 22 53 25" src="https://user-images.githubusercontent.com/48599460/185230311-eed69010-c6dd-4ef3-b275-d1c090833aab.png">


Плюс не понял откуда взялся `:before` на этом скриншоте:
![image](https://user-images.githubusercontent.com/48599460/185231446-e1e4db87-8ec6-4a37-83cf-49b26f942afb.png)

2022-08-17 20:05 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      width: calc(100% - ${t.btnIconSizeLarge} - 4px);
> Подскажи, как это воспроизвести. У меня такое воспроизводится, только если ни одна буква названия файла физически не влезает вместе с многоточием в контейнер

У тебя это не воспроизводится на `medium` и `large` контролах из стори `Different sizes`?

<table>
<tr>
	<td><img width="608" alt="Снимок экрана 2022-08-17 в 23 01 20" src="https://user-images.githubusercontent.com/48599460/185232190-09bba77b-5d2b-46a3-9fd6-4ae127a789c6.png"></td>
	<td><img width="589" alt="Снимок экрана 2022-08-17 в 23 01 29" src="https://user-images.githubusercontent.com/48599460/185232199-d18e7555-d91c-4c65-9d91-643170066b79.png"></td>
</table>

2022-08-17 20:21 UTC, JackUait requested changes

2022-08-17 20:21 UTC, JackUait commented on packages/react-ui/components/FileUploader/__stories__/FileUploader.stories.tsx
> +      <FileUploader size={'large'} width={200} /> large
Если надпись _"или перетащите сюда"_ отображается как троеточие, то пропадает отступ между надписью _"выберите файл"_ и троеточием:
<img width="772" alt="Снимок экрана 2022-08-17 в 23 09 10" src="https://user-images.githubusercontent.com/48599460/185233261-f48b8082-58ca-429c-8eb6-aeafff70592b.png">

Это не было бы проблемой, если бы цвет троеточия совпадал бы с цветом надписи _"выберите файл"_. В общем, нужно спросить у дизайнеров что делать в такой ситуации:
1. Перекрашивать точки в чёрный цвет
2. Добавлять отступ между надписью и троеточием
3. Оставить всё как есть

2022-08-17 20:21 UTC, JackUait commented on packages/react-ui/components/FileUploader/__stories__/FileUploader.stories.tsx
> +      <FileUploader size={'large'} width={200} /> large
Когда у нас выбран файл, но контрол при этом недостаточно большой возникает ситуация, при которой название файла спрятано за троеточием и при этом пользователь видит надпись _"Выбран файл"_:
<img width="546" alt="Снимок экрана 2022-08-17 в 23 15 53" src="https://user-images.githubusercontent.com/48599460/185234448-e9d66592-e37b-4905-a32f-d93b06b9b2ca.png">

Обсудили этот кейс с Вовой Дзехом (@dzekh), пришли к выводу, что в такой ситуации нужно убирать надпись _"Выбран файл"_ и оставлять только название файла

2022-08-17 20:45 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
В таком случае можно оставить класс `content` нетронутым и добавлять его на `FileUploader` всегда, а класс `contentWithFiles` можно сократить до первых двух строчек (чтобы избежать дублирования кода из класса `content`) и добавлять его только при соблюдении условия

2022-08-17 21:02 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      position: absolute;
Окей, давай пока оставим здесь абсолютное позиционирование

2022-08-18 08:36 UTC, dzekh commented on packages/react-ui/components/FileUploader/__stories__/FileUploader.stories.tsx
> +      <FileUploader size={'large'} width={200} /> large
Я бы тут оставил как есть. Пусть серые точки и прилипают, кейс достаточно редкий и не принципиально.

2022-08-24 12:30 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/__stories__/FileUploader.stories.tsx
> +      <FileUploader size={'large'} width={200} /> large
> Подставляем значения в формулу

Кажется, не хватает 2 пикселей боковых бордеров. ::after я добавил руками, чтобы показать, что отступ между элементами 4 пикселя

2022-08-24 12:34 UTC, ant-d-skb commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  }
ок, поправил

2022-08-25 07:04 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/__stories__/FileUploader.stories.tsx
> +      <FileUploader size={'large'} width={200} /> large
> Обсудили этот кейс с Вовой Дзехом

Поправил

2022-08-31 20:57 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static fileUploaderBorderRadius = '8px';
Значения в `fileUploaderTextColorDefault` и `fileUploaderLinkColor` по-прежнему из новой темы

2022-09-01 01:39 UTC, JackUait requested changes

2022-09-01 01:39 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    const containerWidth = fileDivRef.current?.offsetWidth ?? 0;
Здесь лучше использовать `getDOMRect`, он под капотом использует `.getBoundingClientRect`, который [более надёжен](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements#how_much_room_does_it_use_up) чем `offset*`

2022-09-01 01:39 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    const hasOneFile = !!files.length && !multiple;
А почему здесь условие:
```ts
const hasOneFile = !!files.length && !multiple;
```

А не:
```ts
const hasOneFile = files.length === 1 && !multiple;
```

Выглядит достаточно странно, ибо с первым условием мы оставляем пространство для бага, в текущих условиях невозможного, но потенциально возможного в будущем

<hr />

Плюс не похоже, что эта переменная вообще нужна, так как у нас есть переменная `hasOneFileForSingle`, которую мы можем использовать ниже при задании `setLinkVisibility` вместо условия `hasOneFile && !hideFiles`

2022-09-01 01:39 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
Этот комментарий остался без внимания

2022-09-01 01:39 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
А откуда берутся эти значения?

2022-09-01 01:40 UTC, JackUait commented
Ещё нужно подлить свежий мастер и зарезолвить конфликты

2022-09-02 05:12 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
> В таком случае можно оставить класс content...

поправил

2022-09-02 05:23 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    const hasOneFile = !!files.length && !multiple;
согласен, поправил

2022-09-02 05:30 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +    const containerWidth = fileDivRef.current?.offsetWidth ?? 0;
ок, спасибо, поправил

2022-09-02 05:38 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
>                  &nbsp;
поправил

2022-09-02 05:44 UTC, ant-d-skb commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static fileUploaderPaddingXLarge = '15px';
поправил

2022-09-02 05:54 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Вообще, если честно, из головы. Не знаю, нужно ли заводить переменные в теме под эти значения. Тут мы указываем, при какой минимальной ширине нужно скрывать линк. Можно скрывать при максимальной ширине контента, когда остается многоточие, можно чуть раньше, например, когда остается одна буква и многоточие (это не сильно информативнее чем просто многоточие). Возможно нужно посоветоваться с дизайнерами, ну или как вы решите, пока этот пункт не трогаю

2022-09-07 02:18 UTC, JackUait requested changes

2022-09-07 02:18 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
За что тут отвечают стили `width` и `margin-right`?

2022-09-07 02:18 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      text-align: right;
Зачем здесь стиль `text-align: right`?

2022-09-07 02:18 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      bottom: 10px;
Это бесполезные стили. У нас по умолчанию задаётся размер `small`, следовательно, эти стили в любом случае будут переписаны

Это касается не только этого класса, в других "общих" классах встречается эта же проблема

2022-09-07 02:18 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      )};
А почему ты посчитал, что здесь нужно использовать эти миксины?

2022-09-13 08:29 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFileList/FileUploaderFileList.tsx
> +  }, [size]);
поправил

2022-09-13 08:53 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +  },
убрал iconSingle и стиль margin-right: 0. Визуально отличий нет

2022-09-13 08:55 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      margin-left: 4px;
поправил

2022-09-13 09:05 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> -      }
fixed

2022-09-13 10:10 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> -  },
вернул подчеркивание

2022-09-13 10:17 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +                        <UploadIcon size={size} />
ну я предполагал, что если в иконку добавить размер, то иконка автоматически станет нужного размера, с этим связан баг в моей задаче, где иконка у контрола с размером small/default стала меньше. Убрал этот пропс

2022-09-14 04:05 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
margin-right: 0; лишний стиль - убрал
width - задает ширину контейнеру иконки Upload

2022-09-14 04:12 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      text-align: right;
для вырванивания иконок удаления файла и загрузки(Upload). На контроле с мультизагрузкой хорошо видно смещение без этого стиля

2022-09-14 04:19 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      )};
добавлял размерность контролу, взяв за основу Button

2022-09-14 04:20 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +  },
да, этого из-за того, что прокидывал проп size в иконку, убрал проп

2022-09-14 04:27 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +  },
это стили на обертку (div) иконки, он как раз равен 20px
в фигме сейчас макеты с новыми иконками, если текущие иконки растягивать до размеров макетов, то они будут выглядеть очень "жирно", т.к. у них толщина больше, чем у новых иконок

2022-09-14 04:31 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.tsx
> +    [multiple ? jsStyles.iconMultiple() : jsStyles.iconSingle()]: true,
убрал класс iconSingle

2022-09-14 04:47 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFileList/FileUploaderFileList.tsx
> +            {renderFile(file, <FileUploaderFile file={file} showSize multiple size={size} />)}
убрал установку цвета в классе icon в FileUploaderFile.styles.ts – цвет вернулся

2022-09-14 04:53 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      bottom: 10px;
согласен, убрал

2022-09-15 01:40 UTC, JackUait commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFileList/FileUploaderFileList.tsx
> +  }, [size]);
Хук можно использовать ещё в `FileUploaderFileList.tsx` на 26-ой строке и в `FileUploader.tsx` на 87-ой

2022-09-15 02:34 UTC, JackUait requested changes
Ещё падает линтинг, нужно прогнать `prettier`

2022-09-15 02:34 UTC, JackUait commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      margin-left: 4px;
Давай перенесём этот стиль в `iconSmall` для консистентности

2022-09-15 02:50 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      )};
Не думаю, что это оптимальный вариант. Не факт, что в будущем в этом миксине не произойдут изменения несовместимые с `FileUploader`'ом, тем более что, как мы обсуждали ранее - `FileUploader` это частный случай инпута, а не кнопки

Также, в этом миксине есть функция `getBtnPadding`, которая под капотом делает много работы, которая не заложена в логику `FileUploader`'а

В общем, правильный подход в этой ситуации - создать свои миксины, специфичные для `FileUploader`'а

2022-09-15 03:01 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Больше походит на костыль. Мы можем наверняка узнать сколько символов поместится в название файла в данный момент, логика для этого уже даже реализована в функции `getTruncatedName` внутри `FileUploaderFile`. Остаётся только научиться скрывать надпись "Выберите файл", основываясь на логике из `getTruncatedName`

2022-09-19 05:02 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFileList/FileUploaderFileList.tsx
> +  }, [size]);
заменил

2022-09-19 05:04 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      )};
Добавил миксины. Не почувствовал разницу в IE поэтому убрал стили для него

2022-09-19 05:04 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +      // font-size: ${t.fileUploaderIconSize};
ок

2022-09-19 05:04 UTC, ant-d-skb commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.styles.ts
> +      margin-left: 4px;
перенес

2022-09-19 05:14 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Если опираться на символы полученные при урезании названия файла, то получится следующая логика:
1. при загрузке файла, мы вычисляем ширину контейнера в FileUploaderFile и, в зависимости от нее вычисляем новое урезанное имя файла и передаем новое имя вверх в FileUploader
2. в FileUploader мы смотрим какое имя получили и в зависимости от этого скриваем/показываем кнопку "выбран файл"
3. в FileUploaderFile тем временем изменилась ширина контейнера и название нужно снова пересчитать...
С учетом этого я упростил логику, т.к. посчитал, что какая-то мудреная логика получается для простейшего функционала. Поэтому я оперирую изначальной шириной контейнера для отрисовки кнопки "выбран файл", т.к. на мой взгляд нет разницы, отображается просто "..." или "n...". И в том, и в другом случае нужно расширить контейнер, спрятав кнопку "выбран файл"

2022-09-26 03:07 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
На самом деле, не кажется что логика усложнится, скорее даже упростится, сейчас в ней есть неочевидные моменты (например, волшебные числа `20`, `24` и `30`) и вычисления, а также она не стабильна: если в `FileUploader`'е произойдут какие-то изменения, которые увеличат/уменьшат минимальный размер текста, то и эту логику нужно будет обновлять

_Касательно предложенного решения_
Его можно несколько упростить, передавая наружу флаг, вместо имени:
1. В `FileUploaderFile` заводим константу `MIN_CHARS_LENGTH`, которая будет контролировать нижний порог символов в названии файла, задаём ей значение `3`
2. В `FileUploaderControlContext` заводим поля `isMinLengthReached` и `setIsMinLengthReached`, которые будут отвечать за наш флаг для скрытия/показа кнопки "выбран файл" и перерасчёта названия
3. В `FileUploaderFile` проверяем, достигнуто ли минимальное количество символов и в зависимости от этого задаём значение для `isMinLengthReached`
4. Прокидываем флаг `isMinLengthReached` в `useEffect` в `FileUploaderFile`, а также в `setIsLinkVisible` в `FileUploader`

2022-10-11 14:53 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
кажется, предложенный способ работает некорректно. Мне кажется потому,  что в вычисления обрезанного имени файла, контейнер для имени еще не успел обновить свою ширину

2022-10-13 02:44 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Как вариант, можно перерасчитывать `truncatedName` отдельно, на каждый ререндер `FileUploaderFile`, чтобы  всегда иметь актуальный размер. Это не самый оптимальный способ, но пожалуй самый простой в плане кода

P.S.
После последнего коммита начали падать тесты (`Lint/Test (ReactUI)`) с ошибкой `Process exited with code 1`, локально они также не запускаются, нужно разобраться в чём дело

На то, что раннер `Test (SeleniumTesting)` также падает можешь не обращать внимания, там проблема на стороне девопсов

2022-10-13 04:56 UTC, ant-d-skb commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Если просто оставить пересчет truncatedName в рендере, то компонент упадет из-за бесконечного цикла перерендеров. Если обернуть setTruncatedFileName в условие (truncatedName !== truncatedFileName), то компонент ведет себя нестабильно (см. гиф). Может откатим до предыдущего комита? Там достаточно надежный механизм. Если не нравятся волшебные числа, их так же можно вынести в переменные, типа FILE_NAME_MIN_WIDTH_SMALL
![chrome-capture-2022-9-13-1](https://user-images.githubusercontent.com/80962206/195505061-51b1e9b5-04b5-4183-b3a2-176705907693.gif)

2022-10-13 10:49 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.tsx
> +  }
Под перерасчётом на каждый рендер я имел ввиду `useEffect` без зависимостей

Но если просто перетащить всю логику для вычисления `truncatedName` в отдельный `useEffect`, получится следующая ситуация. Имя файла будет некорректно обрезаться:

<table>
<tr>
	<th>Раньше</th>
	<th>Сейчас</th>
<tr>
	<td><img width="284" alt="Снимок экрана 2022-10-13 в 13 21 46" src="https://user-images.githubusercontent.com/48599460/195576365-82fe2619-231d-4807-8dba-389a745a091b.png"></td>
	<td><img width="288" alt="Снимок экрана 2022-10-13 в 13 21 07" src="https://user-images.githubusercontent.com/48599460/195576418-0c46ea89-e118-4ccc-8525-e24f288577de.png"></td>
</table>

Это происходит из-за того, что мы как раз производим вот это (в данном случае лишнее) вычисление

Этого можно избежать, если вынести логику для вычисления `truncatedName` в отдельную функцию и вызывать её в двух разных местах. Итоговый код выглядит так:
```ts
const calcTruncatedName = (
  textHelperRef: React.RefObject<TextWidthHelper>,
  fileNameElementRef: React.RefObject<HTMLSpanElement>,
  name: string,
) => {
  const fileNameWidth = textHelperRef.current?.getTextWidth() || 0;
  const fileNameElementWidth = getDOMRect(fileNameElementRef.current).width;

  return getTruncatedName(fileNameWidth, fileNameElementWidth, name);
};

useEffect(() => {
  const truncatedName = calcTruncatedName(textHelperRef, fileNameElementRef, name);

  setTruncatedFileName(truncatedName);
});

useEffect(() => {
  const truncatedName = calcTruncatedName(textHelperRef, fileNameElementRef, name);

  setIsMinLengthReached((truncatedName?.length ?? 0) <= MIN_CHARS_LENGTH);
}, [name, isMinLengthReached]);
```

2022-10-19 00:27 UTC, JackUait approved these changes

2022-10-20 10:30 UTC, zhzz approved these changes

2022-10-21 05:38 UTC, merged