[Tooltip]: добавить event в onCloseRequest
skbkontur/retail-ui pull request #2966
Opened 2022-07-29 09:59 UTC by HelenaIsh

## Проблема

В `onCloseRequest` не прокидывается `event`. Для некоторых команд это оказалось нужно, чтобы не закрывать Tooltip при клике на определенные элементы

## Решение

Прокинула `event`  в `onCloseRequest`. Сделала его необязательным, чтобы не нарушать обратную совместимость. Также добавила ему два типа: `Event` и `React.MouseEvent<HTMLElement> `чтобы не менять типы в других местах

## Ссылки

fix IF-652

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-08-01 22:35 UTC, JackUait requested changes

2022-08-01 22:35 UTC, JackUait commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +  onCloseRequest?: (event?: Event | React.MouseEvent<HTMLElement>) => void;
Этот тип можно пока оставить в таком виде, но у нас есть `MouseEventType`, который я немного видоизменил в #2946, теперь его можно попробовать затащить сюда, но Егор не совсем [согласен](https://github.com/skbkontur/retail-ui/pull/2946#discussion_r931072657) с тем, что я поменял тип... В общем, я ещё поисследую проблему и сам заменю тип, если это понадобится

<hr />

В любом случае, тут лучше использовать `Element`, вместо `HTMLElement`, иначе у пользователей могут возникнуть проблемы с передачей ивента внутрь `SVG`-шки. Переезд с `HTMLElement` на `Element` - задача IF-643

2022-08-02 08:23 UTC, HelenaIsh commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +  onCloseRequest?: (event?: Event | React.MouseEvent<HTMLElement>) => void;
Изменила `HTMLElement` на `Element` и вебшторм мне сказал, что в этом случае дженерик не нужен. Поэтому удала его совсем.

2022-08-02 09:44 UTC, JackUait approved these changes

2022-08-03 08:31 UTC, zhzz approved these changes

2022-08-03 09:06 UTC, merged