Исправлено поведение selectAll в Input с маской
skbkontur/retail-ui pull request #2996
Opened 2022-09-06 07:15 UTC by HelenaIsh

## Проблема

В инпуте с маской если не введены все цифры не срабатывает метод selectAll

## Причина

Причина кроется в [библиотеке react-input-mask](https://www.npmjs.com/package/react-input-mask), которую мы используем для создания маски. Дело в том, что когда введены не все символы, эта библиотека при фокусе переводит курсор в конец строки (чтобы человек мог ввести недостающие символы). То есть сначала мы говорим: выделить все символы, но библиотека сразу же забирает курсор в конец строки.

## Решение

Добавить задержку перед выделением текста. Тогда сначала библиотека react-input-mask будет переводить курсор в конец строки, а потом будет выделяться текст. Задержка в 150мс была добавлена экспериментальным путем. При фокусе курсор переводится в конец строки тоже с задержкой. Если выделять текст не при фокусе, а например с кнопки, то было бы достаточно 0мс.

## Ссылки

fix IF-692

## Чек-лист перед запросом ревью

Добавила один скриншотный тест для проверки логики, так как через unit тесты не проверить выделение текста

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-09-07 15:35 UTC, JackUait requested changes
Кажется, что более правильным решением было бы форкнуть библиотеку (она не поддерживается автором уже несколько лет) и решить проблему на уровне форка `react-input-mask`. Насколько помню, это уже не первая проблема с инпутом с маской, которая возникает на уровне `react-input-mask`, а не на уровне нашего кода, так что форк поможет избавиться от старых хаков и не заводить новые

В пользу форка также говорит то, что с данным решением присутствует видимая задержка при выделении текста, это не критично, но с форком мы сможем избавиться от неё

Предлагаю обсудить форк `react-input-mask` на ближайшей летучке

2022-09-07 15:35 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +    this.input?.setSelectionRange(start, end);
Так `setSelectionRange` будет вызываться дважды при соблюдении условий в `if`. Второй вызов `setSelectionRange` стоит поместить в блок `else`

2022-09-07 15:35 UTC, JackUait commented on packages/react-ui/components/Input/__stories__/Input.stories.tsx
> +  const inputRef = React.useRef<any>(null);
Использование `any`

2022-09-08 10:17 UTC, HelenaIsh commented on packages/react-ui/components/Input/Input.tsx
> +    this.input?.setSelectionRange(start, end);
Конкретно в этой задаче, кажется, что форк не поможет. Библиотека `react-input-mask` при фокусе переводит курсор в конец строки. По-моему, это логичное и правильное поведение. Я бы не стала его менять. А то что мы хотим при фокусе выделить текст, то это наши проблемы и решать их нужно на нашей стороне

2022-09-09 07:50 UTC, HelenaIsh commented on packages/react-ui/components/Input/__stories__/Input.stories.tsx
> +  const inputRef = React.useRef<any>(null);
а почему Lint его пропустил? Мы ведь вроде бы добавляли правило no-any?

2022-09-09 11:30 UTC, JackUait commented on packages/react-ui/components/Input/__stories__/Input.stories.tsx
> +  const inputRef = React.useRef<any>(null);
Пока ещё не добавили, правило будет добавлено в рамках #2856

2022-09-12 07:01 UTC, JackUait approved these changes

2022-09-23 05:33 UTC, merged