DropdownMenu: замена тени в header и  footer на MenuSeparator
skbkontur/retail-ui pull request #2997
Opened 2022-09-08 10:54 UTC by HelenaIsh

## Проблема

В [документации](https://tech.skbkontur.ru/react-ui/#/Components/DropdownMenu) к DropdownMenu сказано:

> перед элементом переданным в footer будет отрендерен MenuSeparator.

Но на самом деле у футера просто [добавлена тень](https://github.com/skbkontur/retail-ui/blob/93a667a9619a280b0ab0e050a61a9de7a9f7e0a9/packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts#L56), причем ее цвет захардкожен (один для всех тем), в темной теме это очень бросается в глаза.

## Решение

Заменить тень на MenuSeparator. Аналогично сделала для header

## Ссылки

fix IF-749

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения

  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности: Обновила скриншотные тесты. Удалила фон у header чтобы было видно MenuSeparator. В хроме появились непонятные точки, заапрувила их тоже, визуально ничего не поменялось
<img width="98" alt="image" src="https://user-images.githubusercontent.com/32093844/189297039-65fc28d9-7144-4ed0-8e97-cd3c557d8300.png">

  ⬜  нерелевантно

3. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

4. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

5. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-09-13 02:56 UTC, JackUait requested changes

2022-09-13 02:56 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
На скриншотах `With header and footer/*` раньше была некая серая вуаль вокруг поля ввода, на новых скриншотах она пропала. Не помню, чтобы мы обсуждали подобное изменение в отображении

<table>
	<tr>
		<th>Тема</th>
		<th>Раньше</th>
		<th>Сейчас</th>
	</tr>
	<tr>
		<td>Светлая</td>
		<td>
<img width="228" alt="Снимок экрана 2022-09-13 в 05 26 07" src="https://user-images.githubusercontent.com/48599460/189794537-652a240c-db89-40a5-b1b8-9c4500fa6882.png">
</td>
		<td>
<img width="223" alt="Снимок экрана 2022-09-13 в 05 26 15" src="https://user-images.githubusercontent.com/48599460/189794575-999ce398-d232-440a-a66c-6727a1308fb3.png">
</td>
	</tr>
	<tr>
		<td>Тёмная</td>
		<td>
<img width="220" alt="Снимок экрана 2022-09-13 в 05 26 24" src="https://user-images.githubusercontent.com/48599460/189794609-618f9a97-7549-44ee-834c-1a9a6475cf5e.png">
</td>
		<td>
<img width="219" alt="Снимок экрана 2022-09-13 в 05 26 35" src="https://user-images.githubusercontent.com/48599460/189794637-674ed0ba-eb96-4634-abf8-185e1a9cc346.png">
</td>
	</tr>
</table>

2022-09-13 02:56 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
На скриншотах `With header and footer/scrolled by 100` и `With header and footer/scrolled down to bottom` помимо исчезновения вуали также поехали вниз айтемы:

https://user-images.githubusercontent.com/48599460/189796875-dfca3043-cc78-435d-95dc-91f3150347a4.mov

2022-09-13 02:56 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  footer() {
Текст в футере теперь не центрирован вертикально, а прижат к низу и сам футер уменьшился в размере (вероятно, касается и хедера):

<table>
	<tr>
		<th>Раньше</th>
		<th>Сейчас</th>
	</tr>
	<tr>
		<td><img width="225" alt="Снимок экрана 2022-09-13 в 05 49 15" src="https://user-images.githubusercontent.com/48599460/189797240-2fb1c4e9-d479-4976-9b04-bf6212855c2c.png"></td>
		<td><img width="223" alt="Снимок экрана 2022-09-13 в 05 49 07" src="https://user-images.githubusercontent.com/48599460/189797283-e50b6a29-9de6-4df7-9c77-8234018df2ee.png"></td>
	</tr>
</table>

2022-09-13 08:09 UTC, HelenaIsh commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
Это не вуаль, это мы в [тесте](https://github.com/skbkontur/retail-ui/blob/94887c9dee768fe37d00199eda7afbbab82337b0/packages/react-ui/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx#L460) зачем-то подкрашивали header. Из-за этого фона было не видно разделительную полоску между header'ом и остальным списком. Я ее убрала намерено и это изменение только в тесте

2022-09-14 08:44 UTC, HelenaIsh commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
исправила верстку, но разница в 1-2 пикселя осталась. Полностью не получилось избавиться

2022-09-14 11:00 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  private renderMenuSeparatorWithNoMargin = () => {
В тёмной теме со скроллом что-то явно не так с цветом разделителей. В других сторях не воспроизводится

<img width="268" alt="Снимок экрана 2022-09-14 в 13 59 15" src="https://user-images.githubusercontent.com/48599460/190136820-ff93e9b9-5b93-4be5-9661-6089be3af46a.png">

2022-09-14 11:59 UTC, HelenaIsh commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  private renderMenuSeparatorWithNoMargin = () => {
Здесь мой косяк: `MenuSeparator` использовал стили из дефолтной темы

2022-09-16 09:32 UTC, HelenaIsh commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
Да из-за того, что MenuSeparator имеет высоту в 1 пиксель в отличии от тени, то при исчезании появляется скачок. Не вижу легкого способа это устранить

2022-09-16 10:50 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.styles.ts
> +  header() {
Можно оборачивать `<MenuSeparator />` в контейнер с высотой равной высоте `<MenuSeparator />`

Очень грубый пример логики о которой идёт речь:
```tsx
<div style={{ height: '1px' }}>
  {this.state.scrollState !== 'bottom' && this.renderMenuSeparatorWithNoMargin()}
</div>
```

2022-09-16 10:56 UTC, JackUait reviewed
Заметил ещё один момент: когда начинаешь скролл, то футер смещается на пару пикселей вниз, при высоте `<MenuSeparator />` в один пиксель это почти незаметно, но если `<MenuSeparator />` высотой уже в несколько пикселей (на видео - `3px`), то это крайне сильно бросается в глаза

https://user-images.githubusercontent.com/48599460/190622914-db2c5d5b-4985-4576-a7bc-e3a84a0236fd.mov

Это легитимный кейс, так как у нас есть переменная `menuSeparatorBorderWidth` (тем более, что этот баг воспроизводится и с однопиксельным `<MenuSeparator`'ом)

2022-09-21 03:09 UTC, JackUait approved these changes

2022-09-23 10:53 UTC, merged