fix(MenuItem): icon offset in mobile version
skbkontur/retail-ui pull request #3010
Opened 2022-10-04 11:20 UTC by JackUait

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ✅ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-10-06 07:05 UTC, HelenaIsh requested changes

2022-10-06 07:05 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
>    public static menuItemPaddingMobile = '12px 16px';
Насколько я знаю перед удалением нужно пометить переменную тегом @depricated для того, чтобы пользователи узнали, что ее не нужно использовать:
```
 /**
   * @deprecated use menuItemPaddingMobileY and menuItemPaddingMobileX
   */
```
и я бы удалила ее в коде, раз мы от нее отказываемся

2022-10-06 23:26 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
>    public static menuItemPaddingMobile = '12px 16px';
Поправил

2022-10-07 05:16 UTC, HelenaIsh submitted a review, later dismissed

2022-10-12 07:49 UTC, HelenaIsh approved these changes

2022-10-19 11:11 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Текст адресован пользователю, но они же не увидят это. Вроде нигде такой текст не выводится. Да и удалять переменные темы опасно, предлагаю даже не думать в эту сторону =).

Новые переменные залинкованы на старую переменную. Если пользователь задаст отступы в другом формате, то в мобилке верстка может опять поехать.
Поэтому, предлагаю новым переменным задать значение напрямую.

2022-10-20 00:33 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Этот текст выводится при наведении на переменную
Правда, в пользовательском коде переменная почему-то не зачёркивается

<img width="556" alt="Снимок экрана 2022-10-20 в 03 08 24" src="https://user-images.githubusercontent.com/48599460/196827208-f8695655-74e5-47fb-9729-1b106c01ac95.png">

<hr />

> Да и удалять переменные темы опасно, предлагаю даже не думать в эту сторону =).

В чём именно заключается опасность?

> Новые переменные залинкованы на старую переменную. Если пользователь задаст отступы в другом формате, то в мобилке верстка может опять поехать.

Ты прав, об этом кейсе я не подумал. Для десктопной версии компонента существуют только две переменные `menuItemPaddingX` и `menuItemPaddingY`, так что можно ожидать, что дизайнеры будут придерживаться той же логики и на мобилках, следовательно, в переменной `menuItemPaddingMobileX` достаточно фолбечиться на  `menuItemPaddingMobileY`, если переменная `menuItemPaddingMobile` будет определена одним значением

Но на самом деле не уверен, насколько вообще это необходимо, так как квадратные отступы в `MenuItem` это что-то из разряда фантастики

> Поэтому, предлагаю новым переменным задать значение напрямую.

Если мы будем задавать значение напрямую - сломаем обратную совместимость для тех, кто изменил значение в переменной `menuItemPaddingMobile`

2022-10-25 03:42 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
В таком случае, когда пользователь обновит `menuItemPaddingMobile` ему придётся обновить и новую переменную самостоятельно, так как они связаны, что в этом хорошего?

2022-10-25 05:00 UTC, lossir commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Мне кажется, хорошее в том, что пользователь не получает неожиданного изменения вида там, где он ничего не трогал. Пользователи уже могли изменить формат переменной `menuItemPaddingMobile`, и при этом не использовать иконки, и тогда у них может что-то разъехаться. Также могут быть пользователи, которые самостоятельно подхачили этот баг, и тогда у них тоже может что-то разъехаться.

Я чуть внимательнее посмотрел исходную вёрстку, и понял, что если убрать `top: ${t.menuItemPaddingY}` из класса `icon`, то иконка будет сразу норм выравниваться. Тогда и отдельный `top` для мобилки не придётся делать. Абсолютное позиционирование иконки тоже вызывает вопросы, на это уже завязано куча переменных, и так просто не переверстать.

Но может получится просто выкинуть этот `top`?

2022-10-26 05:56 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Похоже, что задание `top` в `icon` - это вынужденное решение и появилось оно из-за наличия абсолютного позиционирования в `MenuItem`

Абсолютное позиционирование в `MenuItem` появилось около 3-ех лет назад, а `top: ${t.menuItemPaddingY}` появился вместе с переменной `menuItemFontSize` около 19-ти месяцев назад и необходим для того, чтобы пользователи могли выровнять иконку относительно текста при изменении размера шрифта в `MenuItem`

Правда, это не мешает нам сохранить логику с заданием отступа через `menuItemPaddingY`, если мы будем забирать `padding-top` у `MenuItem` и на основании него задавать `top`

2022-11-07 05:07 UTC, lossir submitted a review, later dismissed

2022-11-07 06:06 UTC, HelenaIsh requested changes

2022-11-07 06:06 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Получается, что это объяснение больше не соответствует действительности: переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` удалили

2022-11-07 06:14 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +   *  Используйте переменные `menuItemPaddingMobileY` и `menuItemPaddingMobileX` вместо этой переменной.
Удалил

2022-11-07 07:50 UTC, HelenaIsh approved these changes

2022-11-07 08:54 UTC, lossir approved these changes

2022-11-07 08:54 UTC, merged