fix: problems with mobile pop-up windows
skbkontur/retail-ui pull request #3019
Opened 2022-10-20 01:19 UTC by JackUait

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-02 08:07 UTC, zhzz requested changes

2022-12-02 08:07 UTC, zhzz commented on packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
> +    );
Разве это логичное поведение? По ссылке можно будет перейти.

2022-12-06 10:33 UTC, zhzz requested changes

2022-12-06 10:33 UTC, zhzz commented on packages/react-ui/internal/RenderLayer/RenderLayer.tsx
> +      'ontouchstart' in document.documentElement && 'onpointerup' in document.documentElement
`ontouchstart` все еще нужно проверять?

2022-12-07 11:51 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +            <MenuItem component={(props) => <p {...props} />} disabled isMobile>
Конкретно в этом кейсе нет разницы использовать инлайн-функцию или нет, так как `MenuItem` не проверяет пропы по ссылкам. А вот если затащить такое правило для линтинга, то смысл вынести функцию в отдельный метод конечно есть

Завёл задачу `IF-887` для решения этой проблемы. В рамках этого пулл-реквеста правило добавит много "лишнего" кода. Пока только вынес в методы те функции, которые появились в этом пулл-реквесте

2022-12-07 11:51 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +            this.renderUtilityMessage('Начните вводить или изменять значение')}
@dzekh нужен английский текст для этих надписей

2022-12-07 11:54 UTC, JackUait commented on packages/react-ui/components/Hint/Hint.styles.ts
>    mobileContent(t: Theme) {
Удалил

2022-12-07 12:02 UTC, JackUait commented on packages/react-ui/components/Autocomplete/__stories__/Autocomplete.stories.tsx
> +  skip: { in: /^(?!\bchromeMobile\b)/ },
Удалил локальные скипы

2022-12-07 22:15 UTC, JackUait commented on packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
> +    );
Тут логика в том, что если пользователь передаёт кастомный компонент, то пробрасывать на него атрибут `disabled` - не лучшее решение, потому что он [поддерживается](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) только элементами: `<button />`, `<fieldset />`, `<keygen />`, `<optgroup />`, `<option />`, `<select />`, `<textarea />` и `<input />`

Это же справедливо и для пропов `href`, `rel` и `target`, но они не имеют отношения к этому пулл-реквесту, если и будем ими заниматься - то лучше это делать в другом пулл-реквесте

2022-12-07 22:35 UTC, JackUait commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +
> Это слишком ломающие изменения.

А какие другие кейсы ты видишь, помимо того, который я описал?

> ...то может проще сделать для этого отдельный компонент по типу `MenuHeader`?

Насколько я могу судить по дизайну - в идеале этот текст должен визуально копировать `MenuItem`

Вот какие проблемы я вижу в связи с этим:

- Чтобы зашарить стили нам придётся создать не просто новый компонент, а промежуточный компонент между текущим `MenuItem` и новым компонентом. Такой сценарий приведёт к усложнению логики, а также к потенциальным багам в `MenuItem`;
- Единственное отличие "нового `MenuItem`" от текущего будет заключаться в том, что новый сможет рендерить кастомный компонент, если передан проп `disabled`, а текущий - нет;
- Этот компонент скорее всего не будет полезен пользователям и будет валяться у нас в библиотеке как костыль.

Думаю, что эту проблему можно решить с помощью "скрытого" пропа `_visuallyDisabled`, который будет делать то же самое что и `disabled`, но с ним можно будет отрендерить кастомный компонент и он не будет прокидывать `disabled` на компонент

2022-12-07 23:16 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
Похоже, что `Creevey` не умеет работать со `Story Decorators`

Я перенёс логику из глобальных декораторов на стори следующим образом:
```tsx
MobileWithSearch.decorators = [
  (Story) => {
    return (
      <div
        style={{
          width: '475px',
          height: '100vh',
        }}
      >
        <Story />
      </div>
    );
  },
];
```

Декоратор появился в рендере стори, но `Creevey` применяет глобальный декоратор, вместо локального:

<img width="400" alt="Снимок экрана 2022-12-08 в 02 03 09" src="https://user-images.githubusercontent.com/48599460/206315871-c7d66013-289e-4d4b-9385-635b0c8d2f7f.png">

2022-12-07 23:23 UTC, JackUait commented on packages/react-ui/internal/RenderLayer/RenderLayer.tsx
> +      'ontouchstart' in document.documentElement && 'onpointerup' in document.documentElement
Да, событие `ontouchstart` доступно только на устройствах у которых есть тач, а событие `onpointerup` доступно на всех устройствах. Если мы не будем проверять на `ontouchstart` - условие всегда будет возвращать `pointerup`, что сломает поведение компонентов использующих `RenderLayer` на ПК

2022-12-07 23:35 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +        {({ isMobile }) => {
Заменил на декоратор

2022-12-08 06:09 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
Вынес в компонент `MobileTestWrapper`, использовал его во всех мобильных тестах

2022-12-08 06:34 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
Это вряд ли. Криви открывают историю в сторибуке как она есть.

2022-12-08 07:02 UTC, JackUait commented on packages/react-ui/components/MenuItem/__tests__/MenuItem-test.tsx
> +    );
Не учёл, что пользователи могли использовать `disabled` для стилизации
Тогда получается, что это ломающие изменения, откатил

2022-12-08 07:50 UTC, JackUait commented
Раннеры скриншотных тестов, а также линтинга в валидациях и `react-ui` фейлятся без видимых на то причин:
- В скриншотах падают десктопные компоненты в которых не произошло изменений;
- В валидациях в целом не произошло изменений;
- В линтинге падает компонент `Autocomplete`, но при локальном прогоне команды - никаких жалоб на `Autocomplete` нет. Эта проблема также воспроизводится в #3055, но уже с компонентом `FileUploader`.

Перезапуск раннеров не помогает

P.S.
Один из перезапусков починил линтинг в валидациях

2022-12-08 09:55 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +
> А какие другие кейсы ты видишь, помимо того, который я описал?

Раньше пользователям не приходилось думать о состоянии `disabled`, теперь же их кастомным компонентам придется работать и в нем. Они к этому не готовы, потому что есть особенности.

1. Кнопка с  `disabled` отключает обработку событий типа `onClick`, `onMouseOver`, `onMouseLeave`. Это свойство из коробки у MenuItem с кастомными компонентами утратится. Тогда, например, в состоянии `disabled` они начнут выбираться по клику в Select.
2. Кейс, который обсудили ниже с пробросом `disabled` на пользовательский элемент. Сейчас пользователи проброса не ожидают. Но если не пробрасывать, то api будет неполноценным. 
3. Теоретически, пользователи в своих кастомных компонентах могут и не использовать классы, которые приходят в пропах. Тогда, состояние `disabled` у них сломается и визуально.

2022-12-08 10:22 UTC, zhzz commented on packages/react-ui/internal/RenderLayer/RenderLayer.tsx
> +      'ontouchstart' in document.documentElement && 'onpointerup' in document.documentElement
Из статьи следует, что `pointer`-события можно и на ПК использовать. Ты говоришь о разнице up/down? Или и о других потенциальных различиях?

2022-12-08 11:17 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +    return null;
Не выводить ничего в IE11?

2022-12-08 11:17 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
Почему не в декоратор?

2022-12-15 09:22 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +            this.renderUtilityMessage('Начните вводить или изменять значение')}
Добавил локализацию, покрыл локализацию скриншотными тестами

2022-12-16 06:32 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +    return null;
Стало неактуально после добавления компонента `MenuCaption`

2022-12-16 06:48 UTC, JackUait commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +
Создал новый компонент `MenuCaption`
Пока добавил его к `internal` компонентам, но думаю что стоит поисследовать это решение с точки зрения дизайна. Нужно понять, используют ли дизайнеры подобный элемент в своих интерфейсах. По итогу обсуждения заведу, либо не заведу задачу на эту тему

2022-12-17 02:15 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +        {({ isMobile }) => {
Откатил изменения в `SidePage` и `Modal`. Декоратор ломал эти компоненты из-за того, что они используют метод [`ModalStack.isBlocking`](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui/lib/ModalStack.ts#L53-L66), который умеет работать только с `SidePage` и `Modal`, а декоратор подменяет используемый компонент на `ComponentWithLayout`

Думаю, что это делает использование декоратора `@responsiveLayout` небезопасным. Маловероятно, что использование декоратора может коснуться пользователей, но вполне вероятно, что мы можем встретить подобные баги в других компонентах. Что думаешь на этот счёт?

2022-12-20 08:28 UTC, zhzz requested changes

2022-12-20 08:28 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +export const MenuCaption = forwardRefAndName<HTMLParagraphElement, MenuCaptionProps>(
"Сaption" - это заголовок или подпись, описание. А у нас выводятся скорее сообщения. На мой взгляд, `MenuMessage` лучше подойдет как название.

![image](https://user-images.githubusercontent.com/4607770/208615893-24480032-0681-4ff6-bea9-eb67c76b90ae.png)

2022-12-20 08:28 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +          >
Зачем менять переменные MenuItem, если теперь есть отдельный компонент, в котором можно настроить стили как нужно?

2022-12-20 08:28 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +            </MenuCaption>
Еще остался один случай использования `<MenuItem disabled />` со спинером.

2022-12-20 08:28 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Кажется, я погорячился с переиспользованием классов. Так применяется много лишних стилей. Вероятность поломок выше.  Разумнее написать отдельные стили переиспользуя переменные, как в `MenuHeader`.

2022-12-20 08:28 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +        data-tid={MenuCaptionDataTids}
Объект в `data-tid`.

2022-12-20 08:29 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +            this.renderUtilityMessage('Начните вводить или изменять значение')}
А что на счет читаемости?

2022-12-20 08:51 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.tsx
> +        {({ isMobile }) => {
Да, это проблема с декораторами.

2022-12-20 08:54 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
Почему не в декоратор?

2022-12-20 08:55 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
А что с этим?

2022-12-21 05:16 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +export const MenuCaption = forwardRefAndName<HTMLParagraphElement, MenuCaptionProps>(
Переименовал

2022-12-21 05:16 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +          >
У этого текста такой цвет только в `Autocomplete`. Я [задавал](https://yt.skbkontur.ru/issue/IF-530/Problemy-vsplyvayushchikh-okon-v-mobilnom-Safari-i-ne-tolko#focus=Comments-50-3515010.0-0) Вове вопрос на тему того, какой цвет правильный, но не получил ответа. Думаю, что стоит просто откатить его здесь до выяснения обстоятельств

2022-12-21 05:16 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +            </MenuCaption>
Заменил на `MenuMessage`

2022-12-21 05:16 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Разве этот способ лучше? Мне казалось, что смысл этого компонента в том, чтобы частично _скопировать_ необходимые стили из `<MenuItem />`, в том числе забрав его текущие и будущие \*болячки\*

Если мы напишем собственные стили - получим два источника правды. Так, если в `<MenuItem />` добавятся/изменятся какие-то стили не затронутые в переменных нам придётся обновить их и в `<MenuMessage />`

Также, с моей точки зрения история c компонентом `<MenuHeader />` отличается от `<MenuMessage />`:
- У `<MenuHeader />` не стоит задачи скопировать внешний вид `<MenuItem />`;
- `<MenuHeader />` - это почти независимый компонент. Из `<MenuItem />` он использует всего одну переменную, остальные переменные у него "родные";
- У `<MenuHeader />` есть собственная логика в стилях, что ещё больше отдаляет его от `<MenuItem />`.

Исходя из пунктов выше, я бы сказал, что `<MenuHeader />` и `<MenuItem />` очень слабо взаимосвязаны в отличие от `<MenuMessage />` и `<MenuItem />`

2022-12-21 05:16 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +        data-tid={MenuCaptionDataTids}
Заменил на `MenuCaptionDataTids.root`

2022-12-21 05:24 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +            this.renderUtilityMessage('Начните вводить или изменять значение')}
Вытащил в отдельный метод

2022-12-21 05:49 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
А чем так связаны `<MenuMessage />` и `<MenuItem />`, кроме стиля текста и отступов? Все это можно взять из переменных, которые и должны являться источником правды.

2022-12-21 11:13 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
После комментария выше ситуация не изменилась
Наглядное сравнение того, что рендерит сторибук и того, что скриншотит криви:

<table>
<tr>
	<th>Storybook
	<th>Creevey
<tr>
	<td> <img width="502" alt="Снимок экрана 2022-12-21 в 14 00 56" src="https://user-images.githubusercontent.com/48599460/208889993-d649a4a7-cc0b-4ba1-aba4-da24952e3e98.png">
	<td> <img width="215" alt="Снимок экрана 2022-12-21 в 14 02 59" src="https://user-images.githubusercontent.com/48599460/208890518-4858ed05-9e38-4e3f-8793-1837da92332b.png">
</table>

То есть в сторибуке применяется декоратор, но криви на него никак не реагирует

В другой сторе, где используются локальные декораторы (`Sticky/Top`) судя по всему такая же история: там контейнер ограничивается `200px`, но при этом криви делает скриншот всей страницы:

<table>
<tr>
	<th> Мастер (со скроллом)
	<th> Тестовый вариант (без скролла)
<tr>
	<td> <img src="https://user-images.githubusercontent.com/48599460/208891996-e427b022-8209-492f-a6cf-d3c0b678fcce.png">
	<td> <img src="https://user-images.githubusercontent.com/48599460/208892050-f1eebf31-f4d4-45ae-b682-af595fc10b50.png" />

</table>

2022-12-21 11:39 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
"Красивые" декораторы (через `@decorator`) можно использовать только на классах, а оборачивание функции в функцию для реализации этой логики - более запутанный путь, чем просто использование компонента

2022-12-21 12:01 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
Речь про сторибучный декоратор.

2022-12-21 12:07 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Я считаю, что `<MenuItem disabled component={(props) => <p {...props} />}` = `<MenuMessage />` (в левой части выражения имеется ввиду, что логика `component` + `disabled` работает). Следовательно, компонент `<MenuMessage />` должен отражать ту часть изменений в `<MenuItem />`, о которых `<MenuMessage />` знает

Так, например, если в классе `disabled` значение у стиля `background` (не имеет отдельной переменной) поменяется с `transparent` на `diffrentColor` это должно отразиться и в `<MenuMessage />`. Если мы будем завязываться на переменных эти изменения в `<MenuMessage />` отражены не будут. Также, если в `<MenuItem />` поменяется какая-то логика, например, для задания отступов её нужно будет дублировать в `<MenuMessage />`

Поэтому, с моей точки зрения эти два компонента связаны

2022-12-21 12:36 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +        >
Вынес в декоратор

2022-12-22 05:25 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Они связаны не более чем конкретным набором стилей, которые все могут быть вынесены в переменные и слинкованы таким образом, что изменения будут отражаться везде автоматически. Также, никто вроде не гарантирует, что эти стили у них всегда будут совпадать. Цвет текста возможно уже не совпадает.

А на твой пример есть такой же контрпример. У `MenuItem` куча своих стилей, которые не нужны `MenuMessage`, например `border-radius`. Могут появиться еще. Возможно, они будут ломать `MenuMessage`. Придется их перебивать. Зачем?

2022-12-22 10:56 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Получается выносим все стили, которые нужны для `<MenuMessage />` в переменные `<MenuItem />`?

А что насчёт новых стилей, которые будут нужны и `<MenuMessage />` и `<MenuItem />`? В этом сценарии нам нужно будет вручную задавать новые стили для `<MenuMessage />`?

2022-12-22 11:39 UTC, zhzz commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Лучше сделать `MenuMessage` свои переменные, которые будут смотреть на переменные `MenuItem`, если они совпадают.

Если они нужны обоим, то зададим обоим, да.

2022-12-23 06:07 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
Все работает, просто у тебя применяется еще один декоратор, ограничивающий ширину элемента, который фоткается.

2022-12-23 06:38 UTC, zhzz requested changes

2022-12-23 06:38 UTC, zhzz commented on packages/react-ui/internal/MenuMessage/MenuMessage.styles.ts
> +      display: ${t.menuMessageDisplay};
Зачем `MenuMessage` resetButton, cursor, display и position? Если только для того случая в IE11, то проще уже просто переапрувить тот скриншот.

2022-12-23 06:38 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +    if (isNullable(items?.length) && this.props.value) {
```suggestion
    if (isNullable(items) && this.props.value) {
```

2022-12-23 06:38 UTC, zhzz commented on packages/react-ui/.storybook/preview.tsx
> +      return (
Это был декоратор для темы. Теперь в мобильном браузере темы работать не будут.

Декораторы задуманы так, чтобы работать независимо друг от друга. Не нужно все в один запихивать.

2023-01-11 10:50 UTC, JackUait commented on packages/react-ui/.storybook/preview.tsx
> +      return (
Вынес в отдельный декоратор

2023-01-11 10:50 UTC, JackUait commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +    if (isNullable(items?.length) && this.props.value) {
Поправил

2023-01-11 10:50 UTC, JackUait commented on packages/react-ui/internal/MenuMessage/MenuMessage.styles.ts
> +      display: ${t.menuMessageDisplay};
Все стили нужны для нормализации отображения `<MenuMessage />` с различными тегами, в том числе `<button />`

- Без `cursor` при наведении на текст в `<MenuMessage />` курсор из `default` превращается в `text`
- Стиль `display` позволяет сохранить отступы при использовании `inline`-тегов
- Заметил, что тут ещё не хватает `width: 100%`, так как не все теги тянутся на всю ширину c `display: block`, например, `<button />`

От `position` избавился, он здесь действительно лишний

2023-01-11 10:50 UTC, JackUait commented on packages/react-ui/internal/MenuCaption/MenuCaption.tsx
> +            [styles.rootMobile(theme)]: isMobile,
Завёл отдельные переменные для `MenuMessage`

2023-01-11 10:50 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      ) {
Переписал на `Story Decorators`

2023-01-13 06:15 UTC, zhzz commented on packages/react-ui/internal/MenuMessage/MenuMessage.styles.ts
> +      display: ${t.menuMessageDisplay};
Ок, с `cursor` и `display` я могу согласиться. Хотя непонятно, почему не подходит курсор `text`. В `<MenuItem disabled/>` ставится `default` вроде только для того, чтобы перебить `pointer` активного состояния.

Но `button` это маргинальный случай. Думаю не стоит его из коробки поддерживать. Вся подзадача с `MenuItem` ведь началась с того, что button в сообщении не нужен. Если где-то действительно понадобится особый тег, то лучше там прокинуть ему дополнительные стили классом, а  `MenuMessage` оставить простым.  Но тот случай с ie11, думаю, уже того не стоит - там можно переаппрувить. 

А если `MenuMessage` нужны какие-то определенные стили из `resetButton`, например `margin: 0`, то лучше их прописать ему явно. Но уже скорей всего не в виде переменных.

2023-01-17 09:15 UTC, JackUait commented on packages/react-ui/internal/MenuMessage/MenuMessage.styles.ts
> +      display: ${t.menuMessageDisplay};
- Удалил `resetButton`. Заменил его на `margin: 0; padding: 0;`
- По итогу всё-таки отказался от стиля для `cursor`. Удалил стиль и соответствующие переменные

2023-01-17 09:15 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +  },
Вынес декоратор в переменную

2023-01-19 06:34 UTC, zhzz requested changes

2023-01-19 06:34 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +import { StoryFnReactReturnType } from '@storybook/react/dist/ts3.9/client/preview/types';
Лучше использовать публичные типы, например:
```js
import { DecoratorFn } from '@storybook/react';
```

2023-01-19 06:34 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +
Думаю, мы не к таким результатам хотели прийти:

![image](https://user-images.githubusercontent.com/4607770/213371753-a849344f-a376-4f5b-be46-29031210b027.png)

![image](https://user-images.githubusercontent.com/4607770/213371658-6237d260-6908-4be5-bde1-bd15dc70201c.png)


Когда я говорил о переаппрувливании скриншотов в IE, я имел в виду избавление в нем от кнопки сперва, а потом уже переааппрув того, что получится. Там было все лишь маленькое смещение текста:

![image](https://user-images.githubusercontent.com/4607770/213371193-fed26ee5-dd56-4bb7-9ad9-848cd63b2e63.png)

2023-01-19 06:36 UTC, zhzz commented on packages/react-ui/internal/MenuMessage/MenuMessage.styles.ts
> +      display: ${t.menuMessageDisplay};
Ответил [ниже](https://github.com/skbkontur/retail-ui/pull/3019#discussion_r1080854575).

2023-01-20 05:53 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +import { StoryFnReactReturnType } from '@storybook/react/dist/ts3.9/client/preview/types';
Заменил

2023-01-20 05:53 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/ComboBoxMenu.tsx
> +
Вернул тег `<p />` и переапрувил скриншоты

2023-01-24 08:42 UTC, zhzz approved these changes

2023-01-24 10:00 UTC, zhzz commented
Обнови, пожалуйста, описание финальными решениями.

2023-01-24 10:44 UTC, merged