fix(Paging): visual appearance of disabled state
skbkontur/retail-ui pull request #3020
Opened 2022-10-25 02:20 UTC by JackUait

## Проблема

У `Paging`'а в отключенном состоянии пропадала только возможность сфокусироваться на нём, но никак не менялся внешний вид

## Решение

Изменил дизайн отключенного состояния в соотвествии с макетами (макеты можно найти в комментариях к задаче)
Оставил скриншоты только в `Chrome`, так как в отключенном состоянии меняются только цвета контрола

## Ссылки

#3018, IF-806, 

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-10-25 05:27 UTC, lossir commented on packages/react-ui/components/Paging/Paging.tsx
>            tabIndex={0}
Стоит ещё сеттит `tabIndex={-1}` при `disabled`. Иначе при табулировании фокус встаёт на этот спан.

https://user-images.githubusercontent.com/2708211/197689843-249b31c5-1822-4642-803b-d2ab1f5d3b52.mov

2022-10-25 06:58 UTC, HelenaIsh requested changes

2022-10-25 06:58 UTC, HelenaIsh commented on packages/react-ui/components/Paging/Paging.styles.ts
> +      color: #adadad;
Думаю, что нужно залинковать этот цвет на переменную темы`textColorDisabled`

В темной теме точки выделяются из общего стиля

<img width="496" alt="image" src="https://user-images.githubusercontent.com/32093844/197703955-c08dd203-f4ca-41b3-bcbf-71ac7a8c92f8.png">

Я бы добавила скриншотные тесты в разных темах

2022-10-25 23:18 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.tsx
>            tabIndex={0}
Поправил и добавил тест на отсутствие фокуса при отключенном `Paging'`е

2022-10-25 23:34 UTC, JackUait commented on packages/react-ui/components/Paging/Paging.styles.ts
> +      color: #adadad;
Поправил и добавил скриншоты тёмной темы

2022-10-25 23:35 UTC, JackUait commented
Заметил, что в тёмной теме не видно активного кружка в отключенном `Paging`'е
Задал вопрос в задаче, нужно подождать ответа

2022-10-27 04:38 UTC, lossir approved these changes

2022-10-27 06:48 UTC, HelenaIsh approved these changes

2022-10-27 10:31 UTC, merged