feat(Switcher): add renderItem method and hint prop in SwitcherItem t…
skbkontur/retail-ui pull request #3021
Opened 2022-10-25 06:02 UTC by semkedaniil

…o customize SwitcherItems

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-11-07 14:55 UTC, lossir requested changes

2022-11-07 14:55 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +  private _renderItem = (item: SwitcherItems, index: number) => {
Как уже писал тут https://github.com/skbkontur/retail-ui/pull/3017#discussion_r1001485653 - добавление поля `buttonProps` смешивает абстрактные данные об элементе с непосредственной реализацией интерфейса. Но(!) т.к. сам `Switcher` основан на `Button`, то такое поле кажется относительно оправданным и удобным.

Но вот поле `hintProps` так оправдать не получается. Это довольно специфическая потребность. Если кто-то захочет, например, `Tooltip`, то придётся добавлять `tooltipProps` и т.п.

Поэтому я предлагаю добавить проп `renderItem()`, который позволит кастомизировать интерфейс элемента как угодно.

Тип у этого пропа может быть таким:
```js
renderItem?: (
  abel: string,
  value: string,
  buttonProps: ButtonProps,
  renderDefault: () => React.ReactNode,
) => React.ReactNode;
```

И использоваться он может так:
```js
const renderItem = (label, value, buttonProps, renderDefault) => {
  if (value === '111') {
    return <Hint text="Текст Хинта">{renderDefault()}</Hint>;
  }
  if (value === '333') {
    return (
      <Tooltip trigger="opened" render={() => "Текст Тултипа"}>
        {renderDefault()}
      </Tooltip>
    );
  }
  return renderDefault();
};
```

Сделал [грубую реализацию](https://github.com/skbkontur/retail-ui/compare/example-switcher-renderitem) для наглядности.

2022-11-07 14:58 UTC, lossir requested changes

2022-11-07 14:58 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +  'data-tid'?: string;
Это поле можно будет передавать в `buttonProps`, который реализуется в этом ПРе https://github.com/skbkontur/retail-ui/pull/3017

2022-11-09 12:35 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +      return renderItem?.(label, itemValue, buttonProps, () => defaultItem) ?? defaultItem;
Тут мы создаём дефолтный экземпляр независимо от того, что будет делать пользователь - кастомизирует элемент или применит дефолтный вариант.
В этом случае пропадает смысл передавать функцию в аргумент `renderDefault`. Можно сразу передавать `defaultItem`.

Но я бы рекомендовал использовать замыкание и передавать функцию, уже внутри которой будет вызываться `this.renderDefaultItem()`.
В таком случае код из из метода `this.renderDefaultItem()` не будет исполняться в холостую.

2022-11-10 06:35 UTC, lossir commented on packages/react-ui/components/Switcher/__stories__/Switcher.stories.tsx
> +          'ie11Dark',
Это хорошо, что почти все темы игнорируются, т.к здесь тестируется сама возможность кастомного рендера. Но можно оставить только один конфиг - `chrome`.

Скип в криви [поддерживает регулярки](https://github.com/creevey/creevey/blob/master/docs/config.md#skip-option-examples). А в регулярке можно сделать отрицание. Скип получится короче и нагляднее, т.к. будет понятно "что осталось".

```js
/^(?!\bchrome\b)/    <-- пропускаем всё, кроме chrome
```

<details><summary>Подробно про регулярку</summary>

<br/>

Эта штука `?!` полностью называется - `negative lookahead zero-width assertion` =).
Тут можно почитать [подробнее](https://www.regular-expressions.info/lookaround.html).




Как она работает можно посмотреть тут https://regex101.com/r/At5IoM/1:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/2708211/201005767-c6565890-bb58-465f-8da8-73df0ed32d2d.png">

</details>

2022-11-10 06:35 UTC, lossir commented on packages/react-ui/components/Switcher/__stories__/Switcher.stories.tsx
>  export const WithDisabledItems = () => {
Думаю, этот тест можно удалить. Вместе со скриншотами.
Проверять, что в кнопку прокинулся один проп всё-таки лучше в юнит-тестах.

2022-11-10 06:35 UTC, lossir commented on packages/react-ui/components/Switcher/__stories__/Switcher.stories.tsx
> +      <Hint pos="bottom" text="Текст Хинта">
Давай добавим Хинту пропы `opened` и `manual`, чтобы на скриншоте было видно, что он отработал.

2022-11-10 06:57 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +        this.renderDefaultItem(label, itemValue, buttonProps)
Конструкция `??` конвертится в такой код:
```ts
const a = 'a' ?? 'b';

>>>

const a = 'a' !== null && 'a' !== void 0 ? 'a' : 'b';
```

Т.е. если пользователь решил вернуть `null`, вместо вызова `renderDefault()`, чтобы пропустить какой-то элемент, то мы это проигнорируем и сами отредерим дефолтный вид.

Кажется, это не очень очевидное поведение. Если пользователь задал проп `renderItem`, то предлагаю выводить именно то, что он и вернул.

2022-11-10 08:49 UTC, semkedaniil commented on packages/react-ui/components/Switcher/__stories__/Switcher.stories.tsx
> +          'ie11Dark',
поправил

2022-11-10 08:50 UTC, semkedaniil commented on packages/react-ui/components/Switcher/Switcher.tsx
> +        this.renderDefaultItem(label, itemValue, buttonProps)
поправил

2022-11-10 13:41 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +        : this.renderDefaultItem(label, itemValue, buttonProps);
Всё, это последний комментарий.

Тут повторяется довольно длинная конструкция:
```js
this.renderDefaultItem(label, itemValue, buttonProps)
```

Стоит вынести её в отдельную переменную, типа:
```js
<что_то_там> = () => his.renderDefaultItem(label, itemValue, buttonProps)
```

2022-11-10 15:50 UTC, semkedaniil commented on packages/react-ui/components/Switcher/Switcher.tsx
> +        : this.renderDefaultItem(label, itemValue, buttonProps);
поправил

2022-11-14 09:21 UTC, lossir submitted a review, later dismissed

2022-11-14 09:21 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.md
> +      <Tooltip pos="right middle" trigger="opened" render={() => '⚠️ Лучше не трогай...'}>
```suggestion
      <Tooltip pos="right middle" trigger="opened" render={() => 'Тултип'}>
```

2022-11-14 09:21 UTC, lossir commented on packages/react-ui/components/Switcher/Switcher.tsx
> +   * *value*, *buttonProps*, *renderDefault*
```suggestion
   * Функция для отрисовки элемента. Аргументы — `label`,
   * `value`, `buttonProps`, `renderDefault`
```

2022-11-14 10:46 UTC, lossir approved these changes

2022-11-14 10:47 UTC, merged