Screenshot tests new
skbkontur/retail-ui pull request #3023
Opened 2022-10-28 10:18 UTC by galyamovakn

WIP

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-11-14 11:49 UTC, zhzz requested changes

2022-11-14 11:49 UTC, zhzz commented on packages/react-ui/.creevey/config.js
>    : {};
Тут лишние изменения. И линтеры на ТС не проходят. 
Чек-лист в описании ПРа как раз нужен, для того, чтобы не забывать устранять такие мелочи перед ревью.

Нужно прогнать prettier.

2022-11-14 11:49 UTC, zhzz commented on packages/react-ui/components/Button/__stories__/ButtonNEW.stories.tsx
> +import { CreeveyTests } from 'react-ui/typings/stories';
Здесь автоматически вставился импорт из 'react-ui'. Он невалидный. Его нужно поменять на относительный путь до этого файла. 

```suggestion
import { CreeveyTests } from '../../../typings/stories';
```

2022-11-15 03:37 UTC, zhzz reviewed
👍 можно заменять старые

2022-11-15 09:17 UTC, zhzz requested changes

2022-11-15 09:17 UTC, zhzz commented on packages/react-ui/components/Button/__stories__/Button.stories.tsx
> +  title: 'NewButtonTests',
Остался новый title, поэтому тесты не проходят. Плюс снова prettier.

Еще заметил, что из старых потерялся один нужный кейс, история "multiline text with link button". Она проверят, что кнопка-ссылка ведет себя как inline-элемент.

2022-11-15 11:00 UTC, galyamovakn commented on packages/react-ui/components/Button/__stories__/Button.stories.tsx
> +  title: 'NewButtonTests',
Добавила

2022-11-17 06:22 UTC, merged