chore(RadioGroup): extend type with boolean
skbkontur/retail-ui pull request #3033
Opened 2022-11-10 12:22 UTC by HelenaIsh

## Проблема

Сейчас RadioGroup принимает только 2 типа: string и number. Некоторым командам хотелось бы видеть boolean

## Решение

Расширила тип RadioGroupProps

## Ссылки

fix IF-830

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-11-11 11:55 UTC, JackUait reviewed
Мы же здесь не ограничиваем тип с помощью [extends](https://stackoverflow.com/a/71502348), а задаём значение по умолчанию. То есть при желании пользователь всё ещё может передать `boolean` в дженерик `RadioGroup`

2022-11-15 13:22 UTC, JackUait requested changes

2022-11-15 13:22 UTC, JackUait commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +  let selectElem: Select<unknown, string> | null = null;
Получается, что эти изменения ломающие
Нужно подумать сможем ли мы что-то с этим сделать и если нет - обсудить с командой насколько это ломающее изменение критично

2022-11-15 13:22 UTC, JackUait commented on packages/react-ui/components/Select/Select.tsx
> -import PropTypes from 'prop-types';
Давай ещё накинем тестов на это поведение: просто прокинем дженерики в нужные компоненты и назовём тесты как-то вроде этого: _"should pass generic type without type errors"_

2022-11-18 07:42 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +  let selectElem: Select<unknown, string> | null = null;
По факту, изначально тут тип был неточный. Без prop-types тип ref стал выводится из items правильно. Что вызвало необходимость подправить тип selectElem.

Кто-нибудь, конечно, тоже может с этим столкнуться и ему придется поправить свой код. Но, думаю, что не очень критично. Можно на это пойти.

Еще одна проблемка с unknown и необходимостью прокидывать типы уже в Select. Получается, что тип для TValue не выводится из items, хотя может. Если заглянуть в тип SelectItem и добавить в него TValue наравне с TItem, то все починится. И можно будет ограничиться только указанием типа для selectElem: `Select<string, string> | null`.

2022-11-18 11:00 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +      <Select<string, string> ref={(ref) => (selectElem = ref)} search width={width} items={['one', 'two', 'three']} />
В `<Select />` уже не нужно явно типы передавать. Они теперь сами корректно выводятся.

2022-11-21 07:15 UTC, JackUait approved these changes

2022-11-25 06:54 UTC, merged