feat(theme): all edits THEME_2022
skbkontur/retail-ui pull request #3045
Opened 2022-11-17 12:30 UTC by lossir

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-07 08:44 UTC, JackUait requested changes

2023-03-07 08:44 UTC, JackUait commented on packages/react-ui/components/Group/Group.tsx
> +    return React.cloneElement(child, { corners: { ...corners, ...child.props.corners } });
Не хватает теста на этот кейс

2023-03-16 12:43 UTC, lossir commented on packages/react-ui/components/Modal/relinkModalTheme.ts
> +export const relinkModalTheme = (theme: Theme): Theme => {
Функционально разницы нет. По сути это специальный паттерн по перелинковке переменных для "композитных" компонентов.
Мне кажется, что глагол `relink` точнее описывает происходящее. Но я не стал трогать имеющиеся файлы.

2023-03-16 12:44 UTC, lossir commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/OkIcon.tsx
> +export const OkIcon = iconSizer(
Тут смысл именно в абстрагировании от исходных иконок по двум причинам:
1. Названия исходных иконок довольно громоздкие и буквально описывают что в иконке отрисовано.
  В таком виде их не удобно использовать в компонентах.
  
  | Что нарисовано | Как используется |
  | --- | --- |
  | `UiMenuDotsThreeVIcon` | `KebabIcon` |
  | `ArrowShapeDRadiusUpLeftIcon` | `UndoIcon` |

2. При возможных изменениях оригинальной иконки код компонента не придётся менять. Например, если для определённого `size` проектировщики заменят начертание, или целиком заменят иконку.

2023-03-16 12:44 UTC, lossir commented on packages/react-ui/internal/CloseButtonIcon/__stories__/CloseIcon.stories.tsx
> +};
Она для дебага. Забыл скрины добавить

2023-03-16 12:45 UTC, lossir commented on packages/react-ui/components/PasswordInput/ClosedIcon.tsx
> +);
В папке компонента они как-будто уместнее, т.к. их сразу видно когда заходить в компонент.
Например, исходная `CheckAIcon` становится `CheckedIcon` в `<Checkbox>` и `OkIcon` в `<FileUploader>`. Где указаны специфичные настройки, типа `disableCompensation={false}` или `size={12}`.

2023-03-17 07:34 UTC, lossir commented on packages/react-ui/components/Loader/Loader.tsx
> +    type: 'normal',
Исправил. Добавил тип `LoaderType`, который экстрактит из `SpinnerType` нужные типы.
И добавил переменную `types: LoaderType[]` вместо `Spinner.Types`.

2023-03-17 07:36 UTC, lossir commented on packages/react-ui/components/Modal/ModalClose.tsx
> +  const icon = isTheme2022(theme) ? <XIcon16Regular /> : <CrossIcon />;
Исправил. Затащил `XIcon20Regular`

2023-03-17 08:32 UTC, lossir commented on packages/react-ui/components/Spinner/Spinner.tsx
> +export type SpinnerType = 'mini' | 'normal' | 'big' | 'small' | 'medium' | 'large';
Нейминг изменить не получится. 
Набор `'mini' | 'normal' | 'big'` не изменить из-за обратной совместимости.
А набор `'small' | 'medium' | 'large'` соответствует значениям пропу `size` в других компонентах и в макетах, и здесь несут тот же смысл.

Решил подробнее описать в доке этот момент. После чего стало понятно, что и стили надо немного переписать.

2023-03-17 09:12 UTC, lossir commented on packages/react-ui/components/Textarea/Textarea.tsx
> +      ...(isTheme2022(this.theme) ? { backgroundClip: 'padding-box' } : {}),
Можем. Только для дефолтной темы будет `border-box` ([developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip#formal_definition)).
На самом деле в стилях захардкожено `background-clip: padding-box;`. Но идущее следом правило `background` перебивает это. Поэтому в дефолтной теме сеттится умолчательное значение.
Изначально просто не хотел трогать это момент, вдруг браузеры по разному такое разруливают. Но давай попробуем.

https://github.com/skbkontur/retail-ui/blob/6773a3666ccabf25ad119ebb066d5b54c5816412/packages/react-ui/components/Textarea/Textarea.styles.ts#L14-L19

2023-03-17 09:23 UTC, lossir commented on packages/react-ui/internal/CloseButtonIcon/CloseButtonIcon.tsx
> +  ...attrs
По факту в этом объекте остаются пропы, которые прокидываются как атрибуты в нативный компонент.
Этим именем я хотел это подчеркнуть.

2023-03-17 09:47 UTC, lossir commented on packages/react-ui/components/Toast/ToastView.tsx
> +            data-tid={ToastDataTids.close}
Он типизирован - `ButtonHTMLAttributes`.

https://github.com/skbkontur/retail-ui/blob/0b3e188c1f18e3e6f93193ee1b2ede3fff3569e0/packages/react-ui/internal/CloseButtonIcon/CloseButtonIcon.tsx#L12

Под капотом TS разруливает пропы из dataset, поэтому отдельно их описывать не нужно.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/2708211/225869755-50f0665d-5679-4b88-b39b-aeeb4c23f64d.png">

©️ [https://www.typescriptlang.org/play](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4Aoc4AOxiSk3STgGEAbCAZyQEk0JqABRxhOcJAA861ACZjk6GADoAQgFcYMAQAkAKgFkAMgEFNUYACMNSTgB49R9ZoEBRNkhBJaAPjgBvcgBfSklIWDh+ak54di4kJy1qPgEALkRiZQAxNWoMYAEWXEhqLxhbWO5koRFOXwBeOAAKFDNOAEo4Ot9G8jg4Wytnal6+uGoUTzr8CxhqfBG+mRaUAFoYYBkpumiAfQBGedG4JZgWja2bGH3D0b8le5aYKE5gvu8IAGtbAHpBxO9yG0KORyhxuAkBFVjss1ud8NsrgAmfDQ07rTbwy47ZFwb7eIA)

2023-03-17 09:56 UTC, lossir commented on packages/react-ui/components/MenuItem/MenuItem.styles.ts
> +      opacity: 0.6;
Исправил

2023-03-17 10:25 UTC, lossir commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
>    },
Исправил

2023-03-17 10:25 UTC, lossir commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
> +    const bc = isTheme2022(t) ? 'background-clip: padding-box' : '';
Исправил

2023-03-17 12:50 UTC, lossir commented on packages/react-ui/components/Checkbox/Checkbox.styles.ts
> +      width: ${t.checkboxIconWidth};
Это я не дотащил фичу с кастомизацией размеров чекбокса в старой теме.
В теме2022 переменная темы `checkboxBoxSize` просто прокидывается в иконку и норм работает.
В дефолтной теме со старой иконкой это не работает и она всегда сохраняет размеры.

<img width="100" alt="image" src="https://user-images.githubusercontent.com/2708211/225886730-4c6f4c4e-32de-46db-8998-97ef2d5365b5.png">

Исправил и дотащил.

2023-03-20 05:25 UTC, lossir commented on packages/react-ui/components/Paging/Paging.tsx
> +    // d
Убрал

2023-03-29 10:20 UTC, JackUait requested changes

2023-03-29 10:21 UTC, JackUait requested changes

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/Spinner/Spinner.tsx
> +export type SpinnerType = 'mini' | 'normal' | 'big' | 'small' | 'medium' | 'large';
Судя по документации, это изменение - это целая отдельная фича, которая не вписывается в текущую концепцию пропа `type`. Я предлагаю вынести эту фичу в отдельный проп. Это позволит снизить когнитивную нагрузку пользователей и избавиться от путаницы с неймингом

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/Textarea/Textarea.tsx
> +      ...(isTheme2022(this.theme) ? { backgroundClip: 'padding-box' } : {}),
Давай тогда поправим во всех местах где встречается подобный код: `TokenInput` и `Menu`

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/OkIcon.tsx
> +export const OkIcon = iconSizer(
> Названия исходных иконок довольно громоздкие и буквально описывают что в иконке отрисовано.
В таком виде их не удобно использовать в компонентах.

У такого нейминга есть идея - он контексто-независимый. Это позволяет использовать одну и ту же иконку в различных местах, без изменения названия. Так, например, иконка крестика в одном контексте может обозначать закрытие - `CloseIcon`, а в другом удаление - `DeleteIcon`, поэтому она названа `CrossIcon`, что позволяет использовать её в любом контексте

И задавая свои имена иконкам мы как раз ломаем эту логику и плодим лишний контекст. Теперь у нас в двух разных местах есть две одинаковые иконки, которые выглядят одинаково, но называются по-разному. Ломается одно из основных правил нейминга переменных: _"у одной сущности должно быть одно название"_

[Комментарий](https://github.com/skbkontur/retail-ui/pull/3045#discussion_r1127276383) из другого треда:
> Например, исходная CheckAIcon становится CheckedIcon в `<Checkbox>` и OkIcon в `<FileUploader>`

<hr />

> При возможных изменениях оригинальной иконки код компонента не придётся менять. Например, если для определённого size проектировщики заменят начертание, или целиком заменят иконку.

Пока что таких изменений не происходило, но даже если они произойдут в будущем, то нам всё равно придётся обновлять содержимое иконки, а обновить вместе с этим название - не проблема

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/internal/CloseButtonIcon/__stories__/CloseIcon.stories.tsx
> +};
Тут по-прежнему скипаются тесты

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/PasswordInput/ClosedIcon.tsx
> +);
Предлагаю в таких файлах оставлять имена иконок из пакета, мотивацию описал выше

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/internal/CloseButtonIcon/CloseButtonIcon.tsx
> +  ...attrs
Кажется, что такое название только вызывает дополнительные вопросы =)
Думаю, что нам ничего не мешает использовать стандартный `...rest`

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/Toast/ToastView.tsx
> +            data-tid={ToastDataTids.close}
Я имею ввиду, что наш `data-tid` может быть только строкой. Сейчас в него можно передать что угодно
Предлагаю унаследовать тип от `CommonProps`

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
>    },
Тут перепутаны значения: в новой теме синяя обводка, в дефолтной - серая

<table>
<tr>
	<th> Дефолтная тема
	<th> Тема 2022
<tr>
	<td> 

https://user-images.githubusercontent.com/48599460/228496250-b164ba1f-4c22-476b-b5c1-e35443320f7a.mov


<td>


https://user-images.githubusercontent.com/48599460/228499126-0ea46c00-c128-4358-a686-bc876a6a2c4b.mov


</table>

2023-03-29 10:21 UTC, JackUait commented on packages/react-ui/components/Checkbox/Checkbox.styles.ts
> +      width: ${t.checkboxIconWidth};
Переменные `checkboxIconTop`, `checkboxIconLeft`, `checkboxIconHeight` и `checkboxIconWidth` остались в теме

<hr />

И давай накинем тестов на это поведение

2023-04-03 06:49 UTC, lossir commented on packages/react-ui/components/Loader/Loader.tsx
> +  type?: LoaderType;
Да, в доке Лоадера плохо получилось, но дело в экстракте типов, который не может распарсить docgen.
Решил сделать как в Спинере. Тип Лоадера всё равно прокидывается в Спинер, и при несоответствии тс отреагирует.

2023-04-17 13:21 UTC, lossir commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/OkIcon.tsx
> +export const OkIcon = iconSizer(
`ArrowShapeDRadiusUpLeftIcon` - это иконка, как ты правильно говоришь, контексто-независимая. Т.е. её название не пытается предопределить место использования, что хорошо и правильно.

`UndoIcon` - это высокоуровневая абстракцией над `ArrowShapeDRadiusUpLeftIcon`, и будет использоваться в одном конкретном смысле - "отменить действие".

Если чуть детальнее, то `ArrowShapeDRadiusUpLeftIcon` - это "цельная" иконка, вмещающая все 10 "гранулярных" начертаний. При указании размера и веса мы получаем ожидаемое начертания.
`UndoIcon` имеет только 3 "гранулярных" начертания, и для каждого контрола разные. Эти начертания можно получить только через абстрактные значения размера - `small | medium | large` .

👉 Поэтому иконку `UndoIcon` не стоит называть так же, как называется цельная иконка в пакете иконок.
Это разные сущности с разным АПИ и предназначением.

---

В контролах `<Checkbox>` и `<FileUploader>` используется иконка `CheckAIcon`, но она очень отличается из-за контекста:

|  | `<FileUploader>` |  `<Checkbox>` |
| -- | -- | -- |
|  | `OkIcon` | `CheckedIcon` |
`small` | `<CheckAIcon16Light disableCompensation={false} />` | `<CheckAIcon16Solid size={12} />`
`medium` | `<CheckAIcon20Light disableCompensation={false} />` | `<CheckAIcon16Solid />`
`large` | `<CheckAIcon24Regular disableCompensation={false} />` | `<CheckAIcon20Solid />`

_\* `disableCompensation={false}` - это строчное позиционирование._

И если хранить все иконки в одной папке, то условная общая `CheckAIcon` должна уметь разруливать такое.
В этом случае логика внутри единого файла сильно усложниться.

👉 Считаю, что проще и правильней просто создавать отдельные файлы иконок для каждого контрола.

---

При работе в коде компонента также важна семантика. Названия иконок можно сравнить с html-элементами.
без контекста | с контекстом
-- | --
`<div />` | `<h1 />`
`<div />` | `<header />`
`<ArrowShapeDRadiusUpLeftIcon />`  | `<UndoIcon />`
`<ShapeSquareIcon />` | `<IndeterminateIcon />`

Если представить, что мы позволим кастомизировать иконки в контролах как в `material-ui`, то проп `uiMenuDotsThreeVIcon` будет слишком сложен для использования:
```html
<Kebab uiMenuDotsThreeVIcon={<UiMenuBarsThreeHIcon />} />
             ^^^^                   ^^^^
```

Больше семантики:
```html
<Kebab kebabIcon={<UiMenuBarsThreeHIcon />} />
```

👉 И нам и пользователям будем намного понятнее работать с семантичными именами.

2023-04-20 10:03 UTC, lossir commented on packages/react-ui/components/Modal/relinkModalTheme.ts
> +export const relinkModalTheme = (theme: Theme): Theme => {
Переименовал в `get*Component*Theme`.

2023-04-20 10:03 UTC, lossir commented on packages/react-ui/components/Textarea/Textarea.tsx
> +      ...(isTheme2022(this.theme) ? { backgroundClip: 'padding-box' } : {}),
Не вижу подобного кода в `<TokenInput>` и `<Menu>`. Может я поправил отдельно, или что-то не так понял.
Укажи ссылки плиз, если такой код ещё остался

2023-04-20 10:03 UTC, lossir commented on packages/react-ui/internal/CloseButtonIcon/__stories__/CloseIcon.stories.tsx
> +};
Добавил стори. Тесты добавлю после всех правок, вместе с другими для темы2022.

2023-04-20 10:04 UTC, lossir commented on packages/react-ui/components/PasswordInput/ClosedIcon.tsx
> +);
Описал свою мотивацию там же.

2023-04-20 10:06 UTC, lossir commented on packages/react-ui/internal/CloseButtonIcon/CloseButtonIcon.tsx
> +  ...attrs
Переименовал

2023-04-20 10:07 UTC, lossir commented on packages/react-ui/components/Toast/ToastView.tsx
> +            data-tid={ToastDataTids.close}
Добавил `CommonWrapper`

2023-04-21 06:50 UTC, lossir commented on packages/react-ui/components/FileUploader/FileUploader.styles.ts
>    },
Первое у меня не воспроизводится. Второе поправил.

2023-04-21 06:50 UTC, lossir commented on packages/react-ui/components/Checkbox/Checkbox.styles.ts
> +      width: ${t.checkboxIconWidth};
Удалил переменные.
Фичу с кастомизацией в старых темах удалил.

На эту переменную уже есть тест в сторях `Baseline / Different fonts in medium`
и  `Baseline / Different fonts in large`.

2023-04-21 06:51 UTC, lossir commented on packages/react-ui/components/Modal/ModalSeparator.tsx
> +}
Тесты появится в рамках тестов на Modal и SidaPage, когда добавлю тему2022 в криви.

2023-04-21 06:51 UTC, lossir commented on packages/react-ui/components/Group/Group.tsx
> +    return React.cloneElement(child, { corners: { ...corners, ...child.props.corners } });
Появится, когда добавлю тему2022 в криви

2023-04-21 10:50 UTC, lossir commented on packages/react-ui/components/Spinner/Spinner.tsx
> +export type SpinnerType = 'mini' | 'normal' | 'big' | 'small' | 'medium' | 'large';
Решил сделать специальную иконку - `<LoadingIcon>`, которая основана на `<SpinnerIcon>`, но её можно использовать как обычную иконку. И она подчиняется общим правилам с размерами `size`.

2023-04-21 10:53 UTC, lossir commented on packages/react-ui/internal/CloseButtonIcon/CloseButtonIcon.tsx
> +  focusable?: boolean;
Добавил описания и сторисы. Скрины добавлю вместе с другими

2023-05-05 04:27 UTC, JackUait submitted a review, later dismissed
Других комментариев к последним коммитам у меня нет :)
Если с тестами ничего не поделать - это аппрув, но хотелось бы понять почему это может происходить

Давай только обновим описание пулл-реквеста для исторической справки

2023-05-05 04:27 UTC, JackUait commented on packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
> +    },
А как могло получиться так, что эти тесты не проходят только на `TC`? Могли эти скриншоты падать просто из-за нагрузки на `TC`?

2023-05-10 07:59 UTC, lossir commented on packages/react-ui/components/TokenInput/__stories__/TokenInput.stories.tsx
> +    },
Периодически всплывает такая проблема. Думаю, обычно это связано с асинхронным кодом.

Например, в этом случае, метод `handleTokenEdit()` вызывает в конце метод `tryGetItems()`:
https://github.com/skbkontur/retail-ui/blob/255c3671423309ebb6c1ca9ad3eef3471d153502/packages/react-ui/components/TokenInput/TokenInput.tsx#L915

Который в свою очередь является асинхронных:
https://github.com/skbkontur/retail-ui/blob/255c3671423309ebb6c1ca9ad3eef3471d153502/packages/react-ui/components/TokenInput/TokenInput.tsx#L658

А этот метод уже может вызвать диспатчер, который будет асинхронно обновлять стейт.
Т.к. локальное окружение и окружение тимсити отличаются, то может возникать разница в задержках. Обычно мы это лечит "ожиданиями" в тестах, типа, `delay(500)`.

2023-05-11 13:39 UTC, merged