fix(Switcher): fix keyboard navigation with disabled items
skbkontur/retail-ui pull request #3049
Opened 2022-11-23 10:51 UTC by semkedaniil

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-11-28 09:12 UTC, zhzz requested changes
Спасибо за помощь! Было бы совсем круто заполнить описание ПРа и докинуть тестов, если есть на это время.

2022-11-28 09:12 UTC, zhzz commented on packages/react-ui/components/Switcher/Switcher.tsx
> -  private move = (step: number) => {
Думаю, метод `move` лучше оставить. Он помогает более читаемо организовать логику. А аргумент `step` просто переисcпользовать как `direction`.

2022-11-28 09:12 UTC, zhzz commented on packages/react-ui/components/Switcher/Switcher.tsx
> +  private _getFocusedIndexByStep = (left: boolean, focusedIndex: number): number => {
Не очень понятен смысл "byStep" в названии. Как будто `step` ожидается в аргументы.  Может что-то вроде `_getNextFocusedIndex` лучше опишет функцию?

2022-11-28 09:12 UTC, zhzz commented on packages/react-ui/components/Switcher/helpers.ts
> +export const mod = (n: number, mod: number) => ((n % mod) + mod) % mod;
Чем эта формула отличается от простого `n % mod`?

2022-12-05 05:52 UTC, semkedaniil commented on packages/react-ui/components/Switcher/helpers.ts
> +export const mod = (n: number, mod: number) => ((n % mod) + mod) % mod;
Оригинальная функция при отрицательных значениях вернет отрицательное число, когда как мне нужно математическую функцию мод, при которой возвращается всегда число x∈[0, r-1], где r - число mod.
Для чего это нужно? Я беру текущий элемент в фокусе, смотрю направление согласно нажатой стрелке, при отрицательных значениях нового индекса хочется брать items.length - оставшаяся отрицательная часть. Например, newIndex = -2, тогда после преобразования по модулю 10 получим mod(-2, 10)=8 - следующий элемент , когда как обычный мод вернул бы -2, значение массива в котором undefined.

2022-12-05 06:31 UTC, zhzz commented on packages/react-ui/components/Switcher/helpers.ts
> +export const mod = (n: number, mod: number) => ((n % mod) + mod) % mod;
точняк

2022-12-05 07:00 UTC, zhzz commented on packages/react-ui/components/Switcher/Switcher.tsx
> +      this.move(newFocusedIndex);
В таком варианте смысла в методе `move` немного.

Я имел в виду, что если перенести расчет индекса следующего элемента в него (как было изначально), а в аргумент передавать направление движения, то код в этом месте будет проще читать.

2022-12-05 07:50 UTC, semkedaniil commented on packages/react-ui/components/Switcher/Switcher.tsx
> +      this.move(newFocusedIndex);
Поправил

2022-12-05 07:58 UTC, zhzz approved these changes

2022-12-06 04:51 UTC, merged