Refactor unit tests draft
skbkontur/retail-ui pull request #3053
Opened 2022-12-01 15:14 UTC by taranovakn

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-13 09:06 UTC, zhzz requested changes

2022-12-13 16:58 UTC, taranovakn commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> +    }
![image](https://user-images.githubusercontent.com/68959081/207395836-b7bcd53c-b573-470a-ab10-98cbcf3aa83c.png)
На сколько я поняла твой вопрос, то да. Если ошибки не будет и элемент будет доступен для setSelectionRange, то пройдет без catch ветки.

2022-12-14 07:35 UTC, taranovakn commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
>    it('has focus method', () => {
Переименовала

2022-12-16 08:56 UTC, zhzz requested changes

2022-12-16 08:56 UTC, zhzz commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> +    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
Зачем разделять тесты, они же про одно и тоже?

Замоканный `console.error` в конце нужно восстанавливать.

2022-12-16 11:27 UTC, taranovakn commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> +    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
Удалила дублирующий тест и добавила в конце теста consoleSpy.mockRestore();

2022-12-19 05:15 UTC, zhzz commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> +    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
Ты удалила "selectAllOnFocus prop works", но он был не при чем, он нужен.

Я имел в виду тесты "MaskedInput props dont pass in HtmlNode" и "MaskedInput props dont pass in HtmlNode2". Они были про одно и тоже. Ты удалила первый, но он тоже нужен. Я предлагал их объединить.

2022-12-19 07:14 UTC, taranovakn commented on packages/react-ui/components/Input/__tests__/Input-test.tsx
> +    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => {});
Да, тест ошибочно удалила. Вернула его обратно, добавила проверку из теста MaskedInput props dont pass in HtmlNode во второй MaskedInput props dont pass in HtmlNode2. Оставила только 1 тест из 2.

2022-12-20 03:57 UTC, zhzz approved these changes

2022-12-20 03:57 UTC, merged