feat(ScrollContainer): add `offsetY`/`offsetX` to offset scrollbar
skbkontur/retail-ui pull request #3054
Opened 2022-12-01 17:42 UTC by lossir

## Проблема

В макете темы2022 Дроплист получил скруглённый углы. Из-за чего скроллбар пришлось немного подвинуть.

Но текущие возможности не позволяют это сделать.

## Решение

- Добавил 2 пропа `offsetY`/`offsetX` для смещения скроллбара.
- В процессе рефакторинга вёрстки для фичи, исправил некоторые недочеты и решил что они походят на баг. Поэтому обновил все скриншоты со скроллбаром.

## Ссылки

Детали здесь `IF-876`

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ✅ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-02 09:09 UTC, zhzz requested changes

2022-12-02 09:09 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.helpers.ts
> +    scrollPos = containerSize && (100 / containerSize) * scrollPos;
Зачем понадобилось перевести в проценты? Вот [тут](IF-876) должно было сломаться, т.к. раньше вычитались  пиксели.

2022-12-02 09:09 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    },
Дефолтные значение дублируются в стилях и тут.

2022-12-02 09:09 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollBar.tsx
> +    return cx(globalClasses.scrollbarContainerY, styles.scrollBarYContainer());
Разный стиль `scrollbarContainerY` и `scrollBarYContainer`.

2022-12-02 14:18 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollContainer.helpers.ts
> +    scrollPos = containerSize && (100 / containerSize) * scrollPos;
Чтобы учесть смещение в пикселях надо тянуть эти смещения в хелпер и использовать в расчётах.
С процентами же можно не думать о смещении и переложить это на стили и контейнер скроллбара.

В месте, что ты указал, действительно была проблема. Переписал на использование процентами.
Если бы остались пиксели, то тоже пришлось бы учитывать смещения в расчётах.

По крайней мне самому такой подход кажется проще.

2022-12-02 14:18 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    },
Убрал из стилей

2022-12-05 05:37 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.helpers.ts
> +    scrollPos = containerSize && (100 / containerSize) * scrollPos;
Ясно, неплохой ход. 

Такие детали тоже стоит описывать в ПРе, чтобы было меньше итераций ревью и больше информации для будущих раскопок. 

Цитата из шаблона ПРа:
> В деталях опиши предлагаемые изменения, мотивацию принятых решений и все неочевидные моменты

2022-12-05 05:42 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +    },
Теперь если указать не все поля смещения, то скролбар пропадает:

![image](https://user-images.githubusercontent.com/4607770/205557908-16a65555-fd12-4bb4-b0be-f6147c57b006.png)

2022-12-05 05:45 UTC, zhzz requested changes
> ✅ скриншоты для верстки и кросс-браузерности

Были обновлены только старые скриншоты. Стоит также добавить и новых на новую функциональность.

2022-12-05 12:55 UTC, zhzz requested changes

2022-12-05 12:55 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  offsetY?: Record<OffsetCSSPropsY, React.CSSProperties[OffsetCSSPropsY]>;
Теперь обязательно все три свойства указывать: `top` , `right` и `bottom`. Только одно из них или два не получится, типы не дадут.

2022-12-06 03:56 UTC, lossir commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  offsetY?: Record<OffsetCSSPropsY, React.CSSProperties[OffsetCSSPropsY]>;
<img align="middle" width="67" alt="Снимок экрана 2022-12-05 в 19 00 23" src="https://user-images.githubusercontent.com/2708211/205655477-966be46d-eaef-4fa9-b3de-8a3775c1a754.png"> Вроде всё проверил, но всё равно что-то пропустил.

Изменил одну стори, чтобы этот момент тоже проверялся.

2022-12-06 04:49 UTC, zhzz approved these changes

2022-12-06 04:50 UTC, merged