feat(toast): add timeout props in Toast
skbkontur/retail-ui pull request #3062
Opened 2022-12-07 09:50 UTC by Nejjer

## Проблема

У компонента Toast не было возможности установить время существования. Из-за этого возникали трудности
[Тред
](https://kontur.slack.com/archives/C013HTCE18Q/p1669883797115159)
## Решение
Добавил Toast необязательный пропс timeOut, который устанавливает время существования.
Если пропса нет, то компонент ведет себя как раньше:

1. Существует 3 секунды, если нет action
2. Существует 7 секунд, если нет action

Если пропс есть, то компонент при любых условиях существует столько, сколько передали в пропсах

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

4. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

5. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

6. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-01-20 10:05 UTC, lossir commented on packages/react-ui/components/Toast/Toast.tsx
> +    let timeOut = this.state.action ? 7 : 3;
Раз время показа Тоста становится регулируемым, то давай перейдём на миллисекунды.
А то старое решение выглядит как очень странная оптимизация.

2023-01-20 10:05 UTC, lossir commented on packages/react-ui/components/Toast/Toast.md
> +Вызов статических методов, c кастомным timeOut'ом
Надо добавить новый пример, не трогая старый.
И добавить ещё один пример, когда разработчик не передаёт `action`, но время показа задать хочет.

2023-01-24 09:21 UTC, lossir submitted a review, later dismissed

2023-01-24 10:29 UTC, zhzz requested changes
Если добавили настройку в один метод отображения Toast ([через ref](https://tech.skbkontur.ru/react-ui/#!/Components/Toast/Toast/3)), то нужно добавить и в другой ([через статический метод](https://tech.skbkontur.ru/react-ui/#!/Components/Toast/Toast/1)).

2023-01-24 10:29 UTC, zhzz commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
Какой предполагается результат, если пользователь передаст в timeout `0`?

2023-01-25 06:22 UTC, Nejjer commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
Если пользователь передаст в timeout 0, то обычный сценарий. Т.е 7 секунд или 3

2023-01-25 08:32 UTC, zhzz commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
Но почему? Ведь `0` это такое же определенное значение, как `1` или `10000`.

Может быть, кстати, это имя "timeout" сбивает с толку. Что если бы он назывался "showTime"?

2023-01-25 11:43 UTC, Nejjer commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
А я как-то не сильно задумывался по поводу нуля и считал его "специальным" значением. Но щас понял, что он должен быть обычным значением. Изменить условие на `this.state.timeout !== undefined` подойдет?
И "showTime" звучит более значимо. Переименую

2023-01-25 12:59 UTC, zhzz commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
Лучше использовать оператор `??`

2023-01-26 07:01 UTC, Nejjer commented on packages/react-ui/components/Toast/Toast.tsx
> +    timeOut = this.state.timeout ? this.state.timeout : timeOut;
Пофиксил

2023-01-31 03:32 UTC, zhzz approved these changes

2023-01-31 06:31 UTC, merged