fix(theme): add copying theme markers then `overrideDefaultTheme()`
skbkontur/retail-ui pull request #3073
Opened 2022-12-20 07:14 UTC by lossir

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-22 13:18 UTC, zhzz requested changes

2022-12-22 13:18 UTC, zhzz commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    });
Поскольку тема сейчас это объект с цепочкой прототипов, и маркеры там не `enumerable` (собственно, источник проблемы), то было бы проще и логичнее переделать `overrideDefaultTheme` на простой перенос свойств и цепочки прототипов переданной темы, как они есть. 

```ts
    Object.defineProperties(DefaultThemeInternal, Object.getOwnPropertyDescriptors(theme));
    Object.setPrototypeOf(DefaultThemeInternal, Object.getPrototypeOf(theme));
```

2023-01-11 08:14 UTC, lossir commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    });
Это приведёт к цикличеcкой ошибке из-за попытки добавить в цепочку прототипов `DefaultThemeInternal` самого себя.
Дело в том, что объект `theme`, создаваемый через `create()`, по-умолчанию прототипируется на основе `DefaultThemeInternal`.

Метод `create()`:
https://github.com/skbkontur/retail-ui/blob/cce869186704b6e59c1a4e1b71aac0820d431195/packages/react-ui/lib/theming/ThemeFactory.ts#L9-L10
Метод `constructTheme()`:
https://github.com/skbkontur/retail-ui/blob/cce869186704b6e59c1a4e1b71aac0820d431195/packages/react-ui/lib/theming/ThemeFactory.ts#L37

Системные темы (кроме старых) тоже прототипируются от `DefaultThemeInternal`.
Например, тёмная тема:
https://github.com/skbkontur/retail-ui/blob/cce869186704b6e59c1a4e1b71aac0820d431195/packages/react-ui/internal/themes/DarkTheme.ts#L234-L237

---

Ошибку можно воспроизвести таким кодом:
```js
1: const BASE = {};
2: const THEME = Object.create(BASE);
3: Object.setPrototypeOf(BASE, Object.getPrototypeOf(THEME));
```

На что получим следующее:

```diff
-Uncaught TypeError: Cyclic __proto__ value
-    at Function.setPrototypeOf (<anonymous>)
-    at <anonymous>:4:8
```

---

Текущий код мне кажется оптимальным решением, т.к. не требует рефакторинга самого механизма темизации.

2023-01-11 08:14 UTC, lossir commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    const _markers = Array.isArray(baseThemeOrMarkers) ? baseThemeOrMarkers : Array.isArray(markers) ? markers : [];
Т.к. появился уже второй маркер, и их можно применять одновременно, я решил сделать механизм прозрачнее. Правильный объект темы можно создать только методом `create()`, поэтому мне показалось логичным доработать именно его, а он публичный.

Но сейчас я понял, что в методе `overrideDefaultTheme()` копируются только маркеры из системного списка.
Если пользователь и захочет сам маркировать тему, то надо будет что-то придумывать, как копировать его маркеры вместе с системными...
Просто скопировать цепочку прототипов не получится, а передать массив имён вторым аргументом или что-то такое выглядит слишком громоздко..

Сделаю маркирование снова чисто служебным.

2023-01-12 10:46 UTC, zhzz commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    });
Ок, не учел этого и не проверил на реальном примере, прежде чем предложить.

2023-01-12 10:59 UTC, zhzz commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    const _markers = Array.isArray(baseThemeOrMarkers) ? baseThemeOrMarkers : Array.isArray(markers) ? markers : [];
К слову, маркирование также используется в [аддонах](https://git.skbkontur.ru/ui/ui-parking/-/blob/master/packages/react-ui-addons/internal/themes/AddonsTheme.ts#L93). Тоже для служебных целей. Потенциально может использоваться и в других пакетах на основе react-ui для темизации.

От системного списка все же можно было бы избавиться, если хранить все маркеры в одном поле. Тогда достаточно будет скопировать только его. Но можно оставить эту оптимизацию на будущее, если она понадобится.

2023-01-12 10:59 UTC, zhzz approved these changes

2023-01-12 15:45 UTC, lossir commented on packages/react-ui/lib/theming/ThemeFactory.ts
> +    const _markers = Array.isArray(baseThemeOrMarkers) ? baseThemeOrMarkers : Array.isArray(markers) ? markers : [];
Хорошая мысль, хранить в одном поле. Но я надеюсь мы перейдёт на css переменные раньше, чем такая доработка понадобится)

2023-01-13 04:32 UTC, merged