Refactor screenshot tests for input
skbkontur/retail-ui pull request #3075
Opened 2022-12-20 11:38 UTC by taranovakn

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-01-12 06:30 UTC, zhzz requested changes

2023-01-12 06:30 UTC, zhzz commented on packages/react-ui/components/Input/__stories__/InputCreevey.stories.tsx
> +      skip: { in: /^(?!\bchrome\b)/, reason: `themes don't affect logic` },
Эти тесты не нужно прогонять в каждой теме, но желательно прогнать в каждом браузере. Сейчас они гоняются только в хроме.

2023-01-12 06:30 UTC, zhzz commented on packages/react-ui/components/Input/__stories__/InputCreevey.stories.tsx
> +// TODO: Rewrite stories and enable rule (in process of functional refactoring).
Думаю, стоит называть подобные файлы с историями  для тестов `*.creevey.stories.tsx`, чтобы сохранить отдельное имя компонента в названии.

2023-01-12 06:30 UTC, zhzz commented on packages/react-ui/components/Input/__stories__/InputCreevey.stories.tsx
> +// TODO: Rewrite stories and enable rule (in process of functional refactoring).
К этому файлу действительно не применен prettier, о чем и говорит lint на TC.

2023-01-12 06:30 UTC, zhzz commented on packages/react-ui/.storybook/manager.js
> +import { addons } from '@storybook/addons';
Этот файл можно спокойно переименовать в `manager.ts`, для аналогии с соседними.

2023-01-13 08:36 UTC, taranovakn commented on packages/react-ui/components/Input/__stories__/InputCreevey.stories.tsx
> +      skip: { in: /^(?!\bchrome\b)/, reason: `themes don't affect logic` },
Добавила прогоны в FF и IE11

2023-01-13 08:37 UTC, taranovakn commented on packages/react-ui/.storybook/manager.js
> +import { addons } from '@storybook/addons';
Переименовала

2023-01-13 09:18 UTC, taranovakn commented on packages/react-ui/components/Input/__stories__/InputCreevey.stories.tsx
> +// TODO: Rewrite stories and enable rule (in process of functional refactoring).
Исправила

2023-01-13 10:24 UTC, zhzz approved these changes

2023-01-13 11:19 UTC, zhzz commented
Странный скриншот получился в хроме и падает на ТС:

![image](https://user-images.githubusercontent.com/4607770/212308093-3a43b726-2851-4c98-ba73-5aee3c3085d1.png)

2023-01-20 11:03 UTC, merged