feat(ComboBox, DatePicker, Select, Autocomplete): add prop pos for manual control of dropdown position
skbkontur/retail-ui pull request #3076
Opened 2022-12-21 00:41 UTC by JackUait

## Проблема

У компонентов основанных на `DropdownContainer` (`ComboBox`, `DatePicker`, `Select`, `Autocomplete`) не было возможности задать текущую позицию выпадающего окна вручную. 

## Решение

1. Добавил во все компоненты основанные на `DropdownContainer` проп `pos: "top" | "bottom"`, с помощью которого пользователи могут задать текущую позицию выпадающего окна;
2. По ходу решения выяснилось, что компонент `Autocomplete` некорректно работает с пропом `disablePortal` (см. IF-918). Не добавлял тесты на `disablePortal` + `pos` в этом компоненте.

## Ссылки

IF-883, IF-918

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

3. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

4. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

5. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-23 05:29 UTC, zhzz requested changes

2022-12-23 05:29 UTC, zhzz commented on packages/react-ui/internal/DropdownContainer/DropdownContainer.tsx
> +        ...getManualPositionWithoutPortal({ pos: this.props.pos, target, offsetY }),
Зачем еще раз что-то высчитывать, если тут просто конвертируется уже заранее высчитанная позиция?

2022-12-23 06:03 UTC, HelenaIsh commented on packages/react-ui/internal/DropdownContainer/getManualPosition.ts
> +export const getTopAligment = ({
```suggestion
export const getTopAlignment = ({
```

2022-12-23 06:03 UTC, HelenaIsh submitted a review, later dismissed

2022-12-23 09:05 UTC, JackUait commented on packages/react-ui/internal/DropdownContainer/getManualPosition.ts
> +export const getTopAligment = ({
Поправил

2022-12-23 09:05 UTC, JackUait commented on packages/react-ui/internal/DropdownContainer/DropdownContainer.tsx
> +        ...getManualPositionWithoutPortal({ pos: this.props.pos, target, offsetY }),
- Удалил функцию `getManualPositionWithoutPortal`
- Переименовал функцию `getManualPositionWithPortal` в `getManualPosition`

2022-12-23 10:23 UTC, HelenaIsh approved these changes

2022-12-23 10:36 UTC, zhzz approved these changes
Учитывая что в этих компонентах уже есть такие пропы как `menuAlign` и `menuWidth`, было бы уместно новый проп назвать соответственно `menuPos`.

2022-12-23 11:20 UTC, JackUait commented
> Учитывая что в этих компонентах уже есть такие пропы как menuAlign и menuWidth, было бы уместно новый проп назвать соответственно menuPos.

Я называл проп опираясь на название соответствующего пропа в выпадашках основанных на `Popup`

2022-12-27 00:22 UTC, JackUait commented
Переименовал проп `pos` в `menuPos` во всех компонентах из задачи, в том числе и в `DropdownContainer`, по причине того, что при переименовании пропа в типах (`menuPos: DropdownContainer['pos']`)  теряется документация, которая при наследовании через `Pick` сохраняется. Компонент `DropdownContainer` - внутренний и в нём мы в любой момент сможем обратно переименовать проп, если это понадобится, а сейчас такой подход даёт нам единый источник правды для документации

P.S.
Можно, конечно, было пойти от противного и наследовать проп от одного из компонентов основанных на `DropdownContainer` и в самом `DropdownContainer` этот проп переименовывать, но в таком случае терялась бы связь ребёнок-родитель

2022-12-30 08:10 UTC, HelenaIsh approved these changes

2023-01-09 05:36 UTC, zhzz approved these changes

2023-01-13 03:39 UTC, merged