feat(react-ui-validations): allow to customize the data-tid attribute in tooltip and text functions
skbkontur/retail-ui pull request #3081
Opened 2022-12-29 00:49 UTC by JackUait

## Проблема

## Решение

## Ссылки

IF-927

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2022-12-30 08:22 UTC, HelenaIsh requested changes
Нужно добавить  в [документацию апи](https://tech.skbkontur.ru/react-ui-validations/#/api) информацию о новом аргументе для `tooltip` и `text`

А также можно упомянуть о новых аргументах на страничке "[Сообщения об ошибках](https://tech.skbkontur.ru/react-ui-validations/#/error-messages)"

2022-12-30 08:22 UTC, HelenaIsh commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +export interface ErrorRendererOptions {
Не критично, но мне кажется, что лучше переименовать в `RenderErrorOptions` по аналогии с `RenderErrorMessage`

2022-12-30 10:58 UTC, lossir commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +export function tooltip(pos: TooltipPosition, options?: ErrorRendererOptions): RenderErrorMessage {
Раз дошло дело до объекта с опциями, то предлагаю сделать что-то такое:
```typescript
export interface RenderErrorOptions {
  dataTid?: string;
  pos?: TooltipPosition;
}

export function tooltip(pos: TooltipPosition): RenderErrorMessage;
export function tooltip(options: RenderErrorOptions): RenderErrorMessage;
export function tooltip(posOrOptions?: TooltipPosition | RenderErrorOptions): 
```

2023-01-11 07:02 UTC, JackUait commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +export interface ErrorRendererOptions {
Переименовал

2023-01-11 07:02 UTC, JackUait commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +export function tooltip(pos: TooltipPosition, options?: ErrorRendererOptions): RenderErrorMessage {
Честно говоря, кажется, что с таким подходом мы значительно усложним код, а пользователи от этого почти ничего не выиграют (80% усилий, 20% результата). Предлагаю пока оставить всё как есть. Если в будущем к текущим аргументам добавятся новые аргументы с приоритетом сопоставимым с приоритетом `pos` - можно будет вернуться к перегрузке

2023-01-11 07:38 UTC, HelenaIsh commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +        data-tid={options?.dataTid}
в `ValidationTooltipProps` нет поля `data-tid`. Нужно добавить

2023-01-11 07:54 UTC, JackUait commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +        data-tid={options?.dataTid}
Добавил

2023-01-11 08:45 UTC, HelenaIsh approved these changes

2023-01-12 05:27 UTC, lossir requested changes

2023-01-12 05:27 UTC, lossir commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +        <span data-tid={options?.dataTid} style={{ display: 'inline-block' }}>
Этот span оборачивает и текст ошибки и сам Контрол, причем независимо от наличия ошибки.
Дата-тид надо перенести на span ниже, у которого атрибут `data-validation-message="text"`.

2023-01-12 05:27 UTC, lossir commented on packages/react-ui-validations/tests/ErrorRenderer.test.tsx
> +  it('should pass custom data-tid to text', () => {
Стоит добавить тест на отсутствие дата-тида, когда `validationInfo={null}`,

2023-01-12 10:33 UTC, JackUait commented on packages/react-ui-validations/tests/ErrorRenderer.test.tsx
> +  it('should pass custom data-tid to text', () => {
У нас же в любом случае рендерится нода с `data-validation-message="text"`, даже если `validationInfo={null}`

Добавил тесты на то, что если `validationInfo={null}`:
- `text` рендерит пустую ноду;
- `tooltip` не рендерит ничего.

2023-01-12 10:33 UTC, JackUait commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +        <span data-tid={options?.dataTid} style={{ display: 'inline-block' }}>
Здесь `data-tid` передаётся на корень по [аналогии](https://github.com/skbkontur/retail-ui/pull/2257#:~:text=%D0%BF%D1%80%D0%BE%D0%BA%D0%B8%D0%B4%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B8%D1%85%20%D0%B2%D1%81%D0%B5.-,%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83%20%D0%BD%D0%B0%20%D0%BA%D0%BE%D1%80%D0%B5%D0%BD%D1%8C%3F,-%D0%A1%D0%B5%D0%B9%D1%87%D0%B0%D1%81%20%D1%83%D0%B6%D0%B5%20%D0%B5%D1%81%D1%82%D1%8C) с `react-ui`, чтобы у пользователей был доступ ко всему содержимому компонента. Согласен, что в этом кейсе получается не совсем очевидное поведение для пользователей, но я думаю что стоит оставить всё так как есть потому что:
- В `tooltip` у нас такое же поведение и там мы его не можем исправить;
- Это кривой, но тем не менее способ получить доступ к `ValidationWrapper` у которого нет своего `data-tid`'а (на него такого запроса пока не поступало).

2023-01-12 15:39 UTC, lossir commented on packages/react-ui-validations/tests/ErrorRenderer.test.tsx
> +  it('should pass custom data-tid to text', () => {
Предложение исходило из моего представления об потребностях заказчика фичи.
В комментарии выше это пункт 2. Думаю, после уточнения станет ясно как лучше делать.

2023-01-17 10:30 UTC, JackUait commented on packages/react-ui-validations/src/ErrorRenderer.tsx
> +        <span data-tid={options?.dataTid} style={{ display: 'inline-block' }}>
1. Про `tooltip()` я имел ввиду, что в нём также как и в `text()` `data-tid` прокидывается на корень и в `tooltip()` (в отличие от `text()`) мы не можем изменить это поведение
2. Если мы дадим ему инструменты для реализации более общего сценария, то с помощью этих инструментов он сможет реализовать свой. Собственно, от части такая же [мотивация](https://github.com/skbkontur/retail-ui/pull/2257#:~:text=%D0%BF%D1%80%D0%BE%D0%BA%D0%B8%D0%B4%D1%8B%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B8%D1%85%20%D0%B2%D1%81%D0%B5.-,%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83%20%D0%BD%D0%B0%20%D0%BA%D0%BE%D1%80%D0%B5%D0%BD%D1%8C%3F,-%D0%A1%D0%B5%D0%B9%D1%87%D0%B0%D1%81%20%D1%83%D0%B6%D0%B5%20%D0%B5%D1%81%D1%82%D1%8C) стоит и за решением прокидывать `data-tid`'ы на корень в `react-ui`

2023-02-09 18:25 UTC, lossir commented on packages/react-ui-validations/docs/Pages/Api.md
> +### `data-tid?: string`
При рендере по-умолчанию, через `tooltip()`, дата-тид прокидывается непосредственно на Попап с ошибкой.

<details>
<summary>ℹ️ В Сторибуке можно заметить дата-тид и на корне.</summary>

В сторибуке это делает пакет `@skbkontur/react-props2attrs`.
Он транслирует пропы в атрибуты согласно фильтру в файле:
`packages/react-ui-validations/.storybook/preview.ts`

Чтобы выключить трансляцию, фильтр должен вернуть пустой массив:
```js
setFilter(() => []);
```

---

</details>

Заказчик уточнил, что хочет получать непосредственно текст ошибки.
Но т.к. прокидывание дата-тида работает по разному, то в зависимости от `renderMessage` придётся менять и селектор:

| `renderMessage` | `selector` |
| --- | --- |
| `text()` | `[data-tid=<КАСТОМНЫЙ-TID>] [data-validation-message=text]` | 
| `tooltip()` | `[data-tid=<КАСТОМНЫЙ-TID>]` | 

Думаю, это не очень удачное АПИ для тестирования.
Стоит реализовать так, чтобы селектор поиска текста ошибки не менялся. По крайней мере пока пользователь использует наши `text()` и `tooltip()`.

---

Мне приходят в голову такие варианты:
1. Например, можно вернуть прокидывание дата-тида через эти самые `text()` и `tooltip()`, но навешивать их непосредственно не текст ошибки.
2. Или добавить новый проп для `ValidationWrapper`, типа, `messageDataTid`.
3. Или прокидывать дата-тид с `ValidationWrapper` на текст ошибки, а не на корень.
По сути с `tooltip()`так и происходит в текущей реализации.

Вариант (3) мне кажется удобнее всех.
Я не вижу потенциальной пользы от навешивания дата-тида на весь корень валидации. И то селекторы буду работать только при  использовании `text()`. Если "исправить" прокидывание дата-тида для `tooltip()`, то текст ошибки достать селектором не получится из-за использования портала.
Других полезных данных в обёртке валидации вроде и нету, в отличии от контролов.

2023-02-21 08:12 UTC, JackUait commented on packages/react-ui-validations/docs/Pages/Api.md
> +### `data-tid?: string`
Реализовал третий вариант

2023-02-21 15:18 UTC, lossir commented on packages/react-ui-validations/tests/ErrorRenderer.test.tsx
> +    expect(input.container.querySelector('[data-validation-message="text"]')).toBeEmptyDOMElement();
Давай здесь тоже подвяжемся на дата-тид. А то этот атрибут и так кажется архаичным, так мы ещё и модную альтернативу добавляем.

2023-02-21 21:35 UTC, JackUait commented on packages/react-ui-validations/tests/ErrorRenderer.test.tsx
> +    expect(input.container.querySelector('[data-validation-message="text"]')).toBeEmptyDOMElement();
Готово

2023-02-27 22:41 UTC, JackUait commented
На `TC` просто упали тесты, перезапустил их

2023-03-01 10:58 UTC, merged