feat: add aria-describedby attribute to elements
skbkontur/retail-ui pull request #3094
Opened 2023-01-20 11:16 UTC by MarinaAnisi

Добавление атрибута aria-describedby компонентам, для которых может потребоваться дополнительно описание

## Проблема

У компонентов нет aria-describedby атрибутов, для добавления ссылок на доступное описание компонента (например, если есть тултип или подпись к полю), при добавлении пропса для данного значения разработчики могут самостоятельно связывать элементы и их описание

## Решение

Необходимо добавить для компонентов, которые могут нуждаться в доп. описании, атрибут aria-desribedby
При этом, нужно прокинуть этот атрибут на те элементы DOM дерева, которые являются основными при чтении страницы с помощью скринридера, например, input, button, при этом, нет смысла прокидывать атрибут на div-ы - обертки или корневой элемент компонента.

## Ссылки

fix #3093

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов - автоматически, без примеров, пример есть в чек-листе по доступности, если необходимо, то можно и в каждый добавить
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-01-24 02:33 UTC, JackUait requested changes

2023-01-24 02:33 UTC, JackUait commented on packages/react-ui/components/DateInput/DateInput.tsx
> +  ariaDescribedby?: string;
Давай каждому компоненту добавим тест на то, что:
- Атрибут `aria-describedby` передаётся на нужный элемент;
- Атрибут корректно связывает описание и элемент, у `RTL` для этого есть поиск по [description](https://testing-library.com/docs/queries/byrole/#description).

2023-02-03 13:43 UTC, MarinaAnisi commented on packages/react-ui/components/DateInput/DateInput.tsx
> +  ariaDescribedby?: string;
Добавила тесты всем измененным элементам, кроме нескольких, которые нуждаются в улучшении семантичности, после этого можно написать на них нормальные тесты, без костылей или добавления data-testid, например, это RadioGroup, Kebab
Напишу об этом в задачках/аудите самих элементов

2023-02-07 00:13 UTC, JackUait commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +        <p id="elementId">Description</p>
У `ComboBox`'а есть два состояния:
- По умолчанию (не протестировано): в этом состоянии `ComboBox` рендерит `InputLikeText`
- Редактирование (протестировано): в этом состоянии `ComboBox` рендерит `Input`

Стоит протестировать оба состояния

2023-02-07 00:18 UTC, JackUait commented on packages/react-ui/components/DateInput/DateInput.tsx
> +  ariaDescribedby?: string;
Похоже, что мы не добавили `data-tid`'ы в `Kebab`, когда добавляли их в остальные компоненты
Завёл задачу (IF-1036), в её рамках добавлю `data-tid`'ы и тест на `aria-describedby` в `Kebab`

На счёт остальных компонентов (`Tabs`, `Token`, `InputLikeText`, `RadioGroup`): думаю, что сейчас можно воспользоваться `data-tid`'ами и в последствии, когда к ним можно будет получить доступ другим образом, отрефакторим тесты

2023-02-07 00:19 UTC, JackUait commented
Появились конфликты с мастером

2023-02-17 09:47 UTC, MarinaAnisi commented on packages/react-ui/components/DateInput/DateInput.tsx
> +  ariaDescribedby?: string;
Добавила тесты на `RadioGroup`, `Tabs` и `Token`
`InputLikeText` имеет атрибут hidden и поэтому не будет отображать aria-describedby для скринридеров, надо бы подумать как его порефакторить, чтобы и вид сохранить и логику, и доступно показывать атрибуты

2023-02-21 00:05 UTC, JackUait approved these changes

2023-02-21 21:44 UTC, JackUait commented
На всякий случай дополнительно прогнал все юнит-тесты локально с актуальным мастером - все тесты прошли

2023-02-22 04:36 UTC, merged