[RadioGroup] Повышение доступности компонента
skbkontur/retail-ui pull request #3096
Opened 2023-01-20 15:39 UTC by daks01

## Проблема

Радио группа скринридером воспринимается как таблица

## Решение

Задать родительскому элементу `role="radiogroup"`, убрать `display: table`

## Ссылки

resolve 3095
https://github.com/skbkontur/retail-ui/issues/3095

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-01-23 15:30 UTC, JackUait requested changes
Из-за замены `table` на `flex` поехали скриншотные тесты

Не смог найти информацию о том, чтобы `CSS` стили влияли на `ARIA` роли. Также маковский `Voice Over` не говорит, что я нахожусь внутри таблицы, если откатить изменения:

<table>
<tr>
	<th> Без role="radiogroup" и с display: table
	<th> С role="radiogroup" и с display: table
</tr>
<tr>
<td>
<img width="500" alt="Снимок экрана 2023-01-25 в 03 48 21" src="https://user-images.githubusercontent.com/48599460/214455545-4695823b-908d-49d5-9d77-e73b4cf3f886.png">
</td>

<td> 
<img width="500" alt="Снимок экрана 2023-01-25 в 03 48 06" src="https://user-images.githubusercontent.com/48599460/214455562-d912703e-69c1-49d7-b05e-0e11a8b0c2f2.png">
</td>
</tr>
</table>

В обоих случаях отображается ожидаемый результат. Стиль `display: table` не влияет на `ARIA` роль элемента

2023-01-25 01:02 UTC, JackUait commented
Давай ещё накинем юнит-тест на проверку того, что у `RadioGroup` задана корректная роль

2023-01-25 08:52 UTC, daks01 commented
> Не смог найти информацию о том, чтобы `CSS` стили влияли на `ARIA` роли. Также маковский `Voice Over` не говорит, что я нахожусь внутри таблицы

маковский VoiceOver действительно не смотрит на css  
в других скринридерах css может влиять на семантику
https://www.456bereastreet.com/archive/201110/using_displaytable_has_semantic_effects_in_some_screen_readers/

![image](https://user-images.githubusercontent.com/1611549/214516146-6f236cfe-58de-4c00-86a8-d914566adc4c.png)

2023-01-25 12:17 UTC, JackUait commented
> у меня с энзимом возникли трудности

Мы потихоньку переводим тесты на `RTL` можно просто с помощью неё отрендерить контрол

2023-01-25 12:26 UTC, JackUait commented
> в других скринридерах css может влиять на семантику

Разобрались, что поведение на данный момент воспроизводится только в `NVDA` и разработчики приложения [не считают](https://github.com/nvaccess/nvda/issues/9760) его багом. В других популярных скринридерах, в том числе `ORCA` (который упоминается в [статье](https://www.456bereastreet.com/archive/201110/using_displaytable_has_semantic_effects_in_some_screen_readers/)) поведение не воспроизводится

Для исправления этого поведения без изменения вёрстки можно [использовать](https://plousia.com/blog/css-table-display-property-causes-nvda-announce-table) `role="presentation"`. Эффект будет таким же, как если бы мы заменили `display: table` на `display: something-else`

2023-02-06 23:45 UTC, JackUait commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +    render(<RadioGroupGeneric />);
Этот код можно упростить:
```suggestion
      render(
        <RadioGroup>
          <Radio value={'str'} />
        </RadioGroup>
      )
```

2023-02-07 00:21 UTC, JackUait commented
> Надо бы для RadioGroup дописать тесты на пропс aria-describedby, так как до этой задачи группу так просто не выцепить

[Отписался](https://github.com/skbkontur/retail-ui/pull/3094#discussion_r1098049602) в пулл-реквесте #3094

2023-02-07 05:05 UTC, daks01 commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup.test.tsx
> +    render(<RadioGroupGeneric />);
done https://github.com/skbkontur/retail-ui/pull/3096/files/51494acd9e32b46f25bc783a2005ceb07901fe58..cc9d083ec80800537653635574b15a69507624ab

2023-02-07 10:39 UTC, JackUait approved these changes

2023-02-15 11:42 UTC, merged