chore(Storybook): fix mobile view of components on theme change
skbkontur/retail-ui pull request #3100
Opened 2023-02-03 05:15 UTC by JackUait

## Проблема

При изменении темы в `Storybook` с темы по умолчанию (`DEFAULT_THEME`) на любую другую перестает отображаться мобильный вид контролов

## Решение

У нас в качестве `mobileMediaQuery` по умолчанию задано квери вида: `(max-width: 576px) and (hover: none) and (pointer: coarse)`. То есть, помимо того, что ширина экрана должна быть меньше `576px` мы должны ещё и взаимодействовать с тач-устройством, чтобы это квери сработало. Вне зависимости от того, изменён ли у нас вьюпорт средствами `Storybook`'а или нет второе условие никогда не выполнится. Поэтому для `Storybook`'а квери подменяется на `(max-width: 576px)`, но это происходит только для `DEFAULT_THEME`, из-за чего в остальных темах ломается мобильное отображение. Распространил упрощенную версию квери на остальные темы 

## Ссылки

IF-984

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-02-06 05:23 UTC, zhzz requested changes
> Поэтому для Storybook'а квери подменяется на (max-width: 576px), **_но это происходит только для DEFAULT_THEME_**, из-за чего в остальных темах ломается мобильное отображение.

А где эта логика с подменой только для `DEFAULT_THEME` определяется? Почему оно именно так работает?

2023-02-06 05:23 UTC, zhzz commented on packages/react-ui/.storybook/preview.tsx
> +        >
Ты задаешь переменную для мобильных в декораторе для задания основной цветовой темы. Как они связаны между собой?

2023-02-08 09:01 UTC, JackUait commented on packages/react-ui/.storybook/preview.tsx
> +        >
Они не связаны. Думаю, что правильнее будет вынести эту логику в декоратор для мобильных, убрав ограничение на стори с `mobile` в названии

2023-02-08 09:01 UTC, JackUait commented
> А где эта логика с подменой только для DEFAULT_THEME определяется? Почему оно именно так работает?

Это связано с тем, что `ThemeContext.Consumer` всегда возвращает `DEFAULT_THEME` в переменной `theme`, вне зависимости от того, какая тема выбрана в `Storybook`

P.S.
Не упомянул в описании, что раньше эта логика работала только со сторями у которых есть `mobile` в названии, из-за условия в декораторе

2023-02-08 11:44 UTC, zhzz commented
> Это связано с тем, что ThemeContext.Consumer всегда возвращает DEFAULT_THEME в переменной theme, вне зависимости от того, какая тема выбрана в Storybook

Но ведь так быть не должно. При выборе темы в сторибуке она полноценно складывалась в `ThemeContext`. 

Проблема на самом деле в порядке применения декораторов. Либо в том, что первый декоратор перезаписывает тему, невзирая на то, что положили в тему до него.

2023-02-08 11:56 UTC, zhzz requested changes

2023-02-08 11:56 UTC, zhzz commented on packages/react-ui/.storybook/preview.tsx
> +    const theme = themes[context.globals.theme] || DEFAULT_THEME;
Теперь этот декоратор делает две вещи. Предыдущее их разделение по функциям было логичнее.

2023-02-09 06:24 UTC, JackUait commented on packages/react-ui/.storybook/preview.tsx
> +    const theme = themes[context.globals.theme] || DEFAULT_THEME;
Провайдер темы отдаёт предпочтение первому декоратору в котором объявлен провайдер. Следовательно, если мы используем провайдер в двух декораторах, он подействует на первый, но не подействует на второй

```tsx
[
(Story, context) => {
	return (
		<ThemeContext.Provider 
			value={ThemeFactory.create(
		          {
		            inputBorderRadiusSmall: '20px', // Применится
		          },
		          theme,
		        )}
		>
        		<Story />
      		</ThemeContext.Provider>
	)
},
(Story, context) => {
	return (
		<ThemeContext.Provider 
			value={ThemeFactory.create(
		          {
		            inputBorderRadiusSmall: '10px', // Не применится, скругления останутся 20px
		          },
		          theme,
		        )}
		>
        		<Story />
      		</ThemeContext.Provider>
	)
},
]
```

2023-02-10 01:06 UTC, zhzz approved these changes

2023-02-10 11:02 UTC, merged

2023-02-10 11:06 UTC, zhzz commented on packages/react-ui/.storybook/preview.tsx
> +    const theme = themes[context.globals.theme] || DEFAULT_THEME;
Обсудили в личке, пришли к тому, что проблема [тут](https://github.com/skbkontur/retail-ui/pull/3100#issuecomment-1422465384).