fix(Modal): configure z-index to work with other components
skbkontur/retail-ui pull request #3104
Opened 2023-02-09 12:53 UTC by JackUait

## Проблема

## Решение

Решение из ветки `modal-zindex-fix`

## Ссылки

closes #2067, IF-644

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-13 12:22 UTC, zhzz requested changes
Я выпустил тестовую версию `0.0.0-f39463294d` из этого ПРа и заиспользовал в оригинальной [песочнице](https://codesandbox.io/s/jolly-spence-g8mypk). Можно наблюдать, что проблема осталась:

<img width="400" src="https://user-images.githubusercontent.com/4607770/224692818-7e4223be-e37c-4dda-89d7-d7749f912976.png" >

2023-03-13 12:22 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndexStorage.ts
> +  ModalStickyHeader: 11,
`Sticky`, используемый внутри `ModalHeader` и `ModalFooter`,  и так имеет повышенный приоритет, который уже решает нашу задачу. Зачем эти дополнительные приоритеты?

2023-03-13 12:22 UTC, zhzz commented on packages/react-ui/components/Modal/ModalHeader.tsx
> +      <ZIndex priority={sticky ? 'ModalStickyHeader' : undefined} className={styles.headerWrapper()}>
Когда проп `sticky` равен `true`, это означает только то, что компоненту разрешено залипать, когда он достигает края окна.

А `ModalHeader` и `ModalFooter` же, согласно задаче, должны перекрывать контент, когда они уже реально залипли.

2023-04-05 08:01 UTC, JackUait commented on packages/react-ui/internal/ZIndex/__stories__/ZIndex.stories.tsx
> +      <Modal.Header sticky={isSticky} style={{ background: 'green' }}>
Восстановил нормальный порядок

2023-04-05 08:07 UTC, JackUait commented on packages/react-ui/internal/ZIndex/ZIndexStorage.ts
> +  ModalStickyHeader: 11,
Если не задавать эти приоритеты, то контент может перекрывать футер/хедер в залипшем состоянии:

https://user-images.githubusercontent.com/48599460/230020062-6bc9e2a2-aab7-4660-be53-4e4fcc79d97e.mov


<hr />

Правда, нейминг действительно получился не лучшим. Поменял на `ModalFixedHeader`/`ModalFixedFooter`

2023-04-05 14:02 UTC, JackUait commented
Я попытался написать скриншотные тесты на кейсы, в которых выпадашка может перекрывать/не перекрывать футер/хедер, но по итогу столкнулся с тем, что мне кажется багом. В тестах я пытаюсь проскроллить экран до нужной мне точки и затем открыть выпадашку, но в тестах выполняется только одно действие из двух:
- Если в модалке нет скролла - открывается выпадашка, но из-за отсутствия скролла отсутствуют и залипающие элементы
- Если в модалке есть скролл - страница скроллится, но выпадашка (на скриншотах) не открывается

<hr />

Я оставил стори с тестами, предлагаю обсудить их в созвоне, если есть понимание/идеи как это можно исправить, либо уменьшить кол-во тестируемых кейсов, исключив те, которые тестированию не поддаются

2023-04-06 13:15 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndexStorage.ts
> +  ModalStickyHeader: 11,
По логике работы нашего механизма z-index'ов `Sticky` (приоритет 7) сам по себе должен перекрывать `DropdownContainer` (приоритет 5). Но этого не происходит, потому что корневой `ZIndex` в `ModalHeader` и `ModalFooter` создает свой [контекст наложения](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).  Он вроде больше не нужен. Если от него избавиться, то дополнительные приоритеты не понадобятся.

2023-04-06 13:27 UTC, zhzz commented
> * Если в модалке нет скролла - открывается выпадашка, но из-за отсутствия скролла отсутствуют и залипающие элементы
> * Если в модалке есть скролл - страница скроллится, но выпадашка (на скриншотах) не открывается

Судя по всему происходит следующее. Когда есть скролл, Dropdown находится за пределами экрана. При клике на него, селениум сначала сам скролит страницу так, чтобы нижние границы Dropdown и вьюпорта совпали. Но в этом положении Dropdown перекрывается футером. Далее происходит клик по координатам центра Dropdown, но он попадает на футер. В результате выпадашка не открывается.

Это поведение описано [здесь](https://www.selenium.dev/documentation/webdriver/elements/interactions/#additional-validations). Но судя по этому документу, оно не должно распространяться на `Actions API`, которое мы используем. Тем не менее, других объяснений я не нашел.

Нужно переделать тест так, чтобы кликались видимые элементы.

2023-04-13 01:49 UTC, JackUait commented on packages/react-ui/internal/ZIndex/ZIndexStorage.ts
> +  ModalStickyHeader: 11,
Избавился от `ZIndex`

2023-04-13 01:49 UTC, JackUait commented
> Нужно переделать тест так, чтобы кликались видимые элементы.

У нас есть 4 кейса, которые нужно протестировать:
- Если футер или хедер находятся в залипшем состоянии - выпадашка должна скрываться под ними;
- Если футер или хедер статические - выпадашка должна перекрывать их.

Сейчас получается протестировать только 2 кейса со статическими элементами, оставшиеся 2 кейса с залипшими элементами мешают протестировать:
- Багованное поведение `Selenium`'а;
- Футер и хедер нельзя сделать залипшими принудительно;
- Стили в футер и хедер прокидываются не на сам элемент, а на `<Sticky />` оборачивающий их. Это не позволяет увеличить высоту залипающей области до нужных размеров;
- У `Dropdown` есть максимальная высота - `300px` и это нельзя изменить через прокидывание стилей/переменных. Это мешает сделать `Dropdown` достаточно высоким, чтобы он менял своё направление из-за достижения границ экрана.

Вероятно, есть другие способы, протестировать это поведение,  которые я не учитываю, но для того, чтобы реализовать тесты c помощью описанных способов придётся расширять `API` публичных компонентов.

2023-04-14 08:26 UTC, zhzz requested changes
1. Какое багованное поведение `Selenium`? То, что я описывал про клики по невидимым на экране элементам, это фичи, эмуляция реальных возможностей пользователя. Пользователь не может кликнуть на то, что не видит.
2. Зачем прокидывать стили в футер/хедер/боди? Это ломает их верстку и поведение модалки.
3. Направлением `Dropdown` можно управлять через существующее api. Что мешает реализовать [такой тест](https://user-images.githubusercontent.com/4607770/231986725-9690199f-1a87-4f75-ab7b-a878e470620b.webm)?

2023-04-26 12:19 UTC, JackUait commented
Переаппрувил два скриншота, на которых `Creevey` находит `diff`, но происходит это _**только**_ в `Chrome` и визуально никак отличий на этих скриншотах нет

`chrome`
<table>
<tr>
 <td> actual
 <td> expect
 <td> diff
<tr>
 <td>

![open modal-actual-1](https://user-images.githubusercontent.com/48599460/234571477-6468103c-0c1f-4b44-b1a1-ac302256989a.png)

 <td>

![open modal-expect-1](https://user-images.githubusercontent.com/48599460/234571470-dad9ef35-4089-4d32-928c-328ca9ad2326.png)

<td>

![open modal-diff-1](https://user-images.githubusercontent.com/48599460/234571766-443aeb49-8706-4945-beaa-51ddf9b0ff09.png)

</table>

`chrome8px`
<table>
<tr>
 <td> actual
 <td> expect
 <td> diff
<tr>
 <td>

![open modal-actual-1 (1)](https://user-images.githubusercontent.com/48599460/234572336-f178695c-ab6e-4cb4-9a65-32989f329163.png)


 <td>

![open modal-expect-1 (1)](https://user-images.githubusercontent.com/48599460/234572311-89c3a4fb-452d-4085-8a19-6f45648af272.png)

 <td>

![open modal-diff-1 (1)](https://user-images.githubusercontent.com/48599460/234572356-228edb45-57fa-4698-baaa-ee8ef964d485.png)

</table>

2023-04-28 10:48 UTC, zhzz approved these changes

2023-04-28 11:03 UTC, merged