Refactor textarea unit tests
skbkontur/retail-ui pull request #3117
Opened 2023-03-03 07:43 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-10 10:27 UTC, zhzz requested changes

2023-03-10 10:27 UTC, zhzz commented on packages/react-ui/components/Textarea/__tests__/Textarea-test.tsx
> +    userEvent.click(svgEl);
Лучше добавить новый data-tid на иконку, типа `TextareaCounter__helpIcon` и искать по нему.

2023-03-10 10:31 UTC, taranovakn commented on packages/react-ui/components/Textarea/__tests__/Textarea-test.tsx
> +    userEvent.click(svgEl);
Имеешь в виду в сам компонент textarea?

2023-03-10 10:40 UTC, zhzz commented on packages/react-ui/components/Textarea/__tests__/Textarea-test.tsx
> +    userEvent.click(svgEl);
Да

2023-03-13 17:13 UTC, taranovakn commented on packages/react-ui/components/Textarea/__tests__/Textarea-test.tsx
> +    userEvent.click(svgEl);
Добавила

2023-03-14 10:13 UTC, zhzz requested changes

2023-03-14 10:13 UTC, zhzz commented on packages/react-ui/components/Textarea/TextareaCounter.tsx
> +
Лучше добавить его в `TextareaDataTids`, который в `Textarea.tsx`. По аналогии с `TextareaCounter__root`.  Чтобы его можно было импортировать из корня пакета.

2023-03-14 11:32 UTC, taranovakn commented on packages/react-ui/components/Textarea/TextareaCounter.tsx
> +
Поменяла

2023-03-14 11:44 UTC, zhzz approved these changes

2023-03-14 12:25 UTC, merged