Добавление пропсов renderItem и onMonthChange. branch/KS-4180
skbkontur/retail-ui pull request #3118
Opened 2023-03-09 09:36 UTC by tvorojjog

## Проблема
В рамках проекта Контур.Продажи (как и в других проектах) появилась потребность в разрезе месяца\даты показывать дополнительную информацию вместе с датой в календаре.
На примере проекта Контур.Продажи: пользователю нужно показывать кол-во запланированных звонков в разрезе даты. Более подробно [проблема описана здесь](https://yt.skbkontur.ru/issue/KS-3821/Kalendar-5.-Pri-planirovanii-sobytiya-otobrazhat-Ispolnitelyu-informaciyu-o-kolichestve-sobytij-na-datu-v-kartochke-sdelki).

## Решение
Было принято решение использовать `DatePicker ` для решения задачи и внести некоторые доработки в компоненты.

Что сделано:
1. Добавлен пропс `renderItem`, который рендерит кастомный элемент даты месяца. Если такой пропс не передан, то рендерится число месяца.
2. Добавлен пропс `onMonthChange`, который возвращает первый отображаемый месяц, год и направление скролла при изменении месяца при скролле или через селект, а также при изменении года.
3. Выполнен небольшой рефакторинг некоторых методов для унификации их работы, а также стилей для расширения возможности задать собственные стили ячейкам дат через контекст.
4. Добавлено описание работы пропса `renderItem` и тесты.

Трудности:
Не получилось локально запустить скриншотные тесты, также есть проблемы при прогоне селениум тестов в TC и там же скриншотных тестов для IE. С Егором Погадаевым договорились, что пока запустим процесс ревью без учета этих моментов.

## Ссылки
close [IF-818](https://yt.skbkontur.ru/issue/IF-818)
close [IF-949](https://yt.skbkontur.ru/issue/IF-949)

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

6. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ✅ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ✅ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

7. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

8. Прочее
  ⬜ все тесты и линтеры на CI проходят (проходят не все тесты, обсудили лично с Егором Погадаевым)
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-10 09:27 UTC, zhzz requested changes

2023-03-10 09:27 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      }
Заметил пару особенностей у такого способа вызова `onMonthChange`:
1. При скроле на длинный промежуток времени, скажем, сразу на 5 месяцев, `onMonthChange` будет вызван для каждого из них.
2. Нет возможности узнать какой месяц виден при открытии календаря.

Не знаю насколько это критично. Вам должно быть виднее. Подумалось, возможно что-то вроде `onMonthShow` было бы еще полезнее.

2023-03-10 09:27 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellLineHeight = `${parseInt(DefaultTheme.calendarCellHeight) - 2}px`;
Для корректной работы вычисляемых переменных их нужно делать геттерами. Примеры есть ниже в этом файле.

2023-03-10 09:27 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellWidth = '30px';
```suggestion
  public static calendarCellSize = '30px'; // deprecated
  public static get calendarCellHeight() {
    return this.calendarCellSize;
  }
  public static get calendarCellWidth() {
    return this.calendarCellSize;
  }
```

Поскольку список переменных темы является частью публичного апи, мы не можем их удалять в немажорном релизе без обратной совместимости. 

Можно пока вернуть старую переменную, пометить ее `deprecated`, а новые временно сделать на основе старой. В мажорном релизе отрефакторим.

2023-03-10 10:36 UTC, zhzz commented
Выкатил тестовую версию: `@skbkontur/react-ui@0.0.0-3974a633b4`.

2023-03-15 07:54 UTC, tvorojjog commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +  renderItem: (date: CalendarDateShape) => React.ReactNode;
Хорошо, поправил.

2023-03-15 07:57 UTC, tvorojjog commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +  renderItem?: (date: CalendarDateShape) => React.ReactNode | number;
Согласен, поправил.

2023-03-15 08:06 UTC, tvorojjog commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      }
1. Мне показалось это оправданным поведением, ведь метод предполагает, что будет возвращать первый отображаемый месяц при изменении такого месяца. Для нашего сценария это не нужно, нам нужно понимать именно когда месяц зафиксировался. Но, возможно, наш сценарий изменится или какому-то проекту в Контуре важно будет отслеживать каждое изменение.
2. Все так, ведь метод должен возвращать новый месяц при изменении месяца, а при открытии он не меняется.

По поводу названия: я бы все-таки оставил `onMonthChange`, так как название говорит, что метод будет вызываться именно при изменении месяца. Что думаешь?

2023-03-15 08:12 UTC, tvorojjog commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +
Понял, поправил.

2023-03-15 08:34 UTC, tvorojjog commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellLineHeight = `${parseInt(DefaultTheme.calendarCellHeight) - 2}px`;
Хорошо, поправил.

2023-03-15 08:40 UTC, tvorojjog commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellWidth = '30px';
Понял проблему, не подумал об этом. Поправил.

2023-03-17 10:17 UTC, zhzz requested changes

2023-03-17 10:17 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      scrollDirection: this.state.scrollDirection,
Нашел еще такую проблему с `this.state.scrollDirection` - в стейте лежит правильное значение, только когда месяц меняется скролом. Еще месяц может меняться при редактировании текста в инпуте, или выбором значений в выпадашках месяца и года. Тогда `onMonthChange` тоже отрабатывает, но значение `changeInfo.scrollDirection` в нем неправильное - в стейте оно не обновлялось.

Также появилось чувство, что `scrollDirection` не лучшее имя для поля, потому что изменение месяца к скроллу не обязательно привязано. Возможно, `changeDirection` было бы лучше.

И тип поля я бы тоже уточнил:
```ts
export enum CalendarMonthChangeDirection {
  Inc = 1,
  Dec = -1,
}
```

А может быть это поле вовсе не нужно?

2023-03-17 10:18 UTC, zhzz commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      }
Лучше варианта не придумал. Готов согласится с текущим.

2023-03-20 12:38 UTC, tvorojjog commented on packages/react-ui/internal/Calendar/Calendar.tsx
> +      scrollDirection: this.state.scrollDirection,
Согласен, оно выглядит лишним теперь. Убрал.

2023-03-24 08:55 UTC, zhzz approved these changes
Выкатил тестовую версию `@skbkontur/react-ui@0.0.0-85ea551f96`

2023-04-28 12:33 UTC, merged