Refator tooltip tests
skbkontur/retail-ui pull request #3119
Opened 2023-03-10 09:26 UTC by taranovakn

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-16 10:45 UTC, zhzz requested changes

2023-03-16 10:45 UTC, zhzz commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +  // });
Здесь загвоздка в том, что после размонтирования в RTL, в отличии от enzyme, у нас не остается инстанса компонента, чтобы проверить на нем свойство. Можно переписать тест с сохранением смысла:
```js
it('clears hoverTimeout timer after unmount', () => {
    jest.useFakeTimers();
    jest.spyOn(window, 'setTimeout');
    jest.spyOn(window, 'clearTimeout');

    const tooltipRef = React.createRef<Tooltip>();

    const { unmount } = render(
      <Tooltip disableAnimations render={() => <div />} ref={tooltipRef}>
        <Button>Anchor</Button>
      </Tooltip>,
    );

    // @ts-expect-error: Use of private property.
    expect(tooltipRef.current.hoverTimeout).toBeNull();

    userEvent.hover(screen.getByRole('button'));

    // @ts-expect-error: Use of private property.
    const { hoverTimeout } = tooltipRef.current;

    expect(hoverTimeout).not.toBeNull();

    unmount();

    expect(clearTimeout).toHaveBeenCalledWith(hoverTimeout);
  });
```

2023-03-16 10:45 UTC, zhzz commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +    //expect(refFn2.mock.calls[0][0]).toBe(wrapper.find('div').instance());
Вероятно дело в том, что `rerender` из RTL и `update` из enzyme работают по-разному. Как будто `rerender` вызывает перемонтирование. Думаю, можно убрать этот дополнительный `rerender(<Comp refFn={refFn1} />)` с комментарием, тогда заработает.

2023-03-20 09:47 UTC, taranovakn commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +    //expect(refFn2.mock.calls[0][0]).toBe(wrapper.find('div').instance());
Удалила дополнительный rerender, заработало
Спасибо

2023-03-20 09:47 UTC, taranovakn commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +  // });
Спасибо, поправила

2023-03-21 11:48 UTC, zhzz requested changes

2023-03-21 11:48 UTC, zhzz commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +      expect(screen.queryByTestId(TooltipDataTids.content)).not.toBeInTheDocument();
Почему только в этом тесте из всей группы `calls onOpen` добавилась проверка на реальное открытие тултипа?

2023-03-21 11:48 UTC, zhzz commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +      // eslint-disable-next-line testing-library/prefer-presence-queries
Очень много отключено предупреждений `eslint`. Это повод присмотреться, ведь он ругается не просто так. Можно гуглить имя правила, чтобы понять, что оно требует. 

Например, [testing-library/prefer-presence-queries](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-presence-queries.md), говорит о том, что проверки `toBeInTheDocument()` и `not.toBeInTheDocument()` лучше использовать соответственно с запросами `getBy...` и `queryBy...` - так ошибки в консоли при поломке теста будут понятнее.

2023-03-21 11:48 UTC, zhzz commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +    //let wrapper: ReactWrapper<TooltipProps, TooltipState, Tooltip>;
```suggestion
```

2023-03-22 08:19 UTC, taranovakn commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +      // eslint-disable-next-line testing-library/prefer-presence-queries
Убрала все комментарии, поменяла везде где нужно на getBy и queryBy

2023-03-22 08:19 UTC, taranovakn commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +    //let wrapper: ReactWrapper<TooltipProps, TooltipState, Tooltip>;
Удалила

2023-03-22 13:50 UTC, taranovakn commented on packages/react-ui/components/Tooltip/__tests__/Tooltip-test.tsx
> +      expect(screen.queryByTestId(TooltipDataTids.content)).not.toBeInTheDocument();
Добавила во второй тест в этом дереве тестов проверку

2023-03-23 06:29 UTC, zhzz approved these changes

2023-03-23 06:29 UTC, merged