Hide body vertical scroll ios
skbkontur/retail-ui pull request #3121
Opened 2023-03-14 06:47 UTC by HelenaIsh

## Проблема

При закрытии `SidePage` на мобильных устройствах в `iOS` остаются стили, блокирующие скролл страницы.
Причина: в `HideBodyVerticalScroll` не удаляется `listener` на `resize`, если их 2 (только в iOS).

## Решение

Добавлять listener только один раз

## Ссылки

fix IF-1092

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-14 16:39 UTC, lossir requested changes

2023-03-14 16:39 UTC, lossir commented on packages/react-ui/internal/HideBodyVerticalScroll/HideBodyVerticalScroll.tsx
> +      window.addEventListener('resize', this.updateScrollVisibility, { once: true });
Дело немного в другом.
На самом деле в компоненте есть попытка реализовать какбы синглтон.
В специальной переменной `window.RetailUIVerticalScrollCounter` считается кол-во смонтированных компонентов.
И обработчик для `resize` навешивается только на первом смонтированном, а снимается на последнем.

| Монтаж/демонтаж компонентов `<HideBodyVerticalScroll>`<br/> при открытии/закрытии `<SidePage>`|
| --- |
| ![image](https://user-images.githubusercontent.com/2708211/225060836-eca9bc9e-8604-42a2-ac82-cdf3b62ebf02.png) |

И получается, что при монтировании обработчик навешивается из экземпляра `HBVS_blockBackground` т.к. он первый. А при размонтировании "удаляется" обработчик из `HBVS_isMobile` т.к. он последний.
Т.е. по факту обработчик остаётся на месте.

Проблема проявляется в мобилках во всех браузерах, потому-что при скролле окно браузера ресайзится - адресная строка и нижний тулбар уменьшаются или совсем скрываются.

На десктопе это тоже можно воспроизвести вручную изменив размеры мобильного вьюпорта.
Или выполнив такую команду в консоле:
```js
window.dispatchEvent(new Event('resize'))
```

---

Опция `once = true` вроде ничего не ломает, но и не исправляет.
Самое простое решение сейчас, это исключить экземпляр `HBVS_blockBackground` на мобилках:

```diff
-{blockBackground && this.renderShadow()}
+{!isMobile && blockBackground && this.renderShadow()}
```

2023-03-15 06:03 UTC, lossir approved these changes

2023-03-15 07:25 UTC, lossir approved these changes

2023-03-16 07:37 UTC, JackUait reviewed
Текущее решение только маскирует проблему. Думаю, что как временное решение (до того как реализуем нормальный синглтон) стоит полностью выпилить логику "синглтона" из компонента, так как судя по #412 она была добавлена просто как архитектурное решение с целью оптимизации и не стремится покрыть какой-то конкретный кейс

Насчёт кейса, который Максим описал в задаче IF-1094: если я всё правильно понял, то и без "синглтона" скролл будет корректно скрываться и появляться

2023-03-16 08:35 UTC, lossir commented
> Насчёт кейса, который Максим описал в задаче IF-1094: если я всё правильно понял, то и без "синглтона" скролл будет корректно скрываться и появляться
©️ https://github.com/skbkontur/retail-ui/pull/3121#pullrequestreview-1342978608

Нет, такого я не писал) Если выпилить текущий "синглтон", то думаю развалится кейс когда `<Modal>`/`<SidePage>` открываются "друг из друга".
Выпиливать старый и делать нормальный синглтон будем в мажорной версии (пометил в задаче).

Для временного решения достаточно просто следить, чтобы компонент `<HideBodyVerticalScroll>` всегда был смонтированным в единственном числе.
Текущий кейс с мобильным `<SidePage>` кажется довольно редким, поэтому это не должно быть проблемой.

2023-03-22 03:34 UTC, JackUait commented on packages/react-ui/components/SidePage/SidePage.tsx
Возможно, я неправильно понял кейс о котором идёт речь, но без синглтона логика вполне корректно отрабатывает, о чём я писал выше

**На видео:** открывается модалка, из которой открывается SidePage. SidePage и модалка последовательно закрываются, при этом стили на теге `<html />` на протяжении всего видео остаются корректными

https://user-images.githubusercontent.com/48599460/226795319-165e9c70-ae13-4599-a76f-ea96c869dfea.MOV

Также, раз у нас есть такой кейс - нужно покрыть его тестами

2023-03-22 03:34 UTC, JackUait commented
> Насчёт кейса, который Максим описал в задаче IF-1094: если я всё правильно понял, то и без "синглтона" скролл будет корректно скрываться и появляться

> Нет, такого я не писал) Если выпилить текущий "синглтон", то думаю развалится кейс когда <Modal>/<SidePage> открываются "друг из друга".

В своём комментарии я имел ввиду, что кейс описанный тобой будет работать как с синглтоном так и без него. В комментарии выше прикрепил видео с подтверждением своих слов

2023-03-22 07:20 UTC, HelenaIsh commented on packages/react-ui/components/SidePage/SidePage.tsx
Да, мы ввели тебя в заблуждение с примером с `Modal` и `SidePage`. Тем не менее, при удалении логики синглтона из `HideBodyVerticalScroll` ломается криви тест `Multiple_WithScrollableContent`

2023-03-22 10:28 UTC, lossir commented on packages/react-ui/components/SidePage/SidePage.tsx
## "Cинглтон" 
Удалять "синглтон" точно не надо. Тем более, какие именно строчки вы удаляли?
Это будет точно мажорная правка. Не говоря уже о том, что такая правка выходит за рамки исправляемого бага.
Баг "нашёлся" в `<SidePage>` и в нём же удалось исправить проблему.

Переписывать ради этого целый компонент сейчас будет неоправданно долго и дорого.

---

Добавлю ещё, что кол-во экземпляров `<HideBodyVerticalScroll>` храниться в глобале - `window.RetailUIVerticalScrollCounter`.
Значит, модалки и сайдпеджи из других версий контролов тоже смотрят в неё. А одновременно в продукте может быть несколько разных версий контролов. И при удалении/переписывании этой логики надо будет это учесть.

Как то раз мы обновили event-emitter, забыв, что он храниться в глобале. Вот к чему это привело =)
https://github.com/skbkontur/retail-ui/issues/2197#issuecomment-1173912943

## Тесты

> - При монтировании он задаёт свои стили/свой класс;
> - При размонтировании он удаляет свои стили/свой класс.

Что значит "свои стили"? Своего экземпляра? 

Тем не менее, уже есть скриншотные тесты, проверяющие что при монтировании `<HideBodyVerticalScroll>` скрывает скроллбар, а при размонтировании убирает.
Я думаю их достаточно.

2023-03-22 11:10 UTC, JackUait approved these changes

2023-03-22 13:07 UTC, merged