Refactor tests
skbkontur/retail-ui pull request #3127
Opened 2023-03-23 07:39 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-29 06:28 UTC, zhzz requested changes
Крутые новые сценарии!

2023-03-29 06:28 UTC, zhzz commented on packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
> +  });
А как связаны навигация стрелками и добавление нового токена?

2023-03-29 07:47 UTC, taranovakn commented on packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
> +  });
Это старый сценарий, я его не трогала) 
Попробую глянуть что с ним

2023-03-29 08:20 UTC, taranovakn commented on packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
> +  });
Поменяла на проверку наличия токена после перехода в режим его редактирования

2023-03-29 11:02 UTC, zhzz commented on packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
> +  });
А текст в инпуте?

2023-03-30 07:11 UTC, taranovakn commented on packages/react-ui/components/TokenInput/__tests__/TokenInput-test.tsx
> +  });
Добавила проверку на текст в инпуте дополнительно

2023-03-30 10:46 UTC, zhzz approved these changes

2023-03-30 10:46 UTC, merged