feat(Input): support new types (#IF-290)
skbkontur/retail-ui pull request #3129
Opened 2023-03-27 08:01 UTC by strmmm

## Проблема

Клиент хочет, чтобы Input умел принимать больше типов, чем он принимает сейчас.

## Решение

В пропсы компонента добавлена поддержка некоторых типов. Сделаны специальные условия для типа number. 
Обновлён гайдлист, обновлены стори, добавлены тесты.

## Ссылки

IF-290

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-31 07:30 UTC, JackUait requested changes

2023-03-31 07:30 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +      mask && type !== 'number' ? this.renderMaskedInput(inputProps, mask) : React.createElement('input', inputProps);
Мы не должны ограничивать пользователей в сценариях использования пропа `mask`. Наша задача как раз состоит в том, чтобы научить новые типы работать с пропом `mask`

2023-04-10 13:56 UTC, JackUait requested changes

2023-04-10 13:56 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +      const canBeSelected = !this.props.type || (this.props.type && allowedTypes.includes(this.props.type));
Давай добавим сюда ссылку на `MDN` и небольшое пояснение того, зачем это условие нужно

2023-04-10 13:56 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +        /** Выделять введенное значение при фокусе. Работает с типами 'text', 'password', 'tel', 'search', 'url' */
Публичные методы также отображаются в доке и к ним можно добавить описание

2023-04-10 13:56 UTC, JackUait commented on packages/react-ui/.creevey/images/Input/Type Api/firefoxDark.png
Для инпута с типом `search` не тестируются кейсы, когда он зафокушен и в него что-то введено. В таком случае и инпута с этим типом появляется крестик для удаления контента:
<img width="347" alt="Снимок экрана 2023-04-10 в 16 52 33" src="https://user-images.githubusercontent.com/48599460/230914584-4db81445-e4d8-4b45-8b0b-fa462d604bfb.png">

2023-04-10 13:56 UTC, JackUait commented on packages/react-ui/.creevey/images/Input/Functional tests/Submit with pattern/chrome.png
Тесты для `Submit with pattern` удалены, а скриншоты остались. Надо удалить и их тоже

2023-04-19 11:28 UTC, JackUait requested changes

2023-04-19 11:28 UTC, JackUait commented on packages/react-ui/.creevey/images/Input/Functional tests/Search Type Api/Focused/chrome/Focused.png
В тёмной теме изменяется внешний вид крестика, хорошо бы это тоже протестировать

<hr />

Также, при фокусе на инпут с типом `number` отображаются свои элементы управления, их тоже нужно протестировать в обоих темах

<img width="219" alt="Снимок экрана 2023-04-19 в 14 10 04" src="https://user-images.githubusercontent.com/48599460/233057040-5ad95d96-e29a-4b11-9d7e-975b2b22127d.png">

2023-04-19 11:28 UTC, JackUait commented on packages/react-ui/.creevey/images/Input/Functional tests/Search Type Api/Plain/chrome/Plain.png
Мы уже тестируем это состояние в других скриншотных тестах
Здесь можно оставить только скриншоты для `Focused`

2023-04-19 11:28 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +        // [styles.inputColorScheme(this.theme)]: error && (isIE11 || isEdge),
Лишний код

2023-04-25 09:14 UTC, JackUait approved these changes

2023-04-25 12:57 UTC, merged

2023-04-27 08:54 UTC, zhzz reviewed
Следующие скриншоты все еще неправильные, как уже отмечалось [тут](https://github.com/skbkontur/retail-ui/pull/3129#discussion_r1154079510) и [тут](https://github.com/skbkontur/retail-ui/pull/3129#discussion_r1161613639):

1. `Input/Functional tests/Select All By Prop/Focused/firefox/Focused.png`
2. `Input/Functional tests/Select all by button/Selected/firefox/Selected.png`


В задаче также говорилось про вывод предупреждения в консоль, в случаях, когда новые типы конфликтуют с существующим API. Это означает, что если пользователь попытается выделить текст в поле с неподходящим типом, ему лучше дать знать о том, что он делает не так, а не просто проигнорировать.

2023-04-27 08:54 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +   * [Документация](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange)
Документации метода `selectAll` недостаточно, в нем тоже нужно предотвратить ошибку.

![image](https://user-images.githubusercontent.com/4607770/234809737-88909261-a4a5-4604-a437-b3d3acfb26f1.png)

2023-05-17 13:10 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +   * [Документация](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange)
- Добавил проверку
- Накинул тестов на это поведение

2023-05-17 13:10 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +    }
Пользователям как раз может понадобиться фича с `data-tid`'ом, чтобы протестировать их логику, но думаю, что можно будет добавить этот тип по запросу пользователей

Пока удалил тип

2023-05-17 13:10 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +      const canBeSelected = !this.props.type || (this.props.type && allowedTypes.includes(this.props.type));
Задал `text` как значение по умолчанию для `type`