fix(Button): fix button content position (#IF-867)
skbkontur/retail-ui pull request #3132
Opened 2023-03-29 14:01 UTC by strmmm

## Проблема

Разное расстояние от верхнего и нижнего края кнопки (link) до внутреннего контента

## Решение

Убрана часть стиля, вызывающая ассиметрию

## Ссылки

IF-867

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-04-03 07:59 UTC, JackUait requested changes

2023-04-03 07:59 UTC, JackUait commented on packages/react-ui/components/Button/Button.styles.ts
> -      bottom: -2px;
До появления бага у кнопки был размер `20.5px`, после появления бага кнопка уменьшилась до `18.5px`, убирая этот стиль мы уменьшаем кнопку до `16.5px`

Чтобы исправить баг и сохранить размер кнопки нам нужно увеличить высоту кнопки сверху

2023-04-28 09:08 UTC, JackUait approved these changes

2023-05-03 10:57 UTC, zhzz approved these changes

2023-05-03 10:58 UTC, merged