test(hint): remove using enzyme
skbkontur/retail-ui pull request #3134
Opened 2023-03-30 11:02 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-03-31 06:20 UTC, zhzz requested changes

2023-03-31 06:20 UTC, zhzz commented on packages/react-ui/components/Hint/__tests__/Hint-test.tsx
> +    userEvent.type(screen.getByText(hintChildrenText), '{mouseenter}');
Это же событие ввода текста для заполнения инпутов. А по идее нужно наведение мыши.

2023-04-03 14:34 UTC, taranovakn commented on packages/react-ui/components/Hint/__tests__/Hint-test.tsx
> +    userEvent.type(screen.getByText(hintChildrenText), '{mouseenter}');
Поменяла на hover, в следующем тесте тоже сделала unhover

2023-04-04 10:28 UTC, zhzz commented on packages/react-ui/components/Hint/__tests__/Hint-test.tsx
> +    userEvent.type(screen.getByText(hintChildrenText), '{mouseenter}');
В другом тесте еще осталось

2023-04-05 07:36 UTC, taranovakn commented on packages/react-ui/components/Hint/__tests__/Hint-test.tsx
> +    userEvent.type(screen.getByText(hintChildrenText), '{mouseenter}');
Поменяла, спасибо)

2023-04-05 07:46 UTC, zhzz approved these changes

2023-04-06 13:27 UTC, zhzz approved these changes

2023-04-06 13:28 UTC, merged