test(Tabs): remove using enzyme
skbkontur/retail-ui pull request #3148
Opened 2023-04-24 11:42 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-04 06:06 UTC, zhzz requested changes

2023-05-04 17:35 UTC, taranovakn commented on packages/react-ui/components/Tabs/__tests__/Tabs-test.tsx
> +  });
Удалила тест, проверю этот сценарий в скриншотных тестах

2023-05-04 17:38 UTC, taranovakn commented on packages/react-ui/components/Tabs/__tests__/Tabs-test.tsx
> +      <div>
Убрала, спасибо)

2023-05-05 05:53 UTC, zhzz approved these changes

2023-05-05 07:02 UTC, merged