test(Toast): remove using enzyme
skbkontur/retail-ui pull request #3154
Opened 2023-05-05 07:00 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-11 07:02 UTC, zhzz requested changes

2023-05-11 07:02 UTC, zhzz commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
> +    const toast = toastRef.current?._toast;
Тут тоже внутренне свойство, а потом проникновение еще глубже в `toast?.props.action`. А по идее, нужно проверить текст в `ToastDataTids.action`, кликнуть на него и убедиться что `handler` вызвался.

2023-05-12 07:37 UTC, taranovakn commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
>      expect(toast).toBeFalsy();
Поменяла на expect(screen.queryByTestId(ToastDataTids.toastView)).not.toBeInTheDocument();

2023-05-12 07:37 UTC, taranovakn commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
> +    expect(toastRef.current?._toast).toBeTruthy();
Убрала

2023-05-12 07:43 UTC, taranovakn commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
> +    expect(screen.getByTestId(ToastDataTids.toastView)).toHaveTextContent('messageaction');
Добавила проверки 
expect(screen.getByTestId(ToastDataTids.action)).toBeInTheDocument();
expect(screen.getByTestId(ToastDataTids.action)).toHaveTextContent(actionLabel);

2023-05-12 07:45 UTC, taranovakn commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
> +    const toast = toastRef.current?._toast;
Поменяла на клик по элементу и проверку вызова хендлера
userEvent.click(screen.getByTestId(ToastDataTids.action));
expect(handler).toHaveBeenCalled();

2023-05-12 07:47 UTC, taranovakn commented on packages/react-ui/components/Toast/__tests__/Toast-test.tsx
> +    expect(toastRef.current?.state.notification).toBe('message');
Да, согласна, убрала этот тест

2023-05-12 11:32 UTC, zhzz approved these changes

2023-05-12 11:32 UTC, merged