Добавил возможность выключать автоматическое добавление отступа пунктом меню
skbkontur/retail-ui pull request #3155
Opened 2023-05-05 09:11 UTC by slogger

## Проблема

Сейчас различные меню автоматически добавляют отступ всем пунктам меню, если хотя бы у одного есть иконка, это не всегда нужно 
## Решение

Добавил возможность выключать это поведение у всего меню

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности — добавил новый кейс в Storybook
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-12 11:40 UTC, JackUait requested changes

2023-05-12 11:40 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +      React.Children.toArray(this.props.children).some((x) => React.isValidElement(x) && x.props.icon);
В будущем мы планируем смёржить `InternalMenu` и `Menu` в один компонент, так как они шарят много логики. Давай пока вынесем логику для `enableIconPadding` в чистую функцию и переиспользуем её в `InternalMenu` и `Menu`

2023-05-12 11:40 UTC, JackUait commented on packages/react-ui/internal/PopupMenu/PopupMenu.tsx
> +  preventIconPadding?: boolean;
`PopupMenu` основывается на `InternalMenu`
Давай наследовать тип `preventIconPadding` из `InternalMenu`

2023-05-12 11:40 UTC, JackUait commented on packages/react-ui/internal/Menu/Menu.tsx
> +  preventIconPadding?: boolean;
Здесь тоже можно наследовать тип от `InternalMenu`, хоть тут и нет такой связи как у `PopupMenu` с `InternalMenu`. Так мы получим единый источник правды в виде `InternalMenu`

2023-05-12 11:40 UTC, JackUait commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +  preventIconPadding?: boolean;
Предлагаю немного изменить нейминг здесь. Как показывает практика, пропы которые включают что-то проще для восприятия, чем пропы которые что-то выключают

```suggestion
  /**
   * Выравнивает текст всех пунктов меню относительно друг друга
   * Так, если хотя бы у одного пункта меню есть иконка, текст в  остальных пунктах меню будет выровнен относительно пункта меню с иконкой
   *
   * @default true
   */
  enableTextAlignment?: boolean;
```

2023-05-18 11:01 UTC, slogger commented on packages/react-ui/components/DropdownMenu/DropdownMenu.tsx
> +export interface DropdownMenuProps
Добавил в каждый минимум две истории с иконками и выравниванием по умолчанию и с выключенным выравниванием

2023-05-18 11:02 UTC, slogger commented on packages/react-ui/internal/InternalMenu/InternalMenu.tsx
> +      React.Children.toArray(this.props.children).some((x) => React.isValidElement(x) && x.props.icon);
👌

2023-05-18 11:02 UTC, slogger commented on packages/react-ui/internal/PopupMenu/PopupMenu.tsx
> +  preventIconPadding?: boolean;
👌

2023-05-18 11:02 UTC, slogger commented on packages/react-ui/internal/Menu/Menu.tsx
> +  preventIconPadding?: boolean;
👌

2023-05-31 06:55 UTC, slogger commented
Перенёс изменения из форма в этот репозиторий, #3172

2023-05-31 06:55 UTC, closed without merging