Refactor tests
skbkontur/retail-ui pull request #3156
Opened 2023-05-10 12:13 UTC by taranovakn

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-11 08:43 UTC, zhzz requested changes

2023-05-11 08:43 UTC, zhzz commented on packages/react-ui/components/Spinner/__tests__/Spinner-test.tsx
> +// import { mount, ReactWrapper } from 'enzyme';
```suggestion
```

2023-05-11 08:43 UTC, zhzz commented on packages/react-ui/components/Spinner/__tests__/Spinner-test.tsx
>      it('renders correct size of default Spinner', () => {
Тесты на размер "renders correct size of default Spinner" и "should render big Spinner" не очень полезны. Лучше им стать скриншотами.

2023-05-12 07:52 UTC, taranovakn commented on packages/react-ui/components/Spinner/__tests__/Spinner-test.tsx
>      it('renders correct size of default Spinner', () => {
Я сомневалась по поводу необходимости тестов, удалю, спасибо!)

2023-05-12 10:25 UTC, zhzz approved these changes

2023-05-12 10:25 UTC, merged