test(CurrencyLabel): remove using enzyme
skbkontur/retail-ui pull request #3158
Opened 2023-05-16 12:35 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-17 10:27 UTC, zhzz requested changes

2023-05-17 10:27 UTC, zhzz commented on packages/react-ui/components/CurrencyLabel/__tests__/CurrencyLabel-test.tsx
> +    }).toThrow();
Это не проверка на то, что сработала выброшена указанная ошибка. По факту здесь проверяется то, что элемент с переданным текстом на экране не найден. Но такой элемент действительно не рендерится, поэтому проверка проходит. Подробнее про работу [getBy](https://testing-library.com/docs/queries/about/#types-of-queries).

Ошибки, которые используются в CurrencyLabel, не рендерятся в браузере, а пишутся в консоль. Их можно протестировать [так](https://stackoverflow.com/a/46154319).

2023-05-18 13:02 UTC, taranovakn commented on packages/react-ui/components/CurrencyLabel/__tests__/CurrencyLabel-test.tsx
> +    }).toThrow();
Переписала

2023-05-24 19:50 UTC, zhzz requested changes
Линт не проходит

2023-05-29 06:18 UTC, zhzz approved these changes

2023-05-29 06:19 UTC, merged