chore(Input): support new types (postmortem fixes)
skbkontur/retail-ui pull request #3161
Opened 2023-05-17 13:14 UTC by JackUait

## Проблема

После слития #3129 обнаружилось несколько моментов, которые нужно было исправить

## Решение

1. [Неправильные скриншоты](https://github.com/skbkontur/retail-ui/pull/3129#pullrequestreview-1403362214) - переаппрувил скриншот `Input/Functional tests/Select all by button/Selected/firefox/Selected.png`. Второй скриншот по какой-то причине уже был корректным;
2. [Лишние проверки `this.props.type`](https://github.com/skbkontur/retail-ui/pull/3129#discussion_r1178731651) - задал `text` как значение по умолчанию для пропа `type`;
3. [На `type="hidden"` не прокидывается `data-tid`](https://github.com/skbkontur/retail-ui/pull/3129#discussion_r1178766101) - избавился от типа `hidden`;
4. [Нужна проверка на тип для `selectAll`](https://github.com/skbkontur/retail-ui/pull/3129#discussion_r1178823529) - добавил проверку.

## Ссылки

IF-1175

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

5. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ✅ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

6. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

7. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-05-18 04:26 UTC, zhzz requested changes
В [задаче ](https://yt.skbkontur.ru/issue/IF-290)и [ревью ](https://github.com/skbkontur/retail-ui/pull/3129#pullrequestreview-1403362214)говорилось еще про вывод предупреждения в консоль. Можно использовать для этого пакет [warning](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui-validations/src/ValidationWrapperInternal.tsx#L69).

2023-05-18 04:26 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  private canBeSelected = ['text', 'password', 'tel', 'search', 'url'].includes(this.getProps().type);
Значение в этом поле останется неизменным на протяжении всей жизни компонента, а `type` может поменяться. Соответственно, возможен рассинхрон. Нужно сделать геттером.

2023-05-18 04:28 UTC, zhzz commented
lint и скриншоты не проходят.

2023-05-19 04:02 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +  private canBeSelected = ['text', 'password', 'tel', 'search', 'url'].includes(this.getProps().type);
Поправил и добавил тест

2023-05-19 04:04 UTC, JackUait commented
> В [задаче ](https://yt.skbkontur.ru/issue/IF-290)и https://github.com/skbkontur/retail-ui/pull/3129#pullrequestreview-1403362214говорилось еще про вывод предупреждения в консоль. Можно использовать для этого пакет [warning](https://github.com/skbkontur/retail-ui/blob/master/packages/react-ui-validations/src/ValidationWrapperInternal.tsx?rgh-link-date=2023-05-18T04%3A26%3A58Z#L69).

Добавил ошибки для пропов `mask`, `selectAllOnFocus` и для метода `selectAll`, а также покрыл кейсы в которых могут быть вызваны эти ошибки тестами

2023-05-19 04:52 UTC, JackUait commented
Некоторые скриншоты мигают - перезапустил их

2023-05-22 13:03 UTC, zhzz requested changes
Нашел еще один публичный метод выделения: `setSelectionRange`. По идее тоже нужно обработать. 

А может вообще спустить проверки перед любым другим выделением в него и делать их одинаково только в одном месте? Заметно уменьшит код.

2023-05-22 13:03 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  }, '');
Того же можно достичь проще: `[].join(', ')`

2023-05-24 10:19 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +    if (this.props.type !== prevProps.type) {
Расширил проверку и добавил тест

2023-05-24 10:19 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +  }, '');
В таком случае ошибка получится несколько менее читаемой, из-за отсутствия кавычек + появится рассинхрон с первой частью сообщения, где также используются кавычки
<img width="942" alt="Снимок экрана 2023-05-24 в 11 34 54" src="https://github.com/skbkontur/retail-ui/assets/48599460/dd010b05-4277-4d94-a339-5d77f91b6362">

2023-05-24 10:19 UTC, JackUait commented
> Нашел еще один публичный метод выделения: setSelectionRange. По идее тоже нужно обработать.

Добавил обработку ошибок метода и написал тесты

> А может вообще спустить проверки перед любым другим выделением в него и делать их одинаково только в одном месте? Заметно уменьшит код.

Проверки нужны для того, чтобы выводить только одну ошибку в момент времени. Если мы их спустим ниже, то за раз будет выводиться сразу несколько ошибок. Или ты имеешь ввиду какие-то другие проверки?

2023-05-24 10:38 UTC, zhzz commented on packages/react-ui/components/Input/Input.tsx
> +  }, '');
```js 
[].map(i => `"${i}"`).join(', ')
```

2023-05-24 10:50 UTC, zhzz commented
> Проверки нужны для того, чтобы выводить только одну ошибку в момент времени. Если мы их спустим ниже, то за раз будет выводиться сразу несколько ошибок. Или ты имеешь ввиду какие-то другие проверки?

Я имею в виду то, что и `selectAll` и `selectAllOnFocus` внутри используют `setSelectionRange`. И нет нужды делать отдельные проверки для каждого их этих способов выделить текст. Можно сделать одну общую внутри `setSelectionRange`, которая будет выводить предупреждение непосредственно в момент попытки выделения. 

Да, тогда у нас не будет детального сообщения с указанием того, какой именно способ выделения был использован. Но это не так критично. Зато не будет много кода, чтобы поддерживать такой простой сценарий.

2023-05-24 13:14 UTC, JackUait commented on packages/react-ui/components/Input/Input.tsx
> +  }, '');
Отрефакторил

2023-05-24 13:14 UTC, JackUait commented
> Да, тогда у нас не будет детального сообщения с указанием того, какой именно способ выделения был использован. Но это не так критично. Зато не будет много кода, чтобы поддерживать такой простой сценарий.

Упростил сообщение об ошибке и избавился от лишнего кода

2023-05-24 18:31 UTC, zhzz approved these changes

2023-05-29 08:10 UTC, merged