Refactor tests
skbkontur/retail-ui pull request #3171
Opened 2023-05-30 15:45 UTC by taranovakn

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-06 11:50 UTC, JackUait requested changes

2023-06-06 11:50 UTC, JackUait commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +  it('should handel keydown event', () => {
```suggestion
  it('should handle keydown event', () => {
```

Хандель встречается ещё в двух тестах ниже :D

2023-06-06 11:50 UTC, JackUait commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +    fireEvent.blur(input);
Кажется, что правильнее проверять такую логику через `userEvent.tab()`

Плюс здесь стоит добавить проверку на то, что после блюра на `root` нет фокуса

2023-06-06 11:59 UTC, taranovakn commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +  it('should handel keydown event', () => {
Поправила)

2023-06-06 12:05 UTC, taranovakn commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +    fireEvent.blur(input);
Поменяла на userEvent.tab() и добавила проверку на отсутствие фокуса

2023-06-06 12:17 UTC, JackUait commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +  it('should fully clear input by backspace pressing', () => {
Тут ещё один тест с похожим текстом остался

```suggestion
  it('should clear selected text in the input after pressing backspace button', () => {
```

2023-06-20 12:04 UTC, zhzz requested changes

2023-06-20 12:04 UTC, zhzz commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +      `${MASK_CHAR_EXEMPLAR.repeat(2)}.${MASK_CHAR_EXEMPLAR.repeat(2)}.${MASK_CHAR_EXEMPLAR.repeat(4)}`,
Можно вынести в константу, чтобы не повторять такую длинную штуку дважды.

2023-06-27 14:47 UTC, taranovakn commented on packages/react-ui/components/DateInput/__tests__/DateInput-test.tsx
> +      `${MASK_CHAR_EXEMPLAR.repeat(2)}.${MASK_CHAR_EXEMPLAR.repeat(2)}.${MASK_CHAR_EXEMPLAR.repeat(4)}`,
Вынесла

2023-07-04 13:02 UTC, zhzz approved these changes

2023-07-04 13:03 UTC, merged