feat(DropdownMenu, TooltipMenu, Kebab): Добавил возможность выключать автоматическое добавление отступа пунктам меню #3155
skbkontur/retail-ui pull request #3172
Opened 2023-05-31 06:54 UTC by slogger

## Проблема

Сейчас различные меню автоматически добавляют отступ всем пунктам меню, если хотя бы у одного есть иконка, это не всегда нужно 
## Решение

Добавил возможность выключать это поведение у всего меню

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности — добавил новый кейс в Storybook
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-01 11:22 UTC, JackUait approved these changes

2023-06-06 16:49 UTC, zhzz requested changes
"Text alignment" больше ассоциируется с выравниванием текста относительно контейнера, типа "по центру", "слева" или "справа". Я бы предложил назвать проп более однозначно. И еще, если его инвертировать, то не придется явно передавать "false" — будет лаконичнее. Например, `disableIconPadding`.

2023-06-06 22:43 UTC, JackUait commented
> Например, `disableIconPadding`.

Мне не нравятся две вещи в этом названии:
- Слово `Padding`, так как оно намекает на детали реализации;
- Слово `Icon` так как возникает чувство, что речь идёт о какой-то конкретной иконке, а не о всех иконках.

Что насчёт `disableIconsIndent` или `disableIconsOffset`?

P.S.
[Изначально](https://github.com/skbkontur/retail-ui/pull/3155#discussion_r1192256954) мне не понравилась идея что-то выключать пропом, но я не подумал о том, что мы выключаем поведение которое по умолчанию включено и маловероятно, что в этом кейсе понадобится использовать двойное отрицание, чтобы обратно включить отступы: `disableIconPadding={false}`

2023-06-07 07:14 UTC, zhzz commented
> Что насчёт `disableIconsIndent` или `disableIconsOffset`?

Норм, но тогда и во внутрянке компонентов эту сущность придется переименовать, чтобы одинаково было.

Вообще, `Padding` можно воспринимать не как название конкретного css-свойства, а как общее слово в значении "набивка", "проставка". А `Icon` как название этой проставки. Тогда плюс/минус все сходится. Не супер очевидно конечно, но что-то лучше тут сложно придумать.

2023-06-07 11:11 UTC, slogger commented
В итоге по сути откатываю к изначальному варианту, только с другим именем переменной?

2023-06-08 04:54 UTC, zhzz commented
Слово за @JackUait. Меня любой из предложенных тут устроит.

2023-06-08 07:03 UTC, slogger commented
Я бы на `preventIconsOffset` остановился

2023-06-08 14:57 UTC, JackUait approved these changes

2023-06-14 11:07 UTC, merged