test(FileUploader): remove using enzyme
skbkontur/retail-ui pull request #3173
Opened 2023-05-31 13:50 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-02 10:16 UTC, zhzz requested changes

2023-06-02 10:16 UTC, zhzz commented on packages/react-ui/components/FileUploader/__tests__/FileUploader-test.tsx
> +          <ThemeContext.Provider value={DEFAULT_THEME}>
Не знаю зачем вообще в этих тестах используются `ThemeContext.Provider`. Можно убрать их, ничего не должно поменяться. Лишний код получается.

2023-06-06 13:18 UTC, taranovakn commented on packages/react-ui/components/FileUploader/__tests__/FileUploader-test.tsx
> +          <ThemeContext.Provider value={DEFAULT_THEME}>
Убрала в нескольких местах по коду, где встречалось

2023-06-07 12:49 UTC, zhzz approved these changes

2023-06-07 12:50 UTC, merged