refactor: update layout icons
skbkontur/retail-ui pull request #3175
Opened 2023-05-31 19:16 UTC by lossir

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-02 08:17 UTC, JackUait requested changes

2023-06-02 09:13 UTC, lossir commented on packages/react-ui/.creevey/images/Button/Icon/chrome2022.png
Это касается только "старых" иконок, которые прокидывают сами пользователи. Их размер может меняться, например, от кегля родителя.
Причины, почему не стал повторять это для темы2022 и для новых иконок я привёл в описании ПРа п. 4.

Новые иконки вовсе не меняют свой размер.
```
Ни в старой теме с сохранившимися стилями:
```
![image](https://github.com/skbkontur/retail-ui/assets/2708211/7f2c4909-bf88-4620-acc0-c8c65922ed69)

```
ни в новой теме2022:
```
![image](https://github.com/skbkontur/retail-ui/assets/2708211/6e22a2ff-5b53-4fe5-97cf-74d7ed23d3ad)

2023-06-02 10:29 UTC, lossir commented on packages/react-ui/.creevey/images/Dropdown/Simple Dropdown/idle/ie112022/idle.png
Такая небольшая деградация дизайна для IE11 вполне допустима. В остальных браузерах ничего не сдвинулось.

2023-06-02 10:34 UTC, lossir commented on packages/react-ui/.creevey/images/Dropdown/With icon and overflow/ie112022.png
В остальных темах такой же баг. Но воспроизводится только в IE11 и пока никто не жаловался.
Думаю, нам не стоит самим инициировать исправления таких багов под IE11.

Думаю, потом стоит его совсем заскипать.

2023-06-02 10:56 UTC, lossir commented on packages/react-ui/.creevey/images/DropdownMenu/With header and footer/scrolled by 100/chrome2022/scrolled by 100.png
Да, высота стала точнее, как в других темах.
До этого высота была неправильная из-за этого костыля. Об этом говорю в п.4 в описании ПРа.

https://github.com/skbkontur/retail-ui/blob/0baecb51c77b9e1b547b6c358f21cd9cf73d036e/packages/react-ui/components/Button/Button.tsx#L441-L450

2023-06-02 11:50 UTC, JackUait commented on packages/react-ui/.creevey/images/Button/Icon/chrome2022.png
> Новые иконки вовсе не меняют свой размер.

У новых иконок в кнопке меняются размеры  с шагом `2px`

<table>
<tr>
 <td> small
 <td> medium
 <td> large
<tr>
 <td> 
<img width="296" alt="Снимок экрана 2023-06-02 в 14 48 53" src="https://github.com/skbkontur/retail-ui/assets/48599460/b7e619cf-809b-4083-aff1-e60e96a6358d">

 <td> 
<img width="293" alt="Снимок экрана 2023-06-02 в 14 49 07" src="https://github.com/skbkontur/retail-ui/assets/48599460/97e924d7-156e-4e03-87e7-41da1c8dbb87">

 <td> 
<img width="314" alt="Снимок экрана 2023-06-02 в 14 49 20" src="https://github.com/skbkontur/retail-ui/assets/48599460/473c5c32-4b2b-4b42-9a47-6759a6602ff9">

</table>

2023-06-02 11:54 UTC, JackUait commented on packages/react-ui/.creevey/images/Button/Icon/chrome2022.png
Пользователи [ожидают](https://www.figma.com/file/newCbSUe899sicnY2Kvd1m/%D0%9F%D1%83%D0%BB-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87-2022?type=design&node-id=4369-44514&t=eUfz5UjNEn4RMvcY-4), что иконки в кнопке будут меняться с шагом `4px`

2023-06-03 10:13 UTC, JackUait approved these changes

2023-06-03 12:44 UTC, merged