docs: fix red toast example
skbkontur/retail-ui pull request #3178
Opened 2023-06-05 13:04 UTC by asukhar

## Проблема

Надо поправить пример красного тоста в доке 

- Нужно поменять цвет красного тоста: #d94d45f5 → #D20F00C2 
- Убрать строчку которая меняет радиус скругления toastBorderRadius: "4px"
- Нужно поправить фон кнопки при нажатии, переопределить переменную toastLinkBgActive
- Заодно хорошо бы добавить надпись какую-нибудь перед рандомными цифрами, чтобы было например «Пример красного тоста №27»

## Решение

Поправлены все пункты

## Ссылки

проф из [гайдов](https://guides.dev.kontur/components/popup-elements/toast/#Dizain)

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-06 22:28 UTC, JackUait requested changes

2023-06-06 22:28 UTC, JackUait commented on packages/react-ui/components/Toast/Toast.md
> +        toastLinkBgActive: "#D20F00C2"
У меня не открываются гайды, чтобы проверить какой цвет там используется, но для цветовой модели `HEX` нужно 6 цифр в 16-ричной системе после знака `#`, а здесь 8 цифр

2023-06-06 22:28 UTC, JackUait commented on packages/react-ui/components/Toast/Toast.md
>        THEME_2022
Думаю, что тут стоит использовать динамическую тему, чтобы пользователи видели стили текущей темы, а не фиксированную 2022 тему:
```tsx
  <ThemeContext.Consumer>
    {(theme) => {
      return <ThemeContext.Provider
        value={ThemeFactory.create(
          {
            toastBg: "#D20F00C2",
            toastLinkBgActive: "#D20F00C2"
          },
          theme
        )}
      >
        <SuperToast />
      </ThemeContext.Provider>
    }}
  </ThemeContext.Consumer>
```

2023-06-07 07:14 UTC, asukhar commented on packages/react-ui/components/Toast/Toast.md
> +        toastLinkBgActive: "#D20F00C2"
Строчка из гайдов:
Плашка
• #D20F00, прозрачность 76%

2023-06-07 07:28 UTC, asukhar commented on packages/react-ui/components/Toast/Toast.md
>        THEME_2022
Исправил

2023-06-07 09:36 UTC, JackUait commented on packages/react-ui/components/Toast/Toast.md
> +        toastLinkBgActive: "#D20F00C2"
Лучше тогда просто использовать `RGBA` запись, так как пользователи могут не понять `HEX` запись с прозрачностью (я в первый раз с такой записью сталкиваюсь)

```ts
toastBg: "rgba(210, 15, 0, 0.76)",
toastLinkBgActive: "rgba(210, 15, 0, 0.76)",
```

2023-06-07 10:26 UTC, asukhar commented on packages/react-ui/components/Toast/Toast.md
> +        toastLinkBgActive: "#D20F00C2"
Хорошо, исправил

2023-06-07 11:14 UTC, JackUait approved these changes

2023-06-08 11:08 UTC, zhzz approved these changes

2023-06-08 11:08 UTC, merged