test(GlobalLoader): remove using enzyme
skbkontur/retail-ui pull request #3179
Opened 2023-06-06 13:04 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-13 10:03 UTC, HelenaIsh requested changes

2023-06-13 10:03 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    expect(screen.getByTestId(GlobalLoaderDataTids.root)).toBeInTheDocument();
Здесь ошибка:  ГЛ не должен быть в документе в это время. Он должен появится только после задержки на появление. 
Проблема, как мы и обсуждали, скорее всего в том, что в `test-setup.js` мокается `debounce`, который ГЛ использует для формирования задержки. 
Предлагаю размокать `debounce` в этом файле, чтобы правильно протестировать ГЛ. Переписала первые два теста, все работает:
```
jest.unmock('lodash.debounce');
describe('Global Loader', () => {
  const refGlobalLoader = React.createRef<GlobalLoader>();
  const refGlobalLoader2 = React.createRef<GlobalLoader>();
  it('should be the only one', async () => {
    render(<GlobalLoader expectedResponseTime={2000} active ref={refGlobalLoader} />);
    render(<GlobalLoader expectedResponseTime={2000} active ref={refGlobalLoader2} />);

    expect(screen.queryByTestId(GlobalLoaderDataTids.root)).not.toBeInTheDocument();
    expect(refGlobalLoader.current?.state.dead).toBe(true);
    expect(refGlobalLoader2.current?.state.dead).toBe(false);
  });
  describe('with props', () => {
    it('should not show before DELAY_BEFORE_GLOBAL_LOADER_SHOW', async () => {
      render(<GlobalLoader expectedResponseTime={2000} active ref={refGlobalLoader} />);
      await delay(DELAY_BEFORE_GLOBAL_LOADER_SHOW - DIFFERENCE);
      expect(refGlobalLoader.current?.state.visible).toBe(false);
      await delay(DIFFERENCE);
      expect(refGlobalLoader.current?.state.visible).toBe(true);
    });
  });
});
```

2023-06-30 05:17 UTC, HelenaIsh requested changes

2023-06-30 05:17 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
>        GlobalLoader.done();
Кажется, что перед этой строчкой тоже нужно добавить `GlobalLoader.start();`

2023-06-30 05:17 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.visible).toBe(false);
Это поведение тестируется чуть выше в 36 строчке. Этот тест можно удалить

2023-06-30 09:12 UTC, HelenaIsh approved these changes

2023-07-11 11:00 UTC, zhzz requested changes

2023-07-11 11:00 UTC, zhzz commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    expect(screen.queryByTestId(GlobalLoaderDataTids.root)).not.toBeInTheDocument();
А почему тут не должно быть `GlobalLoader` на странице?

2023-07-12 02:54 UTC, HelenaIsh commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    expect(screen.queryByTestId(GlobalLoaderDataTids.root)).not.toBeInTheDocument();
Потому что `GL` появляется после задрежки `delayBeforeShow`, которая по дефолту =  1000мс,

2023-07-12 04:40 UTC, zhzz commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +    expect(screen.queryByTestId(GlobalLoaderDataTids.root)).not.toBeInTheDocument();
Да, но тест ведь не это пытается протестировать. 

Проверяется, что GL может быть только один, но при этом почему-то на странице ни одного быть не должно. Непонятна связь между этими фактами.

Кажется наоборот, лучше проверять, что после запуска нескольких GL на странице в итоге появляется только один.

2023-07-12 13:26 UTC, taranovakn commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.visible).toBe(true);
Убрала проверки через state, сделала проверку по наличию элемента на странице
```
await delay(DELAY_BEFORE_GLOBAL_LOADER_SHOW - DIFFERENCE);
expect(screen.queryByTestId(GlobalLoaderDataTids.root)).not.toBeInTheDocument();

await delay(DIFFERENCE); 
expect(screen.getByTestId(GlobalLoaderDataTids.root)).toBeInTheDocument();
```

2023-07-13 11:28 UTC, taranovakn commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.rejected).toBe(true);
Проревьюй плиз все тесты еще раз, постаралась убрать везде использования state
Оставила только в тесте `'should be the only one'` чтобы проверить, что именно второй экземпляр работает, а первый стал в состоянии dead

2023-07-14 10:00 UTC, zhzz commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.rejected).toBe(true);
Я понял, что все-таки менять или добавлять еще `data-tid` к существующему чревато поломкой тестов у пользователей. Как на счет добавить отдельный атрибут на каждое состояние, типа `data-rejected` и `data-done`?

2023-07-14 10:37 UTC, taranovakn commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.rejected).toBe(true);
Да, скорее всего поломает и мне тоже нравилось это решение
Попробую добавить как отдельный атрибут тогда

2023-07-20 08:20 UTC, taranovakn commented on packages/react-ui/components/GlobalLoader/__tests__/GlobalLoader-test.tsx
> +      expect(refGlobalLoader.current?.state.rejected).toBe(true);
Добавила атрибут data-state

2023-07-25 09:29 UTC, zhzz approved these changes

2023-07-25 09:29 UTC, merged