feat: get link bottom color from computed styles
skbkontur/retail-ui pull request #3185
Opened 2023-06-15 10:07 UTC by HelenaIsh

## Проблема

При задании `linkColor: "inherit"` через кастомизацию `ColorFunctions.fade(this.linkColor, 0.5)` выдает ошибку: `Error: inherit is not a valid hex color string`

## Решение

Варианты решения:

 - задавать `opacity` - нельзя, так как подчеркивание задается через border-bottom
 - использовать псевдо-элемент `after` - нельзя, так как ссылка может переходить на следующую строку
 - использовать цвет из `computed styles` для передачи в `ColorFunctions.fade` ✅
 - разрешить использование только напрямую заданных цветов - нелогично, так как `inherit` - валидное `css` свойство
 - 
## Ссылки

fix IF-1260

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-06-20 18:08 UTC, JackUait requested changes

2023-06-20 18:08 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +  }
Для тем отличных от 2022 `color` всегда будет равен `#fff`

2023-06-21 07:23 UTC, HelenaIsh commented on packages/react-ui/components/Link/Link.tsx
> +  }
Да, но в других темах он ни на что не влияет:

<img width="1428" alt="image" src="https://github.com/skbkontur/retail-ui/assets/32093844/c99f0805-8ebe-432c-978d-ec0bdd42923d">

2023-06-21 07:23 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get linkLineBorderBottomColor() {
Вернула удаленные переменные, но они не на что не влияют. Пометила их `deprecated`

На цвет подчеркивания теперь действительно нельзя повлиять, так как он получается из цвета ссылки. (кстати, в других темах на цвет подчеркивания тоже нельзя повлиять) 

Добавила переменную `linkLineBorderBottomOpacity` для возможности регулирования прозрачности

2023-06-22 08:59 UTC, JackUait commented
> ...стал rgba(133, 133, 133, 0.5), что соответствует макетам

А почему не rgba(133, 133, 133, 0.48)? Ведь в макетах именно это значение

Также, ты уточняла у проектировщиков это актуальное значение? В макетах в некоторых местах могут быть "протухшие" значения

2023-06-22 08:59 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get linkLineBorderBottomColor() {
> На цвет подчеркивания теперь действительно нельзя повлиять, так как он получается из цвета ссылки.

Об этом я и говорю. Изменения в пулл-реквесте ломающие. Если у пользователей до этого была возможность изменить цвет подчёркивания, значит что мы не можем отнимать её в одном из минорных релизов

> Добавила переменную linkLineBorderBottomOpacity для возможности регулирования прозрачности

У нас же вроде не запрашивали такую возможность

2023-06-22 09:01 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +  }
Да, в наших кейсах не влияет - может повлиять в других
До пулл-реквеста туда передавались значения из переменных темы - сейчас всегда `#fff`. Это неправильно

2023-06-22 09:01 UTC, JackUait requested changes
> ...стал rgba(133, 133, 133, 0.5), что соответствует макетам

А почему не rgba(133, 133, 133, 0.48)? Ведь в макетах именно это значение

Также, ты уточняла у проектировщиков это актуальное значение? В макетах в некоторых местах могут быть "протухшие" значения

2023-06-23 04:49 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get linkLineBorderBottomColor() {
По мотивам обсуждения в Толке:
- Эти переменные действительно появились только с `THEME_2022`, но это не отменяет того, что они в том числе влияют на остальные темы;
- Помимо переменных для состояния по умолчанию есть ещё и переменные для состояний `hover` и `active`, и если мы говорим, что единственный способ изменить цвет подчёркивания по умолчанию - поменять цвет ссылки, то вероятно и эти переменные придётся удалить в угоду этому дизайн-решению.

Учитывая вышесказанное, я вижу три пути развития событий:
1. Мы действительно отказываемся от всех этих переменных, так как они не задействуются в дизайне
2. Мы отказываемся от части переменных, так как не все из них задействуются в дизайне (речь о переменных для изменения цвета по умолчанию)
3. Эти переменные нужны в дизайне, и мы ищем другой подход (вероятно, запрещаем менять цвет подчёркивания в дизайне интерфейсов) - чтобы разработчики не приходили к нам с невыполнимыми фича-реквестами

2023-06-23 05:24 UTC, HelenaIsh commented
> А почему не rgba(133, 133, 133, 0.48)? Ведь в макетах именно это значение
> 
> Также, ты уточняла у проектировщиков это актуальное значение? В макетах в некоторых местах могут быть "протухшие" значения

По прозрачности: в макетах 0.48, в библиотеке 0.5. Вова не знает, почему Максим так сделал. Возможно, намеренно округлил. В любом случае, Вова не считает это критичным, можно оставить

По цвету заблокированных ссылок уточнила: `#858585` - актуальный цвет, что дает `rgba(133, 133, 133, 0.5)` в `rgba` формате с прозрачностью

2023-06-23 05:30 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get linkLineBorderBottomColor() {
Эти переменные были добавлены в 22 теме и влияют только на подчеркивание в 22 теме. Вряд ли много пользователей успели этим воспользоваться. В данном ПР мы пытаемся исправить баг, который вызван этими переменными. К сожалению, по причинам, описанным в описании ПР, единственный путь решения задачи - не использовать эти переменные, а брать цвет подчеркивания напрямую из вычисленного цвета ссылки. Предлагаю все же удалить их. 

> У нас же вроде не запрашивали такую возможность

Нет, но нам будет удобнее в будущем менять значение в одном месте

2023-06-23 05:40 UTC, HelenaIsh commented on packages/react-ui/components/Link/Link.tsx
> +  }
удалила условие` isTheme2022(this.theme)` при расчете цвет

2023-06-26 04:28 UTC, HelenaIsh commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get linkLineBorderBottomColor() {
Решили отказаться от этих переменных. Цвет подчеркивания всегда должен соответствовать цвету ссылки. переменные для состояний `hover` и `active` тоже удалила

2023-06-27 10:09 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +  }
Рефка `textRef` сеттится только в 2022 теме, в остальных темах цвет по-прежнему будет `#fff`

2023-06-28 04:56 UTC, HelenaIsh commented on packages/react-ui/components/Link/Link.tsx
> +  }
Исправила. Но все равно мне кажется, что это лишнее. Этот цвет применяется только в border-bottom  и на другие темы не влияет

2023-06-29 10:44 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +  }
Да, это всё-таки моя ошибка. Когда тестировал стили проигнорировал `globalClasses.text` и проверял стили напрямую в классах, а не под `globalClasses.text`, из-за чего мои тесты влияли на все темы, а не только на `THEME_2022`. Ты права - эти правки не нужны

2023-06-30 01:25 UTC, JackUait submitted a review, later dismissed

2023-06-30 08:29 UTC, zhzz requested changes
Кажется есть способ решить проблему проще и надежнее, на уровне css. 

Анимации умеют постепенно переводить один цвет в другой. И они работают с любым форматом задания цвета. В нашем случае нужно перевести currentColor в transparent на 50%. [Демо](https://stackblitz.com/edit/web-platform-ah4xkg?file=index.html), того как это можно сделать.

Таким образом можно решить проблему не только для Link, но и для других компонентов, в чьих переменных используются ColorFunctions. Так цвета можно осветлять, затемнять, применять прозрачность. Цвета, заданные любым законным в css способом: hex, rgb, green, inherit и тд. Нужна только переменная со степенью прозрачности.

В IE11 тоже должно работать. Возможно с доработками.

2023-07-04 11:52 UTC, zhzz approved these changes

2023-07-04 11:55 UTC, merged