Refactor tests
skbkontur/retail-ui pull request #3197
Opened 2023-07-05 07:57 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-07 10:17 UTC, zhzz requested changes

2023-07-07 10:17 UTC, zhzz commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup-test.tsx
> +      expect(radios[index]).toHaveAttribute('value', item);
Не стоит лишний раз отключать eslint-правила. В данном случае оно просто требует заменить проверку на `toHaveValue(item)`

2023-07-07 10:17 UTC, zhzz commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup-test.tsx
> +  // });
Остался комментарий

2023-07-10 12:41 UTC, taranovakn commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup-test.tsx
> +  // });
Спасибо, убрала

2023-07-10 12:44 UTC, taranovakn commented on packages/react-ui/components/RadioGroup/__tests__/RadioGroup-test.tsx
> +      expect(radios[index]).toHaveAttribute('value', item);
Используя проверку expect(radios[index]).toHaveValue(item);
 падает с ошибкой 
![image](https://github.com/skbkontur/retail-ui/assets/68959081/91a05800-dc21-4963-9278-467ed33c8df3)

Пробовала разные варианты, ничего больше не смогла придумать, кроме как тот что сейчас в ветке

2023-07-11 09:01 UTC, zhzz approved these changes

2023-07-11 10:12 UTC, merged