feat: tab size
skbkontur/retail-ui pull request #3198
Opened 2023-07-06 08:53 UTC by d-hand

## Проблема

Добавить size для Tabs

## Ссылки

https://yt.skbkontur.ru/issue/IF-1295/Dobavit-prop-Size-dlya-Tabs
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-07 15:05 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -    return this.tabPaddingX;
> Кажется, что tabsMarginX не нужен и можно выпилить

> или его тоже заменить на tabsMarginXSmall, tabsMarginXMedium, tabsMarginXLarge?

> По коду tabsMarginX равен tabPaddingX. Получается tabsMarginX нужен только для того чтобы его можно было менять через тему? Или он еще для чего-то нужен?)

Я думаю, что это просто легаси, которое забыли выпилить.
Давай добавим переменные `tabsMarginXSmall`, `tabsMarginXMedium` и `tabsMarginXLarge`, но сразу пометим их как [@deprecated](https://jsdoc.app/tags-deprecated.html)

---
Переменные `tabFontSize`, `tabPaddingY` и `tabLineHeight` тоже предлагаю пометить как `@deprecated` и написать комментарий какая переменная актуальная

2023-07-07 15:11 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    const borderWidth = parseInt(this.controlBorderWidth) || 1;
А зачем здесь эти фолбэки?

2023-07-11 06:06 UTC, d-hand commented on packages/react-ui/components/Tabs/Tabs.md
> +</div>;
done

2023-07-11 06:06 UTC, d-hand commented on packages/react-ui/components/Tabs/Tabs.styles.ts
> +function cssRoot(t: Theme, size: TabSize) {
done

2023-07-11 06:11 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    const borderWidth = parseInt(this.controlBorderWidth) || 1;
Я точно не знаю, они были до моих изменений. Возможно они нужны для [ThemePlayground](https://tech.skbkontur.ru/react-ui/#/Customization/ThemePlayground), чтобы избежать ошибок при вводе, но это не точно )

2023-07-11 06:25 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get tabFontSize() {
done

2023-07-11 06:31 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -    return this.tabPaddingX;
Я пометил его как [@deprecated](https://jsdoc.app/tags-deprecated.html), но не стал создавать tabsMarginXSmall, tabsMarginXMedium и tabsMarginXLarge. Вместо него нужно использовать tabPaddingXLarge

2023-07-11 07:26 UTC, d-hand commented on packages/react-ui/components/Tabs/Tabs.tsx
> +    const { vertical, size = 'large' } = this.getProps();
done

2023-07-11 09:17 UTC, d-hand commented on packages/react-ui/components/Tabs/__stories__/Tabs.stories.tsx
> +export const Size: Story = () => {
done

2023-07-18 09:58 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> -  public static get tabFontSize() {
> Почему я не вижу подобных указаний для других контролов где есть свойство size?

По-хорошему, они должны там быть, но их не добавили. Например, у `<FileUploader />` такая же [ситуация](https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/internal/themes/DefaultTheme.ts#L1911-L1922)

> Когда удалят добавленные мной deprecated?

Завёл [задачу](https://yt.skbkontur.ru/issue/IF-1342/Ficha-rekvest-vstavki-iz-bufera-obmena-v-fajl-aploader), в рамках которой мы этим займёмся, это случится вместе с 5.0

2023-07-18 09:58 UTC, JackUait commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    const borderWidth = parseInt(this.controlBorderWidth) || 1;
Думаю, что их лучше будет опустить, учитывая, что мы наверняка не знаем какое у них предназначение

2023-07-18 10:08 UTC, JackUait requested changes

2023-07-20 04:42 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    const borderWidth = parseInt(this.controlBorderWidth) || 1;
done

2023-07-20 04:42 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static get tabLineHeight() {
done

2023-07-20 04:54 UTC, d-hand commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static tabPaddingXLarge = '12px';
done

2023-07-24 01:12 UTC, JackUait approved these changes

2023-07-25 07:14 UTC, merged