feat(CurrencyInput): allow to work with very small or large values
skbkontur/retail-ui pull request #3200
Opened 2023-07-10 04:23 UTC by HelenaIsh

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-12 08:22 UTC, lossir requested changes

2023-07-12 08:22 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyHelper.tsx
> +      return '0.' + zeros + lead;
Здесь неправильно раcсчитывает кол-во нулей, т.к. не учитывается возможность дробного числа перед экспонентой.
Это крашит контрол с той же ошибкой.

Примеры:
| исходное число | `toDecimalString` | должно быть |
| --- | --- | --- |
| `1.425e-8` | `0.00000001.425` | `0.00000001425` |
| `0.123` | `0.1.23` | `0.123` |

Вариант с `0.123` можно полечить, если сначала использовать нативный метод `number.toString()`.

А для вариантов наподобии `1.425e-8` надо изменить расчеты примерно так:

```diff
const [lead, decimal] = number.toExponential().split('e-');
+const [int, fra] = lead.split('.');
-const zeros = '0'.repeat(parseInt(decimal) - 1);
+const zeros = '0'.repeat(parseInt(decimal) - int.length);
-return '0.' + zeros + lead;
+return '0.' + zeros + int + fra;
```

2023-07-12 08:33 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyHelper.tsx
> +      return '0.' + zeros + lead;
Опять же, если б не IE11, то можно было сделать так:
![image](https://github.com/skbkontur/retail-ui/assets/2708211/37737832-d43a-4212-87c7-0194458a3cf7)

Остаётся только нули отрезать)

2023-07-13 08:07 UTC, HelenaIsh commented on packages/react-ui/components/CurrencyInput/CurrencyHelper.tsx
> +      return '0.' + zeros + lead;
Заметила чуть выше метод `destructString`, из которого можно доставать необходимые переменные если чуть-чуть дополнить.

Также поняла, что мой метод не работал с отрицательными числами. Исправила. 

Добавила тестов

2023-07-17 07:31 UTC, lossir commented on packages/react-ui/components/CurrencyInput/CurrencyHelper.tsx
> +    return (sign || '') + '0.' + '0'.repeat(-intExponent - 1) + integer + fraction;
Предлагаю сделать более наглядно, что происходит именно конкатенация.
Например, можно складывать всё в массив и делать `join()`:
```js
[sign, integer, fraction, '0'.repeat(intExponent - fraction.length)].join('');
```

2023-07-17 08:48 UTC, lossir approved these changes

2023-07-17 09:12 UTC, merged