fix(Select): add max-width on mobile
skbkontur/retail-ui pull request #3210
Opened 2023-07-19 12:15 UTC by Funkicide

## Проблема

При большой ширине контента выбранного пункта, Select мог вылезать за границу родительского блока.
## Решение

Ограничить максимальную ширину Select'a через max-width, значение max-width вынести в переменную.
## Ссылки

fix IF-820
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅  в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-21 07:14 UTC, zhzz requested changes

2023-07-21 07:14 UTC, zhzz commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +    <div style={{ width: 'calc(100vw - 8px)' }}>
Родительские паддинги, из-за которых приходится делать  `-8px` когда-нибудь могут измениться, например увеличатся. Тогда тест может перестать работать.

Для нашего случая надежнее задать какую-то фиксированную ширину, необязательно близкую к `100vw`, например `200px`.

2023-07-21 12:36 UTC, Funkicide commented on packages/react-ui/components/Select/__stories__/Select.stories.tsx
> +    <div style={{ width: 'calc(100vw - 8px)' }}>
Исправил, скриншот поправил.

2023-07-25 06:08 UTC, zhzz approved these changes

2023-07-25 06:08 UTC, merged