test(Link): remove uning enzyme
skbkontur/retail-ui pull request #3212
Opened 2023-07-20 08:56 UTC by taranovakn

## Проблема

Повысить покрытие тестами компонент, перевести тесты с использования enzyme на RTL

## Решение

Тесты, которые были на enzyme, переписаны с использованием RTL
Добавлены новые тесты на логику компонента

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-25 08:42 UTC, zhzz requested changes

2023-07-25 08:42 UTC, zhzz commented on packages/react-ui/components/Link/__tests__/Link-test.tsx
> +      userEvent.click(linkElement);
Это довольно большой костыль. Но проблему можно официально обойти.

```suggestion
      userEvent.click(linkElement, {}, { skipPointerEventsCheck: true });
```

2023-07-25 08:42 UTC, zhzz commented on packages/react-ui/components/Link/__tests__/Link-test.tsx
> +      screen.debug();
Остался дебаг

2023-07-31 10:25 UTC, taranovakn commented on packages/react-ui/components/Link/__tests__/Link-test.tsx
> +      screen.debug();
Спасибо, убрала

2023-08-07 06:42 UTC, zhzz approved these changes

2023-08-07 06:43 UTC, merged