feat: add aria-label to all appropriate components
skbkontur/retail-ui pull request #3223
Opened 2023-07-27 12:05 UTC by JackUait

## Проблема

## Решение

Возможность прокидывать aria-label как проп:
1. Button ✅ 
2. Modal ✅
3. SidePage ✅
4. Checkbox - на input ✅
5. ComboBox – на input при редактировании ✅
6. Autocomplete - на input ✅, на items 🚧
7. CurrencyInput - на input ✅
8. DateInput - на input - нет инпута с role!="generic" ❌
9. DatePicker - на input - основан на DateInput ❌
10. Dropdown - на button ✅
11. DropdownMenu - на button ✅
12. FxInput - на кнопку и input ✅
13. Input - на input ✅
14. Kebab - на span с role="button" ✅
15. Link - на a ✅
16. MenuItem - на button ✅
17. PasswordInput - на input ✅
18. Radio - на input ✅
19. Select - на button ✅
20. Switcher - для всех button (через объект) ✅
21. Tabs.Tab - на a ✅
22. Textarea - на textarea ✅
23. Toggle - на input ✅
24. Token - на button ✅
25. TooltipMenu - на button ✅
26. TokenInput - на textarea ✅, токены
27. Toast - сделать кнопку "action" role="button" и передать aria-label на неё ✅  

Описание самих компонентов:
1. Calendar - на кнопки выбора даты, выбора года, выбора месяца
2. DatePicker - на кнопку перехода на сегодняшнюю дату ✅
3. Paging - на кнпоки страниц и на кнопку "дальше" - на кнопки не падает фокус ❌
4. PasswordInput - заменить элемент на button и дать описание глазику ✅
5. Toast - крестик ✅

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-07-28 08:25 UTC, HelenaIsh requested changes

2023-07-30 21:38 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> +          aria-label={ariaLabel}
Атрибут `aria-label` [можно навешивать](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label#associated_roles) только на интерактивный контент: инпуты, кнопки и т.д.
Программы чтения с экрана не поддерживают `aria-label` на статичном контенте
В `InputLikeText` есть только `input` с `type="hidden` у которого нет роли (другими словами у него [роль](https://www.w3.org/TR/html-aria/#docconformance) `generic`)

Так что тут ничего не поделаешь - это ограничение нашей системы

2023-07-30 23:27 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            aria-label={'Перейти к сегодняшней дате'}
Добавил в дефолтную тему и закинул тест

2023-07-30 23:39 UTC, JackUait commented on packages/react-ui/components/Dropdown/Dropdown.tsx
> +  extends Pick<AriaAttributes, 'aria-label'>,
Перенёс `aria-describedby` в `Pick`

2023-07-30 23:39 UTC, JackUait commented on packages/react-ui/components/Switcher/Switcher.tsx
> +    ariaLabel?: string,
Добавил

2023-07-30 23:39 UTC, JackUait commented on packages/react-ui/components/Tabs/Tab.tsx
> +export interface TabProps<T extends string = string> extends Pick<AriaAttributes, 'aria-label'>, CommonProps {
Перенёс

2023-07-30 23:40 UTC, JackUait commented on packages/react-ui/components/Toast/ToastView.tsx
> +      <button
Не думаю что это ломающие изменения, здесь просто тестируются детали реализации. Вроде как мы вообще хотели отказаться от селениумных тестов - нужно обсудить с ребятами

2023-07-31 00:04 UTC, JackUait commented on packages/react-ui/components/Toast/ToastView.tsx
> +          aria-label={TOAST_CLOSE_BUTTON_ARIA_LABEL}
Да, не подумал о них! Круто! Добавил

2023-07-31 00:26 UTC, JackUait commented on packages/react-ui/components/Toast/__tests__/ToastView.test.tsx
> +  it('has correct aria-label on close button', () => {
Добавил

2023-08-01 04:21 UTC, HelenaIsh commented on packages/react-ui/components/Toast/ToastView.tsx
> +      <button
Договорились исправить селектор в тестах

2023-08-01 04:21 UTC, HelenaIsh approved these changes

2023-08-01 12:23 UTC, zhzz requested changes

2023-08-05 02:39 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +            aria-label={TODAY_LINK_ARIA_LABEL}
Содержимое кнопки зачитается, но оно не информативно. Пользователь скорее всего догадается о чём идёт речь, но вариант "Перейти к сегодняшней дате" избавит его от гаданий :)

Добавил локализацию для всех компонентов со встроенными `aria-label`

2023-08-08 11:38 UTC, zhzz requested changes

2023-08-08 11:38 UTC, zhzz commented on packages/react-ui/components/DatePicker/locale/locales/en.ts
> +  'today-aria-label': "Go to today's date",
Почему выбрал kebab case? До этого использовался camel.

2023-08-08 11:38 UTC, zhzz commented on packages/react-ui/components/Modal/__tests__/Modal-test.tsx
> +    });
Почему бы не сверять со значением из локали, как в тестах локализации?

2023-08-10 03:33 UTC, JackUait commented on packages/react-ui/components/DatePicker/locale/locales/en.ts
> +  'today-aria-label': "Go to today's date",
Хочу таким образом подчеркнуть, что эта локализация предназначена для `aria-label`'ов и не будет видна зрячим пользователям. Кебаб-кейс выбрал потому что `aria-*` атрибуты записываются через дефис

2023-08-10 08:53 UTC, JackUait commented on packages/react-ui/components/Modal/__tests__/Modal-test.tsx
> +    });
Поправил. Также написал тесты на изменение локали. Оказалось, что в `<Modal />` (а также в `<FileUploader />`) нельзя поменять локаль, так как это функциональный компонент и в нём используется костыльная локаль - разбираюсь с этим

2023-08-10 09:44 UTC, zhzz commented on packages/react-ui/components/DatePicker/locale/locales/en.ts
> +  'today-aria-label': "Go to today's date",
Думаю, для обозначения принадлежности к `aria-label`'ам будет достаточно наличия постфикса "...AriaLabel" у полей объекта. А код-стайл должен оставаться единообразным, без дополнительных скрытых смыслов.

2023-08-11 09:45 UTC, JackUait commented on packages/react-ui/components/DatePicker/locale/locales/en.ts
> +  'today-aria-label': "Go to today's date",
Исправил на `CamelCase`

2023-08-17 08:40 UTC, zhzz commented on packages/react-ui/components/Token/Token.tsx
> +      <CloseButtonIcon aria-label={ariaLabel} side={16} color="inherit" colorHover="inherit" tabbable={false} />
Для кнопки удаления токена точно нужно брать `aria-label` из пропа? Или лучше предустановленный иметь.

2023-08-18 12:45 UTC, JackUait commented
### Проблема

При добавлении `@locale` компоненту, у которого уже есть контекст `@locale` переписывает его

### Решение

У этой проблемы есть два решения, но оба нам не подходят

**Решение №1:**
Как предлагает [документация](https://legacy.reactjs.org/docs/context.html#consuming-multiple-contexts) использовать `Context.Consumer`

Здесь нам мешает:
- Если используем `SidePageContext.Consumer`,  то не получится вызвать `this.context` в методах жизненного цикла: `componentDidMount` и `componentWillUnmount`
- Если используем `LocaleContext.Consumer`, то будем получать пустой объект, так как контекст инициализируется через `@locale`

**Решение №2:**
Написать функциональный/классовый `HOC`, который будет инициализировать в себе контекст и прокидывать его ниже по дереву с помощью пропов

В таком случае мы модифицируем класс и теряем доступ к части публичных методов и полей, что может повлиять на пользовательский код. Например, в том случае если они используют `ref`

2023-08-18 13:18 UTC, JackUait commented on packages/react-ui/components/Modal/__tests__/Modal-test.tsx
> +    });
По какой-то причине смена локали снова стала работать, так что просто добавил тест в `<Modal />`

2023-08-18 14:16 UTC, JackUait commented on packages/react-ui/components/Token/Token.tsx
> +      <CloseButtonIcon aria-label={ariaLabel} side={16} color="inherit" colorHover="inherit" tabbable={false} />
Да, точно! Задал значение и сделал локализацию

2023-08-22 09:42 UTC, zhzz commented
> Если используем LocaleContext.Consumer, то будем получать пустой объект, так как контекст инициализируется через `@locale`

Что значит _контекст инициализируется через `@locale`_?

2023-08-24 09:52 UTC, JackUait commented
> Что значит контекст инициализируется через @locale?

В [@locale](https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/lib/locale/decorators.tsx) задаётся `contextType` и происходит другая логика для инициализации стора. В целом, эту логику можно попытаться перенести в `<SidePageHeader />` ручками и затем уже использовать `<LocaleContext.Consumer />`, но я этот вариант сразу отмёл, так как мы создаём два источника правды. Не уверен, что стоит этим заниматься ради одной переменной, на которую у пользователей может и не быть запроса и которую мы можем при необходимости (по запросу пользователей) добавить в будущем

2023-08-24 10:23 UTC, zhzz commented
Но ведь задача по добавлению `aria-label` не выполнится, если проигнорировать SidePageHeader. Тесты на доступность, если они у кого-то есть, не будут проходить.

Логика из декоратора уже дублируется в хуке `useLocaleForControl`. Она в принципе небольшая и достойна выноса в какую-то общую утилиту.

Или еще вариант, вынести в отдельный компонент часть SidePageHeader, в которой нужен `LocaleContext`. Например, крестик.

2023-08-25 10:54 UTC, JackUait commented
Вынес кнопку для закрытия `<SidePage />` в отдельный компонент и добавил тест, проверяющий, что кнопка выполняет действие

2023-08-28 05:34 UTC, zhzz approved these changes

2023-08-28 05:34 UTC, merged