feat(MiniModal): add new control
skbkontur/retail-ui pull request #3228
Opened 2023-08-02 10:29 UTC by lossir

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-10 10:05 UTC, zhzz requested changes

2023-08-10 10:05 UTC, zhzz commented on yarn.lock
> +  integrity sha512-hSQPw6jgc+ej/UEcdQPG/iBwwMeCEgZr9HByY/J8ToyXztEqXzU9aLsIyrlj1BywBcStO4JQK/zMUWWrV8+riA==
Странные изменения, как они появились?

2023-08-10 11:04 UTC, lossir commented on yarn.lock
> +  integrity sha512-hSQPw6jgc+ej/UEcdQPG/iBwwMeCEgZr9HByY/J8ToyXztEqXzU9aLsIyrlj1BywBcStO4JQK/zMUWWrV8+riA==
При добавлении пакет иконок появляются эти правки.

2023-08-17 13:11 UTC, zhzz requested changes
Предлагаю немножко снизить специфичность API и добавить гибкости. 

Несмотря на четкое видение Гайдов относительно сценариев использования МиниМодалки, в сущности это все та же обычная Модалка с небольшими настройками внешнего вида и поведения. Эти дополнительные настройки не меняют ее сути. В общем случае, она по прежнему служит для показа произвольного диалогового окна. 

Это значит, что весь базовый функционал обычной Модалки в ней лучше сохранить. 
Иначе могут возникнуть сценарии, которые Гайды не предусмотрели, и пользователь сталкнется с ограничениями.

Но я согласен с тем, что сценарии из Гайдов, скорей всего, наиболее вероятны. 
И что мы можем предусмотреть некоторые готовые решения, чтобы облегчить пользователям жизнь. Однако эти решения не должны ограничивать базовый функционал и усложнять устройство и поддержку всего компонента. 

Тут может помочь декомпозиция. Если вынести специфичную логику, не относящуюся напрямую к базовой Модалке, в отдельные компоненты, или передать ее в руки пользователя, то, возможно, получится достичь неплохого компромиса.

Например, пропы `btn*` логически сильно ограничивают сценарии использования МиниМодалки. Проп `direction` не относится к базовому функционалу, а `hasCancelIndent` супер-специфичен.

Вместо них можно внести более общий проп `actions`, куда пользователь сможет передавать произвольный набор кнопок и там же форматировать его. Такой проп уже можно причислить к базовому функционалу диалогового окна.

```jsx
<MiniModal
  icon={<TrashCanIcon size={64} color={theme.btnDangerBg} />}
  title={`Удалить ${<b>{name}</b>}?`}
  description={`Description ${<Tooltip anchor={<HelpIcon />}/>}`}
  actions={<MiniModal.Actions direction="column">    
    <Button use="danger" size="medium">Удалить</Button>
    <Button use="primary" size="medium">Не удалить</Button>
    <MiniModal.ActionsIndent />
    <Button size="medium">Отменить</Button>
  </MiniModal.Actions>}
/>

```

Также, для максимальной гибкости, предлагаю дать возможность полностью менять содержимое МиниМодалки через проп `children`.

```jsx
<MiniModal>
  <MiniModal.Header>
    <MiniModal.Icon>
      <TrashCanIcon />
    </MiniModal.Icon>
    Удалить <b>{name}</b>?
  </MiniModal.Header>
  <MiniModal.Body>
    Description <Tooltip anchor={<HelpIcon />}/>.
  </MiniModal.Body>
  <MiniModal.Footer>
    <MiniModal.Actions direction="column">    
      <Button use="danger" size="medium">Удалить</Button>
      <Button use="primary" size="medium">Не удалить</Button>
      <MiniModal.ActionsIndent />
      <Button size="medium">Отменить</Button>
    </MiniModal.Actions>
  </MiniModal.Footer>
</MiniModal>
```

Самое интересное, что эти меры не только добавляют гибкости, но также упрощают устройство и поддержку компонента за счет декомпозиции и разделения ответственности.

Еще я бы предложил для пропов `title` и `description` использовать тип `ReactNode`, как в большинстве подобных случаев в других компонентах, и сделать их необязательными. Все  для той же гибкости.

2023-11-08 12:47 UTC, zhzz approved these changes

2023-11-14 05:46 UTC, merged