Checkbox size
skbkontur/retail-ui pull request #3230
Opened 2023-08-03 08:20 UTC by SchwJ

## Проблема

Добавить проп size для Checkbox

## Ссылки
https://yt.skbkontur.ru/issue/IF-1352
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-07 12:47 UTC, zhzz requested changes

2023-08-07 12:47 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +    return this.fontSizeSmall;
Сейчас переменная `checkboxFontSize` перестала работать. Но ее могли использовать. Мы сохраняем обратную совместимость в переделах одной мажорной версии библиотеки, и поступаем в таких случаях специальным образом. А именно, сохраняем старую переменную работоспособной, но помечаем ее комментарием `deprecated`. По комментарию мы ее найдем в будущем и удалим. 

Таким образом, пока что контрол должно быть возможно настроить как старой, так и новой переменной.

2023-08-07 12:47 UTC, zhzz commented on packages/react-ui/lib/styles/getLabGrotesqueBaselineCompensation.ts
> +  } else if (fontSize >= 16 && isChrome) {
Почему понадобилось поменять эту логику?

2023-08-07 12:47 UTC, zhzz commented on packages/react-ui/components/__stories__/baseline.stories.tsx
> +        <Checkbox size={size} />
Скриншот с большим размером действительно нужно обновить. Но обрати внимание, как раньше в истории эти размеры задавались. Там есть код, который больше не нужен, и его можно удалить.

2023-08-07 12:47 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.styles.ts
> +  const baselineCompensation = getLabGrotesqueBaselineCompensation(fontSize, labGrotesqueCompenstation, isChrome);
Тут используется старая переменная. Компенсация из-за этого будет работать не так, как задумано.

2023-08-07 12:47 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.styles.ts
> +  rootLarge(t: Theme) {
В Tabs был не очень удачный пример со стилями в виде функций, принимающих размер в параметры. 

Стили для размеров лучше сделать отдельными классами. Можно сделать миксин, как в Button. Он позволит написать стили один раз и переиспользовать в разных местах. Так код будет более декомпозирован и декларативен. Его будет проще переписать на обычный css в будущем.

2023-08-08 11:54 UTC, SchwJ commented
Скриншоты для size=medium также изменились, так как по макетам [2021](https://www.figma.com/file/gELmgHaDwaSRUDJZvnTuLq/%F0%9F%92%80-Kontur-UI-2021?type=design&node-id=11-3426&mode=design&t=IHvo4e67l8a5vyrc-0) [2022](![image](https://github.com/skbkontur/retail-ui/assets/67754964/8f3fa1ca-9812-4b96-abfe-5eba82610cc7)) gap = 8px вне зависимости от size

2023-08-09 05:04 UTC, SchwJ commented
Падают два мигающих теста 
![image](https://github.com/skbkontur/retail-ui/assets/67754964/a2de005b-c8c8-460d-8c90-bbab10f8e922)

2023-08-09 06:52 UTC, zhzz commented on packages/react-ui/lib/styles/getLabGrotesqueBaselineCompensation.ts
> +  } else if (fontSize >= 16 && isChrome) {
Но пока что не для радио, в котором она теперь тоже изменилась. Это видно на скриншоте. Нужно вернуть радио как он был.

2023-08-10 06:21 UTC, zhzz requested changes
Уже почти, еще пара комментариев :)

2023-08-10 06:21 UTC, zhzz commented on packages/react-ui/components/Checkbox/Checkbox.mixins.ts
> +  const boxFontSize = parseInt(fontSize.slice(0, -2));
А для чего делать `fontSize.slice(0, -2)`? `parseInt` ведь и без этого справится.

2023-08-10 06:21 UTC, zhzz commented on packages/react-ui/components/__stories__/baseline.stories.tsx
> +                  checkboxFontSize: '16px', // TODO:  На этот стиль завязан radio. Убрать при работе с radio.
Похоже, что radio завязан на него по ошибке. Ничего не должно сломаться, если убрать его уже сейчас, пока мы в контексте.

2023-08-10 06:21 UTC, zhzz commented on packages/react-ui/internal/themes/DefaultTheme.ts
>    }
Получается, что старая переменная сейчас нигде не используется, а значит ни на что не влияет. Если пользователь ее переопределял у себя, то у него что-то сломается. Нужно сделать так, чтобы размер можно было поменять как через новые, так и через старую переменные.

2023-08-10 09:56 UTC, zhzz approved these changes
👍

2023-08-10 09:56 UTC, merged