feat(Calendar): add accessible descriptions
skbkontur/retail-ui pull request #3232
Opened 2023-08-04 16:44 UTC by JackUait

## Проблема

Начало истории: #3223 - часть задачи была разбита на подзадачи

В `Calendar` некоторым элементам нужны доступные описания, которые нужно задавать на уровне библиотеки

## Решение

- Добавил `aria-label`
- Покрыл новую логику тестами
- Добавил локализацию

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-09 06:51 UTC, zhzz requested changes
Плюс такие же комментарии, как в #[3223](https://github.com/skbkontur/retail-ui/pull/3223#pullrequestreview-1567096394).

2023-08-09 06:51 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    const Tag = isInteractiveElement ? 'button' : 'span';
Почему бы не оставить кнопку на постоянку и передавать в нее disabled?

2023-08-10 02:04 UTC, JackUait commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    const Tag = isInteractiveElement ? 'button' : 'span';
Фактически это не отключенная кнопка, а статический текст. Этот статический текст может стать кнопкой, но это две независимые истории

Также есть ещё один минорный момент: у активной и отключенной кнопок `role="button"`. На отключенную кнопку нельзя попасть с помощью фокуса, но она по-прежнему отображается в дереве доступности (с помощью которого в том числе навигируются пользователи скрин-ридеров). Наличие таких вот двух кнопок друг рядом с другом может ввести пользователей в недоумение, так как одна активна, а другую непонятно как активировать, хотя кнопки с точки зрения скрин-ридера идентичные

2023-08-10 05:37 UTC, JackUait commented
Добавил в документацию упоминание о дефолтных `aria-label`. Во время добавления заметил, что из `<DatePicker />` не меняются локали для `aria-label`. Добавил тесты на изменение `aria-label` в `<DatePicker />` и `<Calendar />`

2023-08-10 09:31 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +    const Tag = isInteractiveElement ? 'button' : 'span';
Ок

2023-08-10 09:53 UTC, zhzz requested changes
Все еще [настаиваю](https://github.com/skbkontur/retail-ui/pull/3223#discussion_r1289858822) на camel-кейсе.

2023-08-10 09:53 UTC, zhzz commented on packages/react-ui/components/Calendar/Calendar.md
> +```
Может быть завести отдельный общий раздел для этого в доке?

2023-08-11 11:41 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.md
> +```
Вынес информацию в `accessibility.md`

2023-08-11 12:20 UTC, JackUait commented on packages/react-ui/components/Calendar/Calendar.md
> +```
Также немного отформатировал и дополнил раздел

2023-08-15 10:20 UTC, zhzz approved these changes

2023-08-15 10:20 UTC, merged