refactor(FileUploaderFile): wrap component in forwardRef
skbkontur/retail-ui pull request #3238
Opened 2023-08-08 10:00 UTC by Funkicide

## Проблема

В компоненте `FileUploader` можно валидировать каждый файл отдельно.

Но сейчас ` ValidationWrapperInternal` будет выбрасывать ошибку, т.к. пытается прокинуть `ref` в функциональный компонент `FileUploaderFile`, который не обёрнут в `forwardRef`.

## Решение

Обернул `FileUploaderFile` в `forwardRef`.
## Ссылки

Fix [IF-1336](https://yt.skbkontur.ru/issue/IF-1336) FileUploader: обернуть FileUploaderFile в forwardRef
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-10 10:40 UTC, zhzz requested changes

2023-08-10 10:40 UTC, zhzz commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.tsx
> +export const FileUploaderFile = forwardRef<HTMLDivElement, FileUploaderFileProps>((props, ref) => {
Норм. Но вспомнил, что у нас есть утилитка `forwardRefAndName`, которая выполняет еще несколько полезных функций. Попробуй переехать на ее.

2023-08-10 12:13 UTC, Funkicide commented on packages/react-ui/internal/FileUploaderControl/FileUploaderFile/FileUploaderFile.tsx
> +export const FileUploaderFile = forwardRef<HTMLDivElement, FileUploaderFileProps>((props, ref) => {
Переехал

2023-08-11 04:38 UTC, zhzz approved these changes

2023-08-11 04:39 UTC, merged