feat(Radio): add prop size, tests, documentation
skbkontur/retail-ui pull request #3246
Opened 2023-08-21 06:17 UTC by SchwJ

## Проблема

Добавить проп size для Radio

## Ссылки
https://yt.skbkontur.ru/issue/IF-1353/Dobavit-prop-Size-dlya-Radio
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-22 06:52 UTC, zhzz requested changes

2023-08-22 06:52 UTC, zhzz commented on packages/react-ui/components/Radio/Radio.styles.ts
> +        box-sizing: border-box;
Получилось дублирование одного и того же кода в 3 местах. Лучше его тоже вынести в миксин.

2023-08-22 06:52 UTC, zhzz commented on packages/react-ui/components/Radio/Radio.mixins.ts
> +  ); // для firefox тоже поди надо
Остался комментарий

2023-08-22 12:31 UTC, SchwJ commented
Также мы обсудили вынесение типа [Element]Size подобным CommonProps образом. Изучу устройство CommonProps 
 и сделаю в отдельном пулреквесте.

2023-08-23 06:04 UTC, zhzz requested changes
Появились конфликтики в скриншотах

2023-08-23 06:04 UTC, zhzz commented on packages/react-ui/components/Radio/Radio.mixins.ts
> +    inset: -${radioOutlineWidth};
Свойство `inset` не работает в IE11. Мы решили, что теперь допускаем небольшую деградацию в IE, но отсутствие обводок фокуса и валидации довольно сильно ломает сценарии. Я бы вернул тут поддержку IE11 пока.

2023-08-24 08:55 UTC, zhzz approved these changes

2023-08-24 08:56 UTC, merged