feat(Token, TokenInput): add prop size, tests, documentation
skbkontur/retail-ui pull request #3251
Opened 2023-08-23 09:52 UTC by SchwJ

## Проблема

Добавить проп size для Token, TokenInput

## Ссылки
https://yt.skbkontur.ru/issue/IF-1355
https://yt.skbkontur.ru/issue/IF-1356
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-08-30 04:59 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +          );
Но ведь всего того же можно достичь прокидывая size в Token из TokenInput [через проп](https://github.com/skbkontur/retail-ui/blob/1711b98f1749bee95a4ea6e19fc573241c986181/packages/react-ui/components/TokenInput/TokenInput.tsx#L250). Только в этом виде все будет более прозрачно устроено.

2023-08-30 06:14 UTC, zhzz requested changes
Нашел такой момент: при редактировании токена или вставке нового в большом размере ширины инпута для ввода текста не хватает.

[TokenInput---size-⋅-Storybook.webm](https://github.com/skbkontur/retail-ui/assets/4607770/48fc99a9-decb-42a8-aaf9-9539d7fa3835)

2023-08-30 10:03 UTC, SchwJ commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static tokenMarginXLarge = '2px';
![image](https://github.com/skbkontur/retail-ui/assets/67754964/60441cca-4229-41a2-bef4-ae438c299b6c)
В макете была неоднозначность, уточнила у Лёши. Неоднозначность прояснена, макет и код исправлены.

2023-09-06 12:15 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +      [this.getInputDisabledSizeClassName()]: !!disabled,
Кажется этот вопрос остался еще.

2023-10-13 07:08 UTC, zhzz requested changes

2023-10-13 07:08 UTC, zhzz commented on packages/react-ui/components/Token/Token.tsx
> +  view: 'TokenView__root',
Это ломающее изменение. ДатыТиды используют пользователи для тестов. У каждого компонента должен быть `root`-дататид.

2023-10-13 07:08 UTC, zhzz commented on packages/react-ui/components/Token/TokenView.tsx
> +  onMouseEnter?: React.MouseEventHandler<HTMLDivElement>;
Стоит пересмотреть концепцию TokenView. Мы хотели переиспользовать только его размеры. Но в итоге в него попало много стилей и логики, которые нужны только обычному токену. Для других кейсов их приходится отключать. Это приводит к излишней сложности.

2023-10-24 09:13 UTC, zhzz requested changes
Уже очень круто. При беглом просмотре еще немного предложений:
1. Унаследовать тип TokenViewProps от div, как, например, в Button. Чтобы не перечислять onClick, onDoubleClick и тд в TokenViewProps вручную.  
2. Попробовать стили крестика тоже упаковать внутрь TokenView, чтобы не эмулировать  его через margin (crosslessGap).  
2. Проп textHolder переделать на children, т.к. в него не только текст передается.

2023-10-26 08:26 UTC, zhzz requested changes
Заметил, что при редактировании токена длинный текст не становится многострочным. 

[TokenInput---size-⋅-Storybook (1).webm](https://github.com/skbkontur/retail-ui/assets/4607770/4e731320-a6fa-40cc-bad1-9c7e50167234)

2023-10-27 09:49 UTC, SchwJ commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +              className={cx({ [styles.transparentBorder(theme)]: isTheme2022(theme) })}
Ответила в [комментарии](https://github.com/skbkontur/retail-ui/pull/3251#discussion_r1372903874) ниже

2023-10-31 06:49 UTC, zhzz requested changes

2023-10-31 06:49 UTC, zhzz commented on packages/react-ui/components/Token/TokenView.tsx
> +      >
`className` из props фактически попадает на div два раза, из-за того, что CommonWrapper внутри его тоже извлекает и прокидывает на первый вложенный в него элемент. Лучше оставить эту работу CommonWrapper, и не добавлять className из пропов на div самим. А если еще перенести `{...rest}` повыше, то и извлекать className из пропов в самом начале не придется.
```suggestion
      <div
        {...rest}
        className={cx(getSizeClassName(size), styles.token(theme))}
      >
```

2023-10-31 06:49 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +              className={cx({ [styles.transparentBorder(theme)]: isTheme2022(theme) })}
Тогда, судя по всему, прозрачный border должен быть у TokenView всегда. И только для Token его нужно красить.

2023-10-31 06:49 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +              classHelp={cx({ [styles.helperTextEditing(theme)]: this.isEditingMode })}
Похоже, что этот стиль и переменная внутри уже не нужны. Они не оказывают никакого влияния. Их забыли удалить вместе с предыдущей старой темой. Можно от них избавиться.

2023-10-31 06:49 UTC, zhzz commented on packages/react-ui/components/TokenInput/TokenInput.tsx
> +              className={cx({ [styles.transparentBorder(theme)]: isTheme2022(theme) })}
Нашел еще один момент, связанный с размерами хелпера. При определенном наборе символов в инпуте его высота меньше, чем должна быть. Это как раз исправляется добавлением постоянного бордера в TokenView.

[Webpack-App.webm](https://github.com/skbkontur/retail-ui/assets/4607770/be83d16a-c76e-4ee4-aaee-c1af1d4ff372)

2023-11-01 09:07 UTC, zhzz approved these changes

2023-11-01 09:09 UTC, merged

2023-11-01 09:10 UTC, zhzz commented
🎉