feat(Calendar, DatePicker): add renderDay and onMonthChange props
skbkontur/retail-ui pull request #3257
Opened 2023-08-31 04:34 UTC by Funkicide

## Проблема

До того как компонент Календаря стал публичным, были добавлены два пропса в Календарь и выкачены в старой версии. Теперь когда Календарь стал публичным, эти правки нужно продублировать и выкатить в актуальной версии.
## Решение

Продублировал правки, добавил новые юнит тесты и переделал на RTL старый.
## Ссылки

Resolve [IF-1181](https://yt.skbkontur.ru/issue/IF-1181) Продублировать правки в Calendar
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ✅ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ✅ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-09-06 08:35 UTC, JackUait requested changes

2023-09-06 08:35 UTC, JackUait commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +    renderDay: (date: CalendarDateShape) => date.date,
Не уверен, что это значение по умолчанию сейчас нужно. Если удалить его всё будет работать корректно. Если не найдёшь причин задавать его - давай удалим и сделаем проп необязательным. Также нужно удалить упоминание значения по умолчанию из `JSDoc` комментария

2023-09-06 08:35 UTC, JackUait commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +    userEvent.click(screen.getByRole('button', { name: 'Выбрать месяц Июль' }));
Давай забирать фразы _"Выбранный месяц"_ и _"Выбрать месяц"_ из `/locale`, чтобы не переписывать тесты при изменении локалей

2023-09-06 08:35 UTC, JackUait commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +  });
Эта логика может сломаться также на уровне `<Calendar />`
Давай продублируем тесты отсюда в него

2023-09-06 08:35 UTC, JackUait commented on packages/react-ui/components/Calendar/CalendarUtils.ts
> +export const getMonthInHumanFormat = (month: number) => month + 1;
Давай переиспользуем этот хелпер везде, где значение месяца инкрементируется

2023-09-08 07:55 UTC, Funkicide commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellSize = '32px'; // deprecated
Вернул переменной работоспособность, тест написал.

2023-09-08 07:55 UTC, Funkicide commented on packages/react-ui/internal/themes/DefaultTheme.ts
> +  public static calendarCellBorderRadius = '50%';
Поменял `calendarCellBorderRadius` на `'9999px'`

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +  onMonthChange?: (changeInfo: CalendarMonthChangeInfo) => void;
Перенёс описание.

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/DatePicker/DatePicker.md
> +```
Добавил пример

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/DatePicker/DatePicker.tsx
> +    renderDay: (date: CalendarDateShape) => date.date,
Если судить по описанию пропа из оригинального [пуллреквеста](https://github.com/skbkontur/retail-ui/pull/3118), то проп не должен быть обязательным. Удалил.

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +    userEvent.click(screen.getByRole('button', { name: 'Выбрать месяц Июль' }));
Сделал. Слова "Выбрать" в локали не было, добавил.

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +  });
Добавил тесты.

2023-09-08 07:56 UTC, Funkicide commented on packages/react-ui/components/Calendar/CalendarUtils.ts
> +export const getMonthInHumanFormat = (month: number) => month + 1;
Переиспользовал.

2023-09-08 10:17 UTC, Funkicide commented on packages/react-ui/components/DatePicker/__stories__/DatePicker.stories.tsx
> +export const DatePickerWithMonthChangeHandle = () => {
Перенёс историю в календарь, добавил тест.

2023-09-11 02:59 UTC, JackUait commented on packages/react-ui/components/Calendar/__stories__/Calendar.stories.tsx
> +};
В пулл-реквесте остались скриншоты от старой логики
<img width="851" alt="Снимок экрана 2023-09-11 в 05 55 46" src="https://github.com/skbkontur/retail-ui/assets/48599460/3acccae4-38a3-42b6-910b-b2e72d92de23">
Нужно удалить их

2023-09-11 03:26 UTC, JackUait commented on packages/react-ui/components/Calendar/CalendarUtils.ts
> +export const getMonthInHumanFormat = (month: number) => month + 1;
Прелесть предыдущего имени была как раз в том, что оно объясняло зачем нужно это увеличение
Текущее название `increaseMonthByOne` описывает то, за что отвечает функция, но это убивает весь смысл абстракции, так как человеку читающему код понятно, что `month + 1` увеличит значение `month` на единицу
Название `getMonthInHumanFormat` как раз говорит о том, что со значением что-то не так и мы исправляем его, чтобы оно стало понятным для пользователей интерфейсов

2023-09-11 03:42 UTC, JackUait commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +    userEvent.click(screen.getByRole('button', { name: 'Выбрать месяц Июль' }));
Для месяцев у нас тоже есть переменные. Хранятся в локалях `<Calendar />`

2023-09-11 06:32 UTC, Funkicide commented on packages/react-ui/components/Calendar/__stories__/Calendar.stories.tsx
> +};
Удалил.

2023-09-11 06:32 UTC, Funkicide commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> +    userEvent.click(screen.getByRole('button', { name: 'Выбрать месяц Июль' }));
Добавил.

2023-09-11 06:42 UTC, Funkicide commented on packages/react-ui/components/Calendar/CalendarUtils.ts
> +export const getMonthInHumanFormat = (month: number) => month + 1;
Вернул название.

2023-09-11 10:52 UTC, JackUait approved these changes

2023-09-13 07:10 UTC, merged