fix(ComboBox): fix key down logic in closed state
skbkontur/retail-ui pull request #3264
Opened 2023-09-11 03:03 UTC by HelenaIsh

## Проблема

Когда `ComboBox` находится внутри формы, при нажатии на `enter` не происходит сабмит

Ожидаемое поведение при нажатии на `enter`:
При открытом результате поиска в комбобоксе - выбор элемента
Когда выбран элемент и просто инпут в фокусе - сабмит

## Решение

При закрытом меню не вызываю обработчик события. Следовательно, не происходит вызов `preventDefault` и форма засабмитится

## Ссылки

fix IF-1436

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-09-11 20:33 UTC, JackUait commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +        this.state.opened && this.dispatch({ type: 'KeyPress', event });
Классное решение :)

Давай напишем функциональный тест на логику

2023-09-13 05:06 UTC, HelenaIsh commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +        this.state.opened && this.dispatch({ type: 'KeyPress', event });
Добавила тест. Изначально хотела добавить тест на проверку вызова `preventDeafault` при нажатии на `enter`, но не получилось.

2023-09-13 23:22 UTC, JackUait approved these changes

2023-09-22 10:55 UTC, zhzz requested changes

2023-09-22 10:55 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +        this.state.opened && this.dispatch({ type: 'KeyPress', event });
Раньше при нажатии стрелок на кобобоксе в фокусе и с закрытым списком, список открывался. Теперь перестал. На это есть специальная логика:

https://github.com/skbkontur/retail-ui/blob/d5675fff5258b2cfb4827ed3021864569288621d/packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx#L268-L274

2023-09-25 07:49 UTC, HelenaIsh commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +        this.state.opened && this.dispatch({ type: 'KeyPress', event });
Добавила тест на это поведение и поправила реализацию

2023-10-03 07:10 UTC, zhzz approved these changes

2023-10-03 07:11 UTC, merged