chore(Link): add outline when focus link
skbkontur/retail-ui pull request #3266
Opened 2023-09-12 09:28 UTC by SchwJ

## Проблема

Добавить обводку Link при фокусе.

## Ссылки
https://yt.skbkontur.ru/issue/IF-1430
https://yt.skbkontur.ru/issue/IF-807/Dobavit-propy-size-dlya-vseh-komponentov

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-09-14 09:46 UTC, JackUait requested changes

2023-09-14 09:46 UTC, JackUait commented on packages/react-ui/.creevey/images/Link/Focused Link/tab press/firefox/tabPress.png
Давай делать эти скриншоты (`Focused Link`) только в `chrome` и `firefox` (без постфиксов)

2023-09-14 09:46 UTC, JackUait commented on packages/react-ui/components/Link/Link.styles.ts
> -  },
Мы здесь по сути отбираем доступ к переменным `link*HoverColor` и `linkLineHoverBorderBottomStyle` у пользователей. С натяжкой это можно расценить как ломающее изменение. Давай обсудим эти изменения с командой

Также если решим отказываться от них, то нужно будет удалить их из других мест где они используются в библиотеке и пометить их устаревшими в темах

2023-09-14 09:46 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +        !isFocused && styles.useRoot(),
А в каком кейсе `useRoot` влияет на состояние фокуса? Его точно нужно добавлять здесь?

2023-09-14 10:53 UTC, SchwJ commented on packages/react-ui/components/Link/Link.styles.ts
> -  },
Мне пришла идея разделить isFocused = !disabled && (this.state.focusedByTab || focused); (Link.tsx 154 строка) на isFocused и isFocusedByTab. Для isFocused оставить поведение, которое было до мои изменений, а для isFocusedByTab - применить изменения. Как тебе кажется, это удачная мысль?

2023-09-15 04:34 UTC, JackUait commented on packages/react-ui/components/Link/Link.styles.ts
> -  },
Думаю, что тут зависит от сценария, который закладывали в это дизайнеры. С точки зрения доступности могу сказать, что текущий вариант лучше, потому что при любом фокусировании выделение элемента должно быть хорошо видно. Так что я склоняюсь к тому, чтобы оставить этот вариант, но нужно обсудить что будем делать с протухшими переменными

2023-09-19 07:50 UTC, SchwJ commented on packages/react-ui/.creevey/images/Link/Focused Link/tab press/firefox/tabPress.png
Предлагаю оставить скриншоты для дефолтной темы и для 2022 в chrome и edge. Чтобы отследить отсутствие изменений при фокусе в дефолтной теме и наличие обводки при фокусе в 2022.

2023-09-19 07:51 UTC, SchwJ commented on packages/react-ui/components/Link/Link.styles.ts
> -  },
При обсуждении с командой мы постановили пометить эти переменные "deprecated". Однако, изменения применяются лишь в теме 2022, а в дефолтной теме они остается старое поведение, где используются эти переменные. Поэтому не требуется помечать их "deprecated".

2023-09-21 00:18 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +          !_isTheme2022 && isFocused && use === 'grayed' && styles.lineFocusGrayed(this.theme),
Эти проверки `isTheme2022` можно опустить для упрощения логики. Лучше будет вынести стили, которые мы не хотим видеть при фокусе в класс `focus2022`

2023-09-21 00:18 UTC, JackUait commented on packages/react-ui/.creevey/images/Link/Focused Link/tab press/firefox/tabPress.png
Давай затащим скриншоты ещё и в тёмные темы этих браузеров

2023-09-21 00:18 UTC, JackUait requested changes
При наведении на зафокусированную ссылку у неё продолжает появляться подчёркивание

https://github.com/skbkontur/retail-ui/assets/48599460/884a6de0-6493-4a0e-9d5a-008a656dd04d

2023-09-21 10:23 UTC, SchwJ commented
Добавила скриншоты в темные темы браузеров.
Добавила скриншоты на проверку наведения (hover) на tab pressed для аналогичных браузеров.
Исправила скриншоты для Button, 2022Dark: ранее были зааппрувлены скриншоты с неправильным оттенком use='link' visuallyFocused.
Убрала подчеркивание при наведении ссылку с фокусом по tab.

2023-09-21 12:22 UTC, JackUait requested changes

2023-09-21 12:22 UTC, JackUait commented on packages/react-ui/components/Link/Link.styles.ts
> -      }
Кейс, когда пользователь наводится на ссылку и кейс, когда пользователь наводится на ссылку _в фокусе_ это два разных кейса и мы должны поддерживать их одновременно. Мы не можем просто удалить логику для одного из кейсов, потому что они независимы друг от друга

Давай научим компонент обрабатывать оба эти кейса и добавим скриншотные тесты на то, что стиль подчёркивания может меняться при наведении (только для `chrome2022`, так как это чисто логика, не завязанная на поведении браузеров)

2023-09-21 12:22 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +          isFocused && _isTheme2022 && styles.focus2022(this.theme),
Наличие `border-bottom` говорит нам о том, что мы находимся в `DEFAULT_THEME`, потому что `border-bottom` это фишка `THEME_2022`. Мы можем удалить ненужные проверки и свести код к следующему:
```ts
!isBorderBottom
? cx(
	...
	isFocused && styles.focus(this.theme),
	...
)
: cx(
	...
	isFocused && styles.focus2022(this.theme),
	...
)
```

2023-09-21 12:22 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +          !_isTheme2022 && use === 'grayed' && focused && styles.useGrayedFocus(this.theme),
Эта проверка также не нужна, потому что мы уверены что находимся в `DEFAULT_THEME` благодаря `!isBorderBottom`

2023-09-27 11:01 UTC, JackUait requested changes

2023-09-28 08:21 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +              [styles.tabFocused()]: this.state.focusedByTab,
А что с этим комментарием?

2023-09-28 09:21 UTC, JackUait commented on packages/react-ui/components/Link/Link.tsx
> +              [styles.tabFocused()]: this.state.focusedByTab,
Я имел ввиду вот эту строчку:
```ts
202 [styles.tabFocused()]: this.state.focusedByTab,
```

Если удалить её визуально ничего не изменится (ни при фокусе, ни при наведении, ни при фокусе + наведении) и тесты не упадут. Если она действительно нужна, то давай добавим тест, который будет проверять сценарий, который она покрывает

2023-09-28 09:44 UTC, SchwJ commented on packages/react-ui/components/Link/Link.tsx
> +              [styles.tabFocused()]: this.state.focusedByTab,
Проверила на различных кейсах в различных версиях chrome и firefox - эта строчка действительно теперь не нужна

2023-09-28 10:18 UTC, JackUait approved these changes

2023-10-04 08:48 UTC, zhzz requested changes

2023-10-04 08:48 UTC, zhzz commented on packages/react-ui/components/Link/Link.tsx
> -          disabled && _isTheme2022 && isDarkTheme(this.theme) && styles.disabledDark22Theme(this.theme),
Почему пропал флаг `_isTheme2022`? `isBorderBottom` не является его заменой. Кто-то ведь может переопределить переменную `linkLineBorderBottomWidth`.

2023-10-04 08:48 UTC, zhzz commented on packages/react-ui/components/Link/Link.styles.ts
> +  tabFocused() {
А чем принципиально отличается `tabFocused` от `focus2022`?

2023-10-04 08:48 UTC, zhzz commented on packages/react-ui/components/Link/__stories__/Link.stories.tsx
> +export const FocusedLink: Story = () => <Link icon={<OkIcon />}>Simple Link</Link>;
Необязательно создавать отдельную историю для каждого теста. Можно переиспользовать существующие, просто добавляя новые тесты к ним. Эта, например, полностью повторяет историю `WithIcon`.

К тому же, хорошо когда название истории отражает ее содержимое, сценарий который она воспроизводит. Т.е. название `FocusedLink` подразумевает, что внутри ссылка будет сразу в фокусе. Но на самом деле там просто ссылка.

2023-10-04 08:48 UTC, zhzz commented on packages/react-ui/internal/themes/Theme2022.ts
> +  public static focusLinkOutlineColor = '#3D3D3D';
Имена переменных у нас в основном начинаются с названия компонента. Потом может идти конкретный элемент компонента. Потом идет состояние. Потом свойство. 

Т.е. соглашение примерно такое: 
```[Компонент][Элемент][Состояние][Свойство]```

2023-10-05 17:18 UTC, zhzz requested changes

2023-10-05 17:18 UTC, zhzz commented on packages/react-ui/components/Link/Link.tsx
> +          isFocused && styles.focus2022(this.theme),
Условие на тему 2022 тут не нужно?

2023-10-05 17:21 UTC, zhzz commented on packages/react-ui/components/Link/__stories__/Link.stories.tsx
> +export const FocusedStyledLink: Story = () => {
Тут остался вопрос.

2023-10-06 09:10 UTC, SchwJ commented on packages/react-ui/components/Link/__stories__/Link.stories.tsx
> +export const FocusedStyledLink: Story = () => {
Забыла отправить комментарий.

Ранее переопределение linkLineHoverBorderBottomStyle не работало должным образом из-за внутреннего устройства Link и это не было "отловлено" на этапе изменения внутреннего устройства Link. Тест нужен, чтобы проверять, верно ли работает это поведение

2023-10-06 09:18 UTC, SchwJ commented on packages/react-ui/components/Link/Link.tsx
> +          isFocused && styles.focus2022(this.theme),
Условие _isTheme2022 приданном устройстве подчеркивания ни на что не влияет (так как в других темах подчеркивание реализовано другими средствами). Но для логики, "для порядка" это условие нужно. Иначе в будущем при изменение реализации подчеркивания в других темах могут появиться ошибки.
Добавлю это условие.

2023-10-09 11:35 UTC, zhzz approved these changes
Появилось несколько конфликтов

2023-10-10 05:21 UTC, merged