fix(ComboBox): fix mobile overlay not closing when using public methods
skbkontur/retail-ui pull request #3268
Opened 2023-09-14 10:48 UTC by Funkicide

## Проблема

При использовании методов .reset() и/или .close() на мобилках Комбобокс закрывается не до конца.
Для мобилок используется компонент `<MobilePopup>` с собственным проп `opened`.
В компоненте `<ComboBoxView>`, который использует `<MobilePopup>`, прокидывает в этот проп специальный флаг `state.isMobileOpened`, который не синхронизирован с флагом `props.opened`.
## Решение

Я убрал из компонента `<ComboBoxView` состояние, отвечающее за отрисовку мобильного меню, и сделал отрисовку зависимой от пропа `opened`, как в десктопной версии. Так же вынес методы открытия и закрытия мобильного меню в родительский компонент `CustomComboBox`.
## Ссылки

fix [IF-1225](https://yt.skbkontur.ru/issue/IF-1225) ComboBox: не закрывается оверлей на мобилках при использовании публичных методов
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-09-19 04:50 UTC, zhzz requested changes

2023-09-19 04:50 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> -    }
Этот вызов `this.props.onInputBlur` больше не нужен?

2023-09-19 04:50 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> +          onClick={isMobile ? onMobileFocus && onMobileFocus(this.mobileInput) : onInputClick}
Не очень логично передавать `this.mobileInput` куда-то наружу, чтобы там на нем сразу вызывать `fucus()`. Лучше вызывать его тут, по месту, где `mobileInput` определен, как раньше было.

2023-09-19 04:50 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> +      this.props.onMobileClose && this.props.onMobileClose();
Лаконичнее использовать [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

```suggestion
      this.props.onMobileClose?.();
```

2023-09-19 04:50 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +    this.dispatch({ type: 'Search', query: '' });
Раньше этот вызов вроде не требовался?

2023-09-19 09:06 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> -    }
Да, теперь этот метод из этого пропа вызывается в `onMobileClose`, который прокидывается из `CustomComboBox`.

2023-09-19 09:06 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/ComboBoxView.tsx
> +      this.props.onMobileClose && this.props.onMobileClose();
Изменил на оператор.

2023-09-19 09:06 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBox.tsx
> +    this.dispatch({ type: 'Search', query: '' });
Получается, что при закрытии комбобокса через публичный `close`, в состоянии флаги `editing`, `focused` оставались `true` и меню либо не открывалась повторно, либо открывалось, но пустое, либо вообще открывалось, но с одним `item`, хотя должно целиком рисоваться, как на десктопе. Этот вызов приводит логику к десктопной, где такой проблемы нет. Плюс немного отрефакторил и заменил `this.dispatch({ type: 'Search', query: '' })` на вызов `this.props.onInputClick?.()` и получается логика открытия, закрытия почти одинаковая на десктопе и мобилке.

2023-09-20 02:55 UTC, zhzz requested changes

2023-09-20 02:55 UTC, zhzz commented on packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
> +class ComboBoxWithRenderAddButtonProp extends React.Component<
Довольно сложная история для такого теста. Можно просто передать `renderAddButton` в `SimpleCombobox`.

Еще лучше попробовать написать unit-тест вместо скриншотного, ведь здесь тестируется только логика, а не внешний вид. Эмулировать мобильный режим в unit-тестах  можно [так](https://github.com/skbkontur/retail-ui/blob/7befaf9d9222c95d99150aba37988cec9a5b0326/packages/react-ui/components/ResponsiveLayout/__tests__/useResponsiveLayout-test.tsx#L22-L42).

2023-10-02 13:23 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__stories__/Combobox.stories.tsx
> +class ComboBoxWithRenderAddButtonProp extends React.Component<
Добавил юнит тест вместо скриншотного.

2023-10-04 10:09 UTC, zhzz requested changes

2023-10-04 10:09 UTC, zhzz commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    userEvent.click(screen.getByTestId('AddButton'));
Уже не обязательно нажимать на `AddButton`, чтобы закрыть меню. Это неочевидное действие. Можно просто явно вызвать `close()`.

2023-10-04 10:09 UTC, zhzz commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    ).then<typeof items>((result) => new Promise((resolve) => setTimeout(resolve, 0, result)));
Зачем нужен такой `then`?

2023-10-04 10:09 UTC, zhzz commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +  const menuItemsWithAddButtonCount = 4;
Магичиское число `4`. Его лучше высчитывать а не хардкодить.

2023-10-04 14:31 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    userEvent.click(screen.getByTestId('AddButton'));
Поменял на вызовы `close()` и убрал `AddButton`.

2023-10-04 14:31 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    ).then<typeof items>((result) => new Promise((resolve) => setTimeout(resolve, 0, result)));
Если подумать, то не нужен. Убрал.

2023-10-04 14:32 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +  const menuItemsWithAddButtonCount = 4;
Исправил.

2023-10-05 16:53 UTC, zhzz approved these changes

2023-10-05 16:54 UTC, merged