feat(MenuItem): allow MenuItem at any level
skbkontur/retail-ui pull request #3270
Opened 2023-09-19 04:02 UTC by HelenaIsh

## Проблема

Позволить оборачивать MenuItem

## Решение

Предыдущая неудачная попытка была в #3247
В данном ПР пробую решить проблему через контекст. 

## Ссылки

fix IF-216

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-10-23 09:17 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/MenuNavigation.ts
> +      const menuItems = Array.from(this.root.current.querySelectorAll('span[data-tid="MenuItem__content"]'));
исправила на дата-тид из константы

2023-10-23 09:17 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/MenuNavigation.ts
> +  };
добавила исключение заблокированных пунктов меню;
добавила метод `select` вместо пропсов

2023-10-23 09:18 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/MenuNavigation.ts
> +    }
поправила  👍

2023-10-23 09:21 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    this.unhighlight();
перенесла вызов `unhighlight()` пункта меню в `MenuNavigation`

2023-10-23 09:22 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    this.context.navigation?.select?.(e, this.context.onItemClick);
перенесла вызов `onItemClick` в пункт меню

2023-10-23 09:24 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +      this.scrollToSelected,
перенесла логику для скролла в `Menu`. Пришлось сделать `items` публичным, чтобы `Menu` понимал в какую сторону нужно скроллить

2023-10-23 10:09 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    this.menuNavigation?.highlightByIndex(index);
Правильно ли я тебя поняла, что в случае с заблокированными пунтами меню они не будут включены в список `items`,  а следовательно нужно передавать `index` понимая, что считать нужно только активные пункты меню? 

Например в следующем примере `Menu.highlightItem(0`) будет выделять второй пункт меню
```
<Menu>
  <MenuItem disabled /> 
  <MenuItem />
</Menu> 
```

То есть написать в документации, что нужно считать активные пункты меню?

2023-10-24 08:40 UTC, lossir commented on packages/react-ui/internal/Menu/Menu.tsx
> +    this.menuNavigation?.highlightByIndex(index);
Да, всё правильно поняла. Но я совсем не учёл, что компонент `Menu` - внутренний.  У него нет доки)
Зато этот метод используется в наших же контролах, которые используют `Menu` под капотом: `Select`, `TokenInput` и `ComboBox`. Ещё отчасти `Dropdown`, т.к. у него внутри `Select`.

Чтобы сохранить обратную совместимость придётся что-то другое придумать.
Например, в интерфейс `Highlightable` можно добавить метод типа `isEnabled()`.
Тогда в методах `move()` и `highlight()` можно будет просто фильтровать `this.items` предварительно.
А в методе `highlightByIndex()` уже **не** фильтровать весь массив, а проверять включенность нужного итема непосредственно перед вызовом `highlight()`.

Так логика включенности/выключености также останется внутри `MenuItem`, и получится сохранить обратную совместимость.

2023-10-24 08:41 UTC, lossir commented on packages/react-ui/internal/Menu/MenuNavigation.ts
> +      const menuItems = Array.from(this.root.current.querySelectorAll('span[data-tid="MenuItem__content"]'));
Надо чтобы сама константы приходила из `Menu`.

2023-10-24 10:50 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    this.menuNavigation?.highlightByIndex(index);
Классное предложение! Поправила

2023-10-25 06:20 UTC, lossir commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Напомни, зачем это условие?

2023-10-25 06:51 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Здесь костыль, чтобы исправить ситуацию, когда рефка Меню не создается в нужный момент:
`private menuNavigation: MenuNavigation<MenuItem> = new MenuNavigation(this.contentRef, MenuItemDataTids.content);`

Стандартный жизненный цикл выглядит примерно так:

1. `render parent`
2. `render child`
3. `didmount child`
4. `didmount parent`

При маунте ребенка (`MenuItem`) мы обращаемся в навигацию и ожидаем, что там уже есть рефка родителя (`Menu`). Но в этот момент она еще не установилась

Поэтому я ожидаю пока замаунтится родитель и только потом монтирую детей

2023-10-25 10:55 UTC, lossir commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Блин, этот момент я упустил, из-за двойного рендеринга в стрикт моде..
Хотя Лена и до этого упоминала эту проблему, я только сейчас сообразил.

У меня уже есть идея `MenuNavigation` версии `2.0`, где этой проблемы не будет в принципе, но со своими "но".
Думаю, фичу можно катить в таком виде. Доработку можно отложить до получения обратной связи.

2023-10-25 15:47 UTC, lossir commented
Только сейчас понял, что надо добавить документацию с примерами.
Вероятно, примеры надо добавить во всем контролы, который используют `Menu`.

2023-10-25 15:48 UTC, lossir approved these changes

2023-11-13 07:02 UTC, zhzz requested changes

2023-11-13 07:02 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.tsx
> +  };
Здесь предполагается, что MenuItem'ы по прежнему должны лежать на первом уровне в `children`. А суть задачи в отказе от этого требования.

2023-11-20 06:01 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +  };
Ты прав, пропустила этот момент. Перенесла эту логику в `MenuItem`

2023-12-13 08:38 UTC, zhzz requested changes
1\) Если концептуально сравнить текущую и новую реализации, то можно заметить следующее.

Раньше механика подсветки элементов оперировала индексами. Хранился и менялся индекс элемента, который нужно подсветить. Когда элементы были готовы, нужный мог найтись по этому индексу и подсветиться.

Новая версия оперирует элементами. Для подсветки нужный элемент ищется в списке и сохраняется как подсвеченный. Это накладывает ограничение  — для подсветки список элементов уже должен быть готов. Но, как оказалось в ходе реализации, это не всегда так, и не всегда удобно.

Вызывать методы подсветки через setTimeout  — это костыль, который подпирает недостатки новой механики. Есть ли у нее плюсы, ради которых стоит мириться с этим? Задача может быть решена и с сохранением индексного подхода.

2\) Пришло понимание, что при любой реализации текущие правки будут ломающими. 

Какие-то кастомные пользовательские элементы на основе MenuItem, 
которые раньше не работали из коробки теперь заработают. Плюс, у нас самих в доке селекта (первый пример) описан рецепт, как сделать статичный элемент с правильными отступами:
```
Select.static(<Select.Item>Статичный элемент</Select.Item>)
```
Теперь этот рецепт сломается.

Чтобы не откладывать правку до мажорной версии, можно спрятать ее за [фича-флаг](https://github.com/skbkontur/retail-ui/pull/3312 ).

2023-12-28 09:51 UTC, HelenaIsh commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +    globalObject.setTimeout(() => menu.highlightItem(index), 0);
1) Получилось убрать `setTimeout`. Изменила логику: пункты меню могут просто регестрироваться в конец списка, если меню еще не смонтировано. Проверять  себя в списке они должны только если были вставлены динамически в уже смонтированное меню:
```
if (this.root?.current) {
      this.update();
    } else {
      this.items.push(item);
    }
```
2) согласна. Знаю случаи, когда пользователи намеренно оборачивают пункт меню во что-либо, чтобы выключить его из навигации. Аналогичный запрос был в SideMenu (IF-1103)
 - Убрала все изменения под фиче-флаг. 
 - Добавила проп `isNotSelectable` для пунктов меню. В SideMenu проп назвали isButton. В данном случае `isNotSelectable` кажется более уместным

2023-12-28 09:52 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
>    }
вернула `move`

2023-12-28 09:52 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> -    }
вернула

2023-12-28 09:52 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
вынесла

2023-12-28 09:52 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    this.menuNavigation?.reset();
убрала `?`

2023-12-28 09:53 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    }
исправила

2023-12-28 09:53 UTC, HelenaIsh commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    expect(backgroundColor).not.toBe('transparent');
вернула старое поведение

2023-12-28 09:53 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    this.menuNavigation?.highlightByIndex(index);
Исправила `Select`: теперь индексы считаются по реальным пунктам меню. Это тоже можно рассматривать как ломающее изменение

2024-01-16 13:13 UTC, zhzz requested changes

2024-01-16 13:13 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    }
Если в меню с `menuItemsAtAnyLevel` все элементы, у которых есть иконка размонтируются, то у остальных элементов отступ для иконки не пропадет.

2024-01-16 13:13 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +   * Запрещает выделение и выбор данного пункта меню. Работает только с флагом menuItemsAtAnyLevel [FeatureFlags](#/FeatureFlagsContext)
Почему бы не включить `isNotSelectable` для всех режимов, а не только с флагом menuItemsAtAnyLevel? Чтобы не делать лишних правил.

2024-01-16 13:13 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Я думаю, что иметь два отдельных механизма навигации, старый и новый, довольно накладно и сложно. Нет ли вариантов оставить только новый, добавив в него возможность эмулировать старое поведение?

2024-01-17 10:18 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    }
добавила соответствующую логику в `componentDidUpdate`

2024-01-17 10:19 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +    }
добавила логику на проверку иконки у остальных пунктов меню при размонтировании

2024-01-17 10:20 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +   * Запрещает выделение и выбор данного пункта меню. Работает только с флагом menuItemsAtAnyLevel [FeatureFlags](#/FeatureFlagsContext)
добавила логику пропа `isNotSelectable` и в существующее решение

2024-01-17 10:48 UTC, HelenaIsh commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Здесь не вижу возможности это реализовать: новый механизм кастомизации для эмуляции старого поведения должен "отключать" пункт меню, если он завернут во что-либо. Реализовать это можно, если пункт меню будет сам знать о своем родителе, что противоречит однонаправленной передаче информации в реакте. Конечно это можно реализовать, но это не будет красивым решением. 
Также мы удалим старый механизм в ближайшем мажорном релизе. 
Поэтому, по-моему мнению, не стоит пытаться эмулировать старое поведение через новый механизм

2024-01-23 06:54 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
А если знать, что пункт меню во что-то завернут будет не он сам, а Menu или MenuNavigation? Использовать для этого можно примерно тот же механизм, что был раньше.

Такой вариант сильно упростил бы итоговое решение. Поэтому его имеет смысл попробовать. Даже учитывая то, что старый режим планируем скоро удалить. Это тоже будет сделать проще.

2024-01-23 08:49 UTC, zhzz requested changes

2024-01-23 08:49 UTC, zhzz commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +      this.context.setEnableIconPadding?.(!!this.props.icon);
Если иконка пропадет у одного из пунктов, то общий отступ исчезнет, несмотря на то, что иконка еще может оставаться у других пунктов меню.

https://github.com/skbkontur/retail-ui/assets/4607770/bc438abd-44ae-49fb-ac0c-b14bbe7e4479

2024-01-25 07:56 UTC, HelenaIsh commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +      this.context.setEnableIconPadding?.(!!this.props.icon);
исправила

2024-01-25 10:58 UTC, zhzz requested changes

2024-01-25 10:58 UTC, zhzz commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +```
Этот проп уже не привязан к фиче-флагу, поэтому пример стоит перенести в общую доку. Но можно его применить в примере выше к одному из пунктов, в целях рекламы.

2024-01-25 11:02 UTC, zhzz commented on packages/react-ui/internal/Menu/Menu.tsx
> +    }
Ради справедливости отмечу, что рекурсивный проход необязателен, если не пытаться использовать именно проп `isNotSelectable` для отключения. Но больше на своем варианте не настаиваю.

2024-01-26 07:31 UTC, HelenaIsh commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +```
поправила доку

2024-01-29 05:44 UTC, lossir approved these changes
Я посмотрел только использование флага `menuItemsAtAnyLevel`.

Заметил, что в `Menu` флаг всегда разделяет старую и новую логику.
А в `MenuItem` всегда добавляет новую логику.

В целом выглядит норм. Думаю, это самый простой вариант сохранить обратную совместимость на некоторое время.

2024-01-29 06:29 UTC, zhzz approved these changes
Появился конфликт с некстом, нужно порешать. Потом я сам волью ПР, прикинув примерно порядок ближайших релизов.

2024-02-01 09:43 UTC, merged