feat(Button, Link): add addUnderlineOnHover prop
skbkontur/retail-ui pull request #3291
Opened 2023-10-12 09:55 UTC by HelenaIsh

## Проблема

У пользователей часто возникает сценарий, когда в 22 теме необходимо реализовать наличие подчеркивания в кнопке-ссылке при наведении

## Решение

Добавила проп `addUnderlineOnHover` в кнопку и в ссылку

## Ссылки

fix IF-1400

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-10-17 11:48 UTC, zhzz requested changes
Я бы предложил сделать проп более общим и расширяемым. 

Сейчас, как я понимаю, `addUnderlineOnHover` предполагает, что ссылки подчеркнуты по умолчанию, и предлагает "добавить" подчеркивание по наведению. 
- Но слово "добавить" не очень подходит. По сути, должно происходить переключение их одного режима в другой.
- К тому же, ссылки по умолчанию подчеркнуты только в 2022 теме. В старой этот проп будет невалиден. Да и в будущих темах ситуация может поменяться.
- И на самом деле в 2022 теме по наведению ссылки уже подчеркнуты, но без прозрачности.

Более надежно будет не рассчитывать на какую-то конкретную текущую реализацию. Вместо этого можно выявить все возможные популярные режимы подчеркивания, сделать их независимыми друг от друга, и давать переключать пользователю.

Я вижу это примерно так, детали можно обсудить всем вместе:
```
underline="byDefaultWithTransparency"
underline="onHover"
underline="byDefault"
```

В разных темах такой проп может оставаться рабочим, просто с разными значениями по умолчанию. Если появятся другие режимы, то их будет легко добавить, либо заменить.

2023-10-17 11:48 UTC, zhzz commented on packages/react-ui/components/Link/Link.styles.ts
> +      }
Думаю, это лучше делать через переопределение переменных, чтобы не усложнять стили.

2023-10-20 08:35 UTC, HelenaIsh commented on packages/react-ui/components/Link/Link.styles.ts
> +      }
Поддерживаю идею создать более общий проп `underline`.  

Предлагаю, если он не задан, показывать дефолтное подчеркивание.

Плюс добавила режимы:
- `'always'`
- `'onHover'`
- `'none'`

Хотела еще добавить `'WithTransparency'`, но для 22 тем подчеркивание с прозрачностью применяется по умолчанию, а в старых темах не думаю, что нужно его реализовывать.

2023-11-08 09:33 UTC, HelenaIsh commented on packages/react-ui/components/Link/Link.styles.ts
> +      }
Решили не добавлять проп, а добавить примеры в документацию

2023-11-10 06:55 UTC, zhzz approved these changes
👍

2023-11-10 06:59 UTC, merged