chore(Hint, Kebab): remove pin from Kebab and Hint in Theme2022 base on featureFlag
skbkontur/retail-ui pull request #3331
Opened 2023-12-14 09:21 UTC by SchwJ

## Проблема

Удаление клювика у Kebab и Hint -- ломающее изменение

## Решение

Удаление клювика у Kebab и Hint обернуто в featureFlag kebabHintRemovePin

## Ссылки

[#3274](https://github.com/skbkontur/retail-ui/pull/3274) -- удалили клювик

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

3. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

4. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

5. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2023-12-19 05:57 UTC, HelenaIsh requested changes

2023-12-19 05:57 UTC, HelenaIsh commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          this.featureFlags = getFullReactUIFlagsContext(flags);
Кажется, что нам не нужно сохранять флаги в `this.featureFlags`, так как это значение используется только внутри `<ReactUIFeatureFlagsContext.Consumer>` 
Я бы заменила на локальную переменную `const hasPin = ...`

2023-12-19 05:57 UTC, HelenaIsh commented on packages/react-ui/components/Kebab/Kebab.tsx
> +                popupHasPin={this.featureFlags.kebabHintRemovePin ? !isTheme2022(this.theme) : true}
здесь я бы заменила тернарный оператор на булево выражение `!getFullReactUIFlagsContext(flags).kebabHintRemovePin || !isTheme2022(this.theme)` и вынесла бы в переменную `hasPin` выше. 

Аналогичные изменения можно добавить в `Hint`

2023-12-19 06:10 UTC, HelenaIsh commented
А еще нужно добавить описание и пример с `kebabHintRemovePin` в документацию

2023-12-19 08:53 UTC, SchwJ commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          this.featureFlags = getFullReactUIFlagsContext(flags);
Я сделала так, руководствуясь такими соображениями:

- Так сделано в остальных фиче-флагах (в том числе и в [tokenInput](https://github.com/skbkontur/retail-ui/blob/f8cd44001558a6ea7d8ba8354d347ed9402b8f2c/packages/react-ui/components/TokenInput/TokenInput.tsx) (строка 374), где ситуация аналогична), а оно, в свою очередь, сделано по образу и подобию темы.

- Если нам, например, нужно будет добавить какой-то новый флаг, меняющий поведение, например, для изменений в renderCaption (которое непосредственно используется в renderMain), нам придется заново считывать фиче-флаги если мы использовали локальную переменную const hasPin = ... .  А в том варианте, который сейчас есть, достаточно будет просто обратиться к ранее присвоенному this.featureFlags.

- В очередном мажорном релизе проще избавляться от фиче-флагов будет проще -- везде нужно удалять this.featureFlags, а не разноименные переменные.

Если я где-то не права, или чего-то не учла или недопоняла, напиши, пожалуйста

2023-12-19 09:25 UTC, HelenaIsh commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          this.featureFlags = getFullReactUIFlagsContext(flags);
1) В `TokenInput` флаг сохраняется в переменную `this.featureFlags` потому что она используется в методе `getDelimiters()`. В нашем же случае эта значение не используется в других методах, поэтому на мой взгляд достаточно локальной переменной
2) Да, но сейчас в этом нет необходимости. Если мы в `Hint` или `Kebab` будем добавлять еще фиче флаги, то нужно будет добавить поле `featureFlags`. 
3) В мажорном релизе мы будем удалять конструкцию `<ReactUIFeatureFlagsContext.Consumer> {(flags) => { const hasPin=... ` переменную будет не сложно удалить вместе с конструкцией

2023-12-19 09:39 UTC, SchwJ commented on packages/react-ui/components/Kebab/Kebab.tsx
> +          this.featureFlags = getFullReactUIFlagsContext(flags);
Окей, поняла. Спасибо!

2023-12-20 04:54 UTC, HelenaIsh requested changes

2023-12-20 04:54 UTC, HelenaIsh commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +В Hint и Kebab будет убран "клювик"".
```suggestion
В Hint и Kebab будет убран "клювик".
```
Еще я бы написала, что эта фича будет работать только в 22 теме

2023-12-20 08:02 UTC, HelenaIsh approved these changes

2024-01-22 12:35 UTC, zhzz approved these changes

2024-01-22 12:37 UTC, merged