fix(Token): allow capturing token's remove button in focus
skbkontur/retail-ui pull request #3337
Opened 2023-12-19 09:09 UTC by JackUait

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-13 13:13 UTC, lossir requested changes

2024-01-13 13:13 UTC, lossir commented on packages/react-ui/components/Token/Token.tsx
> -        tabbable={false}
Это будет сильно ломающим изменением. Ещё до темы2022 табулирования по крестикам не было.

К тому же навигация стрелками и табом станут конфликтовать.
Если нажать `Tab`➞`Enter`, то токен удалиться.
А если `Right`➞`Enter`, то включиться редактирование.

В целом, я считаю правильным поведение, когда ТокенИнпут при табулировании ведёт себя как обычный Инпут.
Иначе, чтобы пронавигироваться через ТокенИнпут в форме, придётся нажимать Таб столько раз, сколько в нём Токенов.

Даже если представить эти Токены вне контекста ТокенИнпута, то табулирование по Токену всё равно не должно проваливаться внутрь на крестик.
Внутри же ТокенИнпута по ним можно навигироваться стрелками, а удалять клавишами delete или backspase.

---

Думаю правильнее всего будет научить компонент `CloseButtonIcon` правильно выключать доступность кнопки при передаче пропа `tabbable={false}`.

2024-02-08 22:29 UTC, JackUait commented on packages/react-ui/components/Token/Token.tsx
> -        tabbable={false}
> Если нажать Tab➞Enter, то токен удалиться.
А если Right➞Enter, то включиться редактирование.

Это нормально и сопоставимо с управлением с помощью мыши:
- При клике на крестик токен удаляется
- При двойном клике по токену включается режим редактирования

> Иначе, чтобы пронавигироваться через ТокенИнпут в форме, придётся нажимать Таб столько раз, сколько в нём Токенов.

Для зрячих пользователей это не критично, а пользователи скринридеров могут пропустить этот раздел, т.к. VoiceOver добавляет новые комбинации клавиш для навигации по сайту

> Даже если представить эти Токены вне контекста ТокенИнпута, то табулирование по Токену всё равно не должно проваливаться внутрь на крестик.

Почему такое ограничение?

> Внутри же ТокенИнпута по ним можно навигироваться стрелками, а удалять клавишами delete или backspase.

Да, это правда, но приводит к двум проблемам:
- Пользователи скрин-ридеров (в целом как и зрячие пользователи) не знают об этом и им нужно об этой возможности как-то сообщить — возможно есть какие-то варианты это сделать, но я с ними не знаком
- Так как навигация с помощью стрелок реализована не с помощью фокуса — скрин-ридер не зачитывает текст токена при навигации с помощью таба. При навигации с помощью сочетаний клавиш VO текст зачитывается, но озвучиваемые действия не выполняются

**Итого:** я бы сказал, что мой вариант можно и нужно дорабатывать (думаю, что это задача для проектировщиков), но в текущем контексте он работает корректнее с точки зрения взаимодействия с ассистивными технологиями

2024-02-08 22:32 UTC, JackUait commented on packages/react-ui/components/Token/Token.tsx
> -        tabbable={false}
**P.S.**
В этом контроле есть ещё много чем заняться с точки зрения доступности и я не тащил все правки в этот пулл-реквест, так как только он про крестик

2024-02-09 05:43 UTC, lossir commented on packages/react-ui/components/Token/Token.tsx
> -        tabbable={false}
Главный поинт в том, что эти изменения ломающие.

Новое поведение однозначно ломает текущие пользовательские сценарии. К тому же может сломаться куча тестов.

Улучшение доступности в контролах не должно делаться в ущерб привычного поведения, исправление которого никто не просил.
Не было ни одного запроса на подобное изменение логики табулирования.

---

Если допустить, что мы решили улучшить доступность в ТокенИнпуте, то предлагаемое поведение кажется довольно сырым:

1. Почему при фокусе на крестик перестаёт работать навигация стрелками?
И пока не протабулируешь все Токены, навигироваться стрелками не сможешь. Получается спорное улучшение доступности удаления Токена сделано в ущерб доступности редактирования Токена.
При этом не очень понятно как дружить Стрелки и Таб.. придётся навигироваться Токен➞Крестик➞Токен➞Крестик?
2. При этом при включении NVDA навигация стрелками своеобразно включается. Например если при фокусе на крестике нажимать стрелки вверх/вниз, то фокус будет перемещаться на соседние крестики, но визуально ничего не поменяется. Это баг или фига NVDA?
3. Почему новое поведение должно включиться сразу для всех, и а не быть скрыто под фичафлагом или пропом?
4. И самый большой вопрос - почему навигация табом фокусируется именно на крестиках?

Например, в mui есть аналог ТокенИнпута, и навигация внутри работает как у нас сейчас, только стрелками:
— https://mui.com/material-ui/react-autocomplete/#limit-tags

Но там же есть и аналог Токенов, и по ним можно навигироваться табом:
— https://mui.com/material-ui/react-chip/#clickable-and-deletable

Ниже, в блоке про доступность, они пишут:
> If the Chip is deletable or clickable then it is a button in tab order. When the Chip is focused (e.g. when tabbing) releasing (`keyup` event) `Backspace` or `Delete` will call the `onDelete` handler while releasing `Escape` will blur the Chip.

По-моему, их вариант доступности выглядит целостнее и поэтому убедительнее.

---

Исходная задача касалась проблем при тестировании. Поэтому в первую очередь стоит исправить именно эту проблему.

Решение же по улучшению доступности требует большей проработки. И это можно делать независимо отдельной задачей.

2024-02-15 00:54 UTC, JackUait commented on packages/react-ui/components/Token/Token.tsx
> -        tabbable={false}
Удалил роль у `Token`, чтобы тесты не ругались

2024-02-15 07:11 UTC, lossir approved these changes

2024-02-19 08:52 UTC, merged

2024-02-20 05:48 UTC, zhzz commented
@lossir @JackUait

Правильно ли я понял, что в итоге [решили](https://github.com/skbkontur/retail-ui/pull/3337#discussion_r1451508617) фокус на крестиках не включать? Если так, то почему в итоге включили? Я уже выпустил 4.20.2 с этими правками. Получается, ломающее изменение? 

Кроме этого заметил такие странности в новой версии:
1. aria-label у крестика отсутствует в теме 22
2. aria-label у крестика содержит `[object Object]`, если в `children` к `Token` придет `ReactElement` 

Все это видно в [песочнице](https://stackblitz.com/edit/react-ui-template-emehnp?file=src%2FApp.tsx).

2024-02-20 06:07 UTC, lossir commented
Я пропустил проглядел удаление `tabbable={false}`, это да.

Касательно `aria-label` я посчитал, что Жене виднее.

2024-02-20 09:28 UTC, JackUait commented
> Правильно ли я понял, что в итоге https://github.com/skbkontur/retail-ui/pull/3337#discussion_r1451508617 фокус на крестиках не включать?

Да, всё так. Я по запарке забыл вернуть `tabbable={false}`

> aria-label у крестика отсутствует в теме 22

Элементам без роли нельзя задавать `aria-label` — не стал костылить его через `eslint-disable`, чтобы пользовательские тесты снова не ругались

> aria-label у крестика содержит [object Object], если в children к Token придет ReactElement

Я не учёл этот сценарий

2024-02-20 09:46 UTC, JackUait commented
Исправил проблемы в #3361