fix(ComboBox): ignoring new value after losing focus
skbkontur/retail-ui pull request #3340
Opened 2023-12-21 08:17 UTC by Funkicide

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-23 09:48 UTC, zhzz requested changes

2024-01-23 09:48 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +            textValue: getValueString(props.value, props.valueToString) || state.textValue,
Я думаю стоит также сбрасывать режим `editing` и другие соответствующие поля, как при `ValueChange`. Иначе возможны непонятные состояния, например, когда пользователь что-то введет, бросит, случится DidUpdate с новым `value`, потом фокус. Если оставить editing, то в инпуте появится старый пользовательский текст. Хотя разработчик засетил новое значение. 

Кажется, установка нового value должна быть эквивалентом reset.

2024-02-02 14:28 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +            textValue: getValueString(props.value, props.valueToString) || state.textValue,
Обновил решение, дополнил тесты. Конфликтующие тесты пометил.

2024-02-27 10:06 UTC, zhzz requested changes

2024-02-27 10:06 UTC, zhzz commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +      userEvent.type(screen.getByRole('textbox'), 'bar');
В общем случае изменение пропа value при открытой выпадашке не связано напрямую с `onInputValueChange`. Проп может просто поменяться из вне. Тогда содержимое выпадашки может оказаться отличным от того, что получается при вводе текста в инпут (как в этом тесте), и не будет соответствовать новому value. А это важно, я писал в задаче IF-1643.

2024-02-27 10:06 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +          };
Предлагаю сделать шаг назад и вспомнить, зачем нужен режим editing. 

Он для ввода и сохранения данных, которые печатает пользователь. Для этого нужно рендерить инпут. Если пользователь что-то ввел, и не было особых событий явного изменения valuе, то пользовательский введенный текст сохраняется и инпут продолжает рендериться.

В этой задаче мы к особым событиям явного изменения value добавляем изменение value через проп. Это значит, что в случае изменения пропа, пользовательский ввод уже сохранять не нужно. А нужно корректно отрендерить новый value. 

Корректный рендер value включает обновление текста в инпуте и содержимого выпадашки, если она открыта. А если Комбобокс не в фокусе, то вместо инпута нужно рендерить результат renderValue.

2024-03-04 06:54 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +          };
Переделал.

2024-03-04 06:54 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +      userEvent.type(screen.getByRole('textbox'), 'bar');
Поменял тест.

2024-03-04 06:55 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +      expect(await screen.findByTestId(MobilePopupDataTids.root)).toBeInTheDocument();
Решил сделать тест похожим на кейс из задачи.

2024-03-04 07:03 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +    });
Подумал что стоит сделать, т.к. поведение отличается в разных режимах. Убрал.

2024-03-05 11:45 UTC, zhzz commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +      drawArrow={false}
Эти пропы нужны для примера? Примеры должны быть минималистичны и содержать только то, что необходимо. Это касается и примеров в тестах.

2024-03-05 11:47 UTC, zhzz commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +      await changeValue();
`changeValue` используется только в одном месте. Стоит ли выносить отдельную функцию?

2024-03-05 11:54 UTC, zhzz commented
На счет renderAddButton тут делать ничего не нужно. Я заведу отдельную задачу.

2024-03-06 09:25 UTC, Funkicide commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +      drawArrow={false}
Убрал лишние пропы в тестах и доке

2024-03-06 09:25 UTC, Funkicide commented on packages/react-ui/components/ComboBox/__tests__/ComboBox-test.tsx
> +        <ReactUIFeatureFlagsContext.Provider value={{ comboBoxFixValueChange: true }}>
Переиспользовал компонент.

2024-03-06 09:25 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +      break;
Исправил.

2024-03-06 09:58 UTC, Funkicide commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +В примере ниже, при нажатии на кнопку "Обновить" без флага, в функции handleValueChange приходилось бы дополнительно вызывать метод Combobox'a reset. А при смене value через onInputValueChange выпада
Обновил описание.

2024-03-06 11:13 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +              items: null,
Убрал закрытие и очищение.

2024-03-07 07:37 UTC, zhzz requested changes

2024-03-07 07:37 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> -              inputChanged: false,
`inputChanged` поле все таки относится к режиму editing, поэтому его тоже нужно тут сбрасывать.

2024-03-07 07:37 UTC, zhzz commented on packages/react-ui/components/ComboBox/ComboBox.md
> -При изменении значения и блюре `ComboBox` остается в состоянии `editing` и не дает изменить значение через проп `value`. Поэтому, для того чтобы задать новое значение, необходимо вызвать метод `reset
Круто что заметил уже неактуальный пример. Но его можно обновить и оставить как демонстрацию метода `reset`. Метод все еще может быть полезен, если нужно сбросить контрол без изменения value.

2024-03-07 07:37 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +        const nextTextValue = getValueString(props.value, props.valueToString) ?? state.textValue;
Забыл в прошлый раз уточнить, зачем нужно делать `?? state.textValue`?

2024-03-07 07:39 UTC, zhzz commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +              items: null,
И еще `inputChanged`, но про него речи не было

2024-03-07 10:24 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +        const nextTextValue = getValueString(props.value, props.valueToString) ?? state.textValue;
Перепроверил, не нужно. Изначально добавил, чтобы в ситуации, когда при `searchOnFocus=false` и изменении `value` через `onInputValueChange`, данные в инпуте не обновлялись корректно. Но это решилось правильной передачей нового `value`.

2024-03-07 10:24 UTC, Funkicide commented on packages/react-ui/components/ComboBox/ComboBox.md
> -При изменении значения и блюре `ComboBox` остается в состоянии `editing` и не дает изменить значение через проп `value`. Поэтому, для того чтобы задать новое значение, необходимо вызвать метод `reset
Переделал пример.

2024-03-07 10:25 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> -              inputChanged: false,
Добавил сброс `inputChanged`

2024-03-07 10:25 UTC, Funkicide commented on packages/react-ui/internal/CustomComboBox/CustomComboBoxReducer.tsx
> +              items: null,
Добавил сброс inputChanged

2024-03-11 09:04 UTC, zhzz commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +### comboBoxFixValueChange
Обратил внимание, что флаг имеет слишком общее название. У нас есть [соглашение](https://github.com/skbkontur/retail-ui/blob/e4d8a5d771cd37de9e7685e4cc0950ef13b4c200/contributing.md#%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE-%D1%84%D0%B8%D1%87%D0%B0-%D1%84%D0%BB%D0%B0%D0%B3%D0%B0%D0%BC) как именовать флаги. Чем конкретнее название, тем оно более говорящее и меньше вероятность пересечься по смыслу с другим флагом.

2024-03-12 07:04 UTC, merged