fix(Button): use=link prevents action of parent link
skbkontur/retail-ui pull request #3344
Opened 2023-12-26 19:56 UTC by JackUait

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-13 10:48 UTC, lossir requested changes
Думаю, этот ПР стоит закрыть.

Изначальная проблема исходит из неправильного использования компонентов.
И исправляется простой перестановкой кнопки внутрь тултипа, а не наоборот.

2024-02-08 08:29 UTC, zhzz commented
> Думаю, этот ПР стоит закрыть.
> 
> Изначальная проблема исходит из неправильного использования компонентов. И исправляется простой перестановкой кнопки внутрь тултипа, а не наоборот.

Проблема же не только в примере с тултипом. Описан более общий кейс с оборачиванием кнопки с use="link" в ссылку. Да, это мутно и непонятно, почему не взять сразу Link. Но, если посмотреть на причину поломки, то уверенно можно сказать, что она на нашей стороне - мы не до конца отключили Link, положив его внутрь Button.

Это еще более заметно на [другой проблеме](https://github.com/skbkontur/retail-ui/pull/3355), у которой та же причина.

И раз теперь мы это знаем, то нет причин не фиксить . Тем более, что сценариев уже несколько, и могут быть еще.

По поводу решения в этом ПР. Не думаю что нам нужен для этого новый специфичный проп. Кажется, тут лучше отключить обработку кликов вообще. Например, навесив класс с `pointer-events: none` снаружи.

Так или иначе, у нас появилось два дублирующих ПРа. Я пока склоняюсь в пользу #3355. В этом можно оставить только тест. Или докинуть тест в другой ПР, а этот закрыть.

2024-02-08 09:49 UTC, lossir commented
В контексте пары мутных сценариев, с оборачиваниями КнопокСсылок в Ссылки и с Тултипом, я увидел только "спорное место" в нашем коде — почему `Link` ведёт себя именно так, и почему это проблема для `Button use=link`?

Решение с секретным пропом только добавляло спорности в наш код. При этом оба мутных кейса можно было решить на месте, без каких-либо доработок с нашей стороны.

Именно поэтому я и предложил закрыть ПР и написал пример в слак.

---

Но на момент написания моего комментария ещё не было [второго кейса](https://github.com/skbkontur/retail-ui/pull/3355), поэтому мне не с чем было обобщить и найти взаимосвязь.

По поводу конкретного решения с `pointer-events: none`  на первый взгляд должно сработать.
Отмечу только, что это правило останавливает события только если установлено непосредственно на `target` события.

И, вероятно, в компоненте `Link` надо будет всем элементам добавлять это правило, чтобы всё норм работало.

2024-02-08 22:49 UTC, JackUait commented
В целом меня устраивают оба решения

С моей точки зрения к обоим решениям есть вопросы, но для полностью корректного решения требуется более фундаментальный подход и гораздо больше времени — если вам больше нравится решение с `pointer-events: none` то можем оставить его

2024-02-09 11:14 UTC, JackUait commented
Решили закрыть в пользу #3355

2024-02-09 11:14 UTC, closed without merging