fix: globalObject.isInstanceOf in IE 11
skbkontur/retail-ui pull request #3350
Opened 2024-01-12 13:19 UTC by Funkicide

## Проблема

В IE 11 внутри функции `isInstanceOf` `typeof` определяет конструкторы `Element`, `Node`, `MouseEvent` и другие как объекты. Хотя в хроме и других браузерах - как функции.
## Решение

Как я понял, IE 11 не поддерживает фичи ES6, в том числе классы. Проверка, является ли поле `constructor` прокинутого класса функцией, вместо проверки самого класса решило проблему. Сделал исправленную версию функции isInstanceOf  в библиотеке.

Отдельным комитом добавил фикс проверки, где испльзовалось определение isBrowser вместо вызова.
## Ссылки

fix [IF-1576](https://yt.skbkontur.ru/issue/IF-1576)
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-15 12:42 UTC, zhzz requested changes

2024-01-15 12:42 UTC, zhzz commented on packages/react-ui/lib/isInstanceOfForIE11.ts
> Как я понял, IE 11 не поддерживает фичи ES6, в том числе классы. Проверка, является ли поле constructor прокинутого класса функцией, вместо проверки самого класса решило проблему.

Дело не в этом. Даже в ES6 классы под капотом все еще являются функциями.

```js
typeof (class A {}) === 'function' // true
```

В твоем варианте проблему решило то, что поле `constructor` ["есть"](https://developer.mozilla.org/en-US/docs/Glossary/Primitive#:~:text=Primitives%20have%20no%20methods%20but%20still%20behave%20as%20if%20they%20do) почти у всего в js, в том числе у объектов, функций, примитивов.

```js
typeof '1'.constructor //  'function'
typeof (2).constructor //  'function'
typeof {}.constructor //  'function'
typeof (() => {}).constructor //  'function'
```

Поэтому, сейчас `isInstanceOfForIE11` просто не делает разницы между объектом и функцией. Но это не совсем корректно, потому что примитивы тоже теперь удовлетворяют этому условию. Это, теоретически, в нетайпскриптовом проекте, может привести к ошибке.

```js
({}) instanceof {} // TypeError: Right-hand side of 'instanceof' is not callable
({}) instanceof 1 // TypeError: Right-hand side of 'instanceof' is not an object
```

Еще, я нашел [полный алгоритм](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance#description) работы `instanceof`. Он все таки иногда подразумевает работу и с объектами. Поэтому, кажется, что отсылка к IE11 в названии метода уже не уместна.

Похоже нам остается только один путь: попытаться выполнить `instance instanceof constructor`, и посмотреть, не вылетела ли ошибка.

2024-01-25 10:48 UTC, lossir requested changes

2024-01-25 10:48 UTC, lossir commented on packages/react-ui/lib/isInstanceOf.ts
> +}
По-моему тут 2 странных решения.

Во-первых: ошибка игнорируемая директивой `@ts-expect-error` не соответствует своему комментарию. К тому же можно обойтись вовсе без неё.

Ожидается следующая ошибка тайпскрипта:
```diff
-The right-hand side of an 'instanceof' expression must be either of type 'any',
-a class, function, or other type assignable to the 'Function' interface type,
-or an object type with a 'Symbol.hasInstance' method.
```
Фактически здесь перечисляются допустимые типы, предусмотренные работой самого оператора `instanceof`.

В целом тип аргумента `constructor` попадает в это множество. Выбивается только `undefined`.
И именно `undefined` вызывает ошибку, которую глушит `@ts-expect-error`.
Т.е. комментарий к `@ts-expect-error` не отражает суть его применения.

Директиву можно просто убрать, если добавить явную проверку на `undefined`, и сразу возвращать `false`.

---

Во-вторых: применение `try/catch` кажется излишним и нецелесообразным. 

Вариант `undefined` для `constructor` мы можем обработать обычным `if/else`.
Тут всё прозрачно: мы явно допускаем `undefined` - мы явно его и обрабатываем.

Остаются только случаи, когда реальный тип аргументов отличается от типизации TS, и тогда может возникнуть ошибка.
Но по такой логике нам придётся каждый хелпер оборачивать в `try/catch`. Иначе не понятно почему здесь мы решили пользователя обезопасить от самого себя, а в других местах не стали.

Как и говорит Егор: «изначальная суть [хелпера] - разрешить правому операнду быть `undefined`».

В итоге код хелпера я вижу как-то так:
```ts
export function isInstanceOf<C extends new (...args: any) => any>(
  instance?: unknown,
  constructor?: C,
): instance is InstanceType<C> {
  return constructor ? instance instanceof constructor : false;
}
```

2024-01-26 08:14 UTC, lossir approved these changes

2024-01-26 11:02 UTC, zhzz approved these changes

2024-01-26 11:03 UTC, zhzz commented on packages/react-ui/lib/isInstanceOf.ts
> +}
Да, я как-то упустил из виду `@ts-expect-error `

2024-01-26 11:04 UTC, merged