feat(Tooltip): new prop 'showDelay'
skbkontur/retail-ui pull request #3354
Opened 2024-01-23 14:02 UTC by Funkicide

## Проблема

Надо было дотащить ПР, внеся правки по необходимости.
## Решение

Втащил ПР, добавив тесты на новую логику.
## Ссылки

Ссылка на оригинальный [ПР](https://github.com/skbkontur/retail-ui/pull/3349)

Close [IF-1618](https://yt.skbkontur.ru/issue/IF-1618)
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ✅ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-25 07:16 UTC, HelenaIsh requested changes

2024-01-25 07:16 UTC, HelenaIsh commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +  showDelay?: number;
я бы назвала проп `delayBeforeShow`.
Во-первых, для консистентности с другими компонентами (например [GlobalLoader](https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/components/GlobalLoader/GlobalLoader.tsx#L15) или [Loader](https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/components/Loader/Loader.tsx#L53)), а во-вторых, он кажется более понятным для восприятия

2024-01-25 07:16 UTC, HelenaIsh commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    this.hoverTimeout = globalObject.setTimeout(this.open, this.props.showDelay ?? Tooltip.delay);
В принципе, здесь нет ошибок. Но кажется, что правильнее будет добавить дефолтное значение самому пропу через `defaultProps`. Например, если мы в будущем будем использовать проп `showDelay` в другом месте, то нам не нужно будет вспоминать, что нужно проверить дефолтное значение через `Tooltip.delay`. 
Чтобы не было разногласий со статическим полем `delay` я бы вынесла значение 100 в константу (например как [здесь](https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/components/Hint/Hint.tsx#L19)) и использовала бы для статического поля и для дефолтного значения

2024-01-25 08:59 UTC, Funkicide commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +  showDelay?: number;
Переименовал.

2024-01-25 08:59 UTC, Funkicide commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +    this.hoverTimeout = globalObject.setTimeout(this.open, this.props.showDelay ?? Tooltip.delay);
Переделал.

2024-01-25 09:55 UTC, HelenaIsh commented on packages/react-ui/components/Tooltip/Tooltip.tsx
> +  showDelay?: number;
в документации осталось поправить

2024-01-25 11:17 UTC, HelenaIsh approved these changes

2024-01-29 06:41 UTC, zhzz approved these changes
👍

2024-01-29 06:41 UTC, merged