fix(Button):
skbkontur/retail-ui pull request #3355
Opened 2024-01-29 07:08 UTC by Funkicide

## Проблема

В теме 22, если использовать кнопку-ссылку <Button use={"link"} type={"submit"}> внутри формы, то на нажатие submit не срабатывает.

## Решение

В 22 теме кнопка-ссылка использует внутри компонент Link, который если не задан href вызывает event.preventDefault.
Задал шаблонный href в Link для кнопки-ссылки.
## Ссылки

Fix [IF-1627](https://yt.skbkontur.ru/issue/IF-1627)
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-01-31 10:32 UTC, HelenaIsh approved these changes

2024-02-01 09:38 UTC, zhzz requested changes

2024-02-01 09:38 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +            href={isSubmit ? '#!' : ''}
Не приведет ли теперь нажатие на ссылку к переходу по урлу `/#!`? Можно посмотреть в нашей [доке](https://tech.skbkontur.ru/react-ui/#/Components/Link), как это выглядит в SPA с [hashbang-роутингом](https://reactrouter.com/en/main/router-components/hash-router).
```
<Link href="#!">Обычная ссылка</Link>
```

2024-02-01 09:38 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> Добавлены тесты на все изменения
  ...
  ✅ нерелевантно

А почему тесты в данном случае нерелевантны?

2024-02-08 06:55 UTC, zhzz requested changes

2024-02-08 06:55 UTC, zhzz commented on packages/react-ui/components/Button/Button.tsx
> +            href={isSubmit ? '.' : ''}
Разницы с предыдущим вариантом особо нет. Все равно url при переходе может поменяться. Правда я не заметил в прошлый раз, что тут на ссылке еще есть проп `as="span"`. Поэтому перехода по факту не будет. 

Но в любом случае это костыльное решение. Манипуляция с `href`, который нам тут самим не нужен. Плюс неочевидная логика: почему только `isSubmit`? На самом деле есть еще `type="reset"`, который тоже сломан.

Есть более правильное решение, если посмотреть на проблему шире. По факту, нам от ссылки тут нужен только ее внешний вид, без логики, которая мешает. Значит в идеале нам бы просто эту ссылку отключить, чтобы она вообще никак не вмешивалась в нажатие на кнопку. 

Для отключения у Link есть проп `disabled`, но он меняет ее внешний вид. А еще есть [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#disabling_pointer_events_on_a_single_link), способный отключить обработку нажатий на чем угодно.

2024-02-08 06:55 UTC, zhzz commented on packages/react-ui/components/Button/__tests__/Button-test.tsx
> +    userEvent.click(screen.getByTestId(LinkDataTids.root));
Лучше использовать [findByText](https://testing-library.com/docs/example-findbytext/), чтобы не завязываться на текущую реализацию кнопки.

2024-02-13 10:14 UTC, zhzz submitted a review, later dismissed

2024-02-13 10:18 UTC, merged