fix(Hint): fix hint jumping near screen edge
skbkontur/retail-ui pull request #3356
Opened 2024-02-02 10:24 UTC by SchwJ

## Проблема

Hint странно себя ведет у края окна браузера: 
если anchorElement находится в таком положении, что hint не вмещается ни в одно из доступных положений

## Решение

Выяснилось, что у Popup'а неправильно считается длина: берется getBoundingClientRect().width, который возвращает видимую длину в рамках viewport, а не полную ширину Popup'а.

## Ссылки

[#606](https://yt.skbkontur.ru/issue/IF-606/Hint-Stranno-sebya-vedet-u-kraya-okna-brauzera) -- Hint: Странно себя ведет у края окна браузера

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

3. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

4. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

5. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-03-06 10:22 UTC, zhzz requested changes

2024-03-06 10:22 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +        ref={mergeRefs([this.refForTransition, this.refPopupContentElement])}
Мы в итоге и элемент меняем и способ вычисления его размеров? Как эти две правки соотносятся? Нужны ли сразу обе?

2024-03-06 10:22 UTC, zhzz commented on packages/react-ui/lib/featureFlagsContext/FEATUREFLAGSCONTEXT.md
> +### hintFixJumpingNearScreenEdge
А что в итоге с фича-флагом? Он нигде не используется и ни на что не влияет.

2024-03-11 05:58 UTC, SchwJ commented on packages/react-ui/internal/Popup/Popup.tsx
> +        ref={mergeRefs([this.refForTransition, this.refPopupContentElement])}
К моменту ревью были сделаны правки:
1) client-размеры заменены на scroll-размеры
2) у ссылка refPopupElement изменилось место прикрепления и изменилось имя на refPopupContentElement
3) в Hint добавлена логика перерисовки в том случае, когда хинт не находится целиком во viewport

Сейчас разобралась, что 1-ая правка не обязательна и для верного рассчета размеров достаточно изменить место прикрепления ссылки (сделать 2-ую правку). 3-я правка вынесена в [отдельный PR](https://github.com/skbkontur/retail-ui/pull/3369), так как закрывает немного другую [задачу](https://yt.skbkontur.ru/issue/IF-1610/Hint-izmenyat-polozhenie-esli-ne-vlezaet-na-ekran)

2024-03-13 10:53 UTC, zhzz approved these changes

2024-03-13 10:54 UTC, merged