feat(Popup): add mobileOnBlurReques prop
skbkontur/retail-ui pull request #3375
Opened 2024-03-13 11:16 UTC by Funkicide

## Проблема

При использовании `RenderLayer` с лежащим внутри его Popup'ом, на мобильных устройствах (в таком случае отрисовывается MobilePopup) не работают пропы RenderLayer'а: `onFocusOutside` и `onClickOutside`.

Внутри `MobilePopup` уже используется `RenderLayer`, но у него было пропа `onFocusOutside`.
## Решение

Добавил проп `mobileOnBlurRequest` в `Popup`, который прокидывается в `onFocusOutside` внутри `MobilePopup`. Решил отделить `mobileOnBlurRequest` от `mobileOnCloseRequest` на случай, если логика в обработчиках будет разная.
## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ✅ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-03-20 10:44 UTC, zhzz requested changes
Решение не совсем корректное. В результате в пользовательском кейсе `onFocusOutside` и `onClickOutside` должны одинаково работать и для десктопной и для мобильной версии Popup. Отдельный проп прокидывать для этого не должно быть нужно.

Дело не в RenderLayer внутри MobilePopup. Он никак не влияет. Дело именно в том, что onFocusOutside и onClickOutside наружнего RenderLayer почему-то не работают так, как ожидается (как на десктопе) вокруг Popup в мобильном режиме.

Ключ, скорей всего в механизме rootNode (см. [#2518](https://github.com/skbkontur/retail-ui/pull/2518), [#2873](https://github.com/skbkontur/retail-ui/pull/2873)). У Popup есть секция юнит-тестов на него. Думаю, если завести их в мобильном режиме, то проблема с RenderLayer тоже починится.

2024-03-26 10:56 UTC, zhzz requested changes
Много чужих изменений в ветке. Похоже вместо `next` был подлит `master`.

2024-03-29 06:48 UTC, zhzz requested changes

2024-03-29 06:48 UTC, zhzz commented on packages/react-ui/internal/Popup/__tests__/Popup-test.tsx
> +    expect(rootNode).not.toBeNull();
Тесты в десктопном и мобильном режимах должны работать одни и те же. Т.е. тут должен быть `null`.

2024-03-29 07:27 UTC, Funkicide commented on packages/react-ui/internal/Popup/__tests__/Popup-test.tsx
> +    expect(rootNode).not.toBeNull();
Но в десктопном и мобильном режимах по-разному отрисовывается контент попапа. На десктопе контент зависит от `location` и рендер контейнер появляется только при открытии. А в моб. режиме такой зависимости и рендер контейнер появляется при монтировании. Делать зависимость в моб. режиме от переменной `location`, хотя она в нём не используется, как-то странно.

2024-03-29 07:57 UTC, zhzz commented on packages/react-ui/internal/Popup/__tests__/Popup-test.tsx
> +    expect(rootNode).not.toBeNull();
Надо сделать так, чтобы, не меняя структуру компонентов, вместо рендер контейнера в rootNode попадал null. Это предусмотрено текущим механизмом rootNode и работает в десктопной версии.

2024-03-29 08:53 UTC, Funkicide commented on packages/react-ui/internal/Popup/__tests__/Popup-test.tsx
> +    expect(rootNode).not.toBeNull();
Поправил.

2024-03-29 10:20 UTC, zhzz commented on packages/react-ui/internal/Popup/__tests__/Popup-test.tsx
> +    expect(rootNode).not.toBeNull();
А нельзя ли теперь переиспользовать одни и те же тесты для обоих сценариев, а не дублировать?

2024-04-01 06:11 UTC, merged