fix(): remove focus when "disabled" state is changes
skbkontur/retail-ui pull request #3378
Opened 2024-03-20 04:35 UTC by SchwJ

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-03-29 05:32 UTC, zhzz requested changes
Желательно починить саму причину возникновения проблемы, т.е. невызывающийся `onBlur` на инпутах, а не ее следствие в виде несбрасывающегося флага в стейте.

Таким образом мы сможем избежать дублирования одной и той же логики в 9 компонентах. Легче переиспользовать решение в будущем в других подобных местах. И написать более лаконичные тесты.

2024-04-17 05:47 UTC, mshatikhin commented
FocusControlWrapper стал зависимым от CommonWrapper из-за того что CommonWrapper неявно прокидывает и перетирает className, style и дата атрибуты в children

2024-04-18 05:41 UTC, mshatikhin commented
Использование CommonWrapper внутри FocusControlWrapper оправдано тем, что CommonWrapper не ожидает внутри себя других врапперов, и мерджит className, style, ref., в случае когда натыкается на компонент обертку, а не на рутовый компонент ноду, эта логика ломается и перестают склеиваться className, style и прочее.. Компромиссный вариант, это использовать во всех компонентах обертках еще один CommonWrapper который будет выполнять логику склейки.

Так уже сделано в других компонентах, например в:
RenderLayer.tsx

Но при этом решение по дизайну не очень красивое и очевидное, лучшим решением было бы вообще не использовать компоненты обертки, а например использовать хуки для переиспользования логики.

Плюсик к задаче на выпиливание CommonWrapper в виде обертки
https://yt.skbkontur.ru/issue/IF-221/Izbavlenie-ot-CommonWrapper-pod-voprosom

2024-04-19 04:37 UTC, lossir commented on packages/react-ui/internal/FocusControlWrapper/FocusControlWrapper.tsx
> +    </CommonWrapper>
Вариант, просто смотреть не проп `disabled` внутри каждого проблемного контрола, мне нравится намного больше.

Нового кода в каждом контроле будет почти столько же, как и сейчас, но при этом не будет ещё одной сложной обёртки, внутри которой ещё одна сложная обёртка, которую мы вообще думали выпилить.

2024-04-19 06:30 UTC, mshatikhin commented on packages/react-ui/internal/FocusControlWrapper/FocusControlWrapper.tsx
> +    </CommonWrapper>
Частично верно, но, сначала решили задачу "в лоб" и натыкали "if disabled", но такое решение плохо поддерживаемое - разносит логику во много мест, легко ошибиться. Решение с оберткой инкапсулирует эту логику, и позволяет вносить правку в одно место, и тестировать это одно место. 
В целом про обертки я тоже их дико не люблю, начиная от того что это лишний компонент в дереве, заканчивая артефактами пробрасывания пропсов через них. Лучшим решение было бы вынести хук и использовать его везде где нужно, (и коммон враппер и фокус враппер можно спокойно переписать на хуки), но пока это только планы на будущее, поэтому компонент обертка на данный момент это компромисс между поддерживаемостью, сложностью и качеством.

2024-04-19 06:45 UTC, zhzz reviewed
Я считаю, что подход со сосредоточением логики в одном месте, и переиспользованием ее в других - выгодный. Это принцип DRY со всеми вытекающими плюсами. И он реализован в текущем решении. Но есть налет неочевидности и сложности в получившемся механизме управления фокусом в каждом конечном компоненте. 

```jsx
<FocusControlWrapper disabled={disabled} onBlurWhenDisabled={this.resetFocus}>
    <input onFocus={this.setFocus} onBlur={this.resetFocus} />
</FocusControlWrapper>
```

Возможно, решение можно упростить, если всю логику управления фокусом полностью скрыть обертке, таким образом избавив разработчика от необходимости знать и понимать про кейс с onBlurWhenDisabled.

```jsx
<FocusController disabled={disabled} onFocusChange={this.handleFocusChange}>
    <input />
</FocusController>
```

2024-04-19 06:55 UTC, zhzz commented on packages/react-ui/components/__stories__/focus.stories.tsx
> +};
Отдельный вопрос с тестами. Они тоже получились довольно узкими, специфичными и неочевидными.

Кажется, мы либо должны ограничиться тестированием только обертки. Либо написать полноценный тест на фокус в каждом компоненте.

Иначе, например, этот тест продолжит проходить, если сломается установка фокуса на onFocus, или сброс фокуса на onBlur.

2024-04-19 11:48 UTC, lossir commented on packages/react-ui/internal/FocusControlWrapper/FocusControlWrapper.tsx
> +    </CommonWrapper>
>  ...натыкали "if disabled", но такое решение плохо поддерживаемое - разносит логику во много мест, легко ошибиться — @mshatikhin 

> Я считаю, что подход со сосредоточением логики в одном месте, и переиспользованием ее в других - выгодный — @zhzz 

Глобально я согласен, что выносить повторяющий код выгоднее, чем не выносить. Но надо учитывать и другие факторы, типа связность между независимыми компонентами, сложность реализации, костыли и т.п.

Хорошо, если логику можно реализовать через чистую функцию. Если опустить условности, то такую логику конечно стоит попытать инкапсулировать и переиспользовать.

В текущем же случае, не мой взгляд, есть и ненужная связность, и сложность, и костыль. И выходит что выгода от переиспользования конкурирует с рисками от этих факторов. На мой взгляд риски заметно перевешивают выгоду.

Добавить простой и понятный `if disabled` в 8 компонентов считаю правильным.

---

Но вы оба за обёртку в том или ином виде. Двое против одного) 
У меня кончились аргументы, ну и мб я просто не выкупаю.

2024-04-22 04:13 UTC, mshatikhin commented on packages/react-ui/components/__stories__/focus.stories.tsx
> +};
эти тесты кажется можно удалить, тк логика покрыта юнит тестами, а рисование обводки проверяется в других тестах

2024-04-22 04:21 UTC, mshatikhin commented
> ```js
> <FocusController disabled={disabled} onFocusChange={this.handleFocusChange}>
>     <input />
> </FocusController>
> ```

получается не очень API, 
1) нам нужно прокидывать FocusEvent вверх по дереву, а он будет не всегда (в случае с багом)
2) onFocusChange породит ифы на стороне каждого компонента, мне не нравится такой вариант,
3) удалить его когда переедем на хуки будет сложнее, придется разобрать все ифы вместо того чтобы просто обертку удалить

2024-04-23 06:14 UTC, mshatikhin commented on packages/react-ui/components/__stories__/focus.stories.tsx
> +};
выпилил

2024-04-23 06:20 UTC, zhzz commented
> получается не очень API,
> 
> нам нужно прокидывать FocusEvent вверх по дереву, а он будет не всегда (в случае с багом)
> onFocusChange породит ифы на стороне каждого компонента, мне не нравится такой вариант,
> удалить его когда переедем на хуки будет сложнее, придется разобрать все ифы вместо того чтобы просто обертку удалить
> ```

Судя по аргументам, мне не удалось до конца донести свою идею. Оставлю на всякий случай более полноценный пример:

```tsx
const [focus, setFocus] = React.useState(false);
const inputClassName = cx({ focus });

<FocusController disabled={disabled} onFocusChange={setFocus}>
    <input className={inputClassName} onFocus={props.onFocus} onBlur={props.onBlur} />
</FocusController>
```

Т.е. если нам нужен FocusEvent, мы по прежнему можем использовать обычные багованные onFocus/onBlur напрямую на input. Прокидывать его руками не нужно. 

Также, избавляться от решения при переходе на хуки было бы вообще не нужно. Разве что тоже заменить на хук. Ведь это не костыль, а вполне нормальная переиспользуемая логика.

Но, попробовав применить свой подход в реальности я увидел, что в компонентах есть более сложные сценарии работы с фокусом (InpulLikText). Их можно было бы тоже реализовать или отрефакторить, но это уже выходит далеко за рамки текущей задачи. Можно оставить идею на будущее.

В итоге я согласен с текущим решением Миши.

2024-04-23 07:25 UTC, zhzz approved these changes

2024-04-24 11:07 UTC, merged