fix(Token): correct render with conditional children
skbkontur/retail-ui pull request #3404
Opened 2024-04-11 15:04 UTC by Funkicide

## Проблема

Если условно рендерить что-то внутри `Token`, то появляется ошибка.
## Решение

Добавил в хелпер `getChildrenText` возврат пустой строки на boolean.
## Ссылки

Fix [IF-1734](https://yt.skbkontur.ru/issue/IF-1734)
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-04-15 09:48 UTC, zhzz requested changes

2024-04-15 09:48 UTC, zhzz commented on packages/react-ui/components/Token/__tests__/Token-test.tsx
> +    });
Поскольку проблема не на стороне токена, а в утилите, которую он использует, то тест должен быть написан в утилите.

2024-04-15 09:48 UTC, zhzz commented on packages/react-ui/lib/utils.ts
> +
В целом работает. Но я случайно обнаружил полный аналог функции `getChildrenText` тут `lib/reactGetTextContent.ts`. Он более корректно написан (с использованием isReactElement) и имеет тесты. Лучше переехать на него, а от `getChildrenText` избавиться.

2024-04-15 11:34 UTC, Funkicide commented on packages/react-ui/lib/utils.ts
> +
Переехал, тест добавил, версию Жени удалил.

2024-04-16 06:07 UTC, zhzz requested changes

2024-04-16 06:07 UTC, zhzz commented on packages/react-ui/lib/__tests__/reactGetTextContent-test.tsx
> +  });
Почему не сделать тест таким же, как все остальные тут? 
Он не должен проверять что-то специфическое, типа "не выбрасывает ошибку при условном рендеринге". По сути, он должен проверить, что функция корректно отрабатывает, если ей придет boolean на вход.

2024-04-16 08:03 UTC, Funkicide commented on packages/react-ui/lib/__tests__/reactGetTextContent-test.tsx
> +  });
Сделал.

2024-04-16 08:08 UTC, zhzz approved these changes

2024-04-16 08:11 UTC, merged