fix(Calendar): update period
skbkontur/retail-ui pull request #3415
Opened 2024-04-25 10:49 UTC by zhzz

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-05-02 12:38 UTC, mshatikhin requested changes

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/Calendar.md
> +Доступен публичный компонет `CalendarDay` и интерфейс его пропов `CalendarDayProps`. Может быть полезен для использования вмсете с пропом `renderDay`.
вмсете

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +    'MaskedInput',
MaskedInput лишнее кажется

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +  isToday: boolean;
возможно лучше сделать опциональными ?:boolean; для пользователей чуть проще будет, но вкусовщина

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +      const day = children ?? date.date;
странное название day, это же элемент по сути  , ну или caption Назвать)

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +              [styles.weekend(theme)]: Boolean(isWeekend),
тут как будто Boolean не нужен

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +export const CalendarDay: React.FC<CalendarDayProps> = memo(
еще наверное всякие CalendarDay.displayName нужно докинуть

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    if (this.props.onValueChange) {
в коде выше такой же вызов сделан через this.props.onMonthChange?.(value)

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/CalendarDateShape.ts
> +export const fromString = (dateString: string): CalendarDateShape => {
на новые функции нет юнит тестов

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/DayCellView.tsx
> +    <div onClick={handleClick} className={cx(styles.cell(theme))}>
cx точно нужен ?

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/Month.tsx
> +      <div key={`leadgin_${i}`} className={cellStyles.cell(this.theme)} />
зачем префиксы? еще и с опечатками

2024-05-02 12:38 UTC, mshatikhin commented on packages/react-ui/components/Calendar/Calendar.tsx
> +    if (this.props.onMonthChange) {
сверху деструктурируются пропсы, давай onMonthChange от туда и возьмем

2024-05-02 12:57 UTC, mshatikhin commented on packages/react-ui/components/Calendar/__stories__/Calendar.stories.tsx
> +  const dayInPediodStyles = useMemoObject({
Pediod :)

2024-05-03 08:09 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +export const CalendarDay: React.FC<CalendarDayProps> = memo(
`displayName `уже проставляется внутри `forwardRefAndName`

2024-05-03 08:13 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDateShape.ts
> +export const fromString = (dateString: string): CalendarDateShape => {
Добавил. Также заметил и поправил бажок во `fromString`.

2024-05-03 08:23 UTC, zhzz commented on packages/react-ui/components/Calendar/Month.tsx
> +      <div key={`leadgin_${i}`} className={cellStyles.cell(this.theme)} />
Фактически, префиксы тут роли не играют. Наверное, были для уверенности добавлены.

2024-05-06 11:51 UTC, lossir requested changes

2024-05-06 11:51 UTC, lossir commented on packages/react-ui/components/Calendar/CalendarDateShape.ts
> +};
Этот хелпер тоже повторяет возможности InternalDate
```ts
new InternalDate().setComponents({ date, month, year }).toString({ withPad: true })
```

2024-05-06 11:51 UTC, lossir commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +        </button>
Стоит добавить глобальные классы на элементы.

С текущей вёрсткой не получиться без костылей сделать внешний вид по макетам.
Проблема в "квадратных" днях периода при наведении.

![image](https://github.com/skbkontur/retail-ui/assets/2708211/7294e91d-1222-4272-8bcb-35e04f8ef908)

<details><summary>Макеты</summary>

https://www.figma.com/file/6doJJodEzmfI6qrwU7dd9l/%D0%9A%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80%D1%8C-%D1%81-%D0%BF%D0%B5%D1%80%D0%B8%D0%BE%D0%B4%D0%BE%D0%BC?type=design&node-id=2-902&mode=design&t=6TdogmXvwNkiFdD4-0

</details>

2024-05-15 09:17 UTC, zhzz commented
По поводу CalendarDateShape и InternalDate отпишу тут, в одном месте.

У нас наблюдаются два пересекающийхся по функционалу механизма для работы с датами. Это CalendarDateShape и InternalDate. Я не в курсе всей истории и замыслов их создания. Но по косвенным признакам могу предположить следующее.

InternalDate - это внутренний подкапотный механизм. Он содержит кучу логики, о которой пользователю знать нет нужды. И вроде бы он нигде не торчит наружу.

CalendarDateShape - это публичный механизм. Он явным образом экспортируется из календаря. Он доступен пользователю и ограничен теми функциями, которые могут ему реально понадобиться для манипуляции с датами там, где строки не удобны. Например, для работы с периодами.

Поэтому предлагаю считать CalendarDateShape публичным API, описать его в доке и использовать в примерах только его. 

InternalDate лучше оставить только для внутренних нужд компонентов и, когда-нибудь, навести в нем порядок.

2024-05-15 09:17 UTC, zhzz commented
По поводу формата месяцев. 

Их тоже в компонентах наблюдается два: человеческий и нативный (начинающий отсчет с 0). До сих пор все даты, которые передавал или получал пользователь из контрола, мы старались предлагать исключительно в человеческом формате. Нативный же используется во внутрянке.

В этом ПР появляется еще одно место соприкосновения пользователя с датой. Это проп date в CalendaDay. Изначально я не сильно раздумывал и оставил его в нативном формате. Но после ревью и составления всей картины выше стала очевидна непоследовательность этого API для пользователя. 

В итоге, предлагаю CalendaDay, как публичный компонент, тоже перевести на человеческий формат. Это позволяет также избавиться от работы с форматами внутри CalendarDateShape.

2024-05-15 09:23 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDateShape.ts
> +  return create(date, getMonthInNativeFormat(month), year);
Переосознал, переделал и подрезюмировал ниже механизмы работы с датами и форматами.

2024-05-15 09:25 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +        .toA11YFormat()}`;
В итоге ariaLabel и так получался в человеческом формате благодаря второму аргументу в setComponents. 

Но в любом случае, я перевел CalendarDay целиком на работу с человеческим форматом.

2024-05-15 09:27 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDateShape.ts
> +};
Отписал ниже свои предложения по использованию CalendarDateShape и InternalDate

2024-05-15 09:33 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +        </button>
Глобальные классы у нас не для этого. Они не являются публичным API.

Подход с CalendarDay предполагает, что в данном случае, пользователь сможет сам добавить необходимой верстки и стилей. Все нужные пропы и контроль у него есть. И это не будет являться костылем.

2024-05-20 13:13 UTC, lossir commented on packages/react-ui/components/Calendar/CalendarDay.tsx
> +        .toA11YFormat()}`;
Да, тейк был именно в том, что приходится использовать второй аргумент, т.к. в пропах пользователь вынужден будет передавать нативный месяц.

2024-06-05 03:49 UTC, zhzz commented
Переделал `CalendarDay` на работу со строкой. 

Но публичные функции для сравнения дат уже нужны, т.к. без них выбор периода не сделать, а мы предлагаем такую возможность.

Тогда, чтобы не публичить старый `CalendarDateShape`, и также не публичить сложный `InternalDate`, предлагаю завести новый простой набор функций: `lib/date/comparision`. Под капотом у него пока старый механизм, но его легко можно будет перевести на новый, когда дойдут руки навести порядок.

2024-06-05 08:15 UTC, lossir reviewed
Согласен, что `CalendarDateShape` сейчас трогать не надо.

У нас сейчас такая ситуация, что разные общие хэлперы по работе с датами раскиданы по куче файлов:
1. `InternalDate`
2. `CalendarDateShape`
3. `CalendarUtils`
4. `DatePickerHelpers`
5. `comparison`

Некоторые хэлперы дублируются, некоторые перемешались со специфичными функциями для конкретных компонентов.

Думаю стоит это как-нибудь обсудить и завести задачу по наведению тут порядка.

2024-06-05 08:15 UTC, lossir commented on packages/react-ui/lib/date/__tests__/comparison.test.ts
> +});
Лучше использовать `test.each`, тогда при падении будет видно в каком конкретно случае проблема.
```ts
test.each([
  ['10.03.2018', '11.03.2017'], // тут специально ошибка
  ['10.03.2017', '10.04.2017'],
  ['10.03.2017', '10.03.2018'],
])('isLess returns true if "%s" is less than "%s"', (date1, date2) => {
  expect(isLess(date1, date2)).toBe(true);
});
```
| ![image](https://github.com/skbkontur/retail-ui/assets/2708211/c0a7c104-b6e3-472a-b036-1e74f97ce80e) |
| --- |

2024-06-05 10:25 UTC, zhzz commented
Все поправил

2024-06-05 10:37 UTC, lossir commented on packages/react-ui/components/Calendar/CalendarDay.md
> +    <table border='1' cellSpacing='0' cellPadding='8'>
Атрибут `border` тоже диприкейтед.

Можно вообще ничего не добавлять, по-моему смотрится хорошо
```html
<table> ...
```
| ![image](https://github.com/skbkontur/retail-ui/assets/2708211/730035dc-051d-4159-8515-d8e2be4710eb) |
| --- |

2024-06-05 10:39 UTC, lossir approved these changes

2024-06-05 10:46 UTC, merged

2024-06-05 10:51 UTC, zhzz commented on packages/react-ui/components/Calendar/CalendarDay.md
> +    <table border='1' cellSpacing='0' cellPadding='8'>
Тут не успел, докинул в [#3287](https://github.com/skbkontur/retail-ui/pull/3287/commits/a624a6862d9fa1c2f1031e3322c7733fa7e3a518).