chore(Popup, Hint, Tooltip): unify positioning
skbkontur/retail-ui pull request #3416
Opened 2024-04-26 08:58 UTC by SchwJ

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-05-02 08:27 UTC, zhzz requested changes

2024-05-02 08:27 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +      throw new Error('Unexpected position ' + pos_ + ' passed to Popup. Expected one of: ' + positions.join(', '));
Ранее обсуждали отказ от выбрасывания ошибок в пользу более мягких ворнингов.

2024-05-02 08:27 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +  private processPosAndPositions() {
Не очень говорящее название. Хотя метод делает вполне конкретную работу - возвращает позиции.

2024-05-02 12:38 UTC, zhzz reviewed
Я бы на всякий случай еще раз уточнил у дизайна правильные приоритетные позиции по умолчанию у Hint и Tooltip. А то в [Гайдах](https://guides.kontur.ru/components/popup-elements/tooltip/#17) написано другое, возможно их стоит обновить. 

В остальном вроде больше нет вопросов. Можно добавлять фиче-флаг.

2024-05-13 08:12 UTC, SchwJ commented
Фиче-флаг добавлен. 
Обсудила с дизайном правильные приоритетные позиции по умолчанию для Hint и Tooltip, реализация актуальна, а Гайды нужно обновить.

2024-05-15 12:12 UTC, zhzz requested changes

2024-05-15 12:12 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +    if (!this.featureFlags.popupUnifyPositioning) {
Старое и новое условия не равнозначны

2024-05-15 12:12 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +          positions={this.featureFlags.popupUnifyPositioning ? this.props.allowedPositions : this.getPositions()}
Если эту логику унести в getPositions, то станет проще

2024-05-15 12:12 UTC, zhzz commented on packages/react-ui/components/Hint/Hint.tsx
> +    const allowedPositions = this.props.allowedPositions ? this.props.allowedPositions : OldPositions;
Эта логика в коде полностью дублируется два раза. Можно ее унести в геттеры и станет намного чище.

2024-05-17 06:34 UTC, zhzz approved these changes

2024-05-17 06:56 UTC, merged