feat(Button, Link): add new prop - component
skbkontur/retail-ui pull request #3421
Opened 2024-05-14 07:33 UTC by Funkicide

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-07-10 10:11 UTC, zhzz requested changes
Типы таких пропов как  'onClick' остались прихардкожеными к старым корневым html-элеменами. Нужно это тоже поправить.

И как идея, я бы еще предложил попробовать ограничить тип пропа `component` тремя возможными кейсами: `button`, `a` и ComponentType. Это облегчит пользователю понимание как пользоваться пропом, убрав всякие сомнительные опции, типа `div` и все остальные. Плюс сузит зону ответсвенности Button и Link.

2024-07-25 08:22 UTC, Funkicide commented on packages/react-ui/components/Button/Button.tsx
> +    const Root = component as React.ElementType;
Забыл убрать. Убрал.

2024-07-25 08:22 UTC, Funkicide commented on packages/react-ui/components/Button/Button.tsx
> +    type: BUTTON_DEFAULT_ELEMENT,
Убрал.

2024-07-25 08:23 UTC, Funkicide commented on packages/react-ui/components/Button/Button.tsx
> +   * Если нужна кнопка, выглядящая как ссылка, используйте `Link component=button`.
Добавил ворнинг

2024-07-25 08:23 UTC, Funkicide commented on packages/react-ui/components/Button/Button.styles.ts
> +      &.${globalClasses.link} svg {
Сделал один стиль для всех случаев

2024-09-26 18:52 UTC, zhzz commented
Докинул [правок](https://github.com/skbkontur/retail-ui/pull/3421/files/4da47ece0846d90b9d45c9bca6175ea494fe4718..d9095be007d543886ac6d4a0cba500d08c61d4a4), которые подробно описал в новом ПРе #3521. Есть ломающие изменения, поэтому думаю стоит эту фичу выпустить только в 5.x. Новый ПР идет в него, а этот предлагаю закрыть.

2024-09-30 12:47 UTC, zhzz commented
Закрываем в пользу #3521.

2024-09-30 12:47 UTC, closed without merging