feat: update colors
skbkontur/retail-ui pull request #3447
Opened 2024-06-10 12:32 UTC by Funkicide

## Проблема

От дизайнеров пришли обновлённые цвета. И у некоторых контролов был неправильный цвет текста и/или иконок в `disabled` состоянии.
## Решение

Добавил переменные с обновленными цветами в отдельные темы, для того чтобы новые цвета могли использовать только те, кому они нужны.

## Ссылки

resolve [IF-1772](https://yt.skbkontur.ru/issue/IF-1772), [IF-1758](https://yt.skbkontur.ru/issue/IF-1758)
## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ✅ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ✅ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-06-14 07:48 UTC, lossir requested changes

2024-06-14 07:48 UTC, lossir commented on packages/react-ui/lib/theming/themes/Theme2022UpdatedColors.ts
> +export const THEME_2022_UPDATE_JUNE_2024 = ThemeFactory.create(
Думаю, месяц не стоит указывать.
Так будет достаточно — `THEME_2022_UPDATE_2024`.

Если вдруг подъедут ещё правки, то можно будет делать так:
`THEME_2022_UPDATE_2024_2`
`THEME_2022_UPDATE_2024_3`
...

---

И сами файлы тоже стоит так назвать — `Theme2022Update2024`

2024-06-14 07:48 UTC, lossir commented on packages/react-ui/lib/theming/themes/Theme2022DarkUpdatedColors.ts
> +    green: '23A14A',
Здесь потерялась решётка `#`
То же в переменных `btnDangerHoverBorderColor` и `btnDangerActiveBorderColor`.

2024-06-14 07:48 UTC, lossir commented on packages/react-ui/.storybook/preview.tsx
> +// import { THEME_2022_DARK } from '../lib/theming/themes/Theme2022Dark';
Стоит оставить комментарий c `//TODO` что мол надо всё вернуть в `5.0`

2024-06-14 07:48 UTC, lossir commented on packages/react-ui/.storybook/preview.tsx
> +import { THEME_2022_DARK_UPDATE_JUNE_2024 as THEME_2022_DARK } from '../lib/theming/themes/Theme2022DarkUpdatedColors';
Надо добавить эти темы в документацию в "Список существующих тем:"
https://tech.skbkontur.ru/react-ui/#/Customization/ThemeContext

И добавить их в выбор тем в левом верхнем углу.

2024-06-14 09:18 UTC, Funkicide commented on packages/react-ui/lib/theming/themes/Theme2022UpdatedColors.ts
> +export const THEME_2022_UPDATE_JUNE_2024 = ThemeFactory.create(
Сделал.

2024-06-14 09:18 UTC, Funkicide commented on packages/react-ui/lib/theming/themes/Theme2022DarkUpdatedColors.ts
> +    green: '23A14A',
Поправил.

2024-06-14 09:19 UTC, Funkicide commented on packages/react-ui/.storybook/preview.tsx
> +// import { THEME_2022_DARK } from '../lib/theming/themes/Theme2022Dark';
Оставил.

2024-06-14 09:19 UTC, Funkicide commented on packages/react-ui/.storybook/preview.tsx
> +import { THEME_2022_DARK_UPDATE_JUNE_2024 as THEME_2022_DARK } from '../lib/theming/themes/Theme2022DarkUpdatedColors';
Добавил.

2024-06-14 14:25 UTC, lossir requested changes

2024-06-14 14:25 UTC, lossir commented on packages/react-ui/lib/theming/ThemeContext.md
> +| `THEME_2022_UPDATE_2024`| Тёмная тема 2022 г. с последними обновлениями цветов. В `5.0` будет влита в дефолтную темную|
```suggestion
| `THEME_2022_DARK_UPDATE_2024`| Тёмная тема 2022 г. с последними обновлениями цветов. В `5.0` будет влита в дефолтную темную|
```

2024-06-14 14:25 UTC, lossir commented on packages/react-ui/.storybook/preview.tsx
> +// import { THEME_2022_DARK } from '../lib/theming/themes/Theme2022Dark';
Теперь тудушек слишком много)
Но т.к. ты буквально следующей задачей будешь выпиливать эти темы, то и так норм.

2024-06-14 14:25 UTC, lossir commented on packages/react-ui/.creevey/images/Input/Align/chrome2022.png
| было / стало |
| --- |
| ![image](https://github.com/skbkontur/retail-ui/assets/2708211/fff93917-3be3-4210-a3e6-7f837c5c670c) |

Для покраски иконки в Инпуте используется только переменная `inputIconColor`. Для состояния disabled нет отдельной переменной, поэтому теперь иконки всегда покрашены как выключенные.

Чтобы это избежать придётся добавить отдельную переменную для цвета иконки в выключенном состоянии.

2024-06-16 14:15 UTC, Funkicide commented on packages/react-ui/.creevey/images/Input/Align/chrome2022.png
Добавил переменную.

2024-06-16 14:16 UTC, Funkicide commented on packages/react-ui/lib/theming/ThemeContext.md
> +| `THEME_2022_UPDATE_2024`| Тёмная тема 2022 г. с последними обновлениями цветов. В `5.0` будет влита в дефолтную темную|
Поправил

2024-06-17 05:35 UTC, lossir approved these changes

2024-06-17 09:13 UTC, lossir approved these changes

2024-06-17 12:05 UTC, merged