IF-1780
skbkontur/retail-ui pull request #3451
Opened 2024-06-20 13:25 UTC by Eazymov

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-06-24 12:12 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.tsx
> +  'middle right',
middle- значения для использования в DateSelect

2024-06-24 12:15 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.styles.ts
> +    return css``;
Нужна ли в данном случае анимация? Пока используется только для DateSelect, который ранее анимацию не использовал.
Из вариантов анимации на ум приходит только scale(0.9 -> 1), но так ломается получение правильной позиции top.

2024-06-24 12:15 UTC, Eazymov commented on packages/react-ui/internal/Menu/Menu.tsx
> +  hasMargin?: boolean;
Добавил чтобы убирать лишний margin когда Menu рендерится в Popup.

2024-06-24 12:19 UTC, Eazymov commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +  .map((_, index) => defaultMinYear + index);
Стоит ли выносить в утилити функцию `range(start, end)`? Если да, то где её лучше разместить?

2024-06-24 12:31 UTC, Eazymov commented on packages/react-ui/components/Select/Select.tsx
> +  focusOnSelect?: boolean;
Добавил этот проп чтобы при выборе месяца/года в дейтпикере дейтпикер не закрывался из-за фокусировки Select.

2024-06-24 12:32 UTC, Eazymov commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +  scrollIntoView?: boolean;
Добавил этот проп чтобы дропдаун у DateSelect открывался на выбранном элементе.

2024-06-24 12:33 UTC, Eazymov commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> -    });
Посчитал два теста выше более не нужными из-за перехода на использование Select.

2024-06-24 12:34 UTC, Eazymov commented on packages/react-ui/components/DatePicker/DatePicker.styles.ts
> +      display: block;
`inline-block` некорректно отображается в Popup (внизу под выпадашкой дейтпикера появляется лишний отступ).
Что-нибудь может сломаться из-за этого изменения?

2024-06-26 12:06 UTC, zhzz commented
Обязательный прогон тестов на ветке 5.х не был включен. Включил его и стало видно, что падает много скриншотов. Также появились конфликты.

2024-07-02 07:17 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +  'middle right',
Норм, только нужно исключить middle-значения из [алгоритма автоматического выбора](https://github.com/skbkontur/retail-ui/blob/IF-1780/packages/react-ui/internal/Popup/Popup.tsx#L747) позиции. Немного подробней про него [тут](https://github.com/skbkontur/retail-ui/pull/3370).

2024-07-02 07:18 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.styles.ts
> +    return css``;
Думаю, она не обязательна. Можно проконсультироваться с дизайнером.

2024-07-02 07:27 UTC, zhzz commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +  .map((_, index) => defaultMinYear + index);
Если логика где-то повторяется, то стоит вынести. Если она полезна за пределами DateSelect, то можно положить куда-то в 'lib/'.

2024-07-02 08:25 UTC, zhzz commented on packages/react-ui/components/Select/Select.tsx
> +  focusOnSelect?: boolean;
Норм, только он сейчас сломал публичный метод `focus`, который по идее не должен учитывать этот проп.

https://github.com/skbkontur/retail-ui/blob/IF-1780/packages/react-ui/components/Select/Select.tsx#L309

2024-07-02 08:52 UTC, zhzz commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> -    });
А какие именно тесты нужнее? Они покрывают те же сценарии?

2024-07-02 08:59 UTC, zhzz commented on packages/react-ui/components/DatePicker/DatePicker.styles.ts
> +      display: block;
Пропадает отступ под кнопкой Today в 2022 теме.

![image](https://github.com/skbkontur/retail-ui/assets/4607770/e420b449-618a-4c25-aa13-85a94a94b206)

2024-07-02 09:44 UTC, zhzz commented
> У компонентов, которые ранее использовали DropdownContainer, есть пропсы `menuPos` & `menuAlign`. Так как текущие изменения мы наверное будем включать только в 5.0, стоит ли заменить все связки `menuPos` + `menuAlign` на один проп `pos`?

Обсудили в офлайне, что общий проп `pos` был бы уместен. Но подумав еще, мне кажется что имеет смысл оставить текущий `menuPos`, расширив его дополнительными значениями для выравнивания. Общий хелпер для этого можно положить куда-нибудь рядом с Menu.

2024-07-02 09:50 UTC, zhzz reviewed
Полезно будет добавить скриншотов на все компоненты, в которых появился режим disablePortal.

2024-07-03 15:23 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.tsx
> +  'middle right',
Исключил.

2024-07-03 15:30 UTC, Eazymov commented on packages/react-ui/internal/DateSelect/DateSelect.tsx
> +  .map((_, index) => defaultMinYear + index);
Не нашёл юзкейсов за пределами DateSelect

2024-07-03 15:38 UTC, Eazymov commented on packages/react-ui/components/Select/Select.tsx
> +  focusOnSelect?: boolean;
Проблема с блюром попапа при фокусе селекта пропала -_-
Убрал проп

2024-07-03 16:11 UTC, Eazymov commented
> > У компонентов, которые ранее использовали DropdownContainer, есть пропсы `menuPos` & `menuAlign`. Так как текущие изменения мы наверное будем включать только в 5.0, стоит ли заменить все связки `menuPos` + `menuAlign` на один проп `pos`?
> 
> Обсудили в офлайне, что общий проп `pos` был бы уместен. Но подумав еще, мне кажется что имеет смысл оставить текущий `menuPos`, расширив его дополнительными значениями для выравнивания. Общий хелпер для этого можно положить куда-нибудь рядом с Menu.

`menuPos` позволяет задать только одно возможное значение позиции выпадающего меню. Предлагаю сделать массив `positions` как у `Popup`.

2024-07-03 16:16 UTC, Eazymov commented on packages/react-ui/components/DatePicker/DatePicker.styles.ts
> +      display: block;
Исправил.

2024-07-03 16:32 UTC, Eazymov commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> -    });
В DateSelect рендер опций специфичный, зависит от скролла и выбранного значения. Данные тесты проверяют, что нужное значение в меню отображается. Поскольку перешли на использование Select, такая проверка, как мне кажется, не имеет смысла

2024-07-04 09:56 UTC, zhzz commented
> > Обсудили в офлайне, что общий проп `pos` был бы уместен. Но подумав еще, мне кажется что имеет смысл оставить текущий `menuPos`, расширив его дополнительными значениями для выравнивания. Общий хелпер для этого можно положить куда-нибудь рядом с Menu.
> 
> `menuPos` позволяет задать только одно возможное значение позиции выпадающего меню. Предлагаю сделать массив `positions` как у `Popup`.

Да, норм. Но название, кажется, будет уместнее тогда menuPositions.

2024-07-04 10:30 UTC, zhzz commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> -    });
Не совсем так. Эти тесты проверяют, что при выборе значения в DateSelect весь календарь проскролился до нужного месяца. Думаю этоти тест-кейсы остались валидными. Их даже полезно было бы гонять и на десктопной версии контрола, а не только на мобильной, как сейчас.

2024-07-05 10:53 UTC, Eazymov commented
Переименовал positions->menuPositions для Autocomplete, ComboBox, DatePicker, Dropdown, Select

2024-07-05 11:51 UTC, Eazymov commented on packages/react-ui/components/DatePicker/__tests__/DatePicker-test.tsx
> -    });
Вернул эти тесты. Так как связанная с ними логика теперь одинаковая на десктопе и мобилке, думаю дополнительные добавления не нужны.

2024-07-05 11:54 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.styles.ts
> +    return css``;
Спросил у дизайнера, анимация не нужна.

2024-07-12 07:45 UTC, zhzz commented
Пока есть пара комментариев, еще не все посмотрел:

1. Внешний вид DateSelect. Новая версия отличается от старой не только стрелочками, но и отступами. Если это согласовано с дизайнерами, я бы предложил сразу обновить все и в [макетах календаря](https://www.figma.com/design/87ScqxPzJpF9DcVBNYWOjM/%E2%9A%A1-Kontur-UI?node-id=200-979&t=g3bDEO5pg7HKjJe6-0). Но если что, Select позволяет настраивать свой рендер как угодно практически. 
2. Т.к. мы поменяли некоторые публичные пропы: `menuAlign` и `menuPos` стали `menuPosition`, то стоит сделать [кодмод](https://github.com/skbkontur/retail-ui/tree/next/packages/react-ui-codemod), чтобы пользователи могли автоматом переехать.

2024-07-14 12:00 UTC, zhzz commented
Есть момент с пропом Popup `maxWidth`.

По сути, сейчас значение `maxWidth` никак не влияет на ширину попапа. Он все равно рисуется во всю ширину своего контента. Если переданное значение `maxWidth` меньше ширины контента, то только тень попапа реагирует: она получается короче фона.

![image](https://github.com/user-attachments/assets/e7fd9570-f665-4490-bfb3-12874b1c6c74)

Судя по всему, раньше ширина контента тоже не реагировала на `maxWidth`. Скорей всего сломалось в каком-то из релизов. Но тень была адекватной.

![image](https://github.com/user-attachments/assets/b65113cc-e833-4a38-9235-dcd549cdce6e)

На картинках доработанная история Popup.SmallWidth: 
![image](https://github.com/user-attachments/assets/8ade1fdb-6ed8-4e89-8787-6ecf9af830da)


В идеале было бы круто починить и ширину и тень. Но как минимум тень нужно точно.

2024-07-15 05:34 UTC, zhzz commented
> Сейчас в tc валятся следующие тесты:

Для` Select: With Menu Align And Various Width` и `Tooltip: Tooltip with Input and switchable content в firefox`, думаю, должно помочь увеличение задержки перед снятием скриншота. Если не поможет, то можно просто добавить skip.

А для `Dropdown: Simple Dropdown в chrome2022Dark ` и `Tooltip: Tooltip with Input and switchable content в chrome2022Dark` можно сразу добавить skip.

2024-07-15 06:14 UTC, zhzz requested changes

2024-07-15 06:14 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +          </div>
Кажется, тут критичная проблема. Этот `div` с классом `relativeParent` иногда влияет на внешнюю верстку. Например, истории `hint--top-bottom-center` и `kebab--with-items-and-icons` отличаются в режиме `disablePortal` и без него. На Kebab нужно кликнуть, чтобы увидеть.

Думаю, такого нельзя допускать.

2024-07-16 10:17 UTC, Eazymov commented
> В идеале было бы круто починить и ширину и тень. Но как минимум тень нужно точно.

Починил ширину и тень.

2024-07-16 10:30 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.tsx
> +          </div>
Что я думаю по этому поводу:
1) Перенос рендеринга элемента в другое место это абсолютно всегда действие потенциально влияющее на расположение и отображение соседних элементов. Более того, в этом в некоторой степени и смысл пропа `disablePortal`. Более того, даже режим с порталом сейчас будет нарушать внешний вид точно так же как в случаях с твоими примерами, если на body будут навешаны определённые стили (типа `justify-content: space-between`), просто такого не происходит.
2) Обработка нового флоу элементов без портала это ответственность пользователя сознательно использующего проп `disablePortal`.
3) Исходя из написанного в пункте 1, возможности решения проблемы я не вижу.
4) Как я понимаю, эта проблема существует вне рамок этой задачи в случаях подобных твоим примерам, если бы в них использовался существующий сейчас `DropdownContainer`.

2024-07-17 09:59 UTC, zhzz commented on packages/react-ui/internal/Popup/Popup.tsx
> +          </div>
Согласен с мыслью, что мы не всегда можем гарантировать, что у пользователя при вставке выпадашки ничего не поедет. Но вероятности все-таки имеют значение. При вставке абсолютно спозиционированного элемента в `body` мы рискуем намного меньше, чем относительно спозиционированного элемента куда-то в произвольное место. Плюс, есть ситуации, когда все-таки можно снизить риск до 0.

Например, если присмотреться к реализации `disablePortal` в `DropdownContainer` и тем компонентам, 
где они раньше использовались, то можно отметить следующее:
1. DropdownContainer в режиме disablePortal вставлял элемент c `position: absolute`
2. Все компоненты его использующие имели свои обертки с `position: relative`
Так обеспечивалась стабильность поведения в режиме disablePortal и без него.

Но, в новых компнентах, где мы добавили `disablePortal`, в основном такой безопасной обертки нет. А в `Tooltip` и `Hint` ее вообще по дизайну быть не может. По этому стабильности в них добиться нельзя.

Также, думаю, что перекладывать ответственность за стабильность на пользователя - это тоже не совсем правильно. Проблема слишком вероятная и не такая очевидная, как допустим с `overflow: hidden`.  Мы вообще думали использовать `disablePortal` для всего принудительно внутри виджетов. А для этого стабильность критична.

В итоге, похоже, что так мы приходим к пониманию, что не все выпадашки могут работать в режиме `disablePortal`.  А значит `disablePortal` не может быть решением наших проблем их работоспособности в виджетах. 

Возможно тогда нам просто не стоит пытаться добавить `disablePortal` везде. Можно ограничиться только теми компонентами, где он уже был. Стабилизировать его там.  И выкинуть старый `DropdownContainer`. На этом задача будет завершена. 

А с виджетами поищем другое решение.

2024-07-22 14:30 UTC, Eazymov commented
Добавил кодмод.

2024-07-22 14:32 UTC, Eazymov commented on packages/react-ui/internal/Popup/Popup.tsx
> +          </div>
Оставил `disablePortal` только у тех компонентов, у которых он изначально был.

2024-07-23 09:42 UTC, zhzz requested changes
Unit-тесты все еще не все проходят.

2024-07-23 09:42 UTC, zhzz commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
По идее, тут должно быть `menuPositions={["top left", "bottom left"]}`, потому что вертикальная позиция должна выбираться динамически, если явно не задана. 

Увидив на примере этих тестов что в итоге получилось с пропами `menuPos` и `menuAlign`, я уже не уверен, что api компонентов стало лучше. 

1. Оно стало более громоздким. Что раньше задавалось одной строкой, стало массивом строк.
| Было  | Стало |
| ------------- | ------------- |
| `<ComboBox menuAlign="right" />`  | `<ComboBox menuPositions={["top right", "bottom right"]} />`  |
| `<ComboBox menuPos="bottom" />`  | `<ComboBox menuPositions={["bottom left"]} />`  |
| `<ComboBox menuPos="bottom" menuAlign="right" />`  | `<ComboBox menuPositions={["bottom right"]} />`  |

2. Стало нужным знать про необходимость передачи нескольких позиций, чтобы динимический выбор работал.
3. Все равно остался `TokenInput`, у которого нет `menuPositions`, но отстался `menuAlign`.

Возможно, я тогда дал плохой совет и оставить `menuPos` и `menuAlign` было бы лучше. Что думаешь?

2024-07-23 09:42 UTC, zhzz commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +  'bottom center',
Если оставлять menuPositions, то `'bottom center'` и `'top center'` наверное лишние?

2024-07-24 09:17 UTC, Eazymov commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
1. Я думаю так, что в случае выпадающих меню дуэт пропов `menuPos` и `menuAlign` точно лаконичнее, но `menuPositions` это более явное и однозначное решение, плюс это однообразно с остальными выпадашками. Используя только `menuAlign` я как пользователь могу не знать, что вертикальная позиция будет меняться в зависимости от положения, меня может это как устраивать, так и не устраивать. Перечисление всех позиций в `menuPositions` это чуть более громоздко, но убирает всю неоднозначность.
2. Исходя из новой сигнатуры пропа и того, что он копирует уже существующее поведение в других более новых выпадашках, знание о необходимости перечислить все доступные позиции кажется самоочевидным для разработчика.
3. У `TokenInput` уникальный проп `menuAlign` со значением `cursor`. Кажется, что это независимый случай.

2024-07-24 09:19 UTC, Eazymov commented on packages/react-ui/components/Autocomplete/Autocomplete.tsx
> +  'bottom center',
Убрал лишние значения.

2024-07-24 09:38 UTC, Eazymov commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
Кодмод исправил.

2024-07-25 10:31 UTC, zhzz commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
Думаю, в этой ситуации для ComboBox, Select и других дроп-листов важнее простота, чем единообразие с Hint и Tooltip. У этих двух групп выпадашек все таки разные сценарии. Для дроп-листов позиция выпадашки второстепенна, возможных позиций всего 4, и они полностью покрываются пропами menuPos и menuAlign. 

А у Hint и Tooltip по 12 возможных позиций, определенная логика их выбора, плюс простой способ указать приоритетную - проп pos. Позиционирование - одна из основных их функций, для них такое api оправдано.

Поэтому, я бы все-таки оставил как было. Можем привлечь еще кого-нибудь на третье мнение)

2024-07-25 11:24 UTC, Eazymov commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
Тогда возвращаем как было.

2024-07-26 12:55 UTC, Eazymov commented on packages/react-ui-codemod/react-ui-5.0/__tests__/useMenuPositions.test.ts
> +        <${name} menuPositions={["bottom left"]} />
Убрал все дефолтные значения `menuPos` и `menuAlign` из компонентов их использующих. Определение дефолтных значений перенёс в функцию `getMenuPositions`.
Сделал так, потому что мы не можем понять, получены ли значения пропов из `defaultProps` или от пользователя, а поэтому не можем определитить нужно ли нам значение, например, `['top left']` или всё-таки `['top left', 'bottom left']`.

2024-07-30 10:58 UTC, zhzz commented
Вопросы на обсуждение.

Критичное:
1. priority="PopupMenu". Нужно применить везде, где раньше был DropdownContainer.
2. DateSelect. Раньше элементы за пределами min/maxDate не выводились. Теперь они disabled.

Некритичное:
1. Нужен ли в PopupMenu disablePortal? Нигде не используется. Плюс истории на него.
4. DropdownMenuPositions экспортируется, но не используется.
5. Popup. NonPinnablePositions и PinnablePopupPositions стоит переименовать в PopupNonPinnablePositions  и PopupPinnablePositions для консистентности.
6. Тесты на getMenuPositions пригодились бы.

Рефакторинг на будущее:
1. Разобраться с hasShadow/hasMargin и Menu. Ощущение, что ни больше не нужны.
8. Сверить отступы у всех выпадашек с макетами. В коде много где встречается <Popup margin={parseInt(this.theme.menuOffsetY) - 1} />. Нужно ли это еще?

2024-08-04 13:05 UTC, Eazymov commented
Критичное:
1. Исправил
2. Ирл обсудили, что отображение всех элементов позволяет легко центровать выпадашку относительно caption, отображает выбранный год, если он вне пределов min/max, плюс смысла скрывать года вроде бы нет.

Некритичное:
1. Убрал
2. Убрал
3. Переименовал
4. Добавил тесты
5. `hasShadow` убрал, а вот удаление возможности убрать отступ портит визуал:
![image](https://github.com/user-attachments/assets/790a1676-0c53-46f1-924b-0f26aedfc126)

2024-08-16 09:12 UTC, zhzz approved these changes

2024-08-23 07:41 UTC, merged