feat(Link): replace border-bottom with text-decoration
skbkontur/retail-ui pull request #3462
Opened 2024-07-05 06:20 UTC by HelenaIsh

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ⬜ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-08-30 08:04 UTC, zhzz requested changes
Я отписался в задаче по поводу толщины подчеркивания. Нужно решить что с ним делать там. 

И еще появились конфликты скриншотов.

2024-08-30 08:04 UTC, zhzz commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +  btnDefaultBorderBottomColor: 'btnDefaultTextDecorationColor',
Все переменные вида `btn[Use]BorderBottomColor` не то же самое, что и `btnLinkTextDecorationColor`. Они нужны были в [старых темах](https://ui.gitlab-pages.kontur.host/docs/storybook/react-ui/master/?path=/story/button--playground-default&globals=theme:DEFAULT_THEME_8PX_OLD), где у кнопки нижний бордер отличался от остальных, а не для подчеркивания ссылок.

Поэтому привязывать *BorderBottomColor и *TextDecorationColor не нужно. Все *BorderBottomColor  вообще теперь можно удалить.

2024-09-19 08:39 UTC, Funkicide commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +  btnDefaultBorderBottomColor: 'btnDefaultTextDecorationColor',
Удалил в отдельном [ПР](https://github.com/skbkontur/retail-ui/pull/3462)

2024-09-20 07:05 UTC, zhzz approved these changes
👍

2024-09-20 07:06 UTC, merged