feat(ScrollContainer): forwardRef possibility
skbkontur/retail-ui pull request #3476
Opened 2024-07-27 14:20 UTC by n1qcode

## Проблема

У компонента `ScrollContainer` отсутствует возможность получения внешней ссылки и возможность получить доступ к элементу прокрутки `ScrollContainer` за его пределами.
Такая функциональность крайне полезна и в качестве яркого примера можно привести виртуализацию, а именно когда задействуется прокрутка внешнего документа, в частности когда необходимо назначить пользовательский родительский элемент прокрутки.

## Решение

Для решения проблемы был добавлен проп externalRef и создана обертка для возможности передать `ref` с помощью `forwardRef`.
Элемент прокрутки присваивается и `refInner` и `externalRef`, благодаря чему не нарушается обратная совместимость:
```
ref={el => {
              this.refInner(el);
              if (typeof this.props.externalRef === "function") {
                this.props.externalRef(el);
              } else if (this.props.externalRef) {
                this.props.externalRef.current = el;
              }
            }}
```

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-08-14 07:02 UTC, zhzz requested changes

2024-08-14 07:02 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  scrollRef?: React.MutableRefObject<HTMLDivElement | null>;
Лучше использовать тип `React.Ref`, чтобы поддержать [ref callback'и](https://react.dev/reference/react-dom/components/common#ref-callback).

2024-08-14 09:26 UTC, n1qcode commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  scrollRef?: React.MutableRefObject<HTMLDivElement | null>;
Хорошая идея. Только здесь больше подойдет тип `React.ForwardedRef`, т.к. `React.Ref` включает в себя `React.RefObject`, у которого поле `current` является `readonly`:

![image](https://github.com/user-attachments/assets/f20cf6c6-5871-4659-8e63-56489a9e5942)

2024-08-20 06:51 UTC, zhzz commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  scrollRef?: React.MutableRefObject<HTMLDivElement | null>;
Да, наверное ты прав. Но `React.ForwardedRef` появился только в `@types/react@16.14.0`, а мы еще пока заявляем поддержку react начиная с `16.9.0`. К тому же, в других компонентах тоже пока используется `React.Ref`, и стоит сохранить единообразие.

И эта проблемка с `readonly` пропадет, если перейти на `callChildRef` из моего соседнего комментария.

2024-08-20 08:07 UTC, n1qcode commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +  scrollRef?: React.MutableRefObject<HTMLDivElement | null>;
Согласен, спасибо за развернутый ответ.

2024-08-20 08:08 UTC, n1qcode commented on packages/react-ui/components/ScrollContainer/ScrollContainer.tsx
> +              }
О, супер, не заметил его, внес правки и переместил его в `refInner`.

2024-08-20 09:31 UTC, merged