feat(react-ui-codemod): add codemod for react-ui 5.0
skbkontur/retail-ui pull request #3477
Opened 2024-07-30 08:00 UTC by Funkicide

## Проблема
В (ПР)[https://github.com/skbkontur/retail-ui/pull/3459] удалены или заменены некоторые переменные в темах.

## Решение
Добавил кодмод для переименования переменных тем согласно таблице (ПР)[https://github.com/skbkontur/retail-ui/pull/3459]

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-08-09 19:27 UTC, lossir requested changes
Лучше отпочкуйся от ветки `5.x` и направь ПР в неё.
Тогда сможешь протестировать работу кодмода.

Также можно будет запушить заменённые переменные, немного поменять значения для наглядности, и посмотреть на скриншотные тесты.

2024-08-09 19:27 UTC, lossir commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +  pagingForwardLinkDisabledColor: 'linkDisabledColor',
Неправильный эквивалент. Так покрасятся все ссылки в приложении.

Но получается, чтобы теперь покрасить кнопку "Дальше" придётся оборачивать `Paging` в контекст, и задавать неочевидную переменную `linkDisabledColor`... это плохо.

Надо создать файл c перелинковкой переменных, на подобии `getAutocompleteTheme.ts` и т.п.

2024-08-09 19:27 UTC, lossir commented on packages/react-ui-codemod/README.md
> +Переименовывает переменные темы в соответствии с изменениями в [3459](https://github.com/skbkontur/retail-ui/pull/3459)
Надо добавить пример как запускать.

2024-08-14 10:21 UTC, Funkicide commented on packages/react-ui-codemod/README.md
> +Переименовывает переменные темы в соответствии с изменениями в [3459](https://github.com/skbkontur/retail-ui/pull/3459)
Добавил.

2024-08-14 10:21 UTC, Funkicide commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +}
Добавил.

2024-08-14 10:57 UTC, Funkicide commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +  pagingForwardLinkDisabledColor: 'linkDisabledColor',
Вернул в основном ПР переменную `pagingForwardLinkDisabledColor`.

2024-08-15 10:37 UTC, Funkicide commented on packages/react-ui-codemod/react-ui-5.0/renameThemeVars.ts
> +}
Сделал ветку от 5.х. Запушил изменённые переменные и прогнал [тесты](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_ScreenshotTests/35846525?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true). Тоже самое сделал на этой [ветке](https://tc.skbkontur.ru/buildConfiguration/FrontendInfrastructure_Packages_ReactUI_ScreenshotTests/35845928?expandPull+Request+Details=true&expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true). Плюс проверил вручную на тестовом файле.

2024-09-26 07:19 UTC, zhzz approved these changes

2024-09-26 07:20 UTC, merged