chore(Theming): remove deprecated vars
skbkontur/retail-ui pull request #3515
Opened 2024-09-23 09:13 UTC by Funkicide

## Проблема

## Решение

## Ссылки

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ⬜ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-09-23 12:03 UTC, zhzz requested changes

2024-09-23 12:03 UTC, zhzz commented on packages/react-ui/internal/themes/BasicLightTheme.ts
> +  public static btnDangerTextDecorationColor = '';
А зачем эти переменные?

2024-09-23 12:32 UTC, Funkicide commented on packages/react-ui/internal/themes/BasicLightTheme.ts
> +  public static btnDangerTextDecorationColor = '';
Криво мерж конфликт порешал, удалил.

2024-09-24 05:29 UTC, zhzz approved these changes

2024-09-24 05:31 UTC, merged