fix(ZIndex): change document to getRootNode
skbkontur/retail-ui pull request #3540
Opened 2024-11-12 05:34 UTC by SchwJ

## Проблема

При получении контекста через dom есть прямое обращение к `document`. 
Доступ к `document/window` должен быть через `global-object`, либо через html-элементы полученные через ref, иначе `Upgrade.setWindow()` не будет работать ожидаемо.

## Решение

Заменила 
```const noscript = document.querySelector(...); ```
на 
```
const root = element.getRootNode() as HTMLElement;
const noscript = root.querySelector(...);
```

## Ссылки

Задача [IF-1949](https://yt.skbkontur.ru/issue/IF-1949)

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-11-12 10:12 UTC, lossir requested changes

2024-11-12 10:12 UTC, lossir commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        const noscript = root.querySelector(`noscript[${PORTAL_INLET_ATTR}="${portalID}"]`);
Тут пара спорных моментов.

Ассертить здесь тип не стоит (я про оператор `as`).
Метод `getRootNode()` может вернуть узлы типов `Text` и `Comment`, у которых нет метода  `querySelector()`. 
Вот тут можно посмотреть что может вернуть `getRootNode()`
https://codepen.io/lossir/pen/dyxbGqN


Как следствие, использование `getRootNode()` тут не очень подходит. 
Компонент `ZIndex` использует данные, оставляемые компонентом `RenderContainer`, который использует Реакт порталы для рендера компонента за переделами текущего рута
```html
<body>
    <div id="root">                                  // тут всё приложение
      <noscript data-render-container-id="111" /> 
    </div>
    <div data-rendered-container-id="111" />     // а сюда портал вынес выпадашку
</body>
```
Если виджет будет рендериться на не прикреплённом элементе, или внутри теневого дома, то `getRootNode` вернёт не то, что ожидается.
На не прикреплённом узле вернётся самый верхний родитель, в теневом доме вернётся ShadowRoot.

Оба случая это реальные сценарии:
[IF-2005](https://yt.skbkontur.ru/issue/IF-2005) ⚡️Иконки. Возникает ошибка в не прикреплённых узлах
[IF-1655](https://yt.skbkontur.ru/issue/IF-1655) Работа в виджетах: нет поддержки shadow dom

---

Я бы хотел использовать `ownerDocument`. Но есть вероятность, что элемент будет создан например внутри iframe, а прикрепляться будет в родительском окне.

Предлагаю обсудить этот момент на летучке. Если что, применим `globalObject`, как предлагает Егор.

2024-11-13 05:17 UTC, SchwJ commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        const noscript = root.querySelector(`noscript[${PORTAL_INLET_ATTR}="${portalID}"]`);
Спасибо за подробный и понятный коммент!

12.11.2024 обсудили на летучке и решили сделать через `globalobject`

2024-11-15 05:17 UTC, zhzz commented
Давайте зафиналим и выкатим

2024-11-15 05:42 UTC, lossir approved these changes

2024-11-15 05:47 UTC, merged

2024-11-15 06:08 UTC, alexandersorokin commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        const noscript = root.querySelector(`noscript[${PORTAL_INLET_ATTR}="${portalID}"]`);
Пара комментариев:
1. element.ownerDocument не поможет для неприкрепленных элементов, если дерево будет аттачится в другой фрейм или в shadow dom.
2. globalObject вместо getRootNode не поможет shadow dom.

2024-11-15 06:11 UTC, zhzz commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        const noscript = root.querySelector(`noscript[${PORTAL_INLET_ATTR}="${portalID}"]`);
shadow dom мы пока тут не рассматриваем. Занимаемся им отдельно.

2024-11-15 06:18 UTC, alexandersorokin commented on packages/react-ui/internal/ZIndex/ZIndex.tsx
> +        const noscript = root.querySelector(`noscript[${PORTAL_INLET_ATTR}="${portalID}"]`);
> shadow dom мы пока тут не рассматриваем. Занимаемся им отдельно.


> Если виджет будет рендериться на не прикреплённом элементе, или внутри теневого дома, то getRootNode вернёт не то, что ожидается.
> На не прикреплённом узле вернётся самый верхний родитель, в теневом доме вернётся ShadowRoot.

Я скорее про то, что я не очень понял описанную мотивацию для замены одного решение на другое. Мне кажется, что оно не доказывает необходимость.



P.S. В любом случае лучше пока использовать `globalObject`. Например, чтобы не разводить зоопарк из разных решений.