fix(MenuItem): page jumps when opening `<MenuItem>` in `<Calendar>`
skbkontur/retail-ui pull request #3543
Opened 2024-11-14 08:04 UTC by sashachabin

## Проблема

При наличии скрола на странице выпадашка выбора месяца или года в календаре может вызывать скрол экрана

[DatePicker-—-React-UI.webm](https://github.com/user-attachments/assets/e02b5843-bb00-4ca3-91f5-069ceff3df83)

## Решение

- `Element.scrollIntoView` → `scrollYCenterIntoNearestScrollable`. Вместо скролла всех элементов, **включая Viewport** скролл теперь происходит только у  **ближайшего родителя** со скроллом
- Добавил описание к недокументированному пропу `scrollIntoView`

## Ссылки

- [Задача с багом](https://yt.skbkontur.ru/issue/IF-2044/)
- Предыдущий связанный PR https://github.com/skbkontur/retail-ui/pull/3451

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ⬜ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ✅ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ✅ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ⬜ нерелевантно

3. Изменения корректно типизированы
  ✅ без использования `any` (см. PR `2856`)
  ⬜ нерелевантно

4. Прочее
  ✅ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-11-14 08:15 UTC, sashachabin commented on packages/react-ui/lib/dom/scrollYIntoNearestScrollable.ts
> +      return scrollBottom;
Если `lib/*` не используется потребителями библиотеки, то, возможно, это лишнее — юзать `ScrollLogicalPosition`. Можем оставить только вариант с `'center'` (так и было). 

Название, правда, будет ещё более громоздким `scrollYCenterIntoNearestScrollable`

2024-11-15 11:07 UTC, Funkicide commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +   * Скроллить ближайшего прокручивемого родителя до данного пункта меню
🐊 тут опечатка в "прокручиваемого".

2024-11-15 11:39 UTC, sashachabin commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +   * Скроллить ближайшего прокручивемого родителя до данного пункта меню
спасибо!

полечил и пошёл настраивать себе спелчекер 🐊🐊🐊🐊

2024-11-18 04:21 UTC, mshatikhin commented on packages/react-ui/lib/dom/scrollYCenterIntoNearestScrollable.ts
> +export function scrollYCenterIntoNearestScrollable(element: HTMLElement) {
получится написать тесты на эти функции? 
я боюсь словить регресса на ветке с shadowdom

2024-11-19 05:58 UTC, sashachabin commented on packages/react-ui/lib/dom/scrollYCenterIntoNearestScrollable.ts
> +export function scrollYCenterIntoNearestScrollable(element: HTMLElement) {
А смотри, у нас есть скриншотный тест о том, что селект с выбором месяца/года открывается всегда по центру (под мышкой):
https://github.com/skbkontur/retail-ui/blob/next/packages/react-ui/.creevey/images/Calendar/Calendar%20with%20min%20max%20date/DateSelect%20years/chrome2022/DateSelect%20years.png

Или думаешь про unit-тест?

2024-11-21 08:14 UTC, zhzz requested changes
Как временное быстрое решение можно влить. Но потом действительно стоит переделать. Это ответственность Menu скролить к выбранному элементу и в нем уже есть механизм для этого. Останется только его правильно применить.

2024-11-21 18:35 UTC, sashachabin commented on packages/react-ui/lib/dom/scrollYCenterIntoNearestScrollable.ts
> +export function scrollYCenterIntoNearestScrollable(element: HTMLElement) {
Я добавил `lib/dom/getParentOrShadowHost.ts` и тесты к нему — для DOM и ShadowDOM.

Текущую фичу не удается протестить юнит-тестами — у jsdom не scrollTo, но для неё есть скриншотные.

2024-11-21 18:36 UTC, sashachabin commented on packages/react-ui/lib/dom/scrollYCenterIntoNearestScrollable.ts
> +export function scrollYCenterIntoNearestScrollable(element: HTMLElement) {
Добавил функцию `lib/dom/getParentOrShadowHost.ts` и тесты к ней

2024-11-21 18:40 UTC, sashachabin commented on packages/react-ui/lib/dom/scrollYCenterIntoNearestScrollable.ts
> +  return element.ownerDocument.documentElement;
👍

Заменил window.getComputedStyle и получение window.document на globalObject

2024-11-21 18:40 UTC, sashachabin commented on packages/react-ui/components/MenuItem/MenuItem.tsx
> +   */
Заигнорировал

2024-11-22 10:30 UTC, zhzz approved these changes
👍

2024-11-22 10:34 UTC, merged

2024-11-25 07:51 UTC, sashachabin commented
> Как временное быстрое решение можно влить. Но потом действительно стоит переделать. Это ответственность Menu скролить к выбранному элементу и в нем уже есть механизм для этого. Останется только его правильно применить.

Добавил в задачу:
https://yt.skbkontur.ru/issue/IF-2061/