fix(Calendar, DatePicker): onClick on disabled dates
skbkontur/retail-ui pull request #3564
Opened 2024-12-16 17:09 UTC by Funkicide

## Проблема

## Решение

## Ссылки
fix 

## Чек-лист перед запросом ревью

1. Добавлены тесты на все изменения
  ✅ unit-тесты для логики
  ⬜ скриншоты для верстки и кросс-браузерности
  ⬜ нерелевантно

2. Добавлена (обновлена) документация
  ⬜ styleguidist для пропов и примеров использования компонентов
  ⬜ jsdoc для утилит и хелперов
  ⬜ комментарии для неочевидных мест в коде
  ⬜ прочие инструкции (`README.md`, `contributing.md` и др.)
  ✅ нерелевантно

3. Изменения корректно типизированы
  ⬜ без использования `any` (см. PR `2856`)
  ✅ нерелевантно

4. Прочее
  ⬜ все тесты и линтеры на CI проходят
  ✅ в коде нет лишних изменений
  ✅ заголовок PR кратко и доступно отражает суть изменений (он попадет в changelog)

2024-12-17 10:48 UTC, sashachabin commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const date = '03.11.2021';
А давай назовём `initialDate` и `const expectedDate = '06.11.2021'`

2024-12-17 10:52 UTC, sashachabin commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const button = screen.getByRole('button', {
А этот день можем назвать `expectedDay` или `outOfRangeDay`

2024-12-17 11:14 UTC, Funkicide commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const date = '03.11.2021';
Справедливо, поправил.

2024-12-17 11:14 UTC, Funkicide commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const button = screen.getByRole('button', {
Переименовал.

2024-12-18 02:00 UTC, sashachabin commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const button = screen.getByRole('button', {
Почти-почти)
Предлагаю такой вариант:
`const expectedDate = '06.11.2021';`
`const button` → `const outOfRangeDay`

2024-12-18 06:15 UTC, Funkicide commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    const button = screen.getByRole('button', {
Готово.)

2024-12-18 07:25 UTC, sashachabin approved these changes

2024-12-18 14:28 UTC, zhzz requested changes

2024-12-18 14:28 UTC, zhzz commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    expect(onValueChange).not.toHaveBeenCalled();
Если убрать сделанную правку с isDisabled, то тест все равно проходит. То есть он не работает. Кажется дето в том, что кнопка дизейблится и работает как надо, но в реальности клик происходит и слушается не на самой кнопке, а на ее родителе.

2024-12-18 16:15 UTC, Funkicide commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    expect(onValueChange).not.toHaveBeenCalled();
Поправил тест.

2024-12-19 06:16 UTC, zhzz commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    expect(onValueChange).not.toHaveBeenCalled();
Да, так заработало. Но кликать по кнопке кажется все же надежнее. 

Вообще, это все сломалось как раз когда я перенес обработчик клика на родителя, во время добавления пропа renderDay. Думаю лучше вернуть как было. Просто это немного сложнее реализовать: нужно клонировать итоговый день, пробрасывать туда обработчик и не потерять пользовательский обработчик, который тоже мог быть прокинут.

Сделал все это и добавил нужный тест.

2024-12-19 07:20 UTC, Funkicide commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    expect(onValueChange).not.toHaveBeenCalled();
Мелочь, но можно, наверное, ещё сразу в onClick итогового дня прокидывать `onDateClick`, без обёртки `handleClick`.

2024-12-19 10:57 UTC, zhzz commented on packages/react-ui/components/Calendar/__tests__/DayCellView.test.tsx
> +    expect(onValueChange).not.toHaveBeenCalled();
Сделал. Еще за оптимизировал количество ререндеров, а то скриншот в ФФ стал даже нестабильным.

2024-12-19 13:53 UTC, merged